### ISSUE TITLE
audible.co.uk

### ISSUE THREAD

**Issue by cyberdrizzt** [openaudible/openaudible#1]
Logging in to audible.com works just fine but as there is no option to select audible.co.uk or any other audible location the login fails on anything other than audible.com

**Comment by openaudible** [comment]
Added support for UK to master branch. Are there any other regions?

https://github.com/openaudible/openaudible/commit/3385ab70541686101028f87f303347ceb7d6d3be
If able, someone please test. I do not have a UK audible account.

Will post in next binary release.

**Comment by cyberdrizzt** [comment]
Thanks for adding UK support I'll try and test it soon as I can set up a build

I checked the Windows 10 App and it shows a list of the other regions.

audible.de, audible.fr, audible.com.au, audible.it, audible.jp, audible.ca

Germany, France, Australia, Italy, Japan and Canada

**Comment by cyberdrizzt** [comment]
Hi, I have built the source to the best of my ability ( I have very little knowledge of java )
It runs OK and I can select UK as my region, which logs in fine, but it cannot fetch the decryption key

Unable to get key
Error:com.gargoylesoftware.htmlunit.failinghttpstatuscodeexeception:404 no found for http://www.audible.co.uk/mn/404

I am not sure if this is a problem with my build or not, I will gladly test a windows release if you could supply one, thanks!

**Comment by openaudible** [comment]
You might try audible activator to get your decryption key:
https://github.com/inAudible-NG/audible-activator
Thanks for the other domains.

**Comment by openaudible** [comment]
We fixed the key capture logic. But haven't tested UK region, so let us know.

**Comment by cyberdrizzt** [comment]
Great update, I have tried again but connecting to Audible.co.uk seems to work just fine but the library does not update ( it shows no audiobooks ) not sure if this is a problem my end or not, maybe need to see if anyone else on co.uk can also test

**Comment by openaudible** [comment]
The audible scraping hasn't been tested. There is a new console window that might shed light. Open the "Browser" from the control menu and log in.. keep the browser window open..then try logging in. It should attempt to load https://audible.co.uk/lib (which should show your list of books.)

**Comment by cyberdrizzt** [comment]
It does indeed seem to go to /lib but nothing showing ( i can access my library from the inbuilt browser OK ) here is a section of the console log.

INFO: pageLoaded:https://www.audible.co.uk/lib?ref_=a_lib_lib_tnaft_1 My Library | Audible.co.uk
Jan 26, 2018 7:03:39 PM org.openaudible.audible.AudibleScraper _fetchLibrary
INFO: Getting page 1 of audible library...
Jan 26, 2018 7:03:39 PM org.openaudible.audible.AudibleScraper getLibraryFragment
INFO: get Library Page:1 took 70 ms. to complete.
Jan 26, 2018 7:03:39 PM org.openaudible.Audible updateLibrary
INFO: Updated 0 books

I'll try OpenAudible on another PC and let you know if it's the same there
