### ISSUE TITLE
Unable to connect via audible.ca

### ISSUE THREAD

**Issue by docrockulus** [openaudible/openaudible#100]
Seems to be the identical issue to #55 

`SEVERE: connectTask failed to log in: org.openaudible.audible.AudibleLoginError: Not logged in:AudiblePage:https://www.audible.ca/lib 985991`

I note that there is no software verification option on my account settings. Despite this, I am able to download .aax files as I expect.

**Comment by openaudible** [comment]
If you can, restart openaudible. Click "connect". If the browser shows you are logged in, but OpenAudible doesn't show you logged in, do a "Help: Send Bug Report" and mention Issue #100.

For the record: We don't send any cookies or other preference information-- just what is in your openAudible "tmp" directory and your list of books.json. We do not attempt to log in with your credentials... we just look at the .html files that we have attempted to parse to determine if you are logged in. After each new release (or sooner) we delete all bug reports that are closed or are not needed for debugging.

As long as the "Download" book option goes, yes, that seems to be a regional thing that we don't fully understand because we don't have test accounts in every region. But glad you can still manually click the download button. I think you can also manually go through each page of your library to fill in books.

**Comment by docrockulus** [comment]
That is the exact behavior as I'm experiencing, I'll send off a report as soon as I'm back by my machine.

**Comment by ndevries84** [comment]
I am having the exact same issue, and did forward off the report as well

**Comment by openaudible** [comment]
I have one bug report marked as Issue #100. But it does not have any .html files in the "tmp" (temp) directory. There should be a few *.html files that show the attempt to read your audible.ca/lib directory. Downloading may require you to be "Connected".

Can you open the File:console, select a single book to download, Action: Download and copy/paste the console

**Comment by ndevries84** [comment]
I believe this is what you are requesting.

Mar 12, 2019 8:00:35 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 1.4.3 for cocoa swt 4623 jvm 1.8.0_192
Mar 12, 2019 8:00:36 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 1.4.3
Mar 12, 2019 8:00:37 PM org.openaudible.Audible checkLibrary
INFO: bl=12, gl=12
Mar 12, 2019 8:00:37 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: /Applications/OpenAudible.app/Contents/java/app/bin/mac/ffmpeg -version 
Mar 12, 2019 8:00:37 PM org.openaudible.desktop.swt.manager.AudibleGUI checkFFMPEG
INFO: using ffmpeg version N-89585-g5533cbf-tessus Copyright (c) 2000-2017 the FFmpeg developers
built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
libavutil      56.  6.100 / 56.  6.100
libavcodec     58.  8.100 / 58.  8.100
libavformat    58.  3.100 / 58.  3.100
libavdevice    58.  0.100 / 58.  0.100
libavfilter     7.  7.100 /  7.  7.100
libswscale      5.  0.101 /  5.  0.101
libswresample   3.  0.101 /  3.  0.101
libpostproc    55.  0.100 / 55.  0.100

Mar 12, 2019 8:00:41 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
Mar 12, 2019 8:00:42 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Mar 12, 2019 8:01:10 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Connect
Mar 12, 2019 8:01:17 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=100 total=100}
Mar 12, 2019 8:01:18 PM org.openaudible.audible.AudibleConnectionState setRegion
INFO: Setting audible region to CA
Mar 12, 2019 8:01:19 PM org.openaudible.Audible importFromDownloadLink
INFO: Clicked download link for 
Mar 12, 2019 8:01:19 PM org.openaudible.Audible takeBook
WARNING: invalid book: required:fullTitle missing from 
Mar 12, 2019 8:01:19 PM org.openaudible.Audible importFromDownloadLink
INFO: Book not known... Adding: null
Mar 12, 2019 8:01:19 PM org.openaudible.Audible importFromDownloadLink
INFO: Unable to download: null

**Comment by openaudible** [comment]
I saw one bug report with the 100 label, similar to the above.
It looks like it isn't connecting-- or is going from connected to disconnected. I'll have to add more debugging code to determine why a book you click on doesn't have a title. I am relaxing that restriction about requiring a full title to download a book. I assume it is a regional difference. Stay tuned for the next release. No idea when that will be.

**Comment by kevininspace** [comment]
Same issue here. Looking at the AudibleScraper code in the CheckLogin, it seems like looking for "/signout" and/or "/account-details" may no longer work. I've noticed that in particular that the source code of my account page now has the sign out page href equal to "https://www.amazon.ca/ap/signin?openid.return_to=https%3A%2F%2Fwww.audible.ca%2F&openid.identity" ...etc

**Comment by openaudible** [comment]
OK. Try vers 1.4.4 or higher and submit a bug report from the tools menu if you see it happening. We added new code to include more .html files on the bug reporter so we can see what's going on.

**Comment by kevininspace** [comment]
This was in 1.4.4. Will submit new bug report.

**Comment by openaudible** [comment]
Hey @kevininspace that was the problem... your (ca) region uses an href with "signin" as a link to sign out.. so our software was confused. Should be fixed in 1.4.5. Let us know.
