### ISSUE TITLE
Feature request: Set filename manually

### ISSUE THREAD

**Issue by GloomPanther** [openaudible/openaudible#1005]
Hi together,

I think it will be a nice feature, if you can define your own filename with variables.
For example: "%artist% - %album% - %title%"
Maybe with a folder option like backslash. At the moment it is very difficult to find out the artist name in filenames. 

Thanks

**Comment by openaudible** [comment]
We are working on this.. Unfortunately the whole application was built on a more simple file naming strategy and we have to be careful about doing this correctly. 
We close all feature requests by default, and work on them as best we can without making too many promises about timeline.
