### ISSUE TITLE
Feature Request included titles

### ISSUE THREAD

**Issue by kris711** [openaudible/openaudible#1007]
Not purchased titles which are included in the subscription cant be downloaded at the moment.
Please make it happen 👍

**Comment by rnbwpnt** [comment]
Audible doesn't allow downloads of Plus titles. This is an Audible-level limitation.

**Comment by openaudible** [comment]
We are starting to add support for included titles, starting with the latest beta. You can take a look. (You'll need to enable "Included titles" in the preferences.) https://openaudible.org/beta

**Comment by kris711** [comment]
Great job, but unfortunatelly I cant enable the tick box (it will be reset to initial by clicking OK in settings dialog).

**Comment by openaudible** [comment]
Try again beta 2. Forgot to get and set the new prefs.

**Comment by kris711** [comment]
works like a charm. Thank you!

**Comment by openaudible** [comment]
Added in final version 3.6.
