### ISSUE TITLE
Cover Images Repeatedly Downloaded

### ISSUE THREAD

**Issue by rnbwpnt** [openaudible/openaudible#1008]
Apple M1, Monterey 12.5.1, OpenAudible 3.5.9

I have a OA library with over 14,000 titles, and an Audible library of over 10,000 titles.

**OBSERVED BEHAVIOR**
Every time I do a quick library sync, OA re-downloads covers for just over 2000 titles. This is consistent and has happened over a number of versions.

It appears that OA isn't finding the files on Audible (which, since I have thousands of non-Audible books in my library, would be normal). Each console entry of attempting a download ends thusly:

Output #0, image2, to '/Users/$USERNAME/Library/OpenAudible/tmp/1661373467743.jpg':
Output file #0 does not contain any stream

Vidcaps and console copies are available by email upon request.

**DESIRED BEHAVIOR**
I would prefer it if OA would attempt to download a cover once or twice, and then mark failures to not repeat them unless instructed to do so manually.

Insight welcome.

**Comment by openaudible** [comment]
Hmm. Do your non-audible titles have amazon product ID's and ASINs?

**Comment by openaudible** [comment]
For a first pass, I've added a check for ASIN and product ID.. and if the image download has failed, it won't attempt again... but will once you quit and restart OpenAudible. This is in development, so will post a beta with this update later.

**Comment by rnbwpnt** [comment]
From a spot check, it looks like no, these items do not have AISNs or SKUs.

**Comment by openaudible** [comment]
Give the beta a try if you want. Should be fixed in the beta. 
https://openaudible.org/beta
