### ISSUE TITLE
Error converting

### ISSUE THREAD

**Issue by mmaroma** [openaudible/openaudible#1009]
I have tried to download Th eBlack Ink Heart several times and it will not download or split the chapters and there are loads of chapters missing
  }
 },
 "error": {
  "result": 1,
  "cmd": "C:\\Users\\0107827s\\AppData\\Local\\OpenAudible\\bin\\win\\ffmpeg.exe -activation_bytes 08623812 -i \"C:\\Users\\0107827s\\OpenAudible\\aax\\The Ink Black Heart.AAX\" -i \"C:\\Users\\0107827s\\OpenAudible\\tmp\\The Ink Black Heart.AAX.txt\" -map_metadata 1 -map_chapters 1 -map_metadata 0 -metadata:s:v \"title=Album cover\" -metadata:s:v \"comment=Cover (front)\" -codec:a libmp3lame -qscale:a 4 -id3v2_version 3 C:\\Users\\0107827s\\OpenAudible\\tmp\\BK_TWUK_003310UK_temp.mp3 ",
  "stderr": ["0UK_temp.mp3: No space left on device, ...video:543kB audio:1026878kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown, Conversion failed!"]
 }
}
Sep 01, 2022 10:26:56 A.M. org.openaudible.util.queues.ThreadedQueue jobError
INFO: ConvertQueue error processing convert The Ink Black Heart item The Ink Black Heart
java.io.IOException: Failed to convert C:\Users\0107827s\OpenAudible\aax\The Ink Black Heart.AAX. Check console for details.
	at org.openaudible.convert.ConvertJob.convertFile(ConvertJob.java:452)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:635)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:711)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:516)

Sep 01, 2022 10:26:56 A.M. org.openaudible.Audible jobCompleted
INFO: ConvertQueue completed:The Ink Black Heart ConvertQueue size:0 remain:0 success:0 fail:3 threads:1
Sep 01, 2022 10:26:58 A.M. org.openaudible.desktop.swt.manager.AudibleGUI _checkAutomation
INFO: Start auto conversion:1
Sep 01, 2022 10:28:19 A.M. org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by openaudible** [comment]
Buried in the log above, you'll see the reason: No space left on device
I think we just improved that error message for the next version. 
Free up some disk space and you'll be back in business.
