### ISSUE TITLE
Date formats (DE)

### ISSUE THREAD

**Issue by christgod** [openaudible/openaudible#101]
Hi,
I'm still having problems with the sorting of titles, month and day get switched sometimes.
It seems the recognition is working for each date independently, and obviously this only works when the day is >12.
Example:
![image](https://user-images.githubusercontent.com/5426008/53315849-a5082d00-38c5-11e9-9b33-5a5839e79506.png)
results in day/month being switched for "Schändung" (2019 Sept 2 recognized - obviously that's not correct) while "Erlösung" is recognized correctly (probably because the day is >12).
![image](https://user-images.githubusercontent.com/5426008/53315915-e698d800-38c5-11e9-87e5-6ed1da57552c.png)

But this is only a minor and local issue, otherwise the program is working great for me!

**Comment by openaudible** [comment]
Thank you for that report. I will attempt to fix it... we don't have test accounts for each region, so a lot of this is trial and error and hearing from our users. And we've seen dates both 5.10.2019 and 10.5.2019 -- so we can't assume dates using the dot separator is for sure one format.. 

But.. if you are only seeing 13.02.2019 (day.month.year) in the library view, perhaps it is a simple fix.

**Comment by BlockLabTV** [comment]
I don't know if this is related to the bug, but I just noticed that the dates shown to me in openaudible seem to have many differences with the dates shown on the official website (If I'm not completely confused, screens attached below). I'm from germany too. Maybe this has also do something with the "region: US", but I don't know how to change this.

![audible_bug_fertig](https://user-images.githubusercontent.com/29959150/53375223-f282a980-395a-11e9-83e6-7c3e828d018c.png)

**Comment by christgod** [comment]
The dates in Germany are always in day.month.year format, so this could be solved by a region setting.
Otherwise you'd have to take the entire list of dates and check if any months are >13 or something like that.

**Comment by openaudible** [comment]
Hopefully fixed in 1.4.4.  I added new code to create more temp .html files when the app is running so if you get a similar bug, you can send a bug report from the Help menu and we can assist.

**Comment by kai-uwe-rommel** [comment]
I still see the same problem in 1.5.2.
