### ISSUE TITLE
Receiving "Error Converting: ffprobe error"

### ISSUE THREAD

**Issue by JSJarvis** [openaudible/openaudible#1010]
After downloading a set of AAX files this afternoon, I started receiving an error when converting the files to M4B. The error is "error converting: ffprobe error". I have not seen this error before. I received this same error on 2 different Macs.

**Comment by openaudible** [comment]
Did you download them using OpenAudible? Make sure you have enough disk space. You can send a bug report from the application (Help/About menu) and specify issue 1010.

**Comment by openaudible** [comment]
Probably a rare occurrence. Try again and feel free to post the full error from the log or submit a bug report.
