### ISSUE TITLE
Can't connect to Audible

### ISSUE THREAD

**Issue by bluedolphin0502** [openaudible/openaudible#1011]
When I try to connect to Audible, I either get the whole dialogue box disappear or I get a message like 'Oops, this page...'.
Can you help please?

I have done the update to the app and have also tried closing and reopening.

**Comment by openaudible** [comment]
Restart latest version, connect to audible, double check your user name and password, enter it once, then enter it again with the captcha.. then it should get you logged in.. unless you're on a flaky version of linux that might be crashing with the captcha. 
Feel free to send a bug report after trying the steps above from the Help menu.
