### ISSUE TITLE
End of MP3 Audio Books Not Playing on iPod Playing After Time Shows Zero Time Left

### ISSUE THREAD

**Issue by faceb17** [openaudible/openaudible#1012]
I regularly convert AAX files to mp3, add them to iTunes and then sync them to my 1st gen iPod nano.  The last several minutes of every book or book part are cut off, dropped, or don’t play on my iPod.  I can go back to the audio book on my MacBook Pro and play the remainder of the book but what’s interesting is that the countdown time reads as zero even though the book is still playing.  This usually happens for several minutes but there appears to be some variation in the amount of time.  I realize I’m using an older iPod but it is my favorite to use for certain things.  I’m using OpenAudible on a 2010 MacBook Pro and 2009 iMac 27 inch both running High Sierra.  I also noticed the same issue when running Sierra.  Thanks Jeff

**Comment by openaudible** [comment]
Which Mac/windows app reproduces the countdown says zero issue?  (Itunes, VLC, ?)
sounds like the iPod isn’t handling the variable bitrate encoding. 
of course try m4b format (best format for audiobooks) 

I haven’t seen any error reports like yours in a while but found #648 .. which looks the same. Marked as a feature request and might be able to take another look. Will reply here if I can update the code for constant rate encoding.

**Comment by faceb17** [comment]
iTunes version 12.8.3.1. On both Macs. The 1st Gen Nano supports the following formats according to MacTracker.  AAC, MP3, MP3 VBR, Audible, Apple Lossless, AIFF, WAV.  And yes issue 648 does sound the same.  ThanksJeffOn Sep 7, 2022, at 11:13 AM, openaudible ***@***.***> wrote:Which Mac/windows app reproduces the countdown says zero issue?  (Itunes, VLC, ?)
sounds like the iPod isn’t handling the variable bitrate encoding.
of course try m4b format (best format for audiobooks)I haven’t seen any error reports like yours in a while but found #648 .. which looks the same. Marked as a feature request and might be able to take another look. Will reply here if I can update the code for constant rate encoding.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by openaudible** [comment]
It does look like adding support for CBR might make sense. I'm not totally sure why we defaulted to VBR, which definitely adds more complexity to determining how many seconds remain on an audiobook. I think mostly we wanted to keep the number of options minimal.

Will look into adding support in next beta.. but you would need to re-encode all of your mp3 files.

**Comment by faceb17** [comment]
Thanks for the update and re-encoding isn’t a problem.  I appreciate you doing this.

Thanks
Jeff

**Comment by openaudible** [comment]
Ok.. Try the beta. Under prefs, check the CBR checkbox. Then re-encode one or more MP3's.
https://openaudible.org/beta
Let us know.

**Comment by faceb17** [comment]
Ok, it appears to have fixed the issue in iTunes and on my iPod Nano 1st Gen.  Although the Nano rebooted several time before it played the file.  Which is interesting.  It did notice and it makes sense to me now the the file size is considerable larger than when using variable encoding.  I’ll have to experiment with the encoding quality. I know if I set it a certain way the files won’t play on the iPod.  

Thanks and thanks for fixing this so quickly!  
Jeff

**Comment by openaudible** [comment]
Yeah, we had a 0-9 scale for variable bitrate. I need to decide the mapping between that and the available bitrates. currently 4=160kbps which is probably too high a value for an audiobook, especially for the "recommended setting". Will adjust it down and/or just put in a list of available bitrates. Maybe constant bitrate should be the default. I haven't explored whether vbr creates a better (smaller) audiofile than cbr.

**Comment by openaudible** [comment]
Will update the bitrate and make it more clear what the settings mean.

**Comment by faceb17** [comment]
Thanks for the update and thanks for fixing this issue so quickly!
