### ISSUE TITLE
[BUG] Can't download/convert free audiobooks

### ISSUE THREAD

**Issue by 3Domse3** [openaudible/openaudible#1014]
I use the latest release of OA (paid version), but when I try to download and convert audiobooks I added for free to my library, I only get "**Error downloading: JSONObject["content_url"] not found**" as an error message.

**Comment by openaudible** [comment]
That error suggests there is no download URL available for the book. Maybe it has been removed.
Are you using the latest beta? https://openaudible.org/beta

**Comment by openaudible** [comment]
Feel free to submit a bug report from About menu.
