### ISSUE TITLE
Application name misleading (ClosedAudible)

### ISSUE THREAD

**Issue by crztnt** [openaudible/openaudible#1015]
The application is called OpenAudible but actually OpenAudible is currently not open source. You may should consider changing the name into ClosedAudible or AbsolutelyProprietaryAudible.

**Comment by openaudible** [comment]
Open has several meanings. Not helpful to get a github account just to complain about something not being free. Lots of options out there.

**Comment by Alexander-Metzger** [comment]
> Open has several meanings. Not helpful to get a github account just to complain about something not being free. Lots of options out there.
You should know what associations “Open” has in software. Can you guess what OpenBSD, OpenSUSE and OpenOffice all have in common? We all know why the program was called OpenAudible in the past, but the name has lost its meaning entirely. And nobody complained about things not being gratis. The User complained about not having access to the source code, right?

**Comment by openaudible** [comment]
Does OpenAI release all their source code? Should it be forced to because of their domain name? Of course not.
