### ISSUE TITLE
certain books will not download (red circle next to it) 

### ISSUE THREAD

**Issue by ggbg6l** [openaudible/openaudible#1016]
Certain books will not download. I tried logging out and trying again.  I checked to make sure that I had actually purchased the books (I had).  I couldn't find a question with the same issue. Thanks!

**Comment by openaudible** [comment]
Connect to your account and do a full rescan then try again. 
If the red circle books are still there, you'll need to delete them... or make sure they are still in your library (haven't been returned or turned into "free" books.). 
A tip would be to download and convert as soon as you can.
