### ISSUE TITLE
Add folders for authors in downloaded files

### ISSUE THREAD

**Issue by ericthelin** [openaudible/openaudible#1017]
This is a feature request so if there is a better place to make them please let me know. I would like to have the book files organized better. My preference is "author/series/num title/num title.m4b" rather than title.m4b. But I expect that this is something that other people would have different opinions on so making it a config value would be the best.

**Comment by openaudible** [comment]
Yeah, it is a feature request that is in the works. Unfortunately there are a lot of roadblocks for getting this done without breaking existing user's setup. Best thing for now is to use a web based viewer such as audiobookshelf https://www.audiobookshelf.org/...
But we are aware that many people like the option to organize the file structure. One of these days.... appreciate the comment.
