### ISSUE TITLE
ability to enable hw acceleration

### ISSUE THREAD

**Issue by bfujii** [openaudible/openaudible#1018]
i noticed the ffmpeg binary has nvenc and nvdec enabled. is it possible via some ffmpeg options file or have an option to enable it in the openaudible api to enable usage of the GPU?

**Comment by openaudible** [comment]
Hardware acceleration is not something that would improve mp3 (liblame) or aax -> m4a conversion.

We do log the full ffmpeg command to the console, so you're welcome to do your own experiments to see if changing parameters would make a difference. If you find something that speeds conversion, we would be happy to take a look and possibly implement.. we do have an undocumented way to add additional arguments to ffmpeg, but wouldn't recommend that approach until you have solid evidence of an improvement in speed via the command line.
