### ISSUE TITLE
"Download All from Audible" not working?

### ISSUE THREAD

**Issue by seannymurrs** [openaudible/openaudible#102]
I finally managed to get all my audiobooks from Audible loaded into OpenAudible. The issue is, when I click the "Download All from Audible" option from the menu, nothing seems to happen. I checked the console, and it shows that the download all command was sent. The only other thing I notice is the status of the books in the library goes from "Not downloaded" to "Ready to download." Nothing seems to actually start downloading, though.

**Comment by openaudible** [comment]
If there was an error downloading a book (for whatever reason) the Download All doesn't attempt to download that book again until the app is restarted. I'm not sure why there is that logic, but restarting may help, or "select all" and Action: Download. Added some debug logs for next release.

**Comment by seannymurrs** [comment]
Any ETA on the next release?

**Comment by Lwethers** [comment]
Sean - did you have any issues with openAudible not recognizing parts of your library? I understand the download all button isn't working. I'm having an issue where many of my audio books don't appear in openaudible.

**Comment by Lwethers** [comment]
I just updated to 1.4.3, and if I select more than 5 titles at a time and select "download" it only adds the first one I selected.

**Comment by openaudible** [comment]
I still don't have a good sense of what the error is, so not sure if any changes will actually fix anything.
What happens if you select one book and select "Download"? Is anything displayed on the console?

**Comment by LDMartin1959** [comment]
Similarly, the menu option "Convert All to MP3" does not seem to work. One has to select the books individually and select "Convert to MP3" from the mouse context menu.

**Comment by openaudible** [comment]
I think this was fixed when a bug in the queue software was fixed. Re-open if this comes up in 1.4.5 or later.
