### ISSUE TITLE
trying to save changes to info are not saved

### ISSUE THREAD

**Issue by bsferrazza** [openaudible/openaudible#1020]
I imported an m4b file that I created by joining a bunch of m4a files with OpenAudible. When I go to 'Get Info', make changes, and then click 'Save Changes' the changes aren't actually saved. This is using the Mac M1 version 3.5.9. Thank you.

**Comment by openaudible** [comment]
Any errors in the log console? Ctrl-e I think.

**Comment by openaudible** [comment]
I am unable to reproduce this. You can test this by editing a book, saving the changes, quit and restart openaudible, then check that the changes are still present. Feel free to comment here if you have more details about what you're seeing.
