### ISSUE TITLE
Book List does not display

### ISSUE THREAD

**Issue by cslibby** [openaudible/openaudible#1022]
![Screenshot from 2022-09-20 19-10-23](https://user-images.githubusercontent.com/2968084/191389693-094f790d-3fec-47d2-a858-621db3a2ed1b.png)

Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy

List does not display at the bottom of the screenshot. Book information displays properly when clicking on a line, but you have no idea what you are clicking on except for the bullet on the left. I have tried system, dark, and light modes to no avail. I have a server on the same release and it works perfectly. The difference is this instance is a laptop and the other working instance is a desktop. Each has its own license so not shared between the two instances.

diagnostics file in temp is empty.

Not sure what else to include as I don't know where to find the list of books.

**Comment by openaudible** [comment]
Looks like your system color theme is not compatible for some reason. I haven't seen that before.
Can you change the OpenAudible preferences for "Color scheme"? 
What is it set to and have you tried all three themes -- Dark, Light, and System?
I'll see if I can reproduce in virtualbox with the ISO from https://releases.ubuntu.com/22.04/

**Comment by openaudible** [comment]
22.04 fresh install is working for me. Again, try changing the color scheme preference, as seen in the screenshot below:
![u2204](https://user-images.githubusercontent.com/30847528/191573222-f8c0ab08-a19c-4b09-a9ff-b3976a9e726f.png)
