### ISSUE TITLE
openAudible reprocesses entire library

### ISSUE THREAD

**Issue by kyleslaw88** [openaudible/openaudible#1023]
Fantastic tool... I used it to download and convert 229 of my audible books. However, I recently opened the app again to download a newly purchased audiobook and it immediately started reprocessing (converting) my entire library. When I browse the library, I can still see the files, so I am not sure why it did this.

I run MacOS Catalina (10.15.7) and had just prior to this occurrence opened the folder in finder (by default it appears hidden, so I used the "go" function to browse to the path directly in the UI and terminal separately. I did not change permissions or anything.
![image](https://user-images.githubusercontent.com/108549712/191856465-15dd18e3-aba2-4170-b2b1-3d86365e699e.png)
![image](https://user-images.githubusercontent.com/108549712/191856557-bfe97fde-6bcd-499f-a108-8fe3aa101912.png)

**Comment by openaudible** [comment]
Hmm. You could try the "Library Rescan" from the Controls menu... ?

Also, we've been moving to a new file system where the "books" directory hold all converted books. But only if we don't detect the old style "mp3" directory. There may be a bug somewhere. 

You could try manually moving the books from mp3 to "books" and  do a library rescan... 

Sorry that happened! Not totally sure what happened.

**Comment by openaudible** [comment]
Not totally sure, but we made some updates to the file system for 3.6.. Give it a try and let us know if you're still having issues.
