### ISSUE TITLE
Download error: No Library Record Found for user.

### ISSUE THREAD

**Issue by robster7674** [openaudible/openaudible#1025]
Trying to download book https://www.audible.co.uk/pd/The-Great-Oil-Conspiracy-Audiobook/B00AMPHUYM I get:

"Download error: No Library Record Found for user."

**Comment by openaudible** [comment]
Try deleting the book (right-click delete), then full rescan, then try to download and convert.

**Comment by robster7674** [comment]
Tried that, same error afterwards.

**Comment by openaudible** [comment]
When you view it in your audible library (from a browser) does it show that you still own it and is downloadable?

**Comment by robster7674** [comment]
It does not show Download:
![image](https://user-images.githubusercontent.com/70331923/192943287-3fb212d3-7f46-4ebc-8fba-79596c1e4582.png)
Perhaps this is because it was a free title?

**Comment by openaudible** [comment]
Can you try with version 3.6.1? 
do a full library refresh.

**Comment by robster7674** [comment]
I'd love to try, but I don't have the cash for an upgrade right now. Since you have the link to the book can you try?

**Comment by openaudible** [comment]
We aren't tracking bugs in older versions.. Its likely that the book is simply no longer accessible.. it might be in newer versions of OpenAudible, but some books become listenable, and then not, for instance if a book is returned or their "free" period expires.

**Comment by robster7674** [comment]
Nice that you at least tried in the new version, thanks.
