### ISSUE TITLE
I have some audible files. Can i convert it to mp3?

### ISSUE THREAD

**Issue by xrsrke** [openaudible/openaudible#1026]
I have some audible files. Can i convert it to mp3?

**Comment by openaudible** [comment]
If they were not downloaded from an android device, probably. You can just drag and drop AAX files onto the application library status panel and they'll be imported. 
But we limit how many accounts they can be from (to 5), so they should all be from your own account(s). 
If they are AAXC files downloaded, you'll need to log into your account from openaudible and download them from there.
