### ISSUE TITLE
Development extremely slow - still no settings for filename etc. at conversion

### ISSUE THREAD

**Issue by francwalter** [openaudible/openaudible#1027]
Hallo
More than a year ago I [opened an issue](https://github.com/openaudible/openaudible/issues/703) about the filepath at conversion etc.
It was quickly closed, and it was said by the developer, that it is on the ToDo list (which is a private list obviously, nobody can check, only the developer knows it, if existant).
Nothing happend.
Now, more than a year later, my license for updates expired, version 3.6 is out (without any relevant improvements, by the way) and still nothing is done with issue #703 
I can understand, that this development is too big for one developer, but it is not the good style to promise empty strings.
I reverted to 3.5.9 (my last working version) and wont buy any further license (as nothing changes anyway).
frank

**Comment by openaudible** [comment]
Yes. We are slow. Its a significant change to the whole program that has the potential to break all existing customers if not done perfectly. 

Upgrades are always optional and after one year anyone can keep using the "last free version".
