### ISSUE TITLE
“Included” Titles

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#1030]
Current version (MAC/Intel or Apple) of OpenAudible says that it “handles” included books.  How?  I have three “included” books, which were downloaded to my Audible Library.  I can play them using the Audible App, or from the Audible site, but they are not dowloaded by Openaudible.  How do I download and convert to M4B these and other included titles?   My Audible and Openaudible subscriptions are up to date.

**Comment by openaudible** [comment]
Full rescan is supposed to find them. Podcasts require a preference file (settings.json) edit.

**Comment by oboe45** [comment]
Just did a full rescan, it did not find the three included titles

**Comment by openaudible** [comment]
Confirmed.. Fixing.

**Comment by openaudible** [comment]
Fixed in 3.6.1?

**Comment by oboe45** [comment]
will check thursday

**Comment by tdguchi** [comment]
I have downloaded 3.6.1 version, no option to enable included titles on preferences. When clicking on refreshlibrary books are "found" but not shown.

**Comment by oboe45** [comment]
Thanks, using it now, it works!!
