### ISSUE TITLE
Preferences Dialog Box

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#1031]
On my MacBook Pro (Intel, 13 inch 2020 INTEL). When I summon the Preferences dialog box, how do I close it?  The OK and Cancel buttons are out of sight a line or two below the "Cooler Scheme Picker" and there is no way to move the dialog upwards to access the buttons!  The same process works fine on my iMac - both machines use the same OS and Openaudible versions except that the IMAC is the Apple Chipset and the MacBook is the Intel chipset.

I can close the app and restart it, but changes to the dialog are not saved.

**Comment by openaudible** [comment]
What size monitor is this? I recall you had a monitor that was tiny. 800x600 resolution monitor required.. 
But command-Enter (or apple-enter?) should hit the "OK" button for you. Escape hits the cancel. (Tested on my m1 using a windows keyboard, so not positive if its cmd, alt, apple, etc. on a mac keyboard.)
Thanks for the feedback. If the dialog gets bigger I will need to add a scrollbar or tabs.
