### ISSUE TITLE
Feature Request: Auto refresh library after customizable time

### ISSUE THREAD

**Issue by ThePianoMan2255** [openaudible/openaudible#1033]
Not an issue so feel free to add this to the end of your list, however,  I currently run this on a server and there is not a way to auto check for book / library updates without a lot of work with cron. Can you please add a setting to allow for the program to be left open and it refresh local / remote library automatically?

Example:
Refresh Library every: 5 minutes

I would like this to go through all of the steps it does during startup: search for, download, convert books. 

Thank you for your time and work on OpenAudible, it's great!

**Comment by KickHighMDK** [comment]
This would be great, not sure about every 5 min.. but daily or weekly would be nice. It would just fetch books and be ready to use when wanted.
