### ISSUE TITLE
Download Loop

### ISSUE THREAD

**Issue by rnbwpnt** [openaudible/openaudible#1038]
OpenAudible 3.6.2 for Apple Silicon on Monterey 12.6.

I have two possibly-related download loop issues going on. [If they turn out to be separate issues I'm happy to split this into two tickets.]

OA is repeatedly downloading and failing on a specific PDF identified in the console log, getting a 404, and then looping.

Likewise, it is repeatedly downloading, successfully converting, and then looping on a subset of about a dozen audiobooks.

Most books and PDFs seem to work okay; it's just a subset of about 10 or so.

If I cancel the job and ignore the audiobook, the behavior ends for the audiobook, but I haven't been able to figure out how to make it stop for the PDF.

The attached log demonstrates the behavior over several minutes for two audiobooks and the PDF.

[OA.log](https://github.com/openaudible/openaudible/files/9725152/OA.log)

**Comment by openaudible** [comment]
Oh. Sounds like pdf is missing and we don’t stop trying. Will fix. Is the pdf available on the audible web site? 
thanks for the report.

**Comment by openaudible** [comment]
That’s what I figured. You could ask audible to look into it. 
Will get a fix in. Thanks.
