### ISSUE TITLE
when doing a sync, OpenAudible tries to redownload books already downloaded. 

### ISSUE THREAD

**Issue by mayagems** [openaudible/openaudible#1039]
For some reason, OpenAudible did not recognize books already downloaded after I switched the marketplace. I was under the US region and it was working fine and I downloaded the few books I had purchased. But when I changed to .CA By logging out and then logging into audible. I did a quick sync to download maybe 1 new books Ive purchased and it states that 94 books need to be downloaded - when they had been downloading prior.  I downloaded some and noticed it was duplicating the book in the 'books' folder - it would have the name of the title and add .1 after it for the M4B. This just started happening today. 

I switched to yet another marketplace (UK) and it is asking me to download all those books too. I don't have enough space to redownload all the books that are already downloaded and I have soo many books that it would be hard to filter it all. 

Just to followup I have recently downloaded the update and I am using a M1 macbook.

**Comment by mayagems** [comment]
I think I figured out a random fix. I highlighted the greyed to download books and deleted them. Did another quick sync and it only picked up the newer books.
When I changed to another region again it wanted me to download all the books. So I highlighted those and deleted them. And after a new sync stated all my books were up to date (as I had no new books to download). All in all, very strange.

**Comment by openaudible** [comment]
Sounds like switching between regions (with the same library) has some problems. Probably there are two copies of the same book that have different product ID or ASIN numbers.  
Glad you were able to make a fix for this.. Will keep an eye out for similar behavior.. Appreciate the report. 
If anyone wants to chime in with more details or a better solution, feel free to post here.
