### ISSUE TITLE
Latest version browser can't connect to any URL

### ISSUE THREAD

**Issue by ToaKamate** [openaudible/openaudible#104]
Greetings,
Updated to the latest version. Now, when I try to connect to Audible, the browser window that launches can not connect to any URL - even google.com.  When I copy/paste audible.com URLs into FF, Chrome and IE - they connect without issue.

I tried to file a bug report via OpenAudible but received an error, see attached.
![2019-03-01 16_50_51-openaudible](https://user-images.githubusercontent.com/48141166/53673293-c3fb1c00-3c43-11e9-9ff3-50631c056771.png)
![2019-03-01 17_02_27-openaudible](https://user-images.githubusercontent.com/48141166/53673315-de34fa00-3c43-11e9-9f2b-c38524c70b83.png)

**Comment by openaudible** [comment]
Your firewall/anti-virus software is successfully blocking OpenAudible from connecting to the internet. 
You'll need to change your firewall settings to allow this version of OpenAudible to use the network.

**Comment by ToaKamate** [comment]
That was it. Thanks so much.

On March 2, 2019 11:51:56 AM MST, openaudible <notifications@github.com> wrote:
>Your firewall/anti-virus software is successfully blocking OpenAudible
>from connecting to the internet. 
>You'll need to change your firewall settings to allow this version of
>OpenAudible to use the network.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/openaudible/openaudible/issues/104#issuecomment-468948942

-- 
Sent from my Android phone with K-9 Mail. Please excuse my brevity.
