### ISSUE TITLE
Feature Request: Allow the number of conversions to be configured.

### ISSUE THREAD

**Issue by lxtwin** [openaudible/openaudible#1040]
From the GUI It would be great to have more than 3 ffmpeg confessions running at the same time as like may I have a lot of idle threads / cores which could be converting. (instead of editing the settings file)

**Comment by openaudible** [comment]
We are trying to keep the UI simple. The settings file can be edited for advanced users to change the number of concurrent downloads/conversions.  Changing the number can make performance slow to a crawl or create failures due to lack of memory.

**Comment by lxtwin** [comment]
Thanks, for info an AMD Ryzen 9 5900X on a system with 64GB, can convert 20 at once and will use 32GB.

**Comment by openaudible** [comment]
We did tests to determine the optimum number of concurrent conversions and found our reasonably powerful multi-core system got pretty bogged down after about 9 simultaneous mp3 conversions. But glad you found a setting you're happy with. 

We do recommend M4B conversion, which is a lot less strenuous and can be done in a few seconds per book, so there is a big difference between that and MP3 conversion.
