### ISSUE TITLE
[OA v3.6.2 Mac Intel] can't open local files

### ISSUE THREAD

**Issue by Sean-Kelly** [openaudible/openaudible#1044]
This file was already on my hard drive. I have spend countless hours getting all these from the Audible site over the last several years.
The file sows up in the correct directory
[https://imgur.com/a/0T7CBYe](url)

but the action to convert is greyed out and is unavailable.
[https://imgur.com/a/zJPbKOd
](url)
Please tell me I haven't purchased this only to find out that I need to go back to my old software if I don't want to re-download everything?

**Comment by openaudible** [comment]
It is working. Since the book icon is green, it is already converted. Just select show m4b or play. If you’d rather have mp3, you’ll need change the preferences. Cheers!
