### ISSUE TITLE
Is it possible to get access to the latest code?

### ISSUE THREAD

**Issue by nospam2k** [openaudible/openaudible#105]
I'm interested in modifying the interface to use Swing instead of SWT to make it more cross OS friendly. I don't really want to modify old code. Is there a way I can get access to the latest branch?

**Comment by openaudible** [comment]
Probably not. We're considering options on creating a "pro" version which complicates the release of all of the source code. We didn't get enough source code contributions to justify trying to keep everything public. 

That said, a Swing version would be interesting.. but a ton of work (200 hours?). Unfortunately, a lot of logic is still co-mingled with the SWT desktop code, so it would be a bit messy trying to abstract the GUI for both.
