### ISSUE TITLE
Issue with splitting books

### ISSUE THREAD

**Issue by marcoose777** [openaudible/openaudible#1051]
I'm having an issue with book splitting in the Linux version, Terry Pratchett Witches Abroad (new edition) creates 148 chapters from 9 hour 53 min of book. Examining the book file, that should be 28 chapters. 
I've tried deleting and resyncing book metadata (json's) with Audible and that makes no difference.
I have version 3.6.2 of OpenAudible and (using AppImage to manage the installation), Manjaro Linux (Arch) Kernel: 5.15.74-3 (x86_64) compiler: gcc v: 12.2.0 
See book file, just the data for Witches Abroad:
[Witches Abroad Book Data.txt](https://github.com/openaudible/openaudible/files/9897191/Witches.Abroad.Book.Data.txt)

**Comment by openaudible** [comment]
There is no way to fix bad chapter meta data. If you do a Get Info on the book and it says there are 148 chapters, that’s how many will be created. Although it should skip empty chapters less than a second. 

if you want, Do a Get Info on the book, see what the Chapters Tab says, and 
if you want you can post the json version of it from the Book Report tab. 
 
How many chapters does it show from your mobile audible player?

**Comment by marcoose777** [comment]
HI,
I've had a closer look and indeed you are right. When I clear my library (book.json) and perform GetInfo for this book alone it appears Amazon are indeed pushing bogus chapter information ... unless it relates to Whisper sync, which still doesn't tally and 148 chapters for 9 hour reading is certainly unusual (av chapter length 3 mins). There's also a ton of superfluous junk that's downloaded too?? For instance: reviews. Obviously Amazon thinks I need to read the reviews after purchasing the book. God bless Jeff. 
The split function and chapter information is useful, when Amazon get it right. I use your tool to download books to my Sandisk MP3 player and split them into chapters for easier backward and forwarding if necessary. I would otherwise not be able to do this, being a Linux only person since 2005(ish). 
PS
The other 45 books in my library have split just fine

**Comment by marcoose777** [comment]
Closed
