### ISSUE TITLE
Clarification On "Books" Directory?

### ISSUE THREAD

**Issue by TheWrightDev** [openaudible/openaudible#1052]
Yesterday I installed and ran a full sync followed by the download all action. While it was downloading it was placing files in the .\aax, .\m4b and .\pdf directories. Overall no complaints, looked pretty neat.

So today I launched the app again and it just immediately kicked off some conversion job and created a new directory called "books" and one by one reconverted the aax files to m4b again and putting them into the books folder along with any related pdfs right alongside them. Once it finished I closed and reopened it again just to see if it had anymore tricks, but it seems to be content now with just duplicates in the m4b and books directory.

I don't even see any option to configure this "books" directory in the preferences? If I only want to keep one copy of the m4b and pdfs, which folders are safe to delete - ".\books" or ".\m4b" and ".\pdf". And what do I need to change so that it only downloads to one of these in the future? And if "books" is some new thing going forward, will there be any way to have it create folders for the books so that any related files can actually be grouped?

**Comment by openaudible** [comment]
Sorry for the late reply. 

the books directory is the new location for all converted audiobooks going forward. So safe to delete or merge m4b/pdf into that. We have been working on a more flexible directory structure and that was the first step. 

Feel free to ask if anything else comes up.
