### ISSUE TITLE
Problems saving/loading custom table columns

### ISSUE THREAD

**Issue by Bonbernie** [openaudible/openaudible#1053]
Description of problem: 

I own the version for the Mac with M1 processor. If I sort the lower column according to my own needs, e.g. author, title, series, etc. and close the program and then restart it, the program unfortunately does not remember the changes and the original view appears again. Would be nice if the error could be fixed.

**Comment by openaudible** [comment]
Can you clarify what change you make to get your table the way you want it? 

Is it just the sort Table and direction (low to high or high to low)

**Comment by Bonbernie** [comment]
No, it is not low to high or high to low.

Par example the columns before changing are in German: 

Titel, Autor, Erzählt von, Dauer, Kaufdatum, Erscheinungsdatum, Bewertung, Genre

now i make a new sort to

Autor, Titel, Erzählt von, Bewertung, Name der Reihe, Dauer

then i close the program and make a restart and the columns are again

Titel, Autor, Erzählt von, Dauer, Kaufdatum, Erscheinungsdatum, Bewertung, Genre and not Autor, Titel, Erzählt von, Bewertung, Name der Reihe, Dauer

**Comment by openaudible** [comment]
Ok. Confirmed. Will fix soon. Thank you!

**Comment by Bonbernie** [comment]
Thank you very much.

Von meinem iPad gesendet

**Comment by openaudible** [comment]
A beta has been released to address this.
https://openaudible.org/beta

**Comment by Bonbernie** [comment]
Great. Works fine for me. Thank you so much.

**Comment by openaudible** [comment]
OK. Fixed in the beta.
