### ISSUE TITLE
State: Error downloading: Encountered an error. Please try again later.

### ISSUE THREAD

**Issue by zenmeeno** [openaudible/openaudible#1054]
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/117807466/200764697-5cccfef9-e4dc-428a-9deb-61269b42c000.png">

**Cannot download files...**
> Error downloading: Encountered an error. Please try again later.

**Comment by zenmeeno** [comment]
**All new downloads fail right away due to missing links.**
<img width="1027" alt="Xnapper-2022-11-09-23 57 34" src="https://user-images.githubusercontent.com/117807466/200836504-c2de779d-0107-466c-8706-263e9b2b75e9.png">

**Comment by openaudible** [comment]
Under library Status: Do you show "Connected: Yes" ? Have you tried a full rescan lately?

To fully reset,
Try Controls: Log out, 
Delete all red dot books.. Controls: Connect to Audible
Full Rescan
then see if you can download a book.

**Comment by zenmeeno** [comment]
Hi,

Thanks for that. Unfortunately, that didn’t work.
That being said, some book did start downloading, but most still don’t.

Regards
Meeno

**Comment by openaudible** [comment]
Some items may no longer be available to download... free items often expire, or some books may be no longer available. If you can play the item in your mobile browser, it may be a bug... but usually it means the item is no longer available.

**Comment by appmu** [comment]
This seems to occur when the user downloads around 100 books in 24 hours using OpenAudible. After waiting for a day or so, it is usually recovered. It appears Amazon has some blocking mechanism against excessive downloads.

**Comment by openaudible** [comment]
Missing download links may mean you logged into an account, didn't download/convert.. then the items either got removed from your library, or you logged into another account. So always best to log in, download, and convert to m4b. You can always convert to mp3 later if you need to try to make a smaller or more compatible file (at a worse quality.)

**Comment by appmu** [comment]
This occurs even if you are logged in.
