### ISSUE TITLE
Downloading/Syncing Files After Import

### ISSUE THREAD

**Issue by Puddl36lum** [openaudible/openaudible#1056]
After updating my MacBook to 13.01, I started OpenAudible to find that preferences reverted to the default Library/Web directories (I store my audiobook library on my synology.  I set the folders to point to the directories on my synology.  After restarting OpenAudible, after a quick scan of my audiobook folder, OpenAudible showed the correct number of M4B files but didn't list any books. 

 I restarted the app several times and it didn't list the books so i used the import function and it imported all of the books.  However, now, when i use any of the library sync options (quick, full, etc) OpenAudible tries to download my entire library even though the books are there, and the metadata for the M4B files has not changed.

**Comment by Puddl36lum** [comment]
it also seems to rename files and pull different info. Green books were imported, gray was the canceled sync.  Notice the file names are different, and the ratings are imported for the canceled sync as well.
![Screenshot 2022-11-10 at 10 51 51 PM](https://user-images.githubusercontent.com/35609478/201259737-49760e67-0f32-4d01-ad81-26e0325419df.png)

**Comment by openaudible** [comment]
This can happen if your file share is offline. Added a fix for this in latest beta and new version is due out soon. Sorry for late reply.
