### ISSUE TITLE
Request: error handling when configured 'Library' directory not available

### ISSUE THREAD

**Issue by Cybergate9** [openaudible/openaudible#1058]
When OA configured for 'Library+Web' directories on network drive (somewhere off local machine)..

If network drive is not available (server off or whatever) OA reverts to default directories on local machine and *starts a whole new sync*..

This is never what you want it to do in this situation.
Ideally it would ask if you want to quit, or edit settings, because configured directories are not currently available

Thoughts?

maybe related for what user's describing on issue #1056 too

**Comment by openaudible** [comment]
I will fix! Thank you.

**Comment by openaudible** [comment]
Fixed in latest beta. Thank you for the report.
