### ISSUE TITLE
Openaudible will not convert downloaded aax files in fedora and will not open up audible login page.

### ISSUE THREAD

**Issue by dt369369** [openaudible/openaudible#1059]
Main issue is that the browser the openaudible client launches just stays blank.  OS is fedora 36.  Web browser by itself (chrome) works fine and can login.  Just can't connect with openaudible.  No firewall issues.  Turned off.  Verified connectivity (ping, dns, etc.).  Connect to audible just hangs with blank web browser screen.

Diagnostics:
{
 "date": "Sun Nov 13 16:18:06 EST 2022",
 "books.json": "/home/user/OpenAudible/books.json",
 "memory": "Memory: Using 50.157Mb of 1958Mb (3%) Min 25.844Mb Max 50.157Mb",
 "directories": [
  {
   "path": "/home/user/OpenAudible",
   "kind": "BASE",
   "exists": true
  },
  {
   "path": "/home/user/OpenAudible/books",
   "kind": "BOOKS",
   "exists": true
  },
  {
   "path": "/home/user/OpenAudible/web",
   "kind": "WEB",
   "exists": false
  },
  {
   "path": "/home/user/OpenAudible",
   "kind": "META",
   "exists": true
  },
  {
   "path": "/home/user/OpenAudible/aax",
   "kind": "AAX",
   "exists": true
  },
  {
   "path": "/home/user/OpenAudible/art",
   "kind": "ART",
   "exists": true
  },
  {
   "path": "/home/user/OpenAudible/books",
   "kind": "MP3",
   "count": 0,
   "exists": true,
   "sample": "/home/user/OpenAudible/books/sample.mp3"
  },
  {
   "path": "/home/user/OpenAudible/tmp",
   "kind": "TMP",
   "exists": true
  },
  {
   "path": "/opt/OpenAudible",
   "kind": "APP",
   "exists": true
  },
  {
   "path": "/home/user/OpenAudible/books",
   "kind": "M4A",
   "count": 0,
   "exists": true,
   "sample": "/home/user/OpenAudible/books/sample.m4a"
  },
  {
   "path": "/home/user/OpenAudible/books",
   "kind": "M4B",
   "count": 0,
   "exists": true,
   "sample": "/home/user/OpenAudible/books/sample.m4b"
  },
  {
   "path": "/home/user/OpenAudible/books",
   "kind": "PDF",
   "exists": true
  }
 ],
 "gui": {
  "swt_platform": "gtk",
  "main_window": "Rectangle {2129, 385, 1512, 1152}",
  "browser": {
   "prefer_chromium": false,
   "oa_chromium": "",
   "which_xdg": "/usr/bin/xdg-open\n",
   "swtBrowserStyle": 570490880,
   "Desktop.isDesktopSupported": true,
   "externalBrowser": true,
   "Desktop.Action.BROWSE": true,
   "externalBrowserMode": "custom",
   "oa_internal_browser": "",
   "swtBrowserType": "webkit",
   "browseWebCmd": "xdg-open %u"
  },
  "display": {
   "highContrast": false,
   "bounds": "Rectangle {0, 0, 5120, 1440}",
   "dpi": "Point {96, 96}"
  },
  "aspect": 1.3125,
  "theme": {
   "dark_debug": "set  org.eclipse.swt.display.useSystemTheme from  to true\n",
   "org.eclipse.swt.display.useSystemTheme": "true",
   "theme": "system",
   "is_dark": false
  },
  "swt_version": 4950
 },
 "compile_date": "2022-10-04 22:10",
 "region": "US",
 "version": "3.6.2",
 "demo": false,
 "platform": "linux",
 "properties": {
  "org.eclipse.swt.display.useSystemTheme": "true",
  "oa_external": "",
  "file.encoding": "UTF-8",
  "os": "NAME=\"Fedora Linux\"\nVERSION=\"36 (Thirty Six)\"\nID=fedora\nVERSION_ID=36\nVERSION_CODENAME=\"\"\nPLATFORM_ID=\"platform:f36\"\nPRETTY_NAME=\"Fedora Linux 36 (Thirty Six)\"\nANSI_COLOR=\"0;38;2;60;110;180\"\nLOGO=fedora-logo-icon\nCPE_NAME=\"cpe:/o:fedoraproject:fedora:36\"\nHOME_URL=\"https://fedoraproject.org/\"\nDOCUMENTATION_URL=\"https://docs.fedoraproject.org/en-US/fedora/f36/system-administrators-guide/\"\nSUPPORT_URL=\"https://ask.fedoraproject.org/\"\nBUG_REPORT_URL=\"https://bugzilla.redhat.com/\"\nREDHAT_BUGZILLA_PRODUCT=\"Fedora\"\nREDHAT_BUGZILLA_PRODUCT_VERSION=36\nREDHAT_SUPPORT_PRODUCT=\"Fedora\"\nREDHAT_SUPPORT_PRODUCT_VERSION=36\nPRIVACY_POLICY_URL=\"https://fedoraproject.org/wiki/Legal:PrivacyPolicy\"\n",
  "java.version": "11.0.15",
  "oa_chromium": "",
  "sun.jnu.encoding": "UTF-8",
  "SWT_GTK3": "",
  "OPENAUDIBLE_HOME": "",
  "locale": "LANG=C.UTF-8\nLC_CTYPE=\"C.UTF-8\"\nLC_NUMERIC=\"C.UTF-8\"\nLC_TIME=\"C.UTF-8\"\nLC_COLLATE=\"C.UTF-8\"\nLC_MONETARY=\"C.UTF-8\"\nLC_MESSAGES=\"C.UTF-8\"\nLC_PAPER=\"C.UTF-8\"\nLC_NAME=\"C.UTF-8\"\nLC_ADDRESS=\"C.UTF-8\"\nLC_TELEPHONE=\"C.UTF-8\"\nLC_MEASUREMENT=\"C.UTF-8\"\nLC_IDENTIFICATION=\"C.UTF-8\"\nLC_ALL=\n",
  "oa_internal_browser": "",
  "oa_packaging": "rpm"
 },
 "prefs": {
  "disableVersionCheck": false,
  "autoConvert": true,
  "language": "en",
  "uid": "1668354971828",
  "browseFileCmd": "",
  "browser": "external",
  "html": false,
  "theme": "",
  "migrated": true,
  "browseWebCmd": "xdg-open %u",
  "autoDeleteAAX": false,
  "lastVersion": "3.6.2",
  "playFileCmd": "xdg-open",
  "webPageIncludeMP3": true,
  "format": "M4B",
  "autoDownload": false,
  "autoWebPage": false,
  "autoRefreshMinutes": 0,
  "autoConnect": true,
  "concurrentConversions": 3,
  "podcasts": false,
  "autoLink": false,
  "mp3Quality": "",
  "concurrentDownloads": 3,
  "autoPDF": true,
  "region": "US"
 }
}

**Comment by openaudible** [comment]
Some linux browsers aren't compatible. You could try setting an environment variable:
oa_chromium=true and re-running. Did you see anything in the log window? We are working on some alternate login code.
You could run OpenAudible in another computer (mac/win) and copy your credentials.json file over to linux and it should work with that.

**Comment by openaudible** [comment]
Try the latest version 3.6.3 (or newer) and before you run, set the environment oa_jxbrowser=true
That will launch an alternative browser instead of the built-in webkit browser that may be incompatible. Thanks
