### ISSUE TITLE
Use on files already downloaded

### ISSUE THREAD

**Issue by TerryNicko** [openaudible/openaudible#106]
A few years ago I quit Audible after downloading books that I bought. After quiting my Audible subscription I deleted these books from Audible library. I thought I was able to play them in iTunes but now I cannot. 
So is OpenAudible able to open and convert .aa files that are on my hard drive? I can't seem to figure out how to navigate to these files from OpenAudible. Tried dragging and dropping them but did not work.....

**Comment by openaudible** [comment]
We are improving the importing of mp3, aax, and aa files significantly in the next version... Drag and drop will work on .aa, .aax, .mp3 files with new support for audio books not from audible.  

You might be able to use the File:Import Books (or Import AAX).. And you might also have to rename the .aa file to .AAX to fake it if you don't want to wait for the next version.

**Comment by TerryNicko** [comment]
Thanks, I tried changing the extension to AAX but that did not work. I'll wait for the next version. Thanks.
