### ISSUE TITLE
wrong email

### ISSUE THREAD

**Issue by themeghanammon** [openaudible/openaudible#1063]
I purchased Open Audible with a different email then my Audible account and its not connecting, is there anyway to resolve this issue?

**Comment by openaudible** [comment]
Sure, send a message to openaudible at email dot tg and let me know your license number and or old email.

**Comment by themeghanammon** [comment]
Hi there,
here is the license key - wko0-rak1-fpfe
I purchased openaudible under the email ***@***.*** but my
audible account is under
***@***.***
