### ISSUE TITLE
Feature request: Option to structure converted files into author/title

### ISSUE THREAD

**Issue by Huevos-y-Bacon** [openaudible/openaudible#1065]
It would be great to have an option to keep the `books` folder of converted books in `Author/Title` file structure. I have about 200 Audible titles and all the titles in the same directory is not great.

Other than that, great work!

**Comment by openaudible** [comment]
Frequently requested. In progress. Unfortunately no time guarantees.

**Comment by wolfspyre** [comment]
nitpick, but why close the issue if the work is in progress?

**Comment by NovaProton** [comment]
@openaudible Any update on this

**Comment by openaudible** [comment]
Still in progress. Will update when a beta is available. Maybe early Oct.

**Comment by NovaProton** [comment]
@openaudible is there any update on this
