### ISSUE TITLE
OpenAudible FLOSS

### ISSUE THREAD

**Issue by ncorder** [openaudible/openaudible#1067]
As an individual who often has to listen to audio books or read e-books, your application (when used within its legal context) is a life saver. However after reading through your [license](https://openaudible.org/license) page, I wanted to request clarity surrounding your applications software license. 

Is OpenAudible a free/libre and open source application? Does it require any proprietary dependencies? 
The project appears to be Apache licensed, is that correct?

I always want to make sure and show support for FLOSS projects but was curious if the application was asking for donations, or requesting to install a proprietary paid version.
_____________________

Through extension, I have created an entry on the Free Software Foundations wiki for the project as well: https://directory.fsf.org/wiki/OpenAudible

_____________________

**Comment by openaudible** [comment]
We  are formerly open sourced but closed the source after having no meaningful contributions. We use no GPL code which is the only real poisonous license. We removed some rainbow table open source code that did not have a license. We have purchased one commercial license and donate to ffmpeg and eclipse foundation. Thanks for asking.
