### ISSUE TITLE
licenserequest reason: bad request

### ISSUE THREAD

**Issue by Yoddikko** [openaudible/openaudible#1068]
![Immagine 2022-11-20 105347](https://user-images.githubusercontent.com/92546954/202895754-c33c5e55-af0e-4fd3-93d2-b7c71fd3e8d0.png)

I'm on a older version of the software because I bought it time ago. 

`AVVERTENZA: https://api.audible.it/1.0/content/8831802542/licenserequest -> HttpResponseProxy{HTTP/1.1 400 Bad Request [Content-Type: application/json, Content-Length: 153, Connection: keep-alive, Server: Server, Date: Sun, 20 Nov 2022 09:58:45 GMT, x-amz-rid: VX0DA2B0D6JHBH5GHN1C, x-amzn-RequestId: 58891ead-fcb7-4480-a91c-6879547ba2e1, X-Amz-Date: Sun, 20 Nov 2022 09:58:45 GMT, x-amzn-ErrorType: ValidationException:http://internal.amazon.com/coral/com.amazon.coral.validate/, nnCoection: close, Vary: Content-Type,Accept-Encoding,User-Agent, Strict-Transport-Security: max-age=47474747; includeSubDomains; preload, X-Cache: Error from cloudfront, Via: 1.1 700cde4f0f5657e960ef85bdf58168b6.cloudfront.net (CloudFront), X-Amz-Cf-Pop: MXP63-P2, X-Amz-Cf-Id: KiwkWV29FD5_Raoq5zqTTH6K5ejeEEt97WSM7_WH6OwBEWWMCqxhXw==] ResponseEntityProxy{[Content-Type: application/json,Content-Length: 153,Chunked: false]}}
nov 20, 2022 10:58:46 AM org.openaudible.util.queues.ThreadedQueue jobError
INFORMAZIONI: DownloadQueue error processing Download Bomba atomica item Bomba atomica
java.io.IOException: http error getting: https://api.audible.it/1.0/content/8831802542/licenserequest reason:Bad Request
	at org.openaudible.audible.api.Client.requestBytes(Client.java:153)
	at org.openaudible.audible.api.Client.request(Client.java:84)
	at org.openaudible.audible.api.Client.post(Client.java:78)
	at org.openaudible.audible.api.API.getLicenseForBook(API.java:564)
	at org.openaudible.audible.api.API.getLicenseForBook(API.java:555)
	at org.openaudible.audible.APIManager.getAAXCDownloadLink(APIManager.java:93)
	at org.openaudible.download.DownloadAAXJob.preProcessAAXC(DownloadAAXJob.java:239)
	at org.openaudible.download.DownloadAAXJob.processJob(DownloadAAXJob.java:198)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:484)

nov 20, 2022 10:58:46 AM org.openaudible.Audible jobCompleted
INFORMAZIONI: DownloadQueue completed:Bomba atomica DownloadQueue working:0 remain:0 success:0 fail:4
`

**Comment by openaudible** [comment]
Sometimes books become unavailable. 
Delete the "red" book. Make sure the book is still available in your library and can be listened to. Log in (again if needed) and do a full library scan. Try again.

**Comment by alvarq** [comment]
I'm running OpenAudible 3.5.4
If I try to download the newly purchased Audiofiles, I get an "openaudible licenserequest reason:Bad Request" in the console and the files are not downloaded. It this a know issue? Is it a problem with the revision of my software?

**Comment by JamesSwift** [comment]
I'm getting the same error, on two different laptops running v3.5.3
![image](https://user-images.githubusercontent.com/2080205/216157883-eb395882-88d8-4c1a-ba10-1ef8780d0f4d.png)
One was a fresh install, the other worked as recently as last week but is no longer working. I tried logging out and logging in again, and a full library sync. No joy.
Some books will download, but any recent purchases won't.

**Comment by wshaver** [comment]
Same issue.
![image](https://user-images.githubusercontent.com/786554/216511222-82d9a742-16aa-46ac-8c1b-cf35cb011611.png)

V 3.5

**Comment by wshaver** [comment]
I was able to: 1) download the AAX manually from audible. 2) Put it in the correct directory 3) use the "Rename Book" feature to make sure that the book and newly downloaded aax match. 4) restart Open Audible at which point it automatically converted it to an mp3.

**Comment by JamesSwift** [comment]
Updating to the latest beta solved this issue for me.
