### ISSUE TITLE
m4b conversion

### ISSUE THREAD

**Issue by ab-uncoders** [openaudible/openaudible#1069]
Use case is an m4b converted with the latest release on macos Monterey, uploaded to android 11 phone, and then transferred to a pixel watch for listening.  A small group of m4bs play ok - the others report not uploaded properly. One clue: The working m4bs all show the cover art. The others don't. I have noticed that the nonworking m4bs also don't show cover art when loaded into apple books (even though they play) and also when you browse on the android phone with the Files app.

I do have a license. And am happy to have a go debugging this one if I had access to the latest code.

**Comment by openaudible** [comment]
Hmm. Apple books usually shows the artwork just fine. 

Have you tried another media player like "vlc" or something else that can read the tags and cover art?

You can also do an "ffprobe" from within Openaudible using the "Get Info" and looking at the book report data. 

Are the file sizes of the ones that don't play >2GB? (or significantly larger?)  (If so, you can rename the .m4b to .m4a and see if there is a difference..)

Have you tried Mp3 to see if that makes a difference?

How about googling your watch? A quick google found this (last comment:)
https://www.reddit.com/r/PixelWatch/comments/xybfsz/listen_to_audiobooks/

Try another audiobook player on your watch?

**Comment by openaudible** [comment]
I haven’t found any books that don’t have a cover in the Mac book player.

**Comment by openaudible** [comment]
Unable to reproduce. Maybe bug in player. Feel free to add to this.
