### ISSUE TITLE
suggestion - folder.jpg

### ISSUE THREAD

**Issue by kai-uwe-rommel** [openaudible/openaudible#1071]
Hello, I have a small issue: 
When downloading, converting and then splitting an audio book, I get an almost perfect folder with chapter based MP3 files so that I can then listen to the audio book conveniently on my car audio system.
The only thing that does not immediately work is the cover image.
You write the cover image into a .jpg file named with the audio book title in the folder.
Apparently you also write the cover image into each individual MP3 file.
Unfortunately, my car audio does not recognize either directly.
I have to rename the .jpg file to "folder.jpg" and then it is recognized.
As far as I have been able to gather, the name "folder.jpg" seems to be the "standard" to which most audio tools and players conform.
Could you perhaps consider naming the .jpg file "folder.jpg" instead of naming it after the audio book title?

**Comment by openaudible** [comment]
I found a little info about "folder.jpg" being common, as well as "cover.jpg". Both are possible.. not sure what is best. 
Does "cover.jpg" also work for your radio? Trying to keep the options to a minimum..

**Comment by kai-uwe-rommel** [comment]
Quick test: either my car audio system supports both or it has somehow cached the image.
You could simply copy both into the folder. After all, these files are of very small size, compared to the .mp3 files, anyway.
Just a .jpg with the audiobook title as the name will probably not be recognized by many systems.

**Comment by openaudible** [comment]
Added this to the latest beta: 
https://openaudible.org/beta
You will need to re-split the whole book.
