### ISSUE TITLE
Docker Version: Can't login to amazon account

### ISSUE THREAD

**Issue by cypres0099** [openaudible/openaudible#1074]
I've installed the docker version of the app on my unraid machine. When I go to connect my audible account by logging into Amazon.com, I submit the login information and then it takes my right back to the login screen with a captcha. 

I've verified that it's the correct login by logging into Amazon on my web browser, but still no luck with connecting Open Audible

**Comment by cypres0099** [comment]
I just installed the windows version and I'm having the same problem.

**Comment by cypres0099** [comment]
I played around with the external browser login setting and was able to get a little farther.

Now getting this error

![image](https://user-images.githubusercontent.com/74935762/205450865-e7ff99e0-4e29-46aa-a1cd-ee1d92c056a6.png)

**Comment by openaudible** [comment]
It could also be another error that might have a better explanation in the console log (File: Console)

We do have a beta that might also be helpful. https://openaudible.org/beta which can be run by either upgrading from the container or following the docs on how to run the beta container.
