### ISSUE TITLE
Portable?

### ISSUE THREAD

**Issue by Aidolii** [openaudible/openaudible#108]
Do you think you could add a way to install the program as a portable application, i.e. installing outside of Program Files and all settings that would normally be put in appdata or the registry are instead stored within the portable installation directory?

A lot of portable implementations just do something like checking to see if a file named portable_mode.txt exists inside the main executable's directory.

**Comment by openaudible** [comment]
We use install4j (a great installer app) but adding a portable option looks like it takes hours of programming/tinkering.  

https://www.ej-technologies.com/blog/2010/12/more-installation-options-with-install4j/

**Comment by Aidolii** [comment]
That's unfortunate...

**Comment by openaudible** [comment]
What is the use case? If you don't save the settings in a known place, your books would need to be rescanned every time you open the app. If you want, just uninstall after each use and delete the AppData/OpenAudible directory. You could even write a script to delete your settings after each use.

**Comment by Aidolii** [comment]
That's not how portable applications work. The idea is to keep all of the files used within a directory inside of the installation, and use relative pathing to access it.

**Comment by cyberquarks** [comment]
Something like Calibre so you can install your app in a portable drive along with the books 
Ref: https://calibre-ebook.com/download_portable

**Comment by openaudible** [comment]
Added to the feature request list. I think there is a way to do it.
