### ISSUE TITLE
JavaApplicationStub quit unexpectedly

### ISSUE THREAD

**Issue by JimFitt** [openaudible/openaudible#1082]
I am trying to update from 3.3 to 3.6.3 and an getting an endless loop of JavaApplicationStub quit unexpectedly. Below is part of what I am getting...

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               JavaApplicationStub [930]
Path:                  /Applications/OpenAudible.app/Contents/MacOS/JavaApplicationStub
Identifier:            org.openaudible.openaudible
Version:               3.3 (3.3)
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-12-16 16:44:10.4785 -0400
OS Version:            macOS 13.0.1 (22A400)
Report Version:        12
Bridge OS Version:     7.0 (20P420)
Anonymous UUID:        878965CC-6B55-8171-A531-9D00E9504A12

Time Awake Since Boot: 130 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BREAKPOINT (SIGTRAP)
Exception Codes:       0x0000000000000002, 0x0000000000000000

Termination Reason:    Namespace SIGNAL, Code 5 Trace/BPT trap: 5
Terminating Process:   exc handler [930]

**Comment by openaudible** [comment]
Strange. We had a bug come up on Intel Macs running ventura, but that typically only happens when doing a "Connect".

Are you just starting the app? Does the main window open? 
After launching the app, we do a version check.. so if you have an aggressive anti-virus app, maybe it doesn't like us checking the version (you can turn off automatic version checks from the prefs.)
Are earlier versions working?

The above shows you're still using 3.3, not 3.6.3, so you might check to make sure you're using the latest version. Also, make sure you get the correct version for M1/AARCH vs. Intel. 

You can send a full bug report to openaudible at email dot tg ....

**Comment by JimFitt** [comment]
Thanks for replying.

What I'm trying to do is update to 3.6.3 (from 3.3) but the error is not letting me load.

Attached is the full Translated Error Report.

[OpenAudioError.docx](https://github.com/openaudible/openaudible/files/10249891/OpenAudioError.docx)

Here is what is happening
[OpenAudio.pdf](https://github.com/openaudible/openaudible/files/10249912/OpenAudio.pdf)

No sure what openaudible at email dot tg .... is.

**Comment by openaudible** [comment]
OK. Yes.. that is a bug that was introduced in MacOS Ventura. I think we forgot about the upgrade link that can use the browser. Thanks for the heads up.

Please go to settings, and select "Use External Browser" and save those settings and quit.
Then just download the latest OpenAudible from https://openaudible.org/ using a desktop browser. 
And you can copy the new 3.6.3 over to your Applications directory.
The dot tg is our email address slightly obfuscated to avoid getting lots of spam.

**Comment by JimFitt** [comment]
> OK. Yes.. that is a bug that was introduced in MacOS Ventura. I think we forgot about the upgrade link that can use the browser. Thanks for the heads up.
> 
> Please go to settings, and select "Use External Browser" and save those settings and quit. Then just download the latest OpenAudible from https://openaudible.org/ using a desktop browser. And you can copy the new 3.6.3 over to your Applications directory. The dot tg is our email address slightly obfuscated to avoid getting lots of spam.

Very sorry but when you say " Please go to settings, and select "Use External Browser"".... settings where? in OpenAudio? If so, I don't see settings in 3.3.

**Comment by JimFitt** [comment]
I tried this but am getting this...
<img width="271" alt="Screenshot 2022-12-16 at 7 28 18 PM" src="https://user-images.githubusercontent.com/120753142/208204851-b9628545-ac8e-4b8c-aeb6-471673dacbd6.png">

**Comment by openaudible** [comment]
I haven't used 3.3 in a while. You can skip that step or do it later from version 3.6.3.
But it looks like:
![prefsex](https://user-images.githubusercontent.com/30847528/208207902-aac84b94-50d2-4b24-a174-d63104217ab6.png)

**Comment by JimFitt** [comment]
Sorry, OpenAudio will not even open yet. 

Can I remove this altogether and reinstall?

**Comment by JimFitt** [comment]
*Sorry, OpenAudio will not even open any more.

**Comment by openaudible** [comment]
I think you have an intel Mac, so go to openaudible.org and Download latest version 3.6.3 for Mac Intel.

**Comment by JimFitt** [comment]
Yes. I did this. When the file downloaded I moved it to Applications as you side. Now the program will not open at all with this message...
<img width="282" alt="Screenshot 2022-12-16 at 7 46 54 PM" src="https://user-images.githubusercontent.com/120753142/208209114-416a337f-78c6-4e52-baee-cc28dd2155b5.png">

**Comment by openaudible** [comment]
All our signatures are valid and the software is signed. 
Its possible your gatekeeper settings are set to only open applications from the Apple Store. 
Go to Apple Settings, search for gatekeeper, and make sure its set to App Store and identified developers.

You can also try to view the application in Finder, then select the app and right click it and select Open from the menu and you might be able to open it anyway (after a warning about Apple having not detected any malicious software.)

**Comment by JimFitt** [comment]
This does not make sense. I downloaded and installed your software on this computer previously. And it will not open now at all. 

How do I retrieve my license? I’m going to remove it altogether and reinstall.

**Comment by JimFitt** [comment]
Hi, is there anyone there who can help?

**Comment by JimFitt** [comment]
> All our signatures are valid and the software is signed. Its possible your gatekeeper settings are set to only open applications from the Apple Store. Go to Apple Settings, search for gatekeeper, and make sure its set to App Store and identified developers.
> 
> You can also try to view the application in Finder, then select the app and right click it and select Open from the menu and you might be able to open it anyway (after a warning about Apple having not detected any malicious software.)

Nothing seems to work. Can I remove this from my computer and reinstall? If so, how can I retrieve my license?

**Comment by JimFitt** [comment]
> Yes. I did this. When the file downloaded I moved it to Applications as you side. Now the program will not open at all with this message... <img alt="Screenshot 2022-12-16 at 7 46 54 PM" width="282" src="https://user-images.githubusercontent.com/120753142/208209114-416a337f-78c6-4e52-baee-cc28dd2155b5.png">

Can I remove this from my computer and reinstall? If so, how can I retrieve my license?

**Comment by openaudible** [comment]
You can simply toss the application. Your settings and license are saved in your preferences directory that is not changed when you upgrade the application.

It may be that you have Gate Keeper settings on that don't allow apps not on the App Store to run.

Go to settings, type Gate Keeper, and make sure the setting is set to Allow Apps from App Store and Identified Developers.

Another thing that helps is when you run the app the first time, right click on the OpenAudible application and select "Open".

Hope that helps!
