### ISSUE TITLE
Transferring my iTunes purchased book to mp3

### ISSUE THREAD

**Issue by heatherstull** [openaudible/openaudible#1083]
I own a book that I purchased in Apple Books. I can see it in my desktop iTunes and I can see it in the folder in my computer. But when I add it to OpenAudible, it stays in the M4B format. I need to convert it to mp3 in order to add it to my child's yoto player. Is there a way to do that in OpenAudible? Or did I just purchase this for nothing?

**Comment by heatherstull** [comment]
I do see the "Action" to Convert to mp3 but its grayed out and I can't select it even when my book is selected.

**Comment by openaudible** [comment]
We don’t support iTunes books. Just Audible and plain mp3/m4b books.
