### ISSUE TITLE
I can't find the source code anymore.

### ISSUE THREAD

**Issue by Alexander-Metzger** [openaudible/openaudible#1084]
Hello, I bought OpenAudible a while ago, and I wanted to look at the source code now. But I can't find it anywhere. This is a great injustice as well as a risk to people's freedom as well as their privacy.

**Comment by openaudible** [comment]
Duplicate

**Comment by Alexander-Metzger** [comment]
> Duplicate

You might make it Free Software again because everything else is injust. Free Software is not just about other people contributing to your projekt, it's about knowing what I run on my computer and how I can exercise control over it.

**Comment by openaudible** [comment]
Thank you for your purchase. We're working on new features to make it even better. 
 
We didn't get any source code contributions for the year that it was open source. Just a few reports of typos. So it is closed.

**Comment by Alexander-Metzger** [comment]
> Thank you for your purchase. We're working on new features to make it even better.
> 
> We didn't get any source code contributions for the year that it was open source. Just a few reports of typos. So it is closed.

You don't even have to accept changes, just show your community the source code. That is 0% work and you'd have an ethical product. Its not just about technical advantages.

**Comment by openaudible** [comment]
There is nothing unethical about having a commercial version of an open source project that was 100% written in house. 
If you've written a multi-year open source project and surviving on donations, let me know!

**Comment by Alexander-Metzger** [comment]
> There is nothing unethical about having a commercial version of an open source project that was 100% written in house. If you've written a multi-year open source project and surviving on donations, let me know!

If it would still be open I'd fully agree with you but it isn't anymore. There are no objections to make such a "commercial" version with accesible source code. People deserve to know what they run on their machines. @openaudible @machshev
