### ISSUE TITLE
PC crashes when trying to convert very large audiobook to MP3

### ISSUE THREAD

**Issue by trinity654** [openaudible/openaudible#1085]
My PC crashes when trying to convert a large audiobook to MP3. I also tried it on a higher spec laptop and the same thing happened. Have tried 5 or 6 times and it crashes the OS every time (both linux and windows). 

It is several GB in size (the complete works of Orwell). I can try converting to lower quality MP3 but this is not desirable. Is there another fix? For example, can I split the AAX file and then convert each part to MP3 separately? And can I do this and not lose any of the metadata about the book? 

**Note: My mp3 player won't play m4b. I need a hack so I can convert this aax file to high quality mp3 in chapters.** 

Thank you

**Comment by trinity654** [comment]
The whole application failed and the PC froze so that I had to restart it each time I tried to convert (usually once it was abuout 90% complete).

Today I re-downloaded the aax file and tried again. This time, when it was about 70% complete I got the following error message: https://i.imgur.com/e0YWLDs.png

This has not happened before. So maybe the first aax file was indeed corrupt. 

Is there a fix for this error?

RAM seems fine. 
 
Thanks

**Comment by openaudible** [comment]
Check that you have plenty of disk space. 

Next, Please open the file menu: console. That shows the error log. Any error converting will show there.  Copy and paste the last 20 or so lines, removing any personal info. You can paste here or email us (OpenAudible at email.tg)

**Comment by trinity654** [comment]
Success. Did it on my more powerful work PC. Not ideal as it meant I had to use my license code here when I likely won't use this machine for OpenAudible again. But the main thing is, it is done. I think it was more an issue with my home PCs not being so powerful (the audiobook ended up being 5 GB in MP3 format :D). Thank you for your help!

**Comment by openaudible** [comment]
Glad it is working. The license can be used on any number of computers-- only limited to the number of Audible accounts. (5).

We test on very low-end computers. But it is possible you ran out of disk space-- we use a temporary directory that needs lots of room as well as the library destination (which can be on a different drive.) But that is a very long/big book. If you run it again on the less powerful machine, always happy to look at the error log for you.
