### ISSUE TITLE
download will not open

### ISSUE THREAD

**Issue by mikedelma88** [openaudible/openaudible#1086]
after downloading file I receive the message Unconfirmed 222323.crddownload will not allow me to open it. Does your program work on windows 11?

**Comment by openaudible** [comment]
Yes. This could be one of several things. 

Look at your browser's Download status.. make sure the file completes downloading and any warnings or errors are looked at. It should show as fully downloaded in your browser. Its possible it simply hasn't downloaded fully. 

Check that your anti-virus isn't blocking the download.

Try a downloading from different web browser. 

The installer app should download as OpenAudible.exe and is digitally signed. There should be no malware/virus warnings for it.

**Comment by openaudible** [comment]
Looks like Edge has a new warning:
Just click "keep"... Or right-click and report as safe and click Keep.
![uncommon_download_warning](https://user-images.githubusercontent.com/30847528/209009009-6b3a0a0d-1dd2-4615-8b18-bcf520e1ee5a.png)
