### ISSUE TITLE
Can't select a folder for split mp3 file

### ISSUE THREAD

**Issue by flemyri** [openaudible/openaudible#1087]
Hi there, looking for help. I'd like to split an mp3 file into chapters. When asked to select a folder I can do so, but then I can not start the splitting. Here's a screenshot. Am I blind? What do I have to do?
Many thanks in advance.
<img width="861" alt="Bildschirmfoto 2022-12-21 um 22 19 15" src="https://user-images.githubusercontent.com/121200049/209006486-01b2b103-2ba7-4ba5-b2ce-00b36f29e625.png">

**Comment by openaudible** [comment]
There are two ways to split a book. 
Right click on an existing book in the OpenAudible library and split.
The second, is to split a random MP3/M4B/M4A file that isn't in the library, that's done from the file menu.
It looks like you chose the second, so it is asking you to find an MP3/M4A/M4B file.

**Comment by flemyri** [comment]
Things can be so easy. Thank you very much! :)
