### ISSUE TITLE
audible.it

### ISSUE THREAD

**Issue by pinna78** [openaudible/openaudible#109]
After surfing audible.com I get redirected to audible.it, but the software does not recognize my login status.
Do you plan to support this country?

**Comment by openaudible** [comment]
We can try! Log into Audible using the OpenAudible web browser (CTRL-B). Then go to your library of books. What is the URL at the top of the page? We expect it to end in /lib but we don't have an ".it" audible account. From there, we may need a copy of the .html in your library's first page, which you can post using https://pastebin.com/ or email to us.

**Comment by pinna78** [comment]
Thank you! 
I can't find a way to see my library from the website and the /lib url gives a 404.
I checked every link of the page :(

**Comment by openaudible** [comment]
That is strange. Are you saying there is no web browser interface for audible in italy? How do you buy books? Do you have an audible.it account?  

We would need to see the URL you use to view all of the books you've ordered. 

For instance, in the US, the iPhone audible app doesn't allow users to buy books-- that can only be done through the web site. (or Apple would take $$). So we log on to audible.com, view books, buy them, and they show in a list. That list is on a page ending in /lib.  I don't understand how you view and buy books.

Hope that makes sense! Let me know. I am curious.

**Comment by pinna78** [comment]
Yes I have an audible.it account. Here in Italy we pay 10€/month to get unlimited books, we cannot purchase a single book.
From the website I can add a book to my library and listen it immediately: after clicking the button “Add to my library” the same button becomes “Play it now” and it shows the audible cloud player in a popup. This is the only way to play it from the website, I can’t see my library, and to listen it again I need to find it again from the store and press the play button.
From the app I can do the same things, but also displaying all books previously added to my library.

**Comment by openaudible** [comment]
Thank you for the explanation. Unless you can download an AAX file for a book, it doesn't appear that OpenAudible will work with your region. Sorry!
