### ISSUE TITLE
Titles not displayed

### ISSUE THREAD

**Issue by schoedel0** [openaudible/openaudible#1090]
Books seem to be downloaded ok.  There are files in the books, AAX and M4B subdirectories.  But they are not displayed in the OpenAudible window.  Also, I cannot connect to Audible - I get the following error: java.lang.RuntimeException:java.lan.Exception:org.eclipse.swt.SWTErrror:No more handles bacause there is no underlying browser available.  Please ensure the WebKit with its GTK3.x bindings is istalled (WebKit2 API level is preferred). Additionally, please note GTK4 does not currently have Browser support.

Note Firefox and Chrome browsers are running.  OS is Fedora 37.
Thanks for any help with this.

**Comment by openaudible** [comment]
Try a full library rescan after connecting.. or a library refresh. which should pick up any books in your directory that aren't showing in the library.

**Comment by schoedel0** [comment]
Appreciate the quick response.  The library sync commands are "greyed" out.  The refresh command had no effect.

**Comment by openaudible** [comment]
You need to "Connect to Audible" from the Controls menu before the Sync will work.

**Comment by schoedel0** [comment]
A bit closer.  There was a dependency, webkit2gtk4 that needed to be installed in order to connect to audible.  After that the sync worked.  But still no books are displayed.  Perhaps another software dependency?

**Comment by openaudible** [comment]
Thanks for the update. We are removing the browser requirement in the next beta.. 

It should say "Connected: Yes" in Library status (upper left)
After that, a full rescan should work. The demo only finds purchased books.. 
Look for any errors in the console. Feel free to send a bug if you see something (or carefully copy and paste here, removing any PII).

**Comment by openaudible** [comment]
https://openaudible.org/beta is the latest beta that may help.

**Comment by openaudible** [comment]
The demo version will only get books you’ve purchased. After a rescan, take a look at the logs for any books that might have been skipped. 

If the UI shows books in the library status pane, but not in the book table, try the beta. 

Feel free to add to this issue if still stuck.

**Comment by schoedel0** [comment]
A bit closer.  There was a dependency, webkit2gtk4 that needed to be installed in order to connect to audible.  After that the sync worked.  But still no books are displayed.  Perhaps another software dependency?

(https://user-images.githubusercontent.com/78050112/210190352-d6570b8a-0dad-4481-a86e-ee65163cf474.png)

Beta made things worse.  Just brought up a "Yikes!" message.

**Comment by openaudible** [comment]
Thank you for that report. That one has been fixed in beta 6. Give it another shot if you can..
