### ISSUE TITLE
Feature Request: Mark as read

### ISSUE THREAD

**Issue by appmu** [openaudible/openaudible#1091]
Hi,

Is there a way to mark a book as read? It would be nice to have it as a feature if not possible with the current design.

Thanks for your consideration.

**Comment by openaudible** [comment]
Nice idea! Thanks for the suggestion. Marked as a feature suggestion. Pretty easy to implement... but working on getting 3.6.4 out soon.

**Comment by openaudible** [comment]
Maybe a read status:

None, read, unread, want to read, did not finish

(Did not finish for the books not worth reading…)

**Comment by appmu** [comment]
> Maybe a read status:
> 
> None, read, unread, want to read, did not finish

Sounds good to me.

**Comment by catayee** [comment]
> Maybe a read status:
> 
> None, read, unread, want to read, did not finish
> 
> (Did not finish for the books not worth reading…)

Maybe in combination with a date field... so I can see how often and when I finished the book. For example:

Finished:
12/23/2013
05/10/2017
10/19/2022

**Comment by openaudible** [comment]
Added to the latest 3.7 release. To set a date, you'll need to manually add it to the "Read Status" in the Get Info dialog.

**Comment by openaudible** [comment]
See: https://openaudible.org/docs#read_status

**Comment by appmu** [comment]
Thanks for implementing this.

I also feel it would be nice to have a date-time field that indicates finished times of reading the book and the ability to automatically add the time when the read status is changed to Finished.
