### ISSUE TITLE
Importing books downloaded from another account

### ISSUE THREAD

**Issue by appmu** [openaudible/openaudible#1092]
Hi,

What would be the proper steps to import (add) books downloaded before?

There are more than 1k books downloaded already with an account A. Relevant `aax` files are in the `aax` directory, say `G:\OpenAudible\aax`.
Now I'm connecting with an account B and about 100 books are added to the Audbile library. From the preference (Edit -> Preference), the library directory path is set to `G:\OpenAudible`.

I expected that the books downloaded before will be loaded but they don't appear in the list. I tried:

  - From the menu, I chose Controls -> Refresh Files and a window titled Importing... appeared and it took a while to parse all the files but after the window was closed, nothing changed. 
  - From the menu, I chose Files -> Import Books and selected one `aax` file and it did not get added.

Thank you.

OpenAudible: v3.6.3
OS: Windows 10 64bit

**Comment by openaudible** [comment]
I wouldn't import AAX files-- they  have limited meta data included in then. Instead, I would import the M4B/MP3 files. You can also try importing the books.json file if its from another directory/account. Make a backup of your library though.
If you try to import a book and it doesn't seem to add it, check the console log for more details.

**Comment by appmu** [comment]
I had converted most audio files to mp3 as there were not enough space before. I'm planning to have all of them to be converted into m4b to ensure the audio quality. Only there are 2 m4b files with the different account.

I tried: 

  - `File -> Import Books` but couldn't choose `m4b` files. 
  - Drag & dropping a m4b file to the OpenAudible UI window. But after the Importing window, it is not added even after restarting the program.

The `books.json` file seems to have been overwritten while doing some import operations as the modified time has been updated. And the old one is gone and I didn't back it up.

**Comment by openaudible** [comment]
Look at the console window. All major activities produce logs of what happens. The file is probably skipped for some reason--which should be logged.

**Comment by appmu** [comment]
It seems books are not added when drag & dropping from a sub-directory inside the library directory. In my case, I was dropping a m4b file from `G:\OpenAudible\books.done` which I manually created and placed read books. If I move the `books.done` directory outside the library directory and dropping the file onto the UI, it is successfully added.

When I try to drop a `aax` file downloaded with the different account, the book is not added and the console says,

```
org.openaudible.desktop.swt.manager.ImportExport importFiles
SEVERE: import of G:\OpenAudible\aax\sample.AAX failed.
java.io.IOException: Unable to import aaxc files. Required decryption keys unavailable. File=G:\OpenAudible\aax\sample.AAX
	at org.openaudible.convert.FFProbeToBook.probeToBook(FFProbeToBook.java:195)
	at org.openaudible.convert.FFProbeToBook.probeToBook(FFProbeToBook.java:21)
	at org.openaudible.desktop.swt.manager.ImportExport.newBook(ImportExport.java:687)
	at org.openaudible.desktop.swt.manager.ImportExport.audioFileToBook(ImportExport.java:739)
	at org.openaudible.desktop.swt.manager.ImportExport.importAAX(ImportExport.java:702)
	at org.openaudible.desktop.swt.manager.ImportExport._importFile(ImportExport.java:323)
	at org.openaudible.desktop.swt.manager.ImportExport.importFiles(ImportExport.java:136)
	at org.openaudible.desktop.swt.manager.ImportExport$1.run(ImportExport.java:1149)
```

Does this mean that I have to start over all the 1k books if I want them to be m4b?

**Comment by openaudible** [comment]
Sounds like you might have gotten those AAX files from somewhere other than openaudible. AAXC files can't be decoded since the keys are missing.  Importing from AAX is not recommended. Sorry.

**Comment by appmu** [comment]
No. They were downloaded with OpenAudible with a different account which I don't have access any more.

**Comment by appmu** [comment]
Why did you close the topic although it's not solved at all? 

Also,  please respond to this question. I don't want to download more than 1k books again.

> Does this mean that I have to start over all the 1k books if I want them to be m4b?

**Comment by openaudible** [comment]
There is no way to decode an aaxc file without the cryptographic keys. Download and immediately convert to m4b, and optionally delete the aax file to save space.  We can't help further so the issue is closed.

**Comment by appmu** [comment]
Not sure it is an aaxc file or aax file from the mere user's point of view. The file was saved with the capitalized `AAX` file extension with OpenAudible about 6 months ago in the aax directory.

Does this mean that with the current design, it is not possible to import old aax files downloaded with a different account?
