### ISSUE TITLE
Plex not recognising book

### ISSUE THREAD

**Issue by bporima** [openaudible/openaudible#1093]
Hi,
following problem: book downloaded and (seemingly) transcoded ok as .m4b; the file can be played in other players, e.g. Apple Books. But Plex is not recognising the file as audiobook (or does not recognise the file at all). First time this happens in ca. 150 audiobooks; is there anything i can do to diagnose what may be wrong with the file?  (Licence is valid, btw.)

The book URL is this one:
https://www.audible.de/pd/Der-Heimweg-Hoerbuch/B08DRLS5SG

Many thanks for looking into it!
Best regards,
Marco

**Comment by oboe45** [comment]
.M4b don't work for me in flex, just change the .m4a to .m4b and it works

**Comment by openaudible** [comment]
If you have several .m4b files and only one doesn't work.. (but plays on other players) I would suggest looking at the plex logs or post a question there. We have some limited experience with plex but not enough to really know what could be the cause. Obviously we want our books to be compatible with as many platforms as possible.. so feel free to keep us posted.
