### ISSUE TITLE
Feature Request: Ability to convert to M4B/MP3 on demand

### ISSUE THREAD

**Issue by bilcorry** [openaudible/openaudible#1094]
By default, my library is auto-converted to M4B.  But my wife's player doesn't support M4B, so for her, I have to convert it to MP3.  It would be handy if I could select "Convert to MP3" from the Actions menu on any of the books and convert just that one book to MP3. 

I did try setting the "Audio Output Format" to MP3, but it started converting my entire library.  Maybe if I unselected "Automatically convert audio files" I could have select a single book to convert?

Just seems like it would be easier if you could convert any book to either format (M4B or MP3) using the Action menu.

**Comment by openaudible** [comment]
I know it is a little confusing. But it gets worse when you want to have some books mp3, some m4b, and some both.. We would prefer you stick with m4b unless you really need to get an mp3. In which case, yes, you need to switch the prefs to mp3 and re-encode. And yes, turning on automatic convert can be risky. But with m4b, conversions are super quick. 
We're going to keep it the way it is, but will keep it in mind when we do UI changes. Thank you!
