### ISSUE TITLE
Feature Request: Downloaded Time table column and a status bar

### ISSUE THREAD

**Issue by appmu** [openaudible/openaudible#1097]
It appears Amazon limits the number of downloadable books per day which seems to be around 100. If the number of downloaded books exceeds the certain limit, the user becomes unable to download anything including PDF files, even from the Audible mobile app, for a couple of days. After that, the connection usually gets recovered. 

So there needs to be a way to know how many books are downloaded within a particular time span. One simple solution would be to implement a new table column named Downloaded Time so that the user can sort items by it and select them and count them. But there doesn't seem to be a way to instantly know the number of selected items either.  So it would be nice to have a status bar at the bottom of the window that indicates some item info including a count of selected items.

Thanks for your consideration.

**Comment by openaudible** [comment]
We haven't gotten any other reports that this is a common thing. 
Are you using a anonymous proxy service? Which locale (audible region) are you seeing this in?

**Comment by appmu** [comment]
JP.

**Comment by openaudible** [comment]
Will keep monitoring this.. but closing for now. So far unconfirmed.

**Comment by openaudible** [comment]
Haven't been able to reproduce this. Closing for now.
