### ISSUE TITLE
Beta Testers Needed

### ISSUE THREAD

**Issue by openaudible** [openaudible/openaudible#1098]
Looking for beta testers to try the new OpenAudible.

We added some new features to allow logging in with application dialogs... instead of the web browser.. although we also support logging on with a browser as well.

Would like to get some testing, especially from users in different regions and ones that use 2 factor authentication.

If you find any problems, feel free to post them here. If it works for you or have other ideas, let us know. 

https://openaudible.org/beta

**Comment by mjmcnamara** [comment]
Hi, I received a java.lang.NullPointerException error message box after inputting username and password and clicking Next. I am in the US region, I have 2FA enabled, and I have a long password (40 characters). The web browser login worked fine. Are there any additional details or logs I can provide to help?

**Comment by openaudible** [comment]
If you can open the console and find the "NullPointerException" error and send it to me (openaudible at email dot tg) that would be great. Or send a bug report.. But if you already quit the app, you'd need to log out, then log back in.. and from there, you could send a bug report. This would be a big help. If you want to copy and paste the full error here, that's ok, just make sure there isn't any http urls or identifiers in the log.

**Comment by openaudible** [comment]
I think we got the NullPointerException figured out in beta 8. Caused by an unexpected captcha request. Thank you for the report.

**Comment by tomsem** [comment]
I installed 3.6.3.11beta this morning and initially had captcha prompt, which I couldn't get past. But at some point OTP kicked in and I was able to login with SMS code. Web browser login failed with SEVERE: showError: Error registering virtual device.

**Comment by openaudible** [comment]
Thank you for the report! Should now be fixed in the 3.7 release.
