### ISSUE TITLE
Feature Request: Add 'Series' Info to M4B File

### ISSUE THREAD

**Issue by jamesbrindle** [openaudible/openaudible#1099]
Hi,

I started to use the M4B format when converting the audiobooks in order to get the chapter information (useful in me audiobook player).

I also have another app, which organises the books nicely in a folder structure, but I noticed the resulting M4B file is lacking the 'Series' meta data... Specifically, tags:

* SERIES
* SERIES-PART

Also, the 'genre' tag is just 'Audiobook', rather than a descriptive genre, i.e. 'Crime', or 'Science Fiction', which is also useful for me app (the category of book doesn't need to be in the 'genre' tag, in MP3 it's under 'book_genre'.

Looking at the code in this repo (I know it's out of date), you specifically remove the tags when converting using ffmpeg and add better ones, brought down from Audible itself.

Is there any chance you could include this better meta data, like you to for MP3 format, but for M4B as well?

Awesome app by the way!

**Comment by openaudible** [comment]
The m4b format is not super flexible. We tell ffmpeg to add all the meta data we use for mp3 to go into m4b.. but custom tags are not allowed, as far as we can tell. (Apple wrote the standard, and you can't just add tags...)

https://atomicparsley.sourceforge.net/mpeg-4files.html

If there are example m4b files that have more tags that we're not aware of, let us know.

We do use the term "audiobook" for the genre as there is a fixed list of genres available and that is the one we are supposed to use for audiobooks. Again, unfortunate, but there it is.

**Comment by jamesbrindle** [comment]
Hey,

Thanks for the reply...

I've been reading up and doing some digging myself... And yes, it is indeed difficult to add custom tags. I've discovered you certainly can't do it with FFMpeg.

There is however, a single meta data 'field type' (----) under a specific 'namespace' (com.apple.iTunes), that allows 'extra' tags to be added.

https://github.com/Zeugma440/atldotnet/wiki/Focus-on-non-standard-fields

I've successfully managed to add custom tags, with a C# library: atldotnet (although I'm aware you might not use C#, but just highlighting, it is somewhat possible, but probably pointless, since it's not standard).

https://github.com/Zeugma440/atldotnet

My m4b tags now look like this (see *'extra:'* node):

```
"Composer": "Dick Hill",
"Genre": "Audiobook",
"Recorded_Date": "2008-01-01",
"Encoded_Date": "UTC 2021-07-23 18:24:43",
"Tagged_Date": "UTC 2021-07-23 18:24:43",
"File_Created_Date": "UTC 2023-01-06 11:50:18.126",
"File_Created_Date_Local": "2023-01-06 11:50:18.126",
"File_Modified_Date": "UTC 2023-01-06 11:50:32.548",
"File_Modified_Date_Local": "2023-01-06 11:50:32.548",
"Encoded_Application": "Lavf59.20.101",
"Copyright": "&#169;1968 Arthur C. Clarke;&#169;1968 Polaris Productions, Inc.;(P)2000 Brilliance Audio",
"Cover": "Yes",
"Comment": "From the savannas of Africa at the dawn of mankind to the rings of Saturn as man adventures to the outer rim of our solar system,  / 2001: A Space Odyssey is a journey unlike any other....",
"extra": {
"SERIES": "Space Odyssey Series",
"SERIES-PART": "1",
"NRT": "Dick Hill",
"book_genre": "Literature & Fiction, Classics, Science Fiction & Fantasy, Fantasy, Science Fiction & Fantasy, Science Fiction, Hard Science Fiction, Science Fiction & Fantasy, Science Fiction, Space Opera",
"ASIN": "B004EW2292"
}
},
```

I've written the app that organises my library, and puts them in a folder structure, 'grouping' series, so I kind of needed it... I think it's very odd m4b metadata standards don't include the series and series number, by default... But there you go.

I don't expect you to make any changes now, since it's probably only useful for me alone (so this can be closed), and I've managed to implement a workaround. I just have an automated task that looks at the 'audible library data' XML, grabs the genres and series from there *(I've kept 'genre' as Audiobook, as you suggested, and added another tag 'book_genre' to differentiate).*

### However...

There is one standard tag FYI, in which I only noticed after spending an unreasonable amount of time working out how to add custom tags. It's called **'Grouping'** and is a text field... You could possibly use that, if you get bored? I'd have thought Audible would have actually utilised this actually, since it's empty.


Thanks again,

Kind regards,

Jamie

**Comment by openaudible** [comment]
Will take a look at supporting better meta data in m4b. Definitely seems like there is some room for additional tags.

**Comment by feldegast** [comment]
I tend to put Series info in the Group field....

**Comment by openaudible** [comment]
We added this to the beta... So it is embedded, but we're not sure if any players will pick it up. 

We may need to make a discussion about the topic-- as it isn't really supported by ffmpeg and we had to modify ffmpeg to allow setting additional meta in the m4a/m4b file format.

https://openaudible.org/beta
Any feedback you can reply to this thread, but closing to keep the clutter down.
