### ISSUE TITLE
There is no *.desktop file

### ISSUE THREAD

**Issue by dataCobra** [openaudible/openaudible#110]
I don't know why, but there is no *.desktop file for this software. I think it would be really outstanding if we (the users) would get a *.desktop file so our desktop environments like (Gnome, KDE, XFCE, etc.)  are going to find it and let it show up in the application bar.

**Comment by openaudible** [comment]
We use install4j that builds the desktop file automatically. For my test ubuntu, it creates the desktop file at: /opt/OpenAudible/OpenAudible.desktop 

There are three release installers for linux-- I used the .sh file installer for my testing. 

Is there anything wrong with ours?

`cat /opt/OpenAudible/OpenAudible.desktop
#!/usr/bin/env xdg-open
[Desktop Entry]
Type=Application
Name=OpenAudible
Exec=/bin/sh "/opt/OpenAudible/OpenAudible"
Icon=/opt/OpenAudible/.install4j/OpenAudible.png
Categories=Application;
`

**Comment by dataCobra** [comment]
I used the *.deb file to install your software.

The *.desktop file should normally be in one of the following directories:
1. /usr/share/applications/
2. /home/$USERNAME/.local/share/applications/

Thats my *.desktop file:
[Desktop Entry]
Name=OpenAudible
Comment=Hear your Audiobooks on PC and also convert them if you want.
GenericName=Audiobook Player
Exec=/usr/local/bin/OpenAudible
Icon=OpenAudible
Type=Application
Categories=Audio;Player;

**Comment by openaudible** [comment]
Did the .deb installer create an OpenAudible.desktop file with the rest of the application files? Maybe it just needs to be found and linked into your /usr/share/applications?  I am not a linux on desktop person.

**Comment by dataCobra** [comment]
The correct way for software under Linux is to create a *.desktop file under **/usr/share/applications**. It's not normal for a Linux user to find the *.desktop file themselves and link it to the correct folder. The way you describe is something for advanced Linux users, not for beginners.

It should work right out of the box.

**Comment by openaudible** [comment]
It looks like a setting in install4j. I will take a look. Re-open if not fixed in the next release. Thanks for the heads up.

**Comment by openaudible** [comment]
Re-opening. 

Attempted to add a screen in install4j for 1.4.4 and not sure it worked. 

dpkg -i OpenAudible.*.deb  doesn't add any links to 

For now, 
sudo ln -s /opt/OpenAudible/OpenAudible.desktop /usr/share/OpenAudible.desktop

The OpenAudible linux installer .sh is a GUI app that does appear to work.

**Comment by openaudible** [comment]
Posted 1.4.4 with an updated installer/deb/rpm files.

If anyone has suggestions on getting it to work, let me know.

**Comment by openaudible** [comment]
Sounds like install4j doesn't currently have that option for .deb or .rpm files (but may be added to version 8). It would probably break the ability to do non-root installs. So the accepted way to "fix" is to manually link the /opt/OpenAudible.desktop to the appropriate directory.
