### ISSUE TITLE
Error aax invalid

### ISSUE THREAD

**Issue by lvomo** [openaudible/openaudible#1100]
I keep receiving the error that three of my books are invalid files. Ive confirmed they are all downloadable, aax files, that I purchased less than 6 hrs ago. I just paid for the updated version of openaudible and I'm opening the files through OA. 

I've already filled out the form to check the aax file as well.

**Comment by lvomo** [comment]
I also was just able to download a bunch that were "free" with membership. I was unable to do that in the past. Still cannot download or convert the three though that are confirmed aax files.

**Comment by openaudible** [comment]
Try deleting them.. Then, connect to audible, full rescan, download one book, convert to m4b or mp3. If you still get the error, take a look at the error log.. then send a bug report from the About/Help menu and we can take a look.

**Comment by lvomo** [comment]
Okay I deleted and tried again and still got the same error. I just reported

**Comment by lvomo** [comment]
{
 "date": "Fri Jan 06 14:40:24 AKST 2023",
 "memory": "Memory: Using 127.14Mb of 2048Mb (6%) Min 33.329Mb Max 127.14Mb",
 "library_stats": {
  "Downloading": "",
  "PDFs": "0/0",
  "Connected": "Yes",
  "Hours": "473",
  "M4B_Files": "53",
  "License": "Valid",
  "AAX_Files": "60",
  "To_Convert": "2",
  "MP3_Files": "0",
  "Missing_Links": "0",
  "To_Download": "0",
  "Converting": "",
  "Podcasts": "0",
  "Region": "US",
  "Books": "68",
  "M4A_Files": "0",
  "Ignored": "13"
 },
 "compile_date": "2023-01-05 05:01",
 "version": "3.6.3.7",
 "demo": false,
 "platform": "mac_aarch64",
 "prefs": {
  "disableVersionCheck": false,
  "autoConvert": true,
  "language": "en",
  "uid": "1640232857720",
  "browseFileCmd": "",
  "browser": "",
  "html": false,
  "theme": "",
  "migrated": true,
  "browseWebCmd": "",
  "autoDeleteAAX": false,
  "lastVersion": "3.6.3.7",
  "playFileCmd": "",
  "webPageIncludeMP3": true,
  "format": "M4B",
  "autoDownload": false,
  "autoWebPage": false,
  "autoRefreshMinutes": 0,
  "autoConnect": false,
  "concurrentConversions": 3,
  "podcasts": false,
  "mp3Quality": "",
  "concurrentDownloads": 3,
  "autoPDF": true,
  "region": "US"
 },
 "books.json": "/Users/sunsetpeak/Library/OpenAudible/books.json",
 "java": {
  "gopherProxySet": "false",
  "awt.toolkit": "sun.lwawt.macosx.LWCToolkit",
  "java.specification.version": "11",
  "install4j.launcherId": "22",
  "sun.cpu.isalist": "",
  "sun.jnu.encoding": "UTF-8",
  "java.class.path": "/Applications/OpenAudible.app/Contents/Resources/app/.install4j/i4jruntime.jar:/Applications/OpenAudible.app/Contents/Resources/app/./openaudible_mac_aarch64.jar:/Applications/OpenAudible.app/Contents/Resources/app/openaudible_mac_aarch64.jar",
  "sun.awt.enableExtraMouseButtons": "true",
  "java.vm.vendor": "Eclipse Adoptium",
  "sun.arch.data.model": "64",
  "i4j.ownBundlePath": "/Applications/OpenAudible.app",
  "install4j.exeDir": "/Applications/",
  "sun.font.fontmanager": "sun.font.CFontManager",
  "java.vendor.url": "https://adoptium.net/",
  "user.timezone": "America/Anchorage",
  "os.name": "Mac OS X",
  "java.vm.specification.version": "11",
  "sun.java.launcher": "SUN_STANDARD",
  "user.country": "US",
  "sun.boot.library.path": "/Applications/OpenAudible.app/Contents/Resources/jre.bundle/Contents/Home/lib",
  "sun.java.command": "com.install4j.runtime.launcher.MacLauncher",
  "http.nonProxyHosts": "local|*.local|169.254/16|*.169.254/16",
  "jdk.debug": "release",
  "sun.cpu.endian": "little",
  "user.home": "/Users/sunsetpeak",
  "user.language": "en",
  "java.specification.vendor": "Oracle Corporation",
  "java.version.date": "2022-04-19",
  "java.home": "/Applications/OpenAudible.app/Contents/Resources/jre.bundle/Contents/Home",
  "file.separator": "/",
  "java.vm.compressedOopsMode": "Zero based",
  "line.separator": "\n",
  "java.specification.name": "Java Platform API Specification",
  "java.vm.specification.vendor": "Oracle Corporation",
  "java.awt.graphicsenv": "sun.awt.CGraphicsEnvironment",
  "exe4j.moduleName": "/Applications/OpenAudible.app",
  "sun.management.compiler": "HotSpot 64-Bit Tiered Compilers",
  "ftp.nonProxyHosts": "local|*.local|169.254/16|*.169.254/16",
  "java.runtime.version": "11.0.15+10",
  "org.eclipse.swt.internal.deviceZoom": "200",
  "user.name": "sunsetpeak",
  "path.separator": ":",
  "os.version": "12.4",
  "java.runtime.name": "OpenJDK Runtime Environment",
  "file.encoding": "UTF-8",
  "java.vm.name": "OpenJDK 64-Bit Server VM",
  "java.vendor.version": "Temurin-11.0.15+10",
  "i4j.jreBundle": "/Applications/OpenAudible.app/Contents/Resources/jre.bundle",
  "install4j.appDir": "/Applications/OpenAudible.app/Contents/Resources/app/",
  "java.vendor.url.bug": "https://github.com/adoptium/adoptium-support/issues",
  "java.io.tmpdir": "/var/folders/qx/l6r5_mz163n1ymgd_sjwzkfc0000gn/T/",
  "java.version": "11.0.15",
  "user.dir": "/Applications/OpenAudible.app/Contents/Resources/app",
  "os.arch": "aarch64",
  "java.vm.specification.name": "Java Virtual Machine Specification",
  "java.awt.printerjob": "sun.lwawt.macosx.CPrinterJob",
  "vm_args": [
   "-Dfile.encoding=UTF-8",
   "-Dfile.encoding=UTF-8",
   "-Dsun.jnu.encoding=UTF-8",
   "-Dinstall4j.launcherId=22",
   "-Dinstall4j.swt=true",
   "-Dexe4j.moduleName=/Applications/OpenAudible.app",
   "-Di4j.ownBundlePath=/Applications/OpenAudible.app",
   "-Di4j.jreBundle=/Applications/OpenAudible.app/Contents/Resources/jre.bundle"
  ],
  "sun.os.patch.level": "unknown",
  "java.library.path": "/Users/sunsetpeak/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.",
  "java.vm.info": "mixed mode",
  "java.vendor": "Eclipse Adoptium",
  "java.vm.version": "11.0.15+10",
  "sun.io.unicode.encoding": "UnicodeBig",
  "java.class.version": "55.0",
  "socksNonProxyHosts": "local|*.local|169.254/16|*.169.254/16",
  "install4j.swt": "true"
 },
 "directories": [
  {
   "path": "/Users/sunsetpeak/Library/OpenAudible",
   "kind": "BASE",
   "exists": true
  },
  {
   "path": "/Users/sunsetpeak/Library/OpenAudible/books",
   "kind": "BOOKS",
   "exists": true
  },
  {
   "path": "/Users/sunsetpeak/Library/OpenAudible/web",
   "kind": "WEB",
   "exists": false
  },
  {
   "path": "/Users/sunsetpeak/Library/OpenAudible",
   "kind": "META",
   "exists": true
  },
  {
   "path": "/Users/sunsetpeak/Library/OpenAudible/tmp",
   "kind": "TMP",
   "exists": true
  },
  {
   "path": "/Applications/OpenAudible.app/Contents/Resources/app",
   "kind": "APP",
   "exists": true
  }
 ],
 "gui": {
  "swt_platform": "cocoa",
  "main_window": "Rectangle {0, 25, 1019, 794}",
  "browser": {
   "prefer_chromium": false,
   "oa_chromium": "",
   "swtBrowserStyle": 0,
   "Desktop.isDesktopSupported": true,
   "externalBrowser": true,
   "Desktop.Action.BROWSE": true,
   "externalBrowserMode": "desktop",
   "oa_internal_browser": "",
   "browseWebCmd": ""
  },
  "display": {
   "highContrast": false,
   "bounds": "Rectangle {0, 0, 1440, 900}",
   "dpi": "Point {72, 72}"
  },
  "aspect": 1.2833753,
  "theme": {
   "dark_debug": "",
   "org.eclipse.swt.display.useSystemTheme": "null",
   "theme": "system",
   "is_dark": true
  },
  "table": {
   "col_width": 25,
   "2x": false,
   "col0Width": 25,
   "img_bounds": "Rectangle {0, 0, 14, 14}",
   "scale_down_1k": 500,
   "scale_up_1k": 2000
  },
  "swt_version": 4954
 },
 "region": "US",
 "beta": {
  "connected": true,
  "errors": false
 },
 "properties": {
  "oa_external": "",
  "os": "ProductName:\tmacOS\nProductVersion:\t12.4\nBuildVersion:\t21F79\n",
  "java.version": "11.0.15",
  "oa_ayce": "",
  "sun.jnu.encoding": "UTF-8",
  "locale": "LANG=\"en_US.UTF-8\"\nLC_COLLATE=\"en_US.UTF-8\"\nLC_CTYPE=\"en_US.UTF-8\"\nLC_MESSAGES=\"en_US.UTF-8\"\nLC_MONETARY=\"en_US.UTF-8\"\nLC_NUMERIC=\"en_US.UTF-8\"\nLC_TIME=\"en_US.UTF-8\"\nLC_ALL=\n",
  "oa_internal_browser": "",
  "oa_packaging": "",
  "mac_arch": {
   "system_arch": "arm64",
   "java_arch": "aarch64",
   "macVenturaOnIntel": false,
   "macM1RunningIntelVersion": false,
   "platform": "mac_aarch64"
  },
  "file.encoding": "UTF-8",
  "oa_chromium": "",
  "SWT_GTK3": "null",
  "OPENAUDIBLE_HOME": ""
 }
}

**Comment by openaudible** [comment]
That above was the diagnostics view. The Console log is found from the File: Console (CMD-E) menu.
Better to email the error to openaudible at email dot tg (or be sure to delete all URL's and anything that might be identifying.)

**Comment by lvomo** [comment]
I did email and haven't had a response.

**Comment by openaudible** [comment]
Thank you for the report. Confirmed! Great bug report. Fixing and will release a new beta shortly. Thank you.

**Comment by openaudible** [comment]
Fixed in latest beta: https://openaudible.org/beta
Let us know if that fixes it.

**Comment by openaudible** [comment]
Try the latest 3.7 version. https://openaudible.org/
You can reply here and/or send a bug report from the Help menu if still having issues.
