### ISSUE TITLE
Upgrade issues

### ISSUE THREAD

**Issue by HassoEccard** [openaudible/openaudible#1101]
Going from 3.6.2 to 3.6.3 on Intel mac Ventura 13.1 , I had the previously mentioned upgrade-crash loop which I got round by a fresh download. 

After that my license had expired, and pressing the 'Upgrade' button on the dialog, caused it to hang. I got a new licence by just doing a purchase on the website.

**Comment by openaudible** [comment]
If you paid for a full purchase instead of an upgrade, drop us a line (reply to the email from openaudible) and we'll refund the difference.

**Comment by HassoEccard** [comment]
Hi

I didn’t realise that there was a price difference.  

Give the difference to someone or a charity that needs it.

regards

Stephen

**Comment by openaudible** [comment]
Thank you. Will do.
