### ISSUE TITLE
Genre descriptor only says "audiobook" in M4B files, but could have much more and better data?

### ISSUE THREAD

**Issue by amjoythis** [openaudible/openaudible#1104]
I have noticed that the genre metadata loses information, when a book is removed from the online library.
When an audiobook is still in my online Audible library, its "genre" has plenty of useful info and OpenAudible displays it.
After I download and convert the book to M4B, and remove it from the online library, the M4B file works, but its metadata only states "audiobook", which leads to an inferior offline library.
All my offline titles suffer from this loss, with a useless "genre" descriptor.
I would like to have a function to enrich the metadata of existing M4Bs with the same data that I read, when the book is still in the online library. It could even be a companion JSON file with the exact same file name of the M4B.
Any solution?
Thank you.

**Comment by openaudible** [comment]
Unfortunately the m4b standard uses a fixed list of genres, so audiobook is as good as we can do with that field.
However, we are looking at adding additional meta data to the m4b files. Follow #1099
