### ISSUE TITLE
Any way to change bit rate after already downloading? 

### ISSUE THREAD

**Issue by criticalthinky** [openaudible/openaudible#1106]
For mp3 i chose 64 and i should have chosen higher.... is there anyway to redo everything or do I need to delete and redownload? Thanks.

**Comment by criticalthinky** [comment]
thank you for the response sir, yes I did delete those I think, or set them to delete. How should i proceed?

**Comment by openaudible** [comment]
Select one and "Show MP3". Then drag and drop into the trash. You can wait a while and OpenAudible will notice the change.. or you can "rescan files".. Or just quit and restart openaudible and those books can be re-encoded.

**Comment by criticalthinky** [comment]
Oh, if i quit and restart open audible they will be re-encoded? Im just worried because these are from the audible plus catalog and I'm not sure if they remove them? 
And then just to clarify... all i have to do is close and restart the application it'll re-encode everything even without the aax files?

**Comment by criticalthinky** [comment]
i downloaded many of these like 4 months ago... I don't think they removed them but I'm just kind of worried about it thanks

**Comment by criticalthinky** [comment]
dont think its re-encoding but not sure how to tell...to clarify i dont have any aax

**Comment by openaudible** [comment]
Well, they will still be in the trash, so it is pretty safe. but you can check that the AAX is still there by selecting the book and Action: Show AAX. If that is grayed out, then the aax file is missing and you might have to re-download. 

If "automatically encode" is checked in prefs, the app may automatically re-encode.. Maybe a good idea to turn off the automation.

**Comment by criticalthinky** [comment]
yeah its greyed out... so is my option right now to redownload aax? What do you think I should do? Can i redownload aax to a different folder and try that?

**Comment by criticalthinky** [comment]
hello
