### ISSUE TITLE
error connecting to audible for the first time

### ISSUE THREAD

**Issue by rmurawka01** [openaudible/openaudible#1107]
Hi, I just installed OpenAudible, and tried to connect to Audible from Controls>Connect to Audible. I select French region but URL generated an error like "URL entered doesn't match with any active page on our site"
I am on a Mac M1

regards

Richard

**Comment by rmurawka01** [comment]
it works when I select English langage for GUI. it didn't when I select French langage.

**Comment by openaudible** [comment]
For connecting, the region is for the audible account.. not for the language preference. 
But there is a language preference as well. 
I'll see if I can reproduce, but glad it is working.
