### ISSUE TITLE
Converting AAX to OOG Vorbis

### ISSUE THREAD

**Issue by namura123** [openaudible/openaudible#111]
It's very nice that you can convert AAX to MP3 but it would be so much better if there was a option to convert AAX to MP3 directly. If you could implement such an option I would be very thankful!
Thanks in advance.

**Comment by CrustyApplesniffer** [comment]
Do you mean ?

>  it would be so much better if there was a option to convert AAX to **_OOG Vorbis_** directly.

**Comment by borindal** [comment]
And it would be nice to to get the pure AAC from the AAX.

**Comment by borindal** [comment]
I think he meant OGG Vorbis...

**Comment by openaudible** [comment]
Won't add.
I doubt there is a single audio book player that supports OGG that doesn't support MP3. Same goes for AAC. You can set the mp3 quality to max by editing the settings and transcode it to whatever you like.

**Comment by MrTomRod** [comment]
I would also prefer OGG. It has a better quality to file size ratio. On cheaper phones, storage is still limited.
