### ISSUE TITLE
Book Table does not save sort order

### ISSUE THREAD

**Issue by gabigfoot** [openaudible/openaudible#1110]
I sort the book table in descending order by Purchase Date. This makes the most logical sense for me since I want to convert the audible books with each purchase and I need the recent purchase(s) at the top. Each time I close and reopen Open Audible it defaults to sorting by Title in alphabetical order. Is there a way to keep the Book Table sorted by descending purchase order with the newest purchases at the top?

All of the columns are saved as modified except the sort order will not save.

**Comment by openaudible** [comment]
Fixed for next version. Thanks for the report.

**Comment by gabigfoot** [comment]
Awesome! That was the fastest and best software customer service ever.

 Thank You

**Comment by openaudible** [comment]
You're welcome. 

Fixed in beta... https://openaudible.org/beta

Clicking on a column header will produce 3 states -- Down Sort, Up Sort, and back to the default sort. Settings are saved between launches. Thanks for the report.
