### ISSUE TITLE
Won't finish converting to MB4

### ISSUE THREAD

**Issue by kcstandefer** [openaudible/openaudible#1111]
I imported 437 books to OpenAudible.  All seem to have come over successfully.  339 converted to MB4.  The others ones won't convert.  That should leave 98, but the app says there are still 107 to convert and it seems to have stopped converting.  I've tried to restart it several times and it will do one more book, but not finish the rest.  

![image](https://user-images.githubusercontent.com/96642399/213472428-0bce14ed-a763-4d04-aa2d-e20b1cfae5d0.png)

**Comment by openaudible** [comment]
Did you run out of hard disk space?
Check the log under the File Menu: Console
There should be a semi-human readable error. Also, you can select one of the red books and look at the Audiobook Info: State to see the problem.

**Comment by kcstandefer** [comment]
I could have run out of space.  I have only 5.81gb left.  I had forgotten
that OneDrive will store it on my computer as well as the cloud.  I was
hoping to just put it all in the cloud.  May have to get an external drive
instead.

**Comment by openaudible** [comment]
Closing. You can reply if there are any other issues.
