### ISSUE TITLE
Feature Request/question: Keep original audible filenames

### ISSUE THREAD

**Issue by BRTPOB** [openaudible/openaudible#1112]
I just found out about your tool, and I really like the idea of it, but I'm wanting to pull all of my audiobooks without renaming them. Is there any way to do that?

**Comment by openaudible** [comment]
Not sure what you mean.. but if you import existing audiobooks, the file names shouldn't change. Just drag one or more audiobook files onto the app. (Start with one and make sure it does what you expect.)
But I may not follow exactly what you want  to do. Filenames of your audible books are generated by the app.

**Comment by BRTPOB** [comment]
Yeah, so for example when I manually download the audiobooks from Audible, the filenames show up like this: "AbaddonsGateExpanseBook3_ep5.aax", while OpenAudible is renaming them to "Abaddon's Gate Expanse Book 3.AAX". I just want it to leave the filename as "AbaddonsGateExpanseBook3_ep5.aax".

**Comment by openaudible** [comment]
Yeah that isn’t an option. That file name isn’t guaranteed to be unique. Nor is it easily obtained except by doing the download. There is a file rename command under the action menu.
