### ISSUE TITLE
Unable to Import Part 2 of Downloaded Books from Audible

### ISSUE THREAD

**Issue by faceb17** [openaudible/openaudible#1113]
Hi, Recently I'm unable to import part 2 of books I download.  I will usually download them as part one and two etc. and then convert them to mp3.  The import screen flashes briefly and then nothing happens.  I've tried renaming the aax file with no success.  

Currently using version 3.6.3. Mac OS 10.13.6 High Sierra, 27" iMac Late 2009.

Thanks
Jeff

**Comment by openaudible** [comment]
OpenAudible doesn't support partial books that you've manually downloaded (would create duplicates and other problems.). 

We only recommend connecting to your account and downloading them from the app, which does it in one step. 

You can manually download the full file and import that if you don't want to connect to your account.

**Comment by faceb17** [comment]
Hi and thanks for getting back to me.   Just to clarify Audible let’s me download the entire book or depending on the length will split it in to two or more parts.  I’ve downloaded say parts 1 and 2 to my desktop, imported them in to OpenAudible and converted them multiple times with no issues until recently.  My understanding is that this isn’t supported.  I guess my question is have I just been lucky lately?  I figured that this feature was possibly broken in a recent update.   The reason I do this or have done it as that I listen to books on my 1st gen iPod Nano (I know it’s old) so I import the books in parts to save space for podcasts and music in addition to audio books.  

Anyway, I still like the app and find it very useful.  

Thanks
Jeff

**Comment by openaudible** [comment]
I'm pretty sure the restriction has been in place for a long time. You could download a multi-part book, but I think you can only import one part at a time. So possilbly you could import part 1, then (maybe delete it?) and then import part two. Has to do with the product ID being the same and OpenAudible making sure duplicates are not allowed. For space limited devices, split by chapter is an option. Or buy a bigger iPod. :)

**Comment by faceb17** [comment]
I’m trying what you suggest now.  Sounds like I just got lucky then.  I would and should use my iPhone but for the gym I just like being about to reach down and click the old click wheel.  Some things just work better.  

So regarding split by chapter is interesting but it can create a lot of files. I think about 30 chapters for the current book. Is it feasible or worth the effort to add an option to split the book in to equal parts?  Say a preference where you can enter how many?  Looks like I have a work around but you know I had to ask.  

Thanks
Jeff
