### ISSUE TITLE
Error converting. Unable to convert aaxc file, missing audible_key/audible_iv pair.

### ISSUE THREAD

**Issue by johnk42** [openaudible/openaudible#1115]
Error converting. Unable to convert aaxc file, missing audible_key/audible_iv pair.
Have just downloaded book from Audible

**Comment by openaudible** [comment]
Make sure you download and convert from OpenAudible and that the title is still in your library. If you downloaded the file using android, for instance, it won’t be convertible.

**Comment by johnk42** [comment]
#1115 IS NOT CLOSED. I still cannot convert files.
