### ISSUE TITLE
Error converting: ffprobe error

### ISSUE THREAD

**Issue by BillStrait** [openaudible/openaudible#1116]
Seems like whatever FFProbe is can be a bit finicky. I'm submitting a bug report (and will mention this issue # when I get it).

Here's a few things I'm doing that are out of the ordinary:
1. I am downloading a 230+ file library.
2. I started downloading to my C:\ drive before I realized the space requirements
3. I manually copied everything from the initial directory to my F:\ drive (which is a USB thumb drive)
4. I am still downloading files.

I don't think anything has been converted since I moved over to the thumb drive. I suspect this is because the drive is slow and the downloads are maxing out it's write speed. I'll add more information after testing.

**Comment by BillStrait** [comment]
1. After I finished my current downloads I closed the application and tried again - Same issue. 
2. I selected a file, deleted it, and got a fresh copy from Audible to F:\ - Same issue. 
3. Moved a few files back to C:\ drive, and updated preferences to look at C:\ for the library - Same issue.
4. Downloaded a fresh copy from Audible to C:\ - worked.

I thought there might be a problem with copying data between drives. So I ran an MD5 hash off two files.
```
PS F:\OpenAudible\aax> Get-FileHash '.\Agency.AAX' -Algorithm MD5

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
MD5             E92752212CA3B627A411B35FC0015E2F                                       F:\OpenAudible\aax\Agency.AAX


PS F:\OpenAudible\aax> Get-FileHash 'c:\Users\bills\OpenAudible\aax\Agency.AAX' -Algorithm MD5

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
MD5             E738F0F64E9E3C4ACAD25FACC172B0B8                                       C:\Users\bills\OpenAudible\aa...
```

So, there's the problem, probably the thumb drive failing a write operation. 

I'd suggest getting a hash of the file at the original download time, and if possible get a hash from Audible. If that is provided, (or can be obtained while the file is in memory), you can cut down on this type of error report by checking the hashs to verify the file is not corrupted.

The web page the application generates could also provide this hash to users, so they can verify large files were downloaded correctly. It's pretty techy, but since you're having users post issues on github, I imagine that's not a huge concern.

**Comment by openaudible** [comment]
Hmm. We make certain assumptions-- that files will be the same when copied between two systems. There may be something else going on-- perhaps innocuous, or perhaps indicating a bigger problem. MD5 will only tell if the files are a tiny bit off-- would be more helpful to know how they are different. You can use a program like BeyondCompare or a hex editor to compare the files and see what is going on. If one is shorter than the other, you may be out of disk space. Also, getting the same file from audible may produce slightly different files as your username and other meta data is embedded in the file -- no md5 available from audible. Although our download algorithm will either get the entire perfect copy, or throw an error and delete failed download. 
 
Can't add MD5 to the main product-- it simply is too variable (update one metadata tag, and it changes, etc)  

Good luck.
