### ISSUE TITLE
App crashes whenever I try to do anything

### ISSUE THREAD

**Issue by cindymindylindy** [openaudible/openaudible#1117]
Hello, I'm new to the app. I just bought the license, and I was able to log in to Audible and get my library without an issue. However, whenever I try to do anything, such as download or split into chapters, the app crashes and freezes. When I force quit, I do see that the action was implemented. But I can only do one thing at a time before it crashes and I have to force quit. 

I'm using a MacBook Pro, 2018. 2.6 Ghz 6-Core Intel Core i7. MacOS 13.0.1

**Comment by openaudible** [comment]
Very strange. Can you open the console window and see if you notice any errors (cmd-E, or under the file menu.) 

check your system is up to date and has enough disk space.  We haven’t had any similar reports so not sure. 

We do have a beta program but nothing has changed that we know of that would have caused freezing.

**Comment by cindymindylindy** [comment]
This 

> Very strange. Can you open the console window and see if you notice any errors (cmd-E, or under the file menu.)
> 
> check your system is up to date and has enough disk space. We haven’t had any similar reports so not sure.
> 
> We do have a beta program but nothing has changed that we know of that would have caused freezing.
> 
> Edit: Also check to see if you have an extra anti-virus or firewall that might be blocking requests.. You can also try to do Check for Update under the About menu.. that should succeed if the network is working.

This was today's logfile:

Feb 03, 2023 9:08:38 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Feb 03, 2023 9:08:54 PM org.openaudible.convert.ConvertJob convertFile
INFO: create MP3 /Users/cindylee/Library/OpenAudible/aax/Loving Kindness.AAX result:0
Feb 03, 2023 9:08:54 PM org.openaudible.convert.ConvertJob convert
INFO: Converted Loving Kindness to /Users/cindylee/Library/OpenAudible/books/Loving Kindness.mp3 size=7556054 in 17 seconds.
Feb 03, 2023 9:08:54 PM org.openaudible.Audible jobCompleted
INFO: ConvertQueue completed:Loving Kindness ConvertQueue size:30 remain:28 success:1 fail:0 threads:3
Feb 03, 2023 9:08:54 PM org.openaudible.Audible needSave
INFO: Change to library, need save flag set
Feb 03, 2023 9:08:54 PM org.openaudible.util.queues.ThreadedQueue run
INFO: Starting job convert Story Party: Sweet Tooth ConvertQueue size:30 remain:27 success:1 fail:0 threads:3
Feb 03, 2023 9:08:54 PM org.openaudible.Audible jobStarted
INFO: ConvertQueue started:Story Party: Sweet Tooth ConvertQueue size:30 remain:27 success:1 fail:0 threads:3
Feb 03, 2023 9:08:54 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: /Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffprobe -hide_banner "/Users/cindylee/Library/OpenAudible/aax/Story Party Sweet Tooth.AAX" -show_streams -show_chapters -show_error -show_format -print_format json 
Feb 03, 2023 9:08:54 PM org.openaudible.convert.ConvertJob convertFile
INFO: converting: Story Party: Sweet Tooth to temp file: /Users/cindylee/Library/OpenAudible/tmp/RO_A144_000006_temp.mp3 from source /Users/cindylee/Library/OpenAudible/aax/Story Party Sweet Tooth.AAX length=42934127
Feb 03, 2023 9:08:54 PM org.openaudible.convert.ConvertJob convertFile
INFO: /Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffmpeg -audible_iv e97aa3bc8ca07894d1155e567db4db1f -audible_key 5178495c2cb065aab9af86170e355347 -i "/Users/cindylee/Library/OpenAudible/aax/Story Party Sweet Tooth.AAX" -i "/Users/cindylee/Library/OpenAudible/tmp/Story Party Sweet Tooth.AAX.txt" -map_metadata 1 -map_chapters 0 -map_metadata 0 -metadata:s:v "title=Album cover" -metadata:s:v "comment=Cover (front)" -codec:a libmp3lame -b:a 112k -id3v2_version 3 /Users/cindylee/Library/OpenAudible/tmp/RO_A144_000006_temp.mp3 
Feb 03, 2023 9:09:13 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by openaudible** [comment]
So nothing seems amiss in the log--although I don't know if the mp3 conversion completed. That can take a few minutes-- but should update the book information state showing the conversion progress... (0-100%)

If you have any additional anti-virus application, you may need to tell it that "OpenAudible" and the binaries within (ffmpeg/ffprobe) are "OK". 

Only other things to try: disable automatic downloads and conversions and just do them one at a time until the cause is found.

Try converting one book, and keep the book selected and watch the conversion state progress. Does it start converting? Get partially done and "hang"? Obviously, the conversion process should start, and proceed to 100% complete. If you want, email a screenshot of the hang... and once again, check disk space.

**Comment by cindymindylindy** [comment]
This is perfect! I changed my settings and I am able to do things one at a
time without crashing. Thank you!

**Comment by openaudible** [comment]
Sorry that was happening. Glad it is working better now.
