### ISSUE TITLE
License requests returns "Request could not be authenticated"

### ISSUE THREAD

**Issue by alex-babanov** [openaudible/openaudible#1118]
As of yesterday books aren't downloaded anymore in 3.5.3. When I peek at console I see it trying URL like https://api.audible.com/1.0/content/B0777TY894/licenserequest and getting back "Request could not be authenticated"

Call stack:

java.io.IOException: http error getting: https://api.audible.com/1.0/content/B0777TY894/licenserequest reason:Bad Request
	at org.openaudible.audible.api.Client.requestBytes(Client.java:151)
	at org.openaudible.audible.api.Client.request(Client.java:82)
	at org.openaudible.audible.api.Client.post(Client.java:76)
	at org.openaudible.audible.api.API.getLicenseForBook(API.java:566)
	at org.openaudible.audible.api.API.getLicenseForBook(API.java:557)
	at org.openaudible.audible.APIManager.getAAXCDownloadLink(APIManager.java:96)
	at org.openaudible.download.DownloadAAXJob.preProcessAAXC(DownloadAAXJob.java:237)
	at org.openaudible.download.DownloadAAXJob.downloadAlt(DownloadAAXJob.java:197)
	at org.openaudible.download.DownloadAAXJob.processJob(DownloadAAXJob.java:207)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:516)

**Comment by openaudible** [comment]
Check that you are connected to your library. Do a Quick or Full Library rescan. 

Make sure the title is still in your current library and it hasn't expired -- some titles are automatically removed after a period of time. 

You could also try Control: Log out of Audible... and then reconnect.. 

If you're still having issues, you can send a bug report by: connect, full library rescan, download, if error, send bug report from About menu.

**Comment by JamesSwift** [comment]
This is the same behaviour as reported in this issue: https://github.com/openaudible/openaudible/issues/1068

**Comment by openaudible** [comment]
What region are you in? If anyone is seeing this, a bug report would be helpful:

quit and launch openaudible (clears tmp directory) 
Controls: quick library scan
download a book
convert the book.
If any errors, submit a bug report from the About menu.
And verify that the title is playable in your audible application using the same account.

**Comment by alex-babanov** [comment]
> Check that you are connected to your library. Do a Quick or Full Library rescan.

Done both before filing bug report.

> Make sure the title is still in your current library and it hasn't expired -- some titles are automatically removed after a period of time.

This affects the last 6 books I purchased. Their authors and release dates vary, I see 2017, 2020 and 2022. It is unlikely that all six expired at once, especially since I can listen to them.

> You could also try Control: Log out of Audible... and then reconnect..

Done this before filing the bug report.

> If you're still having issues, you can send a bug report by: connect, full library rescan, download, if error, send bug report from About menu.

Will repeat all troubleshooting and do this.

Thank you!

**Comment by alex-babanov** [comment]
> What region are you in?

US exclusively. I do not switch my region to buy from other countries' libraries.

Thank you!

**Comment by JamesSwift** [comment]
I'm in UK region. I'll file a bug report once I get home.

**Comment by alex-babanov** [comment]
Today's troubleshooting:

1. Launched OpenAudible
2. Logged out from Audible
3. Closed OpenAudible
4. Launched OpenAudible
5. Connected to Audible
6. Started full scan (1023 books)
7. Sorted by purchased, same 6 books are not downloaded with error status
8. Triggered download for each one of these, got same error for each
9. Sent report from About menu

Thank you!

**Comment by JamesSwift** [comment]
Bug report submitted

**Comment by openaudible** [comment]
Ok. Those 6 books may not be still available. Check that they are in your library in the audible web app or in your mobile app. You could delete those books and try the scan again and see if they reappear. 
will check bug report later and see if I see anything.

**Comment by openaudible** [comment]
Ok. Looks like you were using an old copy of OpenAudible. I sent a new license to your email and you can try the beta or wait for the next version.

**Comment by JamesSwift** [comment]
Thank you. I can confirm that the latest beta v3.6.3.12 solves my issues. Thanks for your work on this project!

**Comment by alex-babanov** [comment]
@openaudible could you send me beta as well? If it's a change in Audible, I can get a new license, but I'd like to confirm the fix.

Thank you!
