### ISSUE TITLE
Getting an OpenAudible error "Download error: http error"

### ISSUE THREAD

**Issue by klinkehoffen** [openaudible/openaudible#1119]
Hello GitHub gurus,
I am a paid user of OpenAudible (which is utterly brilliant, by the way), but today have struck a download error, and as I am a coding newbie I have very little idea of what I can do to fix this. The error is reported, against the "State" of the book as:

Error downloading: http error  [https://api.audible.com/1.0/content/B0B8DT3VH8/licenserequest reason:Bad Request](https://api.audible.com/1.0/content/B0B8DT3VH8/licenserequest%20reason:Bad%20Request)
[Open Audible error 03 03 2023.pdf](https://github.com/openaudible/openaudible/files/10574170/Open.Audible.error.03.03.2023.pdf)

I have tried shutting down the software and restarting, but this has made no change. Perhaps this is a known problem and there is a patch coming? Any help would be appreciated. (And if there is additional information which I need to supply, please explain as simply as possible, as I will probably be trying to plug the power into the plumbing if too complex 🤦🏼‍♀️)

Warmest regards

Sam Young

**Comment by openaudible** [comment]
Are you in the US? We're starting to see a few of these issues. Some report errors if downloading too many things in regions outside of the US..  If you want to submit a bug report, you can by quitting, launch openaudible, Controls: quick rescan, download one file.. if it fails, send a bug report issue 1119 from About Menu: Send Bug Report...

**Comment by klinkehoffen** [comment]
Thanks so much for the reply, No, not in the US. I am in New Zealand.

**Comment by klinkehoffen** [comment]
OK, I am trying to follow your instructions. Do you mean Controls | Quick Audible Library Sync ...?

If so, the one file that has not downloaded still doesn't download. All the other fles have already downloaded... but I am not sure that is what you meant (sorry!).

**Comment by openaudible** [comment]
Yes, but might as well make it a "Full Audible Library Sync".. That won't download anything except your current list of books.
And if you can verify that the title is still playable in your Audible mobile app. 
Thanks

**Comment by klinkehoffen** [comment]
Thank you! OK. I tried both downloads, and neither worked. I don't use the mobile app. So I went to report the error and got a notification that I don't have the latest version of OpenAudible 🤦🏼‍♀️. Just downloading now. Will report back if this is still a problem.

**Comment by klinkehoffen** [comment]
OK. It worked perfectly after the update. Apologies for wasting your time, and thank you for helping me!
