### ISSUE TITLE
Unable to create temp aax file/Won't download

### ISSUE THREAD

**Issue by artnbones** [openaudible/openaudible#112]
I'm unable to download a book - the status says "unable to create temp aax file:C:\blah\foo"
I do not have the "check for Audible download manager" box checked in my account settings. 

Here is what was logged, if it helps: 

INFO: Converted:
Salem's Lot
Salem%27s+Lot
Mar 30, 2019 4:41:23 PM org.openaudible.download.DownloadJob download
INFO: Downloading book: Salem's Lot url=[]
Mar 30, 2019 4:41:23 PM org.openaudible.download.DownloadJob download
INFO: Download failed:C:\Users\Me\OpenAudible\aax\Salems Lot.AAX Salem's Lot
Mar 30, 2019 4:41:23 PM org.openaudible.util.queues.ThreadedQueue jobError
INFO: DownloadQueue error processing Download Salem's Lot
java.io.IOException: Unable to create temp aax file:C:\Users\Me\OpenAudible\tmp\Salems Lot.AAX.part
	at org.openaudible.download.DownloadJob.download(DownloadJob.java:194)
	at org.openaudible.download.DownloadJob.downloadNew(DownloadJob.java:276)
	at org.openaudible.download.DownloadJob.processJob(DownloadJob.java:292)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:324)

Mar 30, 2019 4:41:23 PM org.openaudible.Audible jobCompleted
INFO: DownloadQueue completed:Salem's Lot remaining queue size:0
Mar 30, 2019 4:41:23 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 16928 to disk:C:\Users\Me\OpenAudible\tmp\saved_books.json
Mar 30, 2019 4:41:23 PM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error downloading Salem's Lot: Unable to create temp aax file:C:\Users\Me\OpenAudible\tmp\Salems Lot.AAX.part
Mar 30, 2019 4:43:03 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute

Any ideas what's going on? 
Thanks a bunch!

**Comment by openaudible** [comment]
That is weird, will happen if there is already a temp file called: file:C:\Users\Me\OpenAudible\tmp\Salems Lot.AAX.part  Try deleting that file if it exists.. 
Also, edit or delete the URL to your book to remove your "cust_id" in your issue above if you didn't already obfuscate the URL.
