### ISSUE TITLE
Latest version 3.6.3 does not allow Preferences->Directory override to stick

### ISSUE THREAD

**Issue by viperccp** [openaudible/openaudible#1120]
Hello,

I just purchased a license and am trying to install the utility so it uses my D: drive to store/process my audiobook files.

I set both a System and User variable for the Preferences path, as well as pointing the Library and Web Directory to the new folder(s):

Library: D:\Media\Audible\OpenAudible
Web Directory: D:\Media\Audible\OpenAudible\web
Preferences: (set environment variable "OPENAUDIBLE_HOME" to point to D:\Media\Audible\OpenAudible as instructed)

After making all these changes and even rebooting the computer... nothing is sticking.

It is always defaulting back to the hardcoded folders:

Library: C:\Users\username\OpenAudible
Web Directory: C:\Users\username\OpenAudible\web
Preferences: C:\Users\username\OpenAudible

Is this a known issue in the latest release (v3.6.3), or am I missing something? I made sure the new folder on drive D is not read only and it seems permissions should be fine to write to it. I am using an antivirus software, but that should not cause an issue.

Is there perhaps a regedit I can made to force these overrides from the registry itself if necessary? Ideally the interface would work as expected, but right now I need to use my larger data SATA drive instead of mucking up my smaller system SSD drive.

Thanks!

Update: I was able to edit the directories.json file (libraries.json already had my new paths, so no updated needed there) and force the new desired directory structure that way. Not an ideal solution, but it should work for now.

**Comment by openaudible** [comment]
So the library path is the primary location you want to set.

Using the OPENAUDIBLE_HOME will only change where preferences are saved.. although the temp dir is also there which can use a few gigs of disk space.

I didn't think anything is wrong with the directory path-- but you might look at the log window as soon as the program restarts. It should display all directory info.

You can also give the beta a try. It has a feature to allow you to choose between libraries... Although it is a work in progress. 
https://openaudible.org/beta

**Comment by viperccp** [comment]
> So the library path is the primary location you want to set.
> 
> Using the OPENAUDIBLE_HOME will only change where preferences are saved.. although the temp dir is also there which can use a few gigs of disk space.
> 
> I didn't think anything is wrong with the directory path-- but you might look at the log window as soon as the program restarts. It should display all directory info.
> 
> You can also give the beta a try. It has a feature to allow you to choose between libraries... Although it is a work in progress. https://openaudible.org/beta

Thank you for your response and this great tool. Looking forward to seeing the results and having access to my books offline. For now, the direct overwriting of paths in the json file did the trick (made a backup of the original file). I am downloading books now and they are going to the D: drive without issue (so far). With gigs of books and temp space, I'm very glad I waited until I could use the D drive. :)
