### ISSUE TITLE
Bought the license 2 days ago, now crashes every time I click on a book.

### ISSUE THREAD

**Issue by phreakwenci** [openaudible/openaudible#1123]
When I click on a book that is converting from Aax to m4b the app hangs and I need to force quit in order to get it working again. I also have books that it can’t seem to convert the aax giving me an error.

**Comment by openaudible** [comment]
How does it crash? Totally quits or hangs? Does it leave any messages in the File:Console log? All other apps running fine? 

Very unusual. What OS?

**Comment by phreakwenci** [comment]
It happens on certain books where if you click on it in the app, it’ll give
you the colorful spinning ball of death and then just hang forever and not
respond.

In order to get it running you need to force quit the app and restart but
even after you do that, if you click on any of the books that we’re giving
you that issue it will freeze and not respond again.

**Comment by openaudible** [comment]
We have no similar reports so suspect something unusual on your Mac. Most likely it is trying to fetch the cover image from disk and getting a read error retrieving from the disk or network drive. Try a disk check and make sure you have disk space. 

If that doesn’t work, send us an email and we can refund. May be a strangely incompatible with your Mac.
