### ISSUE TITLE
Feature Request: automatic splits for mp3 conversion as a preference

### ISSUE THREAD

**Issue by Cybergate9** [openaudible/openaudible#1124]
Firstly, thanks again for this software it's a life saver! :-)

Is it possible (simple enough) to add a preference that when MP3 conversions are done, mp3 chapter splits are also done?

As a conjunction with this, having an option to 'properly title' mp3 chapter files would be ideal (but I suspect significantly more difficult due to edge cases) - I'd be happy to split this idea out into a seperate issue# if you think it possible/feasible/desirable.

Background:
I have hundreds of books and would like to 'back them up' to MP3 and, yes, doing that to a monothilic MP3 of each title will achieve a 'backup'..
But - the MP3 won't really be a 'useable' backup in the future because navigation will be difficult, if not impossible, without chapters..
If I could convert to entire library to chapter split MP3's automatically (rather than having to do each one after initially having converted them all to monothilic MP3s) that would be ideal..

**Comment by openaudible** [comment]
At this point it is not possible. But you can split multiple books at once by selecting one or more or do a “select all” and action: split books. 

Chapter meta data is included in the monolithic mp3 and should be read by almost all good book players. 

Marking as feature request.
