### ISSUE TITLE
AAX files no longer playing in iTunes

### ISSUE THREAD

**Issue by BlueDjinni** [openaudible/openaudible#1125]
Using version 3.6.3 connected to my UK audible account to download the latest purchases. all downloaded OK but none of the new downloads (aax files) would open in Tuneskit Audible Converter. I tested by adding to iTunes library. aax Files loaded but won't playback. Downloaded file directly from Audible and aax file will play ok in iTunes. Previous aax audiobooks retrieved using version 3.5.3 WILL play in iTunes. To test further I re-downloaded an older book - aax file from 3.5.3 plays in iTunes but aax file from 3.6.3 won't.
Tried reinstalling OpenAudible 3.5.3 to see if this is a new featurebut get the following error
![image](https://user-images.githubusercontent.com/124905121/217860137-7a130319-cc02-4508-b905-5eaf5a03df1d.png)
My license is showing as valid
Please advise how to go forward

**Comment by openaudible** [comment]
You need to download and convert to mp3 or m4b. AAX files are encrpyted, so any device that plays them (iTunes) is not really our issue.
I do see the error downloading, so the best thing to do is delete the whole book in OpenAudible (make a backup if you want) and do a full library scan, find the book, re-download, and convert.

**Comment by BlueDjinni** [comment]
Hi, the point is this worked before. All aax files were authorised to open in iTunes and tuneskit audio converter.  Presumably you are extracting them in a different way in this version. If this is the case, can I restore the previous version of open audible as this worked for me. When I try to open the previous version I get a bad license request  even though I have paid for a licence?ThanksSent from my Galaxy
-------- Original message --------From: openaudible ***@***.***> Date: 09/02/2023  22:48  (GMT+00:00) To: openaudible/openaudible ***@***.***> Cc: BlueDjinni ***@***.***>, Author ***@***.***> Subject: Re: [openaudible/openaudible] AAX files no longer playing in iTunes (Issue #1125) 
You need to download and convert to mp3 or m4b. AAX files are encrpyted, so any device that plays them (iTunes) is not really our issue.
I do see the error downloading, so the best thing to do is delete the whole book in OpenAudible (make a backup if you want) and do a full library scan, find the book, re-download, and convert.

**Comment by openaudible** [comment]
We don’t support itunes playing aax files or tuneskit. Those aren’t our products! You can use any version of OpenAudible— available in the releases link above. But I doubt downgrading will help. You may have to follow the recommendations above. Sorry we can’t help more.

**Comment by BlueDjinni** [comment]
I have downloaded over 500 titles from audible using openaudible 3.5.3, all of which are recognized as valid encrypted audible aax files by iTunes and will play without issue on an authorised computer. openaudible 3.6.3 downloads are not recognized as valid encrypted audible aax files and will not play on an authorised computer, whereas files downloaded directly from audible are recognized and will play.

Clearly something has changed in this release and I would argue that the files output from your program are indeed your responsibility. Your program is supposed to provide a facility to bulk download audible files, but if a valid audiobook player cannot read them, then they are not audible files.

If these files are not meant to be valid encrypted audible files, may I suggest you change the file extension to something that a legitimately authorised 3rd party program such as iTunes does not expect to be able to read as an encrypted audible file?
