### ISSUE TITLE
Can't revert to previous version

### ISSUE THREAD

**Issue by BlueDjinni** [openaudible/openaudible#1126]
Upgraded on prompt to version 3.6.3 which doesn't work the way I want so I need to revert to 3.5.3. I have reinstalled the software, removed all my library information and connected to UK audible. A full library sync has retrieved my library, but I cannot download any of the titles because of the following error:-
![Capture](https://user-images.githubusercontent.com/124905121/218049635-9973f98e-9714-4717-b93f-b623b1e466c3.PNG)

Please reset my license registration to work with 3.5.3

**Comment by openaudible** [comment]
That is strange. Do you have multiple accounts and is it possible you're trying to download that book with a different account or login?  Did you check that the book is in your library (or comes back into your library after being deleted and doing a full library sync?)
All versions can be downloaded from: https://github.com/openaudible/openaudible/releases
Go here to find more details and links to all versions. https://openaudible.org/license

**Comment by BlueDjinni** [comment]
I completely wiped the directory before doing a full resync. All books in my library are reloaded into the library, but I cannot download ANY file. I already checked my license status and it is showing as valid. I also tried to reregister from the app. I assume that the issue is because this license was used against a later version and the database your end is causing the problem. Maybe it would help to reset the license to unregistered and I could try to reactivate from this end. Or failing that you could issue a new license code

Also looks like you have closed this thread - please reopen as it is far from resolved. Answered is not the same as complete.

**Comment by openaudible** [comment]
Can you do a "Full Rescan", Download a book (which fails?) and also attempt to convert a book .. then send a bug report with the 1126 issue number.. I'll take a look. Hard to tell with just the screenshot.
