### ISSUE TITLE
Right click menu for downloaded PDFs includes Convert to M4B

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#1129]
how can you convert a PDF to M4B?

**Comment by openaudible** [comment]
You cannot. PDFs are supposed to only be added as a supplement to an audiobook. So you are right clicking on the book, not pdf. 
I don’t understand the concern.

**Comment by feldegast** [comment]
I see, so it is a lack of clarity in the app, when I filter to show what I think are the list PDFs and I then see books with PDFs maybe the filter should be "With PDFs" rather than just "PDFs"?

**Comment by openaudible** [comment]
Yeah I don’t know how that will translate. Thanks tho.

**Comment by openaudible** [comment]
I added the wording to the tool tip and updated the documentation.
