### ISSUE TITLE
error converting to m4b files see issue #1115

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#1131]
i am having the same issue with files downloaded within openaudible, books I was previously able to download and convert

**Comment by openaudible** [comment]
Need an error log and region or bug report. Feel free to obfuscate any urls/data. Most interested in any exceptions and stack traces.

**Comment by feldegast** [comment]
I re-logged in and am unable to repeat the issue as the books downloaded fine after re-logging in

Maybe a tip to re-login for the user to resolve the issue themself?

**Comment by openaudible** [comment]
Ok.. Will check for that and try to put up an error message. Closing and will keep following #1115
