### ISSUE TITLE
KDE Plasma 5.25, 5.26, and 5.27 Beta issues

### ISSUE THREAD

**Issue by xenspidey** [openaudible/openaudible#1132]
On KDE Plasma 5.25, 5.26, and 5.27 Beta, with Wayland, only the .sh installer looks correct. All others have graphical issues. Epiphany and webkit2 gtk3 must be installed to login to audible as well

**Comment by openaudible** [comment]
The beta removes the web browser requirement which might fix some of the issues. https://openaudible.org/beta 
If you post a link to an iso if we have more time we can test when we have time— but a little backlogged at the moment.

**Comment by openaudible** [comment]
Closing for now. Can’t support all Linux variants in beta. Our OpenAudible beta should help.
