### ISSUE TITLE
Feature request or missing feature - Ability to sort by Author > Series Name > Release Date etc. to be able to see audiobooks from the same series in correct order.

### ISSUE THREAD

**Issue by 747main** [openaudible/openaudible#1134]
Feature request or missing feature:

Ability to sort by Author > Series Name> > Series Order  etc. to be able to see audiobooks from the same series in correct order. As long as you can see books by the same author, then under that author, in the same series, and then in order of release and/or numbered order it would be very convenient. Currently you can't do this. Only one category works at the same time and even with it sorted by series name, it doesn't put the books in the correct order. Pretty please with sugar on top?! Thanks in advance. Keep up the stellar work!

**Comment by 747main** [comment]
Thanks for having a think on this. Best of luck on your next big release. Sending best 🤓 success vibes.


Have peace.

**Comment by openaudible** [comment]
We improved sorting per your suggestion. 
check out the beta if you want to check if out

https://openaudible.org/beta

**Comment by 747main** [comment]
Thanks! It works great so far! Much appreciated! 


Have peace,

James
