### ISSUE TITLE
Splitting AudioBooks

### ISSUE THREAD

**Issue by Knuffiex** [openaudible/openaudible#1139]
Is there a possibility to split the audiobooks in (e.g.) 10min junks? At least I havent found a way. This would be handy because I hear them in the car, where skiping to a certain point is more thane kind of a long acticity without smaller "chapters".
And I would appreciate a possibility to store converted books in a folder hierarchy like: "Writer"  and then subfolders "Books". I haven't found a possibility for this ether.

**Comment by openaudible** [comment]
No, sorry. Plenty of good audiobook players out there that keep track of where you are.
