### ISSUE TITLE
Cannot export list of books

### ISSUE THREAD

**Issue by Schnoidz** [openaudible/openaudible#114]
I just installed 1.4.4 and when I try to export the list of books I get a popup saying it's a feature not available in the demo version and that I should upgrade to the full version.  When I try Help > Check for update, it shows I'm using the latest version.

Windows 10
![2019-03-31 12 14 10](https://user-images.githubusercontent.com/41595961/55291908-33cf0480-53b2-11e9-8c3f-1803fb20f784.png)

**Comment by oscott** [comment]
Same for me but when i export webpage. osx mojave oa.1.4.4

**Comment by openaudible** [comment]
That is a bug on our end. As you might have guessed, we're considering a paid version to cover some of the time and expenses. Will remove for the next version.
