### ISSUE TITLE
Cant convert to MP3

### ISSUE THREAD

**Issue by Hensmon303** [openaudible/openaudible#1142]
I got the software because it said it could convert to MP3. I have no option to do that. After importing my .aax file succesfully I then right click and all export options are disbaled. Even M4B is disabled. Why?

**Comment by openaudible** [comment]
Go to the Preferences (click cog button in upper right) and set output format to MP3.
M4B is often disabled if you already are converted to m4b or if the file hasn't been downloaded first.

**Comment by Hensmon303** [comment]
OK that worked thanks.

The issue I have now is that the other aax files from my book (part 2 and 3) will not import into the software. Part 1 worked fine. Whenever I drag in, or import from file, nothing happens...
