### ISSUE TITLE
Help I changed file location and now it wont work

### ISSUE THREAD

**Issue by Mindfullymakingit** [openaudible/openaudible#1143]
![20230221_080807](https://user-images.githubusercontent.com/125959104/220286794-b19ef5f7-29f7-422d-b4b9-690a25233bd5.jpg)

This is the error message, i deleted and uninstalled and reinstalled and its made no difference.

**Comment by openaudible** [comment]
Oh, you can't have your books stored in the Program Files. 
A better dialog should show up in the latest versions of OpenAudible. So running a current copy should ask to locate your library.

But to fix on your current system, go to your home directory the directory C:\Users\YOUR_USER_NAME\OpenAudible  and rename the "directories.json" file to something else (directories.backup.json) and restart the app.
