### ISSUE TITLE
Can't Convert to either MP3 or M4B

### ISSUE THREAD

**Issue by Convair58** [openaudible/openaudible#1144]
Purchased software yesterday and was able to convert 8 of 14 aax files then it stop. says can't convert because Audible _Key is missing or Audible_iv pair. Tried converting M4B and MP3 from Audible by online download and also pre-downloaded AAX files to my pc with no change. Convair58

**Comment by sixsceptres** [comment]
Reporting same issue.
**Software Version**: 3.6.3
**Operating System**: macOS Ventura 13.2.  
**Error message text**: 
> Error converting: Unable to convert aaxc file, missing audible_key/audible_iv pair

**Troubleshooting steps taken**:
- Log out of Audible (and log back in)
- Quick Audible Library Sync
- Full Audible Library Sync
- Refresh Files

**Comment by openaudible** [comment]
You need to download the Aaxc files using OpenAudible. So however that aaxc file was downloaded, it needs to be deleted and re-downloaded.  You can do this by action show aax and then delete the file(a) that aren’t converting. 

We will update the software to automatically redownload the file, since this sometimes comes up.

**Comment by Convair58** [comment]
Perform procedure but still got same failure. Even change download directory to virgin drive to make sure there was plenty of room for files. The problem persists with the same book files...?

**Comment by Convair58** [comment]
Addendum: I notice that all the files that won't convert do not display the length of time of the file on AUDIBLE. All the files that work correctly, do..

**Comment by openaudible** [comment]
It’s possible the files are corrupt or missing on audible. Can you play them from the audible mobile app and or using the web player? That would be a requirement. 

Next you could: quit/restart OpenAudible. Full rescan. select one book, action delete audiobook, download, attempt convert. If fails, Send bug report from about menu.

**Comment by Convair58** [comment]
Hello. Your suggestion about playing using audible app sent me back to audible and I found AudibleSync app. Downloaded it and used it to sync my library. After doing that, everything that you suggested, worked as you described.  Apparently, the app synced the library correctly with the time length displayed for all books and I was able to delete and redownload the aaxc files which promptly converted. Thank you for your prompt responses and help! CTillman

**Comment by openaudible** [comment]
Glad its working better. Yeah, you need to download the file using OpenAudible. We changed the beta (for the next release) to be more proactive about not letting you import or convert files that are missing the decryption keys. Thanks for the report.
