### ISSUE TITLE
When downloading a title: "Error downloading: error HTTP/1.1 416 Requested Range Not Satisfiable"

### ISSUE THREAD

**Issue by alzxjm** [openaudible/openaudible#1145]
Trying to download a book and getting error code "Error downloading: error HTTP/1.1 416 Requested Range Not Satisfiable" but only for one book. I have been able to download other books before and after this one in question. 

There is a closed issue in which the lack of available storage was a potential cause, but I don't think it applies in my case. My library is stored on a NAS with plenty of storage and my computer, an M1 mac, has plenty of storage as well.

I will submit a bug report.

<img width="1087" alt="Screenshot 2023-02-25 at 4 17 51 PM" src="https://user-images.githubusercontent.com/15354332/221380065-22679c18-f642-4532-a84e-bd60bfeaa31c.png">

**Comment by alzxjm** [comment]
Just to confirm - after submitting this report I bought another audible book and downloaded and converted it successfully. The book in the screenshot still fails.

**Comment by openaudible** [comment]
Thanks for the report. Looks like a problem or two was encountered. It looks like there was already a file called /Volumes/Media/Audiobooks/aax/The Last Town.AAX on the NAS. Maybe try a "Refresh Files" from the Control Menu. 
If that file is corrupt for some reason, it can be deleted.
Worst case, you could right-click the book, delete, full rescan and re-download/convert.

**Comment by alzxjm** [comment]
Yeah that took care of it! I had tried to manually download the AAX and convert it. Once I deleted the file, rebooted OpenAudible and did a Full Sync, it worked.

Thanks!

**Comment by openaudible** [comment]
Thanks for the report. Glad its working. We have made some changes in the beta that may help when that error occurs in the future..

**Comment by Muxelmann** [comment]
In docker, I found that this error pops up when the title contains an umlaut (äöü) for German audiobooks. Maybe it's to do with linux implementation? Under macOS and Windows I don't seem to get this error (yet).

**Comment by openaudible** [comment]
Make sure you rebuild the docker image if the version is not the latest (currently 4.4.7)
We typically don't request a download with any title characters. So not positive. You can copy and paste the error log (assuming you're using the latest version) and send it via our contact form at openaudible.org/contact

**Comment by Muxelmann** [comment]
Thanks for the quick reply! I use `openaudible/openaudible:latest` and it's version 4.4.7. I deleted all files, restarted the container and reattempted the download; it failed again. I just sent the content of `log.txt` via your contact form.

![Bildschirmfoto 2024-10-03 um 10 25 20](https://github.com/user-attachments/assets/115bda68-6e5e-4862-bcf0-b804e2d870d0)
