### ISSUE TITLE
Downloading stopped working - immediate red dots

### ISSUE THREAD

**Issue by TansyEH** [openaudible/openaudible#1146]
Hi, I've been using openaudible for a while with no problems but now cannot download any books at all. I get immediate red dots for either individual books or the entire library. 
Please can you advise me on what to do? I have tried uninstalling/reinstalling openaudible - the reinstallation via ubuntu software is still version 3.5.3., deleting and re-syncing books, and searching everywhere in audible for the software verification box that I've seen mentioned. I don't know what is suddenly wrong? 
Thanks in advance.

**Comment by feldegast** [comment]
(not the developer but this may be of some help as I have had similar issues)
I had this issue with some of my books (maybe 3%) I found that some books were only accessible from some Audible servers but not all
I had to get some audiobooks re-approved by contacting Audible directly to restore access to Audiobooks i had purchased that became unavailable.... 
Are you still able to listen to audiobooks through the Audible website?
if not it is an issue with them....
Connecting to Audible.com gave access to books from other locales but not all
I downloaded an audiobook in the last 5 hours without issue....

which Audible server did you connect to?
which titles are you having an issue with? (not links to books as they are not any use to me) a small example could help
I don't know if the plus catalogue id available through the app I buy my books outright.....

**Comment by openaudible** [comment]
Which region are you in? How many books have downloaded and have not downloaded? 
Click on a red dot book-- what does the "Book Info: State" line say?

Check disk space.

You could try Controls: Log out of Audible and Controls: Connect to Audible... 

We got a report that some regions have a time limit on downloads-- if that is true, waiting a little may help. 

Lastly, you can file a report by: Quit, Select a book, right-click, download. convert. If still failing, send bug report from Help menu.

**Comment by andrewcalvin** [comment]
Same problem as OP. New book. Can and have downloaded manually from the Audible web page. Error is "Error downloading http error getting https://api/audible.com.au/1.0/content/[redacted]/licenserequest reason: Bad Request.

I have logged out and in again in the app. Version 3.5.2.

**Comment by bigbosst** [comment]
Same licesnerequest API error for me as well

**Comment by openaudible** [comment]
What regions are you in? Are you working with multiple audible accounts?
If you want, you can submit a bug report: Quit and restart OA. Do Controls: Full audible library sync, then attempt download, and if error, About Menu: Send Bug Report. We can take a look at the logs.

**Comment by andrewcalvin** [comment]
I have one Audible account. It is audible.com.au.

Bug report sent.

**Comment by TansyEH** [comment]
All listing Bad Request for me as well - have filed a bug report.

**Comment by openaudible** [comment]
There are a few reasons why a download might fail. 

- Out of disk space. Make sure the destination drive has disk space.
- You are logged into the wrong account. If you have multiple accounts, you need to be connected to it before a download will work.
- Some books become unavailable-- check that the audiobook is available in the Audible mobile app and/or Audible web page and can be played.
- Rate limit exceeded. Try disabling automatic downloads and waiting a little before trying again.
- Often, Controls: Log Out of Audible, then Controls: Connect to Audible is needed.
- If the audiobook still shows "red dot" error, you can select and Action:Delete the book, and do a Controls: Full Audible Library Sync, then retry downloading.
- Upgrade to the latest version. Some issues have been addressed in later versions of OpenAudible.
- It is always best to back up your files as soon as possible.

**Comment by openaudible** [comment]
Closing, but feel free to add any comments. You can also use the beta if you want.. some networking issues have changed.

**Comment by treeballswim** [comment]
Has anyone managed to resolve this issue by upgrading to the latest version? I am getting this error on every single book in my library and can still listen fine via other routes. Bug report submitted a few days ago.

**Comment by feldegast** [comment]
i find if i connect to the US server I can get most books even when I bought them from other servers but Audible may restrict access to downloads bought from the same region

**Comment by treeballswim** [comment]
> i find if i connect to the US server I can get most books even when I bought them from other servers but Audible may restrict access to downloads bought from the same region

thank you! I tried this but still no luck. Then I upgraded and that did resolve the issue, if anyone else gets this.
