### ISSUE TITLE
Need chapter breaks for yoto player

### ISSUE THREAD

**Issue by JaneAirgun** [openaudible/openaudible#1148]
I'm converting books from audible to mp3 so my child can listen on the Yoto player, which can only go from one chapter to another (there is no fast forward or rewind function). Some of my audiobooks seem not to have good chapter data, e.g. Sideways Stories from Wayside School (many very short chapters, but only two 'chapters' in the metadata). I don't need the chapter names but is there a way I can insert manual chapter breaks?

**Comment by openaudible** [comment]
Unfortunately, there is no way for us to fix that. 

If the chapter data is wrong, you might be able to tell Audible and they may correct it.. 

Sorry.
