### ISSUE TITLE
Error downloading: error HTTP/1.1416 Requested Range Not Satisfiable  only on a file

### ISSUE THREAD

**Issue by estrazio** [openaudible/openaudible#1149]
I have a lot of disc space...

**Comment by estrazio** [comment]
The name off the book starts with "..." , is this the problem?

**Comment by openaudible** [comment]
That is a strange file name but shouldn't matter. 
The range request is usually an attempt to retry a failed download. 
Here are some things you can try 

- You can try quitting and restarting openaudible.
- You are logged into the wrong account.
- Some books become unavailable-- check that the audiobook is available in the Audible mobile app and/or Audible web page and can be played.
- Often, Controls: Log Out of Audible, then Controls: Connect to Audible is needed.

**Comment by openaudible** [comment]
Make sure you are using the latest version or the beta. https://openaudible.org/beta
the documentation has a troubleshooting section as well.
