### ISSUE TITLE
Download failed, bad response: HTTP/1.1 204 No Content

### ISSUE THREAD

**Issue by jasonm010** [openaudible/openaudible#1151]
Hi. I'm getting an error state 'Download failed, bad response: HTTP/1.1 204 No Content'. It is on a book i just bought earlier today. I bought 3 others today as well and they all downloaded fine. Thoughts?

**Comment by openaudible** [comment]
Strange. Does the book play in your mobile audible app?
What audible region are you in?

**Comment by jasonm010** [comment]
I just downloaded the audible app and the book (Ordination by Daniel M Ford) played perfectly. I've used your app for years and have downloaded well over a hundred books from my library with no issues. This is obviously very strange.

I've closed the app several times, logged out of audible on the app and back in and still see the same error. Happy to provide any other information to help you out here. I'm in the US, southeast

**Comment by openaudible** [comment]
Can you try the beta?  We added a "fallback" method to download a book using an alternate method.

https://openaudible.org/beta

Might be a good idea to turn off automatic downloads & conversions in the prefs before upgrading... Just in case it doesn't find your library.

If that still doesn't work, please send a bug report from the Help menu. Thanks!

**Comment by jasonm010** [comment]
Thanks. I installed it and it downloaded fine. However, I was using an older version (3.1.2) as my license was only for that older version and has now expired ☹

**Comment by jasonm010** [comment]
So oddly enough, after using the beta then going back to the 3.1.2 version it's now downloading fine. go figure!

**Comment by openaudible** [comment]
Glad it is working.

Why did you go back to 3.1.2? Trying to get some more feedback on it so we can get it released.

**Comment by jasonm010** [comment]
I went back because my previous license was no longer valid so the beta wouldn’t allow me to convert to mp3. I can’t remember when I last renewed, but back when I paid for the full version it was via a donation (at the time it was all open with no trial vs full). I recall making the donation because I was getting so much use out of the product and wanted to show my appreciation. After I upgraded to 3.1.2 a few yrs ago it wouldn’t let me upgrade anymore without a license upgrade. It has worked ever since, so I never did go about renewing (was not broken so did not “fix”).

**Comment by harveydatasystems** [comment]
I am having this same problem with version 3.7    It downloads some. then seems to stop working.    I can usually get it started again by logging out and then back in, or restarting the app.    sometimes manually triggering the download multiple times gets it to occasionally work also.     As a new customer    I love the app.    but I've got over 250 books downloading so it is a bit maddening.    but   I'll take it over the older methods.
