### ISSUE TITLE
Mp3 Folder Names

### ISSUE THREAD

**Issue by DumelZA** [openaudible/openaudible#1153]
This is not really an issue but I don't know how else to contact you to ask this question. The mp3 folders are named according to the author of the book. Is it possible to change this to the name of the book?

**Comment by openaudible** [comment]
We don't typically create folders-- each audiobook is usually in a file by itself. Unless you are splitting a book by chapter-- then we use the title. Can you take a screenshot or provide a snippet of the OpenAudible console log of what you mean?  you can send an email to openaudible at email dot tg.

**Comment by DumelZA** [comment]
Hi there

 

Thank you for your response. It seems I made a mistake. When I right clicked on one of the books and selected “show MP3” it went to a folder I didn’t realise existed and that contained the mp3 files as single files and named by the title. Those other folders must have been made by another application before I found OpenAudible. So all is good. Apologies! I will delete the issue on GH.

 

Kind regards,

Hennie Botha

 

Dumel

Web Design and Search Engine Optimisation

 

Tel: 082 885 5555

For urgent support please send a text message or voice note using WhatsApp, Telegram or Signal

 

E-mail:  ***@***.***> ***@***.***

Web :  <https://www.dumel.co.za/> www.dumel.co.za

Business Hours: 08h30 - 17h00 (Weekdays)

 

Postal Address: Postnet Suite 91, Private Bag X22, Tyger Valley, 7536
