### ISSUE TITLE
Unable to connect to Audible

### ISSUE THREAD

**Issue by mayonaese** [openaudible/openaudible#1154]
When I attempt to connect OpenAudible to my Audible account, by signing into Audible using my Amazon account, I receive a popup titled: "Error registering virtual device" with the error message: Error creating a virtual device to communicate with Audible.  You may need to delete some of your registered audible devices...

I checked Amazon.com "Manage content and devices", only 1 device registered on Audible.

Therefore I am unable to see or manage any of my books that I own in Audible.

Copied from the Console:
Mar 11, 2023 2:38:49 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:Error registering virtual device body:
Error creating a virtual device to communicate with Audible. You may need to delete some of your registered audible devices. 
Visit https://help.audible.com/s/article/how-can-i-deactivate-devices-that-are-using-the-audible-app

**Comment by openaudible** [comment]
Try the latest 3.7 version. 
More at: https://openaudible.org/docs#login_errors
You can email or send a bug report from the Help menu if still having issues.
