### ISSUE TITLE
Import books available only in full version?

### ISSUE THREAD

**Issue by piretro** [openaudible/openaudible#116]
![2019-04-03 00_10_48-Window](https://user-images.githubusercontent.com/8805969/55439479-072f0e80-55a5-11e9-805e-f492572b4580.png)

I appreciated the automatic file naming in latest release, but I was not expecting this. Furthermore, I found nothing about a "full" premium version on the website.

Thank you

**Comment by openaudible** [comment]
That was some experimental code left in by mistake. This affects import and exporting. We are obviously considering a paid version, but for the time being, we will keep it free.

**Comment by openaudible** [comment]
Fixed in 1.4.5
