### ISSUE TITLE
OpenAudible suggestions

### ISSUE THREAD

**Issue by MMIKEE** [openaudible/openaudible#1160]
OpenAudible 3.7+ VIEW suggestions…
1.	Add a setting to allow “Auto Size Columns & Headers” of lower window…  
2.	Add Save & Print capability of 1 or more selected Audio Books of lower window…  So that information could be edited and copied & pasted into a spreadsheet or other document format… Currently, only the “Summary” window content can be Copied and/or Printed…
3.	Maybe add a setting to allow “Show Grid Lines” and / or “Mark Odd/Even Rows…  Not a big deal, but easier on the eyes for us older users…

**Comment by openaudible** [comment]
1. Unfortunately auto size isn't easily accomplished. Has to do with the new monitors that are high dpi.
2. Try the export to Excel function.. 
3. Odd/even colors used to be a thing we had.. but then with dark mode, it gets nasty trying to determine what the system might decide is a good color for tables. Might be able to add it to a theme setting.. will give it some thought!

Appreciate the suggestions and thank you for throwing those out.
