### ISSUE TITLE
Version 3.7 Mac - Fails to convert AAX to MP4

### ISSUE THREAD

**Issue by groggu** [openaudible/openaudible#1161]
After downloading a new book, I found that the automated conversion from AAX to M4B did not run.  I manually ran the convert to M4B command using the menu, and the action still did not complete.

MacBook Pro 2018 - 2.9 GHz 6-Core Intel Core i9, 32 GB
Mac OSX 13.2.1 (22D68) (Ventura)
The OA library is located on an external USB drive and was previously used by OA 3.6.x

When reviewing the console, I found the following error.

{
    "start_time": "28138.171973",
    "time_base": "1/22050",
    "start"Mar 17, 2023 3:17:52 PM org.openaudible.util.queues.ThreadedQueue jobError
INFO: ConvertQueue error processing convert Owner's Share item Owner's Share
java.lang.IllegalArgumentException
	at java.base/java.util.Date.parse(Date.java:616)
	at java.base/java.util.Date.<init>(Date.java:274)
	at org.openaudible.convert.ConvertJob.getCommonConversionArgs(ConvertJob.java:240)
	at org.openaudible.convert.ConvertJob.getConversionArgs(ConvertJob.java:315)
	at org.openaudible.convert.ConvertJob.convertFile(ConvertJob.java:368)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:618)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:720)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:513)

Mar 17, 2023 3:17:52 PM org.openaudible.Audible jobCompleted
INFO: ConvertQueue completed:Owner's Share ConvertQueue size:0 remain:0 success:0 fail:8 threads:1
Mar 17, 2023 3:17:54 PM org.openaudible.desktop.swt.manager.AudibleGUI _checkAutomation
INFO: Start auto conversion:2

The full error log, with book details, is attached.

[OpenAudible error.txt](https://github.com/openaudible/openaudible/files/11005160/OpenAudible.error.txt)

**Comment by openaudible** [comment]
Thank you for the bug report. That is a bug on our end. It will be fixed in the next beta.
The error happens when there are no decrpytion keys for the file you're trying to convert. We were attempting to generate a nice error message and messed up the file modification date string. 
In any case, you'll need to delete that AAX file (since it is hopelessly encrypted) and try downloading it again using OpenAudible.
Will close when a beta or new version is posted.

**Comment by groggu** [comment]
Thanks for the quick response.  I'll delete the AAX files that were downloaded and retry. I'll update this ticket with the results.

**Comment by groggu** [comment]
Thanks! That worked.  I found the books I downloaded in the aax directory and deleted them, then redownloaded them from Audible and they converted correctly.
