### ISSUE TITLE
Slow with a large number of books

### ISSUE THREAD

**Issue by appmu** [openaudible/openaudible#1163]
Hi,

It seems OpenAudible becomes slow when the number of books becomes large. Currently, I have about 8k books and the `books.json` file is about 51mb located on a local network drive.

It takes:
- 1 minute to start
- 30 seconds to sort (by clicking on a column)
- 40 seconds to update meta of a single book

It often happens that I click something unintended and the window becomes not responsible for a while. 

I guess the program often interacts with `books.json` thus takes time. If so, what about separate ignored books from the main library file (books.json) and store ignored book data to `books.ignored.json` or something? So the user can temporarily mark some books as ignored to speed up the program behavior and its responses.

Windows 10 64bit 
OpenAudible 3.7, 3.6.3

**Comment by openaudible** [comment]
We have a few optimizations in mind but that is a lot of books.  More RAM and a fast SSD drive might help. Marking as feature request, but will take a look.

**Comment by appmu** [comment]
Now the number of books has reached 12k and it's really hard to operate. I cannot allocate more memory for this virtual machine as I have to run other machines simultaneously. 

By pressing Control + R, downloading cover artwork takes forever, seeming to pause after downloading several images like three or four. I remember this was really quick and seamless. Also downloading audio books has become not seamless. After downloading one book, to start next, it takes 10 minutes or so. It used to be immediate and very smooth.

Memory: 4GB
OpenAudible 3.7.5

**Comment by openaudible** [comment]
Sounds like too many books on too little resources for our app. OpenAudible is a desktop app— not something designed to go on a VM. It needs memory and fast access to the file system. If your books are on a network drive that can slow things down a lot. You can check swap space and other common performance tools to see what the bottleneck is. OpenAudible lets you copy your whole library to another disk under File> Manage Libraries so you can try moving to an external drive and testing on a Mac or desktop pc.
