### ISSUE TITLE
Connect to Audible doesn't work on M1 Mac Studio

### ISSUE THREAD

**Issue by jessearmstrong** [openaudible/openaudible#1164]
I have been trying to connect to my Audible account on my M1 Mac. It keeps saying error creating virtual device. And check console. I don't see a way to access a console to check the error. I decided to try it using a virtualized copy of Arm Windows in Parallels and it worked just fine. I don't want to have to manage this in a virtual machine. I can't find any help information on this.

**Comment by jessearmstrong** [comment]
I am using version 3.7 licensed (I thought it might work if I paid for it)

**Comment by jessearmstrong** [comment]
So I was able to copy the credentials.json from the virtual machine and it seems to be working for far on the Mac, but it definitely is NOT working without this step.

**Comment by openaudible** [comment]
We test on m1. If you can try again and send a bug report from the about menu that would be great. That error is either a bug on our end or an unexpected result from audible that we aren’t handling properly. A bug report will give us a detailed error log.

**Comment by jessearmstrong** [comment]
Report sent. I am also getting an error now (most books downloaded, I have about 23 that are not downloading), when I try to sync my library I get the message "Unexpected error refreshing library. Check Console. If this persists, you may need to log out of Audible and long into Audible from the Controls Menu."

I don't know how to access the console on Mac.

**Comment by openaudible** [comment]
The error you're seeing has been fixed in the latest beta. I believe it is due to a file that needs to be deleted and re-downloaded.. but the nice message we tried to create made a bigger error that wasn't handled properly.

Give it a try.
https://openaudible.org/beta

**Comment by jessearmstrong** [comment]
No change for me with the Beta. I'll send another bug report.

**Comment by jessearmstrong** [comment]
Tried again with 3.7.1. Issue is the same. Tried logging out completely (I had copied the credentials.json from my windows virtual machine). Will not log in.

**Comment by openaudible** [comment]
Thanks for the bug report. Seems like it isn't getting cookies properly.. which it needs... Maybe a webkit bug or apple has locked down 3rd party software from getting the cookies?? At least I got a good bug report and error.. so will attempt to put more debugging code into a new beta.. stand by.. 

Also.. Can you try logging in with the alternate (no browser) method? (Second radio button on first connect dialog)

**Comment by jessearmstrong** [comment]
I wanted to try that but it asked for an Audible username and password but we log in with our Amazon Account. I wish I didn’t have to though. -JesseOn Mar 20, 2023, at 11:59 PM, openaudible ***@***.***> wrote:﻿
Thanks for the bug report. Seems like it isn't getting cookies properly.. which it needs... Maybe a webkit bug or apple has locked down 3rd party software from getting the cookies?? At least I got a good bug report and error.. so will attempt to put more debugging code into a new beta.. stand by..
Also.. Can you try logging in with the alternate (no browser) method? (Second radio button on first connect dialog)

**Comment by openaudible** [comment]
Oh you can enter your Amazon email/password. It should be the same as your audible username and password you use on their website.

**Comment by hjbarraza** [comment]
Version 3.6.1 worked for me

**Comment by oboe45** [comment]
works on my Mac studio

**Comment by asherok521** [comment]
I'm also running into the same issue on my M1 Mac mini. I tried both the latest release and the beta linked above and still cannot connect to my Audible account.

**Comment by openaudible** [comment]
Ok. We did find a couple more login bugs and have updated OpenAudible to 3.7.2. \
Thanks for the reports!
