### ISSUE TITLE
Doubled clipboard text when pasting in text area meta fields

### ISSUE THREAD

**Issue by appmu** [openaudible/openaudible#1165]
Hello,

It seems the clipboard functionality has a bug that doubles copied text when pasted in text area meta fields such as Notes and Summary. 

To reproduce it, 

1. Copy some text to the clipboard
2. Select a book and open the `Get Info` window (Ctrl + I)
3. Activate the Notes tab
4. Paste the clipboard content to the text area field

Windows 10 64bit
OpenAudible 3.7, 3.6.3

**Comment by openaudible** [comment]
Confirmed. Will fix in next beta (2). Will need to check on several platforms. Thank you for the heads up.

**Comment by openaudible** [comment]
Fixed in 3.7.1. Thank you.
