### ISSUE TITLE
[REQ] Generate NFO file

### ISSUE THREAD

**Issue by milegrin** [openaudible/openaudible#117]
Feature request if I may

Would it be possible to generate a text .nfo file along with the MP3 please?
Essentially store the "Audio Book Info" that you already display in OpenAudible to a text .nfo file alongside the cover image.

Example of the potential Contents of a .nfo file (Same info OpenAudible displays and aligned the same (github keeps removing alignment here ) ):
<< start >>
Title:                  The Black Ice: Harry Bosch Series Book2
Author:              Michael Connelly
Narrated by:      Dick Hill
Duration:           11:39:35
Release date:    17/06/2008
Purchase date:  13/03/2018
Genre:                Mysteries & Thrillers > Modern Detective 
Publisher:           Brilliance Audio
Copyright:          ©2004 Michael Connelly ℗2004 Brilliance Audio
ASIN:                 B002VAEK76
Product ID:        BK_BRLL_000252
Description:
Narcotics officer Cal Moore's orders were to look into the city's latest drug killing. Instead, he ends up in a motel room with his head in several pieces and a suicide note stuffed in his back pocket.

Years ago, Harry Bosch learned the first rule of the good cop: don't look for the facts, but the glue that holds them together. Now, Harry's making some very dangerous connections, starting with one dead cop and leading to a bloody string of murders that winds from Hollywood Boulevard's drug bazaar to the dusty back alleys south of the border and into the center of a complex and lethal game - one in which Harry is the next and likeliest victim.
<< end >>

Optional extras may be to add the bitrate, encoding etc of the MP3, Audible rating (eg 3.6 stars) and the link to the Audible page for the audio book.

PS: Add donation button to your site :)
Thank you!

**Comment by openaudible** [comment]
Is there any book players that uses .nfo files? What other apps are you using that make a good use case for adding that feature? This is one of those jobs any programmer can do by reading the books.json and writing the files.. I'm trying to avoid feature bloat. 

Will do on the donation page. Thanks.

**Comment by milegrin** [comment]
NFO files are a common usage for file indexing/descriptions and the library software I use to manage my ebook & audiobook library reads them to pre-populate fields when importing new books.

My family and I also use it to quickly read a little bit about a book when choosing books for our MP3 players and at the moment I am manually creating them by copying and pasting from the Audible site for the book and seeing the OpenAudible already extracts this information already on the GUI it would be a great feature to add.

As it is meta data I thought "art" would be a good place to save it but any folder would work equally well :)

Thank you for considering my request

**Comment by openaudible** [comment]
This would be a good 10 minute program for someone to write.. but need to keep it out of the app to avoid clutter. Thanks for the suggestion.

**Comment by milegrin** [comment]
Would you be prepared to release an optional companion app to do this?  (I am no programmer :( )
