### ISSUE TITLE
Downloading Books that are already downloaded

### ISSUE THREAD

**Issue by LarryBetz** [openaudible/openaudible#1170]
Updated to v3.7.1 and on startup the UI is attempting to download 277 books that have been downloaded in the past and are currently in the BOOKS  folder

**Comment by oboe45** [comment]
I have noticed that 3.7 and 3.1 and the betas that preceded it all finished
the login and indicated that some number of books were still to be
downloaded, this happens every time I load the app.  However, if I click
the m4b link or select the m4b download, the count of books to download is
cleared and everything is fine.  No the that the number it says are to be
downloaded is different most times.  Not a serious problem, but
consistently odd.

**Comment by Cybergate9** [comment]
same here for 3.7.1, and noticed there's no longer as many folder options in settings, so I'm not quite sure where it's downloading to (or where it's looking to see if books are already downloaded)..

odd..

**Comment by openaudible** [comment]
Sorry all. Use the File Menu: Manage Libraries to re-select your library location.

**Comment by LarryBetz** [comment]
> Sorry all. Use the File Menu: Manage Libraries to re-select your library location.

Sorry, but I need a bit more.  There are 2 options: Create New, or Open Existing.  The Open option wants to be pointed to a json.  I did both and neither worked.  Maybe you could give a step by step, 
Thanks

**Comment by Cybergate9** [comment]
> Sorry, but I need a bit more. 

In my case the directory containing the 'books' folder (also contains the aax, web and art folders), also has a _file_ called books.json. 
From my understanding this is the file which contains all the metadata for all the books in your _existing_ library.

So with/via 'Open Existing OpenAudible Library' button (via File Menu->Manage Libraries...) navigate to your current folder which contains your 'books' and 'aax' directories, and beside those directories your existing 'books.json' library file should exist?

**Comment by LarryBetz** [comment]
> So with/via 'Open Existing OpenAudible Library' button (via File Menu->Manage Libraries...) navigate to your current folder which contains your 'books' and 'aax' directories, and beside those directories your existing 'books.json' library file should exist?

Thanks for the directions... I have 2 BOOKS.json.  The one in the root was the problem.  However, I found one in the WEB folder.  That one fixed the issue.  
Thanks  :) 

** But now I receive an alert to update t the new 3.7.2 version, but when downloading I still get 3.7.1  🤦‍♂️

**Comment by Cybergate9** [comment]
> Thanks for the directions... I have 2 BOOKS.json. The one in the root was the problem. However, I found one in the WEB folder. That one fixed the issue. Thanks :)
Glad you've found your original library file.. :-)
(it may pay to move it out of the web folder because that one might get overwritten if you "export to web" again)

> ** But now I receive an alert to update t the new 3.7.2 version, but when downloading I still get 3.7.1

me too, something odd going on there, I'm just going to wait a few days (i.e. ignore update prompts for now) until the versions problem is sorted out

**Comment by noahsager** [comment]
I fixed this by moving all my .m4b books from the "books" folder to the "m4b" folder. After a Refresh Files, they were now being counted. Did the default directory for saving books change from books to m4b?

**Comment by openaudible** [comment]
Ok. Sorry for the issues.. Feel free to add more details..
