### ISSUE TITLE
feature request, autosplit books, and choose to not have artwork

### ISSUE THREAD

**Issue by Werpage** [openaudible/openaudible#1171]
Hi,
I wish there was a way to have all the books you convert automatically split post convert. Also, I wish there was an option to not have the jpeg image included in the folder with the split book. I'm blind, so I don't need the images. :)

**Comment by openaudible** [comment]
First is marked as a feature request. 2nd one is required for some media players, like Plex, to automatically find the artwork for the book.. We try hard to avoid UI changes that might make the application seem confusing, so we probably won't make that an option.  You may be able to search for .jpg and delete all files of that type. 
Thank you for the suggestions.
