### ISSUE TITLE
Library location cannot be changed in latest update.

### ISSUE THREAD

**Issue by JoanieOaks** [openaudible/openaudible#1173]
Since updating the app, I seem to have lost the option to change the location of my downloaded library contents. It seems to default to the C:/ drive which I only use for core software - and had been using another drive in previous versions. This was an option at the top of the preferences section but is no longer there.

Is this a 

![image](https://user-images.githubusercontent.com/128754356/227378235-96044989-4184-4620-b119-fb606e008081.png)

**Comment by openaudible** [comment]
New feature: File Menu: Manage Libraries: Switch between different libraries.
