### ISSUE TITLE
cannot connect openaudible to amazon/audible account

### ISSUE THREAD

**Issue by brlale** [openaudible/openaudible#1174]
I'm new here and wanted to try OpenAudible so just downloaded version 3.7.2 on mac, but cannot get it to connect to my audible account.

Under Control > Connect to Audible, if I select the secure web browser login, and select US as the region, as soon as I click Next, OpenAudible quits and I get a "JavaApplicationStub quit unexpectedly" error. I don't even have the chance to input my log in.

If I select Secure OpenAudible Login, I input my username and password, go through two captchas, and then I get a Login Error:

"An unexpected error occurred while logging in.

Error: no protocol:

This may indicate a bug that needs fixing in OpenAudible.

Would you like to file a bug report? Issue #500 has been created for this error."

Please help. I'd really like to be able to try your product. Now I'm just glad I didn't spend the money on the license before trying it since I don't appear to be able to use it at this time.

**Comment by taramisu47** [comment]
Also having this issue. Could not get the old version to download books even though it said it was connected to Audible. Kept getting "Bad Request" error. Upgraded to 3.7.2 and now it won't connect to Audible at all. It tells me to deauthorize extra devices with Audible. I did so and it did not help.

**Comment by openaudible** [comment]
Shoot. It does look like there are some issues with connecting using the dialogs— got a few bug reports we are looking at. 
try logging in with the web browser (first radio). 

Will try a few things and get a beta out soon. 

If you have an older version that was working (or success on another computer) you can copy the credentials.json file over to get connected.

**Comment by taramisu47** [comment]
Neither method of signing in works. And my old version stopped working as well.  

Thank you for your response!

Tara

⁣Get BlueMail for Android ​

**Comment by ShrubWitch** [comment]
I got this error message... I thought it was because i changed my Amazon login credentials... it appears we've been locked out... hoping for a patch. 

![image](https://user-images.githubusercontent.com/128941698/227747884-8e3bfc1e-1ed5-46a1-8043-04d7bfeaa36e.png)

**Comment by smitch7613** [comment]
I am getting an error registering a virtual device as well. I did deactivate devices using the audible app but I still cannot get openaudible to link to my audible account.

**Comment by openaudible** [comment]
Sorry for the issues. This should be resolved in 3.7.3.
