### ISSUE TITLE
AAX Download resume

### ISSUE THREAD

**Issue by milegrin** [openaudible/openaudible#118]
Improvement request please.
Enable "resume" option on failed AAX downloads instead of restarting from scratch.  
When using a slow link this can be frustrating when a file fails near the end and it restarts from scratch.

**Comment by openaudible** [comment]
Unable. Sorry.

**Comment by feldegast** [comment]
> Improvement request please. Enable "resume" option on failed AAX downloads instead of restarting from scratch. When using a slow link this can be frustrating when a file fails near the end and it restarts from scratch.

as a fellow user with a slow connection, I have the same issue what I do when I have this issue is use wget -c <URL of aax file> then import the downloaded file

**Comment by feldegast** [comment]
you may like to know, resume is available in ver 3.4.3.1beta (I shared some source code and got it added) currently testing and fixing bugs but resume is working for me
