### ISSUE TITLE
OpenAudible Preferences "OPENAUDIBLE_HOME" Variable

### ISSUE THREAD

**Issue by Puddl36lum** [openaudible/openaudible#1180]
I was curious about the rationale behind changing the way a user can set the location of where audiobooks are stored?  I'd consider myself an average user and this seems a little much for the average user.  

In prior versions, you could simply browse to the location in the settings and set the location where audiobooks were saved (the way you set the web directory). But now a user has to move "the directory" (which directory?) somewhere else (anywhere?), and set an environment variable (what's an environment variable?) to point to the new location (where i moved "the" directory or maybe an existing directory on a NAS on a home network that a prior version of OpenAudible was set to?).

At least, if this is a permanent change, update the documentation so that a luddite like myself can just set the path without too much trouble.

**Comment by openaudible** [comment]
Do not use the OPENAUDIBLE_HOME (under normal circumstance.) We changed the location of the library to "Manage Library" under the File menu. We will add a note in the documentation. Thanks for the reminder about the documentation.
