### ISSUE TITLE
Manage Library's not working

### ISSUE THREAD

**Issue by eea3** [openaudible/openaudible#1181]
as with setting openaudible_home not working the manage lib's does not do anything
I try to open the existing library and select the books.json and nothing changes!
just updated to the latest version 3.7.3 the previous version was working

**Comment by openaudible** [comment]
Check the console log. If the library is already set to point to your books.json, setting it again in the manage library won't do anything.

Maybe do a full Library Rescan and Refresh files from the control menu?
