### ISSUE TITLE
FFProbe error running latest version on Centos 8 Stream

### ISSUE THREAD

**Issue by mraganpbr** [openaudible/openaudible#1182]
Cannot convert to Mb4 after download from Audible
Logs below:
Apr 02, 2023 5:49:35 PM org.openaudible.util.queues.ThreadedQueue jobError
INFO: ConvertQueue error processing convert Behemoth item Behemoth
java.io.IOException: ffprobe error on /home/rodeo1221/OpenAudible/aax/Behemoth.AAX
	at org.openaudible.convert.FFProbe.probe(FFProbe.java:59)
	at org.openaudible.convert.AudibleProbe.<init>(AudibleProbe.java:20)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:624)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:736)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:513)

Apr 02, 2023 5:49:35 PM org.openaudible.Audible jobCompleted
INFO: ConvertQueue completed:Behemoth ConvertQueue size:0 remain:0 success:0 fail:222 threads:1
Apr 02, 2023 5:49:37 PM org.openaudible.desktop.swt.manager.AudibleGUI _checkAutomation
INFO: Start auto conversion:215
Apr 02, 2023 5:50:21 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Convert_All

I was asuming it may have been some sort of permissions issue after I downloaded all the books. 
Here is the file structure that was built in /home/rodeo1221/Openaudible

drwxrwxrwx. 2 rodeo1221 rodeo1221   12288 Apr  1 08:11 aax
drwxrwxrwx. 2 rodeo1221 rodeo1221   12288 Mar 31 20:33 art
drwxrwxrwx. 2 rodeo1221 rodeo1221       6 Mar 31 20:25 books
-rwxrwxrwx. 1 rodeo1221 rodeo1221 2307311 Apr  1 21:03 books.json
-rwxrwxrwx. 1 rodeo1221 rodeo1221   11837 Mar 31 20:33 credentials.json
-rwxrwxrwx. 1 rodeo1221 rodeo1221     153 Apr  2 17:38 directories.json
-rwxrwxrwx. 1 rodeo1221 rodeo1221     259 Apr  2 17:38 libraries.json
-rwxrwxrwx. 1 rodeo1221 rodeo1221     670 Mar 31 20:27 license.json
-rwxrwxrwx. 1 rodeo1221 rodeo1221     583 Apr  1 08:47 settings.json
drwxrwxrwx. 2 rodeo1221 rodeo1221      40 Apr  2 17:38 tmp
-rwxrwxrwx. 1 rodeo1221 rodeo1221    1616 Apr  1 21:03 windows.json

**Comment by openaudible** [comment]
We recently updated ffmpeg/ffprobe for 3.7 to improve m4b metadata. 
Unfortunately I don't see an actual error message. Can you try again and send a bug report from the About menu?
Or you can try running our ffprobe from the command line on a file.. 
Its possible we or linking to a library not installed on your system-- so if you have a linux distribution and/or ISO we can reproduce it here.

**Comment by mraganpbr** [comment]
Bug report sent. Yes that is the correct ISO

**Comment by openaudible** [comment]
Error is glibc compatibility problem: 
stderr:/opt/OpenAudible/bin/linux_x86_64/ffprobe: /lib64/libm.so.6: version `GLIBC_2.29' not found (required by /opt/OpenAudible/bin/linux_x86_64/ffprobe)

will try to fix but may be a problem with centos 8 stream. Found several others affected by googling glibc centos 8. Apparently we link against 2.29 and it isn’t safe to attempt to change whatever version your OS uses.

**Comment by mraganpbr** [comment]
I will look forward seeing what you come up with

**Comment by openaudible** [comment]
Confirmed and working on a solution.

**Comment by openaudible** [comment]
Fixed and updated ffmpeg/ffprobe in our latest beta 2:
https://openaudible.org/beta
Spent a day learning about the joys of building linux apps that are supposed to be compatible with everything. 
Thanks for the report!

**Comment by mraganpbr** [comment]
WOW!!! Nice work guys. This is now converting like a champ. Really impressed

**Comment by openaudible** [comment]
Fixed in latest release. Thanks for the report.
