### ISSUE TITLE
All actions are being "skipped"--Can't add new books or split files

### ISSUE THREAD

**Issue by struckdumm** [openaudible/openaudible#1183]
Every time I try and split a file already loaded this pops up in my browser window and if I try and add a new book it just skips it. I recently did a software update on my computer and then after this issue updated openaudible thinking that might be the issue but it didn't help.

"Selected 1 book(s) to split

Skipped "BookTitle Destination directory exists:/Users/admin/Library/OpenAudible/books/booktitle

Good:0, Errors:0 Skipped:1
Destination: /Users/admin/Library/OpenAudible/books"

**Comment by openaudible** [comment]
Is it possible they've already been converted? 
Check to see if /Users/admin/Library/OpenAudible/books/booktitle is a directory and what is in it. If it is empty, just delete it and try again.  (this is a bug we recently saw and I think is fixed in our beta.) 

We also made a change for splitting to correct for faulty chapter data from audible-- you can try our beta for an update: https://openaudible.org/beta

**Comment by struckdumm** [comment]
> Is it possible they've already been converted? Check to see if /Users/admin/Library/OpenAudible/books/booktitle is a directory and what is in it. If it is empty, just delete it and try again. (this is a bug we recently saw and I think is fixed in our beta.)
> 
> We also made a change for splitting to correct for faulty chapter data from audible-- you can try our beta for an update: https://openaudible.org/beta
> 
> Edit: Also check for low disks space.

Thanks, it looks like it's now starting to convert new books but is working very very slow... a rate of 5-10 seconds of audio per real time second. Splitting function also isn't working at all.

**Comment by openaudible** [comment]
M4B format should be very fast. MP3 is slower but can depend on cpu and disk speed. 

Splitting should work. Again, check the contents of the directory it says it was going to split to. And try the beta 2.

**Comment by Michelleh123321** [comment]
Hi Open Audible! I am having the same problem because my desktop accidentally got unplugged while the chapters were splitting. How do I get the split function to work again? I don't understand the directions that you listed above.

thanks so much! Michelle

**Comment by openaudible** [comment]
One, we upgraded the alert message when a book is skipped. Run a About Menu > Check for Update. (or use 3.7.6.1)
To split a book by chapter, select the book, right click and select "Split book". If it says it was skipped, it is likely it has already been split-- check the log message to see for sure, File > Console.

**Comment by Michelleh123321** [comment]
Below is what it says when I go to, File > Console. I was splitting the books when my son accidentally unplugged the computer and it shut off while it was splitting. So I'm not sure where to find the files to save them as individual books. 


Jun 11, 2023 5:57:11 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 3.7.6.2 for cocoa swt 4956 jvm 11.0.15
Jun 11, 2023 5:57:12 PM org.openaudible.Directories load
INFO: Loading directories. These must be online and read/writable:
->{
 "META": "/Users/barbarabrinkman/Library/OpenAudible",
 "APP": "/Volumes/OpenAudible/OpenAudible.app/Contents/Resources/app",
 "MP3": "",
 "PDF": "",
 "ART": "",
 "TMP": "/Users/barbarabrinkman/Library/OpenAudible/tmp",
 "AAX": "",
 "M4B": "",
 "M4A": "",
 "BOOKS": "",
 "BASE": "/Users/barbarabrinkman/Library/OpenAudible"
}
Jun 11, 2023 5:57:13 PM org.openaudible.Directories getPrefs
INFO: Loading /Users/barbarabrinkman/Library/OpenAudible/settings.json exists=true size=574
Jun 11, 2023 5:57:13 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1686349911311
Jun 11, 2023 5:57:13 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 3.7.6.2 mac
Jun 11, 2023 5:57:13 PM org.openaudible.desktop.swt.util.shop.PaintShop prefer2x
INFO: useHighDPI=false
Jun 11, 2023 5:57:14 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: sw_vers -productVersion 
Jun 11, 2023 5:57:14 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: uname -m 
Jun 11, 2023 5:57:14 PM org.openaudible.util.Arch systemArch
INFO: Ran systemArch: x86_64
Jun 11, 2023 5:57:14 PM org.openaudible.util.Arch macVenturaOnIntel
INFO: MacOS Ventura on Intel: 11.5 x86_64 is: false
Jun 11, 2023 5:57:14 PM org.openaudible.Directories getPrefs
INFO: Loading /Users/barbarabrinkman/Library/OpenAudible/settings.json exists=true size=574
Jun 11, 2023 5:57:14 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1686349911311
Jun 11, 2023 5:57:14 PM org.openaudible.audible.AudibleConnectionState setRegion
INFO: Setting audible region to US
Jun 11, 2023 5:57:14 PM org.openaudible.desktop.swt.manager.AudibleGUI loadPrefs
INFO: Saving prefs on startup, reason: setting lastVersion,
Jun 11, 2023 5:57:14 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 574 to disk:/Users/barbarabrinkman/Library/OpenAudible/settings.json
Jun 11, 2023 5:57:14 PM org.openaudible.library.LibraryManager activate
INFO: activating: /Users/barbarabrinkman/Library/OpenAudible [
 {
  "path": "/Users/barbarabrinkman/Library/OpenAudible",
  "kind": "BASE",
  "exists": true,
  "enabled": true
 },
 {
  "path": "/Users/barbarabrinkman/Library/OpenAudible/books",
  "kind": "BOOKS",
  "exists": true,
  "enabled": true
 },
 {
  "path": "/Users/barbarabrinkman/Library/OpenAudible/web",
  "kind": "WEB",
  "exists": false,
  "enabled": true
 },
 {
  "path": "/Users/barbarabrinkman/Library/OpenAudible",
  "kind": "META",
  "exists": true,
  "enabled": true
 },
 {
  "path": "/Users/barbarabrinkman/Library/OpenAudible/tmp",
  "kind": "TMP",
  "exists": true,
  "enabled": true
 },
 {
  "path": "/Volumes/OpenAudible 1/OpenAudible.app/Contents/Resources/app",
  "kind": "APP",
  "exists": true,
  "enabled": true
 }
]
Jun 11, 2023 5:57:14 PM org.openaudible.library.BookLibrary load
INFO: Loading /Users/barbarabrinkman/Library/OpenAudible/books.json
Jun 11, 2023 5:57:14 PM org.openaudible.audible.AudibleConnectionState connectionChanged
INFO: Connection state changed to Connected from Not_Connected
Jun 11, 2023 5:57:14 PM org.openaudible.audible.APIManager postInit
INFO: postInit API ready.
Jun 11, 2023 5:57:14 PM org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFO: applicationStarted took 382 ms. to complete.
Jun 11, 2023 5:57:17 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: sysctl -n sysctl.proc_translated 
Jun 11, 2023 5:57:18 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Jun 11, 2023 5:57:26 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Split_Selected_Books
Jun 11, 2023 5:57:26 PM org.openaudible.desktop.swt.manager.SplitJoinGUI run
INFO: Split 1 The Chronicles of Narnia Complet -> Skipped The Chronicles of Narnia Complete Audio Collection Destination directory exists:/Users/barbarabrinkman/Library/OpenAudible/books/The Chronicles of Narnia Complete Audio Collection
Jun 11, 2023 5:57:26 PM org.openaudible.desktop.swt.manager.browser.BrowserFactory browse
INFO: Browse to URL: file:/Users/barbarabrinkman/Library/OpenAudible/tmp/split_report.html
Jun 11, 2023 5:57:26 PM org.openaudible.Directories getPrefs
INFO: Loading /Users/barbarabrinkman/Library/OpenAudible/settings.json exists=true size=574
Jun 11, 2023 5:57:26 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1686349911311
Jun 11, 2023 5:58:20 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by openaudible** [comment]
The book is already split, located:
/Users/barbarabrinkman/Library/OpenAudible/books/The Chronicles of Narnia Complete Audio Collection

**Comment by Michelleh123321** [comment]
> The book is already split, located:
> /Users/barbarabrinkman/Library/OpenAudible/books/The Chronicles of Narnia Complete Audio Collection

I was able to find the books! But I noticed that it is missing some chapters. How do I recover the missing chapters?
