### ISSUE TITLE
Hitting "cancel"  while starting up will corrupt books.json

### ISSUE THREAD

**Issue by bilcorry** [openaudible/openaudible#1184]
Dropbox is a disk I/O hog.  If I open OpenAudible while Dropbox is busy uploading/downloading a file, OpenAudible will do it's normal startup by processing books.json and will display each book with a number in a dialog box, e.g. "4. Some Book Title".  I normally never see this because it loads so fast, but when the disk I/O is saturated, OpenAudible goes really slow and I'm able to see the dialog box.  It's happened twice and both times I hit "cancel" -- I figured I'd just wait for Dropbox to finish, then try again.  But hitting "cancel" results in a IO error in OpenAudible and books.json is then saved with only a few books rather than my entire library, corrupting it.  Even crazier, besides corrupting books.json, OpenAudible also does not cancel but instead will start downloading new books.  It's suppose to ask me first and usually does, but when I hit cancel, it corrupts books.json and downloads new books without asking.

I now know not to cancel that initial dialog startup process, but in case there's something that can be done to fix it, I'm passing along this report.  I'm using v3.7.3.

**Comment by openaudible** [comment]
Will fix. Thank you for the report.

**Comment by openaudible** [comment]
Fixed in 3.7.4. Thanks for the report. That was a nasty one.
