### ISSUE TITLE
Not able to re-connect to audible account

### ISSUE THREAD

**Issue by jjgaff** [openaudible/openaudible#1185]
I've searched previous posts and having similar issues with my mac. I've tried all the suggested methods including sending an error code, downloading the latest version, and downloading the beta. I've tried logging in via browser and non browser but neither has worked.

**Comment by openaudible** [comment]
We did some more research on the bug reports we've seen. Check your firewall and make sure OpenAudible is allowed to connect to audible and openaudible.org. (You can make sure the "Check for new version" works.) Or look for a "HostNotFound" exception in the log. 
Also make sure you can log into audible from your regular desktop browser. Sometimes an account can be "locked until the password is changed."
But repeated failures is probably a firewall issue.. but we can't know for sure without looking at a bug report.

**Comment by openaudible** [comment]
Try 3.7.4.. we added an error message for firewall issues (maybe) and made a few small changes.. Feel free to respond here or file a bug report from the About menu.
