### ISSUE TITLE
Conversion to m4b stopped after 13 of 188 books

### ISSUE THREAD

**Issue by cosmicseahorse** [openaudible/openaudible#1186]
First time licensed user. Downloads completed, but m4b conversion froze after 13 of 188 books. Using version 3.7.3. Please help.

**Comment by openaudible** [comment]
Check disk space. Look for error messages in the File: Console. If you got an error on a conversion click on the book to see what the error is. If actually frozen that would be unusual. 
More troubling shooting in documentation but disk space is most common.

**Comment by cosmicseahorse** [comment]
Wow, I would never have guessed, but you were right. Disk space. Thank you! :)
