### ISSUE TITLE
Merging multiple Audible accounts

### ISSUE THREAD

**Issue by the-nicolas** [openaudible/openaudible#1187]
I know that this is not an issue, but found no other support channel to ask.
The license says, that I can connect up to 5 audible accounts.
For me that looked like, that I can have more than one account and sync them together.

What I am looking for:
I have several audible accounts and want to sync and join all the books to one collection - and export them as a webpage to have a full overview. What would be the best way to achieve that?

Thanks for help!

**Comment by openaudible** [comment]
Just connect to one account, do full library download and convert, log out, and repeat the process. We do limit the number of accounts to five.
