### ISSUE TITLE
Could not find AAX file checksum

### ISSUE THREAD

**Issue by hawkiboy** [openaudible/openaudible#1188]
Really sad. This sw ALWAYS asks me to upgrade then downloads where I do not know. SO I finally went to the site and downloaded and wiped out my old version before I realized this was not a free upgrade. Great. So now I have to figure out how to downgrade.... which version. So I went to Version 3. Now everything is broken. It will not convert to mp3, it will not download. I am so mad (and sad as I said) that I tried to upgrade. I would pay for the upgrade but wonder if that is broken too. My old version worked fine.

Convert to MP3 - Could not find aax file checksome:---path to my library.... /becoming animal.AAX. size=tru (message cuts off)
So I tried to delete the AAX file then redownload it:
Download failed, bad response:HTTP/1.1 204 No Content
---
Tried to delete a title, the resync. Now the message:
Download error: No Library Record Found for user. for (book title)
All books can be downloaded from audible.com no problem.

**Comment by openaudible** [comment]
Sorry for the trouble. We try to make it clear if an upgrade is not free. 
Send me an email at openaudible at email dot tg and I'll see if I can upgrade you.
To downgrade or switch versions: https://openaudible.org/license (or click on the link in the license dialog.)
To select a library, in 3.7.x, use the Manage Libraries under the File menu.
Before downloading, make sure it says "Connected yes" and the file still is in your library.

**Comment by hawkiboy** [comment]
I upgraded and the new version works. but I really do hate the 'New Version
pop up window that ALWAYS opens.  I would prefer something in preferences
to allow the user to disable it. Also, it asks if you want to download with
no button for 'NO' so you have to close it with the little bubble closer in
the upper left corner. And if you do request a download it seems to
proceed, but then nothing happens and I can never see that any file was
downloaded. Most apps will auto-update. Other apps like Libreoffice just
send you to their download page using the default browser. I think that is
preferable.

**Comment by openaudible** [comment]
You can disable "Version Check on Startup" in the preferences. 
Agree, downloading via a browser would be better.. will switch back to that. 
Again, drop me an email and I'll upgrade your license.

**Comment by hawkiboy** [comment]
Thanks. I already upgraded.
