### ISSUE TITLE
Cannot update 3.6.3 to 3.7.4 on MacOS Ventura

### ISSUE THREAD

**Issue by NimbleThink** [openaudible/openaudible#1189]
When I click the "Download..." button in the update version dialog the runs for a bit and then a waiting wheelie appears and the application is reported as "not responding" by the system.
MacOS Ventura 13.2.1

Partial error report:

Date/Time:        2023-04-07 19:24:45.820 -0700
End time:         2023-04-07 19:25:08.675 -0700
OS Version:       macOS 13.2.1 (Build 22D68)
Architecture:     x86_64h
Report Version:   40
Incident Identifier: C4A843A3-47AE-4BB1-9DD7-40E933F3F59D

Data Source:      Stackshots
Shared Cache:     57815A20-AF2C-3B56-9006-23ABDE7962B0 slid base address 0x7ff80a9ba000, slide 0xa9ba000 (System Primary)
Shared Cache:     E1E267C5-FE0B-3ED9-86BE-E4F329F01460 slid base address 0x7ff805bb5000, slide 0x5bb5000 (DriverKit)

Command:          JavaApplicationStub
Path:             /Applications/OpenAudible.app/Contents/MacOS/JavaApplicationStub
Identifier:       org.openaudible.openaudible
Version:          3.6.3 (3.6.3)
Team ID:          XQ3TNHB55H
Is First Party:   No
Architecture:     x86_64
Parent:           launchd [1]
PID:              23251
Time Since Fork:  112s

Event:            hang
Duration:         22.86s
Duration Sampled: 5.30s (process was unresponsive for 18 seconds before sampling)
Steps:            53 (100ms sampling interval)

Hardware model:   MacBookPro16,1
Active cpus:      12
HW page size:     4096
VM page size:     4096

Time Since Boot: xxx
Time Awake Since Boot:xxx 
Time Since Wake:  xxx

Fan speed:        xxx
Total CPU Time:   xxx
Advisory levels:  Battery -> 2, User -> 2, ThermalPressure -> 0, Combined -> 2
Free disk space:  47.15 GB/xxx
Vnodes Available: 71.xx% (187791/xxx)

Preferred User Language: en-US, fr-US
Country Code:     US
Keyboards:        U.S.
OS Cryptex File Extents: 2032

--------------------------------------------------
Timeline format: stacks are sorted chronologically
Use -i and -heavy to re-report with count sorting
--------------------------------------------------

Heaviest stack for the main thread of the target process:
  53  <truncated backtrace>
  53  ??? [0x19756a10]
  53  JVM_MonitorWait + 301 (libjvm.dylib + 4401589) [0x11e089b5]
  53  ObjectSynchronizer::wait(Handle, long, Thread*) + 248 (libjvm.dylib + 7680678) [0x121292a6]
  53  ObjectMonitor::wait(long, bool, Thread*) + 737 (libjvm.dylib + 6386441) [0x11fed309]
  53  os::PlatformEvent::park() + 126 (libjvm.dylib + 6498366) [0x1200883e]
  53  __psynch_cvwait + 10 (libsystem_kernel.dylib + 16666) [0x7ff80ad4b11a]
 *53  psynch_cvcontinue + 0 (com.apple.kec.pthread + 20912) [0xffffff800371e1b0]

Process:          JavaApplicationStub (OpenAudible) [23251]
UUID:             FD129C22-27B7-371A-8D97-EF30E5D81912
Path:             /Applications/OpenAudible.app/Contents/MacOS/JavaApplicationStub
Identifier:       org.openaudible.openaudible
Version:          3.6.3 (3.6.3)
Team ID:          XQ3TNHB55H
Is First Party:   No
Shared Cache:     57815A20-AF2C-3B56-9006-23ABDE7962B0 slid base address 0x7ff80a9ba000, slide 0xa9ba000 (System Primary)
Architecture:     x86_64
Parent:           launchd [1]
UID:              501
Footprint:        330.15 MB
Pageins:          2 pages
Time Since Fork:  112s
Num samples:      53 (1-53)
CPU Time:         0.054s (97.8M cycles, 49.1M instructions, 1.99c/i)
Note:             Unresponsive for 18 seconds before sampling
Note:             1 idle work queue thread omitted

  Thread 0x914a4    DispatchQueue "com.apple.main-thread"(1)    53 samples (1-53)    priority 47 (base 47)    cpu time <0.001s (158.6K cycles, 242.8K instructions, 0.65c/i)
  <process frontmost, thread QoS user interactive (requested user interactive), process unclamped, process received importance donation from WindowServer [157], IO tier 0>
  53  <truncated backtrace> 1-53
    53  ??? [0x19756a10] 1-53
      53  JVM_MonitorWait + 301 (libjvm.dylib + 4401589) [0x11e089b5] 1-53
        53  ObjectSynchronizer::wait(Handle, long, Thread*) + 248 (libjvm.dylib + 7680678) [0x121292a6] 1-53
          53  ObjectMonitor::wait(long, bool, Thread*) + 737 (libjvm.dylib + 6386441) [0x11fed309] 1-53
            53  os::PlatformEvent::park() + 126 (libjvm.dylib + 6498366) [0x1200883e] 1-53
              53  __psynch_cvwait + 10 (libsystem_kernel.dylib + 16666) [0x7ff80ad4b11a] 1-53
               *53  psynch_cvcontinue + 0 (com.apple.kec.pthread + 20912) [0xffffff800371e1b0] 1-53

  Thread 0x914b0    53 samples (1-53)    priority 31 (base 31)
  <process frontmost, thread QoS default (requested default), process unclamped, process received importance donation from WindowServer [157], IO tier 0>
  53  thread_start + 15 (libsystem_pthread.dylib + 7291) [0x7ff80ad82c7b] 1-53
    53  _pthread_start + 125 (libsystem_pthread.dylib + 25177) [0x7ff80ad87259] 1-53
      53  apple_main + 84 (libjli.dylib + 29758) [0x10c2d43e] 1-53
        53  main + 34 (JavaApplicationStub + 43490) [0xed799e2] 1-53
          53  launcher_main + 226 (JavaApplicationStub + 42706) [0xed796d2] 1-53
            53  JLI_Launch + 6260 (libjli.dylib + 15272) [0x10c29ba8] 1-53
              53  JVMInit + 262 (libjli.dylib + 28580) [0x10c2cfa4] 1-53
                53  -[NSObject(NSThreadPerformAdditions) performSelectorOnMainThread:withObject:waitUntilDone:] + 124 (Foundation + 320652) [0x7ff80bcac48c] 1-53
                  53  -[NSObject(NSThreadPerformAdditions) performSelector:onThread:withObject:waitUntilDone:modes:] + 450 (Foundation + 321454) [0x7ff80bcac7ae] 1-53
                    53  -[_NSThreadPerformInfo wait] + 63 (Foundation + 6664808) [0x7ff80c2b9268] 1-53
                      53  __psynch_cvwait + 10 (libsystem_kernel.dylib + 16666) [0x7ff80ad4b11a] 1-53
                       *53  psynch_cvcontinue + 0 (com.apple.kec.pthread + 20912) [0xffffff800371e1b0] 1-53

  Thread 0x914b3    Thread name "Java: GC Thread#0"    53 samples (1-53)    priority 31 (base 31)    cpu time <0.001s (215.2K cycles, 71.6K instructions, 3.01c/i)
  <process frontmost, thread QoS default (requested default), process unclamped, process received importance donation from WindowServer [157], IO tier 0>
  53  thread_start + 15 (libsystem_pthread.dylib + 7291) [0x7ff80ad82c7b] 1-53
    53  _pthread_start + 125 (libsystem_pthread.dylib + 25177) [0x7ff80ad87259] 1-53
      53  thread_native_entry(Thread*) + 313 (libjvm.dylib + 6463447) [0x11ffffd7] 1-53
        53  Thread::call_run() + 104 (libjvm.dylib + 7846916) [0x12151c04] 1-53
          53  GangWorker::loop() + 39 (libjvm.dylib + 8319971) [0x121c53e3] 1-53
            53  SemaphoreGangTaskDispatcher::worker_wait_for_task() + 18 (libjvm.dylib + 8321312) [0x121c5920] 1-53
              53  semaphore_wait_trap + 10 (libsystem_kernel.dylib + 5438) [0x7ff80ad4853e] 1-53
               *53  ??? (kernel + 1365216) [0xffffff80004294e0] 1-53

**Comment by openaudible** [comment]
Hmm... firewall? 
Try downloading from: https://openaudible.org/

**Comment by openaudible** [comment]
I will try to reproduce on our end.

**Comment by openaudible** [comment]
That code is supposed to just open a web browser to go to our web page where you can download the latest version. Haven't see too much about it hanging there for any reason.. Maybe a firewall or ?? If you go to the About>Documentation, we should use the same code to open a browser to show the docs.. So not sure if that also hangs. Can you let me know if that is still happening?
