### ISSUE TITLE
Window becomes invisible sometimes

### ISSUE THREAD

**Issue by appmu** [openaudible/openaudible#1190]
Hello,

Sometimes, the window does not open after staring OpenAudible. It seems the window position information is not updated properly like below.

windows.json
```json
 "window_pos": {
  "maximized": false,
  "x": -32000,
  "width": 160,
  "y": -32000,
  "open": true,
  "height": 39
 },
```

After changing that part to the following, it started normally.
```json
 "window_pos": {
  "maximized": false,
  "x": 1,
  "width": 600,
  "y": 1,
  "open": true,
  "height": 320
 },
```

It might be a good idea to initialize the window positions when the previous position contains a negative number. 

Windows 10
OpenAudible 3.7.4 (This happened in earlier versions like 3.6.x)

**Comment by appmu** [comment]
One monitor on a virtual machine.

This seems to occur when the program is forcefully terminated when it is freezing, which often occurs in my environment. When it freezes, the window title shows "(Not Responding)".

**Comment by openaudible** [comment]
Fixed in latest beta https://openaudible.org/beta and will be in the next release. thanks for the  heads up.
