### ISSUE TITLE
Not working for yoto

### ISSUE THREAD

**Issue by jzatarai** [openaudible/openaudible#1191]
This program creates mp3s but they will not work with Yoto. How can I receive a refund?

**Comment by openaudible** [comment]
Try switching from VBR to CBR in the prefs or vice versa and try one more time. Some players don’t work with vbr but vbr makes a smaller file so it is sometimes preferred.  Let us know.

**Comment by jzatarai** [comment]
I'll be honest, I have no idea how to do that lol. I thought it was already
not VBR

**Comment by openaudible** [comment]
Just go to preferences and look at output format. Cog icon in upper right gets prefs.

**Comment by jzatarai** [comment]
ok I tried downloading both ways, toggling back and forth between vbr and
not and neither is working

**Comment by openaudible** [comment]
I’ve had users report that OpenAudible works with Yoto— but it isn’t great because there is no way to fast forward or reverse. Not really anything we can do about that. 

What error or problem are you experiencing exactly?

**Comment by jzatarai** [comment]
So after fiddling around with it yesterday hers what I’ve figured out. If I save the mp3 files to the desktop, attach them and email to myself, download it and save back to the desktop then I can put them on my Yoto. The only problem is I cannot do that with files larger than 25mbs because those cannot be sent through as regular attachments. Any suggestions? If I try sending as a google file it won’t work. Yoto said as long as file size is under 100 per chapter or 500 total it should workSent from my iPhoneOn Apr 11, 2023, at 9:56 PM, openaudible ***@***.***> wrote:﻿
I’ve had users report that OpenAudible works with Yoto— but it isn’t great because there is no way to fast forward or reverse. Not really anything we can do about that.
What error or problem are you experiencing exactly?

**Comment by openaudible** [comment]
You would need to split the book by chapter. Select a book, Action>Split Selected Book(s).
Then you get an MP3 with one mp3 per chapter.
