### ISSUE TITLE
Transfer of OpenAudible file to Yoto

### ISSUE THREAD

**Issue by murphyboysmom5** [openaudible/openaudible#1194]
I have successfully converted a file from Audible using OpenAudible and have attempted to load it onto Yoto to make my own card. It goes through the process of uploading the individual chapters, but when it goes to process each one, once reaching 100 percent, it says, " Failed to process file. Make sure it's a valid MP3, M4A or AAC audio." I tried deleting the book from my computer and trying the whole process again in case some error occurred only to have the same result. Any suggestions?

**Comment by openaudible** [comment]
Maybe try using CBR as the mp3 format. You'll need to delete the existing mp3 and split by chapter folder.. then set preferences to Output Format: MP3 (CBR) -- then re-encode, then split, then try again.
Searching Yoto in the issues may show others with similar issues.

**Comment by openaudible** [comment]
Good luck. If someone wanted to make a guide on using their Yoto with OpenAudible, that would be great. Doesn’t sound like an ideal player but maybe for short chapters it could work.
