### ISSUE TITLE
Update OpenAudible_3.7.4_x86_64.exe Windows 10 error

### ISSUE THREAD

**Issue by wegomeier** [openaudible/openaudible#1195]
OpenAudible_3.7.4_x86_64.exe starts, then disappears, and program is not installed/running.
I tried to install the update after deinstalling the 3.6 version.
no success.

what can i do?

**Comment by openaudible** [comment]
Strange. Here are things to try. 
Check your anti virus program. 
run open audible from the command line using the debug_win.bat script inside the application directory. Let us know the error. 
copy and move or delete the configuration json files. Maybe one is corrupt and preventing start.

**Comment by wegomeier** [comment]
Thank you!
Problem dissolved with you description.
1) Disabling Kaspersky Internet Security during installation
2) Deleting the json files after installation to heal the login problem
