### ISSUE TITLE
Importing Books - Metadata Info Population

### ISSUE THREAD

**Issue by 777black777** [openaudible/openaudible#1198]
The information pulled down for Audible books is awesome. I love being able to sort by "Narrated By" or read the summary of my Audiobooks. However, when importing books from other sources, the information population leaves a lot to be desired.

It would be great if some type of search function could be implemented. For example, if the Title and Author or the Book URL from Audible are added, it would be great if there was a button to retrieve the rest of the book information from Audible.

I am not sure where the book information is pulled from when doing an Audible sync. Maybe the book info is contained within the AAX files in which case a search function might be difficult to implement. However, if Audible has an API or web scraping is used, I am hoping the search function could be easily implemented.

Another option is for an "Import Book Info" function could be done where a template file (JSON/XML/CSV) is provided that allows someone to manually or programmatically fill in the details. OpenAudible could ingest that file. If a single book section from books.json was turned into a template file and then an "Import Book Info" menu code was added that might work.

I know this application has a focus on Audible, but it is so great that outside Audiobooks can be brought into OpenAudible and I would love to see a simple method for making outside book information as informative and useful as books pulled down from Audible.

Keep up the great work!

**Comment by openaudible** [comment]
Thanks. You can edit the meta data by selecting a book and Menu Action> Get Info...
But manually editing is a chore. We do recommend buying the books from Audible, of course.
That said... we could scrape the information if you provide an Audible Product ID (ASIN). So will mark as a feature request and give it a look.

**Comment by 777black777** [comment]
I just did a search for a book on Audible and this was the prefix of the URL:
https://www.audible.com/pd/The-Ballad-of-Songbirds-and-Snakes-Audiobook/1338635204
I then tried using:
https://www.audible.com/pd/1338635204
and I ended up at the same page.

Would I be correct in assuming the 1338635204 is the ASIN? If it is, I would love to be able to use that identifier and then have the book info auto populated.

All my future audiobooks will be Audible, but a few are MP3 rips from purchased CD audiobooks that I'd love to have fully documented in one application (OpenAudible) showing my notes and read status.

**Comment by openaudible** [comment]
Yeah. That is the asin. 
Will work on that. No promises but should be doable.

**Comment by openaudible** [comment]
Ok. First iteration done in beta: https://openaudible.org/beta
Go to Get Info.. and click the "Auto Fill" button at the bottom (after filling in the ASIN.)

**Comment by 777black777** [comment]
> Ok. First iteration done in beta: https://openaudible.org/beta Go to Get Info.. and click the "Auto Fill" button at the bottom (after filling in the ASIN.)

Never and I mean never has a developer been so responsive and then actually coded a feature request so quickly. The AUTO FILL feature worked gang busters and was exactly what I was envisioning. Major props to you! Thank you!
