### ISSUE TITLE
Documentation Question on Syncing / Losing Books

### ISSUE THREAD

**Issue by pheriwinkle** [openaudible/openaudible#1199]
I have a question whose answer I couldn't find in the documentation.  When keeping a large library in sync, if Audible removes a book from my library for whatever reason, will OpenAudible delete it from my local storage?  Or, are we guaranteed that anything that has been downloaded in the past will stay in our libraries without having to make a backup copy of things elsewhere?
I have had a few books disappear from my Kindle library on Amazon because of contractual/copyright changes, so I figure the same thing will happen with Audiobooks over time too.
Thank you.

**Comment by openaudible** [comment]
Once a book is downloaded and converted it is safely backed up. We won’t delete anything. But if it hasn’t been downloaded or converted and it gets deleted by audible it may show up as a red dot 🔴 and be unavailable.
