### ISSUE TITLE
Book always downloading AAXC

### ISSUE THREAD

**Issue by TimCinel** [openaudible/openaudible#1200]
I have a book that always downloads an `aaxc` format file (though, OpenAudible names it `<title>.AAX`)
Have tried the following:

* Different versions (`3.7.4` and `3.7.3.3_beta`)
* Delete, Log Out, Quit, Log Back In, Download.

Every time, it downloads an `aaxc` file:

```
$ ffprobe downloaded.AAX
ffprobe version 5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
  ...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fd6eba04100] [aaxc] audible_key value needs to be 16 bytes!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fd6eba04100] stream 0, timescale not set
[aac @ 0x7fd6ea7050c0] ms_present = 3 is reserved.
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'downloaded.AAX':
  Metadata:
    major_brand     : aaxc
    minor_version   : 1
    compatible_brands: aaxcM4B mp42isom
    creation_time   : 2019-06-03T02:35:19.000000Z
    genre           : Audiobook
    title           : ... 
    artist          : ... 
    album_artist    : ... 
    album           : ... 
    comment         : ... 
    copyright       : ... 
    date            : ... 
....
  Chapters:
    Chapter #0:0: start 0.000000, end ...
      Metadata:
        title           : Opening Credits
    ...
```

My previous downloads were all `aax`, e.g:

```
$ ffprobe older-download.AAX
ffprobe version 5.1.2 Copyright (c) 2007-2022 the FFmpeg developers
...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fdfc0104100] [aax] file checksum == ...
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fdfc0104100] [aax] activation_bytes option is missing!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fdfc0104100] stream 0, timescale not set
[aac @ 0x7fdfc0104f00] Number of bands (16) exceeds limit (14).
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'older-download.AAX':
  Metadata:
    major_brand     : aax
    minor_version   : 1
    compatible_brands: aax M4B mp42isom
    creation_time   : ...
    comment         : ...
    title           : ...
    artist          : ...
    album_artist    : ...
    album           : ...
    genre           : ...
    copyright       : ...
    date            : ...
...
  Chapters:
    Chapter #0:0: start 0.000000, end ...
      ...
```

I've seen other issues with similar problem, where retrying seems to have worked, but after many retries (10+) I cannot get a different result. Always `aaxc`.

**Comment by openaudible** [comment]
AAXC is fine if you download and convert it with the latest version of OpenAudible.

**Comment by TimCinel** [comment]
Ok, thanks for that. I didn't know that was expected, hence this issue.

Would you consider changing the behaviour so that the extension reflects the underlying file format?

**Comment by blurfl** [comment]
This may be related to an issue I've been battling for a while.
I've found that the Apple Books app will not play the .AAX files downloaded using the recent versions of OpenAudible. This is a recent change, maybe in the last six months. 
The Books app responds to an OA download with: `To play this audiobook, you’ll need to authorize this computer for your Audible account.` but then Audible then fails to authorize. The download of the same book using other browsers (not OA) works with Books, and those files show in ffprobe as `major_brand     : aax`. 
Was there a change to OA that could be causing this?

**Comment by openaudible** [comment]
Oh. Convert to m4b and select Action> Play and it should open in your books.app just fine.

**Comment by blurfl** [comment]
I understand about converting. I prefer to play the .aax files and keep the mp4 files as backup. A shame to download the .aax file and then trash it. Can you implement a preference for using the previous download format? Why the change, anyway?

**Comment by openaudible** [comment]
Seems like Audible is migrating away from aax to the more secure aaxc. So we recommend using m4b as the default output.

There is a setting to delete the AAX/AAXC and only keep the M4B.. The M4B is nearly identical to the original-- no loss in quality.
