### ISSUE TITLE
OpenAudible thinks I've connected but I have not

### ISSUE THREAD

**Issue by gingergu** [openaudible/openaudible#1201]
After logging in with Audible login I get a box titled "SUCCESS" and inside the box says "Skipping the Registration... for testing/read only"
It is not connected and I can most certainly login to Audible on the same browser or other browsers.

**Comment by openaudible** [comment]
What version are you using? That looks like debug code that isn't supposed to happen unless you somehow got your library into "read only mode" (which shoudn't be possible with the release version.) Make sure you're using the latest version.. and I'll add some more logging to see which of the two possible causes are causing the problem.

**Comment by openaudible** [comment]
You can try the latest beta... if it still doing the same thing, please send a bug report.
https://openaudible.org/beta

**Comment by openaudible** [comment]
Reopen or comment more if this happens again with the latest versions.

**Comment by gingergu** [comment]
I just downloaded it yesterday from your site.
