### ISSUE TITLE
Random non compliant files

### ISSUE THREAD

**Issue by nige101uk** [openaudible/openaudible#1202]
Hopefully no one has flagged this before but after I've converted to MP3 and try to split by chapter the output creates random 7kb files. For example after "chapter 7.mp3" there is a "chapter 7 (continued).mp3". it's not a valid MP3 file with or without the parenthesis. I've also checked the end of the preceding file and there's no cut off on the audio so I have no Idea what they're for or how they got there 
![Screenshot 2023-04-23 at 14 59 10](https://user-images.githubusercontent.com/46816754/233844410-04b40b6d-9a96-467a-8293-28122ca33212.png)
Added a screenshot so you can see most of the filelist with the issue.
Currently using OpenAudible 3.7.5 Mac OS Catalina 10.15.7

**Comment by openaudible** [comment]
That's definitely a bug. When the chapter data from audible is corrupt, the chapters are not contiguous and there are gaps (or overlaps) in them. So we either extend chapters or create one to fill in a gap. Looks like something is broken.. We print detailed logs about what we are planning to do, but a bug report might be the best thing for us to fix it. Delete the split book, quit and restart (optional, to clear the logs) then split the book.. and if it has the continued, send a bug report from the About menu. We would be happy to fix this.

**Comment by nige101uk** [comment]
Bug report sent as requested. As an update, I was able to create a clean folder of chapters by selecting the title in the bottom window, right clicking and selecting 'split selected books'. I'm sure it'll make sense to you but it's just weird to me.

**Comment by openaudible** [comment]
We just posted a beta with additional debugging and a bug fix to not add missing chapters that are very short in duration.
https://openaudible.org/beta
Thank you for the report!

**Comment by openaudible** [comment]
Fixed in 3.7.6. Reopen or comment if you notice anything not working. Thank you for the feedback!
