### ISSUE TITLE
[x-posting from openaudible_docker] OA is causing my whole network stack to crash. 

### ISSUE THREAD

**Issue by anthonysnyder** [openaudible/openaudible#1203]
_Note: Sorry for cross posting, but wanted to make sure no one needed anything from my current config before wiping it to start over._ 

**TLDR: The version[1] of OpenAudible in Docker that I am(was) running caused my entire network stack to fail by trying to upload 900+Mbps . Details below.**

I am not even sure where to begin with this, so I will try my best.

The other day, I woke up to my Ubiquiti Dream Machine Pro reporting High Ping and Packet Loss.

Everything on Wi-Fi was not working. I did some basic troubleshooting, rebooting the modem, hard wiring directly into the modem, etc. No dice. So I drove to Best Buy and got a new modem. Issue persisted after new modem was activated.

Called Spectrum Internet and got them to send a tech out as well as to overnight me a new modem since I knew they would not troubleshoot a 3rd party one. Tech comes out and determines that the Coax coming into my house was "extremely noisy" (?) and would need to be replaced. So they replaced the cable coming into my office. (Note: At this point, everything in my network stack was turned off and disconnected) After powering back on the Spectrum modem, the internet is working and consistently stable while hardwired into my Mac. Tech leaves.

I then power my Dream Machine Pro back on and connect it back to the modem. The Wi-Fi comes back online. Everything seems to be working. I am pinging google.com on multiple machines in order to observe any drop outs. As soon as I plug the Synology back into my UDM, I start to see Wi-Fi issues almost immediately.

In order to troubleshoot as best as I can, I hardwire into the Synology and kill all programs and Docker containers. Wi-FI comes back up and is stable. So one by one, I turn on all the natIve apps, no issue appears. So I go to Portainer and start turning on Containers, get to OpenAudible, turn it on and bam Wi-Fi goes down. Upon killing the OpenAudible container, things stabilize again.

I was going to wipe the container, but figured I should open an issue first. Please ask if you need me to provide additional details.

Footnotes:
[1] Linuxserver.io version:- 33054d6a-ls46 Build-date:- 2022-03-06T14:59:19+01:00

[2] Link to video of observations here: https://drive.google.com/file/d/1RNJ9gLcum7gqkFOd5Oh5AzNqUSn1t0G9/view?usp=sharing

**Comment by openaudible** [comment]
Closing -- active on openaudible_docker issues.
