### ISSUE TITLE
Book collections don't split into chapters

### ISSUE THREAD

**Issue by herriga** [openaudible/openaudible#1204]
When splitting the chapters of a collection of books within one audible file, it splits each book into its own file instead of splitting individual chapters. The way it is now, I can't stop listening on a specific chapter and easily restart when I come back to my book. This is a new issue from an old OA version on my older computer.

**Comment by openaudible** [comment]
Split by chapter is not automatic at this time. To split a book by chapter (which we don't recommend) select a book in the Openaudible table and Action > Split Selected books. To split a book not in your library, use File: Split Books.

**Comment by openaudible** [comment]
See https://openaudible.org/docs#split_by_chapter
