### ISSUE TITLE
unlimited account license - possible?

### ISSUE THREAD

**Issue by Strider3000** [openaudible/openaudible#1205]
Hello, longtime user and buyer here.
For a while my mode of populating my personal audible library was to utilize eBay audible account purchases which entailed using probably 50-60 accounts for various audiobooks. 
I noticed in a recent update that openaudible will now only support files from up to 10 separate accounts, leaving the majority of my library unaccounted for with openaudible.
Is there a way to purchase an "unlimited" license for openaudible to get it to function how it used to function before the recent account-file-association license change? Thanks

**Comment by openaudible** [comment]
Unfortunately, we don't allow unlimited accounts. Our license allows up to 5 accounts, with a hard limit of 10. Sorry for the inconvenience.
