### ISSUE TITLE
Error downloading: http error getting: licenserequest reason:Bad Request 

### ISSUE THREAD

**Issue by prasannag** [openaudible/openaudible#1208]
Hi, I'm receiving the following error when trying to download a book. 

Error downloading: http error getting: https:|/api.audible.com/1.0/content/B0060NRXBO/licenserequest reason:Bad Request

**Comment by openaudible** [comment]
Here are some troubleshooting tips from the documentation [troubleshooting guide:](https://openaudible.org/docs#download_errors) 
- Some books become unavailable. Check that the audiobook is available in the Audible mobile app and/or Audible web page and can be played.
- You are logged into the wrong account. If you have multiple accounts, you need to be connected to it before a download will work.
- Rate limit exceeded. Try disabling automatic downloads and waiting a little before trying again.
- Upgrade to the latest version. Some issues have been addressed in later versions of OpenAudible.
