### ISSUE TITLE
feature request: Title in splitted File

### ISSUE THREAD

**Issue by Zerberus8** [openaudible/openaudible#1209]
If you split a MP3 File could you please write the (long) title of the original MP3-File into the Subtitle-Property of the generated/splitted MP3 files? 
[Example](https://imgur.com/a/FIEUa2t)

**Comment by openaudible** [comment]
Will check it out.

**Comment by openaudible** [comment]
Looks like the subtitle used by windows is the TIT3 meta data tag. The Album tag already contains the name of the book. Some sites suggest it could be used to say Unabridged or something related to the title. Not sure that duplicating the book title makes sense. But open to a discussion.

**Comment by openaudible** [comment]
Fixed in 3.7.6. Reopen or comment if you notice anything not working. Thank you for the feedback!
