### ISSUE TITLE
WARNING: Unable to import Book too new for version

### ISSUE THREAD

**Issue by FromerDev** [openaudible/openaudible#121]
Using version 1.4.9

Hi. 

One of my books has worked but but the rest all fail with the message "WARNING: Unable to import Book <title> too new for version"

Thanks.

**Comment by openaudible** [comment]
After you get that error, you can send a bug report from the Help menu. 
What region, what book (audible URL)? Is the "Date Published" and "Date Purchased" correct on the audible page? We skip books if the date is incorrect to avoid creating bad data...

**Comment by thowan** [comment]
I do not even get an error. I simply cannot import a book that just came out a few days ago. Not sure if other books work.

**Comment by openaudible** [comment]
Check that you see a download link for the book in the OpenAudible viewer when logged in and viewing the audible web page for the book in question. Rescanning your library may help. And deleting and re-importing books might also help. Try the new version as well.

**Comment by Porske** [comment]
I get the same error, this is the console output

`INFORMAZIONI: Command: Console
set 05, 2019 6:32:58 PM org.openaudible.desktop.swt.manager.views.FileDropTarget drop
INFORMAZIONI: drop file:/Archivio/Libri/Audible/<book>.aax exists=true
set 05, 2019 6:32:58 PM org.openaudible.util.SimpleProcess <init>
INFORMAZIONI: Running: /home/porske/OpenAudible/bin/linux/ffmpeg -i "/Archivio/Libri/Audible/<book>.aax" -f ffmetadata - 
set 05, 2019 6:32:58 PM org.openaudible.Audible expired
AVVERTENZA: book contains invalid date: <title> date=2200-01-01 product_id=BK_ASIT_001541i,asin=B07RFTR1DS,title=<title>,author=<autor>,narrated_by=<narrated_by>,summary=<summary> "<title>", <description>,duration=11:45:30,release_date=01-JAN-2200,publisher=Pottermore Publishing,title_short=<title>,copyright=<copyright>,filename=<book>,
set 05, 2019 6:32:58 PM org.openaudible.desktop.swt.manager.ImportExport _importFile
AVVERTENZA: Unable to import book:/Archivio/Libri/Audible/<book>.aax : Book too new for version <title>
set 05, 2019 6:33:03 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFORMAZIONI: versionCheck: https://openaudible.org/swt_version.json`

There is some way to ignore wrong date?
