### ISSUE TITLE
Missing sub chapters?

### ISSUE THREAD

**Issue by Bitwolfies** [openaudible/openaudible#1210]
When converting a book, sub chapters appear to go missing, using God of War as an example, there's chapters, and sub chapters. 
![image](https://github.com/openaudible/openaudible/assets/65789901/0aff6b78-9356-43e2-9ea3-2d9ccb0bbf89)
These chapters go missing after converting to m4b. (The same chapter names appearing over and over again is fine, book is just like that)
![Screenshot_20230511_204548](https://github.com/openaudible/openaudible/assets/65789901/3ac85376-1b58-449a-ac26-46eb1912a3d0)

**Comment by openaudible** [comment]
This may or should be fixed in the latest beta. Please give it a try. OpenAudible.org/beta

**Comment by openaudible** [comment]
OK. We updated the code to decide which chapters to use. We should be more aggressive about using the named chapter. 
However, some books may just have corrupt data. Give 3.7.6 a try.. We do include a lot more diagnostic data about which chapters we are using -- it may be that both sets of chapter data is wrong.. or maybe we are choosing poorly still.

**Comment by joergister** [comment]
Just a wild guess, but in context of converting AAXC files to m4b and using chapters from a json file for this, i encountered the problem of not having a correctly formated json file. The python code below fixed it.


```
import sys
import json

def flatten_chapters(y):
out = []

def flatten(x, level=0):

    for a in x:
        if 'chapters' in a:
            sub_chapters = a["chapters"] 
            del a["chapters"]
            if level>0:
                a["title"] = '*' * level + ' ' + a["title"]
            out.append(a)
            flatten(sub_chapters, level+1)

        else:
            if level>0:
                a["title"] = '*' * level + ' ' + a["title"]
            out.append(a)
        
flatten(y)
return out


if len(sys.argv) != 2:
print("usage: python flatten_chapters.py filename")
sys.exit(2)

data = json.load(open(sys.argv[1]));

data["content_metadata"]["chapter_info"]["chapters"] = flatten_chapters(data["content_metadata"]["chapter_info"]["chapters"])

print(json.dumps(data, indent=4, sort_keys=False));
```

**Comment by openaudible** [comment]
Please give 3.8.1 a try. You will probably need to re-encode the m4b/mp3 file(s) that have this problem. 
The API (which usually gives better results) seems to be returning only the book parts.. Will be investigating more, but 3.8.1 should be an improvement. Feel free to re-open or comment more if anything comes up.

**Comment by tischler57** [comment]
3.8.1 solved my problem, thank you.
