### ISSUE TITLE
"Split Selected Books" freezes on several books in my collection.

### ISSUE THREAD

**Issue by smccandl** [openaudible/openaudible#1211]
I have over 750 books in my collection. I was trying to "Split" all the books for better compatibility with Plex and several of the books "freeze" during the convert process. I have submitted a "bug report" with this issue number. I would be happy to provide any additional files or info if it will help! Thanks for a GREAT program! Been using it for years!

**Comment by openaudible** [comment]
Great bug report. Turns out we got confused by a couple of things including chapters with duplicate chapter names. 

Fixed in the latest beta. 
https://openaudible.org/beta

**Comment by openaudible** [comment]
Fixed in 3.7.6
