### ISSUE TITLE
Download failed, bad response: HTTP/1.1 204 No Content

### ISSUE THREAD

**Issue by GarethBlain** [openaudible/openaudible#1212]
I've just re-installed version 3.02 (I've only just gotten a new Mac so haven't used it in a year) and I can't download any books as I get "Download failed, bad response: HTTP/1.1 204 No Content"

It could be a duplicate of [issue 1151](https://github.com/openaudible/openaudible/issues/1151) but I couldn't fix it by installing the latest beta (which DID download by the way) and then going back to the old version. I've tried deleting the app and re-installing but that also didn't fix the error.
I tried downloading all my books encase it was just a few but they all failed one by one. :(

**Comment by openaudible** [comment]
3.0.2 is very out of date and we don't test old versions to see if they are working. So something may have changed. But haven't heard a flood of complaints, so 3.0.2 should still be ok. 

Did you log out and log back in from the Controls menu and do a full library rescan? 

You could look at the log and see if there is more information. 

For now, turn off automatic downloads and try downloading purchased books one at a time..
