### ISSUE TITLE
How to tell which AAX files are from different audible accounts?

### ISSUE THREAD

**Issue by Strider3000** [openaudible/openaudible#1213]
What's the simplest method to check if two AAX files came from the same or different audible accounts?

More recent versions of OpenAudible complain when using AAX files from more than 10 different accounts.
How do I tell which AAX files are from different accounts?
I'd like to partition my collection of AAX files (over 400) to set aside the ones from unique accounts but I'm unsure the proper method to do so (to get OpenAudible to stop complaining at me).

**Comment by openaudible** [comment]
I don't think its possible from OpenAudible. Sorry. To check, you would need to run ffmpeg on the .aax file and look for the unique checksum for each account. Sorry!
