### ISSUE TITLE
Not scraping imported books

### ISSUE THREAD

**Issue by IMDBLM** [openaudible/openaudible#1214]
I have some audio books I want to import that don't sync through my library. When I import the book, OA pulls some of the information (like the Audible webpage it's linked to) but it doesn't scrape any of the proper information.

**Comment by openaudible** [comment]
We added a new feature where if you select a book, go to Get Info.. then click on the "Auto-Fill" button. It will use the ASIN or audible web page) and fill in the missing data (minus chapter names.)

**Comment by IMDBLM** [comment]
Thanks! I didn't even think to click that button.
