### ISSUE TITLE
System Crashing Ubuntu 22.04 with OA version 3.7.5

### ISSUE THREAD

**Issue by djmccullers** [openaudible/openaudible#1215]
I recently installed OA 3.7.5 and purchased a license. After that, my system started crashing on a regular basis. I tracked it to OA. When it's started, if it has the "Auto Convert" flag set it kicks off three instances of ffmpeg to do the conversions. These quickly exhaust memory and swap space. Trying to prevent this doesn't work as when OA is stopped the ffmpeg instances keep running!

I believe that the problem is due, in part, to the fact that the files that are downloaded from Audible are aaxc files, which the website (https://openaudible.org/) indicates that it doesn't support. Note that while the files downloaded have a .AAX extension, they are, in fact, aaxc files. Here's the partial result of ffprobe of one of the files that OA downloaded:

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Without Remorse.AAX':
  Metadata:
    major_brand     : aaxc
    minor_version   : 1
    compatible_brands: aaxcM4B mp42isom
    creation_time   : 2022-07-12T18:32:27.000000Z
    genre           : Audiobook
    title           : Without Remorse (Unabridged)
    artist          : Tom Clancy
    album_artist    : Tom Clancy
    album           : Without Remorse (Unabridged)

I configured OA to not auto convert the files and did it manually while timing the conversion. It took 30 minutes for the conversion. The running time for the file is just over 27 hours.

I downloaded the same file from my library onto my Android phone and moved it over to my computer and did ffprobe on it. Here's the same portion of that:

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'B004FG2QGQ_ep5.aaxc':
  Metadata:
    major_brand     : aaxc
    minor_version   : 1
    compatible_brands: aaxcM4B mp42isom
    creation_time   : 2022-07-12T18:32:26.000000Z
    genre           : Audiobook
    title           : Without Remorse (Unabridged)
    artist          : Tom Clancy
    album_artist    : Tom Clancy
    album           : Without Remorse (Unabridged)
    comment         : Now a major motion picture starring Michael B. Jordan - watch

I also downloaded the same file onto my computer manually from my Audible library and did the ffprobe on it. Here's the matching section from that.

Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'WithoutRemorse_ep6.aax':
  Metadata:
    major_brand     : aax 
    minor_version   : 1
    compatible_brands: aax M4B mp42isom
    creation_time   : 2023-05-18T21:22:25.000000Z
    genre           : Audiobook
    title           : Without Remorse
    artist          : Tom Clancy
    album_artist    : Tom Clancy
    album           : Without Remorse (Unabridged)
I manually used ffmpeg to convert this file and it only took 11 minutes! Also it was MUCH kinder on memory usage!

I'm not skilled enough to locate what needs to be changed to REALLY download an aax file instead of an aaxc file, but I suspect that 
if that were done, my problem would go away. Or if it didn't kick off three instances of ffmpeg to do the conversion that might work too. Best would be to do both.

Don

**Comment by openaudible** [comment]
Sounds like you are a little low on memory.. but crashes should still not happen-- happy to look at the log file or try to find more details about what is crashing. 

To convert one file at a time, you'll need to edit a config file. (We try to keep the UI simple):
Go to OA settings, click on the "Folder" on the upper right hand side next the the Preferences directory. 
Locate the settings.json file. Edit it carefully with a text editor. 
Find the line that says concurrentConversions and change the 3 to a 1. 

```
  "concurrentConversions": 1,
```

Then relaunch OpenAudible.

AAXC files are supported.. but only if downloaded using OpenAudible with your current account connected. (Its possible we need to update our documentation.) 

Conversion to m4b is quick and lossless.. mp3 can take a lot longer and use more memory. (Change from mp3 or m4b in the settings.) 

Keeping auto-convert off for a while is a good idea.. but hopefully that will resolve the problem you're seeing.

If you're using a VM, consider upping the ram.. if you're on bare hardware, let us know how much ram you have available -- maybe we can do a check and see if you're on a low-ram system (and perhaps we can automatically lower the concurrent conversions.)

**Comment by djmccullers** [comment]
I have 8GB of memory.
I've attached a ZIP file of the results of using the "Diagnostics" option.
The first one I did a copy and paste of the .HTML file into a .txt file.
The rest are the actual HTML files.
I made a mistake and, AFTER I changed the "concurrentConversions" value I
reopened Settings and saved it. That reset my change back to 3. :-(

I also quit OA and restarted it. This left the single "ffmpeg" process
running and added another one. I don't know if it's possible to get the PID
of the process when you
kick off ffmpeg or not, but, if it is, you might want to keep track of it.
When quitting, ask if they want to stop those processes or not. If they say
"Yes" go ahead and kill them if they don't,
hold onto the info and check, next time OA starts, for that PID and any
other info to verify that OA created them and take that into account for
the "concurrentConversions"
values. Also, I'm not convinced that the memory used by the ffmpeg
processes is taken into consideration on the memory count.

Another thing, while I have your attention, how come using ffmpeg on the
AAXC files going to MP3 is so much slower than me doing it manually from
AAC files to MP3 files?
And....I thought that the M4B files were supposed to be smaller than MP3
files. Looks like they're much bigger! I'll have to stick with MP3.

Let me know if there's anything else you need from me.

Don McCullers
781 361 9872

**Comment by openaudible** [comment]
We do keep track of running processes and attempt to kill them when quitting.. really should be impossible to quit openaudible (or crash it) and have the child ffmpeg process still remain.. but maybe ffmpeg is hanging? 

The zip file didn't go through.. but maybe just copy and paste the memory if you get a change.. 8gb sounds like it should be enough unless the system is already nearly out of memory. Might be a good idea to look at all of your processes memory usage -- htop is a good choice. And "free -m" or even "top" is also a quick way to get a glimpse of memory.

MP3 is lossy and can create larger or smaller files depending on the compression. The time to run the exact command should be the same whether it is going through OA or the terminal. But to be honest, haven't tested it in a while. Usually "best quality" is preferable to "smaller disk usage".. but it is fine either way-- sometimes you just leave the app running overnight and wake up to all files converted.

**Comment by djmccullers** [comment]
I've no idea why it didn't go through, it's not all that big!  I've put it
on Google Drive here
<https://drive.google.com/file/d/1K673T9RoY_qXWKbynwCqeogZKUvB0pby/view?usp=share_link>.
Let me know if you have any issues getting it.

About the ffmpeg processes staying around after OA exits....I don't know
what to say!  They're staying and doing their thing. If I don't kill them,
they finish processing just fine!

Regarding the time for ffmpeg to process the file, the command I'm using is:
ffmpeg -activation_bytes <myKey> -i  <InFile>.aax -vn -c:a libmp3lame
<OutFile>.mp3

That works fine for me and, as you can see from my entry on GitHub, it's
MUCH faster than what OA's doing. I understand about lossless and, if my
ears were better, or it was
music (AND my ears were better), it might make a difference, but with audio
books, I'm fine with the size vs. quality tradeoff.

I did an ffmpeg -v on my system and got the following:

ffmpeg version 4.4.2-0ubuntu0.22.04.1 Copyright (c) 2000-2021 the FFmpeg
developers
  built with gcc 11 (Ubuntu 11.2.0-19ubuntu1)
  configuration: --prefix=/usr --extra-version=0ubuntu0.22.04.1
--toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu
--incdir=/usr/include/x86_64-linux-gnu --arch=amd64 --enable-gpl
--disable-stripping --enable-gnutls --enable-ladspa --enable-libaom
--enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca
--enable-libcdio --enable-libcodec2 --enable-libdav1d --enable-libflite
--enable-libfontconfig --enable-libfreetype --enable-libfribidi
--enable-libgme --enable-libgsm --enable-libjack --enable-libmp3lame
--enable-libmysofa --enable-libopenjpeg --enable-libopenmpt
--enable-libopus --enable-libpulse --enable-librabbitmq
--enable-librubberband --enable-libshine --enable-libsnappy
--enable-libsoxr --enable-libspeex --enable-libsrt --enable-libssh
--enable-libtheora --enable-libtwolame --enable-libvidstab
--enable-libvorbis --enable-libvpx --enable-libwebp --enable-libx265
--enable-libxml2 --enable-libxvid --enable-libzimg --enable-libzmq
--enable-libzvbi --enable-lv2 --enable-omx --enable-openal --enable-opencl
--enable-opengl --enable-sdl2 --enable-pocketsphinx --enable-librsvg
--enable-libmfx --enable-libdc1394 --enable-libdrm --enable-libiec61883
--enable-chromaprint --enable-frei0r --enable-libx264 --enable-shared
  libavutil      56. 70.100 / 56. 70.100
  libavcodec     58.134.100 / 58.134.100
  libavformat    58. 76.100 / 58. 76.100
  libavdevice    58. 13.100 / 58. 13.100
  libavfilter     7.110.100 /  7.110.100
  libswscale      5.  9.100 /  5.  9.100
  libswresample   3.  9.100 /  3.  9.100
  libpostproc    55.  9.100 / 55.  9.100


Don't know if that's any help or not. Let me know what more I can do.


Don McCullers
781 361 9872

**Comment by openaudible** [comment]
Memory of OpenAudible looks fine-- using less than 1% of the 1GB. 
Glad to hear the conversions do complete.. You can click on a converting book and it will show the progress in the Book Info status panel.
We include a copy of ffmpeg (LGPL) that should be just as quick as your installed version. You can try to compare the speed. We do convert to a /tmp directory, then copy the completed file to the final destination.. so if your disk is on a network drive, that can cause a slowdown. 
I do see you're using a -a:c argument, which is just copying the audio data if possible.. so some aax files are actually mp3 files, so in those rare cases, that command would be faster.. but usually, you need to specify the bitrate and format (constant rate or vbr). 

You mentioned a crash earlier-- but we never determined how it showed up.. system became sluggish, locked up, output a crash log and quit, etc.. 
The only thing I can think is you could try converting 3 files at once using your or our ffmpeg... and see if your system dies. You can start a background task by adding the & at the end of the ffmpeg command, and just use test1.mp3, test2.mp3, etc for the output names.
