### ISSUE TITLE
Download directory changed

### ISSUE THREAD

**Issue by Markovius** [openaudible/openaudible#1216]
My download directory randomly changed to another disk, where it created a new directory and redownloaded all my books. I've checked "manage libraries" and it still shows the correct directory.

Not sure what to do next.

**Comment by openaudible** [comment]
The about menu Diagnostics will show current library locations. They are also printed to the console when the app starts. Was it a network drive or possibly offline for a bit? Not sure what would cause that.

**Comment by Markovius** [comment]
It's Windows. It changed all my drive names. Not sure why it did that, but I'm fixed now. Thanks for the reply.
