### ISSUE TITLE
Not all converted MP3 Files working

### ISSUE THREAD

**Issue by rburke16** [openaudible/openaudible#1217]
I'm converting the audiobooks to mp3s to upload to my son's Yoto player. The upload on some of the audio files are not uploading bc it says it's not in the right format even tho I converted to mp3. Some are uploading but will not play correctly. I know this is not a yoto issue since I'm able to upload other mp3 audio files from other sources just fine. It's only happened thru the open audible files.

**Comment by openaudible** [comment]
Search the issues for yoto. Unfortunately they can’t handle large files. So you need to split the audiobook by chapter.

**Comment by rburke16** [comment]
How can I split chapters??

**Comment by openaudible** [comment]
https://openaudible.org/docs#split_by_chapter

**Comment by rburke16** [comment]
It does not give me the option to do that.

**Comment by openaudible** [comment]
Select a converted (green) book. Right-click, Split Selected Book. If the book has chapters, it will be split into one file per chapter and saved in your "books" directory as a folder with the title of the book.

**Comment by rburke16** [comment]
It keeps trying to convert the same books, that one highlighted has been
converted before but won’t show the green dot when I re open the app.
