### ISSUE TITLE
Login Issues

### ISSUE THREAD

**Issue by SJGit2020** [openaudible/openaudible#1218]
Good afternoon,

I have recently encountered an error when trying to sync my audible library; 'Error Refreshing Library'. Please see the attached screenshot of the error. 

I have tried logging out and back in several times, as suggested by the troubleshooting guide. I have double-checked the region, typos etc., but have still been unsuccessful. 

I have tried both 'Secure web browser login' and 'Secure OpenAudible login', both give the same error. 

Please can you let me know how to fix this login issue?

![image](https://github.com/openaudible/openaudible/assets/60219465/877299e5-bfc0-42f3-9d25-00e9bb9d12c8)

**Comment by SJGit2020** [comment]
Please can you provide an update? I am trying to sync new items from my library, but the error above is stopping me doing so. Thank you,

**Comment by jmartindf** [comment]
I'm seeing the issue as well. The Audible website appears to be throwing internal server errors, when OpenAudible tries to refresh the library.

**Comment by SJGit2020** [comment]
Update please?

**Comment by nabbes79** [comment]
I'm having the same issue with an older version.
I was planning to update.
I will not unless I'm sure open audible will actually work for me, or I'm sure I can get a refund if it doesn't work.
So, please keep us posted!
@openaudible 

Thank you.

**Comment by SJGit2020** [comment]
@openaudible  I am still having this issue, despite upgrading to 3.7.6.1 today. Please can you look into this issue so I can access my books.

**Comment by nabbes79** [comment]
Thanks for the info @SJGit2020 !
And thanks for trying.

**Comment by nabbes79** [comment]
Update:
I just tried it again, and it suddenly works for me again.
For now at least.

**Comment by openaudible** [comment]
Try upgrading.. 

Try logging in with a web browser.. and if already logged in, log out, then back in.. and make sure the password is correct. Sometimes Audible just gets a little picky with new attempts to log in. 
If one method of the OpenAudible login doesn't work, try the other (Web based or Application-based).

We did add more to the documentation: https://openaudible.org/docs#login_errors

**Comment by SJGit2020** [comment]
Good morning,

Please can you reopen this case, since it is not yet solved - I still cannot get access to my books. 

I am not sure why you suggest upgrading - I am on v3.7.6.1, and Check for update says there are no further updates available. I have a full license until April next year. 

I have tried logging in using both 'Secure web browser login' and 'Secure OpenAudible login', both give the same error (as mentioned in my first post). 

The documentation you link to is the same as when I first raised the issue, and I have checked all of those steps. When logging in, it appears successful, but then the error happens when I try the prompted library sync. 

@openaudible  please help. 

![image](https://github.com/openaudible/openaudible/assets/60219465/6e0b7217-431c-46ff-a901-2d99850589f5)

**Comment by SJGit2020** [comment]
Upgraded to v3.8, everything back to normal and working brilliantly again. Thank you :)

**Comment by openaudible** [comment]
Thank you for the bug report. The problem was a bug on our end when something unexpected happened parsing a non audible book. Thanks again!
