### ISSUE TITLE
Filename of splited books with zeros

### ISSUE THREAD

**Issue by christianmerges** [openaudible/openaudible#1219]
Hello can we gat (at least as optional setting) the ability to split the books like
001, 002, 003, ..., 124... instead of 1,2,3,12,124. Because in some applications the order get's mixed up.

**Comment by openaudible** [comment]
I think that was a bug that crept in.. not supposed to happen. We did verify that it has been fixed (as far as we know) in the beta:
https://openaudible.org/beta ... Let us know if you find an example that doesn't work and let me know the version and a copy and paste of the split log from the File > Console menu.

**Comment by openaudible** [comment]
Fixed in 3.7.6. Reopen or comment if you notice anything not working.

**Comment by christianmerges** [comment]
Hi, it was working in the mentioned beta. But in the latest beta where u added the feature with the language in the table, the naming of splitet books is now back to legacy. Please check.
