### ISSUE TITLE
Error trying to connvert to mp3

### ISSUE THREAD

**Issue by Redforte** [openaudible/openaudible#122]
I get this error when I try to convert any  AAX  Audible Audio book to mp3
Im not computer savv sorry

OpenAudible uses the open source application 'rainbow craack' to look up audible codes. This process returned an error. This usually means you're running linux and have an incompatible system to the binary. 

You can try updating your version of 'OpenAudible/bin/rcrack' or just run the same command on a compatible system and copy the keys.json file to this computer.

Check the console for more information. The error reported was: 
cmd:"C:\Program Files\OpenAudible\bin\win\rcrack.exe" "C:\Program Files\OpenAudible\bin\tables" -h 419a8b38125d0cc75e18059f036580bc1f705b0c 
exit=-1073741819
stdout:
err=

For more information, visit: http://project-rainbowcrack.com/ or https://github.com/inAudible-NG/RainbowCrack-NG

**Comment by openaudible** [comment]
Probably an anti-virus program is preventing rcrack.exe from running.
