### ISSUE TITLE
Error when attempting to auto fill data for non audible book

### ISSUE THREAD

**Issue by gmoran1016** [openaudible/openaudible#1220]
Whenever I try to use the new autofill from the ASIN feature I get this error. I'm not sure if its an issue with audible or the program or maybe my book, but I wanted to put it out there. 
![image](https://github.com/openaudible/openaudible/assets/29048060/a638db08-7154-4799-9a8a-ac2ff01200d7)

**Comment by gmoran1016** [comment]
This happens for me both on version 3.7.5 and 3.7.5.2Beta

**Comment by openaudible** [comment]
Oh.. Yeah, you need to find the audible ASIN... if the book isn't on audible, you're out of luck.. unless there is another source for books that we can access the API for.  What did you enter for the ASIN and what result did you expect?

**Comment by gmoran1016** [comment]
I was attempting to use this ASIN from Amazon for the book White sand
ASIN: B08KTV7N2M
Link to the Amazon page where I got the ASIN: https://www.amazon.com/White-Sand-Dramatized-Adaptation-Book/dp/B08KTV7N2M

Link to audible page: https://www.audible.com/series/White-Sand-Audiobooks/B08KVW3H6M

It very well could be just me doing something wrong. Thanks for the help

**Comment by openaudible** [comment]
Oh, just noticed the "Unknown Host Exception" in your image.

That is likely a antivirus firewall issue.... Make sure that OpenAudible can access the internet in your antivirus settings. You can test this by going to "About Menu > Check for Update". You can also look at the console to see the full report. 
Or there was just a temporary network glitch. You can try again by pasting the ASIN and trying again.
