### ISSUE TITLE
Duration is wrong in iTunes on Windows

### ISSUE THREAD

**Issue by TommyNorthAL** [openaudible/openaudible#1221]
When I convert a long book (~20 hours or more) to .m4b, often after I import it to iTunes on Windows, the duration shown there is extremely off. For example, a 25 hour book may show as 360 hours. ffmpeg and ffprobe show the correct duration. I have searched and searched and cannot find a workaround for this. My previous solution has been to retranscode the .m4b using fre:ac and this gets the duration right when I import it to iTunes, but it is slow. I was hoping OpenAudible would  solve this, I just bought the license and realized that since you use ffmpeg I still have the same issue. 
Is there something I can do to solve this within OpenAudible?

**Comment by openaudible** [comment]
This is a very old iTunes for Windows bug that Apple for some reason refuses to fix, dating back over a decade.

Options are to find a better audiobook player for windows (I'm doing a little research)
listen on a mobile device (android/iphone), 
or convert to mp3 from OpenAudible.

We typically don't recommend converting to MP3 but if you need iTunes for windows, this may be the best bet. 

There is a chance that someone has found a fix that would keep the m4b conversion fast and fix the problem, so a little more google research might uncover some leads.. I can also send in a bug report to Apple...

**Comment by TommyNorthAL** [comment]
Thanks for the quick reply, I just got OpenAudible and it is really handy. I download two books a month, I'll just grin and bare it.
Thanks so much.

**Comment by TommyNorthAL** [comment]
I closed this, but the thing is that if I use ffmpeg to convert an aax to m4b, importing it to iTunes gives bad duration, but if I then simply transcode with mediaHuman or fre:ac from m4b to m4b and import that into iTunes, it works fine.
I guess it's just an incompatiblity between ffmpeg and iTunes, not really sure from this that it's all on the iTunes side?
Thanks for your help.

**Comment by openaudible** [comment]
I'll take a look at fre:ac and see if I can compare the two files and see what is going on.

**Comment by openaudible** [comment]
So I wasn't able to get frea:ac to generate working m4b files. They wouldn't play in either VLC or iTunes. Not sure what I did wrong--but selected large m4b and tried both AAC encoders as a single output file.

I did find that splitting the m4b book by chapter worked well for iTunes... All the chapters are split and show up correctly in iTunes under the books tab.

**Comment by TommyNorthAL** [comment]
In fre:ac I used the MPEG4 AAC Low Complexity with 128kbps to single output file and it worked fine. It does seem to crash some on my computer, which is why I ended up switching to mediaHuman instead. I've not had a problem with them working from either fre:ac (if it doesn't crash) or humanMedia.

Thanks for the tip about splitting, I may try that instead.

Thanks for all the help.

**Comment by openaudible** [comment]
That is strange. I was able to get ffmpeg to create a simple 40 hour white noise sample in aac format saved as noise.m4b and the length was correct in iTunes for Windows. I was hoping the noise file could be used to send a good bug report to Apple-- easily reproducible, etc. Someone on iTunes windows developer side would need to get a long audio file that breaks iTunes and see what is going on. iTunes for Mac is working as expected.

Because this is a bug only found on iTunes Windows, the best options are:

- Use different program
- Convert to MP3
- Split the M4B by chapters (seems to only affect large files.) 

Will attempt to file a bug report.

**Comment by TommyNorthAL** [comment]
Yes, it's not strictly deterministic on length, some break it shorter and some long ones work. I will continue my workaround to just re-encode the ones that fail iTunes import with re-coding in mediaHuman, which seems to work.
Thanks for looking into it. Very curious, but I'm guessing there is an overflow going on internally somehow in iTunes import.
