### ISSUE TITLE
downloaded AAX not playable in MAC Books app

### ISSUE THREAD

**Issue by lmgutman** [openaudible/openaudible#1222]
I downloaded 5 books via OpenAudible. The MP3s created worked fine but the AAX files were not playable in the Books app on my Mac or an external Sandisk media device. I had to redownload the files via the website for them to function correctly. Is there anything I can do to fix this? I have downloaded dozens of books before now without any issues.

**Comment by openaudible** [comment]
You need to convert them to M4B or MP3 files to be playable on your devices.

**Comment by openaudible** [comment]
Good to hear. Then it should be able to play m4b files as well.

**Comment by openaudible** [comment]
There are several formats encryption methods used by aax files. Convert them to M4B for the best compatibility and audio quality. Are you just trying to avoid paying for a license? Not sure the hesitancy....

**Comment by lmgutman** [comment]
I already own it.  Just wondering why the AAX file is not playable anymore when downloaded through the app.
