### ISSUE TITLE
converted some then rest stuck in convert queue

### ISSUE THREAD

**Issue by avwohl** [openaudible/openaudible#1223]
It converted 246 books to M4B.  419 books left to convert.  It wont convert any more.  It is stuck on 0 of 419 Converting.  There is no error message.  There is plenty of disk space.  I reinstalled the program. I rebooted. I am up to date on win 11 updates.  Bitdefender for anti virus.

I thought maybe it was stock on a particular book.  I turned off auto convert.  I canceled all converts.  I manually picked convert to MP4 on random books.  But it still would not convert, after picking 2 random books it at "Converting 0 of 2.  It shows a state of "In convert queue".  But no conversions happen.  I sorted by purchase date.  It is all mixed up (converted and won't convert), so it isn't just old or new books that it won't convert.

**Comment by Futoro** [comment]
I have the same problem. Some books converted and the rest is stuck in the converting queue. 
Old and new books all downloaded with openaudible.

**Comment by openaudible** [comment]
I think there might be a bug in the cancel all code. I will review! Thanks.

**Comment by openaudible** [comment]
Fixed in 3.7.6.1...
