### ISSUE TITLE
Unable to join tracks

### ISSUE THREAD

**Issue by petel** [openaudible/openaudible#1224]
Unable to join tracks

console:
Unable to join tracks

Jun 09, 2023 11:33:37 AM org.openaudible.convert.JoinAudio join
SEVERE: Text file contents:
file '/Users/peterloring/Desktop/The Botany of Desire A Plants-Eye View of the World - 005/The Botany of Desire A Plants-Eye View of the World - 005.mp3'
file '/Users/peterloring/Desktop/The Botany of Desire A Plants-Eye View of the World - 005/The Botany of Desire A Plants-Eye View of the World - 006.mp3'

Jun 09, 2023 11:33:37 AM org.openaudible.desktop.swt.manager.SplitJoinGUI run
SEVERE: join error for /Users/peterloring/Desktop/The Botany of Desire A Plants-Eye View of the World - 005 .DS_Store The Botany of Desire A Plants-Eye View of the World - 006.mp3
java.lang.Exception: Join failed:
TextFile:/Users/peterloring/Library/OpenAudible/tmp/files_1686324817825.txt
TextContent:file '/Users/peterloring/Desktop/The Botany of Desire A Plants-Eye View of the World - 005/The Botany of Desire A Plants-Eye View of the World - 005.mp3'
file '/Users/peterloring/Desktop/The Botany of Desire A Plants-Eye View of the World - 005/The Botany of Desire A Plants-Eye View of the World - 006.mp3'
 files=2
	at org.openaudible.convert.JoinAudio.join(JoinAudio.java:250)
	at org.openaudible.convert.JoinAudio.join(JoinAudio.java:154)
	at org.openaudible.convert.JoinAudio.join(JoinAudio.java:120)
	at org.openaudible.desktop.swt.manager.SplitJoinGUI$3.run(SplitJoinGUI.java:277)

Jun 09, 2023 11:33:37 AM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: Error
An error has occurred. Check File>Console for more details.
java.lang.Exception: Join failed:
TextFile:/Users/peterloring/Library/OpenAudible/tmp/files_1686324817825.txt
TextContent:file '/Users/peterloring/Desktop/The Botany of Desire A Plants-Eye View of the World - 005/The Botany of Desire A Plants-Eye View of the World - 005.mp3'
file '/Users/peterloring/Desktop/The Botany of Desire A Plants-Eye View of the World - 005/The Botany of Desire A Plants-Eye View of the World - 006.mp3'
 files=2
	at org.openaudible.convert.JoinAudio.join(JoinAudio.java:250)
	at org.openaudible.convert.JoinAudio.join(JoinAudio.java:154)
	at org.openaudible.convert.JoinAudio.join(JoinAudio.java:120)
	at org.openaudible.desktop.swt.manager.SplitJoinGUI$3.run(SplitJoinGUI.java:277)

**Comment by openaudible** [comment]
Shoot. That is an error from ffmpeg, and for some dumb reason, we don't have a good log message reported. Will try to create a beta with more logging.. unless you see an error further up the console log.

**Comment by openaudible** [comment]
Actually, the ffmpeg error should be displayed. Look at the console log after trying again and look for the line that starts with:
Non-zero for process:
Then it will show the ffmpeg command and the error that was returned. 
Of course, make sure that your audio files are valid.
