### ISSUE TITLE
only one download per running of open audible

### ISSUE THREAD

**Issue by avwohl** [openaudible/openaudible#1225]
osx v 3.7.6.1 I downloaded and converted a few hundred books ok.  Then it stopped without an error message.  Now each time I run oa it downloads and converts just one book.  It says "Downloading: 2 of 547' and sits there indefinitely.  I will submit data from the program as soon as this is posted and I get an incident ID.  Note that I have two audible accounts if it matters, only one is having this problem.

Months ago I ran into the same issue, I guessed it was due to some audible download limit.  I have perhaps 3000 books total across two accounts.  Last time I ran into this I waited a couple of days and it was fine.

**Comment by openaudible** [comment]
There should be three downloads at a time. This can be changed in the preferences. But this is likely a display/accounting problem-- where we fire off a 3rd download, but the display gets updated before it actually starts and before the accounting recognizes there are 3 downloads going. But it is a bug. Will try to address and fix. You can edit the prefs to change the concurrent_downloads from 3 to a higher number (5-6 should be the max.) Thanks for the report.

**Comment by avwohl** [comment]
It isn't just a display problem. No matter how long I leave it only one book is downloaded each time I run oa.  If I leave it running for an hour and restart it has only progressed one book from the previous run.

----- Original message -----

**Comment by openaudible** [comment]
Try this.. Open the File > Console window.
Select 3 books. 
Right-click download.
Watch the console window. You should see something like:

Starting job Download Book Title size:2 remain:1 success:6 fail:0 threads:3
The threads 3 is the number of concurrent downloads.

If there are errors, see if they make sense.. or copy and paste the log here, or drop us a line.

**Comment by avwohl** [comment]
I have a theory as to what the problem is and was able to work around it.  The problem seems to be if you have two accounts and undownloaded books from both and uncoverted books from both that it gets gummed up with which credentials to use to download/decode which books.   I deleted all the undecoded books and all the undownloaded.  Now it downs and converts ok.

- there doesn't seem to be any way to see what account you are logged into.  Maybe the logout menu could change to say login from amazon login foo@bar.com or logout from audible login lalala
- perhaps a column should be added for what account the download is from
- I know this area (multiple accounts) is under development but when this bug hits it makes the current oa unusable
- check that oa handles having the same book come from two different accounts, with 3000 books I have a few in both accounts

**Comment by avwohl** [comment]
You are correct that if I pick 3 books and download it does say 3 threads in the console log.  But that is separate issue from getting gummed up if using two accounts and both have undownloaded and unconverted books.

**Comment by openaudible** [comment]
Fixed in 3.7.6.2. Sorry for the inconvenience. Thank you for the reports!
