### ISSUE TITLE
converts stop after around 100 downloads

### ISSUE THREAD

**Issue by avwohl** [openaudible/openaudible#1226]
3.7.6.1 win11 AND osx After about 100 downloads they stop and never continue no matter how long you wait.  It will stop and be saying Converting: 0 of xxx.  If I exit and restart and quick sync it resumes fine for another batch.

The display starts at Converting: 3 of 545 then immediately changes to 2 of 544 I did try to convert 3 books and it did you 3 threads as you suggested.

There is no fixed number of how many it can download.  I just restarted and got over 300 downloaded before hanging.

Note that ALL the downloads are on the same account. I am being careful to fully download one account before switching to the 2nd account.

**Comment by openaudible** [comment]
Ok. Can you send a bug report from the about menu after it stops downloading? Trying to reproduce here as well. Thank you for the good report.

**Comment by openaudible** [comment]
Confirmed. Found bug. Testing the fix and will post shortly. Thanks!

**Comment by openaudible** [comment]
Fixed in 3.7.6.2. Sorry for the inconvenience. Thank you for the reports! Please update to the latest.
