### ISSUE TITLE
Subchapters (Parts) missing

### ISSUE THREAD

**Issue by joergister** [openaudible/openaudible#1228]
I tried to download https://www.audible.de/author/Thomas+Sowell/B00J5BK55K but it only shows me chapter, all the subchapters (Parts) 
![IMG_AC020C694966-1](https://github.com/openaudible/openaudible/assets/24881413/2eb9296f-357a-4cf9-ba01-8fd748b774d3)
are missing.
<img width="793" alt="chapters" src="https://github.com/openaudible/openaudible/assets/24881413/b2911d6e-fc9f-4a92-a519-6a2ccbd5402f">

I was able 
to obtain a m4b file containing all the chapters (including the subchapters (Parts)) using the method described below though. Since I'm a paying customer and I just delivered you a way of doing this, I think it would be smart to integrate a way of doing this into openaudible because I'm for sure not the onyl customer complaining about this. Also all the code used is open source so there should be no problem figuring out how that works.

The way i obtained the m4b file containing all the chapters (including the subchapters (Parts)):
- I got the Standalone file from https://github.com/mkb79/audible-cli and put it in an empty folder.
- Created the config file using `/audible quickstart` 
- downloaded the aaxc files using `/audible download --all --aaxc --cover --cover-size 1215 --chapter`
- downloaded AAXtoMP3 https://krumpetpirate.github.io/AAXtoMP3/ unzipped it and put it in the folder containing the audible binary. I downloaded the dependencies needed for AAXtoMP3 (can be found in the documentation)
- The Json file containing the chapters and parts needed to be flattened so it would be a proper input for AAXC `python3 flatten_chapters.py TO_FLATTEN.json` using the python code from below does that.
- converted the AAXC file into multiple m4b files all having the chapter of subchapter (part) name as their filename using `bash AAXtoMP3 -e:m4b -c -D 'Audiobooks/$title ($narrator)' --use-audible-cli-data *.aaxc`
- combined the files using https://github.com/gonzoua/AudioBookBinder got it from the appstore though https://apps.apple.com/de/app/audiobook-binder/id413969927?mt=12 while having chapter names configured as described here http://bluezbox.com/audiobookbinder/chapters.html Attention though: the output length had to be set to infinity, otherwise i would get multiple m4b files. 

```
import sys
import json

def flatten_chapters(y):
out = []

def flatten(x, level=0):

    for a in x:
        if 'chapters' in a:
            sub_chapters = a["chapters"] 
            del a["chapters"]
            if level>0:
                a["title"] = '*' * level + ' ' + a["title"]
            out.append(a)
            flatten(sub_chapters, level+1)

        else:
            if level>0:
                a["title"] = '*' * level + ' ' + a["title"]
            out.append(a)
        
flatten(y)
return out


if len(sys.argv) != 2:
print("usage: python flatten_chapters.py filename")
sys.exit(2)

data = json.load(open(sys.argv[1]));

data["content_metadata"]["chapter_info"]["chapters"] = flatten_chapters(data["content_metadata"]["chapter_info"]["chapters"])

print(json.dumps(data, indent=4, sort_keys=False));
```

**Comment by openaudible** [comment]
We get chapter data from the audible api and from within the downloaded book. Usually it contains all the part info.. 
Before splitting we make a determination of which chapters to use for splitting. 
If you send me a full report on that book, we can take a look at what is going on.
Select the book in OpenAudible, go to Get Info, then click on the Book Report tab.
Select all and copy/paste send to us at https://openaudible.org/contact?subject=support

**Comment by joergister** [comment]
Alright, I just did that. Funnily enough, the info for the parts seem to be contained in the content of the book report tab, but is not represented as chapters in the m4b file.

**Comment by openaudible** [comment]
Ok.. Found the problem. The AAX file has the correct info, and we used the API info..  Usually it is the other way around. (API has chapter names, AAX file usually doesn't.)  In any case, we switched the code to prefer more chapters over fewer chapters. (and then chapter names over no chapter names...)
Please give 3.8.1 a try.
You will need to re-encode the M4B ... and if you're splitting the book, you'll need to re-split... 
Please re-open or comment here if that doesn't solve it.
