### ISSUE TITLE
Windows: Error executing ffmpeg

### ISSUE THREAD

**Issue by elpatron68** [openaudible/openaudible#123]
Trying to convert a successfully downloaded AAX file to MP3 using ffmpeg fails:

```
java.io.IOException: Unable to find executable:C:\Program Files\OpenAudible\bin\win\ffmpeg
```
Should the file `C:\Program Files\OpenAudible\bin\win\ffmpeg` not be named `ffmpeg.exe`? Manually renaming it does not help.

/Edit: OpenAudible Version: 1.4.9, Windows 10 64 bit

Thankful for any ideas!

Markus

**Comment by openaudible** [comment]
There should be a file called: C:\Program Files\OpenAudible\bin\win\ffmpeg
From command line: dir "C:\Program Files\OpenAudible\bin\win\ffmpeg" should show the file. 

Check your anti-virus and make sure you are allowed to execute that ffmpeg and that it wasn't quarantined. 

Having .exe should not matter. Firewall/virus program is the only thing I can think of.

**Comment by elpatron68** [comment]
Sorry this was my fault. At the end, I should have been just a little bit more patient because converting takes its time.
