### ISSUE TITLE
Libro.fm

### ISSUE THREAD

**Issue by sgspecker** [openaudible/openaudible#1232]
### Discussed in https://github.com/openaudible/openaudible/discussions/1231

<div type='discussions-op-text'>

<sup>Originally posted by **sgspecker** June 23, 2023</sup>
Along with Audible, I have started buying audiobooks from [Libro.fm](https://libro.fm/). Since they provide DRM-free books in zipped MP3 and M4B formats, it would be great if I could easily add books from my Libro library, too.

Thanks Much,
Scott

</div>

**Comment by openaudible** [comment]
For now you should be able to drag and drop the files onto OpenAudible or use the import. But can take a look.

**Comment by openaudible** [comment]
Yeah, so Libro.fm doesn't have a public API (that we know about) but perhaps it can be determined.
For now, log in with your browser, go to the "Account" and download the m4b... then drag and drop onto OpenAudible. 

One tip... If there are tags missing (publisher, author, asin, etc.) you can fill those in using Audible data by first finding the book in audible, the copy the audible URL into the book's "Get Info" dialog in OpenAudible under "Book URL" (3rd item down), then click on the "Auto Fill" button at the bottom. It should grab additional missing meta data. 

Hope that helps. Feel free to add anything to this... but libro.fm looks like a good service!

**Comment by sgspecker** [comment]
Following your recommendation I added the books using drag-n-drop.
But when I copied the book URL to the Get Info, I received an error. But upon closing the error dialog it immediately popped back up. I had to kill OpenAudible using the Task Manager.
FWIW,Scott    On Sunday, June 25, 2023 at 06:04:04 PM CDT, openaudible ***@***.***> wrote:  
 
 


Yeah, so Libro.fm doesn't have a public API (that we know about) but perhaps it can be determined.
For now, log in with your browser, go to the "Account" and download the m4b... then drag and drop onto OpenAudible.

One tip... If there are tags missing (publisher, author, asin, etc.) you can fill those in using Audible data by first finding the book in audible, the copy the audible URL into the book's "Get Info" dialog in OpenAudible under "Book URL" (3rd item down), then click on the "Auto Fill" button at the bottom. It should grab additional missing meta data.

Hope that helps. Feel free to add anything to this... but libro.fm looks like a good service!

**Comment by openaudible** [comment]
Hmm. That is strange. I tried to reproduce by dragging one of my libro books into OA.. Then Get Info.. and set Book URL to https://libro.fm/audiobooks/xxx-name-of-book  .. Saving updated the meta data and all seemed fine. 

Can you look at the console window (File > Console (ctrl-E) and see what the error message says? Every error and alert dialog should be logged to the console. 

Also, check that you're using the latest version, currently 3.8.1.

**Comment by sgspecker** [comment]
Yes, I'm using 3.8.1.
Since it causes an endless loop error -- and I have to kill it using Windows Task Manager -- it looks like the Console data is erased.
Oddly enough, I thought you suggested that I enter the Audible Book URL (see further below for more on this). When I enter the Libro book URL, here is the error I get. At least, this one is recoverable.
But when I enter the Audible Book URL and click "Autofill"... it appears to work by pulling in data from the page. But then the following dialog pops up. Closing it just makes the dialog pop up, again. The only way to get back control is to kill the program.

FWIW,Scott

    On Sunday, July 2, 2023 at 02:40:43 PM CDT, openaudible ***@***.***> wrote:  
 
 


Hmm. That is strange. I tried to reproduce by dragging one of my libro books into OA.. Then Get Info.. and set Book URL to https://libro.fm/audiobooks/xxx-name-of-book .. Saving updated the meta data and all seemed fine.

Can you look at the console window (File > Console (ctrl-E) and see what the error message says? Every error and alert dialog should be logged to the console.

Also, check that you're using the latest version, currently 3.8.1.

**Comment by openaudible** [comment]
The image didn't come through via email. You can attach by going to this link and using drag and drop.
https://github.com/openaudible/openaudible/issues/1232

Or you can email it to us at openaudible at email dot tg...

**Comment by naglis** [comment]
FWIW, I checked the Libro.fm Android app (v7.6.1, build: 194) to figure out the endpoints of their private API. The three essential calls are:

- `POST /oauth/token` - [login](https://git.sr.ht/~naglis/librofmdl/tree/f00c3332c11233b5d0524cffb5598e47222731ec/item/librofmdl.py#L110) to get the auth token;
- `GET /api/v7/library` - [list purchased publications](https://git.sr.ht/~naglis/librofmdl/tree/f00c3332c11233b5d0524cffb5598e47222731ec/item/librofmdl.py#L127) in the user's library;
- `GET /api/v9/download-manifest` [get download URLs](https://git.sr.ht/~naglis/librofmdl/tree/f00c3332c11233b5d0524cffb5598e47222731ec/item/librofmdl.py#L140) for a publication, indicated by ISBN.
