### ISSUE TITLE
Split Chapters double

### ISSUE THREAD

**Issue by christianmerges** [openaudible/openaudible#1234]
In Version 3.8.1 when we split a book we have every chapter doubled:
Kapitel 01.m4b
Kapitel 01art.m4b

The size seems to be identical.

**Comment by openaudible** [comment]
I have not seen that. How do the chapters look in Get Info for the book?

Can you delete the split book, restart open audible, split the book and send a bug report from the About menu?

**Comment by christianmerges** [comment]
I cannot reproduce that because we it occurred on the windows version only. On Ubuntu the Issue is not happening. Maybe it was problem with filesystem only.

**Comment by openaudible** [comment]
No idea. Feel free to submit a bug report after it happens again.
