### ISSUE TITLE
HTML Code in ID3-Tags

### ISSUE THREAD

**Issue by christianmerges** [openaudible/openaudible#1235]
When we import the splittet Audiobooks in Plex. Alle the Metadata contains 
`
"<BR/>" and "<P>" ` tags.

`Sommer, Sonne, Strand, Meer. Wie man sich als Single in einem Familienhotel durchschlägt. Wie man die beste Liege am Pool sichert. Warum es sinnvoll ist, beim Baden im Meer Schuhe anzuziehen. <br /> <br />Herbert ist Spießer aus Überzeugung, Mitte dreißig, Bayer. Wie jedes Jahr reist Herbert im Urlaub in den Süden. Dieser Herausforderung stellt er sich, ausgerüstet mit einer gesunden Portion Selbstbewusstsein und Durchhaltevermögen. Denn Herbert weiß aus Erfahrung, dass Urlaub auch anstrengend sein kann - erst recht dann, wenn man alleine reist. Ob Herbert seinen Urlaub auch als Single beendet? <br /> <br />Ein Hörbuch, auch für Männer.<p>>> Diese ungekürzte Hörbuch-Fassung genießt du exklusiv nur bei Audible.</p>`

**Comment by openaudible** [comment]
That comes from Audible. Plex should look for that and strip it out or format it has basic HTML...  We try not to modify any of the tags that we get.

**Comment by christianmerges** [comment]
I'm not sure about the ID3 Tag standard in detail but i doubt that it is made to include html code. Can't u not just delete all the tag and replace <br/> tags with a new line instead?

**Comment by openaudible** [comment]
Html is perfectly fine for meta tags. Audible gets to decide what to include. In fact it makes more sense then regular text since you can include links or stylized text. Removing it is possible but could corrupt the meaning, for instance with hyperlinks. Seems like a bug for Plex to address.
