### ISSUE TITLE
Incorrect "last free version" on license information page

### ISSUE THREAD

**Issue by ganders3** [openaudible/openaudible#1236]
Hi, when I go to my license info page (https://openaudible.org/license?license=XXXX-XXXX-XXXX), the "last free license" listed is not correct. My license expired in July 2021, but the last free license links to release 3.2.1 from November 2021. I was unable to activate my license when I installed 3.2.1, but when I searched manually and downloaded the last update before July 2021 (3.0.1) I was able to activate it.

**Comment by openaudible** [comment]
Send a message to us using https://openaudible.org/contact?subject=support and we'll send a new license and try to fix that bug. Thanks!

**Comment by ganders3** [comment]
I already did but wanted to point it out in case other people have the same problem. Thank you

**Comment by openaudible** [comment]
Thank you. Fixed. github started to limit the number of releases returned in their API code.. Nice catch!
