### ISSUE TITLE
Retrieving Metadata does not advance Progress Bar (already at 100%)

### ISSUE THREAD

**Issue by OttScott** [openaudible/openaudible#1237]
When linking my Audible account, the dialog box shows a progress bar while enumerating my titles. When it gets to 100% it switches to a countdown for downloading metadata. The progress bar still shows 100% however and gives a false indication that the process is complete. Recommend starting progress bar over when switching task to metadata download.

**Comment by openaudible** [comment]
Improved for next version.

**Comment by openaudible** [comment]
https://openaudible.org/beta
