### ISSUE TITLE
Moving Library to new drive failed - Failed to delete library file

### ISSUE THREAD

**Issue by OttScott** [openaudible/openaudible#1238]
Migrating drives from default by creating new path and selecting Move from Manage Libraries. All file copies appear to be correctly moved, but exception thrown at 100%. 

Exception Details attached as OpenAudibleLog.txt
[OpenAudibleLog.txt](https://github.com/openaudible/openaudible/files/11951493/OpenAudibleLog.txt)

**Comment by OttScott** [comment]
Appears related to Preferences file still being present and locked in original folder. After moving Preferences file (through Environment Variable, bizarrely) I was able to delete original folder and I suspect this issue would have been resolved. 
Recommend pairing preferences file with 1st library folder and, if moved, move the preferences file as well. (And decouple from Environment variable. Save as Reg value if required)

**Comment by openaudible** [comment]
Oh good catch. Will fix that. Will update this when fixed.

**Comment by openaudible** [comment]
Fixed in first beta: https://openaudible.org/beta

**Comment by openaudible** [comment]
Fixed in 3.9
