### ISSUE TITLE
Feature Request: Search in Books

### ISSUE THREAD

**Issue by OttScott** [openaudible/openaudible#1239]
I have over 300 books from Audible. I'd like the ability to filter or search my titles instead of scrolling through the list. Please add a Full-Text search bar above the library list so I can find the books I want quickly.

**Comment by OttScott** [comment]
Just found the Search bar at top is not just for Categories as it seems to indicate. Recommend making this clearer, but you can close this issue as already implemented.

**Comment by openaudible** [comment]
I can see the confusion. Yes, just type your query!
