### ISSUE TITLE
Cannot resize window elements, text is only partially visivble

### ISSUE THREAD

**Issue by MartinSGill** [openaudible/openaudible#1243]
Suspect it has to do with DPI settings.

Would also be good if I could control the various font sizes in the app from preferences.

![image](https://github.com/openaudible/openaudible/assets/2271740/4843c0df-168f-4907-b0e2-310609a1a065)

**Comment by openaudible** [comment]
That happens sometimes. What if you quit and restart? Which OS are you using?

**Comment by openaudible** [comment]
For now, you many need to make the window bigger and restart the app. Will try to reproduce.

**Comment by MartinSGill** [comment]
It happened right after install.

Restarting did resolve it. Resizing the font would still be nice to have.
