### ISSUE TITLE
Folders "OpenAudible/web/m4b" and "OpenAudible/web/mp3" are not created and populated witht heir respective files

### ISSUE THREAD

**Issue by Lawrence-Norman** [openaudible/openaudible#1244]
1. Folders "m4b" and or "mp3" are not created under folder "web". 
2. Clicking on file "web/index.html" displays the icon links to folders "m4b" and or "mp3", but obviously if the folders don't exists, a correct error message is displayed.
3. My work-around: 
    3.1 Created both folders "web/m4b" and "web/mp3" (per 1 above)
    3.2 Copied respective files from folder OpenAudible/books into their respect folders in 3.1 above.
4. REALLY LOVE THIS FEATURE i.e. being able to play my book in my Browser (Firefox): nice! 

I'm not a java-script programmer (very good at c, c++, java, c#, etc) but was wondering if a simple fix could be applied to some web file e.g. "web/books.js" and or "web/books.json", etc, that allows file "web/index.html" to point to files in OpenAudible/books which eliminates the file duplicates via my work around.

Best Regards
LAwrence

**Comment by openaudible** [comment]
Yes... we are working on removing the duplicate stuff.. But it is a little slow getting going. Putting this back onto the TODO pile.

**Comment by openaudible** [comment]
Try 3.9.4. It will still copy the files over to the web directory.. but our goal is to make it an optional thing-- and for others to be able to just use our books.json file as a read only directory that works with different web interfaces.. Closing as a feature request.
