### ISSUE TITLE
Audiobook Info not populating

### ISSUE THREAD

**Issue by TheRealMathemAddicts** [openaudible/openaudible#1247]
One of the key features of this app is completely missing for me. The "Audiobook Info" pane is completely unfilled for all of my audiobooks despite having been filled in previous versions. I just updated to 3.8.1.

I have gone through a couple of audiobooks, right-clicked, clicked Get Info, then Save (to save anything), but nothing gets populated in the Audiobook Info pane.

**Comment by openaudible** [comment]
Did you enter the audible url into the book info link field? Check the console for any errors. You can send the console log to us via our contact form if you see anything unusual.

**Comment by TheRealMathemAddicts** [comment]
Maybe I am not running the version you are. Mine doesn't have a field titled, "Audible URL". I _do_ have a "Book URL" and that is properly filled for all of my books. Here is an image of the issue. I have clicked a book (and I show the Get Info page), but the Audiobook Info is blank.
![Screenshot 2023-08-15 075357](https://github.com/openaudible/openaudible/assets/142115552/b962bdbf-591c-4165-81d9-5d2206b6ba90)

**Comment by TheRealMathemAddicts** [comment]
My Book Table seems to be filled properly:
![Screenshot 2023-08-15 081718](https://github.com/openaudible/openaudible/assets/142115552/b98c34c3-0db0-47e8-b935-01da3092db60)

**Comment by openaudible** [comment]
Is the book info panel blank for pop-ups if it is, you may need to quit and restart the app. Maybe it got resized incorrectly

**Comment by TheRealMathemAddicts** [comment]
I am not certain what the Book Info Panel is. You have mentioned several things that my version doesn't have - "Book Info Field", "Audible URL", "Book Table"... Here's what I have:
![Screenshot 2023-08-15 085244](https://github.com/openaudible/openaudible/assets/142115552/40aa5201-33f0-4a22-ba39-89ab5c80f6e1)
![Screenshot 2023-08-15 085300](https://github.com/openaudible/openaudible/assets/142115552/93712a7b-404c-42de-a4dc-dd93dd8c089b)
![Screenshot 2023-08-15 085312](https://github.com/openaudible/openaudible/assets/142115552/49583a3d-3a0f-4348-8f35-f5b2e42985f1)
![Screenshot 2023-08-15 085326](https://github.com/openaudible/openaudible/assets/142115552/73d0621a-ef2c-4ce1-a442-0557a6322886)

**Comment by TheRealMathemAddicts** [comment]
Is there possibly an older version that I can rollback to?

**Comment by TheRealMathemAddicts** [comment]
> All are available under this GitHub releases tab.

I am sorry, but I do not see a "releases tab". Could you be more exact (I am new to GitHub).
![Screenshot 2023-08-16 114852](https://github.com/openaudible/openaudible/assets/142115552/5e1a23d5-3e42-4342-99a0-4e6b22cc8401)

**Comment by openaudible** [comment]
https://github.com/openaudible/openaudible/releases

**Comment by openaudible** [comment]
By the way.. I did reproduce a situation where the info panel did not populate. I resized the main window a little bit and shuffled the GUI components around a little and the info panel popped back into view correctly. Maybe you have a weird screen size that populates the GUI components in a way where the Info panel is corrupt. Try resizing the main window with one book selected.
