### ISSUE TITLE
ability to set the output media to mono

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#1249]
i have a number of audiobooks that when converted are stereo, however, the original audio was recorded in mono, both stereo tracks are identical, being able to output as mono rather than stereo would save space due to smaller files for audiobooks that you don't need stereo
while this could be done automatically by seeing if both tracks are identical and if so setting the file to mono, a simple setting to allow output to be mono for all conversions would be easier I think.... and then people would just change it to/from stereo/mono as needed

**Comment by openaudible** [comment]
This is an edge case that we don’t intend to add— we want to keep the audio as is. 

You can use the following FFmpeg command to convert a stereo audio file "test.mp3" to mono:

```bash
ffmpeg -i test.mp3 -ac 1 mono_test.mp3
```

This command will take the input file "test.mp3" and create a mono output file named "mono_test.mp3". The `-ac 1` flag specifies that you want a single audio channel, which makes it mono.
