### ISSUE TITLE
Error updating book

### ISSUE THREAD

**Issue by IMDBLM** [openaudible/openaudible#1250]
When I put the Audible address into the info of a book and click 'save' I get put into an error look that says there was an error updating the book. java.io.IOException: ffmped retag failed

**Comment by openaudible** [comment]
Please copy and paste the whole error log or send it via our contact form. The error is in the File: Console menu.

**Comment by IMDBLM** [comment]
Hey, sorry. Life got away from me. Here is the most recent error log.


{
 "date": "Sun Sep 17 15:58:46 EDT 2023",
 "memory": "Memory: Using 29.59MB of 1.84GB (2%) Min 29.59MB Max 29.59MB",
 "bookFiles": {
  "MP3": {
   "count": 7,
   "dir": "C:\\Users\\Matth\\OpenAudible\\books"
  },
  "ART": {
   "count": 42,
   "dir": "C:\\Users\\Matth\\OpenAudible\\art"
  },
  "PDF": {
   "count": 1,
   "dir": "C:\\Users\\Matth\\OpenAudible\\books"
  },
  "AAX": {
   "count": 6,
   "dir": "C:\\Users\\Matth\\OpenAudible\\aax"
  },
  "M4B": {
   "count": 12,
   "dir": "C:\\Users\\Matth\\OpenAudible\\M4B"
  },
  "M4A": {
   "count": 0,
   "dir": "C:\\Users\\Matth\\OpenAudible\\books"
  }
 },
 "selected_books": [],
 "threads": "",
 "library_stats": {
  "Downloading": "",
  "PDFs": "1/2",
  "AYCE": "0",
  "Connected": "Yes",
  "Hours": "606",
  "M4B_Files": "57",
  "License": "Valid",
  "AAX_Files": "6",
  "To_Convert": "0",
  "MP3_Files": "7",
  "Missing_Links": "1",
  "To_Download": "29",
  "Converting": "",
  "Podcasts": "0",
  "Region": "US",
  "Books": "42",
  "M4A_Files": "0",
  "Ignored": "0"
 },
 "compile_date": "2023-06-26 17:06",
 "version": "3.8.1",
 "demo": false,
 "platform": "win",
 "prefs": {
  "disableVersionCheck": false,
  "expert": false,
  "autoConvert": true,
  "language": "en",
  "uid": "1666145609163",
  "browseFileCmd": "",
  "browser": "",
  "html": false,
  "theme": "",
  "browseWebCmd": "",
  "autoDeleteAAX": false,
  "lastVersion": "3.8.1",
  "playFileCmd": "",
  "webPageIncludeMP3": true,
  "format": "M4B",
  "autoDownload": false,
  "autoWebPage": false,
  "autoRefreshMinutes": 0,
  "autoConnect": false,
  "concurrentConversions": 3,
  "podcasts": false,
  "mp3Quality": "",
  "concurrentDownloads": 3,
  "autoPDF": true,
  "region": "US"
 },
 "books.json": "C:\\Users\\Matth\\OpenAudible\\books.json",
 "java": {
  "java.specification.version": "11",
  "java.runtime.version": "11.0.15+10",
  "java.class.path": "C:\\Program Files\\OpenAudible\\.install4j\\i4jruntime.jar;C:\\Program Files\\OpenAudible\\.\\.\\openaudible_win_x86_64.jar;C:\\Program Files\\OpenAudible\\.\\openaudible_win_x86_64.jar",
  "sun.java2d.dpiaware": "true",
  "java.vm.vendor": "Eclipse Adoptium",
  "java.runtime.name": "OpenJDK Runtime Environment",
  "java.vendor.url": "https://adoptium.net/",
  "java.vm.specification.version": "11",
  "java.vm.name": "OpenJDK 64-Bit Server VM",
  "java.vendor.version": "Temurin-11.0.15+10",
  "sun.java.command": "C:\\Program Files\\OpenAudible\\OpenAudible.exe",
  "java.vendor.url.bug": "https://github.com/adoptium/adoptium-support/issues",
  "java.io.tmpdir": "C:\\Users\\Matth\\AppData\\Local\\Temp\\",
  "java.version": "11.0.15",
  "java.specification.vendor": "Oracle Corporation",
  "java.vm.specification.name": "Java Virtual Machine Specification",
  "java.awt.printerjob": "sun.awt.windows.WPrinterJob",
  "java.version.date": "2022-04-19",
  "java.home": "c:\\program files\\openaudible\\jre",
  "vm_args": [
   "-Dexe4j.semaphoreName=Local\\c:_program_files_openaudible_openaudible.exe",
   "-Dexe4j.isInstall4j=true",
   "-Dexe4j.moduleName=C:\\Program Files\\OpenAudible\\OpenAudible.exe",
   "-Dexe4j.tempDir=",
   "-Dexe4j.unextractedPosition=0",
   "-Djava.library.path=c:\\program files\\openaudible\\jre\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\FileBot\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Calibre2\\;C:\\Users\\Matth\\AppData\\Local\\Microsoft\\WindowsApps;",
   "-Dexe4j.consoleCodepage=cp0",
   "-Dfile.encoding=UTF-8",
   "-Dsun.jnu.encoding=UTF-8",
   "install",
   "-DOARCH=AMD64",
   "-Dinstall4j.launcherId=22",
   "-Dinstall4j.swt=true",
   "-Dsun.java2d.dpiaware=true"
  ],
  "java.vm.compressedOopsMode": "32-bit",
  "java.library.path": "c:\\program files\\openaudible\\jre\\bin;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files\\FileBot\\;C:\\Program Files\\dotnet\\;C:\\Program Files\\Calibre2\\;C:\\Users\\Matth\\AppData\\Local\\Microsoft\\WindowsApps;",
  "java.specification.name": "Java Platform API Specification",
  "java.vm.specification.vendor": "Oracle Corporation",
  "java.vm.info": "mixed mode",
  "java.vendor": "Eclipse Adoptium",
  "java.vm.version": "11.0.15+10",
  "java.awt.graphicsenv": "sun.awt.Win32GraphicsEnvironment",
  "java.class.version": "55.0"
 },
 "queues": [
  "DownloadQueue size:0 remain:0 success:0 fail:0 threads:0 jobs:0 jobs: threads:",
  "PDF Downloader size:0 remain:0 success:0 fail:0 threads:0 jobs:0 jobs: threads:",
  "ConvertQueue size:0 remain:0 success:0 fail:0 threads:0 jobs:0 jobs: threads:",
  "GetBookImageQueue size:0 remain:0 success:0 fail:0 threads:0 jobs:0 jobs: threads:"
 ],
 "directories": [
  {
   "path": "C:\\Users\\Matth\\OpenAudible",
   "kind": "BASE",
   "exists": true
  },
  {
   "path": "C:\\Users\\Matth\\OpenAudible\\books",
   "kind": "BOOKS",
   "exists": true
  },
  {
   "path": "C:\\Users\\Matth\\OpenAudible\\web",
   "kind": "WEB",
   "exists": false
  },
  {
   "path": "C:\\Users\\Matth\\OpenAudible",
   "kind": "META",
   "exists": true
  },
  {
   "path": "C:\\Users\\Matth\\OpenAudible\\tmp",
   "kind": "TMP",
   "exists": true
  },
  {
   "path": "C:\\Program Files\\OpenAudible",
   "kind": "APP",
   "exists": true
  }
 ],
 "gui": {
  "swt_platform": "win32",
  "main_window": "Rectangle {486, 69, 1037, 802}",
  "browser": {
   "prefer_chromium": false,
   "oa_chromium": "",
   "swtBrowserStyle": 0,
   "Desktop.isDesktopSupported": true,
   "externalBrowser": true,
   "Desktop.Action.BROWSE": true,
   "externalBrowserMode": "desktop",
   "oa_internal_browser": "",
   "browseWebCmd": ""
  },
  "display": {
   "highContrast": false,
   "bounds": "Rectangle {0, 0, 1920, 1080}",
   "dpi": "Point {120, 120}"
  },
  "aspect": 1.2930175,
  "theme": {
   "dark_debug": "",
   "org.eclipse.swt.display.useSystemTheme": "null",
   "theme": "system",
   "is_dark": true
  },
  "table": {
   "col_width": 14,
   "2x": false,
   "col0Width": 25,
   "img_bounds": "Rectangle {0, 0, 14, 14}",
   "scale_down_1k": 1000,
   "scale_up_1k": 1000
  },
  "swt_version": 4956
 },
 "region": "US",
 "properties": {
  "oa_external": "",
  "file.encoding": "UTF-8",
  "os": "",
  "java.version": "11.0.15",
  "oa_chromium": "",
  "sun.jnu.encoding": "Cp1252",
  "SWT_GTK3": "null",
  "OPENAUDIBLE_HOME": "",
  "oa_internal_browser": "",
  "oa_packaging": ""
 }
}

**Comment by openaudible** [comment]
Unfortunately that is the diagnostics window. The error log would be under the file menu: Console. The error will appear after you try to modify the book. 
we do have a beta that you can also get that might have better results if we happen to have fixed it since the last full version: https://OpenAudible.org/beta
