### ISSUE TITLE
'aresample' filter not present, cannot convert formats.

### ISSUE THREAD

**Issue by stevenleadbeater** [openaudible/openaudible#1254]
Occurs when a ffmpeg_args_mp3.txt file is present with contents:

`-ar
44100
`

resolved by copying `/usr/bin/ffmpeg` to `/opt/OpenAudible/bin/linux_x86_64/` has the bundled ffmpeg been built without libmp3lame?

**Comment by openaudible** [comment]
Yeah we include a special ffmpeg that has most filters and codecs disabled. Will make a note to include the resample filter. So for the foreseeable future you’ll need to use your own ffmpeg. Rebuilding them all from source is a huge pain.
