### ISSUE TITLE
No Cover 

### ISSUE THREAD

**Issue by Bonbernie** [openaudible/openaudible#1256]
I have no cover shown. When I go to "Get Info" there is a picture. 
[Bildschirmfoto 2023-08-30 um 20.03.25.pdf](https://github.com/openaudible/openaudible/files/12478895/Bildschirmfoto.2023-08-30.um.20.03.25.pdf)

Also the window size is not saved when ending the program. And when I change the table settings from Title, Author, Series Name to Author, Title, Series Name and end the program, the changes are also not saved and by restart there is again Title, Author, Series Name. I have uninstalled and reinstalled the program, even with older versions that worked before. But nothing changes.

**Comment by Bonbernie** [comment]
PS: Mac OS Monterey 12.6.8

**Comment by openaudible** [comment]
That book is in the download queue. Once it is downloaded, if there is no image, it will be extracted from the download's meta data.

**Comment by Bonbernie** [comment]
No, I have downloaded all the books. The cover is not displayed. If I vary with the window size it is displayed in between times. But when I close the program and open it again, no cover is displayed again. Also, the program does not remember the last window size. The same applies to the categories author, title duration etc.. If I change the order, after a restart everything is again as before and not as I had rearranged it.

**Comment by openaudible** [comment]
I see. This looks like the image placeholder is missing. We usually hide the cover image if we detect your window is smaller than 600px. That is why resizing it will bring it back. But I don't know why it would think the size is too small. It does seem related to the window size not getting saved. 

The window positions and table states are saved to the preferences when the app is closed. You can double check by looking at the windows.json in the ~/OpenAudible/windows.json directory. You can view the file with a text editor and the main window should look like:

 "window_pos": {
  "maximized": false,
  "x": -2340,
  "width": 1570,
  "y": 516,
  "open": true,
  "height": 1197
 }
If the width is less than 600 when it starts, it should hide the cover.. but obviously from your screenshot the window is >600 and the cover is missing. 

I can log a little more info to the code that hides the cover. You could also look at the About: Diagnostics and scroll down the the "GUI" entry where it will display info about your window position and size. Maybe you can notice something that doesn't look right.

As soon as a beta or new release has better logging, I'll let you know.

**Comment by Bonbernie** [comment]
Here is my windows.json direcctory:

id | "series_name"
-- | --
10 |  
visible | false
width | 150
id | "notes"
11 |  
visible | false
width | 150
id | "product_id"
12 |  
visible | false
width | 150
id | "asin"
13 |  
visible | false
width | 150
id | "key"
14 |  
visible | false
width | 150
id | "filename"
15 |  
visible | true
width | 150
index | 7
id | "read_status"
16 |  
visible | false
width | 150
id | "ayce"
17 |  
visible | false
width | 150
id | "language"
reverse_sort | false
order |  
0 | 0
1 | 1
2 | 2
3 | 3
4 | 4
5 | 5
6 | 6
7 | 7

And here is a part of the diagnostics with gui information:"gui": {
  "swt_platform": "cocoa",
  "main_window": "Rectangle {20, 34, 790, 774}",
  "browser": {
   "prefer_chromium": false,
   "oa_chromium": "",
   "swtBrowserStyle": 0,
   "Desktop.isDesktopSupported": true,
   "externalBrowser": true,
   "Desktop.Action.BROWSE": true,
   "externalBrowserMode": "desktop",
   "oa_internal_browser": "",
   "browseWebCmd": ""
  },
  "display": {
   "highContrast": false,
   "bounds": "Rectangle {0, 0, 1496, 967}",
   "dpi": "Point {72, 72}"
  },
  "aspect": 1.0206718,
  "theme": {
   "dark_debug": "",
   "org.eclipse.swt.display.useSystemTheme": "false",
   "theme": "dark",
   "is_dark": true
  },
  "table": {
   "col_width": 25,
   "2x": false,
   "col0Width": 25,
   "img_bounds": "Rectangle {0, 0, 14, 14}",
   "scale_down_1k": 500,
   "scale_up_1k": 2000
  },
  "swt_version": 4956
 },
 "region": "DE",
 "properties": {
  "oa_external": "",
  "os": "ProductName:\tmacOS\nProductVersion:\t12.6.8\nBuildVersion:\t21G725\n",
  "java.version": "11.0.15",
  "oa_ayce": "",
  "sun.jnu.encoding": "UTF-8",
  "locale": "LANG=\"de_DE.UTF-8\"\nLC_COLLATE=\"de_DE.UTF-8\"\nLC_CTYPE=\"de_DE.UTF-8\"\nLC_MESSAGES=\"de_DE.UTF-8\"\nLC_MONETARY=\"de_DE.UTF-8\"\nLC_NUMERIC=\"de_DE.UTF-8\"\nLC_TIME=\"de_DE.UTF-8\"\nLC_ALL=\n",
  "oa_internal_browser": "",
  "oa_packaging": "",
  "mac_arch": {
   "system_arch": "arm64",
   "java_arch": "aarch64",
   "macVenturaOnIntel": false,
   "macM1RunningIntelVersion": false,
   "platform": "mac_aarch64"
  },
  "file.encoding": "UTF-8",
  "oa_chromium": "",
  "SWT_GTK3": "null",
  "OPENAUDIBLE_HOME": ""
 }
}

**Comment by openaudible** [comment]
So you could try to maximize the window, close the app and restart and it should save the json and restore the window to that size when you reload. Check that the date modified on the windows json also updates?

**Comment by Bonbernie** [comment]
i have done this. But the size of the window is again small when I restart the app. The windows json has the actual date and time now, but thats it.

**Comment by Bonbernie** [comment]
i have now solved the problem by importing an older backup. i think i had somehow shot up the database with the settings.

**Comment by openaudible** [comment]
Still strange. We added some logging any time we hide or show the cover. In latest beta: https://openaudible.org/beta
