### ISSUE TITLE
Unable to authenticate with Audible via external browser.

### ISSUE THREAD

**Issue by rokejulianlockhart** [openaudible/openaudible#1261]
![image](https://github.com/openaudible/openaudible/assets/42837531/cecb7c60-224d-45a5-9214-19a2a9302186) ![image](https://github.com/openaudible/openaudible/assets/42837531/040e8359-18a8-46d5-8a5f-67cd3addb2fc)

**Comment by rokejulianlockhart** [comment]
After switching it to

![image](https://github.com/openaudible/openaudible/assets/42837531/225591bf-ef3c-45e3-9958-c6b0f05d31fc)

(because https://bugzilla.mozilla.org/show_bug.cgi?id=1852554#c0 might have affected it) simply nothing occurs.

**Comment by openaudible** [comment]
What OS are you using? If you send a link to an ISO I can attempt to reproduce.

**Comment by rokejulianlockhart** [comment]
https://get.opensuse.org/tumbleweed/ contains links to the relevant ISOs. You just need to choose whether you want a netinstaller (smaller) or self-contained image, and which arch to use.

**Comment by RokeJulianLockhart** [comment]
Works with https://software.opensuse.org/package/MozillaFirefox on cpe:/o:opensuse:tumbleweed:20230922.
