### ISSUE TITLE
Unable to authenticate with Audible using credentials.

### ISSUE THREAD

**Issue by rokejulianlockhart** [openaudible/openaudible#1262]
0.	![image](https://github.com/openaudible/openaudible/assets/42837531/430b91b4-b3e8-4dcd-9fe9-9307758b640b)

	Don't worry - the remnant hidden characters add to
	
	> Time to crack your password:
	> 41 thousand trillion trillion trillion trillion trillion years

	per https://www.passwordmonster.com/

	<details>
	
	![image](https://github.com/openaudible/openaudible/assets/42837531/0222cff6-933a-4257-a56f-627797e2509b)

	</details>

0.	![image](https://github.com/openaudible/openaudible/assets/42837531/6f0baa0a-5246-4430-89ec-2365a109da42)

**Comment by openaudible** [comment]
You can try logging on with the web browser interface. I don’t believe there is a max length for usernames or passwords…. But often you have to solve two captchas. See: https://openaudible.org/docs#login_errors

**Comment by RokeJulianLockhart** [comment]
> You can try logging on with the web browser interface.

@openaudible, I can't, due to https://github.com/openaudible/openaudible/issues/1261#issue-1890607529.
