### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by uulb** [openaudible/openaudible#1263]
I can't download some of my books. Error message: Asin [xxxx]is not eligible for AYCL. logging out and logging in to Audible account and restarting does not help. can anyone help? Thank you

**Comment by openaudible** [comment]
We spoke by support channel and this was resolved, somewhat mysteriously.. (It just started working). If anyone has the same issue, feel free to send a bug report from the About menu.  We might be able to see what the error is by looking at the full logs.
