### ISSUE TITLE
Podcasts are not shown and impossible to download

### ISSUE THREAD

**Issue by spawvn** [openaudible/openaudible#1265]
I got some podcasts via Audible Plus subscription, added all episodes to my Library, and I can see them in the Audible app (Screenshot 1), yet they are not picked up by OpenAudible as if they don't exist (Screenshot 2).

What I tried to no avail:
- restart OpenAudible
- full sync
- search podcast by name
- search sorted by "Added date"

![IMG_708F7BBE926A-1](https://github.com/openaudible/openaudible/assets/12695650/b3b9f16f-76a5-41c6-866f-beb96420da07)

![Screenshot 2023-09-18 at 13 21 19](https://github.com/openaudible/openaudible/assets/12695650/87cf7b53-d0c5-4484-8210-c263d7e46d5a)

**Comment by openaudible** [comment]
We haven't finished implementing podcasts yet. It is in progress.
