### ISSUE TITLE
Pile of To Convert Books

### ISSUE THREAD

**Issue by rnbwpnt** [openaudible/openaudible#1268]
v3.9 on an M2 Mac running Ventura 13.6 with 16g RAM.

The library is 17375 books (not a typo).

After loading the library, OA reports having 238 books in "To Convert," but all 238 are already-existing mp3 books. Selecting Convert to M4B forces OA to run the process, but nothing is actually converted, and no error is produced, and it doesn't clear "To Convert" either.

This is what remains after having approximately 1800 "To Convert" books, all of which were mp3s and which were converted to m4b, leaving me with both mp3 and m4b versions in my library (which is not desired).

I'm unable to understand where the conversion instructions came from; I first noticed it under 3.8.1.8b.

After further experimentation, it seems that this issue is blocking new downloads from Audible; OA detected ~35 new books on Audible but is not downloading them.

Guidance welcome.

**Comment by openaudible** [comment]
You could try to do a Controls: Refresh Files (F5) and see if anyting changes.
You can click on the "To Convert" status (or any other status) to see which books are in need of conversion.
You can select an individual book to see the status in the Book Info Panel. (It might say, ready to convert). 
If you think a book says "ready to convert" but you think it has an MP3, you can do a "Get Info" on the book and look at the files it has associated. 

If you get really stuck, after the file refresh, you can send a bug report under the help menu and reference issue 1268.

**Comment by rnbwpnt** [comment]
When I attempt a bug report I get:

Error: java.util.zip.ZipException: duplicate entry: books.json

**Comment by openaudible** [comment]
That's messed up. A bug in our bug reporter. 

Back to your bug... Make sure in Settings/Preferences that output format is set to what you want-- either MP3 or M4B as the default.

The logic is supposed to be "convert all" and any automatic conversion is only supposed to happen if you have no mp3 or m4b version. But we did add the ability to convert to both formats-- as some people usually like m4b, but might need an mp3 copy for a portable device that doesn't support m4b. I'll dig through the code and we're about to release a beta. 

And I've fixed the bug report bug. (Looks like that will happen if you have a books.json in your library as well as another directory, such as your temp directory.)

**Comment by rnbwpnt** [comment]
I've sent a log to support@openaudible.org. The log is what happens when I select my 278 books and select convert to m4b.

**Comment by openaudible** [comment]
Thank you. I think fixed in latest beta. 
https://openaudible.org/beta
Let me know if you find anything else.

**Comment by rnbwpnt** [comment]
Is there a way to find and delete undesired duplicates? I.e., delete mp3 is there is an m4b version, or vice versa?

**Comment by openaudible** [comment]
Perhaps export to excel and make a little formula to list the duplicates.

**Comment by openaudible** [comment]
OK. This should be fixed in the beta.. will be pushing out a 3.9.1 in a day or so.
