### ISSUE TITLE
Very long startup time that appears frozen for 10+ minutes

### ISSUE THREAD

**Issue by bilcorry** [openaudible/openaudible#1269]
I'm running the new v3.9.  It now has a very long startup time for my library (my library is very large).  From when I open the application to when it's finally ready is about 12 to 15 minutes.  It appears to hang/freeze during this time, and according to procmon, doesn't appear to be doing anything, but eventually does load if I leave it alone.

Here's what I see when it's frozen.  Windows will alert that the application has stopped responding and wants to know if I want to abort/quit.

<img width="434" alt="openaudible loading" src="https://github.com/openaudible/openaudible/assets/53133/dedfc295-adfc-4d82-9d5a-30398362a9a4">

Here's what I see in procmon.  It appears to check if files are on disk, then hangs for a bit with a couple of thread exits, then hangs for 10 minutes, then resumes doing stuff and eventually loads.

<img width="1136" alt="openaudible procmon" src="https://github.com/openaudible/openaudible/assets/53133/a5f4ba83-489c-433b-80d2-42daa8f19d3c">

There's a setting to "Refresh library on startup" which I had enabled.  So I disabled it and still have the same issue.

Thoughts?

**Comment by openaudible** [comment]
Hmm. The check to make sure a file is on disk is done fairly often, in case someone adds a book directly to the library. (Perhaps too often?) 
Is the library on a remote drive? Could the disk be having issues? (Slow read/write/access times?)
Its also possible you have an anti-virus program that notices OpenAudible trying to read the "books" directory and before it allows it to get a result, perhaps does some kind of friend/foe check?

**Comment by bilcorry** [comment]
My library is on a local disk, the same disk it's always been on.  It wasn't an issue in the previous version, so that made me think it was a change to the code.

Here's the disk speed test, seems fine?

```
C:\WINDOWS\system32>winsat disk -drive d
Windows System Assessment Tool
> Running: Feature Enumeration ''
> Run Time 00:00:00.00
> Running: Storage Assessment '-drive d -ran -read'
> Run Time 00:00:06.99
> Running: Storage Assessment '-drive d -seq -read'
> Run Time 00:00:08.38
> Running: Storage Assessment '-drive d -seq -write'
> Run Time 00:00:06.41
> Running: Storage Assessment '-drive d -flush -seq'
> Run Time 00:00:02.50
> Running: Storage Assessment '-drive d -flush -ran'
> Run Time 00:00:06.61
> Dshow Video Encode Time                      0.00000 s
> Dshow Video Decode Time                      0.00000 s
> Media Foundation Decode Time                 0.00000 s
> Disk  Random 16.0 Read                       2.58 MB/s          4.4
> Disk  Sequential 64.0 Read                   224.47 MB/s          7.4
> Disk  Sequential 64.0 Write                  170.75 MB/s          7.2
> Average Read Time with Sequential Writes     1.388 ms          7.4
> Latency: 95th Percentile                     14.912 ms          5.0
> Latency: Maximum                             25.271 ms          7.9
> Average Read Time with Random Writes         5.208 ms          5.9
> Total Run Time 00:00:31.28
```

Anti-virus hasn't changed.  Seems unlikely that's the issue.

Is there a way to downgrade?  If I downgrade and the problem goes away, then we know the issue has something to do with the new version.

**Comment by openaudible** [comment]
Disk report seems fine but no idea. 

Firewall may be set to be ok with older version but not newer. 

I would look for that log message similar to mine in the File: Console. You might see something else in it too— errors or unusual messages. 

Lots of users on new version and so far no similar reports. 

You can downgrade: 
https://github.com/openaudible/openaudible/releases

**Comment by bilcorry** [comment]
Here's the log:

```
Sep 25, 2023 4:49:04 PM org.openaudible.bookfiles.BookFiles _updateFileCache
INFO: 1) Refreshed file cache:28710 why force update active=false took 3511 ms. to complete.
Sep 25, 2023 4:49:04 PM org.openaudible.library.BookLibrary load
INFO: Loading D:\...\OpenAudible\books.json
Sep 25, 2023 4:49:07 PM org.openaudible.library.BookLibrary setNeedSave
INFO: Change to library, need save flag set
Sep 25, 2023 4:51:52 PM org.openaudible.bookfiles.BookFiles _updateFileCache
INFO: 2) Refreshed file cache:28710 why force update active=false took 3541 ms. to complete.
Sep 25, 2023 4:51:58 PM org.openaudible.bookfiles.BookFiles _updateFileCache
INFO: 3) Refreshed file cache:28710 why booksUpdated active=false took 3583 ms. to complete.
Sep 25, 2023 5:13:45 PM org.openaudible.audible.AudibleConnectionState connectionChanged
INFO: Connection state changed to Connected from Not_Connected
Sep 25, 2023 5:13:45 PM org.openaudible.audible.APIManager postInit
INFO: postInit API ready.
Sep 25, 2023 5:13:45 PM org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFO: applicationStarted took 1484.179 seconds to complete.
Sep 25, 2023 5:13:48 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Sep 25, 2023 5:14:54 PM org.openaudible.bookfiles.BookFiles _updateFileCache
INFO: 4) Refreshed file cache:28710 why booksUpdated active=true took 3524 ms. to complete.
```
You'll see it's reporting the startup to be 24 minutes.

The interesting thing is the file cache refresh ended at 4:51:58 and didn't take that long.  The "freeze" that occurs happened AFTER that.  If you look at the procmon, the app was checking if files exist until 4:52:00, then there's no Windows calls for 8 minutes, I'm guessing OpenAudible was doing something internally with all of the file checks it just performed?  There are a couple of threads created/destroyed in that timeframe.  Then 18 minutes after the file checks are done, it then loads a .jar file.

<img width="1762" alt="openaudible procmon 2" src="https://github.com/openaudible/openaudible/assets/53133/3616567a-10af-4ac8-aa7e-f16c25354e86">

I'll try downgrading and see if that clears up the issue.  Thanks!

**Comment by bilcorry** [comment]
Wow, using the previous version (v3.8.1), OpenAudible takes 15 seconds to load vs. 24 minutes.  I'm not sure what the difference is, other than when I use v3.9, it has a dialog showing it scanning every book in my library.  v3.8.1 doesn't do that.

Here's the log for v3.8.1: 

```
Sep 25, 2023 5:44:25 PM org.openaudible.library.BookLibrary load
INFO: Loading D:\...\OpenAudible\books.json
Sep 25, 2023 5:44:27 PM org.openaudible.bookfiles.BookFiles _updateFileCache
INFO: 1) Refreshed file cache:0 why  active=false took 1444 ms. to complete.
Sep 25, 2023 5:44:40 PM org.openaudible.audible.AudibleConnectionState connectionChanged
INFO: Connection state changed to Connected from Not_Connected
Sep 25, 2023 5:44:40 PM org.openaudible.audible.APIManager postInit
INFO: postInit API ready.
Sep 25, 2023 5:44:40 PM org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFO: applicationStarted took 14.973 seconds to complete.
Sep 25, 2023 5:44:43 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Sep 25, 2023 5:44:43 PM org.openaudible.desktop.swt.manager.VersionCheck displayUpdateResults
INFO: Version Check: An update is available!
Your version: 3.8.1
Release version:3.9
Add support for audiobook subdirectories in library. Fixes minor issues and adds many new features.
This a recommended upgrade and included with your license!
```

**Comment by openaudible** [comment]
Hmm. 28 seconds to scan 28k files is too long. Maybe you are running low on memory and there is some paging. How many books do you have? I can look at loading an extra large library— haven’t done that in a while.

**Comment by bilcorry** [comment]
My library has 13756 M4Bs and 1201 PDFs.

**Comment by openaudible** [comment]
Ok. That’s a big library. we added a new data structure for each book since the whole directory structure can be more complex . Probably using too much memory. Think there is an optimization we could do.  Will run some tests and get back. Appreciate the feedback!

**Comment by openaudible** [comment]
I am identifying some performance problems with very large libraries. Will have a beta shortly.

**Comment by openaudible** [comment]
Found a few performance issues that we fixed in first beta: https://openaudible.org/beta
