### ISSUE TITLE
ERROR - Asin is not elegible for AYCL

### ISSUE THREAD

**Issue by rhinoroo** [openaudible/openaudible#1270]
I am receiving "Error downloading: Asin [#########] is not eligible for AYCL

**Comment by openaudible** [comment]
What region are you in? Thank you for the report.

**Comment by rhinoroo** [comment]
Region is US

**Comment by openaudible** [comment]
We have heard of some rate limits.. but not positive how to identify. Reply or post a bug report from the Help Menu if they happen again.
