### ISSUE TITLE
Please consider adding an option to automatically run a "Quick Audible Library Sync" every day.

### ISSUE THREAD

**Issue by MammonLord** [openaudible/openaudible#1271]
It is possible to schedule an auto-run and force close with Windows Task Scheduler but it would be much more elegant to have an option within the app itself to automatically refresh the library periodically while it is running. A simple 24 hour timer to call the quick refresh function would be perfect.

Thank you for your consideration.

**Comment by openaudible** [comment]
There is a hidden feature for this.. Find your OpenAudible/settings.json file, edit it carefully with a text editor and change:
```
autoRefreshMinutes:0

to

autoRefreshMinutes:1440
```

Undocumented and unsupported.. but if you have any support questions, feel free to reply here.
