### ISSUE TITLE
Issues with Beta 3.9.0.2 - IMAC M1 - Safari -- V 17.0

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#1272]
My settings are for quick scan, autdownload new, auto convert to M4b and to auto generate the web page.

Scan is good, found a book to download, but did not trigger the download.

I manually triggered the download, which completed, but did not trigger the web page generation.

I trtiggered the web page gen and it worked fine.

All looks OK except that does not seem to respond to the conversion and web page generations automatically

**Comment by openaudible** [comment]
Thank you for the report. I think we fixed it in beta 3. At least we re-wrote a bunch of the code that handles library status and checking automation.

Thank you!

**Comment by openaudible** [comment]
Ok. Back in 3.9.1 production release. Thanks for the heads up!
