### ISSUE TITLE
Join Audio Files command missing in 3.9.0beta

### ISSUE THREAD

**Issue by Two-For-Mirth** [openaudible/openaudible#1273]
Hello! I just downloaded the 3.9.0beta and Join Audio Files is no longer available as a command under the File menu. Is this an accident or part of the new update? Dragging the directory over to combine as suggested in the documentation didn't seem to work either. It would be great to get that Join Audio Files feature back, if possible. Thank you!

**Comment by openaudible** [comment]
Yeah, that was an accident. Split by Chapter was supposed to be removed, since you can do it from the Action menu.
It might be back in beta 3, otherwise it will be in beta 4 that we're working on now.

**Comment by Two-For-Mirth** [comment]
Cool, thanks! Wasn't in beta 3, so I'll keep an eye out for beta 4.
