### ISSUE TITLE
Version 3.9.1 cannot find new purchase - MAC OS Sonoma 14.1 - IMAC M1

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#1276]
I bought the newest of the Cormoran Strike novels - it shows up in my library when using the Audible app, or using web access to the Audible page.

If I load OpenAudible, regardless of if I am logged in , or not (at which point I log in), neither the quick nor full scan can find the new book, nor any other new books. 

This book finding quirk is frustrating the fixes do not seem to be working on my IMAC, I have tried the current beta - same results.  The scenes (Full or Fast) seem to run slower than the last full release despite the claim that 3.9.1 is supposed to address scan speed.  

1. Console log attached after Running OA - already logged in
Oct 02, 2023 7:26:25 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 3.9.1 for cocoa swt 4962 jvm 18.0.2.1
Oct 02, 2023 7:26:25 PM org.openaudible.Directories load
INFO: Loading directories. These must be online and read/writable:
->{
 "ZIP": "",
 "META": "/Users/robertbarker/Library/OpenAudible",
 "APP": "/Applications/OpenAudible.app/Contents/Resources/app",
 "ART": "",
 "BOOKS": "",
 "BASE": "/Volumes/home/Audible-In",
 "MP3": "",
 "PDF": "",
 "WEB": "/Volumes/home/Audible-In/web",
 "TMP": "/Users/robertbarker/Library/OpenAudible/tmp",
 "AAX": "",
 "M4B": "",
 "M4A": ""
}
Oct 02, 2023 7:26:26 PM org.openaudible.Directories getPrefs
INFO: Loading /Users/robertbarker/Library/OpenAudible/settings.json exists=true size=571
Oct 02, 2023 7:26:26 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1677607277263
Oct 02, 2023 7:26:26 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 3.9.1 mac_aarch64
Oct 02, 2023 7:26:26 PM org.openaudible.desktop.swt.util.shop.PaintShop prefer2x
INFO: useHighDPI=false
Oct 02, 2023 7:26:26 PM org.openaudible.desktop.swt.manager.views.BookInfoPanel enableCover
INFO: set enableCover to false. resize event width=0
Oct 02, 2023 7:26:26 PM org.openaudible.desktop.swt.manager.views.BookInfoPanel enableCover
INFO: set enableCover to true. resize event good width=997
Oct 02, 2023 7:26:26 PM org.openaudible.Directories getPrefs
INFO: Loading /Users/robertbarker/Library/OpenAudible/settings.json exists=true size=571
Oct 02, 2023 7:26:26 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1677607277263
Oct 02, 2023 7:26:26 PM org.openaudible.audible.AudibleConnectionState setRegion
INFO: Setting audible region to CA
Oct 02, 2023 7:26:26 PM org.openaudible.library.LibraryManager run
INFO: activating: /Volumes/home/Audible-In [
 {
  "path": "/Volumes/home/Audible-In",
  "kind": "BASE",
  "exists": true,
  "enabled": true
 },
 {
  "path": "/Volumes/home/Audible-In/books",
  "kind": "BOOKS",
  "exists": true,
  "enabled": true
 },
 {
  "path": "/Volumes/home/Audible-In/web",
  "kind": "WEB",
  "exists": true,
  "enabled": true
 },
 {
  "path": "/Users/robertbarker/Library/OpenAudible",
  "kind": "META",
  "exists": true,
  "enabled": true
 },
 {
  "path": "/Users/robertbarker/Library/OpenAudible/tmp",
  "kind": "TMP",
  "exists": true,
  "enabled": true
 },
 {
  "path": "/Applications/OpenAudible.app/Contents/Resources/app",
  "kind": "APP",
  "exists": true,
  "enabled": true
 }
]
Oct 02, 2023 7:26:43 PM org.openaudible.bookfiles.BookFiles _updateFileCache
INFO: 1. Refreshed file cache:3212 files. [] took 16.755 seconds to complete.
Oct 02, 2023 7:26:43 PM org.openaudible.library.BookLibrary load
INFO: Loading /Volumes/home/Audible-In/books.json
Oct 02, 2023 7:26:43 PM org.openaudible.library.BookLibrary setNeedSave
INFO: Change to library, need save flag set
Oct 02, 2023 7:26:44 PM org.openaudible.audible.AudibleConnectionState connectionChanged
INFO: Connection state changed to Connected from Not_Connected
Oct 02, 2023 7:26:44 PM org.openaudible.audible.APIManager postInit
INFO: postInit API ready.
Oct 02, 2023 7:26:44 PM org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFO: applicationStarted took 17.667 seconds to complete.
Oct 02, 2023 7:26:44 PM org.openaudible.desktop.swt.manager.AudibleGUI lambda$applicationStarted$2
SEVERE: Starting autoConnect
Oct 02, 2023 7:26:44 PM org.openaudible.desktop.swt.manager.AudibleGUI lambda$applicationStarted$2
SEVERE: Unexpected error with autoConnect
org.eclipse.swt.SWTException: Invalid thread access
	at org.eclipse.swt.SWT.error(SWT.java:4918)
	at org.eclipse.swt.SWT.error(SWT.java:4833)
	at org.eclipse.swt.SWT.error(SWT.java:4804)
	at org.eclipse.swt.widgets.Display.error(Display.java:1209)
	at org.eclipse.swt.widgets.Display.checkDevice(Display.java:708)
	at org.eclipse.swt.widgets.Display.getActiveShell(Display.java:1372)
	at org.openaudible.desktop.swt.gui.progress.ProgressDialog.getDefaultShell(ProgressDialog.java:67)
	at org.openaudible.desktop.swt.gui.progress.ProgressDialog.doProgressTask(ProgressDialog.java:81)
	at org.openaudible.desktop.swt.manager.AudibleGUI.refreshLibrary(AudibleGUI.java:355)
	at org.openaudible.desktop.swt.manager.AudibleGUI.lambda$applicationStarted$2(AudibleGUI.java:1108)
	at java.base/java.lang.Thread.run(Thread.java:833)

Oct 02, 2023 7:26:47 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Oct 02, 2023 7:26:52 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

I tried to logout, then log in, then run a full scan - this fails with a Visual Device Error - why, despite the fact that I have no program options set, does to offer to do a full scan???

**Comment by rsr-at-mindtwin** [comment]
same issue here

**Comment by openaudible** [comment]
Fixed in 3.9.4 and above.
