### ISSUE TITLE
Table View

### ISSUE THREAD

**Issue by letternews** [openaudible/openaudible#1278]
It would be very helpful to have the possibility to View media format (mp3, m4b) in the table view. Also there should be an option to see the date and time of import.
Thanks

**Comment by openaudible** [comment]
That gets a little tricky. (Especially when you have a direcotry audiobook that might contain any number of audiofiles.) 
You can export as CSV, Excel, json, or read the books.json file to determine this.. but will file it as a feature request.
Why do you need to know when you imported it, versus when you bought the book? (I believe if you import a book that you didn't buy through audible, that will be set as the "purchase" date.)
