### ISSUE TITLE
V3.9.3 - Still not finding new book purchases - IMAC M1 -  Sonoma 14.1

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#1280]
Loaded new 3.9.3 - logged out/logged in - goes through process to list books etc - at the end suggests I log on (1 am already connected, but disconnect and reconnect, yet again).

Accept the full library says - it does this and competes the process saying I have 1528 books to download,and that I have 1544 M4b (which are listed). The new book which is up there on my Audible library does not show up in M4b in any way or form.

How do I get back to a fully working version of OA?  Too frustrating to have this still unfixed!  I have no interest or time to download 1500 plus books if I have no confidence at all that the app will work!!

Why - I ask this again - since I have no settings set (with the exception of the library location) - why does the app do a scan on startup automatically????

**Comment by oboe45** [comment]
Not sure but F5 then refresh seemed to work, the two new purchases showed
up and have now been downloaded.
For safety, I am downloading all of the AAX that I previously deleted.  So
far (about 80% of 1600) have downloaded and there does not seem to be any
cap on download so far ( I know this has been discussed a couple of times).

Any changes planned in the web page generation?  Would love to see a way to
select the colums to be populated - series and number within series would
be handy on the web page, plus a workable security process to protect
access to the page (yes, I know it is relatively easy tor users to add
this, but this 77 year old ex-IT manager cant figure it out!)

Thanks for the efforts, apologies for my rudeness.

**Comment by openaudible** [comment]
We are now doing an "F5" refresh at every library load. If it fails we don't do the auto-convert.
No worries.. that wasn't our best release. Had some errors that crept in at the last minute... Appreciate your feedback as always.
