### ISSUE TITLE
Version 3.93   -  on Mac M1 - Sonoma 14.1 - exception when trying to generate Web Page

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#1282]
Just when it all seemed to work, now I cannot generate the web page

Last part of console output follows:

Oct 03, 2023 6:01:51 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 10712397 to disk:/Users/robertbarker/Library/OpenAudible/tmp/saved_books.json
Oct 03, 2023 6:01:51 PM org.openaudible.library.BookLibrary save
INFO: Saved books /Volumes/home/Audible-In/books.json length 10712397 took 773 ms. to complete.
Oct 03, 2023 6:02:03 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Export_Web_Page
Oct 03, 2023 6:02:03 PM org.openaudible.desktop.swt.manager.ImportExport run
SEVERE: pageBuilder build page failed:
java.lang.NullPointerException: Cannot invoke "java.io.File.exists()" because "src" is null
	at org.openaudible.feeds.pagebuilder.WebPage.buildPage(WebPage.java:194)
	at org.openaudible.desktop.swt.manager.ImportExport$PageBuilderTask.run(ImportExport.java:1477)

Oct 03, 2023 6:02:03 PM org.openaudible.desktop.swt.manager.AudibleGUI showError
SEVERE: building web page
java.lang.NullPointerException: Cannot invoke "java.io.File.exists()" because "src" is null
	at org.openaudible.feeds.pagebuilder.WebPage.buildPage(WebPage.java:194)
	at org.openaudible.desktop.swt.manager.ImportExport$PageBuilderTask.run(ImportExport.java:1477)

Oct 03, 2023 6:02:03 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: Error
An error has occurred. Check File>Console for more details.
3.9.3
java.lang.Exception: Error building web page.
Cannot invoke "java.io.File.exists()" because "src" is null
	at org.openaudible.desktop.swt.gui.MessageBoxFactory.showError(MessageBoxFactory.java:46)
	at org.openaudible.desktop.swt.manager.AudibleGUI.showError(AudibleGUI.java:701)
	at org.openaudible.desktop.swt.manager.ImportExport$PageBuilderTask.run(ImportExport.java:1482)

Oct 03, 2023 6:02:03 PM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {Creating Your Audiobook Web Page} [layout=GridLayout {numColumns=2 marginWidth=12 marginHeight=21 horizontalSpacing=14 verticalSpacing=8}] visible=true input shell:Shell {OpenAudible} [layout=GridLayout {}]
Oct 03, 2023 6:02:03 PM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {Creating Your Audiobook Web Page} [layout=GridLayout {numColumns=2 marginWidth=12 marginHeight=21 horizontalSpacing=14 verticalSpacing=8}] visible=true input shell:Shell {OpenAudible} [layout=GridLayout {}]
Oct 03, 2023 6:02:07 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:Error body:An error has occurred. Check File>Console for more details.
java.lang.Exception
 Error building web page.
Cannot invoke "java.io.File.exists()" because "src" is null response:BUTTON_OK
Oct 03, 2023 6:05:01 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by openaudible** [comment]
Fixed in beta: https:/openaudible.org/beta
Thank you. (This release wasn't our best.)

**Comment by oboe45** [comment]
Thanks - works fine in this beta
