### ISSUE TITLE
Crash loading web views

### ISSUE THREAD

**Issue by aaronmitti** [openaudible/openaudible#1283]
I'm getting a crash when most web views load (connect / login), I tried latest version and beta. I sent the crash report, I'm not sure if you get that. There was an XML log file in tmp but didn't look super helpful, where else is this logging?

**Comment by openaudible** [comment]
Can you make sure you're using the latest version? We had a few bugs that affected some people... 
Just get the latest from our web page and install over any older version.

**Comment by aaronmitti** [comment]
I just upgraded the OS to the new release (Sonoma) and that fixed it! There may be issues on the old Ventura OS. Anyhow, I'm good now, thanks!
