### ISSUE TITLE
Summary screen after stature V3.9.4 MacM1 Sonoma 14.1

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#1287]
After startup - which seems to work fine, although I have no idea what it is doing since all options are turned off, (a startup used to be instantaneous) - the Summary Screen says "To sync your audible library, select 'Connect to Audible' from the 'Controls' menu".  

The Connect to Audible option on the Controls menu is disabled (since I am already connected to Audible), Why is it offering a sync, this has already been done during the longish startup - is the message correct, or spurious??

**Comment by openaudible** [comment]
That's a bug. Will fix for next version. Thank you.

**Comment by openaudible** [comment]
Thank you.
Think fixed in latest beta: https://openaudible.org/beta

**Comment by openaudible** [comment]
Fixed in 3.9.6
