### ISSUE TITLE
Option to automatically convert audio files not working 

### ISSUE THREAD

**Issue by derekgottlieb** [openaudible/openaudible#1288]
I have the option to automatically convert audio files enabled and it used to work, but it seems like it stopped working with one of the recent upgrades (using 3.9.4 currently). After downloading, it leaves all files as AAX format with the “to convert” status. I’ve tried toggling it off and on but it doesn’t seem to have an effect. 

When I manually initiate the conversion to M4B, the option to automatically delete AAX files works as expected.

**Comment by openaudible** [comment]
Thank you.
Think fixed in latest beta: https://openaudible.org/beta

**Comment by derekgottlieb** [comment]
I confirmed this appears to be working again in the 3.9.4.1beta. Thanks!
