### ISSUE TITLE
Free Title Not Syncing

### ISSUE THREAD

**Issue by misterhamm** [openaudible/openaudible#1291]
As far as I can tell, books added to my library that are included with the subscription (so no actual purchase) aren't syncing. Is that expected? I have about 225 books in my library but OpenAudible only shows 114.

**Comment by oboe45** [comment]
I have a lot of "Free" and "Included" books added in my Audible library and
they sync OK with use of OA once they are downloaded and converted to M4b
by the OA App

**Comment by openaudible** [comment]
Make sure you're connected to the correct account (says "Connected: Yes" in the Library Status Panel.) and that you've done a full resync. You should see all your titles. Make sure "Ignored: 0" is in library status. Currently podcasts are not downloadable. More troubleshooting in the docs. Feel free to send a note to support through our web site contact form.

**Comment by openaudible** [comment]
Podcasts supported in 4.2. 
https://openaudible.org/docs#podcasts
