### ISSUE TITLE
iCloud Drive symlinks not recognized, resulting in unlimited archive re-downloads, filling 100% disk space

### ISSUE THREAD

**Issue by vahle** [openaudible/openaudible#1294]
If the OpenAudible directory is placed anywhere in an iCloud Drive directory (by default on most macOS machines), the system will automatically remove local copies of files from the User's machine. 

Under normal use, the 'files' are visible to the user, but are really just ~symlinks that activate the cloud retrieval process. The system will download the files from iCould when a user attempts to access them. **OpenAudible does not recognize this process**, and instead sees the files as missing from the User's audiobook archive, so every time one opens OpenAudible it attempts to re-download the user's entire audiobook catalog. 

This results in duplicates of every library item -- which are then offloaded to prevent disk space filling -- thus incurring another re-download.

**Comment by openaudible** [comment]
Ack. Good old Apple. This is a first report. May need to investigate.

**Comment by oboe45** [comment]
> If the OpenAudible directory is placed anywhere in an iCloud Drive directory (by default on most macOS machines), the system will automatically remove local copies of files from the User's machine.
> 
> Under normal use, the 'files' are visible to the user, but are really just ~symlinks that activate the cloud retrieval process. The system will download the files from iCould when a user attempts to access them. **OpenAudible does not recognize this process**, and instead sees the files as missing from the User's audiobook archive, so every time one opens OpenAudible it attempts to re-download the user's entire audiobook catalog.
> 
> This results in duplicates of every library item -- which are then offloaded to prevent disk space filling -- thus incurring another re-download.

Once this has been resolved, could someone post a short set of instructions on how to set up Openaudible so that it works with required files in iCloud?  My brain cannot figure out to do this without some help!

**Comment by openaudible** [comment]
Reading the below link it looks like watching out for .iCloud files will be something that we can do programmatically. 

https://apple.stackexchange.com/questions/328329/is-there-a-way-via-the-command-line-to-cause-icloud-files-to-download

for the time being, it is not recommended. Will work on it this week.

**Comment by openaudible** [comment]
Did a little research. Most things are working as expected. So I may need more help reproducing the problem.

So if I see artwork or a file "not on disk" and try to access it (by viewing the book and looking at the artwork, or selecting "reveal title.m4b" ) it should work as expected. Double clicking it should download it and start playing it in "Books.app".

A few things to try... Make sure your OS is up to date. Perhaps older systems use this .icloud file. I haven't seen those. Nor have I been able to identify any files as "symlinks".

Use Terminal to run:

```brctl monitor```
 
That will list all files and you'll see some that are "not downloaded". Running openaudible to download or convert files should cause the output to update. Watch for errors. 

However.... Running out of local storage or iCloud storage will really mess things up.. Once either is at capacity, everything appears to break. So this is still not recommended for most situations. An external drive is the best bet, and perhaps use the Manage Libraries to make a backup to iCloud..)

If you're seeing an issue, let us know the Mac OS version, and if you see any errors in ```brctl log```
If you select a book that is causing problems, do a "Get Info" and select the "Files" tab. That should show you which files we think you have. If there is an file.AAX, obviously it shouldn't attempt to download them again. 

You may want to turn off automatic downloads and conversions in preferences. (Its pretty easy to select a few or all and right-click download/convert.)

Keep me posted.

**Comment by openaudible** [comment]
Did not fix. Unable to reproduce on MacOS Sonoma. Feel free to send details.
