### ISSUE TITLE
Auto Fill not working with 2.9.5 windows

### ISSUE THREAD

**Issue by Hazado** [openaudible/openaudible#1295]
Get Info - Enter website - Auto Fill button - No changes to information entered.

**Comment by openaudible** [comment]
Look at the file menu: console. Maybe no new info from audible? Or ? What audible region are you in? Send a sample ASIN.

**Comment by Hazado** [comment]
[log.txt](https://github.com/openaudible/openaudible/files/13127783/log.txt)
Here is the log file
I imported the file manually, added the link from audible to the book URL and hit the auto fill button.
Nothing changed.

US Region
https://www.audible.com/pd/Tales-of-Dune-Expanded-Edition-Audiobook/B07DGLLH4D?qid=1698184041&sr=1-1&ref_pageloadid=not_applicable&ref=a_search_c3_lProduct_1_1&pf_rd_p=83218cca-c308-412f-bfcf-90198b687a2f&pf_rd_r=C9P2KM29QZW1JNV2XVTN&pageLoadId=GJiioAqJi0NOviNG&ref_plink=not_applicable&creativeId=0d6f6720-f41c-457e-a42b-8c8dceb62f2c

**Comment by openaudible** [comment]
Should be fixed in 3.9.6. Thank you.
