### ISSUE TITLE
Some M4B files do not play on iPod Video V 5.5

### ISSUE THREAD

**Issue by Mchass** [openaudible/openaudible#1296]
Hi

I am trying to breathe new life into my beloved iPod Video V5.5 because paying huge premiums for more storage with each new iPhone isn’t sustainable. 

My iPod Video V5.5 has been upgraded to 512GB, from 80GB. My music, and old AA files play fine as do SOME OpenAudible M4B converted files. Note that the old iPod does not support AAX files, which is the only thing I can download from Audible anymore, and thus requires conversion to a supported format. The specs for the iPod Video V5.5 show that it does support M4B.

The M4B files that do not play the book content, sound like dragging the needle back and forth on an old LP record. (Yeah, I’m that old.) Interestingly and frustratingly, the Audible lead-in “This is Audible.” plays clear as a bell. Is it possible that the M4B format has changed over the years? The new M4B files that fail on iPod, do play on my iPhone, iPad and MacBook. In OpenAudible, I notice there are no format options available for converting to M4B like there are for MP3.

1. Are there some hidden M4B format options in OpenAudible that I have missed?
2. Do you know if the M4B decoder built into the iPod is hardware or firmware driven? If firmware driven, do you know if installing ROCKBox has an “updated” M4B decoder and might work with OpenAudibles converted files?
3. Do you have any suggestions for a newer, pocketable M4B player? I have been fruitlessly searching the internet for such a player and haven’t found one. There have been several that have listed 7 to 10 supported formats, none of which is M4B, but also state “and more formats”. But looking for the actual specs of these devices does not add any clarity. 

Thank you for any help or guidance you can provide.
Terry

**Comment by openaudible** [comment]
Have not heard of that. Can you see if there is a firmware update? It is from 2005, so not terribly surprising if things have changed.  

There are no settings additional settings for m4b. I don't know ROCKBox and can't recommend it. 

I would recommend switching to MP3 format.

It could be the length of the file (fails if too big) or it could be the sample rate might be different on incompatible files.)

You could try renaming the file from .m4b to .m4a and try it (if over 10 hours or so).

MP3 is the best bet for your old player!

Feel free to post what you find.
