### ISSUE TITLE
Summary Window Size

### ISSUE THREAD

**Issue by jschlade** [openaudible/openaudible#1297]
It would be nice if the app remembered the size of the summary window.

Every time I start the app this is the first thing I do. I adjust the size of this window. Super annoying.

Thanks

**Comment by openaudible** [comment]
It should be saved in the windows.json file. Will check. What OS are you on?

**Comment by jschlade** [comment]
I have this problem on Windows and Macs.

I don’t remember it ever saving the size of this window.

**Comment by openaudible** [comment]
Confirmed your bug. For some reason the code to save the "sash height" was commented out. Will put it back in for the next release. Thank you for the heads up.

**Comment by jschlade** [comment]
Thank you for fixing this. :-)

**Comment by openaudible** [comment]
Fixed in 3.9.6. Thank you.
