### ISSUE TITLE
Save column order in the bottom section when application exists.

### ISSUE THREAD

**Issue by yurikus** [openaudible/openaudible#1298]
Presently column order is not saved, only sort order upon exiting the application. For example I want series name to be the second column. I drag it into second position, exit the application. On the next start series name is back at its original position, next to last.

Win10 22H2 19045.3570

**Comment by openaudible** [comment]
It is supposed to save to a json file when you quit. I will try to reproduce.

**Comment by openaudible** [comment]
You are correct-- we broke that. 
Fixed in beta: https://openaudible.org/beta

**Comment by openaudible** [comment]
Fixed in 3.9.7
Thank you.
