### ISSUE TITLE
[Feature Request] Option to Organize media by Author

### ISSUE THREAD

**Issue by OttScott** [openaudible/openaudible#1299]
After converting audio, all files are in same folder. This makes managing the local versions of these files convoluted, especially as I use another program (Audiobookshelf) to manage my audio, which requires files sorted by author in folders.

I suggest a setting, either by default or optional, that would organize the downloaded and converted media directly into folders by author.

IE, instead of '\<library>\audibleimports\\**books**\Fahrenheit 451.mp3', it would become '\<library>\audibleimports\books\\**Ray Bradbury**\Fahrenheit 451.mp3'.

**Comment by openaudible** [comment]
We are working on that.. but a lot of books have multiple authors. Sometimes authors are listed with different names (with or without a middle initial, for instance) so it becomes unwieldy and counter-intuitive.. Several similar feature requests have been made.
