### ISSUE TITLE
Add extra troubleshooting tip

### ISSUE THREAD

**Issue by Pisi-Deff** [openaudible/openaudible#13]
Hello,

I spent around 2 hours today debugging trying to figure out why the tool was not able to find any books in my Audible library.

Finally because of a reddit post, figure out that this damn setting here needs to be disabled for download links to actually appear on the library page.
![image](https://user-images.githubusercontent.com/1923619/42111659-d17f072c-7bed-11e8-81e6-4839cfd444c2.png)

I believe it would be a good idea to add this information to the main project page.

**Comment by openaudible** [comment]
Awesome catch. Fixed in 1.1.3.
