### ISSUE TITLE
Source code not available: Missleading project name, documentation and license

### ISSUE THREAD

**Issue by aurelf** [openaudible/openaudible#130]

**Comment by aurelf** [comment]
(Sorry, issue posted before complete by mistake)
It seems that the previous requests for source have been declined (like issue #105). 
Too bad you want to make it proprietary, but your choice. 

However, currently:
- project name is misleading
- documentation is misleading
- git is out of date 
- releases are including download links for old code 
- project license is incorrect
It seems you are abusing github as a file hosting / bugtracking, and making people waste their time trying to download and compile the project. Please clarify the readme at least?

**Comment by openaudible** [comment]
Will update readme.

**Comment by C0rn3j** [comment]
Would be nice to also update the license, because this project is all rights reserved from the looks of it, not Apache 2.0.

**Comment by C0rn3j** [comment]
> There are no restrictions against commercial use and the Apache 2.0 license.

Are you saying the current OpenAudible version (4.1.1 at the time of writing), is licensed under Apache 2.0, and Apache 2.0 does not only apply to the old version whose source code is available in the repository, but to both?

My issue is with using the open source repository for hosting proprietary software under a different license, and it is mighty confusing at first read, and the name does not help.
