### ISSUE TITLE
Library Status Pane too Narrow for all digits

### ISSUE THREAD

**Issue by OttScott** [openaudible/openaudible#1300]
Library Status Panel is too narrow to show totals over 2 digits wide. Please see attached screenshot under Converting. 

As I have over 300 titles, when converting, I'd like to have a better sense of how far along I am. As such, I'd also like to request an estimated time to go of batch conversions. Perhaps based on MB / sec converted so far after the first few completions?

![image](https://github.com/openaudible/openaudible/assets/14189124/65386baa-1b40-4d45-b249-dd3d0407c10d)

**Comment by openaudible** [comment]
I think if you grow the window and restart the app it will fix that. The GUI does its best to fit everything in and sometimes gets confused by smaller windows/monitors.

**Comment by OttScott** [comment]
My monitor size is 1920x1080. Don’t think this the expected behavior is it?
I’d consider it a valid bug but you can decide you Won’t Fix if you want…

**Comment by openaudible** [comment]
will try to fix. It is hard to reproduce. I think I’ve seen it if we make the main window small, quit and restart the app. So I was trying to say you might be able to make the main window bigger and restart the app. It isn’t ideal. 

Are you on windows?

**Comment by openaudible** [comment]
I made a change in the latest beta:
https://openaudible.org/beta
Let me know if that fixes it.

**Comment by bilcorry** [comment]
I had a related issue where the PDF total was getting cut off:

> ![image](https://github.com/openaudible/openaudible/assets/53133/d579fe86-5c93-40c2-8b77-d1a2e425981b)

I can confirm with the latest beta that the problem is resolved.

> ![image](https://github.com/openaudible/openaudible/assets/53133/2924150b-19fc-4e78-80ac-fa49884872bd)

Thanks!

**Comment by openaudible** [comment]
Any feedback on using the beta?

**Comment by feldegast** [comment]
i am using 3.9.7.1 and i set the application to the narrowest width before restarting it to see if there was an issue, it displays fine for me but i only have 16 PDFs in my library the over 7000 books display fine

**Comment by openaudible** [comment]
I think we finally figured out what we were doing wrong.. out... try 4.0.1 or https://openaudible.org/beta
