### ISSUE TITLE
Unable to convert to Mp3 or even download Audible books in Open app 

### ISSUE THREAD

**Issue by bquadrant** [openaudible/openaudible#1301]
Had not logged into the app in months. 

Went to download several new books I bought with audible credits over the past months. None of the new books I tried would finish downloading much less work to be converted to mp3s. 

Some older books worked but nothing from the past 4-6  months it appears. I keep getting errors when attempting to download. 

It used to get to the end of a book download and fail, now it just fails right away. Open and closed the app, and rebooted also. Refreshed the library as well. 

None of these are the + plus books that are included for anyone on audible, (dont think OpenAudible works for those unless that is part of the new release)

What am I missing? thank you

![Screenshot 2023-11-05 at 7 58 25 AM](https://github.com/openaudible/openaudible/assets/149957244/72c54271-20a8-4ab1-b895-f9c9b2739413)

![Screenshot 2023-11-05 at 9 12 53 AM](https://github.com/openaudible/openaudible/assets/149957244/92c82bd9-df0a-402b-a828-e8590be1abdb)

![Screenshot 2023-11-05 at 9 16 36 AM](https://github.com/openaudible/openaudible/assets/149957244/eadf5d40-d6d8-41c8-a711-e947d5f9c380)

**Comment by openaudible** [comment]
This could be a few things:

You're logged into the wrong account for the book you're trying to download. We always recommend connect, full rescan, and download all books. 

You're using an out of date version of OpenAudible.  Audible periodically changes the way requests for downloads work. If you select About: Check for Updates, it should take you to a web page with free and paid options for upgrading.

**Comment by bquadrant** [comment]
Thank you for your response.

Yes I have paid for the license in the past but due to logging in issues w Open and security on the Amazon side. So I have not been able to use it much and wasn’t sure I wanted to pay to upgrade it.

If there is free options to update I am happy to consider doing that, though I am sure that wont bring it the latest updated version since that is paid right?

Only one account, I share an account with my business partner who moved from the US to Germany, so any time I am going to log out or anything I have to make sure she is ready if it asks for text verifications.

I thought about firing up a new account for me but as I remember when I got the software it only did one account.

For a long time we have been buying books in this account so….I kinda need to be able to log in etc.

Kurt Walker

**Comment by bquadrant** [comment]
So I looked the options but it appears that there is no guarantee that updating to another paid version will not necessarily guarantee a fix? Thank you

Kurt Walker

**Comment by bquadrant** [comment]
I went ahead and purchased the product again.

Which worked for some titles and up to a point:

Thoughts?





Kurt Walker

**Comment by bilcorry** [comment]
You might try renaming your OpenAudible folder to "backup" or whatever, then try running OpenAudible as if it were brand new.  Another thought is if you're sharing an account with someone in another country, maybe Audible is blocking the sharing of the account?

**Comment by openaudible** [comment]
Sorry for the late reply. If you select a book and attempt to download it, there should be an error if there is any problem downloading it. You can contact our support if you want to provide additional details. (Try not to post any https download URLs to this page.)

**Comment by feldegast** [comment]
If you purchased audiobooks from one of the audible servers and then tried to download that audiobook while being logged into a different audible server in some cases the audiobook will not download
I have audiobooks purchased through 3 different audible servers so I have to connect to different audible servers to download all my audiobooks
it also fails if there is insufficient disk space to download the audiobooks

**Comment by bquadrant** [comment]
I will try this but I am pretty sure I was logged into the right account to get these particular books because I thought of that.

Kurt Walker
