### ISSUE TITLE
Pulling information from audible.co.uk instead of audible.com

### ISSUE THREAD

**Issue by 777black777** [openaudible/openaudible#1303]
Harry Potter audiobooks in the US are read by Jim Dale. Harry Potter audiobooks from the UK are read by Stephen Fry. I have both versions and I would like to put in the ASIN and use the Auto Fill button to populate all the information for the Stephen Fry UK version. However, I noticed that when using the ASIN, it attempts to pull from audible.com and is able to pull a bit of the information, but not everything. I have to manually change the Book URL link from audible.com to audible.co.uk and manually add the Narrated By plus a few other properties. I know this is a very very niche issue, but I was hoping to have a way to have the UK details pulled in properly. No worries if it isn't possible or is just too niche, but thought I'd put it out there.

I'm reading previous issues where people are located in the UK or in CA, but I do not want to change my region, just temporarily want to use the ASIN from the audible.co.uk to pull down the correct audio book details.

Thank you for all the amazing work you've put into this product.

**Comment by openaudible** [comment]
It does look like we try to get the US version and your regional version. Then choose the best set of information.

Let us know the ASIN you're trying to access. 

I would have thought that the narrated by field wouldn't change regardless of which region you pull the info from.

Can you do an auto-fill when connected to your UK account.. and look at the File: Console and search for the phase:
"bestProduct info" You can copy and paste it into an email to us using our web contact form.

**Comment by openaudible** [comment]
Fixed in 3.9.7
Thank you.
