### ISSUE TITLE
import directory

### ISSUE THREAD

**Issue by Gerry5100** [openaudible/openaudible#1304]
If you select import directory and there are no files recognized in the selected directory you get a dialog box stating no files.  However, you have no exit option -- endless loop.

**Comment by openaudible** [comment]
Confirmed. Will fix for next beta. Thank you!

**Comment by openaudible** [comment]
Fixed in today's beta:
https://openaudible.org/beta

**Comment by openaudible** [comment]
Fixed in 3.9.7
Thank you.
