### ISSUE TITLE
Able to download Audible file of purchased book, but unable after highlighting it to convert to MP3.

### ISSUE THREAD

**Issue by RDMcclintock** [openaudible/openaudible#1305]
Able to download Audible file of purchased book, but unable after highlighting it to convert to MP3. The convert option is greyed out.

**Comment by openaudible** [comment]
What color is the icon next to the book? If it is green, the book is already converted to mp3. You should be able  to select it and Action Menu: Reveal Menu: Reveal Filename.mp3

**Comment by openaudible** [comment]
It’s probably already converted. If not reply.
