### ISSUE TITLE
Error downloading: Cannot invoke "org.json.JSONObject.toString(int) because it is null

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#1308]
tried to download 3 audiobooks but got the above error for 2 books, 1 book did download

**Comment by openaudible** [comment]
Can you copy and paste the whole error (stack trace) from the file: Console log window? 
also let me know what version you’re using. Thanks!

**Comment by feldegast** [comment]
based on the audiobook codes i may need to switch servers to download them (change from US to AU) but a null error is not as friendly as saying "please log into a different server"....

**Comment by openaudible** [comment]
Thank you. Got the error. Will fix.
The request for license had already failed, but we added an error in the reporting that made it worse. 
So the book is probably no longer available in the connected user's account. 
Truncating your log above. Thank you!

**Comment by openaudible** [comment]
Fixed in 3.9.7.1 
Thank you!
