### ISSUE TITLE
Unable to check for updates

### ISSUE THREAD

**Issue by Plaenkler** [openaudible/openaudible#1309]
It seems that the latest hotfix breaks the version check because a fourth decimal place was added, which is not typical for Semver.
I only had the error once and couldn't take a screenshot. 
Everything worked the second time I started the software. However, the error message criticized the formatting with too many dots.

**Comment by feldegast** [comment]
in 3.9.7.1 it says it is the current version and i don't see the error
i was using 3.9.7 on windows 64bit
i will have to see if i get the error again but i am unable to reproduce the eror in the latest version

**Comment by openaudible** [comment]
Ok. Will review. Thank you.

**Comment by Plaenkler** [comment]
> Can you send a copy of the error in the File: Console menu? Also what version you’re using? can’t reproduce but wouldn’t be surprised if there is a bug somewhere. Check firewall too.

I can not provide the file`s contents it nearly empty after reinstalltion

Sry :/

**Comment by openaudible** [comment]
Hmm. It might be because the version has 4 semver numbers -- 3.9.7.1. But I can't seem to reproduce. If it shows up for anyone, just go to the File: Console, and copy and paste the error message (it can be several lines long.)
