### ISSUE TITLE
RPM doesnt install - does not verify no digest

### ISSUE THREAD

**Issue by abradshaw** [openaudible/openaudible#131]
Hi 

Thanks so much for creating this but I cant install the RPM on my Fedora system - I get this error

```
Total size: 60 M
Installed size: 136 M
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Error: Transaction check error:
  package OpenAudible-1.5.0-1.i386 does not verify: no digest
```

Can wait to try this

**Comment by abradshaw** [comment]
This seems to be the issue

https://stackoverflow.com/questions/53494925/install4j-missing-digest-in-rpm-archives

**Comment by openaudible** [comment]
Install4j also produces the .sh file, which may work better. I don't know-- I'm not a linux on the desktop guy. 

You might also be able to uncompress the .rpm or .deb file manually-- all files needed are in one "OpenAudible" directory and there should be one executable. Feel free to post a followup on how you solve it! :)

**Comment by abradshaw** [comment]
Yeah, those will disable sig checks but still wont let it install

--nodigest  however will disable the digest check :-)

I think the ultimate "cure" will be to use the newer install4j version - the post above has a reply staying ...

"As of install4j 7.0.8, the digest is done with MD5 which is no longer acceptable in recent versions of rpm. This will be fixed in install4j 7.0.9 where SHA-1 and SHA-256 signatures will be generated as well.

Please contact support@ej-technologies.com to get a build where this is already implemented."

Hope this helps some people

**Comment by adatum** [comment]
Thanks, I had this same error on Fedora 30. `rpm -i --nodigest OpenAudible_rpm_1.5.2.rpm` worked for me. Not sure if there's an equivalent flag for `dnf`.

**Comment by jizhipeng969699** [comment]
rpm -ivh --nodigest --nofiledigest
