### ISSUE TITLE
OpenAudible error converting 60 file mp3 to m4b

### ISSUE THREAD

**Issue by computertech35975** [openaudible/openaudible#1312]
I am unable to convert a 60 file mp3 to m4b. It has happened on different files as well. Log file attached. I am using a windows 11 home 22h2 computer.

**Comment by openaudible** [comment]
Typically that isn’t recommended. You lose audio quality and may end up with a larger file. 

However you might be able to join the book into one mp3 file (file join menu). Then convert that to m4b. 

The whole log is difficult to parse. Better to open the file console. Right click to clear the contents, try the task, then copy and paste any errors or log. 

Thanks
