### ISSUE TITLE
damaged library. 

### ISSUE THREAD

**Issue by LoponWangdu** [openaudible/openaudible#1313]
<img width="598" alt="Screenshot 2023-12-04 at 2 26 52 PM" src="https://github.com/openaudible/openaudible/assets/152929667/6ad2e8dc-732b-42c6-a43e-e17b7ed0d5b8">
I had a similar error, and started over with a new library. Now it has done it to me again. Is there something I can do the the books.json to give it the proper termination, so I don't have to start over again. 
The first time I had this error, I tried to do a full download which started out ok but the download rate kept getting slower and slower, then ground to a halt. 
When I started the new library, I just downloaded one book at a time. If I accidentally started another book while the first was downloading, the rate would change from ~20 mb/sec to ~.5 mb/sec
Attached please find the .json in question.

**Comment by openaudible** [comment]
I deleted the link to the books file, but got a copy. 

The file is indeed damaged. It doesn't appear to be a normal type of corruption. Looks like your external hard drive is going bad. 


Only thing I can recommend is doing a disk check and use backup software. 

It might also explain the slow-down -- as writing to a bad disk will be slow, as more error checking is done and errors are managed.
