### ISSUE TITLE
Version 3.9.7.1 crashes on attempt to connect to amazon.

### ISSUE THREAD

**Issue by SeanAtsatt** [openaudible/openaudible#1315]
I am on an intel mac running 13.1 (22C65).  Here is the crash report

[Crash Report.pdf](https://github.com/openaudible/openaudible/files/13641748/Crash.Report.pdf)

**Comment by openaudible** [comment]
Reviewing.. Seems like an isolated case, but hard to diagnose. Looks like it is in the Webkit browser code which we don't have any control over.. Anyone else having this issue?

**Comment by HaleySp** [comment]
I'm getting the same. I select Amazon AU and then when the box comes up to login it never opens and crashes the program.

**Comment by openaudible** [comment]
Can you try the beta? We switched to a newer library. 
https://openaudible.org/beta

**Comment by citroenash** [comment]
I have the same issue. Have tried using 3.9.7.4 Beta and the issue remains. See Crash Report 1.pdf
[Crash Report 1.pdf](https://github.com/openaudible/openaudible/files/13786442/Crash.Report.1.pdf)

**Comment by openaudible** [comment]
Please try our latest beta https://openaudible.org/beta 

looking for feedback. You can log in and use the log in with Dialog rather than with the browser.

**Comment by citroenash** [comment]
Have tried 4.1.1.2 beta. Linking to Audible crashes uses dialog box, but using browser login it took me to Audible but said the page was invalid then crashed OpenAudible.

**Comment by openaudible** [comment]
can you send a bug report after it doesn't work? That's from the About menu. You can use issue 1315 for the number.

**Comment by citroenash** [comment]
crash report as requested.
[crash report 2.docx](https://github.com/openaudible/openaudible/files/14965693/crash.report.2.docx)

**Comment by openaudible** [comment]
Downloaded. Will review. Did you try the latest beta? https://openaudible.org/beta and the no browser log in?
