### ISSUE TITLE
Send Bug Report form dismisses/cancels when pressing shift+enter in the multiline form field.

### ISSUE THREAD

**Issue by elipriaulx** [openaudible/openaudible#1316]
The Send Bug Report form closes (cancel) when pressing shift+enter in the form field. In most applications I would expect this to insert a line break (instead of a paragraph break), but it is also what I would usually press when I am unsure if pressing enter alone will submit the form. 

Expected Behaviour:
New line is inserted in description field.

Actual Behaviour:
Form dismisses and content is lost without prompt.

**Comment by openaudible** [comment]
Shift-enter appears to be a Microsoft Word shortcut that isn't supported by the Eclipse SWT our application uses.

**Comment by openaudible** [comment]
The problem is fixed in the next version -- the cancel button was set as the default button, and apparently shift-enter will invoke the default action. Thanks for the report.

**Comment by elipriaulx** [comment]
> The problem is fixed in the next version -- the cancel button was set as the default button, and apparently shift-enter will invoke the default action. Thanks for the report.

I was actually worried at first that I had submitted an incomplete bug report when I tried to start a new paragraph and the dialogue suddenly dismissed suddenly. 😅

Re: Shift + Enter - Microsoft Word is certainly one place where this shortcut is used, but it's also common in most web forms (like when using Twitter/Facebook) and almost every instant messaging platform where the enter key would otherwise be assumed to 'post' or 'send' as the default action.
