### ISSUE TITLE
Send Bug Report form won't send if no issue number is provided. 

### ISSUE THREAD

**Issue by elipriaulx** [openaudible/openaudible#1317]
The Send Bug Report form instructs the user to include a github issue number 'if available', but does not allow users to continue without one (essentially making this mandatory). 

Expected Behaviour:
- The form should be sendable with no issue number provided, given the bug report form clearly states that it is optional.

Actual Behaviour:
- The issue number field is mandatory (and won't accept 'NA' or '0') in contradiction to the instruction above.

![image](https://github.com/openaudible/openaudible/assets/8568379/8ce94fcc-33aa-4eea-ace8-237d1e6ae18f)

**Comment by openaudible** [comment]
I’ll fix the wording and decide if none is ok.  You can make one up if you want (111 is popular). The bug report sends a lot of extra info and we don’t check for new bugs as often as just sending a support email thru the contact form. 

What bug are you reporting? Will keep an eye out for it.

**Comment by openaudible** [comment]
Edited. Feature and support questions need to go through the contact page on our web site. 

An issue number from the issues page or assigned by support is required. We will update the wording in the dialog.

Our (unsupported) https://github.com/openaudible/openaudible_docker version runs on Intel/AMD NAS systems via docker but not headless. The web UI is there to allow you to do things that can't be automated.
