### ISSUE TITLE
High CPU Usage

### ISSUE THREAD

**Issue by faizeln02** [openaudible/openaudible#132]
High CPU usage even though the program was idle, not downloading or converting any files.
CPU usage was around 50%,this seems to be too high for an idle program.

**Comment by openaudible** [comment]
That is high. CPU should be 0 when idle. 

Are you sure it wasn't doing an automatic conversion? Status will show a non-zero number under "Converting:".  (Automatic conversions can be disabled in prefs.)
What OS are you on? Did it ever go back to normal?

**Comment by d-olivares** [comment]
I can replicate the issue by starting a download-convert job. Just opening the applications displays a normal CPU usage. After running the download-convert process, ffmpeg.exe etc all disappear from task manager but OpenAudible.exe CPU usage stays high and does not return to the pre download-convert usage.

Windows 10 x64, OpenAudible 1.5.0, though this happened in previous versions as well.

**Comment by openaudible** [comment]
Thank you for the report. I believe I was able to reproduce and fix. Will do some testing and get a new release out.

**Comment by openaudible** [comment]
Fixed 1.5.1
