### ISSUE TITLE
Various .aax files will not play on an .mp3 player after an OpenAudible sync

### ISSUE THREAD

**Issue by asj1223** [openaudible/openaudible#1322]
When I attempt to play numerous .aax files in my OpenAudible library on a SanDisk .mp3 player, the files are rejected as "Unknown File Format". When I load those same files in inAudible, checksums of all 0s and warnings of "Could not find your key" are displayed.  When I download those same files directly from Audible via a browser, the files both play on the SanDisk .mp3 player and the correct activation bytes/keys are recognized by inAudible.  Most of the OpenAudible library files were originally loaded via a full Audbile sync. The rest have been added incrementally via full or quick syncs.  Please advise.

**Comment by openaudible** [comment]
You should not try to play the aax files as they are always encrypted.  AAX files should be converted to m4b or mp3 using OpenAudible.

Once you convert a file to mp3/m4b, it will turn green in the UI-- select the Action Menu: Reveal to reveal the location on your drive -- then drag and drop into your media player.

You can drag and drop AAX and AA files onto OpenAudible if they can be converted, they will be. (Some may not be if your encryption keys are not available.)
