### ISSUE TITLE
cannot connect to audible account

### ISSUE THREAD

**Issue by nutmeg2019** [openaudible/openaudible#1323]
![Untitled](https://github.com/openaudible/openaudible/assets/154947187/f6503d36-025f-4231-b870-c00b8e6c2b6b)

I have deactivated all the devices I can from my audible account. I tried to look for an update and it is giving me an error, but I don't have a firewall up and I told my browser to allow all cookies.

Dec 26, 2023 10:04:21 PM org.openaudible.desktop.swt.manager.login.LoginInternalBrowser handleMapLanding
INFO: handleMapLanding: connected:false
Dec 26, 2023 10:04:21 PM org.openaudible.desktop.swt.manager.login.LoginInternalBrowser handleMapLanding
INFO: handleMapLanding internal
Dec 26, 2023 10:04:21 PM org.openaudible.desktop.swt.manager.login.LoginInternalBrowser handleMapLanding
SEVERE: internal browser cookie error!
java.lang.Exception: No browser open getCookies
	at org.openaudible.desktop.swt.manager.browser.BrowserManager.getCookies(BrowserManager.java:43)
	at org.openaudible.desktop.swt.manager.login.LoginInternalBrowser.handleMapLanding(LoginInternalBrowser.java:117)
	at org.openaudible.desktop.swt.manager.login.LoginInternalBrowser.lambda$takeURL$0(LoginInternalBrowser.java:190)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by Hottabych-** [comment]
I've the same error. Then I've updated to liftime license because my lic was outdated since November. But after the update (3.9.7.1) the error was the same. So: 'Houston we have a problem' ...

**Comment by openaudible** [comment]
Hmm. What version and platform are you on? Make sure you’re using the latest version. (You can check from the about menu). If it happens again you can send a bug report from the about menu using this issue number 1323.

**Comment by nutmeg2019** [comment]
So I tried sending a bug report, and it wouldn't send! This is the message I got:

Dec 27, 2023 6:55:51 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:Error body:An error has occurred. Check File>Console for more details.
java.lang.Exception: Error sending bug report. 

Perhaps bug reporting is disabled or there is a bug in a bug reporter or a firewall or anti-virus program is blocking it.
More details about this error are in the debug log. 
You can resend, or cancel. 

Error:
org.apache.http.conn.ConnectTimeoutException: Connect to openaudible.org:443 [openaudible.org/18.216.30.50] failed: Connect timed out response:BUTTON_OK
Dec 27, 2023 6:56:03 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by openaudible** [comment]
Maybe you have a firewall blocking outgoing traffic from OpenAudible. That would explain both problems. 

Figure out which firewall you have an enable traffic. You can use the About: Check for Updates to see if that works before and after any firewall changes.

**Comment by nutmeg2019** [comment]
Yes, I've tried working on that. I turned off my firewall for my macbook, but it's still not working. Is it possible that I have some other firewall?

**Comment by nutmeg2019** [comment]
Ok so I logged in from a different computer, and it worked. It says in the troubleshooting guide to copy the credentials from that machine into my machine. Where should I copy it?

**Comment by openaudible** [comment]
From the preferences dialog, click on the icon next to preferences directory and you’ll see the location of the prefs in Finder/explorer. The credentials.properties is there and goes in the same preferences directory on the other computer. 

But the firewall needs to allow traffic for downloads to work.
