### ISSUE TITLE
3.9.7.1 treats split chapters as a new book

### ISSUE THREAD

**Issue by dlcarroll** [openaudible/openaudible#1324]
Upon launching 3.9.7.1 after upgrading to it, Open Audible wants to add all of the chapter-split m4b files for the 5 books I have split that way as new books.

If I allow it to add them, it treats "Chapter 01.m4b" as its own book, copying each chapter (? I think) into the Library root.

**Comment by openaudible** [comment]
Drag and dropping a directory handling has been changed recently (to support split audiobooks within directories.)

You may need to use the "File: Join Audiobook" to import a book that has already been split into chapters where you want the final book to be a single file. 
If you drag and drop multiple "chapter" files onto the app, they will be imported as individual books. 
We do have a beta with some changes to the importing.. you could try: https://openaudible.org/beta

**Comment by openaudible** [comment]
You may need to delete those books.. and put them into a directory within the "books" directory.. then do a Controls: Rescan Files.
We made some improvements in version 4.1. https://openaudible.org
