### ISSUE TITLE
Cover art not showing in audiobook info

### ISSUE THREAD

**Issue by SmartCollege** [openaudible/openaudible#1325]
None of the downloaded cover art jpgs are showing in the audiobook info box. Interestingly, when I move the window, the jpg shows DURING the move. Also, I just discovered that the art shows in a non-maximized window. The art is missing in any maximized window, no mater the width of the window.

**Comment by openaudible** [comment]
What OS are you using? If you're using a linux variant, I would need to get a full ISO to attempt to reproduce.
I assume the image shows in the Get Info Window?

**Comment by openaudible** [comment]
Just saw this on Ubuntu. Will fix.

**Comment by openaudible** [comment]
Ok. we either fixed it or it stopped being reproducible. (Tested full screen and small.) 

Can you try the beta: https://openaudible.org/beta

If you don't see the problem, let me know. 
If you do see the problem, open the File Debug Window and every time we change the cover image we log something... so let me know if you see the log messages.  

This seemed to affect only Linux.
