### ISSUE TITLE
Error downloading: Asin: [B002UZKIBO]

### ISSUE THREAD

**Issue by skdreher** [openaudible/openaudible#1326]
When attempting to download some books in my library, I have quite a few that will not download and have the red ball.  The state says Error downloading: Asin: then the ASIN of the book.  I was able to download 66 of 170 books.  I have closed the program then relaunched the program and done both download all and just selecting a book individually with no luck.  I am using OpenAudible 4.0.1

**Comment by openaudible** [comment]
If you have multiple accounts you need to make sure you are logged into the correct one. Also if you logged in with a legacy account but upgraded to the account with an email, you may need to re-log in with that. Also try a full resync from the control menu.
