### ISSUE TITLE
Split books action show no book selected

### ISSUE THREAD

**Issue by lauriekrueger** [openaudible/openaudible#1327]
trying to split a book shows 0 books selected in the split report.  It is the last book in a list of 4.  All others split without issue.

<img width="704" alt="image" src="https://github.com/openaudible/openaudible/assets/18015418/a4199164-4ad9-4ae7-8831-006bd0e711c2">

<img width="278" alt="image" src="https://github.com/openaudible/openaudible/assets/18015418/ea682005-a53f-464a-8dbd-486ce4af5d84">

**Comment by openaudible** [comment]
Hmm. Right click and select split selected? There might be more info in the Log Window.

**Comment by openaudible** [comment]
There is some kind of error and we didn't add it to the results to get summarized. We fixed that in the beta: https://openaudible.org/beta  But you still may have an error in the Log Window or it should get summarized properly when it displays the Good, Errors, Skipped summary. Let me know!

**Comment by openaudible** [comment]
Fixed in latest production version, 4.0.2.
