### ISSUE TITLE
Ordered download/processing

### ISSUE THREAD

**Issue by thiemo-taken** [openaudible/openaudible#1329]
Hi

Many thanks for the software. It is great.

To me, it seems, that the pieces for download and conversion get picked randomly. I would appreciate, if one could get an order into it. By file size/play length would be nice. Or just respecting the order displayed in the list. Or if one could move them.

Kind regards

Thiemo

**Comment by openaudible** [comment]
It does get scrambled. Recommend picking a few books you want to download or convert, selecting those and Action menu: download or convert. Then do the rest automatically. Thinking about it now most recent purchases should be downloaded first.
