### ISSUE TITLE
Converts downloaded book to mp3 but doesn't display it as converted afterwards

### ISSUE THREAD

**Issue by SageRebel** [openaudible/openaudible#1330]
I just upgraded from version 3 to 4 (current builds) and all features appear to work fine except once I have downloaded a book and convert it to mp3, once it finishes it returns the state as "Ready to Convert"

However the book has been converted but I have to quit OpenAudible and restart it for the book to show their proper state.

The log file doesn't show any errors:

NFO: create MP3 C:\Users\tbrog\OpenAudible\aax\Wisdom Sits in Places.AAX result:0
Jan 17, 2024 3:06:23 PM org.openaudible.convert.ConvertJob convert
INFO: Converted Wisdom Sits in Places to C:\Users\tbrog\OpenAudible\mp3\Wisdom Sits in Places.mp3 size=208982615 duration 07:14 in 1452 seconds.
Jan 17, 2024 3:06:24 PM org.openaudible.Audible jobCompleted
INFO: ConvertQueue completed:Wisdom Sits in Places ConvertQueue size:0 remain:0 success:2 fail:0 threads:1 jobs:0
Jan 17, 2024 3:06:34 PM org.openaudible.desktop.swt.manager.views.BookInfoPanel setThumbnailImage
INFO: Setting cover: Rectangle {0, 0, 200, 200} from C:\Users\tbrog\OpenAudible\art\Wisdom Sits in Places.jpg
Jan 17, 2024 3:06:35 PM org.openaudible.audible.bookstatus.LibraryStats updateStats
INFO: updateStats for 184 books took 9.401 seconds to complete.
Jan 17, 2024 3:06:37 PM org.openaudible.desktop.swt.manager.views.BookInfoPanel setThumbnailImage
INFO: Setting cover: Rectangle {0, 0, 200, 200} from C:\Users\tbrog\OpenAudible\art\Wisdom Sits in Places.jpg
Jan 17, 2024 3:06:47 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

Also I installed the latest beta after browsing the issues but it didn't change anything.

Please advise....

**Comment by openaudible** [comment]
That is strange. 
For me, I click on a gray book and it says "Not Downloaded"
I right-click and Download and it downloads and the state turns to Ready To Convert (icon for the book changes)
I can then Action Menu: Convert to MP3 or M4B.  After it converts the book icon turns green and the state changes to "Converted: mp3"

I see you're on windows and I am testing this on windows. 
Does the icon for the book in the book table change? 

We are trying to track down an error where conversion tasks are canceled unexpectedly.. but I don't see any messages about that either. 

I guess I might need more information to debug this.. It doesn't seem super common, but it may also be going unnoticed by others.

Feel free to add to this discussion.. or send a screenshot or video to us if you want. You can get our email by contacting us through our web form and mentioning this issue number. https://openaudible.org/contact

**Comment by SageRebel** [comment]
Historically your description is exactly how it used to work for me prior to upgrading to ver. 4.01.
I installed the beta 4.0.12 and the issue was still present.

To answer your question, the icon does not change to the green circle denoting the completion of the conversion and the listed state goes from "converting" to "ready to convert" which is the state before converting. I also attempted import the mp3 file immediately after converting completed, which resulted in an "unable to import (filename) error message and the icon turned into a red circle.  I then manually looked in the OpenAudible mp3 directory and the mp3 file no longer existed. The axx file was in the axx directory as it should be. I then exited the program and restarted it but this time the converted file didn't show the green icon as it usually does if I don't try to import it after conversion.  As I stated in my original post that usually after conversion I exit the program restart it and the book shows in the library and I can then split it into chapters. I'm about to install the 4.0.13 beta and see if that resolves the issue. I'll let you know.

**Comment by nulladiessinecorde** [comment]
I have been going through the same issue.

**Comment by openaudible** [comment]
Open the File menu: Debug Log. See if there are any error messages when you convert a file. 
Disable auto-convert and auto-download in the prefs if you need to.
Convert one file. It should say if there was an error of it was converted successfully.

**Comment by SageRebel** [comment]
Upgraded to 4.0.14 beta : issue resolved... all operations performing as required.

**Comment by openaudible** [comment]
Strange! Didn't think I changed much! Got one other strange bug and will update the app to 4.0.2. Thanks for the report!
