### ISSUE TITLE
Installer - Enable multilanguage

### ISSUE THREAD

**Issue by bovirus** [openaudible/openaudible#1333]
@openaudible 

Is it possible to enable multilanguage for installer?
I'd like to add Italian language.

Could be possible to add to github homepage infos how to revsie strings for multilanguage installer?

Thanks.

**Comment by openaudible** [comment]
I have enabled the multilingual installer in the beta. https://openaudible.org/beta 
I haven't really tested it yet tho. I believe your system will give you a language dialog if your locale is other than "en" english.

**Comment by openaudible** [comment]
I posted beta 2 that allows you to use a local i18n_it.properties file. Just copy it to your C:\Users\Name\OpenAudible directory and restart the app. It should start using translations from that local file. Feel free to ask if you have any questions. 

For anyone else following this.. This will work for any language. To get the original translations in your current version, go to C:\Program Files\OpenAudible and open the openaudible_xxx.jar file and navigate to the org/openaudible/languages directory, from there you'll see the i18n_xx.properties, where xx is ar,de,en,es,fr,hi,it,ja,pt,ru,zh language strings. 

If you make any changes, save as a UTF file and email to me. 

I'm using the latest install4j, version 10.0.6.

**Comment by bovirus** [comment]
@openaudible 

Thanks for new beta2.
Will be very useful to devlop/test translations.
I will continue the revision of OpenAudible GUI language.
I contacted the Install4j developers and I will send them (and to you) the new Italian Install4j language.
Thanks.

**Comment by openaudible** [comment]
Very nice! I assume you can find the i18n files somewhere in the Mac or Windows install4j application. Can assist if needed.

**Comment by openaudible** [comment]
Fixed in 4.0.4. Thank you!!
