### ISSUE TITLE
Settings on installing new update - conversion preference

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#1335]
Every new version, beta or full release, on iMac version changes the preference for conversion to MP3 even though it is always set by me to M4b.  Why does it not stick with the present set of preferences.

**Comment by oboe45** [comment]
This is present, again, on 4.0.3.3 Beta

**Comment by openaudible** [comment]
I will check. We added ability to convert to both mp3 and m4b (previously making you change preferences.) so the menu item for convert to mp3 may now always be enabled. But automatic conversions should only use your preference.

**Comment by oboe45** [comment]
Yes, it always uses the preference, but the preference always defaults to
MP3 when an update occurs.  Your notes say the M4b is the usually preferred
format, so, why do you set default to mp3 when a new version of the app is
downloaded??

**Comment by openaudible** [comment]
It definitely should not. After an upgrade, you're seeing the Preferences dialog change from M4B to MP3?? But all other setting stay the same? (like credentials, etc.. ) 

You can look at the file settings.json ("format":"M4B") ~/OpenAudible/settings.json and that should never change even after an upgrade. 

Are you on a Mac? They do have some strange security features...

**Comment by oboe45** [comment]
Its on an Imac - all sw uptodate, preference changes from mp4 to mp3 when a
new version is installed.  Since a newly installed update, when started,
goes straight into the process of verifying files etc, I cannot see the
changed conversion setting until it has finished the 4 minute start up at
which point I can change back to Mp4 - it would be better if either it
didn't change, or, it did not automatically start into the 4 minute file
checking bonanza!

**Comment by openaudible** [comment]
I can’t reproduce. But added a bunch of code to the logging. So if it happens again just send a bug report from the About menu.
