### ISSUE TITLE
4.0.3.6 Beta - Incorrectly setting the conversion option to Mp3

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#1337]
My OA settings were set to M4b in the version (4.0.3.3) I had been using and in all versions before that.  After downloading and installing 4.0.3.6. the conversion option was set, incorrectly, by the app to mp3.  

I now check the settings every time I use OpenAudible, and the conversion option was definitely m4b before the latest update. 

This was previously reported in earlier versions.

Running OA on an IMAC M1, using Sonoma 14.3

**Comment by openaudible** [comment]
I have tried and am unable to reproduce this. I believe it can happen, but I don't know how. 
Maybe check the settings.json file before and after an upgrade? 
I will add a "setting output format to XXX" to the beta and maybe you can catch it in the act.. 

Very puzzling.

**Comment by openaudible** [comment]
That's the thing. I don't change it. I read it in from the settings.json file. If that doesn't exist, we do use the default M4B.
It's almost like there is an extra settings.json file that is getting read... I'm building a new beta and will add some code to assist.

**Comment by oboe45** [comment]
Ok, let me know.

**Comment by oboe45** [comment]
Loaded 4.0.3.7 - The settings were for m4b conversion in 4.0.3.6 and after loading, the new version also shows m4b!!   Not sure if that is what you were planning to fix, but it solved my issue

**Comment by openaudible** [comment]
I didn't change anything.. just added one debug message to the prefs loading log messages. Since there was already a fair amount of logging when we open and load the settings.json. 

If it happens again, please send a bug report (or look at the File Log Window... and let me know by email or here..
