### ISSUE TITLE
Default file naming convention has collisions with other closely named Audiobooks, which gives an identical filename.

### ISSUE THREAD

**Issue by bennettjw** [openaudible/openaudible#1339]
A short file name is created for each Audiobook using an 'unaccessible to the user' naming convention.
Occasionally there is a collision with those names.
E.g.
I have both the abridged and unabridged versions of Atlas Shrugged. Default filenames (using the rename filename button) were "Atlas Shrugged" and Atlas Shrugged.1".
Output was only "Atlas Shrugged.1.mb4". There was no second file of "Atlas Shrugged.mp4".
This happened six times in a 747 audiobook collection.

PS - Maybe a fix could be a default file naming that appended the ASIN to the filename? (e.g. "Atlas Shrugged.B002VA3KG8" unabridged and "Atlas Shrugged.B000APYGIW"). Not completely certain all have ASINs though.

**Comment by openaudible** [comment]
Will investigate. We could definitely add the ASIN. Not sure about as the default for all books but perhaps those with collisions.

**Comment by openaudible** [comment]
Made a fix and posted it to the latest beta: https://openaudible.org/beta
Should be an improvement.
You may need decide to delete and re-download them to get them to use the full title correctly.

**Comment by openaudible** [comment]
This should be better in the latest 4.0.4 or higher.
