### ISSUE TITLE
feature request: convert to MP3 dividing by tracks

### ISSUE THREAD

**Issue by Butterfly-Dragon** [openaudible/openaudible#134]
the mp3 created has several tracks, just like the original audible file, i would prefer to have it divided into multiple files, one for each track.

**Comment by CrustyApplesniffer** [comment]
I've worked on a third party way to do what you expect. Have a look to 
https://github.com/PrometeoConseil/AudioBookSplitter

**Comment by openaudible** [comment]
There is also a python version:
https://gist.github.com/MawKKe/2212578adbeb3df6835e11852ea9ff21
If someone finds or writes a java version (that doesn't require ffprobe), I might add it as a utility.. but don't want to spend the 4 hours to write and test.

**Comment by gbouthenot** [comment]
You can use [mp3splitter](https://github.com/gbouthenot/mp3splitter/)
It directly splits the mp3 by chapters based on integrated tags.
