### ISSUE TITLE
Audible Account Manager incorrectly counts the number of accounts added to the app

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#1341]
in the Audible Account Manager screen it shows i have one single account added but in the text above the list it says i have 0 of 10 accounts added
if i connect to another server with the same account it shows this as a duplicate but it still only shows 0 of 10 accounts added

**Comment by openaudible** [comment]
Oh we only add one when you convert a book. And sometimes even then we don’t increment the count. We don’t want to be too aggressive or people will complain we marked two accounts when they only have one. Will review.

**Comment by feldegast** [comment]
maybe it should say "logged in accoints" ? "active accounts"?

**Comment by openaudible** [comment]
If the status is OK you are logged in and it is working. If it is "enabled" it will be included in the library scan. At the moment, even a disabled account can be used to download a book that is in your library and using a "disabled" account.

**Comment by feldegast** [comment]
i still don't get how it is 0/10 or do i actually have to download something for 0 to become one?

**Comment by openaudible** [comment]
Yeah, it looks a little buggy... I am going to fix that. Thank you for the heads up.

**Comment by feldegast** [comment]
was trying to upload a screenshot but it wouldn't attach here glad you can see issues in the code to fix

**Comment by openaudible** [comment]
Got the screenshot. 
I created a beta that hides the account info unless you approach the limit. It will also keep better track of accounts. 
Give it a try! https://openaudible.org/beta

**Comment by openaudible** [comment]
Updated the JDK and made other changes to possibly fix your issues. 4.0.4.2
https://openaudible.org/beta

**Comment by openaudible** [comment]
Fixed in 4.0.5. Thanks for the report!
