### ISSUE TITLE
Default file naming convention dumps all characters past the dash character including the dash

### ISSUE THREAD

**Issue by bennettjw** [openaudible/openaudible#1343]
The default file naming convention dumps all characters past the dash character including the dash.
For example: 
An audiobook named "1636 - The Saxon Uprising" results in the filename "1636.1".
I observed this in every case with a dash character in the audiobook name, 58 instances in a 1200+ audiobook collection.
Recommend stripping the dash character when assigning the filename associated with the audiobook to allow for a more meaningful filename.

**Comment by bennettjw** [comment]
In short, "1636 - The Saxon Uprising" would result in "1636  The Saxon Uprising"

**Comment by openaudible** [comment]
I believe there is a "short name" and a "long name" for book titles. We typically use the short name as the long name can be very long and unwieldy. So we use the short name by default, unless there is a collision. 
This could be improved... perhaps use the long name if under a reasonable length -- say 64 characters. 
You can verify this using the "Get Info" for the book and look at the titles. We don't set those.. but open to suggestions on improvements.

**Comment by openaudible** [comment]
We created a beta that uses the long file name by default if it is under 64 characters. Give it a try!
https://openaudible.org/beta

**Comment by bennettjw** [comment]
I need a day to set this up on a different computer. Will get back to you.

**Comment by openaudible** [comment]
Fixed in 4.0.5. Thanks for the report.
