### ISSUE TITLE
When splitting a file, it appears that the "Title" field in MP3 Track Title tag is reusing the filename instead of the metadata (OpenAudible 4.04)

### ISSUE THREAD

**Issue by ZLoth** [openaudible/openaudible#1344]
I've been encountering an issue when splitting files in OpenAudible 4.04 when using the split file feature. When the Metadata from Amazon is available for the chapters, it appears that OpenAudible is doing some conversions to the chapter name to make it file system friendly (e.g. converting unusable colons under Windows to usable dashes as well as adding the track number at the beginning). However, this "sanitized" name also being reused as the MP3 track title instead of the title available at part of Amazon's Metadata. I end up having to go back in using MP3Tag to clean up those titles prior to uploading them to my private Emby server.

**Comment by openaudible** [comment]
I looked into this and haven't been able to reproduce this. 

I think what you're seeing is we choose the best chapter data from the usually two sets of chapter data available-- the audiobook file and the API. We have to choose the best set of chapters to use. Often one uses the dashes and another uses colons etc. 
I'll look into it some more.. but didn't get anything changed for the latest 4.0.5.

**Comment by ZLoth** [comment]
This is easily reproducable. Here is an example book (_Sci-Phi: Science Fiction as Philosophy_):

![Book Information](https://github.com/openaudible/openaudible/assets/6700159/e52de324-269a-455d-a6f5-26de1fccebf1)

I've highlighted two chapters in particular:
- Lecture 7: Interstellar: Is Time Travel Possible?
- Lecture 13: The Thirteenth Floor: Are We Simulated?

![Chapter List](https://github.com/openaudible/openaudible/assets/6700159/01a1347f-3f46-493c-a5c8-b70c13619540)

When I look at the same thing in MP3Tag, I see the following:

First Example: 
- Filename: 09 Lecture 7- Interstellar- Is Time Travel Possible.mp3 _(Expected)_
- Track Title: 09 Lecture 7- Interstellar- Is Time Travel Possible _(Not Expected, Colon and question mark are allowed characters)_

Second Example:
- Filename: 15 Lecture 13- The Thirteenth Floor- Are We Simulated.mp3 _(Expected)_
- Track Title: 15 Lecture 13- The Thirteenth Floor- Are We Simulated _(Not Expected, Colon and question mark are allowed characters)_

Plus... the track numbers are in front of the track title....
![MP3Tag](https://github.com/openaudible/openaudible/assets/6700159/d00408c2-208b-4d6f-95fb-5c66ac3747cf)

Here is the book metadata:
[Metadata.txt](https://github.com/openaudible/openaudible/files/14366267/Metadata.txt)

And here are the preferences:
![OpenAudible Preferences](https://github.com/openaudible/openaudible/assets/6700159/a142a57b-699f-41f0-a8a5-0ad0025bbd51)

**Comment by ZLoth** [comment]
I am able to replicate this in OpenAudible 4.05 with as MP3 with both VBR checked and unchecked.

**Comment by ZLoth** [comment]
Ahhh, yes, fixed! 
![Mp3tag 2024-02-22 16-08-27](https://github.com/openaudible/openaudible/assets/6700159/1eec485e-56e0-4b5e-aaa3-a464227f404f)

**Comment by openaudible** [comment]
Good to hear. Working on the "parts" with subchapters.

**Comment by openaudible** [comment]
Fixed in 4.1 release!
https://openaudible.org
