### ISSUE TITLE
Some books with Parts and Subchapters are only displaying the parts in Chapter Information (OpenAudible 4.04)

### ISSUE THREAD

**Issue by ZLoth** [openaudible/openaudible#1345]
The example I'm providing is for the _James Bond (Celebrity Performances)_ version of _Moonraker - James Bond, Book 3_, but I noticed this on a few others because of how the JSON is formatted from Amazon.

In this book, there are three distinct parts, and then several chapters under each part. When I go to Actions → Get Info → Chapters, only the three major parts are listed, but not the subchapters. I have confirmed the JSON data is there, and splitting by chapters is working as expected. 

Example Book Information:
![Example Book Information](https://github.com/openaudible/openaudible/assets/6700159/470e1410-748b-4870-9018-1701c1652e83)

Example Chapters:
![Example Chapters](https://github.com/openaudible/openaudible/assets/6700159/db3ce072-cde7-4a9c-80a9-c9ff3c888503)

Example Book Report:
![Example Book Report](https://github.com/openaudible/openaudible/assets/6700159/b06f352f-9521-4d63-ab53-b3d61cbc83e5)

Example JSON:
[Example JSON.txt](https://github.com/openaudible/openaudible/files/14337128/Example.JSON.txt)

**Comment by openaudible** [comment]
That is interesting. I haven't seen the book parts in the JSON like that. Will need to investigate. Thank you for the report.

**Comment by ZLoth** [comment]
From Dreamsongs (Unabridged Selections).... nice! Thank you!

![OpenAudible 2024-02-27 05-51-12](https://github.com/openaudible/openaudible/assets/6700159/ef2a0e92-ee7f-4ed8-8700-c45767a1abfe)
[Metadata.txt](https://github.com/openaudible/openaudible/files/14418977/Metadata.txt)

**Comment by openaudible** [comment]
Please try the latest beta. It should help. You will need to recode any books that have missing chapters

**Comment by ZLoth** [comment]
> Please try the latest beta. It should help. You will need to recode any books that have missing chapters.
> 
> https://openaudible.org/beta

Already have. :D See above message with the quote: "From Dreamsongs (Unabridged Selections).... nice! Thank you!"

**Comment by openaudible** [comment]
Fixed in 4.1 release! Thank you!
https://openaudible.org
