### ISSUE TITLE
Feature Request: Confirming prompt when using Control → Download All From Audible

### ISSUE THREAD

**Issue by ZLoth** [openaudible/openaudible#1347]
I made an error when I was trying to do a "Full Audible Library Sync" and instead selected "Download All From Audible".  This started a download of all of my audiobooks which numbered over 2,000 and what I would consider a "runaway job", and I was able to cancel and clean up. There should be a pop-up "sanity check" confirmation box if I am downloading more than 15-20 books at a time. This value can be set in preferences.

**Comment by openaudible** [comment]
First instance of that.. Cancel All Jobs is an easy way to undo that. And the point of the software is to download all books.. Thanks for the suggestion.
