### ISSUE TITLE
SEVERE: No API found for book

### ISSUE THREAD

**Issue by Larakin** [openaudible/openaudible#1348]
Problem:
Autofill is failing. Log shows error: "SEVERE: No API found for book:"

Description:
When attempting to Autofill, I get no error messages (previous versions would give a popup to retrieve ASIN or Product ID) and nothing happens.

Log is as follows:
INFO: generated book report for The Order of the Phoenix
Feb 21, 2024 10:36:29 AM org.openaudible.desktop.swt.manager.editor.GetInfoDialog autoFill
SEVERE: No API found for book: Harry Potter and the Order of the Phoenix, Book 5

I have inserted the ASIN/Product ID just as it worked before.

I have also tried several other books If I had previously used autofill, it seems to work correctly. But any new book seems to fail.

Im am continuing to debug by updating and see if I can find a solution.

**Comment by openaudible** [comment]
Can you try the latest beta https://openaudible.org/beta

**Comment by Larakin** [comment]
Worked as expected! Thank you!

**Comment by openaudible** [comment]
fixed in 4.0.5 final. A Controls: Full Resync should have also helped.
