### ISSUE TITLE
If "Automatically delete AAX Files" is checked, OpenAudible is unable to Delete Book (OpenAudible 4.0.5) 

### ISSUE THREAD

**Issue by ZLoth** [openaudible/openaudible#1349]
Here is one I stumbled across. If you have "Automatically delete AAX Files" enabled in the Preferences, then try to delete the book, OpenAudible 4.0.5 can't complete the operation because it can't find the file to delete. 

Steps to replicate:

1. Go to Edit → Preferences and check off "Automatically delete AAX files".
2. Download an audiobook. Upon completion, the associated AAX file is deleted (As expected)
3. Right-click on the audiobook and select delete.
4. Confirm the deleteion.

WHAT IS EXPECTED: The associated files are deleted. If they are already deleted (e.g. moved to another directory), no error message is thrown.
WHAT ACTUALLY HAPPENS: The deletion option does not complete, and a java.io.IOException error is thrown.

Here is a recording of the issue:
https://github.com/openaudible/openaudible/assets/6700159/a79ea030-1151-47d8-8529-547f74c37ae6

OpenAudible preferences: 
![OpenAudible Preferences](https://github.com/openaudible/openaudible/assets/6700159/80fe5b03-f13c-4749-9943-ae3d53fbef21)

OpenAudible message showing four files to delete:
![OpenAudible Confirmation Box](https://github.com/openaudible/openaudible/assets/6700159/26684cc3-3b24-427d-b0e1-02c927422296)

OpenAudible Error Message:
![OpenAudible Error Log](https://github.com/openaudible/openaudible/assets/6700159/12ff9446-97b7-4098-816d-56064e1f5df1)

Error Log Snippet:
[Error Log.txt](https://github.com/openaudible/openaudible/files/14366554/Error.Log.txt)

**Comment by openaudible** [comment]
Thank you. Will fix and report back.

**Comment by ZLoth** [comment]
Confirmed fixed. Thank you.
