### ISSUE TITLE
Cant download books

### ISSUE THREAD

**Issue by breugel1** [openaudible/openaudible#135]
All of my books have a red dot to the left of the book not a green one. Running version 1.5 on Win 10
![image](https://user-images.githubusercontent.com/50328102/57227327-1d365180-6fdf-11e9-828e-ccdce8738f13.png)

**Comment by openaudible** [comment]
What region are you in? (Upper left of UI)
Check your settings: https://openaudible.org/settings.html
That indicates there is no download URL for your book. When you view a book in the audible browser, you should be able to click on a download button and have the book start to download. 
Try a "Rescan".

Copy and paste any errors from the console, removing any personal info.

**Comment by klinkehoffen** [comment]
I have a similar problem with not being able to download, although I am not getting a red dot: I have a grey dot. 

My Actions menu is greyed out, as is my right-click menu. Also running OA v1.5 on Win 10. As you can see by the attached images showing both menus, the items I want to download are showing that they are in the download queue. However, in more than 12 hours they are STILL in the download queue, with nothing to show that anything is happening. I am connected to the internet. Everything else is operating as normal. 

I have tried launching the in-OA Audible window and clicking the download button there, but this also doesn't work.

Any ideas would be gratefully received. 
![OpenAudible download options greyed out](https://user-images.githubusercontent.com/25827960/57324386-d0c45080-715b-11e9-9048-c417bfbc82d5.jpg)

**Comment by klinkehoffen** [comment]
By the way, my software verification button is already unchecked.

**Comment by breugel1** [comment]
It was the audible settings. I mis read the pic i thought it needed to be checked. Sorry for the inconvenience. Working fine now.

**Comment by openaudible** [comment]
@klinkehoffen - looks like those books were in the download queue waiting to be downloaded. Update to 1.5.1 for a better UI.

**Comment by guysoft** [comment]
I managed to fix it now.

If might be because you dont have the download links.
In order to fix that select in OpenAudiable:

1.
actions> view in audible.
2.
Login
3. go form from "Hi , your name" to "Account details"
4. 
Under "settings" tab unheck "Check for Audible Download Manager"/
5. refresh your library and see if the red balls go grey and let you download.

**Comment by frankstallone** [comment]
^^ @guysoft nailed it. Once I unchecked "Check for Audible Download Manager" in my Audible Account details > Settings, I was immediately able to download the books. 🙏
