### ISSUE TITLE
Unable to convert two Audible books from aax to mp3/m4b (4.0.5.2beta)

### ISSUE THREAD

**Issue by ZLoth** [openaudible/openaudible#1353]
Issue is occurring with OpenAudible 4.0.5.2 Beta, but I do not know if it occurred in previous versions.

Today, when attempting to download and covert the book _The World of Ice & Fire - The Untold History of Westeros and the Game of Thrones_, the conversion from AAX to MP3 or M4B failed. It appears the AAX file is downloading, but either the download is incomplete (only 593MB) or the metadata provided by Amazon is malformed. So far, it only appears to affect this sole title. 

Book Information:
![Book Information](https://github.com/openaudible/openaudible/assets/6700159/e9b87d9e-5925-4a4b-bbd9-61cf2c1ab6dc)

Chapter List:
![Chapter List](https://github.com/openaudible/openaudible/assets/6700159/2055e84b-b964-4550-86be-f9da143e2d58)

Log files and Metadata:
[Log File 1.txt](https://github.com/openaudible/openaudible/files/14421206/Log.File.1.txt)
[Log File 2.txt](https://github.com/openaudible/openaudible/files/14421207/Log.File.2.txt)
[Metadata.txt](https://github.com/openaudible/openaudible/files/14421208/Metadata.txt)

**Comment by ZLoth** [comment]
And, it figures. I found another one, in this case _Apollo_. Also, when in a "Error" state, the "Book Report" section is blank.

Book Information:
![Book Information](https://github.com/openaudible/openaudible/assets/6700159/5a8aac5f-151e-4d7b-b9d7-86566704e551)

Chapter List:
![Chapter List](https://github.com/openaudible/openaudible/assets/6700159/cb8a721d-dee2-4374-9c62-4cfef3ae9f17)

Book Report before I attempt to download the book:
![Book Report-Before Download](https://github.com/openaudible/openaudible/assets/6700159/08736e44-4198-473e-8dbe-dc95e52d7e97)

Book Report when in a Error state:
![Book Report-When in a error state](https://github.com/openaudible/openaudible/assets/6700159/57c456ae-8ae0-4533-994a-5e439930d950)

Metadata and log files:
[Log File.txt](https://github.com/openaudible/openaudible/files/14423060/Log.File.txt)
[Metadata.txt](https://github.com/openaudible/openaudible/files/14423061/Metadata.txt)

**Comment by openaudible** [comment]
Please check the file debug window for an error. Copy and paste or email me or send a bug report if you see an error.

**Comment by openaudible** [comment]
Disregard last message. Saw you included logs.  Will review. Thank you.

**Comment by openaudible** [comment]
Oops made a infinite recursion error. Will fix. Thank you for the report!
```
	at org.openaudible.books.Chapters.count(Chapters.java:84)
	at org.openaudible.books.Chapters.count(Chapters.java:84)
```

**Comment by openaudible** [comment]
Fixed in the latest https://openaudible.org/beta
Thank you!

**Comment by ZLoth** [comment]
Testing now on 4.0.5.4 with the book _Apollo_ and it appears to be working. Thank you.

**Comment by ZLoth** [comment]
Whoops. spoke too soon. File SPlitting threw an error:

Error Apollo Index 39 out of bounds for length 39java.lang.IndexOutOfBoundsException: Index 39 out of bounds for length 39 at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:100) at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:106) at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:302) at java.base/java.util.Objects.checkIndex(Objects.java:359) at java.base/java.util.ArrayList.get(ArrayList.java:427) at org.openaudible.books.Chapters.get(Chapters.java:170) at org.openaudible.convert.SplitAudio.getChapters(SplitAudio.java:608) at org.openaudible.convert.SplitAudio.splitByChapter(SplitAudio.java:326) at org.openaudible.desktop.swt.manager.SplitJoinGUI.splitOne(SplitJoinGUI.java:273) at org.openaudible.desktop.swt.manager.SplitJoinGUI$2.run(SplitJoinGUI.java:168)

![chrome 2024-02-27 15-57-05](https://github.com/openaudible/openaudible/assets/6700159/a96abb8a-4b55-41fc-8b7f-f97820547722)

[Log File.txt](https://github.com/openaudible/openaudible/files/14426166/Log.File.txt)

**Comment by openaudible** [comment]
Should be fixed in latest beta https://openaudible.org/beta
