### ISSUE TITLE
Get Info → Cancel or Save Changes does not work when conversion is in progress (4.0.5.2-4.0.5.4)

### ISSUE THREAD

**Issue by ZLoth** [openaudible/openaudible#1354]
This issue was first observed in 4.0.5.2 and still exists in 4.0.5.4. 

STEPS TO REPLICATE:
1. Begin downloading and then converting the book.
2. Right-click on that book and click on "Get Info"
3. Click on "Cancel" or "Save Changes"

WHAT SHOULD HAPPEN: The "Edit Book" Window closes. 
WHAT REALLY HAPPENS: The button clicks but window remains open.

Recording of issue:
https://github.com/openaudible/openaudible/assets/6700159/53fad569-205f-4bde-aee0-1690a3415b79

Log File:
[Log File.txt](https://github.com/openaudible/openaudible/files/14426097/Log.File.txt)

**Comment by ZLoth** [comment]
Issue also occurs when the book is in a "Downloaded" state.

https://github.com/openaudible/openaudible/assets/6700159/9bf0cba8-5bf0-4cb7-af1f-47f2035da975

**Comment by openaudible** [comment]
I don't see anything in the Log you sent.. But that could be related to the previous error. Building a new version. Maybe keep an eye on the File: Debug Window and if you see something like an error message (Exception) my guess is that will be the problem.

Thanks for the reports! Amazing!

**Comment by openaudible** [comment]
Uploaded beta! https://openaudible.org/beta

**Comment by openaudible** [comment]
Beta should fix it.. but there may be an error that pops up in the Debug Window when you hit cancel or save... (But hopefully not.)

**Comment by ZLoth** [comment]
Fixed in latest beta. Thank you.
