### ISSUE TITLE
"Error message: No Active Accounts" when starting OpenAudible or doing a Quick/Full Sync

### ISSUE THREAD

**Issue by ZLoth** [openaudible/openaudible#1355]
This is a new issue that came up after installing OpenAudible 4.0.5.6 . I have a single Audible account that is in the United States.

When I attempt the following:
- Starting OpenAudible 4.0.5.6
- Attempting a Control → Quick Audible Library Sync 
- Attempting a Control → Full Audible Library Sync

I see the following error message:
![OpenAudible 2024-02-27 19-57-38](https://github.com/openaudible/openaudible/assets/6700159/b67f665c-3be0-426b-b8c0-b8acee33abb3)

Here is the error when doing the library sync:
https://github.com/openaudible/openaudible/assets/6700159/0c140ebe-6f7d-41e4-8655-647507750ad7

I'm not seeing an option to log out from the Control Menu, only to log on.
![Control menu](https://github.com/openaudible/openaudible/assets/6700159/c954a85c-90dd-4692-81a3-aa1b6686326e)

I am able to see the option under File → Manage Accounts:
![OpenAudible 2024-02-27 20-03-57](https://github.com/openaudible/openaudible/assets/6700159/07a256ac-4105-42b4-a8d7-fb56f2e1cb7e)

However, clicking on the Trash can icon brings up a confirmation message, but account isn't deleted. Test All appears to be fine. 

I am able to download and convert books. 

As always, a log file:
[Log File.txt](https://github.com/openaudible/openaudible/files/14427847/Log.File.txt)

**Comment by feldegast** [comment]
#1350 is where i am working through multi server issues this bug is new as of this beta

**Comment by ZLoth** [comment]
Fixed in 4.0.5.7.... THANK YOU!!!!

**Comment by openaudible** [comment]
Thank you for the report.. Glad to hear its working now!!
