### ISSUE TITLE
indeterminant status indications when converting to the 2nd format file

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#1356]
i generally convert my audiobooks to m4b files
when converting it is a blue circle
when converted to m4b it is a green circle
i convert say 10 f9les to m4b i then have 10 books with green circles
if i then switch to converting to mp3 and start converting to mp3, the indicator stays green all the time
there is no indication which books are being converted to mp3 as all aare green
there is no indication which books have been converted to mp3 as all are green

i am not sure what the best way to add clarity here maybe the indicator colours only reflect the selected conversion option or different colours for each i don't know....
this is just a display thing so clearly low priority
just thought i'd make note of it wile waiting for the next build

**Comment by openaudible** [comment]
Yeah, green means converted. You can filter by "has mp3" or "has m4b" using the search tab. From there you can decide to convert in another format. I'm up to my eyeballs in feature requests.. love them but this one I'm closing.
