### ISSUE TITLE
Excessive or invalid metadata when exporting to mp3

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#1357]
i generally export to M4B so i don't generally see these issues but i needed a few audiobooks in m4a (which this app doesn't convert to) or mp3 which is fine for  my needs here so so far so good, when i exported the books then opened them in Kid3 which i use to edit my metadata i notice the mp3 files have issues:

these are not hard for me to fix manually but a few are strange to see

i see a number of chapter fields - there should be none in mp3 files
Table of Contents : tee <- i have no idea how this got in there
there is a (c)des field at the end but the generic description field is blank
Language should be 3 lowercase letters only so english -> eng - not hard for me to fix

i am unsure how i can get a large volume of test data to you other than sending the audio files?
is this something that needs/should be fixed?

**Comment by openaudible** [comment]
We use ffmpeg and write a meta data file out with each conversion. We log everything to File: Debug Window.
The meta data  .txt file should stay around for a few minutes after conversion, so you can make a copy and should be able to reproduce the whole convert and add meta process. (It is somewhat convoluted.) If you can recommend a change to the meta file we create for mp3, we can make a change. Sending a file is also fine and I can probably create a test ffmpeg command.

**Comment by feldegast** [comment]
well the simplest change would be to not write chapter data to mp3 files, it is not supported all it does is add a lot of strange custom entries
i would need to find where this txt file is? same place as the new mp3? in temp??

**Comment by openaudible** [comment]
We use ffmpeg to encode the chapters. Calling ffprobe displays the chapters. So the industry standard app for encoding should be supported by the tagging/player app(s). Emailed you an example.

**Comment by openaudible** [comment]
Closing as I think chapters are supported in mp3 with ffmpeg/ffprobe. Thanks tho!
