### ISSUE TITLE
Clicking on Cancel to close "Edit Book" throws a "Index Out Of Bounds" error message

### ISSUE THREAD

**Issue by ZLoth** [openaudible/openaudible#1362]
This issue is occurring with OpenAudible 4.1 on Windows. It also takes _multiple_ open and cancels before this issue occurs. 

Screenshot of error message:
![OpenAudible 2024-03-01 18-28-20](https://github.com/openaudible/openaudible/assets/6700159/e7a1abf6-fc54-47cd-a251-76e7a25a28ac)

Recording of error message:
https://github.com/openaudible/openaudible/assets/6700159/65b7ada6-88d3-490a-a714-dac4be4463e9

[Log File.txt](https://github.com/openaudible/openaudible/files/14467188/Log.File.txt)

**Comment by openaudible** [comment]
Thank you for the report. Fixed (hopefully) in 4.1.0.2 beta. https://openaudible.org/beta
