### ISSUE TITLE
Library location directory isn't properly escaped in the Summary panel

### ISSUE THREAD

**Issue by ndouthit** [openaudible/openaudible#1364]
The library location directory isn't properly escaped on Windows if your username starts with an N. For example, my username is "natha" which would make the library location directory "C:\Users\natha\OpenAudible". The "\n" is interpreted as a newline character causing the output to print to a new line.

I've seen this in the Summary panel when you first launch the app:
> Welcome to OpenAudible! To get started quickly, there is a quick setup guide in the documentation (type F1).
> Your audio output encoding is set to M4B which can be changed in the Edit > Preferences...
> Your library location is set to C:\Users
> atha\OpenAudible which can be changed with File> Manage Libraries. 
> To sync with Audible, select the menu Controls: Connect to Audible. 
> Thank you for trying OpenAudible!

**Comment by openaudible** [comment]
Nice catch. Will fix.

**Comment by openaudible** [comment]
Fixed in 4.1.1.
Thank you!
