### ISSUE TITLE
Get Info Window Issue

### ISSUE THREAD

**Issue by djmccullers** [openaudible/openaudible#1365]
When I select a book in my library and click the "Get Info" menu item under "Actions", the "Edit Book" window appears like so:
![Initial](https://github.com/openaudible/openaudible/assets/11414262/85c8a281-9c0a-4170-aec4-60973fe7f648)

A few of the labels are truncated. If I grab the right side of the window to expand it, it expands to appear like so:
![Expanded](https://github.com/openaudible/openaudible/assets/11414262/cbf3c3fe-a589-446b-ab73-16ad3b8acb76)

Note that the buttons at the bottom of the window are no longer visible. This is regardless of how small the move is. The window cannot now be resized at all and no information can be saved.

This is running under Linux Mint 21.3 Virginia.
I'm running the AppImage version of Openaudible 4.1 

Please let me know if I'm doing something incorrect or if you need more info.

Don

**Comment by djmccullers** [comment]
While 4.1.1 fixes the issue of the labels being truncated, 
![Initial2](https://github.com/openaudible/openaudible/assets/11414262/520ed7ac-a6ee-49fc-9ef8-65e1a7d642e5)

if the window is expanded, the buttons at the bottom STILL disappear and cannot be re-displayed. Also, the window size can no longer be adjusted.
![Expanded2](https://github.com/openaudible/openaudible/assets/11414262/1a1aba3c-d6fc-4a9a-98d6-9acb71403350)

**Comment by openaudible** [comment]
Can you check it in version 4.2.1 ? Sorry for the lack of reply here..

**Comment by djmccullers** [comment]
Sorry, I still get the same result. When I adjust the window the buttons
disappear and the window can no longer be adjusted. See attached for end
result.

Don McCullers
781 361 9872

**Comment by openaudible** [comment]
Thanks... I am able to reproduce and will attempt a fix.

**Comment by openaudible** [comment]
Fixed for the next release, also in the latest beta: https://openaudible.org/beta
Thank you for the report!
