### ISSUE TITLE
Edit Metadata Feature Expansion

### ISSUE THREAD

**Issue by djmccullers** [openaudible/openaudible#1367]
In the current version, 4.1.1, it's possible to edit metadata for a single book. Can this be expanded so that a number of books can be selected and the metadata for all of them changed at once?  

This request is the result of downloading a number of books by Robert J. Crane in his "Girl in the Box" series. These have been "recorded" using "Virtual Voice". The problem is that none of these have the series name filled in.

Thanks!
Don

**Comment by openaudible** [comment]
Sorry, at this time that is beyond the scope of the application... There are many good tag editing apps out there.. 
Logging it as a feature request.. However, if you contact Audible, they might be able to fill in that missing data and then when you do a full library resync, it might get filled in.
