### ISSUE TITLE
Page load failed with error: too many HTTP redirects

### ISSUE THREAD

**Issue by iphonzors** [openaudible/openaudible#137]
Used to work great last week when I first set it up, now when I try to sign in from the action menu it give the error "Page load failed with error: too many HTTP redirects”. on a mac mojave 10.14.4 with Openaudible 1.5.0

**Comment by openaudible** [comment]
Not able to fix or reproduce. Google for more details. Attempting to log in with browser manually may help.

**Comment by iphonzors** [comment]
That's so much for replying, I did try those things at that time as well as restarting devices and it didn't work however the issue went away on it's own.  If you have this issue I recommend waiting a day or 2 to see if it just goes away. A side note I did just purchase 2 new books right before hand so maybe there is a time period that can cause issues to soon after purchase?  who knows.  app is working great again!
