### ISSUE TITLE
Dropdown lists have VERY low contract on MacOS

### ISSUE THREAD

**Issue by Xalior** [openaudible/openaudible#1370]
Closed dropdowns are basically invisible, opened dropdowns are very hard to see.

Attached screenshow to show problems.

MacOS Version: Ventura 13.6.3
OpenAudible Version: 4.1.1 

![image](https://github.com/openaudible/openaudible/assets/114975/abcb9dfa-b98d-4190-84a6-4ff3a0b37054)

Really liking v4, otherwise.  New progress UI is top notch.

**Comment by openaudible** [comment]
You're right. What color scheme are you using? You may need to change it from System to Dark.  The system theme doesn't set any foreground/background colors and lets the "system" determine what the controls should look like. Unfortunately with Mac, it doesn't always work.

**Comment by Xalior** [comment]
It already was "Dark", sorry. As is my System theme, not "auto".
![image](https://github.com/openaudible/openaudible/assets/114975/9f2329f6-fee9-470a-8227-2d5649c5e451)

**Comment by openaudible** [comment]
I wasn't able to reproduce this using the same settings. I don't know why. I'm using OA 4.1.1 on Sonoma 14.1.2.

<img width="1276" alt="Screenshot 2024-03-11 at 9 23 53 AM" src="https://github.com/openaudible/openaudible/assets/30847528/92317280-3cd3-4cbc-9f06-736d8a70ef57">

**Comment by openaudible** [comment]
Have you updated your MacOS to the latest version? Sonoma 14.1.2 or higher?

**Comment by Xalior** [comment]
No, my work requirement apps are not compatible.  If you cannot reproduce it I understandably get that you probably want to close this ticket.

**Comment by openaudible** [comment]
No problem.  What version of MacOS are you using? 
I had some code where if it was on Mac, I didn't set the background color of combos. But I can change that to if MacOS version less than 14 I can disable it.. but not sure what is the first version that has a working combo menu background. I can also google.

**Comment by Xalior** [comment]
Still on Ventura, as when I reported the bug - sorry! :)

**Comment by openaudible** [comment]
I created a beta that doesn’t set the background on combos when using older macos versions. 
https://openaudible.org/beta

**Comment by openaudible** [comment]
Fixed in beta. Will be in next release after 4.1.1
