### ISSUE TITLE
App Crash When Attempting Audible Login

### ISSUE THREAD

**Issue by akdsteel** [openaudible/openaudible#1373]
<img width="1014" alt="Screenshot 2024-03-21 at 12 24 25 AM" src="https://github.com/openaudible/openaudible/assets/164310567/dd2593e2-e8ae-4450-b127-a145f39e8973">

When trying to login to audible account the Open Audible application crashes and closes out. Tried downloading the up to date version and the beta.

**Comment by openaudible** [comment]
New beta has a alternate connect option
https://openaudible.org/beta

**Comment by openaudible** [comment]
Version 2.2 and higher have an alternate log in method that uses application dialogs instead of a web browser.
