### ISSUE TITLE
Setting path for playing audiobook

### ISSUE THREAD

**Issue by Aces-and-Jacks** [openaudible/openaudible#1375]
Couldn't find any closed issue to help me solve this. 

Basically I'm on mac and I'm trying to use a certain app to play an audiobook but whenever I do nothing happens. I'm probably typing in the path format incorrectly but I don't know how it should be typed. An example of a path would be helpful.

**Comment by openaudible** [comment]
The default on Mac is to play the book in the "Books.app". But you can change this to any app.
Go to the preferences, click on the "More... " button in the Applications and Browsers group.
Define the command line to launch the app. 
Just noticed a display bug on that "more" section, but it should work. If you have any questions, let me know which app you're trying to launch.

**Comment by Aces-and-Jacks** [comment]
I do 
- `/Applications/IINA.app`
- `%f/Applications/IINA.app`
- `%f=/Applications/IINA.app`

None of them work

**Comment by openaudible** [comment]
What does the File: Debug Window say?

**Comment by Aces-and-Jacks** [comment]
```
INFO: Command: Play
Mar 22, 2024 11:38:51 PM org.openaudible.desktop.swt.manager.AudibleGUI play
INFO: Request play Ghost Story file /Users/*****/Library/OpenAudible/books/Ghost Story - A Novel of the Dresden Files.m4b cmd /Applications/IINA.app
Mar 22, 2024 11:38:51 PM org.openaudible.desktop.swt.manager.AudibleGUI play
INFO: Playing: /Applications/IINA.app /Users/*****/Library/OpenAudible/books/Ghost Story - A Novel of the Dresden Files.m4b
Mar 22, 2024 11:38:51 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: /Applications/IINA.app "/Users/*****/Library/OpenAudible/books/Ghost Story - A Novel of the Dresden Files.m4b" 
Mar 22, 2024 11:38:51 PM org.openaudible.util.SimpleProcess lambda$runAsync$0
INFO: runAsync finished with error: org.openaudible.util.SimpleProcess@2e72a4a4

```

**Comment by Aces-and-Jacks** [comment]
And yes I can

**Comment by openaudible** [comment]
What is the correct command line command to play a book that works?

**Comment by Aces-and-Jacks** [comment]
> Are you able to play an m4b from the command line using IINA.app? (I am not familiar with that app.)

Yes I can

**Comment by Aces-and-Jacks** [comment]
> What is the correct command line command to play a book that works?

Leaving it blank. It opens the default iBooks but I don't know how its typed

**Comment by Aces-and-Jacks** [comment]
would it show in the log?

**Comment by Aces-and-Jacks** [comment]
```
NFO: Command: Play
Mar 22, 2024 11:43:30 PM org.openaudible.desktop.swt.manager.AudibleGUI play
INFO: Request play Death Masks file /Users/****/Library/OpenAudible/books/Death Masks - The Dresden Files, Book 5.m4b cmd 
Mar 22, 2024 11:43:30 PM org.openaudible.desktop.swt.manager.AudibleGUI play
INFO: Playing: Open -a Books.app %f /Users/****/Library/OpenAudible/books/Death Masks - The Dresden Files, Book 5.m4b
Mar 22, 2024 11:43:30 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: Open -a Books.app "/Users/****/Library/OpenAudible/books/Death Masks - The Dresden Files, Book 5.m4b" 
```
this is what shows for default

**Comment by openaudible** [comment]
I would try: Applications/IINA.app %f

Open a Terminal.app and type /Applications/IINA.app/ /path/to/filename.m4b and see if the book starts playing...

**Comment by Aces-and-Jacks** [comment]
I get `permission denied: /Applications/IINA.app/`

**Comment by openaudible** [comment]
Try in the More.. Applications and Browsers, Audio:
```
/Applications/IINA.app/Contents/MacOS/iina-cli %f 
```
That worked for me.

**Comment by Aces-and-Jacks** [comment]
You know that was what also fixed for another application that ran exe files

**Comment by Aces-and-Jacks** [comment]
I'll try

**Comment by Aces-and-Jacks** [comment]
It worked! Thanks

**Comment by Aces-and-Jacks** [comment]
With two other applications in the past I had to do that as well. Open app contents, go to macOS, select app executable...now that I think about it that makes sense. But it's hidden behind the `.app` extension, so it's not the fist thing I'd think of. I also don't do much with terminal files

**Comment by Aces-and-Jacks** [comment]
Also one last thing 
> Open a Terminal.app and type /Applications/IINA.app/ /path/to/filename.m4b and see if the book starts playing...

I know the issue has been solved, just wanted to say `afplay /Path/To/Filename.m4b` does this as well. Won't solve the issue but a little random bit of knowledge for anyone who comes across this

**Comment by openaudible** [comment]
Glad it worked! 

I've added an example to the preferences to make it a little more clear. 

  "Example: /Applications/VLC.app/Contents/MacOS/VLC %f"

Cheers
