### ISSUE TITLE
Error Creating new library

### ISSUE THREAD

**Issue by EmilyKPDX** [openaudible/openaudible#1377]
I was downloading my books to my harddrive and it is filling up. I have tried creating a new library to hold my downloads on external hard drives (2) that are new and empty, and both times I get the message:

Error creating new library

Unable to create new library
Java.lang.Exception: Directory is not empty D:\

what should I do?

**Comment by openaudible** [comment]
Creat an empty directory and select that as the new directory. It can be named anything.
