### ISSUE TITLE
Keine Synchronisierung möglich

### ISSUE THREAD

**Issue by Alexiel999** [openaudible/openaudible#1378]
Keine Synchronisierung möglich. Auch nicht nach neuer Anmeldung.

**Comment by openaudible** [comment]
After trying a Full Rescan from the Control menu.. feel free to send a bug report from the About Menu, using issue #1378. Or send a copy of the File: Log Window of any errors to us via our contact form. (Or here, but be sure to remove any security tokens or user name information.)
