### ISSUE TITLE
Issues with chapter metadata for "Alex Fletcher Boxset, Complete Series: Books 1-5"

### ISSUE THREAD

**Issue by ZLoth** [openaudible/openaudible#1380]
One of my acquisitions has been the _Alex Fletcher Boxset, Complete Series: Books 1-5_ (B078SH2ZCV). I'm able to get the chapter stops for books 1-3, but after chapter 187, we have a long "end credits" chapter with a length of 7 hours 53 minutes.

![image](https://github.com/openaudible/openaudible/assets/6700159/c364ae9c-656c-4519-abf5-f0c6d428b803)

Is this a metadata issue on Amazon's side, or is it a handling issue at OpenAudible's side? 

Here is the metadata:
[Metadata.txt](https://github.com/openaudible/openaudible/files/14894527/Metadata.txt)

**Comment by openaudible** [comment]
That looks like bad meta data from amazon. Are the chapters correct on the Audible player?

**Comment by ZLoth** [comment]
Yup, looks like a Audible data issue. Thanks for confirming.

![Screenshot_20240406-141820](https://github.com/openaudible/openaudible/assets/6700159/4086f6a4-3426-454c-a13c-4d8264a86928)
