### ISSUE TITLE
[Crash] Not able to connect/login to Amazon JP

### ISSUE THREAD

**Issue by zhht1204** [openaudible/openaudible#1382]
It comes out an error page at the last step each time. As the pic below.
![image](https://github.com/openaudible/openaudible/assets/4829202/2628d59a-763d-4911-8d28-c4b0db63c733)
Which the japanese in the page means "Sorry, this web address is not provided by us (officially)".

Maybe because the callback address of login has been changed?

My Openaudible version is 4.1.1.

**Comment by openaudible** [comment]
Hmm. The map landing page is usually the one that contains your credentials and is basically a "success" page (that doesn't actually get shown to the user.)
I haven't gotten any other reports, but not sure how many in Japan are registering.
Can you try the latest beta https://openaudible.org/beta and see if that works? We've switched some code around for that and also have a login that doesn't require a browser. 
If you get that or a similar error, feel free to send a bug report from the About men.

**Comment by zhht1204** [comment]
Oh thanks for quick response at first.
I've tried to use the beta version, and the triditional web page login is still error. As attached below.
![image](https://github.com/openaudible/openaudible/assets/4829202/1bfc3fb8-5008-475e-9d08-eac4a5971325)
![image](https://github.com/openaudible/openaudible/assets/4829202/de6972cf-6b89-4481-b290-1cf6a5f8d0e9)

And then I tried the new login method, as without browser.
![image](https://github.com/openaudible/openaudible/assets/4829202/404c1633-1eba-4d69-8552-bddb2b266215)
And provided my account. But because of network issues the login failed too, so I cannot confirm if it works.
![image](https://github.com/openaudible/openaudible/assets/4829202/89971079-426b-4d16-bdb4-5d63ec0e7f00)
I did not find the option to configure network proxy. Did I miss it?

**Comment by openaudible** [comment]
Check that your firewall isn’t blocking network access. You can test it by checking for an application update under the about menu.

**Comment by zhht1204** [comment]
> Check that your firewall isn’t blocking network access. You can test it by checking for an application update under the about menu.

My Windows firewall is all closed. And about network, there're 2 facts maybe I need explain.
1 is that it's difficult/unable to access outside network world using China network, so I use Clash proxy to access, and it's able to connect using browsers but OpenAudible seems not be using the system proxy correctly. I checked the preferences in OpenAudible about network but there is only one configuration that which exe to use when open book? I'm not sure.
2 is that Audible JP service is limited to access only in Japanese.
Anyway the proxy settings are necessary I think. My situation just for reference.

Regards & Thanks

**Comment by zhht1204** [comment]
I just tried the US site login, and got the same result. Afterwards I searched the official document about audible authorization, it seems correct to go to the landing page as `amazon.(com/co.jp)/ap/maplanding` . 
But in my browser I always get the error page as 
![image](https://github.com/openaudible/openaudible/assets/4829202/a49cc92a-7453-4186-8542-e75210f222a3)
Weird.

**Comment by zhht1204** [comment]
![image](https://github.com/openaudible/openaudible/assets/4829202/7e498a44-4f16-45d0-befb-bfaa42526168)

**Comment by openaudible** [comment]
A network timeout is very unusual. 

I would need you to send a bug report from the About dialog after it fails.  Be careful not to send logs about logging in to here as they may contain sensitive information.

Let me know when you have and I can take a look.
