### ISSUE TITLE
Problem with library

### ISSUE THREAD

**Issue by EmilyKPDX** [openaudible/openaudible#1383]
I successfully downloaded my library (which took a while) and had it convert. Went back to update it and now getting this message. 
![IMG_0251](https://github.com/openaudible/openaudible/assets/164567667/c8af3d10-72b2-4205-a518-1476937d3ce4)

**Comment by feldegast** [comment]
the 1st menu entry on the file menu shows a log of what the application is doing, it might help the developers if this was posted to this bug report....

**Comment by openaudible** [comment]
That is a corrupt json file. You may need to rename it broken.json and restart the app. I'm not sure what would cause that. If you wanted to email it to us to diagnose, contact us through our web form and we'll reply with our email address.
Sorry that happened. Perhaps also check that you have plenty of disk space and that your disk is not failing by running a disk check on it. Could also happen if you edit the file directly.
