### ISSUE TITLE
full library sync causes error messages that are harder to diagnose than they need to be as only ASIN provided to identify the book

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#1384]
when i do a full library sync i get a number od errors in the log file like the one below but there is insufficent information for me to easily find the relevent book
would it be possible to get the title, author, narated by and duration to the log file so it is easy to identify the audiobook that is causing the error?
this is more a request for improvment to the log file rather than an actual bug
it says the title is missing but the title should be available from the table listing the audiobooks....

Apr 20, 2024 10:14:27 PM org.openaudible.audible.api.APIToBook parseBook
SEVERE: checkBook error: required:title missing from , inspect:{"asset_details":[],"is_ws4v_enabled":false,"is_buyable":false,"is_pdf_url_available":false,"rating":{"overall_distribution":{"num_ratings":2,"display_stars":5,"num_one_star_ratings":0,"average_rating":5,"num_four_star_ratings":0,"num_three_star_ratings":0,"num_five_star_ratings":2,"num_two_star_ratings":0,"display_average_rating":"5.0"},"performance_distribution":{"num_ratings":2,"display_stars":5,"num_one_star_ratings":0,"average_rating":5,"num_four_star_ratings":0,"num_three_star_ratings":0,"num_five_star_ratings":2,"num_two_star_ratings":0,"display_average_rating":"5.0"},"num_reviews":0,"story_distribution":{"num_ratings":2,"display_stars":5,"num_one_star_ratings":0,"average_rating":5,"num_four_star_ratings":0,"num_three_star_ratings":0,"num_five_star_ratings":2,"num_two_star_ratings":0,"display_average_rating":"5.0"}},"asin":"B00WN8TIBY","is_vvab":false,"is_in_wishlist":false,"customer_rights":{"is_consumable_indefinitely":false,"is_consumable":false,"is_consumable_offline":false},"is_world_rights":false}
Apr 20, 2024 10:14:27 PM org.openaudible.audible.LibraryScanner getProducts
INFO: no book found for asin:B00WN8TIBY

**Comment by openaudible** [comment]
That usually means a book has been deleted. We go to get the information and it is essentially blank.. but doesn't return a simple file not found type message. Usually those messages can be safely ignored, since there isn't anything we can do about them.

**Comment by feldegast** [comment]
but as you are working your way through a table of books, if a file has beed deleted (i think you are right) couldn't you return the book title text from the table if the title can't be obtained from the original file? the table still has the title text i think even if the file is deleted....

**Comment by feldegast** [comment]
i understand what your saying and your right but the list of books that is being checked that generates the error containst a title can this title be added to the error so it is easier to identify the line in the app that needs to be acted on?
when you have over 100 books in the app, finding the broken book is not trivial when all you have to go on is the ASIN number.... if it can identify the title that is in the table by adding it to the log it would make it significantly easier

**Comment by openaudible** [comment]
I will improve the logging.

**Comment by openaudible** [comment]
Also, the problem book is the one with ASIN: B00WN8TIBY  Type that into your OpenAudible books search filter and it should find it. That _probably_ means the book is no longer available on Audible, but it may have also changed ASIN or something else.
