### ISSUE TITLE
checking for newer versions mis-states latest beta versions as release versions

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#1387]
![Screenshot 2024-05-02 110613](https://github.com/openaudible/openaudible/assets/1029921/b731143d-17e9-4016-b32c-2410f5f628cc)
the dialogue says it is the latest "release" version but in the app, it says it is a beta version
the simplest fix would be to remove the word "release" from the dialogue

**Comment by openaudible** [comment]
Until 4.1.2 or 4.2 are released, you are using the latest available release. (We got a few things in progress!) As soon as we release a newer prod version that message will be replaced with a notice about a better version.
