### ISSUE TITLE
Error Converting AAXC file

### ISSUE THREAD

**Issue by Mura20** [openaudible/openaudible#1390]
I got an error while trying to download and convert three of my audiobooks through the application (I'm using the latest release 4.1.1). They show up in the folder as aax, not aaxc, though I'm not sure whether or not that's normal. The exact error reads:

Error converting: Invalid aaxc file, missing audible_key/audible_iv pair.

**Comment by openaudible** [comment]
That means the file was not downloaded from OpenAudible. Make sure you use OpenAudible for getting the files. You can’t grab them from an Android device, for example.

**Comment by Mura20** [comment]
I did download them through OpenAudible. I was able to fix it by going in and deleting the files and forcing a redownload though.
