### ISSUE TITLE
multi-part MP3 -> M4B conversion only doing first part

### ISSUE THREAD

**Issue by cornickj** [openaudible/openaudible#1394]
I've imported a number of multi-part MP3 audiobooks to OpenAudible 4.1.1 and when I try to convert them to M4B it appears to work, but the file size is very small (less than a single MP3 chapter), and the file only has audio for the first chapter, the rest of the book is silence. All the chapters appear in the file, just without any audio.

I've confirmed that the individual MP3s do have content, so it isn't a bad source, just the conversion.

**Comment by openaudible** [comment]
Hmm. I might need more details. Generally going from m4b to mp3 or vice versa is lossy and not recommended. 

If you want, quit and restart OA then try again and submit a bug report using the about menu and I can take a look

**Comment by openaudible** [comment]
Bad news to report.. but we're disabling the ability (inability) to convert a directory of mp3/m4b files to the alternate file type. Next version will not allow you to do it. You'll lose audio quality and end up with two of each chapter. No really good reason to go from mp3 to m4b.. Could lead to unwanted results. 
But do appreciate the report.
