### ISSUE TITLE
[FEATURE REQUEST] Place split-books into subfolder by language

### ISSUE THREAD

**Issue by christianmerges** [openaudible/openaudible#1395]
I have different languages in my library. When the split-books are placed into folders by language, the application for listening directly access these folders, because there is an extra library per language.

Also after creating the split-book, the big m4a file and attachment(s) could be deleted, because it;s redundant.
A setting would be nice, to automatically create split book after conversion to m4a.

**Comment by openaudible** [comment]
Noted but won’t happen until custom paths are implemented. Thanks.
