### ISSUE TITLE
[FEATURE REQUEST] Delete incomplete split-book

### ISSUE THREAD

**Issue by christianmerges** [openaudible/openaudible#1396]
In case the split-book operation is canceled, the incomplete book should be deleted or at least a question should pop-up to ask if i wanna do so.

**Comment by openaudible** [comment]
Good idea. It should. What error is stopping the split?

**Comment by christianmerges** [comment]
no error at all. Just a toooooo big batch and need to reboot the machine.

**Comment by openaudible** [comment]
Hmm. We definitely delete the split book directory if it fails, but if you force quit the app (by rebooting) It won't do that. 
It really shouldn't hang on large split jobs-- it may just take some time to finish. Keep an eye on the File: Log Window as it does the splitting and hopefully you'll see it continue to make progress. Of course check your hard drive for space.

**Comment by christianmerges** [comment]
It is rather like this: Other things are also happen on the same machine, which may require a reboot, so i have to abort the split process before initiating the reboot. Atm i have to search for the aborted split book and delete the folder manually, because if i don't do, the next time i start the batch, this unfinished split book would be recognized as already done.

**Comment by openaudible** [comment]
I’ll check that quitting the app cancels any split jobs.
