### ISSUE TITLE
Allow marking a book as downloaded and moved

### ISSUE THREAD

**Issue by ericthelin** [openaudible/openaudible#1397]
This is similar to ignored. But the listing would still show up just like a normal book but it would allow setting to automatically download books even if the get moved to another location.

**Comment by openaudible** [comment]
I'm not sure I follow or what the use case for that is. We don't recommend moving files manually, but you can rename them using the Action: Rename Book feature. 
We keep UI changes to a minimum as each additional change adds to complexity that makes the product less user friendly.
