### ISSUE TITLE
Podcasts not detected in v4.2.0

### ISSUE THREAD

**Issue by Kalthax** [openaudible/openaudible#1399]
I see v4.2 is supposed to have support for downloading Audible podcasts. But I tried both a quick and a full library refresh in Open Audible for my large library, and it reports there are zero podcasts. I definitely have several in my library. I looked through the documentation and settings and I don't see any mention of it being necessary to do anything special to detect and download podcasts, but did I miss something or is this a bug?

**Comment by openaudible** [comment]
So you need to enable podcasts in the "Manage Libraries" section. They are still off by default for this release:
https://openaudible.org/docs#podcasts

**Comment by Kalthax** [comment]
Yup, would never have found that. Thanks.
