### ISSUE TITLE
Chocolatey package

### ISSUE THREAD

**Issue by elpatron68** [openaudible/openaudible#140]
Hi,

I just wanted to let you know that I have published a package for openaudible on chocolatey.org for easy and quick installation / upgrading. See https://chocolatey.org/packages/openaudible

Markus

**Comment by openaudible** [comment]
Cool. Thanks!

What about updates? I am releasing a 1.5.1 today.

It might be nice if your script could parse the latest version from here: and download it
https://openaudible.org/swt_version.json 
and change from sha256 to my calculated md5. 

Or parse: https://api.github.com/repos/openaudible/openaudible/releases/latest 

(which is a bit uglier, but maybe someone has already done something like it.)

Or maybe there is a way to point chocolatey to: https://github.com/openaudible/openaudible/latest

Anyway, good luck!

**Comment by elpatron68** [comment]
I´m monitoring the Github releases and manually update the package atm.  Maybe I will write a script in the future. Updated the package to 1.5.1 - validation from the moderators takes it´s time...

**Comment by elpatron68** [comment]
I now made a script which parses `https://openaudible.org/swt_version.json` and builds a chocolatey update  if a new version is available.

**Comment by openaudible** [comment]
Hi @elpatron68 

Cool. I just updated our code.. and also tried to make a chocolateyinstall.ps1 that I added to the release.. 
https://github.com/openaudible/openaudible/releases/tag/v1.5.3
Was curious what the steps are that are used to update a release.. but didn't get very far.. 

But apparently some blind people are using choclatey to make the install easier, which is cool. #183  

Cheers

**Comment by elpatron68** [comment]
Hi,

I have made a daily running Python script that checks https://openaudible.org/swt_version.json for an update, generates a `chocolateyinstall.ps1` with checksums and download urls for openaudible and pushes the updated package to chocolatey.org. The script has updated openaudible to v1.5.3 yesterday. Chocolatey has published the package after two automated tests to it´s catalogue.

As of the fact that our package now is approved as "trusted package", the process of publishing does not require a manual audit (which would at least take a couple of days).

Bye,
Markus

**Comment by openaudible** [comment]
Thanks!

**Comment by openaudible** [comment]
Hey Markus,
Let me know if I can send you some license codes.. And if you need me to take over submitting the OA chocolatey updates. Check in any time..

**Comment by elpatron68** [comment]
Hi,

I found an erroneous regex in my update script. Fixed it & committed 2.0.3. The Chocolatey package should update soon and will probably be up-to-date in the future.

If you like to maintain the package by yourself, you´d have to contact the Chocolatey Site-Admins to become the (co-) maintainer of the Openaudible package: https://chocolatey.org/packages/openaudible/2.0/ContactAdmins

Maybe that is the best way to always keep the package updated.

Thanks for offering a license key! I already bought one as I have an idea of how much work the develpoment a project like this can mean.

Bye,
Markus

**Comment by elpatron68** [comment]
The OpenAudible Chocolatey package is now a so called [Trusted Package](https://chocolatey.org/faq#what-is-a-trusted-package). It will be automatically validated after the upload of an update. So, we don´t have to wait for a human moderator to validate the package.
