### ISSUE TITLE
OA doesn't see all podcast episodes nor all podcasts

### ISSUE THREAD

**Issue by Kalthax** [openaudible/openaudible#1402]
OpenAudible was able to download a single episode (the first) of two of the podcasts I am subscribed to, but it doesn't see any other episodes nor any other podcasts.

The documentation mentions that OA works with any saved podcast episode. Does this mean something specific? I am following several podcasts and I tried following a new one and it didn't work. The podcasts OA can see have 8-12 episodes each. Is there something special I need to do to get OA to see all of the podcasts and episodes I follow on Audible?

**Comment by openaudible** [comment]
Go to the Manage Accounts. Check the Enable Podcasts checkbox.

**Comment by Kalthax** [comment]
There is no podcast checkbox under Manage Accounts. There is only the checkbox under Manage Libraries and that is checked already.
