### ISSUE TITLE
"Unable to Convert" due to previous, low-quality MP3 conversion

### ISSUE THREAD

**Issue by Lingoue** [openaudible/openaudible#1404]
Hello - 

I'm trying to convert a book linked to my Audible account into MP3 but am unable to. I had already done so, then realized the default bitrate was much lower than I wanted, so I adjusted the preferences and tried to do it again. However, I find the MP3 conversion option grayed out and in the book info it says, "Status: Unable to convert, has converted MP3".

I've tried troubleshooting by deleting the lower- bitrate MP3, deleting then re-establishing my coonnection to the accoount, etc, but the problem remains. It seems like once an MP3 conversion has been made, it won't allow me to try again with a better bitrate.

Kindly let me know how to solve this; thanks so much for any assistance.

**Comment by openaudible** [comment]
If you manually delete an mp3, use the Controls: Refresh Files to let open Audible know files changed. Then convert to mp3 should be available as an option. 

Check that there aren’t two copies by mistake in a mp3 and books directory.

**Comment by openaudible** [comment]
Be sure to upgrade to the latest version.
