### ISSUE TITLE
Audible book converted to MP3 - won't play on Sandisk sport clip - 

### ISSUE THREAD

**Issue by ennisdcs** [openaudible/openaudible#1405]
Converted an Audible book from aax to MP3 - and then copied to Sandisk sport clip.  I can see the file(book) but when I attempt to play it - it will go to pause mode.  If I hit play it will try then go to pause mode again. 64k bitrate - no vbr.

**Comment by openaudible** [comment]
Haven't heard of this problem before. Here are some things to try: 

You can try splitting the book.. Maybe it is too large to play? 
Do other mp3's work? Anything different between the two files? 
Check for a firmware upgrade for the player.
You mention not VBR, which means CBR.. which is usually "more compatible"..
Have you googled the Sandisk model and checked for similar reports?
Make sure the memory card is working. Run a disk check on it from windows/mac?

**Comment by ennisdcs** [comment]
I adjusted to 64kb and vbr - works
    On Thursday, May 30, 2024 at 04:41:24 PM MDT, openaudible ***@***.***> wrote:  
 
 


Haven't heard of this problem before. Here are some things to try:

You can try splitting the book.. Maybe it is too large to play?
Do other mp3's work? Anything different between the two files?
Check for a firmware upgrade for the player.
You mention not VBR, which means CBR.. which is usually "more compatible"..
Have you googled the Sandisk model and checked for similar reports?
Make sure the memory card is working. Run a disk check on it from windows/mac?

**Comment by openaudible** [comment]
Strange. Glad its working now! 
If you want to comment with your model number, others may find the answer when googling.
