### ISSUE TITLE
Open Audible 4.2 says I need to convert all my files to mp3

### ISSUE THREAD

**Issue by byronholloway** [openaudible/openaudible#1407]
It shows all my books, and shows that I have MP3's but none of my books shows to have an MP3 File linked.

**Comment by openaudible** [comment]
This is a bug affecting old libraries with "m4b" and "mp3" directories.
We have a fix in beta 4.2.0.3 and will release a 4.2.1 shortly.
https://openaudible.org/beta
Thank you for the report.

**Comment by openaudible** [comment]
Fixed in 4.2.1. You will be asked to migrate your older style library to the new format. Should take care of any duplicates.
