### ISSUE TITLE
[FEATURE REQUEST] Dolby Atmos Support

### ISSUE THREAD

**Issue by simonhull** [openaudible/openaudible#1408]
With Audible rolling Dolby Atmos support out for some of their titles it would be great to have the option to grab those versions. More and more devices are getting Atmos support and even if you don't have an Atmos compatible sound system, you could still reap the benefits of the surround sound.

**Comment by openaudible** [comment]
At this point I don't see any ability to request that-- but it is possible it is already part of the M4B file created. As it is just added to the existing audio file and we don't do much to it.

**Comment by simonhull** [comment]
I did a bit more digging, there seems to be a detailed ongoing discussion about the mechanisms required over in this thread: https://github.com/mkb79/audible-cli/issues/155

**Comment by openaudible** [comment]
Yikes. No plans to support at this time. Thanks for the info! Looks intriguing
