### ISSUE TITLE
Is there a way to change the install location?

### ISSUE THREAD

**Issue by twistedgunslinger** [openaudible/openaudible#1409]
I have open audible on my laptop and I have been a member of audible since it started.  I have over 700 titles and downloading them all will overfill my c drive.  Is there any way to change the install location to a D drive OR is there a way just to change where the program downloads and outputs files even if the install stays on the c drive?  I searched the issues and didn't get a match on this question. Thanks!!

**Comment by openaudible** [comment]
You bet.
To change your library location, go to "File: Manage Libraries" menu. Then click the "Move Library".
https://openaudible.org/docs#manage_libraries
