### ISSUE TITLE
Clean install - not importing all books in Library

### ISSUE THREAD

**Issue by livtin** [openaudible/openaudible#141]

**Comment by livtin** [comment]
I did a clean install of my OS (18.04) and OpenAudible.  I have re-downloaded my library and have 19 books on my drive that will not show/import in the app

**Comment by openaudible** [comment]
Make sure when you view your library in the openaudible browser you set the filter to "All Time". Other than that, you'll need to look through the logs and see if the missing books are getting scanned..
