### ISSUE TITLE
Add new option to list books by Audible account nickname

### ISSUE THREAD

**Issue by fivegomad** [openaudible/openaudible#1412]
There is no obvious way to list/sort books by a specific audible account when multiple accounts are used.  There is an option for "User ID" but it's not an obvious account name - eg the nickname given to the account when it was set up.  Either User ID should be changed to return the nickname, or a new menu reveal/sorting option is given for "Nickname". 

When there are multiple accounts, you might want to know in whose Audible account a particular book is located.

**Comment by openaudible** [comment]
Good idea.

**Comment by openaudible** [comment]
Added to beta: https://openaudible.org/beta
