### ISSUE TITLE
Temporary license for debugging

### ISSUE THREAD

**Issue by rstewa** [openaudible/openaudible#1413]
I have a desktop Audiobook player called [Audibly](https://github.com/rstewa/Audibly). I have had someone reach out about my app having issues importing .M4B files that were created with OpenAudible. I'd like to be able to debug these issues but I don't have a license. Is there any way I could get a temporary license or temporary access to create .M4B files? I don't need it permanently. The problem I have is that I can't ask the guy with the issue to send me his .M4B file since I don't want to break any copyright laws.

**Comment by openaudible** [comment]
Of course. Will get you a full license. 
Please ping me at https://openaudible.org/contact?subject=other

**Comment by feldegast** [comment]
I believe you also can use the following command in Linux to convert from mp3 to m4b using ffmpeg too

for i in *.mp3; do ffmpeg -i "$i" "${i%.*}.m4b"; done
this should create files in the same m4b format.?
if the files are not the same it would be good to know

**Comment by rstewa** [comment]
Does Open

> Of course. Will get you a full license. Please ping me at https://openaudible.org/contact?subject=other
> 
> Or just let me know your email.

I sent you a message on your website. Thank you!

**Comment by openaudible** [comment]
Looks like a good app and happy to help where I can.
