### ISSUE TITLE
Feature request: Split Report to be divided up into sections

### ISSUE THREAD

**Issue by ZLoth** [openaudible/openaudible#1414]
It would be nice if the Split report was divided up into three sections:

- Good
- Skipped
- Errors

This would make it easier to read especially when splitting a large number of audible books.

**Comment by openaudible** [comment]
Added. And fixed split report that incorrectly showed ** Split Report ** repeatedly. 
In beta: https://openaudible.org/beta
Will be fixed in 4.2.2.

**Comment by openaudible** [comment]
Fixed in 4.2.2
Thank you.
