### ISSUE TITLE
Feature Request: Right-click → Copy cell

### ISSUE THREAD

**Issue by ZLoth** [openaudible/openaudible#1415]
It would be nice if there was a way to right-click on a cell and copy the contests. 

My current workflow for Audiobooks is as follows:

1. Convert the Audible book to a MP3 file and split the chapters.
2. Use MP3Tag to fix the titles, add chapter titles where necessary, and rename the files.
3. Transfer the work to my server which has AudioBookShelf running

Sometimes, only the short title is part of the book title after conversion. I prefer the "Long Title" to make it easier, and right now, I have to bring up the book information to be able to copy the title.

**Comment by openaudible** [comment]
Have you tried "CTRL-C" ? It should copy the contents of the Book Table in tab delineated format.
Also, you can fix the tags in OpenAudible, select the book, Get Info, modify the tags... it should also re-encode any changed files.

**Comment by ZLoth** [comment]
Thank you, I'm looking forward to the next release @openaudible .

**Comment by openaudible** [comment]
You're welcome. And just to be clear... the current version of OpenAudible supports copy cells from table and editing tags.
