### ISSUE TITLE
Feature Request: Disable the "(Unabridged)" in Album tag

### ISSUE THREAD

**Issue by ZLoth** [openaudible/openaudible#1416]
Is there any way to disable the (Unabridged) tag being added to the Title field of a MP3 during the conversion process?

**Comment by openaudible** [comment]
It should automatically be removed from the title. If you search your library (CTRL-F) does the word Unabridged show up in the book table under the title? Maybe re-encode the book (delete or move the mp3 and right-click the book convert to mp3. Then do a Get Info and look at the "Book Report" to see what the tags are. If still there, we can investigate. (Send a copy of the book report to info at openaudible dot org.

**Comment by ZLoth** [comment]
Here is the main OpenAudio screen for "Spacesuit: Fashioning Apollo" - ASIN: B00K7105ES:

![image](https://github.com/openaudible/openaudible/assets/6700159/12b30902-fd4e-4581-959f-99d4f6d8d6a8)

Tags screen:

![image](https://github.com/openaudible/openaudible/assets/6700159/dc575d9b-9242-4748-8f0b-e044e44a02a6)

Files screen:

![image](https://github.com/openaudible/openaudible/assets/6700159/c06154b4-0b03-4349-b800-06b6e9f06162)

But when I look at the MP3 file using MP3TAG:

![image](https://github.com/openaudible/openaudible/assets/6700159/e71c3918-0b51-4dc5-8d39-a571f0bd1cf8)

**Comment by ZLoth** [comment]
Here is the preferences screen:

![image](https://github.com/openaudible/openaudible/assets/6700159/01d32ac9-14b4-4ef6-a796-8fabee383b8b)

**Comment by ZLoth** [comment]
When I use M4B instead of MP3, the issue does not occur:

![image](https://github.com/openaudible/openaudible/assets/6700159/edd75569-0f95-4a2a-9321-80a0a38b723e)

**Comment by openaudible** [comment]
When was the MP3 created? 
Select Get Info for the book, go to the Book Report tab, copy and paste to info at openaudible dot org.

**Comment by ZLoth** [comment]
> When was the MP3 created? Select Get Info for the book, go to the Book Report tab, copy and paste to info at openaudible dot org.

For reference, I created it today. The book was purchased today. 

Email was sent per this posting.

**Comment by openaudible** [comment]
Ok. Only tihng I can think of the AAX file includes the unabridged tag and it is getting copied over.
Looks like our book report feature was broken.
Can you make sure the AAX file is present and re-do the Book Report for me (by email) using the beta? 
https://openaudible.org/beta

**Comment by ZLoth** [comment]
>Can you make sure the AAX file is present and re-do the Book Report for me (by email) using the beta? (See how your "Files tab" doesn't have the AAX? (Why is that? is delete aax files automatically turned on?) https://openaudible.org/beta

I had turned on AAX deletion to save some space when converting a batch of books. That feature has been unchecked, OpenAudible_4.2.1.3_beta_x86_64.exe has been installed, and a set of reports and screen shots was emailed at 3:36 PM Central Time.

**Comment by ZLoth** [comment]
OpenAudible_4.2.1.4_beta_x86_64.exe has fixed the issue.

![image](https://github.com/openaudible/openaudible/assets/6700159/736b9c4b-ca41-449c-9a7b-7f83a679aef6)

**Comment by openaudible** [comment]
Fixed in 4.2.2
Thank you.
