### ISSUE TITLE
When splitting books, the title no longer updates in the progress window

### ISSUE THREAD

**Issue by ZLoth** [openaudible/openaudible#1417]
Something which I noticed.... when splitting an audiobook, the title of the book no longer updates in the progress window. Note that the book does update in the main OpenAudible window. 

![image](https://github.com/openaudible/openaudible/assets/6700159/bcad42ac-19ce-46eb-b153-54b3610942f1)

**Comment by ZLoth** [comment]
Here is a partial recording of when you start up the split process. 
https://github.com/openaudible/openaudible/assets/6700159/5fcc1b3f-f880-419e-b3f9-0fbc5b2e916d

**Comment by openaudible** [comment]
You’re splitting multiple books and the title of the second and subsequent books isn’t updating? 
I can check. But also feel free to mock up what you would rather see.

**Comment by ZLoth** [comment]
> You’re splitting multiple books and the title of the second and subsequent books isn’t updating? I can check. 

That's correct.

> But also feel free to mock up what you would rather see.

I think it would be nice to incorporate it as part of the jobs listing that you incorporated a release or two ago.

**Comment by openaudible** [comment]
Fixed in next release.

**Comment by ZLoth** [comment]
Looking forward to the next release.
