### ISSUE TITLE
Feature Request: 

### ISSUE THREAD

**Issue by chompinlynx** [openaudible/openaudible#1420]

**Comment by chompinlynx** [comment]
I no longer do full library sync because i rename my book series to a custom format e.g. James Bond 01 - Skyfall. When i do a full sync it renames all my titles which erases hours of work. 
The feature request is to be able to have a option to preserve metadata that has been edited such as titles while other options like the photo etc is updated.

**Comment by openaudible** [comment]
Full Rescan doesn't rename books. The quick rescan just starts at the last rescan or book purchase date. Which should just get new purchases.

**Comment by chompinlynx** [comment]
It does rename book titles. Please see ticket #1419

**Comment by openaudible** [comment]
Fixed in 4.3. Uncheck the "Update Metadata on full rescan" in the Manage Libraries dialog.

**Comment by chompinlynx** [comment]
Dude you gotta be kidding me. I unchecked the box, exited the dialog box, then did a "quick sync" and it freaking changed ALL of my titles again! I went back to the box to double check and realize that it doesnt stay unchecked when you leave the dialog box. There is no save button or anything to save your preferences either. This happened to my backup library so now im out of days of work!!!

**Comment by chompinlynx** [comment]
@openaudible see above ^ 
Can you add a new feature to resolve this where i can override my titles with my file names?

**Comment by chompinlynx** [comment]
Also when you said that changing the title can take a long time to reencode, i dont understand how the audible sync can update/rename all the title metadata for 800 books in 2 minutes while when i manually update the title for one 10+ hour book and hit save changes it take 2-3minutes... There is definitely a disconnect here..

**Comment by chompinlynx** [comment]
Also since 4.2 the "get Info" box lags 10-15 sec where i cant click into and edit the title for those 10-15 seconds. Earlier versions were fine. @openaudible

**Comment by openaudible** [comment]
Shoot. Very sorry. The new beta fixes this. 
https://openaudible.org/beta

We improved the get info so it wouldn't do the "book report" until you click on the tab. That should improve the performance and letting you edit sooner.

The difference in speed is when the meta data is updated, we just update the openaudible database. If something like the series or ratings count changes, we just make a note in the database so it is shown in the book table/book info. Making a change from the Get Info dialog actually writes the new information to the m4b/mp3 audiobooks. That takes a lot more processing time as the whole file has to be read and written out.
