### ISSUE TITLE
Issue: Meta data update 

### ISSUE THREAD

**Issue by chompinlynx** [openaudible/openaudible#1421]
I update my metadata such as title frequently here. The issue i noticed is that it takes a long time for books 10+ hours to just change the title and series #. Is there any more effiecient way to update metadata or maybe you can explain the process if not possible?

**Comment by openaudible** [comment]
When you edit the tags, the meta data in the files have to be updated as well. That takes a lot of time because the tags are typically stored at the beginning of the file -- so the whole (usually large) file needs to be re-written from scratch.
