### ISSUE TITLE
Feature Request: When splitting single chapter books, go ahead and create folder anyways

### ISSUE THREAD

**Issue by ZLoth** [openaudible/openaudible#1422]
As presently written, OpenAudible has a "split audiobook" function which will split a multi-chapter book into individual files and put those in their own directory along with the cover and any associated attachments. However, current behavior is to skip over single-chapter books. 

It would be nice if, during the splitting operation, if a single-chapter book is encountered, to go ahead and create the folder, copy the file over, create the cover, and add in any attachments. 

Use case: I'm using OpenAudible to convert my Audible library and then put the files into a self-hosted audiobook server called [Audiobookshelf](https://www.audiobookshelf.org/)/. Each book has to be in it's own file folder, so automating the process will save time on my end.

**Comment by openaudible** [comment]
Marked as feature request. Goal is to have better integration with Audiobookshelf.

**Comment by ZLoth** [comment]
Thank you for adding this feature. I look forward to the release.
