### ISSUE TITLE
This title is not supported for full audio file download, please download individual parts.

### ISSUE THREAD

**Issue by Kayle7777** [openaudible/openaudible#1423]
I get this error when trying to download The Eye of the Bedlam Bride: Dungeon Crawler Carl, Book 6

"Error downloading: Download error: This title is not supported for full audio file download, please download individual parts.

I would like if there was a way I could still download this one. Thank you

**Comment by openaudible** [comment]
That's a new one for us. 

Can you play the whole book on your audible mobile player?

I can take a look if you attempt the download again, then send a bug report from the About Menu. Use issue 1423 

Otherwise, will need to see if it happens more frequently..

**Comment by rumo42** [comment]
Hey, I just got my license and I am having the same issue with INFINITUM by Christopher Paolini. I think this might have something to do with the length of the file, all books over ~28hours seem to have that issue for me.

**Comment by openaudible** [comment]
What player are you using? Have you tried VLC or another app that is known to work? (iTunes for Windows is buggy on large files.) Does MP3 work for you?

**Comment by rumo42** [comment]
I can't even get it to start the download, as soon as I press it the error shows up in the "State:" section.

**Comment by openaudible** [comment]
No need for a full bug report.. just open the File: Log Window and copy and paste the error you see in an email to support https://openaudible.org/contact . (Or see if the error message is somewhat human readable.)  
Also see: https://openaudible.org/docs#download_errors

**Comment by rumo42** [comment]
Sure, where do I finde that file?

**Comment by openaudible** [comment]
Its not a file, its a window under the file menu: File: Log Window (CTRL-E)

**Comment by rumo42** [comment]
Ah I see thanks, I will continue tomorrow, gotta work now. 
Thanks so much for you work and the quick replys. Really appreciate it! Good day :)

**Comment by openaudible** [comment]
Just FYI, I got this issue confused with the "can't play long files" issue. A full bug report might be helpful.
Attempt download, send bug report. Use issue number 1423.
Thanks in advance.

**Comment by rumo42** [comment]
Ah I see:
Also the problem fixed itself by now. The issue was on my end, I wasn't using the latest version. I actually installed the update but for some reason it still opened the old version. One de-and reinstall later and I am on 4.3 and its downloading just fine now :). Thanks for your great piece of software! And to everyone else with the same issue make sure you're up to date.

Best wishes

**Comment by openaudible** [comment]
Good to know. Upgrading to the latest version will fix the problem. Thanks.
