### ISSUE TITLE
Feature Request: Create URL files with links to Audible Book and, if necessary, Audible Series

### ISSUE THREAD

**Issue by ZLoth** [openaudible/openaudible#1424]
It would be nice to have an option to have OpenAudible create URL files of the link to go to the book and, where applicable, the Series. This would allow me to more easily look up similar books by the author or the series associated with the book. While the book title can have the name of "Book Title.url", the series link could have the "Book Title (Series Title).url"

**Comment by openaudible** [comment]
The OpenAudible app has the ability to quickly navigate to the URL of the book, author, and series.

Just click on the book link or series link in the OpenAudible application. It will take you to the book URL or series URL.
https://openaudible.org/docs#audiobook_info

The blue labels on the left side can be clicked on to filter books by title, author, narrator, genre, or publisher.

Clicking the blue text on the right side will open the browser to display the Audible page for the title, author, narrator, genre, or publisher.

The books.json can be read by computer and a small script to generate the .url file is possible.
