### ISSUE TITLE
Full book not downloading

### ISSUE THREAD

**Issue by chompinlynx** [openaudible/openaudible#1425]
Im consistently getting an issue downloading this audiobook. It only downloads about 9hrs of the total 62hrs. 

https://www.audible.com/pd/Sherlock-Holmes-Audiobook/B06WLMWF2S

I've deleted the file and redownloaded and no bueno. FIrst time 9 hrs 23 min avail now second time 8 hrs 45 min available.

**Comment by openaudible** [comment]
Look at the file: log window. Maybe there is an error message. It could also be an error on audibles side — does the book play in the Audible app? Feel free to email us the full error log on our contact page.

**Comment by chompinlynx** [comment]
The book plays fully in Audible. I emailed the bug report over to y'all. If theres another file you need could you send the path where its located? 
Thanks,

**Comment by chompinlynx** [comment]
I just converted to MP3 and the mp3 is fine, but the M4b is the problem

**Comment by openaudible** [comment]
Hmm. Maybe your audio player doesn't handle long audiobook m4b files. What player are using? Maybe try VLC or another player.

**Comment by openaudible** [comment]
I got a bug report from you but it didn't contain any errors encountered downloading or converting.

**Comment by chompinlynx** [comment]
Okay, I’ll live with it since it does seem to be this singular occasion and the MP3 works fine.

Thank you for looking into it!

**Comment by openaudible** [comment]
Sure. Check your m4b player as well. iTunes for Windows is pretty crappy with large files.
