### ISSUE TITLE
Slow sorting of the table of books

### ISSUE THREAD

**Issue by KickHighMDK** [openaudible/openaudible#1426]
I have a large library of books (xxk) and the sorting/reordering of the table is very slow. 
Seems like it is either not in memory or using a slow algorithm for sorting.

**Comment by openaudible** [comment]
Everything is done in memory. Which might be part of the problem -- your library is quite large -- over 22 years worth of audio? 

You'll have to expect some slowness. 

Take a look at the About Menu: Diagnostics. 

You'll see something like:  "memory": "Memory: Using 94.01MB of 7.99GB (1%) Min 94.01MB Max 94.01MB",
If you're bumping up against the limit, let use know.. we can attempt to increase that. 

If you export to CSV, how long does Excel take to sort your columns?

**Comment by murraypetera** [comment]
Hitting mx limit.
I tired updating vmoptions.txt
-Xmx8G (tired upper case and lower on the G)
tried editing Info.plist
<string>-Xmx8G</string>

setting is not getting to java,  stuck at 2g 

Where do I edit the jam settings? 
thanks

**Comment by openaudible** [comment]
If you're on Mac, run from terminal:

``` 
cd /Applications/OpenAudible.app/Contents/Resources/app
cp debug_mac.sh test.sh
```
Edit the test.sh file and add -Xmx16G to the java command.

Of course, it will help that you actually have 16 or more GB.. Adjust as needed.. I tried with 12Gb on my 8GB mac and it ran, but I don't know if it runs faster than the default 8GB. 

``` 
./test.sh
```

Now when you run, the diagnostics should show 16Gb. 

That said, I'm not positive that running with that argument will help-- modern java should use most memory available.

**Comment by openaudible** [comment]
How much physical ram do you have? You can try 16G or 32G as well.. 

I have a test library of 11K files, and sorting is well under 1 second. That's on the an 8GB JVM with 32GB physical RAM. 

If you want, send a bug report from the about menu. That will send a copy of your books.json file and I'll run it on my end and see how bad it is...

Also, make sure you're using 4.3, released today. (So the bug report doesn't get rejected.)

**Comment by openaudible** [comment]
If you have 16G physical you should be able to set the java vm arguments to 

-Xmx16G 
or 
-Xmx32G

I'm building a beta that will print a message if populating the book table takes more than 10 seconds. It could be the sorting that takes a long time or creating the table with the sorted data that is taking a long time. 

If you want to send me a copy of your library to experiment with, you can use the About Menu: Send Bug Report... and use issue 1426

**Comment by openaudible** [comment]
A beta has been posted: https://openaudible.org/beta

**Comment by openaudible** [comment]
The beta will show a log message on long sort/redraw events. That might narrow down if its the list sorting or the Mac having a problem with many items in a table. You could try selecting one genre (or some smaller subset of your library) and seeing how long it takes to redraw on sort changes.
