### ISSUE TITLE
Fetching bookmarks/notes

### ISSUE THREAD

**Issue by livingstaccato** [openaudible/openaudible#1427]
Hi there!

Is there any chance that you'll be implementing the ability to download the locations/notes of bookmarks? That would help make researching stuff sooooooooo much better. :)

Thanks!

--Tim

**Comment by openaudible** [comment]
Yeah, we are working on that.. Probably next release. It will be a read-only service.. with ability to sort by type, date, etc. But no firm timeline.

**Comment by openaudible** [comment]
A first pass has been added to the beta. Click on a book, Action: Get Info. Go to the Annotations tab. Click the "Auto fill" button at the bottom. Hopefully you see your notes and bookmarks.
Let me know.
