### ISSUE TITLE
Open Audible Export to Apple Books

### ISSUE THREAD

**Issue by Dunadaen** [openaudible/openaudible#1428]
If I want to add my M4B Files as a Book to the Application Books it needs to be Sorted by Album Name to be sensible, since Books does not support a sorting with other Metadata then Album Name. So what I would love is that when I convert the File to M4B that the Title also becomes the Album Name. See Screenshots.
<img width="482" alt="InfoMac" src="https://github.com/openaudible/openaudible/assets/174183520/6db985d3-6da8-4381-8372-837ff7ad9076">
<img width="568" alt="InfoOpenAudible" src="https://github.com/openaudible/openaudible/assets/174183520/0e74c110-e13f-443c-bb1d-2518dc1a7109">

**Comment by Dunadaen** [comment]
Ok. So i understand now that what you name Short Title will actually translate to Album Name. So what i would really love is a function that one can run that will set Album name to "Series Name" & " " & 00 (Series Sequence in format nn) & Title. 
If you could create such a function then it would be afterwards perfect for Import into the Application Book from Apple. Because the Books would then be imported into the Application correctly sorted. If you could even create a plugin that would put the books into the right collections according to Series Name that would be perfect.

**Comment by openaudible** [comment]
We currently put the "Series Name" & " " & 00 (Series Sequence in format nn) & Title in the "Album Sort" meta data field. Which is what Apple Books should be using.. however... it shouldn't hurt to move it to the album tag, since the name of the book is always correct in the "title" tag. 

I could try to test that and see what happens.. maybe make a beta. Don't want to break anything...

**Comment by Dunadaen** [comment]
I See. I did not fully realise that. Since Apple Books does not show the sort field I like to have the series and title together in the album tag, because that makes for a better overview for me. I used MP3Tag now to actually automatically do my whole collection (602 Books) and put the Information into the Album Tag. This results in the following screenshot. I included it so you can see why I am doing it this way. 
<img width="1118" alt="SortedSeriesTitle" src="https://github.com/openaudible/openaudible/assets/174183520/f43b8087-2054-4a7b-b9b9-94385b41b255">

**Comment by openaudible** [comment]
OK. I have posted a beta https://openaudible.org/beta that writes the album tag the way we did the album sort -- with series info.
You'll need to re-encode any files you want to test with.
Let me know if that works.

**Comment by Dunadaen** [comment]
Hi.
This does almost exactly what I would like. 😊 The only thing now is that the Album is
“Alex Rider 1 – Stormbreaker”
instead of
“Alex Rider 01 – Stormbreaker”

Because Apple-Books (and so far as I can see itunes and android too) will sort the numbers wrong if they’re not in double digit format, since it’s a text sort

But this is lovely. Thanks for the fast Beta! And sorry that I only had time to reply today.

Have a good day.
René

Von: openaudible ***@***.***>
Gesendet: Mittwoch, 3. Juli 2024 00:19
An: openaudible/openaudible ***@***.***>
Cc: Dunadaen ***@***.***>; Author ***@***.***>
Betreff: Re: [openaudible/openaudible] Open Audible Export to Apple Books (Issue #1428)


OK. I have posted a beta https://openaudible.org/beta that writes the album tag the way we did the album sort -- with series info.
You'll need to re-encode any files you want to test with.
Let me know if that works.

**Comment by openaudible** [comment]
Can fix. Don't see any reason this can't go into the next production version. 

Thanks for the feedback.

**Comment by openaudible** [comment]
Try latest beta.
