### ISSUE TITLE
Manual Change of Title / Metadata is not reflected after restart - Mac and Windows

### ISSUE THREAD

**Issue by Dunadaen** [openaudible/openaudible#1429]
I have downloaded my Audible Books and try to rename / reorganize them in series and editing titles. When i call up the data with command I i can change the metadata and the Metadata in the file is actually changed. But when i close open Audible and open it again that change is not reflected in the Application. Instead the Data seems to be redownloaded from the web. This happens even if i turn off the option Refresh Library on Application startup. What am i doing wrong or is this a known error? 
<img width="1505" alt="Saved Data" src="https://github.com/openaudible/openaudible/assets/174183520/5bfbaf79-2ae7-410d-853f-ecd12ca1bdb3">
<img width="383" alt="Metadata File is changed" src="https://github.com/openaudible/openaudible/assets/174183520/4729ca1a-b804-4c54-83e5-ccb37f8f73f8">
<img width="776" alt="Information Library" src="https://github.com/openaudible/openaudible/assets/174183520/90ba0c79-b1ac-45d7-8fda-15eae4000834">
<img width="1520" alt="After Restart" src="https://github.com/openaudible/openaudible/assets/174183520/19c4e8ba-0438-4513-b48a-f87ac7a88533">

**Comment by Dunadaen** [comment]
I have now tested this on Mac and on Windows Version extensively. And the same thing happens. Even when i deactivate my Audible account the library file seems not to get updated when i change the data. I don't know why. Looking at the books.json i see that the information does not get changed there when i change it in the application.

**Comment by openaudible** [comment]
A few things to check or note.

Meta data changes to title should be saved on restart. 

Changing the title will not change the file names associated with the book -- to rename the files, use the "Action:Rename Book" menu item. 

Doing a full rescan will overwrite your meta data changes. This behavior can be changed by unchecking the "enable metadata updates". See: https://openaudible.org/docs#manage_libraries

Make sure you're using the latest version...
