### ISSUE TITLE
git repo not matching binary version

### ISSUE THREAD

**Issue by rbartl** [openaudible/openaudible#143]
Hy,

wanted to start the master or 1.5.1 from the git repo version locally - but it doesnt connect correctly to audible.com (instead it opens file:///)
i then compared the binary AudibleGui.class from release 1.5.1 and it seems it doesnt match any source files. 
e.g. binary has a  

   private String defaultURL() {
           return this.audible.getAudibleLibraryURL();
       }

which i cant find in any source file (git or 1.5.1 source zip)

help ;)...  ?

BR, RB.

**Comment by openaudible** [comment]
The latest source code is not "open". It was much more work to keep it public and I got no useful contributions after a year of effort. 

I updated the README and project web page to show that 1.1.8 is most recent source code and the binary on our site is newer.
