### ISSUE TITLE
Could error msg be related to new audible password?

### ISSUE THREAD

**Issue by EmilyKPDX** [openaudible/openaudible#1430]
I’m in the process of doing a download to an external drive. I’m getting a lot of books that won’t download. I have both an audible US and audible UK account. Audible/Amazon made me update my password recently. Is that part of the problem? If so, I don’t see any way in open audible to update my password. Do I just need to forget about both of those accounts and then Re-enter them like they were new? 

I realize this is a pretty basic question, but I am not as tech advanced as some.

**Comment by openaudible** [comment]
I'm not sure. You can check your "File: Library Status" menu. Make sure everything is green. 
Try a "Full Library rescan" from the controls menu.
Check your firewall/antivirus.
Review: https://openaudible.org/docs#troubleshooting
