### ISSUE TITLE
Unable to Split into chapter

### ISSUE THREAD

**Issue by jro806** [openaudible/openaudible#1431]
I confirmed that the book has multiple chapters by going to "Get Info".  I also made sure I had the latest update.  It will not allow me to split.  See attached for what comes up when I try to.  This is happening with all of the books I have tried.
![splitting error](https://github.com/openaudible/openaudible/assets/174916361/256b8586-34ea-4e84-8971-3dbce5d575c2)

**Comment by openaudible** [comment]
Hmm. That is weird. Is that file on disk? Is the audiobook "green" when you select it and attempt to split it? 
There may be more in the Log Window, CTRL-D.
You can send an email to our support from our web site.
