### ISSUE TITLE
split into chapters - on full frames?

### ISSUE THREAD

**Issue by kai-uwe-rommel** [openaudible/openaudible#1432]
Splitting a long audiobook is a bit painful as it is rather slow and uses 100% CPU because it apparently de- and then re-encodes the audio stream(s).
Can you check if in the converted MP3 (or in the original AAX) the chapter markers happen to fall on full frame boundaries so that a much simpler splitting process could be possible?

**Comment by openaudible** [comment]
We use a lot of CPU because we split several chapters concurrently. We don’t decode and re-encode. (That would take minutes not seconds.) 
If you think you can improve the speed, feel free to send a suggestion— but we use ffmpeg and unlikely to do better.

**Comment by kai-uwe-rommel** [comment]
I would welcome an option to have it split only sequentially, one chapter after another. I don't mind how long it takes as long as I can continue to use my PC for other task while OpenAudible splits in the background.

I saw that ffmpeg was run by OpenAudible and thus thought that it is used for re-encoding - why else would you need it? And, why would ffmpeg need so much CPU power when it does not re-encode?
