### ISSUE TITLE
Requesting a way to restore corrupt books.json without redownloading 1000+ books

### ISSUE THREAD

**Issue by alex-babanov** [openaudible/openaudible#1433]
Please, add a way to repair the library when books.json gets corrupted. The library is still there, so a sync without download and conversion should be able to create a whole new books.json.

Thank you! / Alex

**Comment by openaudible** [comment]
It's a good suggestion. A little tricky, of course. 

Good idea to back everything up. Just in case things get messed up.

We typically don't write the books file unless it is valid json. Not sure how it got corrupt. Try to fix it (make it legal json)?

If loading books.json gives an error, move it to broken.json. Or create a books.json file that contains: [] 
(an empty json list)

Next turn off auto-download/auto-conversion in the prefs.

Method 1:
Use the Controls: Refresh Files. That is supposed to rebuild your library. It may not be perfect. 

Method 2:
Create a new library. Do a full rescan. Manually copy aax, images and books files.

**Comment by alex-babanov** [comment]
Thank you @openaudible! I am trying your suggestion, but a backup of 1000+ books takes a while. Will be back with the results once ready.

**Comment by alex-babanov** [comment]
To clarify, the corruption was caused by an unexpected reboot while the library was being updated. The corrupted books.json has a tail part filled with null symbols.

**Comment by openaudible** [comment]
We will review the saving so that hopefully doesn't happen. It is super rare but not something we power off test.

**Comment by alex-babanov** [comment]
@openaudible So, good news / bad news situation with the workarounds: I copied the whole 1.3 terabyte library, disabled automatic download and sync, and did first a quick sync and then a full sync. The app now shows that I have 1332 books, 1341 m4b files, 644 books to download and 3 books to convert. I believe these 3 books were my last purchases before the corruption.

I don't know why these 644 books were not linked to the local copies, but I guess I'll be writing a script with some fuzzy matching to fix my new books.json. And will start backing this file up.

**Comment by openaudible** [comment]
Ok, thanks for the update. Not sure why!
