### ISSUE TITLE
Audible Originals 

### ISSUE THREAD

**Issue by Trev195074** [openaudible/openaudible#1434]
I have The Big Lie - all eight episodes - downloaded to my Audible Library. The Big Lie is an "Audible Original". In my Audible Library the episodes come up under "All" but not under "Audiobooks". I'd like to get them into OpenAudible but I can't seem to get them in there.
Trev195074

**Comment by openaudible** [comment]
Those are podcasts and are not enabled by default.
Go to File:Manage Libraries
Check the "Enable Podcasts" checkbox.
Save, then do a Controls: Full Audible Library Sync

**Comment by Trev195074** [comment]
That’s great Thanks Trev Sent from my iPhoneOn 27 Jul 2024, at 11:52 AM, openaudible ***@***.***> wrote:﻿
Those are podcasts and are not enabled by default.
Go to File:Manage Libraries
Check the "Enable Podcasts" checkbox.
Save, then do a Controls: Full Audible Library Sync
