### ISSUE TITLE
Error Converting: failed to convert check console for details

### ISSUE THREAD

**Issue by dpm0** [openaudible/openaudible#1436]
What is the console? There is no mention of a console in any of the top level menus. I have checked that the network location of the aax file is available and readable.
Here is the log: 

July 27, 2024 2:46:46 PM org.openaudible.convert.ConvertJob convert
SEVERE: {
 "exception": "Failed to convert Z:\\audiobooks\\AA Audible library\\aax\\Think Again.AAX. Check console for details.",
 "stacktrace": "java.io.IOException: Failed to convert Z:\\audiobooks\\AA Audible library\\aax\\Think Again.AAX. Check console for details.\r\n\tat org.openaudible.convert.ConvertJob.convertFile(ConvertJob.java:554)\r\n\tat org.openaudible.convert.ConvertJob.convert(ConvertJob.java:719)\r\n\tat org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:855)\r\n\tat org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:571)\r\n",
 "book": {
  "rating_average": "4.639429312581064",
  "copyright": "©2021 Adam Grant;℗2021 Penguin Audio",
  "chapters": "",
    "tags": {"title": "Actions fo [message truncated]July 27, 2024 2:46:46 PM org.openaudible.util.queues.ThreadedQueue jobError
INFO: ConvertQueue error processing convert Think Again item Think Again
java.io.IOException: Failed to convert Z:\audiobooks\AA Audible library\aax\Think Again.AAX. Check console for details.
	at org.openaudible.convert.ConvertJob.convertFile(ConvertJob.java:554)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:719)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:855)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:571)

July 27, 2024 2:46:46 PM org.openaudible.Audible jobCompleted
INFO: ConvertQueue completed:Think Again ConvertQueue size:0 remain:0 success:1 fail:15 threads:1 jobs:0
July 27, 2024 2:46:47 PM org.openaudible.desktop.swt.manager.views.BookInfoPanel enableCover
INFO: set enableCover to true. resize event good width=1176
July 27, 2024 2:46:48 PM org.openaudible.desktop.swt.manager.AudibleGUI _checkAutomation
INFO: Start auto web page:
July 27, 2024 2:46:51 PM org.openaudible.queues.JobProgressManager lambda$setDone$0
SEVERE: JobStatusManager: job not removed: convert Think Again Error done
July 27, 2024 2:47:04 PM org.openaudible.feeds.pagebuilder.WebPage buildPage
INFO: Copying template files from: C:\Program Files\OpenAudible\webapp
July 27, 2024 2:47:05 PM org.openaudible.feeds.pagebuilder.WebPage buildPage
INFO: no post run script found: C:\Users\dm\OpenAudible\web_updated.bat
July 27, 2024 2:47:05 PM org.openaudible.desktop.swt.manager.ExportBooks exportWebPage
INFO: Book html file is: Z:\audiobooks\AA Audible library\web\index.html url=file:/Z:/audiobooks/AA%20Audible%20library/web/index.html
July 27, 2024 2:49:26 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute

**Comment by openaudible** [comment]
By console we meant FIle: Debug Window. Updated the code to reflect that.
The error message we needed was probably right above where you copied and pasted. Feel free to send message through our web site with full log. Or look for: FFMPEG error converting and the error message is supposed to be right there.
Check also disk space and that you downloaded the title using openaudible.

**Comment by dpm0** [comment]
"Check also disk space" I fell a bit embarrassed now. I thought I was better than that. That was it.

**Comment by openaudible** [comment]
No worries. Not the first one to have that happen to. We can try to improve our error messages.
