### ISSUE TITLE
Shokz cannot play split file. 

### ISSUE THREAD

**Issue by vargas8812** [openaudible/openaudible#1437]
When I converted a book to mp3 format, the book plays as one long track and not as separate tracks to choose chapters. Then, when I split the file and try to add it back to player, the file was converted back to mp4 format and the player did not recognize the file. How do I keep the file from being split and converted back to mp4 format?

**Comment by openaudible** [comment]
If you just need mp3 for the split, set the output format to mp3. If that doesn't work, delete the m4b version so there is only the full mp3 to be split.
