### ISSUE TITLE
Request to show seconds in the book duration  column

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#1438]
currently, this column shows hours and minutes for the audiobook
this is fine for most applications however sometimes some books get an extra message added to the beginning increasing the length by about 40 seconds I have downloaded the book from different servers some servers append the extra message some servers it is missing
to help identify the books that include the extra unwanted message, showing the seconds for duration would help
otherwise, I have to convert both to listen to the start to remove the version with the extra message

**Comment by openaudible** [comment]
I need to keep things simple. Export to excel and duration in milliseconds should be available. If not will add.

**Comment by openaudible** [comment]
Looking at it we don’t usually have duration in milliseconds. We can get it if we calculate it .

One thing you can do is select two books in the table and they will be compared in the summary panel. 

FYI we have a new beta with integrated player. Https://openaudible.org/beta

**Comment by feldegast** [comment]
all i was interested in was a way to ensure i had the longest book as it
contained an ad i wanted to avoid

**Comment by feldegast** [comment]
comparison in the summary panel works well
i do notice a few issues, however,
length is the actual file size not length in seconds or milliseconds
the time for the 2 being compared is missing

- length1: 322.76MB (338442619 bytes)

- length2: 322.4MB (338060727 bytes)


Comparing the two selected books:

Comparing: Monstrous Regiment and Monstrous Regiment

keys: book1=BK_RHUK_000320 and book2=BK_RHUK_000320AU

Book Status Mismatch: book1=Converted OK m4b and book2=Ready to convert

mismatch: Product ID BK_RHUK_000320 is not equal to BK_RHUK_000320AU

mismatch: ASIN B0032N4L16 is not equal to B00FE5FDCQ

mismatch: Book URL https://www.audible.com/p… is not equal to
https://www.audible.com.a…

mismatch: Ave. Rating 4.69811320754717 is not equal to 4.901197604790419

mismatch: Rating Count 424 is not equal to 334

mismatch: Copyright ©2001 Terry Pratchett ℗20… is not equal to ©2001 Terry
Pratchett;℗20…

mismatch: Author URL https://www.audible.com/a… is not equal to
https://www.audible.com.a…

mismatch: Download URL https://cds.audible.com/d… is not equal to
https://dze5l2jxnquy5.clo…

mismatch: File name Monstrous Regiment.1 is not equal to Monstrous
Regiment.4

mismatch: Key BK_RHUK_000320 is not equal to BK_RHUK_000320AU

mismatch: Series URL /series/Discworld-Industr… is not equal to
/series/Discworld-Industr…

mismatch: Region US is not equal to AU

book2 missing User ID amzn1.account.AFEWHLYYIMCPSLUVOAQ4FV4F2R5A

AAX files are different, file1 is larger

- file1: P:\Plex Extra\OpenAudibleFiles\aax\Monstrous Regiment.1.AAX

- file2: P:\Plex Extra\OpenAudibleFiles\aax\Monstrous Regiment.4.AAX

- length1: 322.76MB (338442619 bytes)

- length2: 322.4MB (338060727 bytes)

M4B files are different, file1 is larger

- file1: P:\Plex Extra\OpenAudibleFiles\books\Monstrous Regiment.1.m4b

- file2:

- length1: 316.82MB (332214268 bytes)

- length2:

ART files are different, file2 is larger

- file1: P:\Plex Extra\OpenAudibleFiles\art\Monstrous Regiment.1.jpg

- file2: P:\Plex Extra\OpenAudibleFiles\art\Monstrous Regiment.4.jpg

- length1: 54.21KB (55509 bytes)

- length2: 55.37KB (56698 bytes)

**Comment by feldegast** [comment]
the ability to play the audiobook in the 4.3.0.7 beta looks good as a quick way to check if the book is the one wanted

**Comment by openaudible** [comment]
The comparison looks like it is working as expected. We don't yet have the book duration in milliseconds since it is typically delivered as a string. 


After looking a little more, adding the seconds is no big deal (since the column name "duration" is longer than the time with the seconds. So added to latest beta and posting a new release shortly.
