### ISSUE TITLE
Get info feature not working after latest update

### ISSUE THREAD

**Issue by Andyg1491** [openaudible/openaudible#1440]
After installing the latest update, I can no longer use the GET INFO feature. Nothing happens when I try to update an audiobook's information. I tried reinstalling it, but it did not help. I reinstalled the previous version, and it is working again.

**Comment by openaudible** [comment]
You can look at the File: Log Window. If you see an error you can paste it here or to our support page. We will also run some tests soon.

**Comment by openaudible** [comment]
Confirmed. We added a new tab (Annotations) and forgot to enable it for the release. Will update to 4.4.1 shortly. Thank you for the report!

**Comment by openaudible** [comment]
Fixed in 4.4.1. Thank you for the report.
