### ISSUE TITLE
Cannot select/jump-to book by typing first character of title

### ISSUE THREAD

**Issue by misterjohnk** [openaudible/openaudible#1442]
When focus is in the book list and you type a character, selection should move to the next book whose title starts with that character.  That's standard UI, and extremely useful.  I was hoping it would be fixed when I just upgraded from an old version (currently using 4.4.0 on Windows).

**Comment by openaudible** [comment]
I'll take a look. We currently recommend CTRL-F (Find) then type what you're looking for.

**Comment by openaudible** [comment]
Added that feature to the latest 4.4.2.2 beta: https://openaudible.org/beta

**Comment by misterjohnk** [comment]
Awesome, works great!

**Comment by openaudible** [comment]
Fixed in 4.4.3
