### ISSUE TITLE
Almost all podcasts don't get detected or downloaded

### ISSUE THREAD

**Issue by Kalthax** [openaudible/openaudible#1444]
![Screenshot 2024-08-07 at 7 41 26 PM](https://github.com/user-attachments/assets/7d9d75a1-97ea-4993-9dee-3deba3c9cc16)
![Screenshot 2024-08-07 at 7 40 39 PM](https://github.com/user-attachments/assets/addb6f05-153e-4dd8-969a-efcbd1082ee4)
![Screenshot 2024-08-07 at 7 38 10 PM](https://github.com/user-attachments/assets/c2c4508f-1db5-42c1-b359-4eadb57d4499)

I'm using the latest update and as you can see, I have podcasts enabled for the library and I have 21 different podcasts with multiple episodes each in my Audible library, but OA only sees the first episode of 2 of the podcasts and nothing else. If you want the diagnostics log, I can send it over, but I'd prefer to send that somewhere that isn't publicly accessible.

Thanks.

**Comment by openaudible** [comment]
You need to add each podcast episode to your library from the Audible web app. Then try a full rescan. Also, make sure you have podcasts enabled in the File: Manage Libraries dialog.

**Comment by Kalthax** [comment]
Is this a bug or intentional design? How many episodes do I need to download manually? All of them, or just the first few episodes of each podcast and then OA will fetch the rest?

thanks.

**Comment by openaudible** [comment]
That is just the current way it works. We back up items actually in your library. 

Maybe will be improved in a future version.
