### ISSUE TITLE
podcasts not syncing

### ISSUE THREAD

**Issue by tsolignani** [openaudible/openaudible#1446]
Good morning.

I have an italian audible account and a lifetime openaudible licence.

I enabled podcast into «manage libraries» as per your documentation.

Still no joy, I have several podcast into my library (I double checked that) but they don't get downloaded and synced, the list is empty.

I tried restarting and even doing a full library sync.

In «Library status», the podcast entry says: 0

Thank you for your attention and have a nice day.

Tiziano

**Comment by openaudible** [comment]
So you need to add individual episodes to your library for them to get added.

**Comment by tsolignani** [comment]
Thank you for your reply.

If I browse my library, all episodes are already added into it, so I wouldn't even know how to add them, but removing them and adding each one, though I doubt it would work since they are already into it.

Thank you.

**Comment by tsolignani** [comment]
I went on the audible website to made some tries.

You only have the option to follow (segui) the entire podcast, you don't even have to option to add to library single episodes, but just listen (ascolta). See screenshot.

When you follow a whole podcast, it gets added to the library.

If I use libation, I can see and download single episodes much link audiobooks, but I just would like to keep using openaudible, it's just to confirm those episodes are already into my library.

Thank you.
![20240813_124744 - schermata](https://github.com/user-attachments/assets/7ec1055b-8692-48f4-a3dc-2fc8a4e5cee4)

**Comment by openaudible** [comment]
Ah- looks like a difference in your audible region. In other audible regions there is an option to add an episode to your library. Thanks for the clarification. Will explore that…

**Comment by openaudible** [comment]
Try our beta: https://openaudible.org/beta 

Do a full resync from the control menu. 

Then click the podcasts library stat or select podcasts from the search menu. 

Let us know.

**Comment by openaudible** [comment]
Maybe fixed in 4.4.4
