### ISSUE TITLE
Make MP3/M4B download buttons SVG and bigger on web output.

### ISSUE THREAD

**Issue by Taurolyon** [openaudible/openaudible#1447]
The personal website output generates a clean table with titles, authors, narrators, and summaries. However, the MP3/M4B download buttons are very small, low resolution PNG files. These appear to be a fraction of the font size from the rest of the page.

![image](https://github.com/user-attachments/assets/8edbc4ab-5c8a-46d2-bc40-b3f4a029a201)

![image](https://github.com/user-attachments/assets/b4b702d8-d276-4a3d-9795-9c4ae319749d)

When control mouse wheeling up to zoom in on the page, you can see that the PNGs become blurry.
![image](https://github.com/user-attachments/assets/3247a267-a71b-4231-b8aa-1c8e9101a2de)

My suggestion is to replace these with vector format (SVG) and make these appear slightly larger on the outputted website. This would make these download buttons clearer for users.

**Comment by openaudible** [comment]
If you send files that look good we can swap them out.

**Comment by Cfomodz** [comment]
If someone wants to link me to the code that generates this page / the pngs themselves I am happy to create vector replacements (this is also true of any other raster images that you would like updated)

**Comment by openaudible** [comment]
The html is generated by openaudible when exporting to web from the File menu. It is pretty simple at the moment.. and is due for a re-write to make it support multiple libraries better. It currently makes a full copy of your library, so it is kind of a disk pig.. Another thing we are planning to revamp.

**Comment by chr00ted** [comment]
@Taurolyon I have an off-topic question for you: I happened to come across an old proxmox post of your where you had the following displayed. Just wondering if you can share it ;)

         .://:`              `://:.            root@pve
       `hMMMMMMd/          /dMMMMMMh`          --------
        `sMMMMMMMd:      :mMMMMMMMs`           OS: Proxmox VE 7.2-7 x86_64
`-/+oo+/:`.yMMMMMMMh-  -hMMMMMMMy.`:/+oo+/-`   Host: PowerEdge R710
`:oooooooo/`-hMMMMMMMyyMMMMMMMh-`/oooooooo:`   Kernel: 5.15.39-4-pve
  `/oooooooo:`:mMMMMMMMMMMMMm:`:oooooooo/`     Uptime: 4 mins
    ./ooooooo+- +NMMMMMMMMN+ -+ooooooo/.       Packages: 746 (dpkg)
      .+ooooooo+-`oNMMMMNo`-+ooooooo+.         Shell: bash 5.1.4
        -+ooooooo/.`sMMs`./ooooooo+-           Terminal: /dev/pts/0
          :oooooooo/`..`/oooooooo:             CPU: Intel Xeon X5670 (24) @ 2.927GHz [36.0°on]
          :oooooooo/`..`/oooooooo:             GPU: NVIDIA Quadro P620
        -+ooooooo/.`sMMs`./ooooooo+-           Memory: 19.96GiB / 141.32GiB (14%)
      .+ooooooo+-`oNMMMMNo`-+ooooooo+.
    ./ooooooo+- +NMMMMMMMMN+ -+ooooooo/.
  `/oooooooo:`:mMMMMMMMMMMMMm:`:oooooooo/`
`:oooooooo/`-hMMMMMMMyyMMMMMMMh-`/oooooooo:`
`-/+oo+/:`.yMMMMMMMh-  -hMMMMMMMy.`:/+oo+/-`
        `sMMMMMMMm:      :dMMMMMMMs`
       `hMMMMMMd/          /dMMMMMMh`

**Comment by Taurolyon** [comment]
> @Taurolyon I have an off-topic question for you: I happened to come across an old proxmox post of your where you had the [...]

That's the neofetch output from one of my old servers. I mentioned that in this post https://forum.proxmox.com/threads/remove-or-reset-cluster-configuration.114260/
I hope this helps.
Telegram me if you need any other info https://t.me/taurolyon

**Comment by openaudible** [comment]
Fixed image size in the latest 4.4.8 release. 

Will hide those off topic questions shortly-- not sure if they contain too much information.
