### ISSUE TITLE
Connection to Audible Window blank

### ISSUE THREAD

**Issue by gotmonkey70** [openaudible/openaudible#1450]
![Screenshot from 2024-08-23 12-57-01](https://github.com/user-attachments/assets/88e2988d-827a-4799-99d7-3b1d5e9e06aa)

I updated my system from Mint 21.3 to Mint 22. OpenAudible had been working fine on 21.3. After a full install of Mint 22, I installed OpenAudible_4.3_x86_64.sh to my system and installation was successful. Launched the program and registered my license with no issue.

Connecting to audible is the problem. 
Connect to audible
Secure web browser (recommended)
Default US region and legacy unchecked

Small browser window opens and it looks blank.
If I mouse around the window, the cursor changes to find text boxes, check boxes, and buttons.
Same result with setting Firefox as default browser

As a side note, I tried the appimages for 4.3 and 4.4.4 and have the same issue with the pop up browser connecting to audible. 

Any ideas? 

Browser: Chrome
OS: Linux Mint 22 x86_64 
Kernel: 6.8.0-41-generic
DE: Cinnamon 6.2.9
WM Theme: Mint-L (Mint-Y)
Theme: Mint-L-Darker [GTK2/3]
CPU: AMD Ryzen 7 7800X3D (16) @ 5.050GHz
Theme: Mint-L-Darker [GTK2/3]

**Comment by openaudible** [comment]
This looks like #1406 but we added (I thought) a fix to always set the export. Make sure you're using the latest (4.4.4).

```export WEBKIT_DISABLE_DMABUF_RENDERER=1```

Try running the above export and see if that helps. 

Check the File: Log Window to see if you see any errors in the console when the browser window is open.

**Comment by gotmonkey70** [comment]
Thanks, running that export worked and I could see the credential logon screen. I successfully logged in and did a full sync. 

I will update to 4.4.4, just need to update my license (it expired on 8/4).

**Comment by openaudible** [comment]
Thank you for the update. 4.4 includes an audiobook player. :)
