### ISSUE TITLE
Only the account added last works

### ISSUE THREAD

**Issue by Mela** [openaudible/openaudible#1453]
1. Adding Audible.de account
2. books download and convert
3. Adding Audible.com account
4. Audible.com books download and convert
5. Audible.de books no download or convert
6. Removing Audible.de account
7. Re-adding Audible.de account
8. Audible.de books download and convert
9. Audible.com books no longer download and convert.
10. Removing Audible.com account
11. Re-adding Audible.com account.
12. Audible.com books download and convert
13. Audible.de books no longer download and convert
14. Rinse and repeat.

Both accounts are shown as green.

MacOS Sonoma 14.6.1 (23G93)
OpenAudible 4.4.4

Regards,

Mela

**Comment by openaudible** [comment]
Hmm. A full rescan should go through all. Can you hover over the account in the manage account dialog and let me know if the user id is the same for both? I assume the region is different.

**Comment by Mela** [comment]
Tried the rescan several times, also tried to restart to remedy the problem. Both didn't help. The user IDs are the same, yes. 

![2024-08-30_04-46-46_user_accounts](https://github.com/user-attachments/assets/759e197b-34ff-4105-a873-183daacee604)

**Comment by openaudible** [comment]
For now, what if you uncheck DE, then run a full scan.. then check DE and uncheck US.. That should at least work around the problem. Will try to simulate over here.

**Comment by Mela** [comment]
Will try later. Don't like to fail currently running conversions.

**Comment by openaudible** [comment]
No hurry. Will look on our end. Thanks.

**Comment by Mela** [comment]
* Unchecked Audible.com
* Full sync
* Checked Audible.com
* Unchecked Audible.de
* Full sync
* Download Audible.com works
* Checked Audible.de
* Full sync
* Download Audible.de works
* Download Audible.com fails

**Comment by openaudible** [comment]
Can you try the latest beta with both accounts checked?

In the log window it should say it will be scanning both accounts. 

If only one feel free to send a bug report from the about menu.

**Comment by openaudible** [comment]
Updated changes to final 4.4.5. 
If still seeing issue after resync… Send bug report from about if still seeing issues.
