### ISSUE TITLE
Account won't sync

### ISSUE THREAD

**Issue by mshouls** [openaudible/openaudible#1456]
I have been trying to sync my account for multiple days.  I have deleted and reconnect multiple times and still get an error message.  The status says that it is active and OK but when I resync my library I get an error

![Screenshot 2024-09-04 233520](https://github.com/user-attachments/assets/5df28971-a2a1-4c53-9759-2ad8b8519820)

![Screenshot 2024-09-04 233520](https://github.com/user-attachments/assets/d8be8e11-e16d-4afb-8fde-a422dfe8f4cb)

**Comment by openaudible** [comment]
Check your accounts in the File Menu: Manage Accounts. Delete any accounts that show an error by clicking the trash can icon. 
You may need to Connect again if the only account was in error.
Send a bug report from the About Menu if you continue to see that error message.
Sometimes account credentials expire unexpectedly.. But it could also be something else -- you can take a look at the File: Log Window and see if you see any other error messages or send us an email with the logs....

**Comment by mshouls** [comment]
No luck.  did all of the above and nothing.  there is not even an listed in
the log

**Comment by openaudible** [comment]
There is definitely something in the File: Log Window when you do a full resync.
Send a bug report after you see that error message and we'll be able to assist.

**Comment by mshouls** [comment]
Error spot is blank

Error:

Nothing there. I've deleted the app and reinstalled still getting the same
resync error message

sent from Moto.

**Comment by openaudible** [comment]
Closing -- waiting for email/bug reports.
