### ISSUE TITLE
Login initiates password recovery.

### ISSUE THREAD

**Issue by fistwho** [openaudible/openaudible#1457]
Hello,
I have a strange problem. When I try to link my account, ?Amazon? initiates a password recovery and sends me an OTP by email. Then I am asked to enter my full name. However, this only happens when I try to link my account with OpenAudible. If I log in using the normal browser, there is no password recovery request. 

System: Windows 11
Region: Audible-DE
Version: 4.4.6 (Downloaded from Github)

**Comment by openaudible** [comment]
I am unable to reproduce this. An OTP should give you a browser window where you enter it into the browser. You could try the latest version (4.4.7 currently) and send a bug report from the About menu after getting the results you describe. Not many similar reports.
