### ISSUE TITLE
Issues with SWT on Kubuntu Linux

### ISSUE THREAD

**Issue by hiramknick** [openaudible/openaudible#1458]
After running the Shell script and successfully installing it I was unable to connect to the Amazon server and had an SWT error with missing libraries.  

To resolve this issue I needed to add the following libraries:
sudo apt install libwebkit2gtk-4.1-0
sudo apt install libwebkit2gtk-4.1-dev

**Comment by openaudible** [comment]
Thank you for that report. I’m not sure how to determine that before an error is displayed. Will do a little testing. Can definitely add a message. 

https://stackoverflow.com/questions/78060800/install4j-install-additional-packages-for-different-linux-families

**Comment by openaudible** [comment]
I added dependencies for both to the beta rpm and deb. 
For the installer, I added a note about installing the above dependencies.
Also improved my error message in the app (beta)
Thanks for the report!! Closing for now -- hopefully fixed for next release. 
https://openaudible.org/beta
