### ISSUE TITLE
Downloads won't work on devices - says not authorized

### ISSUE THREAD

**Issue by Zacharybinx34** [openaudible/openaudible#1459]
Is this supposed to happen?

**Comment by openaudible** [comment]
Go to the File: Manage accounts. If the account is in error, delete it and re-connect.
If it shows green/OK, make sure you're using the latest version. If you have multiple accounts, make sure both are active and green.

But its possible I am misunderstanding your question. Feel free to clarify with a log window message or screenshot, or drop us a tech support question from the OA website.

**Comment by Zacharybinx34** [comment]
The files are not in error. The issue is trying to sync it to devices like an Ipod Nano.
