### ISSUE TITLE
default AAC codec is better choice than reencoding to mp3

### ISSUE THREAD

**Issue by qqgg231** [openaudible/openaudible#146]
Please note that converting to MP3 isn't best choice if a device can play AAC

ffmpeg can convert aax to aac without reencoding. It gives the same quality as aax file and sligthly lower filesize

Example command:

`ffmpeg -activation_bytes bbbbbbbb -i "C:\Users\aaaaaaa\OpenAudible\aax\ccccc.AAX" -vn -c:a copy -map_metadata 0:g "ccccc.m4b"`

**Comment by qqgg231** [comment]
https://github.com/openaudible/openaudible/issues/45

**Comment by qqgg231** [comment]
#45

**Comment by openaudible** [comment]
Unfortunately, .m4b has a max file size limitation that requires splitting the files. Supporting multiple output formats requires a great deal of work, especially with split audio files. Thanks.

**Comment by cytec** [comment]
@openaudible just use .m4a instead ;) still better than transcoding to mp3

**Comment by qqgg231** [comment]
I agree, both m4a and m4b are containers for AAC

It seems that m4b can also support chapters, mp3 and m4a don't support them

If aax can be converted to m4b when small enough is should be, if it is too big then it can be converted to m4a instead

Or just always convert to m4a, it is still better than reencoding to mp3

**Comment by openaudible** [comment]
M4A support has been added to 2.0.6 and newer.
