### ISSUE TITLE
"Show Chapters" feature stopped working?

### ISSUE THREAD

**Issue by b1ueliner** [openaudible/openaudible#1463]
The "Show Chapters" feature stopped working after upgrading to the latest version (OpenAudible 4.4.7).

**Comment by openaudible** [comment]
To show the chapters, click on a book, Select Action: Get Info, then click on the Chapters tab.
That works here.. is there something else not working?

**Comment by b1ueliner** [comment]
OK, that does work.

I had previously just clicked on the three vertical dots icon and it 
showed the chapters, but then it stopped working that way after the last 
update.

thanx

mike

**Comment by openaudible** [comment]
3 vertical dots for the player appears to be working as well.  If you see the behavior again feel free to take a screenshot. Also, look at the File: Log Window if you see something strange and you might see an error message indicating a bug or unexpected event.
