### ISSUE TITLE
New Feature Request: Copy to my favorite places

### ISSUE THREAD

**Issue by drew-helgeson** [openaudible/openaudible#1464]
I use Emby and Plex, and have to perform the following steps manually for each converted book.
It would be nice to have a settings tab that allows me to set my "Favorite Places" and it when configured, it will:
1) Create a folder named with the book title in each favorite location defined
2) Copy the M4B or MP3 (based on config settings) to that folder
3) Copy the JPG to that folder

**Comment by openaudible** [comment]
Working on a way to customize the file structure so this is possible. It is a frequently requested feature. Getting closer.. hoping for a first public beta this month.
