### ISSUE TITLE
Convert to MP3 doesn't work

### ISSUE THREAD

**Issue by tinfoil-hat-net** [openaudible/openaudible#1469]
Hi, I have purchased a license for OpenAudible and I can only convert 3 of 8 of my Audio Books to MP3, the "convert to MP3" option is greyed out for the other books. Any Ideas on how to convert the ohter books to MP3?

**Comment by openaudible** [comment]
Please check out: 

https://openaudible.org/docs#conversion_errors

To troubleshoot an audiobook not converting, select the book and look at the state in the Book Info Panel. 
It might read "ready to convert" or OK: [mp3/m4b], (already converted, in convert queue, converting, or some error. Basically any reason it can't convert should be displayed. 

If it says OK:mp3, then you can reveal it from the Action: Reveal menu.

**Comment by tinfoil-hat-net** [comment]
I didn't understand the UI, everything s fine, no problem
