### ISSUE TITLE
Audible.in

### ISSUE THREAD

**Issue by fox4ben** [openaudible/openaudible#147]
Logging in to audible.com works just fine but as there is no option to select audible.in, the login fails on anything other than audible.com. Kindly add support to audible.in
[y1Hrwm2F.txt](https://github.com/openaudible/openaudible/files/3243710/y1Hrwm2F.txt)

**Comment by openaudible** [comment]
It looks like the /lib URL is supported. I will add it to the next version.. and post a follow up message here.

**Comment by openaudible** [comment]
Posted a new version with .in support. Please test and report back... thanks!

**Comment by fox4ben** [comment]
Thanks a ton for extending the support to Audible.IN

The login using my credentials through the inbuilt browser goes fine , ie to audible.in - which is correct. and then to audible.in/lib. The Library status shows the region as IN  -but fails to connect as the connection status remains NO.

**Comment by fox4ben** [comment]
Thanks a ton for extending the support to Audible.IN

The login using my credentials through the inbuilt browser goes fine , ie to audible.in - which is correct. and then to audible.in/lib. The Library status shows the region as IN -but fails to connect as the connection status remains NO.
![Screen Shot Open Audible 2](https://user-images.githubusercontent.com/51263165/58998595-29e8d800-881f-11e9-8b57-f936f171278c.jpg)
![Screen Shot Open Audible](https://user-images.githubusercontent.com/51263165/58998598-2d7c5f00-881f-11e9-87d9-0c79e2b8d327.jpg)

**Comment by openaudible** [comment]
Thanks for the report. I think we're close. 

Can you send a "Bug Report" from the Help menu and reference #147 after doing the same thing-- open browser, log in, and try to do a Scan? That will include the last html file.  

There may also be an error logged in the console, which is under the File menu. A bug report after that (or copy and paste) might be all that is needed.

**Comment by fox4ben** [comment]
Sorry about the delayed reply. The Bug Report has been generated and sent. The error logged in console is attached
[Log.txt](https://github.com/openaudible/openaudible/files/3293293/Log.txt)
 as a text document.

**Comment by openaudible** [comment]
Thanks for the report. I think that was enough to fix it.
Can you give this version a try and let me know?
https://openaudible.org/downloads/OpenAudible_win_1.5.2.exe

**Comment by fox4ben** [comment]
Working like a charm, thanks a ton!!!
![OpenAudible](https://user-images.githubusercontent.com/51263165/59579765-fdb93b00-90eb-11e9-9f7c-cc471271c278.jpg)

**Comment by openaudible** [comment]
Whoop whoop!
