### ISSUE TITLE
play option disabled

### ISSUE THREAD

**Issue by omendezmorales** [openaudible/openaudible#1470]
hello,
I have a few audiobooks downloaded, but after played well the first time, in subsequent times I've opened OpenAudible UI, the play option is disabled (see image):
![image](https://github.com/user-attachments/assets/7a2ea341-a878-455b-9ce1-50b7c2f05af7)

Is this expected behavior if the book has been already downloaded? Thanks for the help.

**Comment by openaudible** [comment]
You should convert it first. However we do allow playing if it was recently downloaded using OpenAudible and your library status says connected.

If you imported an old aax file I believe play will be disabled. (For various technical but not insurmountable reasons.)

At least that is how it is in the beta. Haven’t verified whether it is exactly as above in 4.4.7.
