### ISSUE TITLE
Build for aarch64

### ISSUE THREAD

**Issue by brezinajn** [openaudible/openaudible#1471]
Is there a build available for aarch64 or is this strictly x86-64?

**Comment by openaudible** [comment]
For Mac it is a universal binary— super optimized for aarch64.

**Comment by brezinajn** [comment]
Sorry I didn't specify the platform properly. I actually meant for Linux.

**Comment by openaudible** [comment]
In that case no. Sorry.

**Comment by brezinajn** [comment]
Are there any plans to publish for additional platforms in the future? My understanding is that the project went closed source, so unfortunately I cannot PR the fix. The fix should be fairly trivial, since the Openaudible is written in Java, it should just be a matter of supplying native dependencies for the required architecture.

**Comment by openaudible** [comment]
We would need our ffmpeg/ffprobe binaries compiled: 

https://github.com/openaudible/ffmpeg-build

If you submit a PR for that I can link a version with the aarch64 Linux eclipse SWT jars.

**Comment by brezinajn** [comment]
Sure. Give me a few days. I'm gonna take stab at it.
