### ISSUE TITLE
Multiple Libraries listed..  Unable to successfully delete unused libraries.

### ISSUE THREAD

**Issue by PickleG** [openaudible/openaudible#1472]
Platform is ubuntu 24.10.  License is forever. Version is 4.4.7

Unable to delete Library from Manage Libraries.

I have one library.   My list of libraries shows three.

/home/username/OpenAudible
/home/username/nextcloud/OpenAudible
/home/username/nextcloud/OpenAudible

Two and three are the same directory.
Two and three are not activated.  I delete two.  Three remains.  I delete three,  Three remains.  I close the dialog and re-open.  All three are listed again.

**Comment by openaudible** [comment]
Can you try again and look at the menu File: Log Window and see if there are any errors reported? 

A few things: 
You can't delete the active library.
Make sure that the permissions in the library are such that the app can delete the files.
You want to make sure there are no files open in any apps that might prevent us deleting the files.
You can always manually delete libraries by tossing them into the trash.

The drop down in the Manage Libraries should not show the same library twice. So not positive if there is a hidden space or some bug on our end.

**Comment by PickleG** [comment]
Log clips..
1 ----

INFO: using alt reveal, as desktop reveal unavailable.
java.lang.UnsupportedOperationException: The BROWSE_FILE_DIR action is not supported on the current platform!
	at java.desktop/java.awt.Desktop.checkActionSupport(Desktop.java:381)
	at java.desktop/java.awt.Desktop.browseFileDirectory(Desktop.java:1011)
	at org.openaudible.desktop.swt.gui.Reveal.reveal(Reveal.java:195)
	at org.openaudible.desktop.swt.gui.Reveal.lambda$reveal$0(Reveal.java:183)
	at java.base/java.lang.Thread.run(Thread.java:1583)

2 ----

Oct 30, 2024 7:03:26 PM org.openaudible.desktop.swt.manager.dialogs.ManageLibraryDialog widgetSelected
INFO: SelectionEvent{Combo {/home/gfowler/nextcloud/OpenAudible} [layout=null] time=68666717 data=null item=null detail=0 x=0 y=0 width=0 height=0 stateMask=0x80000 text=null doit=true}
Oct 30, 2024 7:03:27 PM org.openaudible.library.LibraryManager deleteLibrary
INFO: Delete library /home/gfowler/nextcloud/OpenAudible /home/gfowler/nextcloud/OpenAudible (missing) files:0 dirs:0 size: 0 B
Oct 30, 2024 7:03:27 PM org.openaudible.library.LibraryManager deleteLibrary
WARNING: deleting empty directory:/home/gfowler/nextcloud/OpenAudible
Oct 30, 2024 7:03:27 PM org.openaudible.library.LibraryManager deleteLibrary
INFO: deleted library completed: /home/gfowler/nextcloud/OpenAudible (missing) files:0 dirs:0 size: 0 B
Oct 30, 2024 7:03:33 PM org.openaudible.desktop.swt.manager.dialogs.ManageLibraryDialog widgetSelected
INFO: SelectionEvent{Combo {/home/gfowler/nextcloud/Openaudible} [layout=null] time=68673321 data=null item=null detail=0 x=0 y=0 width=0 height=0 stateMask=0x80000 text=null doit=true}
Oct 30, 2024 7:03:49 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:DELETE_LIBRARY_TITLE body:Are you sure you want to permanently delete this library?

Path:/home/gfowler/nextcloud/Openaudible
Info:Invalid library Missing books.json file
Size:Files: 0 Length: 0 B (1.64TB Free) response:BUTTON_YES
Oct 30, 2024 7:03:49 PM org.openaudible.library.LibraryManager deleteLibrary
INFO: Delete library /home/gfowler/nextcloud/Openaudible /home/gfowler/nextcloud/Openaudible files:0 dirs:0 size: 0 B
Oct 30, 2024 7:03:49 PM org.openaudible.library.LibraryManager deleteLibrary
WARNING: directory still contains 1 files: /home/gfowler/nextcloud/Openaudible
Oct 30, 2024 7:03:49 PM org.openaudible.library.LibraryManager deleteLibrary
INFO: deleted library completed: /home/gfowler/nextcloud/Openaudible files:0 dirs:0 size: 0 B
Oct 30, 2024 7:06:05 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by PickleG** [comment]
Attached

libraries.json
directories.json
[libraries.json](https://github.com/user-attachments/files/17579917/libraries.json)
[directories.json](https://github.com/user-attachments/files/17579918/directories.json)

**Comment by openaudible** [comment]
Ok. Looks like a bug somewhere. Since it doesn't have the books.json, we don't consider it a library.. and we don't attempt to delete the directory-- we want to only delete things we know are libraries. 

You'll need to manually delete that directory and you may want to manually delete the entries in the libraries.json.

We will add a check to see if they are valid libraries and not duplicates for the next release. 

Thanks for the report! Will let you know when an update is available.

**Comment by openaudible** [comment]
I added a few checks to the software so there shouldn't be any duplicates. https://openaudible.org/beta

**Comment by PickleG** [comment]
Upgraded to beta 4.4.7.7..   The two extra library paths disappeared..

resolved.
