### ISSUE TITLE
Audio comes out random device

### ISSUE THREAD

**Issue by PickleG** [openaudible/openaudible#1473]
Version 4.4.7 on Ubuntu 24.10

audio playback appears to be using java.
On my system, I have two HDMI monitors, a DAC, and the built-in audio on the motherboard.
In pulsewire/alsa, I have disabled audio output to the HDMI monitors.   Preferred output is via my D01 DAC.
Openaudio sends audio out the primary HDMI monitor.   I'm not able to change which device OpenAudible uses for audio output.

How do I change the device for audio?   Or can OpenAudible be adjusted to use ALSA or pulsewire?

**Comment by openaudible** [comment]
Not at this time. I'm trying to keep the UI simple and this is the first report. I am able to get a list of devices and for windows, there is a primary driver that comes first which is what we use. 

In Ubuntu there are several ways to set the default audio output that Java's AudioSystem will respect:

Using PulseAudio Volume Control (pavucontrol):
```
udo apt install pavucontrol
pavucontrol
```

Then go to the "Output Devices" tab and click the green checkmark button (Set as Fallback) next to your D01 DAC.

Using the Ubuntu Settings GUI:

Click on the system menu (top right)
Click on "Settings"
Go to "Sound"
Under "Output", select your D01 DAC
Make sure it's set as the Default Output Device

Give that a try!

**Comment by PickleG** [comment]
Upgraded to 4.4.7.6 beta..  no change.
The default output is set to D01 DAC.
The audio appears to be playing independent of the alsa/pulsewire subsystem.
The audio stream does not show in pw-top.   
adjusting the master volume does not affect the audobook audio.

**Comment by openaudible** [comment]
Nothing added to the beta for audio yet. 

Let me have you try more stuff recommended by Claude:

```
# List all sinks (output devices)
pactl list short sinks

# Set default sink (replace X with the sink number or name)
pactl set-default-sink X
```
For ALSA specifically:
```
# Edit or create ~/.asoundrc
nano ~/.asoundrc
```
Then add:
```
pcm.!default {
    type hw
    card D01  # Replace with your DAC's card name from 'aplay -l'
}

ctl.!default {
    type hw
    card D01
}
```

You can find your card name using:
```# List all audio devices
aplay -l
```

The Java AudioSystem typically respects the system's default audio device on Ubuntu. If it's still not working after setting the default device:

Check if your Java application is running as the same user that set the audio preferences
Verify PulseAudio is running:

`pulseaudio --check`

You might need to restart PulseAudio:

```
pulseaudio -k  # Kill current PulseAudio instance
pulseaudio --start  # Restart PulseAudio
```

Or restart the application after changing the default device

If OpenAudible is still not respecting the system default, you can also try setting a system property: 

`javax.sound.sampled.SourceDataLine=ALSA `

I'll try to make sure that the next version prints out more info about available mixers.. and hopefully just setting javax.sound.sampled.SourceDataLine property will make it work as expected.

**Comment by openaudible** [comment]
I added some debugging info, with the ability to specify a mixer by setting a property (OA_MIXER) and the name of the mixer.
I print those the first time you play some audio.
Feel free to check it out. but try the above steps as well or first.. https://openaudible.org/beta

**Comment by PickleG** [comment]
Set the .asoundrc does allow the default device to be selected..  sound now comes out the D01 DAC..

Volume can still only be controlled via OpenAudible volume..  master and direct D01 does not affect audiobook volume.

Also, a correction.   I've been referring to pulsewire..  it's pipewire audio sub-system..  I do not have a pulseaudio tool.  I believe in the past, installing pulseaudio tool corrupts pipewire..

**Comment by openaudible** [comment]
OK. Not sure why there are two volumes. The beta will print out more info and we have a new OA_MIXER system property you can set that might switch it as well. Perhaps there are two mixers-- one that goes through a master volume? Look at the File: Log Window when you first play something for the list of line out mixers.

**Comment by openaudible** [comment]
Closing for now.. Glad .asoundrc works. Maybe see if there is a mixer that looks like the master volume that goes to the right device.
