### ISSUE TITLE
OpenAudible 4.4.8 requires libwebkit2gtk-4.1 as a dependency , should be libwebkit2gtk-4.1-0

### ISSUE THREAD

**Issue by OlyAndy** [openaudible/openaudible#1476]
Install of the deb package fails on Ubuntu 24.10 Oracular as a result

**Comment by openaudible** [comment]
I thought you’re supposed to use rpm for Ubuntu. Fedora uses deb. We made that change for fedora users who don’t have that exact version. 
Just use the recommended .sh installer and you should be good.

**Comment by openaudible** [comment]
It does look like I reversed them... got a bug report from a fedora user using .deb. 
I'm tempted to remove the dependency from both-- as I wasn't able to specify >4.1 using the install4j.. And we display a message if the web browser doesn't launch. Will put a beta up.

**Comment by openaudible** [comment]
Released a beta without any dependencies. That might be best and I will put up a message if the browser fails to launch.
https://openaudible.org/beta

**Comment by openaudible** [comment]
Fixed in the production. You'll need to re-download 4.4.8. Let me know if that doesn't work.

**Comment by OlyAndy** [comment]
Works fine now. Ubuntu is a debian system, so always uses deb, not rpm installation files.

**Comment by openaudible** [comment]
Thanks for the update. Closed.
