### ISSUE TITLE
Podcast not downloaded

### ISSUE THREAD

**Issue by suemanning** [openaudible/openaudible#1481]
I notice a work is missing, it's a podcast.  I did check the correct box, and I have done a full scan and checked the log.  I don't see this podcast in the podcast folder, the aax folder, or the books folder.

I don't know if there are other works missing, but I noticed this one and I can't figure it out.  I'm using the latest version 4.4.8 on apple silicon macbook pro running sonoma.

It's from Audible US, "The Temp"
https://www.audible.com/podcast/The-Temp/B08DCSBDP1?qid=1731889879

**Comment by openaudible** [comment]
Make sure podcasts are enabled under manage accounts.

Try a full library scan from the control menu. 

Then…
From the search combo select podcasts.

**Comment by suemanning** [comment]
I tried all that, no dice.  I also searched the disk.

**Comment by openaudible** [comment]
Only other thing is to copy and paste the File menu Log Window window and search the text for the name of the podcast and see if there are any warnings about it. 

Also make sure you added it as a podcast from audible and it shows in your library.

**Comment by suemanning** [comment]
I have checked the log already, nothing is mentioned.

It is available in my library, at least it's one of those free or Prime
ones so I have only the Play option, but that works right?

I don't know what you mean about adding it as a podcast from audible?
//sue

**Comment by suemanning** [comment]
Oh no!  I see I am no longer "following" this for some reason...  I fixed
that and all is well.  Sorry about that.
