### ISSUE TITLE
Getting error in docker container when trying to add a second audible account. 

### ISSUE THREAD

**Issue by piersonjarvis** [openaudible/openaudible#1483]
I've had 2 instances of the openaudible docker container for a while, one for my account and one for my brother's. But I saw that there was an option to add more than one account per instance. So when I sat down to try and consolidate the two instances I get the following error. 

An error occurred opening an internal web browser.
This means your system is not compatible with OpenAudible,
until or unless additional software dependencies are installed.
Unfortunately, OpenAudibIe is not compatible with all platforms.
usually googling the error code below with 'SVvT Browser' will lead
to solutions for the same issue you're seeing.
Error code:
org.ecIipse.svR.SVvTError: because there is no underlying browser
available.
Please ensure that WebKit with its GTK 3.x/4.x bindings is installed.
** You need to install: libwebkit2gtk4.1-0 libwebkit2gtk4.1 -dev **
sudo apt install libwebkit2gtk-4.1-0 libwebkit2gtk-4.1 -dev

Container is updated to the latest version, though the application within says it has an update, doing the normal remove the container, pull the latest and re-start the container doesn't change this.

**Comment by openaudible** [comment]
If it says there is an update it isn’t the latest container. Follow instructions for stopping and deleting the container and restart. It should keep your settings if they are mounted as recommended.

**Comment by piersonjarvis** [comment]
I have. Many times. And it doesn't update it. I've made sure the container is deleted. I even went as far as removing the image from the machine as well. Still when I start it up again it prompts for the update instead of running the startup script to initiate the download. 

But this is beside the real point. Which is I cannot add a second account, as the openaudible application gives the error I mentioned above when I do try to add an account. It seems that it's trying to launch a web browser but can't find it. Which is strange since other ways of launching the browser work.

**Comment by openaudible** [comment]
You must be deleting the image and not container. Or it is misconfigured to save the app in a volume. Make sure stop and rm the container. First time it starts it will download and install the latest. Docker is unsupported so you’re kind of on your own.
