### ISSUE TITLE
Unexpected Error Refreshing Your Library

### ISSUE THREAD

**Issue by Puddl36lum** [openaudible/openaudible#1484]
Hello! 

Currently running OSX Version 4.4.8 and getting the following error when running quick synch and full library sync. I've attached a screenshot as well. Started when I upgraded from 4.4.7.  Haven't changed any settings. Audiobooks are stored on a Synology NAS 920+.

I also removed all registered devices from my account and logged back into my account via open audible.
Log output:

```
Volumes/Audiobooks/tmp/saved_books.json
4.4.8

Dec 09, 2024 10:45:18 AM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {Saro's 2nd Audible} [layout=GridLayout {numColumns=2 marginWidth=14 marginHeight=14 horizontalSpacing=16 verticalSpacing=8}] visible=true input shell:null
Dec 09, 2024 10:45:18 AM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {Saro's 2nd Audible} [layout=GridLayout {numColumns=2 marginWidth=14 marginHeight=14 horizontalSpacing=16 verticalSpacing=8}] visible=true input shell:null
Dec 09, 2024 10:45:31 AM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:Error refreshing library body:Unexpected error refreshing your library. Check the log.
If this persists, you may need to Log out of Audible and Log into Audible from the Controls Menu.
There is also a troubleshooting guide in the documentation.

/Volumes/Audiobooks/tmp/saved_books.json response:BUTTON_OK
Dec 09, 2024 10:45:31 AM org.openaudible.audible.api.API renewCredentials
INFO: exp=Sat Dec 07 18:55:30 EST 2024 now=Mon Dec 09 10:45:31 EST 2024 delta=1 day, 15 hours, 50 minutes and 1 second
exp=Mon Dec 09 11:45:31 EST 2024 now=Mon Dec 09 10:45:31 EST 2024 delta=59 minutes and 59 seconds
Dec 09, 2024 10:45:34 AM org.openaudible.desktop.swt.manager.dialogs.ManageAccountsDialog doCommand
INFO: Close
Dec 09, 2024 10:45:37 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
```
![Screenshot 2024-12-09 at 10 50 53 AM](https://github.com/user-attachments/assets/98618bba-e6a5-4f17-8bed-cb6021b8dfdd)

**Comment by openaudible** [comment]
Make sure the volume is online and writable. Send a full log message to us via our contact page or post it here if it doesn’t contain any personal info. We would want to see the details in the log before the message. 

Check that the firewall allows OpenAudible. 

Also check your File menu manage accounts and make sure they are green.

**Comment by openaudible** [comment]
Also check your disk space. Send a copy of the File menu: Log Window contents to us if needed.
