### ISSUE TITLE
Ubuntu - Unable to Log In

### ISSUE THREAD

**Issue by johnlescault** [openaudible/openaudible#1485]
After selecting my region (canada) and click OK, it opens a browser but it stays "stuck" at a black screen.
Is there a way to fix this by chance?
Thanks

**Comment by openaudible** [comment]
Yes, probably by installing: 

```
sudo apt install libwebkit2gtk-4.1-0
```

**Comment by Davidsmithdevelopment** [comment]
Should I open a new bug, or tag along in this one? I'm having the same issue. I have tried the above step, without success

**Comment by openaudible** [comment]
Do you have WebKit installed?


sudo apt install libwebkit2gtk-4.1-0

**Comment by Davidsmithdevelopment** [comment]
Yes, as noted above, I tried that step. Already installed. Just for kicks I added the libwebkit2gtk-4.1-dev too just to make sure I wasn't missing any dependencies.

**Comment by openaudible** [comment]
Any errors in the log window (ctrl-E) 

Can you install and run Mozilla or another WebKit based browser?

Make sure you're using the latest OpenAudible. 4.8. 

You could also check system logs for any unusual messages.

**Comment by Davidsmithdevelopment** [comment]
Ok, that's interesting. I dl'ed the sh from the site, but just checked and it is version 4.5. I check for updates and it says none are available. I can install a different way if needed. 

This is the filename of what was downloaded btw
OpenAudible_4.5_x86_64.sh

**Comment by openaudible** [comment]
Yes 4.5 is the latest version currently.

**Comment by Davidsmithdevelopment** [comment]
Have Chromium, and FF installed as browsers already. Only item in the log is attempting to open the url

I'll check system logs, and see what I can find

**Comment by Davidsmithdevelopment** [comment]
Hmm, see two errors
"install4j_k8y22j-OpenAudible.desktop[899973]: INFO: created browser of type: webkit
unity-panel-ser[2027]: gtk_label_set_text_with_mnemonic: assertion 'str != NULL' failed"



"kernel: nouveau 0000:01:00.0: gr: DATA_ERROR 0000009c [] ch 13 [007f651000 WebKitWebProces[902172]] subc 0 class 9297 mthd 0d78 data 00000004"

Everything else is the normal attempting to open the url. I can attach full logs if that helps

**Comment by openaudible** [comment]
Paste the second error into chatgpt. Looks like a problem with the nouveau driver. 

Try 

export WEBKIT_FORCE_COMPOSITING_MODE=software
./OpenAudible 

G_MESSAGES_DEBUG=all ./OpenAudible 

There is also an nvidia driver you can try. 

Let me know!

**Comment by bmbeverst** [comment]
Little different system, Manjaro, but similar errors. I also run Nvidia. Installed OpenAudible 4.5.1 for [Arch](https://aur.archlinux.org/packages/openaudible-bin) user repo. Same error with the installer.

Also installed [webkit2gtk](https://archlinux.org/packages/extra/x86_64/webkit2gtk/)

The sample [jcefmaven](https://github.com/jcefmaven/jcefsampleapp/releases) app does work for me. But that is using Chromium. 

NVIDIA info: `Driver Version: 550.144.03`

This is all I see:
![Image](https://github.com/user-attachments/assets/6113c816-0bef-4458-97d5-6d677e1039ff)

```
src/nv_gbm.c:288: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)

KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 384x816: Permission denied
```

```
❯ export WEBKIT_FORCE_COMPOSITING_MODE=software
❯ G_MESSAGES_DEBUG=all WEBKIT_FORCE_COMPOSITING_MODE=software OpenAudible

. . . . . 
Feb 18, 2025 9:24:37 PM org.openaudible.desktop.swt.manager.login.LoginGUI loginWithInternalBrowser
INFO: logging on to audible US
Feb 18, 2025 9:24:37 PM org.openaudible.audible.api.login.Login build_oauth_url

Feb 18, 2025 9:24:37 PM org.openaudible.audible.api.login.Login build_oauth_url

Feb 18, 2025 9:24:37 PM org.openaudible.desktop.swt.manager.browser.swt.AudibleBrowser createBrowser
INFO: creating browser of type: SWT.WEBKIT
Feb 18, 2025 9:24:37 PM org.openaudible.desktop.swt.manager.browser.swt.AudibleBrowser createBrowser
INFO: created browser of type: webkit
(process:156008): GLib-GIO-DEBUG: 21:24:37.496: Failed to initialize portal (GNetworkMonitorPortal) for gio-network-monitor: Not using portals
(process:156008): GLib-GIO-DEBUG: 21:24:37.497: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(process:156008): GLib-GIO-DEBUG: 21:24:37.497: _g_io_module_get_default: Found default implementation networkmanager (GNetworkMonitorNM) for ?gio-network-monitor?

(OpenAudible:155163): IBUS-WARNING **: 21:24:37.513: OpenAudible has no capability of surrounding-text feature

(OpenAudible:155163): IBUS-WARNING **: 21:24:37.526: OpenAudible has no capability of surrounding-text feature
(process:156008): GLib-GIO-DEBUG: 21:24:37.536: Failed to initialize portal (GPowerProfileMonitorPortal) for gio-power-profile-monitor: Not using portals
(process:156008): GLib-GIO-DEBUG: 21:24:37.537: _g_io_module_get_default: Found default implementation dbus (GPowerProfileMonitorDBus) for ?gio-power-profile-monitor?
(process:156008): GLib-GIO-DEBUG: 21:24:37.537: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ?gio-vfs?
(WebKitWebProcess:156014): GLib-GIO-DEBUG: 21:24:37.581: _g_io_module_get_default: Found default implementation local (GLocalVfs) for ‘gio-vfs’
(WebKitWebProcess:156014): GLib-GIO-DEBUG: 21:24:37.599: _g_io_module_get_default: Found default implementation dconf (DConfSettingsBackend) for ‘gsettings-backend’
(WebKitWebProcess:156014): dconf-DEBUG: 21:24:37.599: watch_fast: "/org/appmenu/gtk-module/" (establishing: 0, active: 0)
(WebKitWebProcess:156014): dconf-DEBUG: 21:24:37.599: unwatch_fast: "/org/appmenu/gtk-module/" (active: 0, establishing: 1)
(WebKitWebProcess:156014): GLib-GIO-DEBUG: 21:24:37.600: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
(WebKitWebProcess:156014): dconf-DEBUG: 21:24:37.600: watch_established: "/org/appmenu/gtk-module/" (establishing: 0)
(WebKitWebProcess:156014): dconf-DEBUG: 21:24:37.600: watch_fast: "/org/appmenu/gtk-module/" (establishing: 0, active: 0)
(WebKitWebProcess:156014): dconf-DEBUG: 21:24:37.600: unwatch_fast: "/org/appmenu/gtk-module/" (active: 0, establishing: 1)
(WebKitWebProcess:156014): dconf-DEBUG: 21:24:37.600: watch_established: "/org/appmenu/gtk-module/" (establishing: 0)
** (WebKitWebProcess:156014): DEBUG: 21:24:37.603: Name com.canonical.AppMenu.Registrar does not exist on the session bus

(WebKitWebProcess:156014): dconf-DEBUG: 21:24:37.603: watch_fast: "/org/appmenu/gtk-module/" (establishing: 0, active: 0)
(WebKitWebProcess:156014): dconf-DEBUG: 21:24:37.603: unwatch_fast: "/org/appmenu/gtk-module/" (active: 0, establishing: 1)
(WebKitWebProcess:156014): dconf-DEBUG: 21:24:37.603: watch_established: "/org/appmenu/gtk-module/" (establishing: 0)
(WebKitWebProcess:156014): GLib-GIO-DEBUG: 21:24:37.618: Failed to initialize portal (GPowerProfileMonitorPortal) for gio-power-profile-monitor: Not using portals
(WebKitWebProcess:156014): GLib-GIO-DEBUG: 21:24:37.618: _g_io_module_get_default: Found default implementation dbus (GPowerProfileMonitorDBus) for ‘gio-power-profile-monitor’
(WebKitWebProcess:156014): GLib-GIO-DEBUG: 21:24:37.618: Using cross-namespace EXTERNAL authentication (this will deadlock if server is GDBus < 2.73.3)
src/nv_gbm.c:288: GBM-DRV error (nv_gbm_create_device_native): nv_common_gbm_create_device failed (ret=-1)

KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
KMS: DRM_IOCTL_MODE_CREATE_DUMB failed: Permission denied
Failed to create GBM buffer of size 384x816: Permission denied
Feb 18, 2025 9:24:37 PM org.openaudible.desktop.swt.manager.login.LoginInternalBrowser browserEvent

```

**Comment by openaudible** [comment]
That is an unusual one. Does Mozilla Firefox work? 
Try googling some of the error messages. If you have an iso for a linux distribution I can try it but I don't have a graphics card to test with. 

My guess is someone has a flag that can be set to make it work. 

Ugh!

**Comment by bmbeverst** [comment]
How would I set it to use Firefox or Chromium? I tried exporting the values and tried changing the setting.json in the library. Set both `prefer_chromium` and `oa_chromium` to true. Also tried the `browser` setting. But nothing seemed to work, it was always overwritten. 

Also running KDE, not sure if that matters. I am unsure if you can reproduce, since it appears to be an Nvidia issue.

Here is an ISO though: https://download.manjaro.org/kde/24.2.1/manjaro-kde-24.2.1-241216-linux612.iso

Edit: The docker version didn't work either. Wanted to be updated and complained about webkit2gtk not being installed.

**Comment by openaudible** [comment]
We removed chromium support-- so we are just WebKit for Linux. (Chromium was a pain.) so we should take that preference out. 

I can try the iso tomorrow. 

Usually someone else has run into the same issue and posted about it somewhere. So will look as well. 

Thanks for the report

**Comment by bmbeverst** [comment]
There are too many reports, how I found the chromium stuff. Thought it was odd the code didn't have it.

Would hate to have you waste time on the ISO. But if the ISO works, at least we prove it is Nvidia or my system.

**Comment by openaudible** [comment]
Takes 10 minutes to try a new iso and I get to check out a new desktop. 
Will let you know.

**Comment by openaudible** [comment]
I think I figured it out! 
https://openaudible.org/beta

This version sets the environment variables 
"WEBKIT_DISABLE_COMPOSITING_MODE", "WEBKIT_FORCE_SOFTWARE_RENDERING", "WEBKIT_DISABLE_DMABUF_RENDERER" to 1.

**Comment by bmbeverst** [comment]
It works! Thanks so much for making those changes to the beta ❤ 
`WEBKIT_DISABLE_COMPOSITING_MODE=1 WEBKIT_FORCE_SOFTWARE_RENDERING=1 WEBKIT_DISABLE_DMABUF_RENDERER=1 OpenAudible` would duplicate the fix in a normal installation.

**Comment by openaudible** [comment]
Thanks for the confirmation and help getting that fixed. Nice to be able to work around someone else's bug!

**Comment by bmbeverst** [comment]
FYI, you have another happy customer, thanks so much and keep up the wonderful work!

**Comment by openaudible** [comment]
Thanks for bringing it to my attention. Will release a new version shortly.
