### ISSUE TITLE
Feature Request: Manual Chapter Editor prior to splitting

### ISSUE THREAD

**Issue by ZLoth** [openaudible/openaudible#1486]
It would be nice to have a chapter editor for two different cases:

1. Some very old books in Audible were mastered from 45 minute per side tapes, and the chapter stops correspond to the end of those tapes rather than the actual chapters.
2. For omnibus versions of books, the publisher simply glued the three books together. For GraphicAudio, I may not want the chapter setup, but separate MP3/M4Bs for each of those books and removing some of the repeated stuff like "Graphic Audio... A Movie In Your Mind" and the note that it was a bundle at the beginning. (e.g. [Tangent Knights Trilogy Bundle (Dramatized Adaptation)](https://www.audible.com/series/Tangent-Knights-Audiobooks/B09G9PZKSK) ) so that I have three seperate books.

**Comment by openaudible** [comment]
Currently you can only edit the names of the chapters, not the start time and duration. 
The only other way I can think to do this is to use an audio editor and save each chapter as a mp3 file with a name like 01. Introduction, 02. Chapter 1, etc. Then join the files using the File: Join Audio Files option.. That should produce a single file with chapters correct.

No real plans to make a full fledged audiobook editing application.
