### ISSUE TITLE
Export Book List Issue

### ISSUE THREAD

**Issue by Audi-O-Oh-two-tu** [openaudible/openaudible#1489]
When exporting a book list as an Excel file, the "purchase date" and "release date" columns are returning numbers that are not dates, This is a fairly recent event and this is data I use frequently to sort my books by acquisition date. 

Thanks

**Comment by openaudible** [comment]
Will investigate and fix. Thanks.

**Comment by openaudible** [comment]
Fixed in latest beta: https://openaudible.org/beta

**Comment by Audi-O-Oh-two-tu** [comment]
Thank you!
