### ISSUE TITLE
suggestion: control settings for ffmpeg?

### ISSUE THREAD

**Issue by Cybergate9** [openaudible/openaudible#149]
There might be a way to do it in global config (for either ffmpeg or OA)? 
But..
ffmpeg absolutely pegs the processor out on OSX 10.14.5 when doing the mp3 conversions
<img width="638" alt="Screenshot 2019-06-05 10 49 25" src="https://user-images.githubusercontent.com/11902848/58923640-9ca27680-877f-11e9-859f-2f65e76b68cf.png">

**Comment by openaudible** [comment]
You can set number of concurrent conversions by manually editing the concurrentConversions in "settings.json" file from 3 to 1. 

It will still peg one core, but the other cores in your CPU should be free to do work.
