### ISSUE TITLE
Thunderbird nuisance bug after removal of Openaudible

### ISSUE THREAD

**Issue by QuinoaMillet** [openaudible/openaudible#1490]
I tried the openaudible for Linux Mint 21.1 the other day (.deb install) but realized SMPlayer app is just fine for audiobooks so I uninstalled OA.

Problem is after deleting the folder according to OA uninstall instructions, Thunderbird was left with a pop up annoying window bug that looked like this:
![image](https://github.com/user-attachments/assets/8b4cacbd-f628-4ffc-8a0e-a8eaefb85cc0)

Which is an issue with hotmail accounts that had already been resolved months ago following [instructions](https://support.mozilla.org/en-US/kb/microsoft-oauth-authentication-and-thunderbird-202).

Not sure if this bug is related to the install/uninstall of Openaudible, but coincidentally, it happened right after OA removal.

Ultimately, I deleted both hotmail accounts from TB as they're too much trouble compared to my other E-mail accounts and services.

Thank you for reading and have a nice day. 🙏🏼

**Comment by openaudible** [comment]
Pretty sure this is unrelated. The OpenAudible uninstaller doesn't uninstall any system components. OpenAudible is a self-contained app.
