### ISSUE TITLE
JSON / CSV / Excel Table editing

### ISSUE THREAD

**Issue by jcbrooks1066** [openaudible/openaudible#1491]
Problem solve or feature request. The books.json file has all the metadata but when exported to any tables (CSV or Excel) it cannot be reintegrated. Power Query from Excel to extract the JSON directly is problematic and I'm not sure it would save correctly as a readable file again. Can the JSON be translated to an editable table? Or the Application be capable of importing a CSV / Excel file for the library metadata?

Thank you!

**Comment by openaudible** [comment]
No plans for this, unfortunately.
