### ISSUE TITLE
audible.co.uk doesn't go to /lib after the site does a redirect from .com

### ISSUE THREAD

**Issue by cruciux** [openaudible/openaudible#150]
Hi, firstly thank you for this brilliant bit of software. I love paying for my audiobooks, but like to listen to them with a far better player than Audible's android offering.

My issue is that the inbuilt browser (when trying to sync) goes to audible.com, then gets redirected to audible.co.uk - which is correct. But it then doesn't try to go to audible.co.uk/lib - I have to manually change the URL in the address bar, hit enter, then the sync works correctly.

I think a change might be needed to handle redirecting to audible.co.uk/lib AFTER the automatic redirection from audible.com to audible.co.uk by the site itself.

Any thoughts on this?

**Comment by openaudible** [comment]
You're welcome. 

Things "should" start using the .uk site once you open the browser and log in... and the browser will keep cookies to remember who you were. The "Region" in upper left of the OA window should say "UK" and we shouldn't ever make a request to simply www.audible.com".. So I'm not sure.. but the /lib should take you to the .uk /lib... you may be able to look at the console and see if somehow we are going to the wrong url.
