### ISSUE TITLE
Odd visual issue on windows

### ISSUE THREAD

**Issue by FDinolfo** [openaudible/openaudible#151]
Using High Contrast mode in Windows 10, I am seeing an odd visual issue with the main window. Part of it remains white whereas most of it takes on High-Contrast.

I've included a screenshot to illustrate the problem.

<img width="1280" alt="oa-hi-c" src="https://user-images.githubusercontent.com/6538286/59010129-3b6db800-87fe-11e9-9f1f-0a55d6274518.png">

Reproducing the problem is easy on Windows 10. Simply right click on the desktop, choose personalize, then choose High-Contrast Settings on the right. Turn on High-Contrast.

**Comment by openaudible** [comment]
Interesting. Fixed for next release.

**Comment by FDinolfo** [comment]
Thank you. If I find any other oddities I'll make note of them.
