### ISSUE TITLE
Feature: Chapter titles from the ajax feed.

### ISSUE THREAD

**Issue by kellcomnet2** [openaudible/openaudible#153]
Using the web player, there is a chapters button that lists the chapter names with text not just number. Could this be added in to the scraper?

It gets this data from 

https://www.audible.com/cloudplayer?asin=B002V0Q70E&ref_=a_ownedbuybox_cloudplayer#

form data
asin: B002V0Q70E
token: ***Removed***
key: AudibleCloudPlayer
action: getUrl

**Comment by openaudible** [comment]
It looks harder than a quick feature. 

What are you planning to do with the chapter data? I am still looking for good audio book players that support chapter data that is already supported.

I will think about it.. but leaning towards not worth the effort.

**Comment by Xan-Kun** [comment]
Are the proper chapter titles not in the aax file?

**Comment by kellcomnet2** [comment]
> Are the proper chapter titles not in the aax file?

Sorry for the delay, take this book, using FFPROBE you can see the chapter titles are just "Chapter x"
![image](https://user-images.githubusercontent.com/1731737/95583997-98850980-0a02-11eb-87ab-faff677e5b62.png)



but using the player url
![image](https://user-images.githubusercontent.com/1731737/95583945-873bfd00-0a02-11eb-9812-4cfd7f5585dd.png)

**Comment by Xan-Kun** [comment]
Thank you for the answer and absolutel no need to apologize. I am happy that I can hear the books I own on any old device I want to. That's still the main value for me :-)

Having said that, of course it would be nice to habe meaningful chapter names. And I understand, that the web api might change any moment without notice. Basically what will happen might be similar to youtube-dl: Whenever they change something, there are litterally hunderds of tickets and people going crazy about it. And all it takes is a day or two until the new version comes out. I imagine it very stressful :-)

Nevertheless, such an option might be super attractive to nearly all users. How about trying to do it automatically, but when the api call fails or anything else goes wrong, we could just provide a super simple csv-style text, with the times and titels inserted manually. I wouldn't mind and it seems possible with the current muxing suite.
