### ISSUE TITLE
Setup fails

### ISSUE THREAD

**Issue by PresidentBarackObama** [openaudible/openaudible#154]
Hello, 

I get an error while running setup for windows. The installer gets to extracting OpenAudible\bin\rcrack.txt and then a message appears stating C:\Program Files\OpenAudible\bin\rcrack.txt Could not create this file. Shall I try again?  Yes or Cancel.   Yes fails and cancel ends installation.

**Comment by openaudible** [comment]
Check or disable your antivirus and that you have disk space.
