### ISSUE TITLE
Donated.

### ISSUE THREAD

**Issue by jcraig999** [openaudible/openaudible#155]
Hey. Thank you for this amazing application. I have no clue why Audible does not have a desktop app like this. Anyway, I donated $10 via PayPal, so how do I get access to future releases early? My PayPal email address is jcraig999@gmail.com
https://imgur.com/S5NTcib
Transaction ID 3W6590300F2790844

**Comment by openaudible** [comment]
Thanks! As soon as I set up a system to allow "enhanced" content or access to pre-releases, I'll send an email with instructions. Cheers.
