### ISSUE TITLE
Contributing to the newest version

### ISSUE THREAD

**Issue by vandersmissenc** [openaudible/openaudible#157]
Currently the github repo is at 1.1.8 but the latest release is 1.5.2. I am interested in contributing should I download [sources](https://github.com/openaudible/openaudible/releases/tag/v1.5.2) for the latest version, do my updates, and then submit a PR or is there a different process since the github is out of sync?

**Comment by openaudible** [comment]
Yes, try to test it on 1.1.8 source code and send a PR.. or describe the update.. I'm trying to put in fewer hours on this project, so trying to keep new features to a minimum. Most of the core audible code hasn't changed much..
