### ISSUE TITLE
OpenAudible 1.1.4 won't connect in Ubuntu 18.04

### ISSUE THREAD

**Issue by livtin** [openaudible/openaudible#16]
I just did a clean install of Ubuntu 18.04 and tried to install OpenAudible. The original version I installed will not uninstall and the new version will not connect to audible. The program accepts my login and password in preferences and opens the web page for the login page BUT it still indicates Connected No.

**Comment by fakewaffle** [comment]
Same here on macOS High Sierra (10.13)

**Comment by fakewaffle** [comment]
I tried going back to version 1.0 and it wasn't authenticating either.
