### ISSUE TITLE
Works with Audible Escape?

### ISSUE THREAD

**Issue by catqueenpurr** [openaudible/openaudible#161]
Does this work with Audible escape (Previously known as Audible Romance Package)? I try login in with my Audible account. The Audible Escape books appear, but they don't seem to download.

**Comment by openaudible** [comment]
Probably not, but no idea-- don't have access to it. What is the URL that shows your books? We only look at the /lib URL. Is there a "Download" button next to each book?
No plans to add support.

**Comment by catqueenpurr** [comment]
@openaudible How do I view the URL? There's no download button next to the book in Open Audible. When right-clicking, the play audio and download options are grey out. If it helps, they are currently doing a free trial: https://www.audible.com/ep/Romance-Package (Although, if you are unable to add support, then I respect this decision).

**Comment by openaudible** [comment]
Version 3.6 adds support for additional included titles.
