### ISSUE TITLE
Setting for how many books can be converted at once

### ISSUE THREAD

**Issue by MrEbbinghaus** [openaudible/openaudible#162]
Hey,

While converting I noticed that only three books are getting converted at once. 
I have a 6(12) core processor and some books to go through.

A setting to set the number of ffmpeg processes would be nice.

**Comment by MrEbbinghaus** [comment]
I set `concurrentConversions` in the settings.json to 12 and now 4 books are converted at once. 🤔

**Comment by openaudible** [comment]
The max you can set by editing the settings is 10.

**Comment by MrEbbinghaus** [comment]
@openaudible Do you care to explain why you closed the issue? 

Why is the default set to 3? 
Why ist the max 10?

**Comment by openaudible** [comment]
I don't know how well a computer will respond to a large number of concurrent ffmpeg conversions-- I assumed the PC may become unusable with that much CPU load, which is why we set it to 3 and capped it to maximum 10. It was a design issue. I'll increase the limit for the next version.
