### ISSUE TITLE
Add support for new file format *.aaxc

### ISSUE THREAD

**Issue by isukhetskyi** [openaudible/openaudible#163]
Recently audible has changed file format of the audio books which currently is not supported by the OpenAudible app, are you planning to add support for it?

**Comment by openaudible** [comment]
There is no support for decrypting that format. If/when anyone finds that ffmpeg supports it, someone can re-open this issue.. but don't hold your breath. sounds like an improved encryption system.

**Comment by isukhetskyi** [comment]
Ok, thanks for quick reply

**Comment by voltagex** [comment]
The ffmpeg patch is at https://ffmpeg.org/pipermail/ffmpeg-devel/attachments/20200408/eeb2c4e1/attachment.patch

**Comment by kholia** [comment]
https://twitter.com/mkvenkit/status/1277828622095548417
