### ISSUE TITLE
Multipart audiobooks won't import

### ISSUE THREAD

**Issue by jaredmo** [openaudible/openaudible#165]
Programs works great for books with one file. However, when I attempt to import multipart books (File > Import Books), they aren't added. I get the importing screen but when it's complete, the book is not in the library.

Naming example:
The Rise and Fall of_B003VWHZ5C_LC_64_22050_Stereo.aax
The Rise and Fall of_B003VWHZA2_LC_64_22050_Stereo.aax
The Rise and Fall of_B003VWJARS_LC_64_22050_Stereo.aax
etc...

**Comment by openaudible** [comment]
Most books are available as a single download as well as a multi-part version.. We try to only download the full version to avoid trying to deal with multiple files per book. 
What's a link to the book on audible?
Maybe do a bug report after trying to do a library sync.. reference #165

**Comment by jaredmo** [comment]
Got it. Library sync worked, rather than dropping the files into the application.
