### ISSUE TITLE
Pre-order Books not appearing on release

### ISSUE THREAD

**Issue by milegrin** [openaudible/openaudible#166]
I pre-ordered a Danielle Steel audiobook in April which was released on Tuesday (26 June) and none of the sync's (quick & full) enabled the ability to download the book.  I waited 2 days just in case and confirmed the book showed as available in my library.  

I tested using 1.5.2 on Linux and windows 10 clients.

As a work around I manually downloaded the AAX file into the Openaudible AAX folder and imported it.
![pre-order](https://user-images.githubusercontent.com/3263146/60246503-17623b80-98bf-11e9-8e69-5fec844bdd02.png)

PS: How much would you charge to add the ability to export book info to text file option?  Either a configurable item (EG enable text file export in setting) or a small unobtrusive button/link per book on the interface.

**Comment by openaudible** [comment]
The book would need to show up in your "library" view in the browser with a download link next to it.. If there, the software should have found it and added it.. but maybe not at the top of the list? Not sure why, but hard to reproduce after its been downloaded. 

I haven't done any custom work yet... Did you see the export to excel and json? From there its pretty easy to extract a book and create a text document. But I can be bribed.. describe the text format you'd like to see.

**Comment by milegrin** [comment]
Hi
Thank you.  Next time I pre-order a book I will test the work-around.

As for the text output request; I have created and example on pastebin to retain formatting and spacing : https://pastebin.com/NvnLgaUX  

For teh implementation, I had 2 ideas that may work (obviously it is ultimately up to you :) )
Firstly, a menu item under preferences to enable or disable saving the into to text that would save it automagically when the audiobook is added to the library and details retrieved (much like the artwork is)

The second is to add a "save" button with the info.  This is a very rough example of what I mean:

![save_nfo](https://user-images.githubusercontent.com/3263146/60445197-0a2ab100-9c1f-11e9-8811-08e34439ce75.png)

Thank you for considering the request.
Please provide an estimate of how you would like for a donation toward the request.
Thank you
Michael
