### ISSUE TITLE
Not finding any books on MacOS (SEVERE: Unable to set purchaseDateFilter.)

### ISSUE THREAD

**Issue by krpan** [openaudible/openaudible#17]
Build: OpenAudible 1.1.4
Released: 2018-06-30

Fresh install on MacOS 10.13.5

OpenAudible shows me as connected and if I bring up the browser I can navigate the site. However, both Quick and Full Library Sync indicate zero books.

The console indicates **SEVERE: Unable to set purchaseDateFilter.**

Full console log upon requesting Full Library Sync is as follows:

`Jul 03, 2018 7:02:44 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute`
`INFO: Execute: Rescan_Library`
`Jul 03, 2018 7:02:44 PM org.openaudible.audible.AudibleScraper setURL`
`INFO: setURL:/access`
`Jul 03, 2018 7:02:45 PM org.openaudible.audible.AudibleScraper setPage`
`INFO: pageLoaded:https://www.audible.com/account/access Download Audiobooks with Audible.com`
`Jul 03, 2018 7:02:45 PM org.openaudible.audible.AudibleScraper setURL`
`INFO: setURL:/lib`
`Jul 03, 2018 7:02:46 PM org.openaudible.audible.AudibleScraper setPage`
`INFO: pageLoaded:https://www.amazon.com/ap/signin?clientContext=XXX-XXXXXXX-XXXXXXX&openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.audible.com%2Flib&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_audible_us&openid.mode=checkid_setup&marketPlaceId=XXXXXXXXXXXXX&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_audible_bc_us&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0& Amazon Sign In`
`Jul 03, 2018 7:02:46 PM org.openaudible.audible.AudibleScraper setPageFilter`
`SEVERE: Unable to set purchaseDateFilter.`
`com.gargoylesoftware.htmlunit.ElementNotFoundException: elementName=[*] attributeName=[name] attributeValue=[purchaseDateFilter]`
`	at com.gargoylesoftware.htmlunit.html.HtmlPage.getElementByName(HtmlPage.java:1572)`
`	at org.openaudible.audible.AudibleScraper.setPageFilter(AudibleScraper.java:547)`
`	at org.openaudible.audible.AudibleScraper._fetchLibrary(AudibleScraper.java:477)`
`	at org.openaudible.audible.AudibleScraper.fetchLibrary(AudibleScraper.java:584)`
`	at org.openaudible.Audible.updateLibrary(Audible.java:336)`
`	at org.openaudible.desktop.swt.manager.AudibleGUI$3.run(AudibleGUI.java:328)`
` `
`Jul 03, 2018 7:02:46 PM org.openaudible.Audible updateLibrary`
`INFO: Updated 0 books`

Please note that I replaced the text with X's where it seemed advisable.

**Comment by openaudible** [comment]
It looks like you got redirected to the login page which didn't happen very cleanly.. which can happen if audible thinks  you are logging in with stale user/password.. re-logging should fix that.. sometimes it can take a few tries.
