### ISSUE TITLE
unable to download books

### ISSUE THREAD

**Issue by Butterfly-Dragon** [openaudible/openaudible#170]
i get an "unspecified database error"

**Comment by openaudible** [comment]
Not my error message. Maybe an audible problem or the book is no longer available? Open it in the OA browser and click the download button for that book in the web page. Feel free to post the full console error from when you click download to when the error is reported.

**Comment by Butterfly-Dragon** [comment]
it ceased on its own 2 days ago, lasted only 2 days, origin unknown, the stuff you said to try worked at the time, but i did not know there was a console to dump
