### ISSUE TITLE
unable to convert book to MP3 (on Windows)

### ISSUE THREAD

**Issue by ilyatout** [openaudible/openaudible#172]
![error](https://user-images.githubusercontent.com/53450380/62081185-67cc1080-b252-11e9-8dbd-a6e70f151223.png)
![error](https://user-images.githubusercontent.com/53450380/62081216-74e8ff80-b252-11e9-9358-226856c6bbfd.png)

Hello,

I am on windows, no ANTIVIRUS or other running, but always the same issue with rcrack causing issue to convert to MP3.

Picture attached.

Please help,
THanks

**Comment by ilyatout** [comment]
Same error each time. I tried to update RCRACK, but same issue.
Please help :)

**Comment by openaudible** [comment]
Never heard of this problem.

It says "no rainbow table found". The tables are files in the OpenAudible/bin/tables directory. Check that to make sure files are there. 

You must have 4 .rt files and a readme in the folder:
C:\Program Files\OpenAudible\bin\tables

You can also try running the command from the command line-- it should be fully shown in the console window. (command is shown in picture above, from cmd: up to but not including the exit=0)


Re-installing the whole app might help.
