### ISSUE TITLE
Audio glitches

### ISSUE THREAD

**Issue by Jan0707** [openaudible/openaudible#173]
Hey everyone,

Whenever I try to convert an audiobook the resulting file ends up with audio glitches every x seconds. Any ideas ?

**Comment by openaudible** [comment]
No. Try multiple mp3 players? Check your system performance. 

ffmpeg converts the file, so you can google ffmpeg aax audio conversion glitches.

If anyone else has suggestions, feel free to respond but I don't think this is a repeatable or known bug.

**Comment by Jan0707** [comment]
Strangely, you are right. The issues is not present when using VLC for Playback. Before I only used QuickTime (in Mac) - I honestly did not expect issues like that in software that is so commonly used for media play back.
