### ISSUE TITLE
OpenAudible builds shouldn't expire

### ISSUE THREAD

**Issue by tensiondriven** [openaudible/openaudible#174]
I use OpenAudible every couple of months to create audio files from my audio books.  It seems that every time I open the app now (which is every month or two), I'm told that the current version has expired and that I must download a new copy.

I'm not interested in using any new functionality, so why am I unable to use an existing build? 

Removing this constraint would make the application more useful.

**Comment by tensiondriven** [comment]
The specific request here is to remove the feature that checks to see if there is a new version of OpenAudible and closes the application if there is a new version available.

**Comment by openaudible** [comment]
I like to keep users on the latest version. That may change in the future. Thanks for the suggestion.

**Comment by AMArostegui** [comment]
I'm all in for security updates and so... but for a standalone local first program this seems a drag.

And FORCING the user to update, seems like the trend followed by corporations with tracking-first and saas mentality.

It's hard not to be thankful for Open Audible. Is a marvelous and useful software, but this feature is against what seems to be its philosophy
