### ISSUE TITLE
Support Podcast

### ISSUE THREAD

**Issue by STX2k** [openaudible/openaudible#175]
Hi, 

Can you please add podcast support? So we can download Aud*ble Origin Podcasts? 

Greets STX

**Comment by ptownzizzle** [comment]
I have had the same problem. Couldn't download podcasts. For example 'How Not to F*ck Up Your Kids Too Bad' and 'The Last Days of August'.

OpenAudible couldn't download them directly. It saw them in my library but the circle on the left was red and the download option was greyed out.

When I went to my web browser an clicked an episodes download link it downloaded a file called admhelper.adh . Opening that file caused AudibleDownloadManager to grab it and so I ended up just using that to download the file. Then I imported the AAX files to OpenAudible and converted them to MP3 from there.

Hopefully that's helpful to anyone having the same issue.

**Comment by openaudible** [comment]
Hmm. Opening an audiblehelper file from the OpenAudible browser (CMD-B) should start the download & import. 
Looking up those two titles in audible, neither use the word "podcast", so they look like regular books to me. But I don't own either. Not sure why they wouldn't automatically show up in your list of books. 

Glad you found a solution.
