### ISSUE TITLE
Sync problem with purchase dates

### ISSUE THREAD

**Issue by rdow64** [openaudible/openaudible#18]
using 1.1.4 
full sync purchase dates problem.  All books earlier than 06-10- #2011 are all being given the 6-10-2011 date.  should be around a hundred books going back to 2004.

**Comment by openaudible** [comment]
Is the purchase date correct when viewed in Audible when viewing your library as a list?

**Comment by rdow64** [comment]
Interesting.  Library list has same problem on Audible, but purchase history has real dates.  Oh well, not a problem with your tool.  THx

**Comment by openaudible** [comment]
Closed as an audible bug.
