### ISSUE TITLE
Doesn't convert to mp3 with big files?

### ISSUE THREAD

**Issue by 1337pwner** [openaudible/openaudible#184]
Hello,

Thank you for the wonderful programme! I am new to Open Audible and I am new to Github, but I thought I would report that when I tried to convert 'Sherlock Holmes - The Definitive Collection', it wouldn't work. I presume it's because the size of the files is too big. Many thanks!

**Comment by 1337pwner** [comment]
Thanks for your reply! Actually I have had no problems adding any book to the programme, but specifically with 'Sherlock Holmes - The Definitive Edition', narrated by Stephen Fry, which seems quite popular, will not add. I've tried dragging and dropping it onto the programme but not one of the parts seems to be recognised by it. It also coincidentally seems the biggest book I have tried to add.

**Comment by openaudible** [comment]
Copy and paste any errors in the Console window generated when adding the file.

**Comment by 1337pwner** [comment]
Ah, it seems the book has an invalid date:

Aug 29, 2019 8:55:45 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 1.5.3 for win32 swt 4623 jvm 1.8.0_202
Aug 29, 2019 8:55:45 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 1.5.3
Aug 29, 2019 8:55:45 PM org.openaudible.Audible load
INFO: Loading C:\Users\Feidhlim O'Luachra\OpenAudible\books.json
Aug 29, 2019 8:55:45 PM org.openaudible.Audible checkLibrary
SEVERE: loaded 2 books.
Aug 29, 2019 8:55:45 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: "C:\Program Files\OpenAudible\bin\win\ffmpeg.exe" -version 
Aug 29, 2019 8:55:45 PM org.openaudible.desktop.swt.manager.AudibleGUI checkFFMPEG
INFO: using ffmpeg version N-76456-g6df2c94 Copyright (c) 2000-2015 the FFmpeg developer
Aug 29, 2019 8:56:15 PM org.openaudible.desktop.swt.manager.views.FileDropTarget drop
INFO: drop file:C:\Users\Feidhlim O'Luachra\Documents\Audible\Programs\Downloads\SherlockHolmesTheDefinitiveCollectionPart1_ep6_KuWH7yO-uEZJEGdnDAceOR7L8nXuswPzVtxaM7gpksMyL-IHONMVitqq7-0_eQ.aax exists=true
Aug 29, 2019 8:56:15 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: "C:\Program Files\OpenAudible\bin\win\ffmpeg.exe" -i "C:\Users\Feidhlim O'Luachra\Documents\Audible\Programs\Downloads\SherlockHolmesTheDefinitiveCollectionPart1_ep6_KuWH7yO-uEZJEGdnDAceOR7L8nXuswPzVtxaM7gpksMyL-IHONMVitqq7-0_eQ.aax" -f ffmetadata - 
Aug 29, 2019 8:56:15 PM org.openaudible.Audible expired
WARNING: book contains invalid date: Sherlock Holmes: The Definitive  date=2200-01-01 product_id=BK_ADBL_030145a,asin=B06VX1CD9Q,title=Sherlock Holmes: The Definitive Collection Part 1,author=Arthur Conan Doyle, Stephen Fry - introductions,narrated_by=Stephen Fry,summary=Ever since he made his first appearance in 
A Study In Scarlet, Sherlock Holmes has enthralled and delighted millions of fans throughout the world. Now Audible is proud to present Arthur Conan Doyle's 
Sherlock Holmes: The Definitive Collection, read by Stephen Fry. A lifelong fan of Doyle's detective fiction, Fry has narrated the complete works of Sherlock Holmes - four novels and five collections of short stories.,duration=06:35:38,release_date=01-JAN-2200,publisher=Audible Studios,title_short=Sherlock Holmes: The Definitive Collection Part 1,copyright=©2017 Stephen Fry (introductions); original text public domain (P)2017 Audible, Ltd,filename=SherlockHolmesTheDefinitiveCollectionPart1_ep6_KuWH7yO-uEZJEGdnDAceOR7L8nXuswPzVtxaM7gpksMyL-IHONMVitqq7-0_eQ,
Aug 29, 2019 8:56:15 PM org.openaudible.desktop.swt.manager.ImportExport _importFile
WARNING: Unable to import book:C:\Users\Feidhlim O'Luachra\Documents\Audible\Programs\Downloads\SherlockHolmesTheDefinitiveCollectionPart1_ep6_KuWH7yO-uEZJEGdnDAceOR7L8nXuswPzVtxaM7gpksMyL-IHONMVitqq7-0_eQ.aax : Book too new for version Sherlock Holmes: The Definitive 
Aug 29, 2019 8:56:15 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Aug 29, 2019 8:56:20 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by openaudible** [comment]
The book you are importing has an invalid release date of 2200-01-01. Not sure why, but that prevents the book from importing.

You might be able to delete the book from openaudible.. then go to: https://www.audible.com/pd/Sherlock-Holmes-Audiobook/B06WLMWF2S
in the OA browser.. and click download and try again.
The release date is supposed to be 02-27-17

Thanks for the report..
