### ISSUE TITLE
OpenAudible won't download whole library

### ISSUE THREAD

**Issue by fishpoke** [openaudible/openaudible#185]
When synchronizing first time I only got 20 books. Quick Sync : "Library is up to date!"

When I alter the "title per page" to 40 (Browser) and try to sync again I got 40 books. How can I manage to download all my books ?

**Comment by openaudible** [comment]
Try "Full Library Sync". 
Quick Library sync scans the first pages of books until no new books are found. You library must be sorted by most recent purchases for the quick sync to work properly.

**Comment by girino** [comment]
Same here for me. Full Library Sync doesn't work. I can get some extra books by changing the way they are sorted, but could'nt get past 151 (i have more than 500)

**Comment by sonnenlanze** [comment]
Same here. Full Library Sync only gives back page one (of more than 10)

> Okt 03, 2019 10:55:29 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
> INFORMATION: Command: Rescan_Library
> Okt 03, 2019 10:55:29 AM org.openaudible.audible.AudibleScraper _fetchLibrary
> INFORMATION: ******************* LIBRARY PAGE 1
> Okt 03, 2019 10:55:29 AM org.openaudible.audible.AudibleScraper setPageFilter
> WARNUNG: setPageFilter Unimplemented
> Okt 03, 2019 10:55:29 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
> INFORMATION: Library page contains: 20 book(s)
> Okt 03, 2019 10:55:29 AM org.openaudible.audible.AudibleScraper _fetchLibrary
> INFORMATION: pageNum=1 total=20 new=20 partial=0
> Parsed:20 books
> BK_AREN_000439DE: 	new:The Fires of Heaven: Book Five o
> BK_AREN_000421DE: 	new:The Shadow Rising: Book Four of 
> BK_AREN_000420DE: 	new:The Dragon Reborn: Book Three in
> BK_AREN_000371DE: 	new:The Great Hunt: The Wheel Of Tim
> BK_ADBL_050938DE: 	new:Unfettered III: New Tales by Mas
> BK_AREN_000370DE: 	new:The Eye of the World: The Wheel 
> BK_RHUK_002292DE: 	new:The Magicians, Book 1
> BK_ADBL_027985DE: 	new:Skyward
> BK_ADBL_020668DE: 	new:Unfettered II: New Tales by Mast
> BK_HCUK_003091DE: 	new:The Core: The Demon Cycle, Book 
> BK_HCUK_002005DE: 	new:The Skull Throne: The Demon Cycl
> BK_HCUK_001861DE: 	new:The Daylight War: The Demon Cycl
> BK_HCUK_001860DE: 	new:The Desert Spear: The Demon Cycl
> BK_HCUK_001859DE: 	new:The Painted Man: The Demon Cycle
> BK_ORIO_001018DE: 	new:Arcanum Unbounded: The Cosmere C
> BK_ORIO_000895DE: 	new:The Bands of Mourning: A Mistbor
> BK_ORIO_000867DE: 	new:Shadows of Self: A Mistborn Nove
> BK_PENG_003900DE: 	new:Brief Cases
> BK_PENG_002891DE: 	new:Shadowed Souls
> BK_TWUK_000709DE: 	new:Side Jobs: Stories from the Dres
> 
> Okt 03, 2019 10:55:29 AM org.openaudible.Audible updateLibrary
> INFORMATION: Updated 20 books
> Okt 03, 2019 10:55:29 AM org.openaudible.util.HTMLUtil writeFile
> INFORMATION: wrote 66069 to disk:C:\Users\Sunny\OpenAudible\tmp\saved_books.json
> Okt 03, 2019 10:55:29 AM org.openaudible.desktop.swt.manager.AudibleGUI downloadAndConvertWithDialog
> INFORMATION: You have 20 book(s) to download.
>  autoConvert=false
