### ISSUE TITLE
How do I get "ignored" files back?

### ISSUE THREAD

**Issue by prestonstell** [openaudible/openaudible#189]
I was trying to delete the aax files I put on to Open Audible. It let me go through the process of "deleting" although they didn't really leave the Open Audible screen. I then chose "Ignore" the file which was a right-click option next to "Delete." Now when I try to open that file again ("Import file") it loads but I can't find it anymore. I've tried uninstalling and reinstalling Open Audible, but when I reinstall and open it still says the same "40 files" from before, only 11 of which I can actually view or do anything with. The other 29 were "ignored" and I can no longer view in the app, much less convert from aax to mp3. Thank you for the help!

**Comment by openaudible** [comment]
There is currently no GUI to restore ignored books. But you can delete the ignore.json file to restore all books, or carefully use a text editor to edit the list of ignored books.

The ignore.json file can be found by opening the Preferences dialog. Near the bottom is the path to your preferences directory. You can click: "Show"
