### ISSUE TITLE
Automatically update web page copies all MP3 again when a new book is downloaded.

### ISSUE THREAD

**Issue by girino** [openaudible/openaudible#192]
I had the same books being copied several times simultaneously because i set the "Automatically update web page". As soon as it finished some conversion, it copied not only the new file, but all existing mp3. When downloading the full library the first time, this meant i had 10+ copies of the same files being performed simultaneously.

**Comment by openaudible** [comment]
I added some new checks to make sure the code doesn't get called more than once at a time.. For now, disable until next version is out. Re-open if it happens again after 1.5.4.
