### ISSUE TITLE
Books no longer available appear twice, with a strange icon, and their mp3 is not found after conversion

### ISSUE THREAD

**Issue by girino** [openaudible/openaudible#193]
I have some books that are no longer available on audible. They appear twice on the list, and they have very strange behaviour:
- Their download and conversion rates are repeated, even if i only asked for one to be downloaded. 
- Strange icon (orange RSS like icon)
- MP3 is not found by openaudible and not listed after conversion. File exists in mp3 folder.

screenshot atached
![Screen Shot 2019-09-15 at 18 25 02](https://user-images.githubusercontent.com/1211762/64927890-0e5e7780-d7e7-11e9-9544-308cc4e76329.png)

**Comment by openaudible** [comment]
That icon means there is an AAX (audible) file.. but no mp3 file. If the mp3 exists but OA can't find it, it may be there is a file name difference. The aax file and mp3 file must have the exact same name, except for the extension. Are there any non-standard ascii characters in the file name? 

Keep a backup of the aax files... I think this version of OA has a broken "Delete book" function, so it may be hard to fix.. but usually you could delete the references in OA, then import the AAX manually (from a location not in the OA /aax directory.)
