### ISSUE TITLE
Create homebrew cask for open audible?

### ISSUE THREAD

**Issue by jakevossen5** [openaudible/openaudible#197]
Has this project considered creating a [Homebrew](https://brew.sh) cask for this project? I personally try to install as much software as I can through Homebrew and find it really nice to use to keep software up to date.

I looked into it a bit, and I think the initial barrier is that a `.app` would have to be distributed, not the installer. 

I am willing to work on this, but if I do, would this be something this project is interested in?

**Comment by openaudible** [comment]
@jakevossen5 did something for windows using chocolatey. Take a look at issue #110. 
If you made a script I could run after each new version, that might be the easiest way.

**Comment by jakevossen5** [comment]
Thank you. I will look into that.
