### ISSUE TITLE
Connecting to audible server opens up /account/access endpoint in a web browser

### ISSUE THREAD

**Issue by johnyoonh** [openaudible/openaudible#20]
Version 1.1.4
Tested on Windows 10, Mac OS, Ubuntu 16.04 LTS
Connect to Audible
Open up a web browser with no toolbars on address `https://www.audible.com/account/access?serial=&`
The page doesn't seem to load CSS.
Signing in doesn't affect the program. Adding credentials in the preference doesn't affect the program.

I do not have active membership with audible.com but I have audiobooks that I purchased in the past.

**Comment by cobalt027** [comment]
Confirmed the above comment (from johnyoonh). I DO have an active membership.
Duplicated on Win 7, Win10, MacOS 10.11
Connect to Audible, Quick Sync, Full Sync all yield the browser open to https://www.audible.com/account/access with no toolbars and most of the time no CSS.

**Comment by Erudition** [comment]
Same problem. I have an active subscription. That page seems to look the same in Firefox, too, so maybe Audible has stopped making that a valid URL anymore.

**Comment by jasoncawood** [comment]
> The http://audible.com/access page is for visually impaired people and makes it easier for openaudible to determine if it is logged in or attempt to log in. It does look like it now redirects to /account/access.

> The best way to fix this is make sure you can view your library in the built-in browser (CMD-B) and go to the /lib page. (For non-US audible, this may not work!) Also make sure you're logging on with the web browser with the same (and correct) credentials in the preferences.

> Looking to confirm and improve logging in.

This did work.  I was able to update my library through the program.  Thanks!

**Comment by Erudition** [comment]
Not sure what this changes. The web browser is logged in and sitting at the /lib page, with my library showing. The preferences are set. But how do I get it to connect to my account? There doesn't seem to be anything relevant to do on this page.

**Comment by openaudible** [comment]
If you are logged on to audible in the OpenAudible web browser (cmd-B) then logging on via the "connect" or "refresh library" is supposed to work. (Cookies from your browser session are used..) If you're unable to connect using the OpenAudible "Connect".. make sure you have your log-in name correct, you're using the latest version... You can open the Log Window and look for a human readable error.. or copy and paste the console output in a new issue.
