### ISSUE TITLE
Version expired popup message

### ISSUE THREAD

**Issue by wcurtiss** [openaudible/openaudible#200]
Just installed OpenAudible_deb_1.5.3.deb on Linux Mint 19.1
When I start the app I get a popup saying:
  "This version of OpenAudible has is expired."
  "Please download a new version from openaudible.org"

**Comment by openaudible** [comment]
What is the date set on your Ubuntu? We use some code to make sure the date is more or less correct so we don't write incorrect dates into the audio files.
