### ISSUE TITLE
Cannot Install OpenAudible on Mac OSX El Cap

### ISSUE THREAD

**Issue by kcchrist** [openaudible/openaudible#202]
When I click the installer it returns error "You can't open the application 'OpenAudible Installer' because it is not responding". 
<img width="421" alt="Screen Shot 2019-10-07 at 10 00 59 PM" src="https://user-images.githubusercontent.com/8407084/66364079-1759e900-e94e-11e9-94e8-17900ce4451f.png">

**Comment by openaudible** [comment]
Try again.. re-download.. right click on the installer and select open. You're the only to report this, so its probably something on your end.
