### ISSUE TITLE
Converted MP3s directory

### ISSUE THREAD

**Issue by biziosan** [openaudible/openaudible#203]
Thank you for OpenAudible! It solved all my problems with my audio books. 

I changed the "Web/MP3" directory in the preferences dialog to where my audio books should go. However, after the book is converted to MP3, the new file is still going to the OpenAudible/mp3 directory. 

Is this a bug? If not, is there a way to tell OpenAudible to save the MP3 is a specific directory?

**Comment by openaudible** [comment]
The web directory and the mp3 work directory is supposed to be separate. The idea was the work directory had aax/mp3/art files.. but the web directory was a copy of that. Inefficient, but had to do with trying to keep the file names sane, and keep the aax directory out of the web directory. Your options are to deal with the duplicate waste of space.. or not use the web export feature. But definitely don't have the work directory overlap with the web directory.
