### ISSUE TITLE
Multiple links for v1.5.2

### ISSUE THREAD

**Issue by livtin** [openaudible/openaudible#204]
I cannot remove these links, 1.5.3 link is not showing and I cannot uninstall 1.5.2 using uninstall script
Help appreciated

**Comment by openaudible** [comment]
I don't know what you mean. Uninstall as much as you can.. Then manually search for and delete program files and shortcuts that belong to openaudible.. then re-install if you want. You may need to look for a windows uninstall/cleanup utility if you see further errors.
