### ISSUE TITLE
Open Audible will not install on Mac Catalina 

### ISSUE THREAD

**Issue by Mikeropc** [openaudible/openaudible#205]
Tried to install OpenAudible 1.5.3 on Macbook Pro with Latest OS Catalina and got  error message "This software needs to be updated. Contact the developer for more information."

**Comment by openaudible** [comment]
Select and right-click "OpenAudible Installer". Its on the list to make it a little more clear. 

We don't have an apple developer account that we can sign our app with so you have to use the right-click open method.
