### ISSUE TITLE
rcrack crashes on execution

### ISSUE THREAD

**Issue by antymat** [openaudible/openaudible#206]
As mentioned in issue #196, rcrack crashes on a decode attempt. The solution in #196 is a no-solution: after checking the antivirus (no complaints) **and** switching off the firewall, the result is still the same. MD5 of both rcrack executables is the same.

**Comment by openaudible** [comment]
Please don't create a new issue for the same problem. You can reopen 196. But the answer is the same--it is something with your system. are you on a 32 bit machine? The source code is available for you to compile, run and debug. https://github.com/inAudible-NG/tables with another executable https://github.com/inAudible-NG/tables/tree/master/run

**Comment by openaudible** [comment]
This may be fixed in 2.0.6.
