### ISSUE TITLE
ffprobe binary isn't in OSX package.

### ISSUE THREAD

**Issue by Robotto** [openaudible/openaudible#211]
The "Split by chapter" feature requires ffprobe to function.

Issue is solved on user's machine by placing the ffprobe binary from https://ffbinaries.com/downloads in the location specified by the error message.

Developers should package the ffprobe binary alongside the ffmpeg binary in future releases.

**Comment by openaudible** [comment]
Thanks. Will update linux and mac.

**Comment by openaudible** [comment]
Fixed in release 1.5.5.
