### ISSUE TITLE
Descriptions on web server not formatting properly

### ISSUE THREAD

**Issue by SilverSkyes** [openaudible/openaudible#213]
Sample description for illustrative purposes -

`<p><b>Winner of the Specsavers Popular Fiction Book of the Year 2018.</b></p> <p>Costa First Novel Book Award winner 2017. </p> <p><i>The Sunday Times</i> best seller. </p> <p><i>AudioFile Magazine</i> Earphones Award Winner. </p> <p>Soon to be a major motion picture produced by Reese Witherspoon. </p> <p>Eleanor Oliphant has learned how to survive - but not how to live </p> <p>Eleanor Oliphant leads a simple life. She wears the same clothes to work every day, eats the same meal deal for lunch every day and buys the same two bottles of vodka to drink every weekend. </p>`

It's formatted as code because Github interprets and hides the markdown. I tried it with the latest versions of Firefox, Chrome and Safari; no dice. I don't know enough about HTML to debug this.

**Comment by openaudible** [comment]
Try again with 1.5.5. Feel free to take a screenshot and post it here.

**Comment by SilverSkyes** [comment]
- I downloaded and installed OpenAudible v1.5.5
![OpenAudible_Version](https://user-images.githubusercontent.com/19542026/67610930-f71f8c00-f78d-11e9-8712-5651562a64be.png)

- I deleted everything in the 'web' directory
![OpenAudible_empty](https://user-images.githubusercontent.com/19542026/67610995-60070400-f78e-11e9-8024-13bcdea0c04e.png)

- I opened the OpenAudible app and exported the webpage to regenerate it
![OpenAudible_regenerate](https://user-images.githubusercontent.com/19542026/67611170-b0329600-f78f-11e9-8bab-3830e66226c4.png)

- No improvement I'm afraid
![OpenAudible_web](https://user-images.githubusercontent.com/19542026/67611262-4c5c9d00-f790-11e9-92f5-99e77e951f8b.png)

**Comment by openaudible** [comment]
Ah, that error. Got it.. Will fix.

**Comment by openaudible** [comment]
Fixed in 1.6
