### ISSUE TITLE
Add support for multiple accounts

### ISSUE THREAD

**Issue by n8udd** [openaudible/openaudible#215]
I can't see a way at the minute that I can logout from my account and login to my wife's account to back up her library purchases also? Is this an option that I'm missing, or not possible?

If it's the latter, it would be useful if multiple logins were supported, or at least multiple sign in certificates, so that I could download her aax from the browser and import manually.

**Comment by openaudible** [comment]
You should be able to log out and log in with your wife's account. If you want to keep them separate, you'll need to change the working directory.. then restart OA, then log in to her account. So, it is supported, may just require a little experimenting.

**Comment by openaudible** [comment]
https://openaudible.org/beta
