### ISSUE TITLE
Import of already downloaded .aax files isn't working

### ISSUE THREAD

**Issue by ldkearl** [openaudible/openaudible#216]
Hi, I drag several .aax files onto the app in the section where it lists the books or else import them using File->Import Books. I see a progress bar saying the files are importing. But they don't appear in the list of books and so I am not able to then convert them to mp3.

I'd rather not get them by linking to Audible because I wan't to convert the individual parts of some long books (30+ hours) so that in my audio player I have better control over scrubbing forward/backward.

The manually importing files worked about a week ago, but now doesn't. I updated to v 1.5.5 and am using OS X 10.14.6. I can't think of any changes I've made that should cause this to not work. Thanks.

**Comment by openaudible** [comment]
Importing AAX files still works. Check the console for errors..  If they're partial files, they might get skipped... you can split a whole book into chapters now if you want.

**Comment by openaudible** [comment]
Going to close.. only full aax files can be converted.
