### ISSUE TITLE
Download of books doesn't work - version 1.5.5

### ISSUE THREAD

**Issue by m-j-r** [openaudible/openaudible#217]
I'm getting an error message when I try to download a book - it seems like it is unable to parse some HTML, and ends up spitting the whole lot out into the console.

I have sent a bug report from the app.

**Comment by openaudible** [comment]
OK. I wasn't sure which bug report. If you can, use version 1.6 (or latest), open the app, try to download the file, then submit a bug report with #217 in the topic. But also read the console log-- it may have a human readable error log.
