### ISSUE TITLE
Guide to a "NO START?"

### ISSUE THREAD

**Issue by MRGEE223** [openaudible/openaudible#218]
I run LUBUNTU 19.04.
Installed the Debian package listed for openaudible.
After, I get no response when trying to open it.
It shows on the GUI "OTHER" Programs, but it will not respond in any way.
Is there a guide to troubleshooting, or could you provide a couple of options?

**Comment by openaudible** [comment]
Try running the OpenAudible from the command line:

`/opt/OpenAudible/OpenAudible
`

(The app may be installed somewhere else... Adjust as needed)

You can also run the app from java on the command line:

```
cd /opt/OpenAudible
java -cp "openaudible-jar-with-dependencies.jar:org.eclipse.swt.gtk.linux.x86_64-4.6.jar" org.openaudible.desktop.Application
```

See what happens.

**Comment by MRGEE223** [comment]
The issue became instantly apparent when I tried opening it.
(No JVM installed.)
Installed Java and POOF! It worked.
Is there a pre-req page I missed?
Thanks for the nudge!
