### ISSUE TITLE
Conversion from AAX to MP3 failing

### ISSUE THREAD

**Issue by rdoherty47** [openaudible/openaudible#22]
Using version 1.1.4 on Mac OSX El Cap. Conversion from AAX files to MP3 files appears to fail. I can play the AAX files in iTunes fine, but when I play resulting converted MP3, the file duration is different (drastically so). Seems like most chapters or something are getting lost during the conversion? This happens if I try to convert a whole bunch of audiobooks at once, or even if I try one at a time. I see the "Converting..." message with the time stamp slowly increasing, but it just seems to stop randomly. If there's a way to provide additional logs or anything, let me know and I'll do that.

**Comment by openaudible** [comment]
Strange. Make sure you're using the latest version. 

Open the Console window from the file menu. 
Select one file to convert. Convert it to MP3. Copy and paste the log output after the "ffmpeg" command.. 

Selecting the book as it converts should show the time converted go towards the duration of the book.

When you open and play the MP3, make sure it "This is Audible" and ends at the end of the book. 

Make sure you have enough disk space. 

A successful conversion should look like: (please hide activation_bytes or don't post ffmpeg command) 

INFO: "C:\Program Files\OpenAudible\bin\win_ffmpeg" -activation_bytes xxxx -i M:\Books\Audible\aax\BK_ADBK_0000xx.AAX -map_metadata 0 -codec:a libmp3lame -qscale:a 6 M:\Books\Audible\tmp\BK_ADBK_0000xx_temp.mp3 
Jul 30, 2018 11:22:43 AM org.openaudible.convert.ConvertJob createMP3
INFO: createMP3:0
Jul 30, 2018 11:22:43 AM org.openaudible.convert.ConvertJob convert
INFO: converted M:\Books\Audible\mp3\BK_ADBK_0000xx.mp3 200 seconds.
Jul 30, 2018 11:22:43 AM org.openaudible.Audible jobCompleted
INFO: ConvertQueue name of book size:0

**Comment by rdoherty47** [comment]
So I realized that the files that were downloaded from Audible were the problem. I was having a hard time using the tool to download, once the browser opened, so maybe I did something weird? Either way I went and downloaded them again and the conversion works now. Thanks!
