### ISSUE TITLE
making it work with an IT audible account

### ISSUE THREAD

**Issue by tsolignani** [openaudible/openaudible#222]
i am willing to work on that, right now I am importing files otherwise downloaded but would like to be able to use only openaudible and connect my library. Thank you and congrats for the great work. PS no matter what, openaudible always connect to US region as of now and doesn't see any book into the library.

**Comment by openaudible** [comment]
We disabled Audible IT region because we need the following URL to show your library (list of books)

https://audible.it/lib
Does the above URL show your audible library? 

Thanks for the offer.

**Comment by tsolignani** [comment]
As a matter of fact, it does not.
The US audible version let users access the library, while the IT one doesn’t, I have no idea why.
Thank you.

**Comment by openaudible** [comment]
I don't know how the Italian site works. Are you able to see all your books online? Are there any "download" book links? How do you "buy" books? After you buy one, what are your options to listen to it? Curious why it is different from the other regions. If someone from Italy wanted to send some screenshots that show the library and "purchased book" pages.. that might help.

**Comment by tsolignani** [comment]
No, you do not have access to the library. If you try to get to www.audible.it/lib <http://www.audible.it/lib> you get an error, as if not existent. You cannot see all your books online and there is no download link. When you browse the catalogue, there is though an «add to library» button, but afterwards you cannot see any library… You can just start listening the book you just added to the library. There is no Mac app, as you know, but you can see all your books, and download them, into the a) android app b) windows app. As an Italian user, you have no access to the library via the browser as US users have, you can just access it via those 2 apps and if you use just a Mac you’re completely out of luck. There is no screenshoot of the library, just the error you get when trying to access it, when you «add to the library» the button transform into «listen to this book» BUT if you want to look to all books you added to the library via browser you CANNOT, you can only on the windows or android app. You have no way to remove, for instance, a book from your library with the browser. As funny as it sounds… Thank you.

**Comment by openaudible** [comment]
Thanks for the explanation. Just let us know if you're able to view your library from a web browser. Closing until then.
