### ISSUE TITLE
Open Audible and Catalina

### ISSUE THREAD

**Issue by Miguel3451** [openaudible/openaudible#223]
I recently tried to install version 1.5.5 on my Mac which I recently upgraded (?) to Catalina.  When try to run the newly installed copy I get an error message “OpenAudible.app” can’t be opened because Apple cannot check it for malicious software.  The previous version worked perfectly.

I would appreciate any help.

**Comment by openaudible** [comment]
Try to "right-click" on the app or dmg and select open. You may need to change your gatekeeper settings.

**Comment by Miguel3451** [comment]
Thanks for your help.  I did use the right-click method during installation but ...  I was desperately hoping to avoid having to get into the guts of (shudder) Gatekeeper.
