### ISSUE TITLE
MP3 playback is very bad.

### ISSUE THREAD

**Issue by Viz525** [openaudible/openaudible#224]
The MP3s that have been converted from AAX files do not play back properly. They keep jumping backward repeating sections.

**Comment by openaudible** [comment]
What operating system? I've never had a similar report, so assume it is unique to you. Maybe your mp3 player is not working well.

**Comment by Viz525** [comment]
Please disregard my post… I converted the AAX files agains and they play perfectly. (MacOS Mojave 10.14.6)
__________________________

**Comment by ikershaw** [comment]
I also had this issue, but as @openaudible suggests, I think it's the mp3 player. In this instance, I 
had the problem with the preview option in Finder on Mac. When loading into iTunes, it plays fine.
