### ISSUE TITLE
Enhancement: Chapter marks in MP3

### ISSUE THREAD

**Issue by damajor** [openaudible/openaudible#225]
Having chapter in distinct files is a nice feature. But MP3 and many other audio formats or containers (OGG/MP4) also support chapter marks.

Supporting this out of the box when building the single MP3 can be very interesting.
Also providing this feature by manual action (like splitting chapter) can let old users to convert their MP3 files without marks to new ones.

Tip: this is supported by ffmpeg.

**Comment by openaudible** [comment]
Chapter data is already embedded in the single file mp3... Just call ffprobe on any of the mp3 files to see it. Most players just ignore it. What are you hoping to have users see (using what app?)

We log the ffmpeg command used to create the mp3.. You can copy and paste it into a shell and reproduce what we do.. and if you wanted to make a change to our command, just describe the changes with examples.

**Comment by damajor** [comment]
Just noticed that. Please forget this request.
