### ISSUE TITLE
What player to use for playback that has chapter support?

### ISSUE THREAD

**Issue by mtaki14** [openaudible/openaudible#226]
I have trouble finding a player on both windows and android that has mp3 chapter support. I would rather only split the mp3 file into parts as a last resort.

What player do people generally use for this purpose? Or do they not make use of chapters at all for unsplit files?

**Comment by mtaki14** [comment]
I only found out about chapter support because of this comment:

https://github.com/openaudible/openaudible/issues/43#issuecomment-431147778

Now the question is, how to take advantage of it?

**Comment by openaudible** [comment]
I don't know any android or windows apps that support chapters. I haven't looked. I like [BookPlayer](https://github.com/TortugaPower/BookPlayer) for iOS, but it doesn't support chapters (AFAIK).

But I personally find chapters pointless for navigation purposes.  Who needs to go to a random chapter? Most people listen from start to finish. 

With the Audible player, I've frequently hit the "next chapter" button and ended up lost about where I was previously and had to hunt around. Annoying and poorly designed for an app people frequently have running while in their pockets. 

Anyway, I'll leave this open for a week in case someone wants to chime in.

**Comment by mtaki14** [comment]
I ended up using inAudible and converting the audiobooks to *.m4b instead which can hold chapter information as well but seems to be more standard and supported by a few of the players I already use. (Win: VLC, Android: Podcast Addict & Smart Audiobook Player).

"But I personally find chapters pointless for navigation purposes. Who needs to go to a random chapter? Most people listen from start to finish."

I beg to different, even though yes mostly I listen to audiobooks from start to finish there are still times I want to quickly jump to a certain chapter for a refresher about something that was referenced later down the line or referenced somewhere else. This happens very rarely but it is still is nice to know that the possibility exists when the need arises.

**Comment by LF2005** [comment]
Are you guys joking, there is a bunch of players with chapter support in windows
1st MPC and second VLC. but I'm pretty sure that mp3 does not support chapters, I think I saw that function only in mkv and maybe mp4.

**Comment by DDQW** [comment]
https://id3.org/id3v2-chapters-1.0
id3 absolutly supports chapters. so pretty much every audiofile can be chaptered

problem: very few player implement it. which is sad cause it would be great for carstereo or digitalradios with mp3

butnthe current sitiation is that you have to use your smartphobe all the time

**Comment by neingeist** [comment]
> but I'm pretty sure that mp3 does not support chapters

MP3/ID3v2 has chapters (CTOC/CHAP frames), and they work fine in mpv and audiobookshelf. Sadly not in VLC at the moment.
