### ISSUE TITLE
downloads

### ISSUE THREAD

**Issue by ironpepsi** [openaudible/openaudible#227]
since upgrading to 1.6 it no longer completes any downloads

**Comment by openaudible** [comment]
From the bug reports from you I saw, I think the file downloaded but couldn't be converted. It didn't look like a regular book file, but some kind of podcast episiode.. which are not supported by ffmpeg. 

However, you also had a problem submitting bugs. So it could be a download problem too.

Delete all files in the C:\Users\xxx\OpenAudible\tmp\ directory and retry with a very simple: start, connect, download. Look at the console and see if you can get a human readable error message. Also, you should be able to click the "download" button on the library page from the OA browser.

**Comment by openaudible** [comment]
Also, fixed our bug reporter in 1.6.1. Feel free to re-open or submit a new bug report referencing #227
