### ISSUE TITLE
Can't import files

### ISSUE THREAD

**Issue by OmegaRea** [openaudible/openaudible#230]
I am attempting to import my Audible file into my Library.  I select Controls -> Refresh Files and select "Yes".  It states that it is importing the files, but when it complete, they are not showing up as important.  If I repeat the process, it shows that the files need to be imported.  Am I doing something wrong? Thank you for any help.
![import](https://user-images.githubusercontent.com/56102453/69302528-909c5b00-0bdf-11ea-95f9-223f8c31da8e.jpg)

**Comment by openaudible** [comment]
Hi,
You would have to read the log about why those files aren't getting imported. It should say.. Usually something like "partial books" or the book is already in your library. 

We don't use that file name strategy, so it looks like those were downloaded another way.. So 

I would recommend removing those books from the OA aax folder and try importing them one at a time until you get the sense that it is working the way you expect. You can also re-download them using OA.

**Comment by OmegaRea** [comment]
Thank you.  I will do that.
