### ISSUE TITLE
This audio format is not supported for the title

### ISSUE THREAD

**Issue by OmegaRea** [openaudible/openaudible#232]
I received this error when trying to download one of my books. Through the audible app for Windows 10 it shows only available in parts.  this is the info the console reports.

Nov 23, 2019 12:18:53 PM org.openaudible.download.DownloadJob download
INFO: Download failed:I:\Downloads\aax\Mark Twain. The Complete Novels.1.AAX Mark Twain. The Complete Novels
Nov 23, 2019 12:18:53 PM org.openaudible.util.queues.ThreadedQueue jobError
INFO: DownloadQueue error processing Download Mark Twain. The Complete Novels
java.io.IOException: Download error: This audio format is not supported for the title. Please download in another audio format. for Mark Twain. The Complete Novels
	at org.openaudible.download.DownloadJob.handleError(DownloadJob.java:102)
	at org.openaudible.download.DownloadJob.download(DownloadJob.java:215)
	at org.openaudible.download.DownloadJob.downloadNew(DownloadJob.java:314)
	at org.openaudible.download.DownloadJob.processJob(DownloadJob.java:321)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:422)

**Comment by openaudible** [comment]
I haven't seen that error before. Can you go to the book in Audible using the OA browser? Then click on the download link.. Sometimes book details change and the download link fails to work.

**Comment by OmegaRea** [comment]
This is the image that shows up in the browser.  Following is an image of what shows in the Audible for Windows App.  The file seems to have been divided into 8 files.

![MarkTwainError](https://user-images.githubusercontent.com/56102453/69502701-c723ef80-0ed7-11ea-88ba-7aa1a29ff031.jpg)

![MarkTwainError2](https://user-images.githubusercontent.com/56102453/69502705-de62dd00-0ed7-11ea-9dd9-96034d931bbe.jpg)

**Comment by openaudible** [comment]
Once audible changes or discontinues a book.. the one you purchased may not be available for download.
