### ISSUE TITLE
[Request] Support for creating M4B files (single file w. chapter markers)

### ISSUE THREAD

**Issue by Optilasgar** [openaudible/openaudible#233]
First off let me thank you for making and maintaining this app in the first place.  
Being able to play all my audio content in 1 app instead of multiples is great.  

However, having to choose between having 1 single file that makes it hard to go (back) to specific chapters or end up with a whole folder full of sometimes dozens upon dozens of individual files that make folder navigation slow and cumbersome is not exactly ideal.  

Single *.m4b files with chapter markers in them would hit 2 birds with 1 stone, and since you seem to use ffmpeg as your backend, and it being able to create these, i would be eternally grateful if you could implement this as an option.  

i found some scripts / guides on how to do this, but they don't involve GUI solutions.  

Resources i've found:  
https://superuser.com/questions/1283118/how-to-convert-audible-aax-file-to-m4b-format-while-preserving-all-information  

https://github.com/KrumpetPirate/AAXtoMP3

**Comment by openaudible** [comment]
Addressed in other feature request issues. MP3s contain chapter info. M4B's have drawbacks.

**Comment by yin** [comment]
@openaudible Can you provide at least one example of a drawback? Thanks

**Comment by danielb2** [comment]
I'm curious of the drawback too. What's the primary motivator for not providing the option for export to m4b ?

**Comment by danielb2** [comment]
And where are the mp3s storing chapter info ?

**Comment by danielb2** [comment]
I use Smart Audiobook for Android, and it does not use mp3 chapter info. I suspect many audio players don't so m4b still seems like a reasonable request

**Comment by yin** [comment]
@danielb2 the maintainer(s) are clear on this. If there is a way to push this through, we'll have to make our own pull request. Even then, I'm not sure if they are having the will to maintain it.

**Comment by danielb2** [comment]
@yin  I solved my use-case with this post: https://github.com/openaudible/openaudible/issues/273#issuecomment-588506885

But it would be nice if openaudible could do this.  A lot of apps allow for custom output files etc too

**Comment by yin** [comment]
Well, I had a quick look into the source. Adding the new UI would be a lot more work than looking up the activation code. Would that suffice?

**Comment by danielb2** [comment]
I'm sorry, would what suffice ?
 
I'm guessing openaudible is using rainbowcrack and the checksum of the aax file internally.
