### ISSUE TITLE
i am getting this as an error

### ISSUE THREAD

**Issue by MALI143225** [openaudible/openaudible#234]
AAXtoMP3: line 332: 10897 Segmentation fault      ffmpeg -loglevel error -activation_bytes "${auth_code}" -i "${aax_file}" -an -codec:v copy "${cover_file}" < /dev/null

Help me resolve this issue please

**Comment by openaudible** [comment]
That log message isn't from OpenAudible. AAXtoMP3 is another application. Your ffmpeg isn't working.
