### ISSUE TITLE
mp3 chapter split

### ISSUE THREAD

**Issue by Asok76** [openaudible/openaudible#236]
New to Openaudible and it is great.  but I am having an issue.
Using 1.6.2
I have downloaded my books and converted them to mp3.  I would like to use the "split  by Chapter" option but when I use it I just get an error.   There is no error information just an empty error window that says error.

Dec 04, 2019 4:11:49 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: MESSAGE_BOX_TITLE_ERROR
Error

I am guessing it is because there is no chapter information.  I found the ffprobe.exe and used it to -show_chapters and I didn't see any.  I checked the .aax file for the same book and ffprobe showed the chapter information.  So it appears to me the chapter information was not retained when the .mp3 was created.  I should note that I have never used ffmpeg or ffprobe before, I'm just googling and trying things.

Any help would be appreciated.

**Comment by openaudible** [comment]
Copy and paste more from the console from where it says Command: Split by chapter 

There should be a "stack trace" that shows what caused the error. If there are no chapters, I had the choice to make a simple alert (No chapter data available) or totally ignore the error and print something to the console. An empty message error isn't what I had intended. So there seems to be a bug there somewhere.

**Comment by Asok76** [comment]
Here is everything in the console.  I'm afraid it isn't going to be much more help.

Dec 06, 2019 12:36:13 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Split_By_Chapter
Dec 06, 2019 12:36:26 PM org.openaudible.desktop.swt.manager.SplitJoinGUI _splitBook
INFO: Split source:D:\Audio Books\mp3\The Richest Man in Babylon.mp3
Dec 06, 2019 12:36:29 PM org.openaudible.desktop.swt.manager.SplitJoinGUI _splitBook
INFO: Split directory:D:\Audio Books\mp3\The Richest Man in Babylon.mp3
Dec 06, 2019 12:36:29 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: "C:\Program Files\OpenAudible\bin\win\ffprobe.exe" -hide_banner "D:\Audio Books\mp3\The Richest Man in Babylon.mp3" -show_streams -show_chapters -print_format json 
Dec 06, 2019 12:36:29 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: MESSAGE_BOX_TITLE_ERROR
Error
Dec 06, 2019 12:36:34 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

 So there seems to be 2 issues.  1 Why is there an error when there are no chapters instead of the intended message.  And 2,  why are there no chapters in my mp3s?    The second question is more important to me, but I understand the need to fix the first one.  Thanks for looking into this.  I'll try to be as much help as I can, which may not be much.

when I run the ffprobe command on the .mp3 the chapters just shows : 

 "chapters": [

    ]



If I run the same command on the .aax it shows:

 "chapters": [
        {
            "id": 0,
            "time_base": "1/4000000",
            "start": 0,
            "start_time": "0.000000",
            "end": 17160000,
            "end_time": "4.290000"
        },
        {
            "id": 1,
            "time_base": "1/4000000",
            "start": 17160000,
            "start_time": "4.290000",
            "end": 535029000,
            "end_time": "133.757250"
        }
     ,...... And so on for all the chapters     
    ]

**Comment by Asok76** [comment]
Well, good news I have solved problem #2.  It was the copy of ffmpeg.  I downloaded the latest version from 12/4 and it works.   Tried the prev version from 11/26 and no chapters.  So getting the latest ffmpeg has solved the missing chapters problem.  Which in turn means I no longer get an error which is problem #1.    If you still want to look into the blank errror, I would be glad to help, but I consider this problem solved.

**Comment by openaudible** [comment]
I fixed the blank error message when there are no chapters found. Thanks for finding that.  Will be in next release. I will also update to the latest ffmpeg to 4.2.1, which I get from: https://ffbinaries.com/downloads

Hopefully that will do it.. although there is another ffmpeg chapter splitting bug #237 I'd like to address before the next version.

**Comment by Asok76** [comment]
Great, glad you got the error fixed.  Unfortunately, it seems as I might have encountered a similar problem to #237   It seems the chapters don't quite split where they are supposed to. It continually gets more and more off the further chapters you go.  Chapter 2 starts a few seconds into the file for chapter 2.  by the time you get to a chapter 13 it is off by minutes.   I'll have to do some more investigating.  It appears that the timestamp, while using a different time_base are the same between the aax and the mp3.  But it seems that the mp3 is longer than the aax.  I'll do some more investigating when I have time.  Perhaps there is indeed some additional setting for ffmpeg that needs to be turned used.... it appears there are a lot of them.

**Comment by openaudible** [comment]
It does look like a number of people have reported "padding" bugs in ffmpeg. If you find anything useful, please post it to #237.  Closing this.
