### ISSUE TITLE
Chapter splitting / chapter metadata

### ISSUE THREAD

**Issue by brettw1234** [openaudible/openaudible#237]
This problem has been stumping me for awhile now, but I think I discovered something slightly interesting about chapter splitting and chapter metadata. Let me try to explain with an example -

This is what ffmpeg tells me about the original file:

    Duration: 14:07:48.82, start: 0.050111, bitrate: 57 kb/s
    Chapter #0:0: start 0.000000, end 1569.344000
    Metadata:
      title           : Chapter 1

    Chapter #0:1: start 1569.344000, end 2415.386000
    Metadata:
      title           : Chapter 2
    
    ... remaining chapters ...

But the ffmetadata that is actually encoded into the id3 tags shows this:

```
[CHAPTER]
TIMEBASE=1/1000
START=0
END=1569294
title=Chapter 1

[CHAPTER]
TIMEBASE=1/1000
START=1569294
END=2415336
title=Chapter 2

... remaining chapters ...
```

Notice there is a 50ms difference in the end of Chapter 1 between the metadata file and ffmpeg (due to some delay added to the beginning of the file, see No. 2 [here](https://lame.sourceforge.io/tech-FAQ.txt)). You can see this represented by the `start: 0.050111` in the first snippet.

Because of this, the metadata of the resulting chapter files is thrown off.
This is what the metadata looks like in each file after the split:

Chapter 1.mp3

    Chapter #0:0: start 0.000000, end 1569.294000
    Metadata:
      title           : Chapter 1
    Chapter #0:1: start 1569.294000, end 1569.344000
    Metadata:
      title           : Chapter 2

Chapter 2.mp3

    Chapter #0:0: start 0.000000, end 845.992000
    Metadata:
      title           : Chapter 2
    Chapter #0:1: start 845.992000, end 846.042000
    Metadata:
      title           : Chapter 3

You can see the 50ms return here - the metadata thinks there is 50ms of Chapter 2 in the first file even though there isn't.

**Comment by openaudible** [comment]
Thanks for digging.

It seems like you're suggesting this is an ffmpeg issue.. If so, not much I can do. Unless there is a way to encode the mp3 differently without padding. (Is there a NO PAD ffmpeg encode option?) It seems if padding is added, the chapter meta data that gets copied should be adjusted by ffmpeg. 

If you really want a solution, I'll need concrete changes that I can make to the ffmpeg/ffprobe commands I use to encode and split. 

All of those commands I write to the console. 

To reproduce and test: 
Delete an MP3 file that shows the problem. 
Controls: Refresh Files (or restart the app, to get a fresh console.)
Encode the file to MP3.
Split by chapters.

Now copy the console text to a text editor and start looking at the data. You'll see how we encode aax to mp3 using ffmpeg. Then we use ffprobe on the mp3 and output as JSON. From there we extract the start and stop times that you probably see. 

Then see if you can make recommendations on how to split more accurately.

**Comment by brettw1234** [comment]
After some more investigation, I _think_ the actual audio data is correct in the split files. I grabbed a couple of chapters and checked their total lengths and it seems to be pretty dang close - 

Chapter 1:
- Length in original file: **1569.344 s** 
- Split out file length: 00:26:09.36 -> **1569.36 s**
- Diff = **.016 s**

Chapter 20:
- Length in original file: **878.597 s**
- Split out file length: 00:14:38.60 -> **878.60 s** 
- Diff = **.003s**

Chapter 38:
- Length in original file: **1134.759 s**
- Split out file length: 00:18:54.76 -> **1,134.76s**
- Diff = **.001s**

Since the two measurements are using different levels of precision it isn't quite a 1:1 comparison, still extremely close nonetheless. The problem seems to lie entirely in the metadata - not sure how to fix that other than overwriting it for each file.

**Comment by openaudible** [comment]
My test books have the narrator say "Chapter XX" at the start of every chapter. I haven't found any books don't split correctly. Do you have examples of books where the chapter data is off by more than a full second? Or is this bug just about being off by 50ms?

**Comment by brettw1234** [comment]
So that is what I meant by the audio data being correct. When you listen to the actual audio files, I am pretty sure they are being cut in the proper spot. It is just the metadata of the split files that is incorrect, which is a much smaller deal, but still a small bug nonetheless.

I am not sure there is much you can do about this problem unless you were to go back through the split files and update the metadata of each individually.

**Comment by openaudible** [comment]
OK.. Interesting but changing to Won't fix.
