### ISSUE TITLE
Trouble When Exporting to Webpage

### ISSUE THREAD

**Issue by deanrmercer** [openaudible/openaudible#238]
When exporting to Web Page I get the message Error building web page ...java.lang.NullPointerException

**Comment by deanrmercer** [comment]
Sorry I should say this is version 1.6.2

**Comment by openaudible** [comment]
Can you open the Console (under File menu) and copy and paste more of the error? Hopefully you get a full stack trace.

**Comment by deanrmercer** [comment]
Dec 06, 2019 3:17:29 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 1.6.2 for win32 swt 4623 jvm 1.8.0_202
Dec 06, 2019 3:17:29 PM org.openaudible.Directories isValid
SEVERE: Not found:D:\OpenAudibleweb
Dec 06, 2019 3:17:29 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 1.6.2
Dec 06, 2019 3:17:29 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1575078708020
Dec 06, 2019 3:17:30 PM org.openaudible.Audible load
INFO: Loading D:\OpenAudible\books.json
Dec 06, 2019 3:17:30 PM org.openaudible.Audible normalizeBook
INFO: change filename: Imperial Grunts On the Ground with the American Military, from Mongolia to the Philippines to Iraq and Beyond. to Imperial Grunts On the Ground with the American Military, from Mongolia to the Philippines to Iraq and Beyond
Dec 06, 2019 3:17:30 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1575078708020
Dec 06, 2019 3:17:30 PM org.openaudible.Audible checkLibrary
INFO: loaded 508 books.
Dec 06, 2019 3:17:30 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: "C:\Program Files\OpenAudible\bin\win\ffmpeg.exe" -version 
Dec 06, 2019 3:17:30 PM org.openaudible.desktop.swt.manager.AudibleGUI checkFFMPEG
INFO: using ffmpeg version N-76456-g6df2c94 Copyright (c) 2000-2015 the FFmpeg developer
Dec 06, 2019 3:17:30 PM org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFO: applicationStarted took 801 ms. to complete.
Dec 06, 2019 3:17:39 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Export_Web_Page
Dec 06, 2019 3:17:40 PM org.openaudible.desktop.swt.manager.ImportExport run
SEVERE: error
java.lang.NullPointerException
	at org.openaudible.feeds.pagebuilder.WebPage.createThumbnail(WebPage.java:231)
	at org.openaudible.feeds.pagebuilder.WebPage.buildPage(WebPage.java:186)
	at org.openaudible.desktop.swt.manager.ImportExport$PageBuilderTask.run(ImportExport.java:774)

Dec 06, 2019 3:17:40 PM org.openaudible.desktop.swt.manager.AudibleGUI showError
SEVERE: building web page
java.lang.NullPointerException
	at org.openaudible.feeds.pagebuilder.WebPage.createThumbnail(WebPage.java:231)
	at org.openaudible.feeds.pagebuilder.WebPage.buildPage(WebPage.java:186)
	at org.openaudible.desktop.swt.manager.ImportExport$PageBuilderTask.run(ImportExport.java:774)

Dec 06, 2019 3:17:40 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: MESSAGE_BOX_TITLE_ERROR
Error
Dec 06, 2019 3:17:40 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Dec 06, 2019 3:17:43 PM org.openaudible.desktop.swt.manager.ImportExport exportWebPage
INFO: Book html file is: D:\OpenAudible\web\index.html url=file:/D:/OpenAudible/web/index.html
Dec 06, 2019 3:17:44 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=0 total=0}
Dec 06, 2019 3:17:45 PM org.openaudible.desktop.swt.manager.browser.AudibleBrowser setUrl
INFO: AudibleBrowser setURL: about:blank
Dec 06, 2019 3:17:45 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=0 total=0}
Dec 06, 2019 3:17:49 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by openaudible** [comment]
Thanks. It failed to create a thumbnail image from one of the cover art files. I don't know why.. but maybe there is a corrupt image somewhere. I'll fix it so it doesn't happen in the next release.

**Comment by openaudible** [comment]
Fixed. But feel free to submit any new error messages that come up.. one or more of your images may not be available as a thumbnail.
