### ISSUE TITLE
Large audiobook -coversion stops 

### ISSUE THREAD

**Issue by GreentheGroovy1** [openaudible/openaudible#239]
![Screenshot 2019-12-11 at 12 10 30 PM](https://user-images.githubusercontent.com/57015428/70648066-eaf17000-1c0f-11ea-8c5f-d535cd3d2f9b.png)
[log.txt](https://github.com/openaudible/openaudible/files/3951924/log.txt)

Stops around the 46 hour mark every time . OpenAudible then freezes up. Tried also to download directly from the Audible website then manually importing the aax file and converting it. Same thing happens. if there is anything else i can do to help the troubleshooting process , please let me know

**Comment by openaudible** [comment]
Strange. Run the ffmpeg command from the command line and see if it finishes by itself. The command is in the second to last log message above. It starts with:
/opt/OpenAudible/bin/linux/ffmpeg
and ends with 001745_temp.mp3

Might be an ffmpeg problem.. you could try grabbing a newer ffmpeg from "https://ffbinaries.com/downloads"

**Comment by GreentheGroovy1** [comment]
Follow up . That did work . it complete the conversion . The next book in the series, Oathbringer, is 55 hrs long . it is also having issues - (see attachement) i am running it via cli notice 2 things 

1. i'm seeing this message in CLI 

[swscaler @ 0x46a08e0] deprecated pixel format used, make sure you did set range correctly
[mp3 @ 0x4685a80] Frame rate very high for a muxer not efficiently supporting it.
Please consider specifying a lower framerate, a different muxer or -vsync 2

2. around 48hrs into the mp3 conversion, it slows to a crawl. it takes 5-10 seconds to convert 1 second of the file. it seems to only be getting slower as it goes on . it takes 10-12 minutes to get to the 48hr mark.

please note that i am using a Intel Core i5-8250U with 8gb memory and 128 gb of storage .. a lenovo C630 Chromebook - with Debian Buster

**Comment by GreentheGroovy1** [comment]
Screen shots 
![Screenshot 2019-12-12 at 5 38 59 PM](https://user-images.githubusercontent.com/57015428/70757779-79e0b400-1d06-11ea-8d84-4762b0e3f41d.png)
![Screenshot 2019-12-12 at 2 35 45 PM](https://user-images.githubusercontent.com/57015428/70757780-79e0b400-1d06-11ea-9460-472e696389d9.png)

**Comment by GreentheGroovy1** [comment]
![Screenshot 2019-12-12 at 5 47 45 PM](https://user-images.githubusercontent.com/57015428/70758548-042a1780-1d09-11ea-9940-44431221a723.png)

**Comment by openaudible** [comment]
So it is also slow running from the command line? (or just when running from OA?)
If slow on command line, try a new version of ffmpeg. Or check their support pages to see if anyone else is seeing that.

**Comment by GreentheGroovy1** [comment]
updating ffmpeg to the latest version did not fix the issue . Same thing happen in the app or in CLI the conversion on both books, weather downloaded in app or from the website then imported . i have  found a workaround . ffmpeg does finish the conversion . How can i contact you to share it with you ?

**Comment by openaudible** [comment]
Have you tested the speed on your linux machine vs a PC or Mac? I haven't had any other linux users complain and plenty of people have really big books. 

I am not sure I can do much with problems in ffmpeg that don't happen to any other users. 

But if you have a solution, I'll take a look: openaudible at email.tg .

**Comment by openaudible** [comment]
A user PM'd me that they have the same book and it converted correctly:

`
INFO: Converted your Words of Radiance: The Stormligh to mp3: mp3/Words of Radiance.mp3 size=1836835088 in 1808 seconds.
`
