### ISSUE TITLE
Syncing, but no books are showing up

### ISSUE THREAD

**Issue by nikhilmaddirala** [openaudible/openaudible#24]
![2018-07-27 13_16_59-new issue openaudible_openaudible](https://user-images.githubusercontent.com/4138581/43336586-6b18a912-919f-11e8-828f-0be0e9de91e9.png)

**Comment by nikhilmaddirala** [comment]
Other notes:

1. Version 1.1.4
2. Connected to Audible (verified in browser)

**Comment by patanne** [comment]
console output where everything goes sideways is as below. the clientContext and marketPlaceId have been set to all X's:

Jul 30, 2018 4:27:59 PM org.openaudible.Audible updateLibrary
INFO: Updated 0 books
Jul 30, 2018 4:28:15 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Execute: Rescan_Library
Jul 30, 2018 4:28:15 PM org.openaudible.audible.AudibleScraper setURL
INFO: setURL:/access
Jul 30, 2018 4:28:16 PM org.openaudible.audible.AudibleScraper setPage
INFO: pageLoaded:https://www.audible.com/account/access Download Audiobooks with Audible.com
Jul 30, 2018 4:28:16 PM org.openaudible.audible.AudibleScraper setURL
INFO: setURL:/lib
Jul 30, 2018 4:28:16 PM org.openaudible.audible.AudibleScraper setPage
INFO: pageLoaded:https://www.amazon.com/ap/signin?clientContext=XXX-XXXXXXX-XXXXXXX&openid.pape.max_auth_age=0&openid.return_to=https%3A%2F%2Fwww.audible.com%2Flib&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_audible_us&openid.mode=checkid_setup&marketPlaceId=XXXXXXXXXXXX&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_audible_bc_us&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0& Amazon Sign In
Jul 30, 2018 4:28:16 PM org.openaudible.audible.AudibleScraper setPageFilter
SEVERE: Unable to set purchaseDateFilter.
com.gargoylesoftware.htmlunit.ElementNotFoundException: elementName=[*] attributeName=[name] attributeValue=[purchaseDateFilter]
	at com.gargoylesoftware.htmlunit.html.HtmlPage.getElementByName(HtmlPage.java:1572)
	at org.openaudible.audible.AudibleScraper.setPageFilter(AudibleScraper.java:547)
	at org.openaudible.audible.AudibleScraper._fetchLibrary(AudibleScraper.java:477)
	at org.openaudible.audible.AudibleScraper.fetchLibrary(AudibleScraper.java:584)
	at org.openaudible.Audible.updateLibrary(Audible.java:336)
	at org.openaudible.desktop.swt.manager.AudibleGUI$3.run(AudibleGUI.java:328)

**Comment by drixstopa** [comment]
I am also experiencing this issue connecting to audible.co.uk

**Comment by drixstopa** [comment]
@patanne the error you  describe may be related to https://github.com/openaudible/openaudible/issues/17
I was getting that error message in the console and logging in again resolved it.

**Comment by drixstopa** [comment]
@nikhilmaddirala I stepped through the code in the debugger as I am seeing the same dialog i.e 'Go buy more books' when I have 600+ books in my library. I can see that the application skips multipart books completely. In

org/openaudible/audible/AudibleScraper.java lines 529/530

```            for (Book b : list) {
                // LOG.info(b.toString());
                if (b.partial())
                    continue;
                if (results.contains(b)) {
                    LOG.error("duplicate book:" + b);
                    assert (false);
                }
```
If the book (b) is a partial then it is skipped. All my books appear to be multipart books and so nothing is added to the library. 

Of course you may not have the same problem as me.

**Comment by drixstopa** [comment]
Hacking partial to return false for multipart books results in my library being loaded (976 books - higher count due to multipart).
Clearly this is not a solution, however we need to understand why multipart books are explicitly excluded by @openaudible

**Comment by drixstopa** [comment]
@openaudible 
I think the problem stems from the way ```partial()``` assumes multipart books are named
```
    // isPartialBook. A part of a single book. Not to be confused with one of a series.
    public boolean partial() {
        String pid = getProduct_id();
        if (pid.isEmpty()) throw new IllegalStateException("Undefined");
        char last = pid.charAt(pid.length() - 1);
        // last character is lowercase letter..
        return !Character.isDigit(last);
    }
```

On the audible.co.uk library page books are listed for download as a single file or multipart e.g. 
```
product_id=BK_POTR_000010UK
Harry Potter and the Prisoner of Azkaban, Book 3

product_id=BK_POTR_000010aUK
Harry Potter and the Prisoner of Azkaban, Book 3 Part 1

product_id=BK_POTR_000010bUK
Harry Potter and the Prisoner of Azkaban, Book 3 Part 2
```
However, ```partial()``` assumes that a download with a non-numeric last character is a partial. As can be seen above all three downloads have a non-numeric last character. Hence in my case no books are found in my library.

Note that all table rows (```<tr>```) for a particular book appear to have the same id attribute value e.g. in the case above ```id="adbl-library-content-row-B017WGLLXO"``` which may be helpful when filtering partials.

**Comment by drixstopa** [comment]
Checking the third from last character worked for me. I was able to download my library excluding partials.
```
        char last = pid.charAt(pid.length() - 3);
```

**Comment by openaudible** [comment]
Thank you for the report. I pushed a change to master that should fix your issue.. basically testing to see if the product_id has any lowercase letters. Will get into the next release. Feel free to pull and test.
