### ISSUE TITLE
No library

### ISSUE THREAD

**Issue by protoniogg** [openaudible/openaudible#242]
When I sign in in the browser window and try quick/full library sync appears "page not found" (and I can't find a link to the  library in the browser) and it doesn't find the audiobooks. I am using 1.6.2 version on arch linux ( same result on windows 10).

**Comment by openaudible** [comment]
What region are you in? Some regions don't have a "library" view.. specifically Italy. You should be able to go to https://audible.com/lib and see your books. (but use the regional URL instead of audible.com)

**Comment by protoniogg** [comment]
Ok, that is the problem; I am in Italy so I think I can't use openaudible. Thanks for your reply

**Comment by rubbo898** [comment]
Same problem here, so there's no way to use Openaudible with italian Audible subscriptions?

**Comment by openaudible** [comment]
Search for the word Italy in the issues. You can ask Audible support if there is a way to view your books in a web browser. You can also find out how to download aax book files.. and import them by dragging and dropping them into OpenAudible. I have never seen an Italy login so don't really understand why there is no library view.

**Comment by protoniogg** [comment]
> Search for the word Italy in the issues. You can ask Audible support if there is a way to view your books in a web browser. You can also find out how to download aax book files.. and import them by dragging and dropping them into OpenAudible. I have never seen an Italy login so don't really understand why there is no library view.

I am doing exactly this, downloading aax and importing in openaudible
