### ISSUE TITLE
Receiving error while importing AAX book contains invalid date

### ISSUE THREAD

**Issue by xircon-eng** [openaudible/openaudible#243]
INFO: Running: "C:\Program Files\OpenAudible\bin\win\ffmpeg.exe" -i C:\Books\B00A81MRF2_ep5.aax -f ffmetadata - 
Dec 15, 2019 11:16:41 AM org.openaudible.Audible expired
WARNING: book contains invalid date: The Vampire Archives Part 1: The date=2200-01-01 product_id=BK_RAND_002534a,asin=B00A81MRF2,title=The Vampire Archives Part 1: The Most Complete Volume of Vampire Tales Ever Published,author=Otto Penzler (editor), Kim Newman (foreword), Neil Gaiman (preface), Clive Barker, Robert Bloch, Stephen King,narrated_by=Scott Brick, Jonathan Cowley, Erik Davies,summary=The Vampire Archives is the biggest, hungriest, undeadliest collection of vampire stories, as well as the most comprehensive bibliography of vampire fiction ever assembled. Dark, stormy, and delicious, once it sinks its teeth into you there’s no escape.,description=The Vampire Archives is the biggest, hungriest, undeadliest collection of vampire stories....,duration=07:56:07,release_date=01-JAN-2200,publisher=Random House Audio,title_short=The Vampire Archives Part 1: The Most Complete Volume of Vampire Tales Ever Published,copyright=©2009 Otto Penzler (P)2011 Random House,filename=B00A81MRF2_ep5,
Dec 15, 2019 11:16:41 AM org.openaudible.desktop.swt.manager.ImportExport _importFile
WARNING: Unable to import book:C:\Books\B00A81MRF2_ep5.aax : Book too new for version The Vampire Archives Part 1: The
Dec 15, 2019 11:16:46 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Import_Books

**Comment by openaudible** [comment]
Release date was set tojan-2200 which we assume is invalid. Or maybe you've downloaded the book in parts (ep 5)? Maybe try refreshing that book.  It looks like the correct date is  correct (2-15-11) on https://www.audible.com/pd/The-Vampire-Archives-Audiobook/B004MU7Z8E

**Comment by lxtwin** [comment]
Although this is closed a work around is to edit the AAX file with something such as ghex.
You can locate the 2200 string ( it appears twice) and replace it with 2020 (other values may work)
save the file and it does then import.
