### ISSUE TITLE
Copy stream instead of converting

### ISSUE THREAD

**Issue by Tooker** [openaudible/openaudible#244]
Hello,

i was looking into your tool. The basic featureset looks very promising but, I don't want to convert every of my audible books. Is it possible to just copy the stream into an m4a file. I know that ffmpeg supports the copy function with ffmpeg -activation-bytes deadbeaf -I input.aax c:a copy  output.m4a . I would change the sources by my self but, the git version is older than the last release. Maybe add a copy button into the gui or make it configurable via the settings.json or add the newest source code to the git.

**Comment by openaudible** [comment]
At some point I hope to. As addressed in other issues, converting to m4b breaks if the book is too big.. and I prefer one book, one file. Maybe in a future version.

**Comment by Tooker** [comment]
I’m not talking about converting to m4b. When you use the c:a copy the stream will be copied. There is no processing. A 600 mb aax file will be an 600m4a file. 

Why is the source code not updated?

**Comment by openaudible** [comment]
M4A support has been added to 2.0.6 and newer.
