### ISSUE TITLE
Convert to MP3 Grayed Out

### ISSUE THREAD

**Issue by don26812** [openaudible/openaudible#246]
I downloaded OpenAudible and donated $10. But the Convert to MP3 button is grayed out. How do I fix this?

**Comment by joke2k** [comment]
Latest version broke it

**Comment by openaudible** [comment]
Sorry. Broke that when I took out the initial startup check to see if ffmpeg is installed and working.. pushing new release now.

**Comment by openaudible** [comment]
OK. Should be fixed. Thanks for the donation @don26812 !

**Comment by don26812** [comment]
Can I download a previous version? How could a new version be released with something that is so fundamental be broken? Hopefully the developers are hard at work fixing the bug. 

 

Take Care,

Don

**Comment by don26812** [comment]
Great!

 

Take Care,

Don

**Comment by don26812** [comment]
Thank you so much! That fixed it.

 

Take Care,

Don
