### ISSUE TITLE
Convert Greyed Out / Red Dot Next to Book 

### ISSUE THREAD

**Issue by secretovida** [openaudible/openaudible#247]
Was working great and now I import a book from Audible via connect there is a red dot next to the book. 
![image](https://user-images.githubusercontent.com/59149582/71327587-55ed5180-2502-11ea-9275-5246d9c186f7.png)

**Comment by TimoT75** [comment]
Hi, same for me on Mac. New version 1.6.4 installed (after 1.5.x).
Most of the imports show a red dot next to the book.
Import works normal. State shows "No MP3 or AAX or download" but
everything else is filled.
<img width="791" alt="Bildschirmfoto 2019-12-23 um 18 11 51" src="https://user-images.githubusercontent.com/59177039/71370921-c0a89680-25af-11ea-96c9-c27e134d918b.png">

**Comment by openaudible** [comment]
No download link means it can't be downloaded by OpenAudible. Try Library Resync.. and make sure when you view your library in the OA browser, there is a download button by each book. Clicking the download button should start a download in OA.

**Comment by milegrin** [comment]
This occurs with PodCasts, Audible Escape and such.

The only solution I have found thus far is to manually download the AAX and either import into OpenAudible or use the AAX2MP3 script (to convert and split into chapters similar to OpenAudible except it can do bulk convert and sorts the output by author & title).

PodCasts can be downloaded via web but you need the Audible Manager to download Audible Escape books.  It is a P.I.T.A but all I have found thus far.

**Comment by TimoT75** [comment]
Hi, thank you for the quick answers.
This seems not to be the problem. The file was already download and i imported it from my local disk. I re-downloaded it then via OpenAudible and it worked. I retried and downloaded the AXX-File manually from Audible and tried again with the same result as above.
The download via OpenAudible worked but not the dierct import ???

**Comment by secretovida** [comment]
I got it to work this morning. I changed the download type from 'format 4' to 'Enhanced' and then clicked download and it worked.

**Comment by openaudible** [comment]
Good to know... Set download type to Enhanced. I'll see if I can detect that when looking at the library.
