### ISSUE TITLE
Feature Request : Description file

### ISSUE THREAD

**Issue by milegrin** [openaudible/openaudible#248]
Feature Request
Save the Audiobook details in a TXT file with the MP3 as a configurable option
I am willing to donate for this feature

I have written a very crude script to generate the files from the OpenAudible book list export which works ok :
https://www.dropbox.com/s/l8nmwk2okwjdm1r/openaudible_books_csv2nfo.sh?dl=0

This is an example of the output file : 
https://pastebin.com/NvnLgaUX

**Comment by openaudible** [comment]
Its a good idea. I do think its pretty easy to write a little script to go from books.json to .nfo. 
You could also try: ffprobe -hide_banner xyz.mp3 > xyz.nfo 2>&1
Will keep it as a possible future feature.
