### ISSUE TITLE
Native PodCast Support

### ISSUE THREAD

**Issue by benjaminewton** [openaudible/openaudible#249]
I know this has come up before but native Podcast support would be very useful.
Great program though, many thanks.

**Comment by M1DLG** [comment]
I was going to open a ticket for this unaware it was a frequently request issue. I have a very large Audible collection (2000+ purchases and several podcasts) and I find it difficult to manage the podcasts. If I could just drop the aax files I have downloaded from the website in a folder with the name of the podcast it would be helpful. Currently this doesn't work, only the files in the aax folder is visible folders within the aax folder is ignored, 

To download the AAX files I use Chrome with the user agent changed to a Nokia 7110.

**Comment by openaudible** [comment]
Try the following:
Quit and restart OA. 
Open File: Console 
Drag and drop an AAX file onto the OA application.
Does the file import? If not, what does the console log say?
