### ISSUE TITLE
Join Audio Files not creating the single mp3

### ISSUE THREAD

**Issue by Avilyn238** [openaudible/openaudible#252]
I select "Join Audio Files" from the File menu, point to a folder with individual mp3s, select all of the mp3s, and hit "Open";  I select a new folder for the output and give the joined file a new name, but when I hit save, the dialog box disappears almost immediately and the destination folder I selected is empty.  I've made certain the destination folder is not the same as the working or web folders.  The mp3s I'm trying to join are from LibroFM, but they are DRM free.

**Comment by openaudible** [comment]
Look at the File: Console and see what the error message says.

**Comment by Avilyn238** [comment]
[Console Text.txt](https://github.com/openaudible/openaudible/files/4014475/Console.Text.txt)
Attached a copy of the console text.

**Comment by openaudible** [comment]
That's a weird ffmpeg error. If that txt file is still on your machine, try running from the command line:

`"C:\Program Files\OpenAudible\bin\win\ffmpeg.exe" -f concat -i C:\Users\admin\OpenAudible\tmp\1577907565097.txt -c copy -safe 0 "C:\Users\admin\Documents\Keep\LibroFM\Joined MP3s\A Blade So Black.mp3" `

Which adds a -safe 0 to the standard ffmpeg command. I don't know why that error comes up --but I think it has to do with unicode characters or spaces in the file names... but the safe flag should prevent the error.. but would be curious to know why ffmpeg doesn't think a file name is safe.

**Comment by openaudible** [comment]
Can you try the version: https://openaudible.org/temp/OpenAudible_1.6.4_win.exe
I added the -safe 0 arguments to ffmpeg.
Please let me know.

**Comment by Avilyn238** [comment]
Confirmed the new version works, thank you!
