### ISSUE TITLE
Version of open audible is out of date?

### ISSUE THREAD

**Issue by finitetime1** [openaudible/openaudible#253]
I tried to open Open audible and it would not open.  I get error message saying its out of date and I need to update. I tried to download the new version but windows says its not a good win32 file. 
I have spent the last couple of months downloading and converting my books and now I cant add any more. Any suggestions. I'm still running windows 7

**Comment by openaudible** [comment]
OpenAudible requires 64 bits for windows. It has always been an unsigned application, so you may need to "run it anyway".

**Comment by finitetime1** [comment]
I've got windows 64bit os. It worked right up until the new year kicked in. I haven't been given the option to run it anyways or I would have. I get a message "This version has expired" and a link to to download new version. I downloaded the new version but when I try to open it I get the error message that "This applications is not a valid win32 app?

**Comment by finitetime1** [comment]
Everytime I opened the program I was told a new version existed but I could never get it to install either. Since I had a version that was working I gave up and just closed the window.

**Comment by openaudible** [comment]
We have expiration code in the application in case we get a nastygram. 

Try uninstalling current version (it won't work once expired..) then disable firewall/anti-virus and try latest installer. Not a known or common error message and 5000+ windows downloads.

**Comment by finitetime1** [comment]
I just uninstalled. I still get its not a valid win 32 app when I try to install

**Comment by finitetime1** [comment]
Do you have an older version that will not expire?

**Comment by openaudible** [comment]
You can try other versions.. but they will all eventually expire. 
How about a screenshot of your error?

**Comment by finitetime1** [comment]
the exact message is  c:\users\jp\desktop\openaudible_1.6.4_win.exe is not a valid Win32 application. 
This started immediately after I installed the first version. After I tried it one day and realized I liked it I tried to upgrade when i was told there was a newer version. I got the error message as soon as I tried install it but didn't worry to much cause I thought I had a working version.

**Comment by openaudible** [comment]
Well, OpenAudible isn't a 32 bit application.. its 64 bit. I don't know. My guess is anti-virus. Or incomplete download. Check the file size and md5.

   "file": "OpenAudible_1.6.4_win.exe",
   "size": 163629568,
   "mb": "156.04Mb",
   "version": "1.6.4",
   "platform": "Windows 64x",
   "md5": "72696cebe66229f6cea8b190ad32062d"

**Comment by tpmullan** [comment]
I am getting that the version has expired.  It looks like this issue was added on purpose and really shows how much of a money grab this project has turned into.  It is really disappointing when open source projects have to resort to such annoying tactics.
