### ISSUE TITLE
Different hard drive for AAX and MP3

### ISSUE THREAD

**Issue by M1DLG** [openaudible/openaudible#254]
I have a small SSD for my c drive, this usually isn't an issue, but with OpenAudible and my 2000+ book account I cannot download everything easily, as this is 600gb for the aax files alone. I have an external drive and would like to have the mp3 and the aax files on separate drives so I can manage them better as the number of books out grows my drives capacity.

Is this something I can do? I cannot see any settings allowing me to do this currently. I suspect under Linux this would be easy, but I am under W10 on this computer :(

**Comment by openaudible** [comment]
Sorry. No way to do this. If you can buy that many books you can afford a new hard drive.  :)  Actually, you _might_ be able to create an alias to a new aax directory.. but haven't tried.. maybe depends on the OS.

**Comment by M1DLG** [comment]
> Sorry. No way to do this. If you can buy that many books you can afford a new hard drive. :) 

Became unemployed at xmas. If I didn't I'd have offered a donation to help support development.

**Comment by pcarrick** [comment]
I was able to download to an external drive. Just set the "working directory" as the other drive letter. I also made backups of the data, so I used the same structure and names. 
(i.e. D:\Users\username\OpenAudible)

3,000+ titles, 900+ GB. 

My suggestion after my 4th attempt, it was over many weeks

Do not us the "download" or "convert" at start up options. 
Download everything first
Once all of the books are downloaded, you can begin converting.
If you do not care or want the AAX files, create a script to "clear" the file if it is in the MP3 folder.

I'm keeping the AAX files to customize the conversion to MP3 outside of OpenAudible. Some of the books do not need a high baud rate.

Feel free to let me know if you have any questions.
