### ISSUE TITLE
 Please Enable Cookies to Continue. To continue shopping at Amazon.com, please enable cookies in your Web browser.

### ISSUE THREAD

**Issue by ninep9up** [openaudible/openaudible#255]
Is all I get while trying to log in. Is there something I'm missing?

**Comment by openaudible** [comment]
What region are you in? Italy is not supported. Usually you can just log into your audible account and as long as you can view and/or download your books, it should work. A screenshot perhaps?

**Comment by ninep9up** [comment]
I'm in Russia. I've imported some aaxs and it seemed to have gotten credentials from them - I don't actually know what happened, but I was logged afterwards. If I try it through the browser though, I get this

![Untitled11](https://user-images.githubusercontent.com/24707777/71776037-4dcdf100-2f9b-11ea-9000-dcdc4a6e0947.png)

**Comment by openaudible** [comment]
That is probably audible.co.jp region restricting your access from Russia. You could try a VPN based in Japan. Closing as likely an audible issue.

**Comment by ninep9up** [comment]
Audible.com logging doesn't work likewise if anyone's gonna keep an eye on it. Waterfox works fine. So it's probably a protocol-based.
