### ISSUE TITLE
exporting to m4a m4b and exporting as not just a single file

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#256]
the project https://github.com/KrumpetPirate/AAXtoMP3 exports AAX files as mp3 and m4a broken into the chapters (for want of a better word) used by audible players the license of the AAXtoMP3 should permit you to use it's work.
Being able to export to this format (it should be just a simple list box selecting the output format and if to concatenate the file or not) and then using this in the ffmpeg parameter.

the commend to extract to m4a using aaxtimp3 is
AAXtoMP3 -e:m4a -c -A <audible key> <filename>.aax 

the audible key is used to decrypt the aax file you clearly already know this bit

**Comment by feldegast** [comment]
https://github.com/KrumpetPirate/AAXtoMP3

**Comment by openaudible** [comment]
I've successfully made m4a files from aax using ffmpeg. It works great and its fast. The only downside is m4a isn't supported by many players.. even VLC can't play them. These "easy features" often turn out to require a lot more tech support and debugging. Its on the feature request list.

**Comment by feldegast** [comment]
i use Plex and VLC, extensively they both support m4a and m4b formats, i
just tested VLC and while VLC may not fully support the formats they do
play without an issue,

**Comment by feldegast** [comment]
Extracting chaptered MP3 files from AAX files using openaudible is a little clunky, it remembers only one of the directories needed to split the file, try exporting 3 AAX files and see what i mean.
Compare the process below to quickly to extract multiple AAX files to M4A, which is significantly faster than having to convert the files to mp3 and then individually split each file as there is no batch process
AAXtoMP3 -e:m4a -c -A <code> <path to AAX files>/*.AAX

**Comment by openaudible** [comment]
Saved as a feature request.

**Comment by openaudible** [comment]
M4A support has been added to 2.0.6 and newer.
