### ISSUE TITLE
OpenAudible converting 12h AudioBook into 17h MP3-File

### ISSUE THREAD

**Issue by kaleitec** [openaudible/openaudible#257]
I´ve tried to convert some Audiobooks from my library, but every Audiobook is about 6-8 hours longer than the aax-file. 

One of the titles was the first pat of "The Witcher", the original audio book is about 12h 35m and open audible converts into an mp3-file with 17h 40m.

I think it's a Bug or someone maybe now what the Problem is?

**Comment by openaudible** [comment]
Never heard of that. Can you ffprobe both aax and mp3 file and see what the difference is? Did you listen to the mp3 and see if it added content somehow?

**Comment by kaleitec** [comment]
Today i start the converted version with the vlc player, yesterday i used the integrated windows player. But in the vlc player the remaining time changes every second and near the end the converted mp3 file end abrupt.

I want to try ffprobe the two files tomorrow and then i post the logs here.

**Comment by openaudible** [comment]
This appears to be bug #258... Investigating. Closing and feel free to add comments to #258.
