### ISSUE TITLE
Conversation got non-zero response:69

### ISSUE THREAD

**Issue by Jonges** [openaudible/openaudible#259]
So I been searching for a DRM remover for my audible library. I didn’t wanna pay like 40 bucks for any pro versions. I tried cracks for softwares but they all are out of date.

When I try to convert my audiobooks to mp3 everything works till the last min of audio then I get the error Conversation got non-zero response:69. 

Not really sure what to do so if you need any other information please tell me.

**Comment by openaudible** [comment]
Duplicate of #250 ...
