### ISSUE TITLE
Open Audible won't load

### ISSUE THREAD

**Issue by Trebor-58** [openaudible/openaudible#260]
OpenAudible crashed and came up with the error message below, I have tried uninstalling but when I reinstall I get the same message.

Unable to create or load required directories. Check that the drives are read/writable.
ErronNot a JSON Object:
AuOWO\uOCH)0\uOCH)0\uOC^
0000\u0000\u0000\u0000\u0000\u0000\u^^
0\uOWO\uOCH)0\uOCH)0\uO^
0000\u0000\u0000\u0000\u0000\u0000\u^^
0\uOWO\uOCH)0\uOCH)0\uOCW^
0000\u0000\u0000\u0000\u0000\u0000\u^^
0\uOWO\uOCH)0\uOCH)0\uOCW^
0000\u0000\u0000\u0000\u0000\u0000\u^^
0\uOWO\uOCH)0\uOCH)0\uOCW^
0000\u0000\u0000\u0000\u0000\u0000\u^^
0\uOWO\uOCH)0\uOCH)0\uOCW^
0000\u0000\u0000\u0000\u0000\u0000\u^^
<Au0000\u0000\u0000\u0000\u0000\u000^

**Comment by openaudible** [comment]
Take a look at the contents of your C:\Users\XXXX\OpenAudible\directories.json . It may have gotten garbled? Just rename/erase that file and try again. I'll improve the error message.. but it is strange. What OS and language/region are you in? For future versions, if I can't load the directories I'll try to fall back to the default settings.

**Comment by Trebor-58** [comment]
That fixed it, I renamed the json file it came up with an error message
about not being able to find books, so uninstalled and renamed the whole
folder for it to install a new on all seemd to be working fine thank you

**Comment by openaudible** [comment]
Curious how it got corrupted.
