### ISSUE TITLE
Want to donate but not through paypal

### ISSUE THREAD

**Issue by michaelgreen06** [openaudible/openaudible#261]
PayPal censored my account so I no longer can use this to donate. 

I love this software and want to support it.

Can I pay you in crypto? Preferably ETH.

Thanks!

**Comment by openaudible** [comment]
Hah. I've never used crypto.  I just created an empty wallet 

ETH: 0x8478CECc6acDF9fc65adF7728Ce3A5B40D5051D2 
BTC: 1MN38DyrBEFhoKsjQJDKBzZiucvCquZDgD

Thanks for the kindness!

**Comment by michaelgreen06** [comment]
Great!

I just sent you $10 in sai tokens. It's a stable coin so you don't have to
worry about its value going up or down.

Thanks for creating such useful software! I love it so much and greatly
appreciate you!

**Comment by openaudible** [comment]
Got it! Thanks!
