### ISSUE TITLE
Feature Request / Advice Request - Extremely Large Library

### ISSUE THREAD

**Issue by Torr1978** [openaudible/openaudible#262]
My Audible library is larger (I haven't found a sale I could pass up on) than my NVMe OS drive (Windows 10 on  C:\) could possibly handle.  My solution to that was to use **mklink /j** to redirect the OpenAudible folder in my User home to a spinning disk (D:\Audible\OpenAudible).  Unfortunately that spinning disk also houses my steam library.  That results in constantly competing space.

Is there a way to redirect OpenAudible so it looks for it's data on my NAS or Home Media Server? Is there a way to split up the AAX and MP3 files in batchs across multiple hard drives?

I assume a really fancy system it will require a ton more logic than just pointing it's base data level at the NAS (but that might do what I'm needing) in that you would probably want to keep a list/record of what has been downloaded and converted and the last time the program saw it, instead of it just trying to download it over and over again, a better solution would probably be to ask for where it has been moved to before re-downloading something.

Extra feature request: download rate throttling for very large file/book counts.  If I were to just download my entire library in one go I would probably go over my data cap that month.  Maybe limit the number of downloads per day, or per month.  Once I've got a copy of everything I don't expect to have this problem in the future but getting there might be better to do it slow and steady fashion instead of all at once.

**Comment by openaudible** [comment]
Buy a bigger hard drive if you're running out of space. 7000 books per TB?

You can point the data directory to a NAS if its mapped to a file path. 

You could also try using symbolic links (aliases or shortcuts).

Some people have edited the directories.json settings file and added a MP3 or AAX entry.. but not supported. 

You can edit the settings.json file to limit the concurrent downloads from to 1 but we don't throttle downloads.

**Comment by Torr1978** [comment]
Your numbers and my numbers are not anywhere close to being similar.
"Buy a bigger hard drive if you're running out of space. 7000 books per TB?"
While amusing and I assume and attempt at humor (I don't get it), the issue wasn't that I couldn't get a bigger hard drive it is that I didn't want the data going onto my expensive very fast hard drive but a larger slower hard drive (preferably through a setting in the software instead of tricking the software with symlinks/hardlinks/junctions or the like).  Though a 2TB NVMe M.2 drive does sound like a great investment for some applications I was really hoping for a solution to utilize other mass storage already at my disposal.  _I have learned that, unfortunately junctions will not cross a Network Share and I didn't have time to investigate other link methods before posing the question._

I did however verify that I could map a network drive letter to a section of my NAS (or some file server on my network) and then using the Windows 10 command **mklink "C:\user\{username}\OpenAudible" "{NAS Dirve Mapping}:\OpenAudible"** and trick the software into seeing the data that I copied over there.  This was one solution you suggested.

I have not tried just right click dragging a folder across for creating a shortcut and giving it the name "OpenAudilbe", have people had success with that?


The 7K Books to 1TB ratio you mention, if serious and not sarcastic, now makes wonder if I have my configuration set completely incorrectly some how to be so far off (I didn't actually configure anything, just installed the program)? Let me provide my numbers for disk usage and you can let me know if I've broken something some how:
In my OpenAudible\AAX folder right now I have 1,204 files which weigh in at roughly 364 GB according to windows (in reality 391,277,969,408 bytes on disk are actually used) and I haven't finished downloading my library yet.

Then you throw in the OpenAudible\MP3 files, while smaller, still add up to 260 GB (279,720,034,304 bytes on disk) but there are many files/books left of to be converted as only 856 files live in that folder and the time I pulled the numbers (they are one file per books MP3s).

In total my OpenAudible folder consumes 671,363,760,128 bytes on my NAS and the process isn't done.  I will cross the the 1TB mark long before I get to 7000 books you mentioned.  Have I done something wrong to cause everything to be bigger than you would expect? I fully realize that the length of the book will greatly impact how big the files are, along with the quality. As such I don't feel like I have an unreasonable exception of how much data is going to be used (7K Books to 1TB sounds like the books would have to be less than 1 hour each in low quality to get to that kind of ratio).  

OpenAudible reports that I have 19,129 hours of listenable material (I don't know if that is in my Audible library or downloaded, I assume my online Library that has had it's meta data downloaded) and using a hours to disk storage ratio might be more meaningful to understand how much data storage could reasonably be expected to be used.
