### ISSUE TITLE
Issues when downloading

### ISSUE THREAD

**Issue by milesdleeg** [openaudible/openaudible#263]
Hello.
I'm sure the problem is on my end but after 3 hour of trying to find a solution, I decided to just post.

When downloading a 4 hour audio book, it repeats sections in the middle making it a 9 hour audio book. 

I followed the steps. Connected my audible account and downloaded as mp3. Uninstalled and reinstalled and I still have the same issue. Weird thing is, when I put the mp3 in itunes, it shows as the normal 4 hours but as soon as I put it on another device or in a different program, it is back to 9 hours. 

Thanks!

**Comment by openaudible** [comment]
It probably isn't a download issue but is a conversion bug in going to mp3. Related to #258 
Are you on Windows?

**Comment by milesdleeg** [comment]
Hello! Yes, I am on windows 10 home.

**Comment by openaudible** [comment]
I updated the version of ffmpeg for 1.6.5. Feel free to erase and re-encode any or all mp3's. Open a new issue if it isn't solved.

**Comment by milesdleeg** [comment]
Thank you so much for the work. I will try it in the next few day. Cheers.
