### ISSUE TITLE
java.nio.file.InvalidPathException for books with umlauts in their name

### ISSUE THREAD

**Issue by docbobo** [openaudible/openaudible#265]
Running on a dockerized Ubuntu, books with german umlauts (äöü etc) in their name fail to download properly. Instead, an exceptions is being logged:

java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters:

**Comment by openaudible** [comment]
Check the output of 
`locale
`

The LANG setting should end in .UTF-8, not some other encoding system. Setting the locale to utf-8 should solve it.

If running OpenAudible from the command line, you need to set the file encoding, which I just noticed my debug.sh didn't show: 

`java -cp "openaudible-jar-with-dependencies.jar:org.eclipse.swt.gtk.linux.x86_64-4.6.jar" -Dfile.encoding=UTF-8 org.openaudible.desktop.Application
`

**Comment by openaudible** [comment]
Updated read-me and added warning if file encoding not utf-8.
