### ISSUE TITLE
Nothing happens on execution

### ISSUE THREAD

**Issue by johnnybollig** [openaudible/openaudible#266]
After I download the file nothing happens at all when I click on the file. Only my "antimalware service executable" runs for 10 seconds acording to my tast manager. 
Maybe it has to do with following, but I have no idea of this stuff:
(I am not getting warned btw. for anything)
"Install the version for your platform. Until we get a signing certificate, you will be warned that this is an unsigned application. You may need to change your GateKeeper settings, but hopefully not."

**Comment by openaudible** [comment]
What platform are you on? Did you disable your anti-malware or create an exception for the app? Maybe run from the terminal and look for an error message..

**Comment by johnnybollig** [comment]
Windows 10. Never disabled anti malware and don't know how :-D However I used a different program that worked fine.
