### ISSUE TITLE
OpenAudible hangs & freezes Ubuntu

### ISSUE THREAD

**Issue by goodmanproject** [openaudible/openaudible#267]
Hi,

I love OpenAudible. Especially enjoy the one of the new features in the latest build that enables me to divide into separate MP3 files for each chapter. I've come across what appears to be two bugs:

1) The application hangs & freezes Ubuntu when converting an .aax that's 1.7 GB. The duration is about 55 hours. It crashes at the 52 hour mark. Here's the description: https://www.audible.com/pd/The-Complete-Sherlock-Holmes-Audiobook/B00FEFE4XK?pf_rd_p=6a5ce8e4-798e-4a64-8bc5-71dcf66d673f&pf_rd_r=6NR6W655WDZKHDDXETNN&ref=a_lib_c4_libItem_B00FEFE4XK - I can send you a download link in Google Drive if that will help.

2) Because the duration is so long and the file is so large, Audible also provide the book for downloading in 7 separate files. The bug here is that OpenAudible won't import them, won't add them to the list of files in the lower pane. Note that the entire file (1.7 GB) does get added and allows conversion to start (but eventually hangs).

I'm happy to test any interim updates. I'm a developer too and I know (all too well) that testing is as important as coding.

Have a great weekend,

Dan

**Comment by openaudible** [comment]
ffmpeg does the conversion and it can do large conversions.  I assume you mean ffmpeg hangs but OA continues to run but the conversion never finishes? What platform are you on (mac/win/linux)

Can you copy and paste the command used to convert the file from the log window and paste it into your terminal? I'd like to know if ffmpeg is hanging or openaudible. If its ffmpeg, there may be a newer version or it may be a bug we can't fix. 

I have a new version coming out that updates the windows version of ffmpeg to fix other bugs affecting us..

**Comment by openaudible** [comment]
I found one deadlock bug that happened when I tried a large file. Fixed in 1.6.5. Give it a try and try the above fix if still having issues.

**Comment by goodmanproject** [comment]
the update didn't fix the bugs
