### ISSUE TITLE
Connection errors with Two-Step Verification

### ISSUE THREAD

**Issue by KatyaL** [openaudible/openaudible#27]
When Two-Step Verification is active on an Amazon/Audible account, the OpenAudible Browser logs in successfully without requiring authentication (?!), but the main application can't connect and the attempt results in error pop-ups.

Audible remembers my regular browser and doesn't require Two-Step Verification when logging in. I assume that the OA Browser mimics my primary browser so it opens my Audible account properly, but for whatever reason the main OA program does not do so, and it has no way to pass the authenticator code request on to the user.

Disabling Two-Step Verification on Amazon/Audible results in a successful connection, but it's not the optimal solution.

**Additional Info**
OS: Windows 10 64-bit  v. 10.0.17134 Build 17134
Browser: Chrome Version 68.0.3440.106 (Official Build) (64-bit)

**Comment by Av8or1ab** [comment]
Bump on this. Having the same issue. Looking forward to a workaround. Great application.

**Comment by openaudible** [comment]
Give 1.2 a try. If any problems, please create a new ticket. The new 1.2 has a whole new way of connecting.
