### ISSUE TITLE
44.1kHz files do not play on Android

### ISSUE THREAD

**Issue by srd424** [openaudible/openaudible#271]
First, apologies: this isn't really a proper bug report. I've come across some information about a really obscure corner case where decrypted AAX files with a 44.1kHz sample rate don't play natively on Android.  This causes problems with e.g. Booksonic if transcoding is disabled for m4a / m4b files.  There's a full write up to be found here: https://rentry.co/n4ost

I just wanted to pass the information around the relevant parts of the community and this seemed a good place to start! Hope that's OK.

**Comment by openaudible** [comment]
The converted MP3's also don't play? 
If this affects anyone, when a fix is made to ffmpeg, you can replace the ffmpeg included with openaudible.

**Comment by srd424** [comment]
No, transcoding is fine - problem is if you keep the original m4a / m4b after decrypting it. As I said, just wanted to put the info somewhere people might find it, apologies for the noise .. I will see if I can find anyone on the ffmpeg project to have a chat to..

**Comment by openaudible** [comment]
M4A support has been added to 2.0.6 and newer.
