### ISSUE TITLE
OpenAudible 1.6.5 not recognizing all books on Audible US

### ISSUE THREAD

**Issue by Geordon** [openaudible/openaudible#272]
I have over 5 pages (50 per page) of Audible purchases, but OpenAudible is only seeing the first page or two.  

How can I make it page through my entire Audible library and find all of my purchases?

**Comment by openaudible** [comment]
Make sure the drop down menus are set to show all your books.. not just the ones from "last 12 months".

**Comment by Geordon** [comment]
Filters are set to display all books at max (50) per page.  For some reason, OA doesn't seem to be progressing to further pages.  Further, if I try to do a full library sync, the app freezes.

**Comment by LanceMcCarthy** [comment]
Same problem here, I have 3 pages at 50-per page.  It seems audible doesn't want us to be able to list them all to prwvent scrapers from downloading the entire library :/

@openaudible Here's the largest it allows from the dropdown selection, notice the `pageSize` parameter value:

https://www.audible.com/lib?[REDACTED-IDs]&ref=a_lib_c5_pageSize_3&purchaseDateFilter=all&programFilter=Product&sortBy=PURCHASE_DATE.dsc&**pageSize=50

I manually tried to bypass this with:

https://www.audible.com/lib?[removedID]s&ref=a_lib_c5_pageSize_3&purchaseDateFilter=all&programFilter=Product&sortBy=PURCHASE_DATE.dsc&**pageSize=150

But it will default back to 20-per page when the `pageSize` parameter doesn't validate.

So OpenAudible is probably going to have to parse the `ref` parameter or something else that determines how many pages are available, then use use a loop to enumerate and repeat each page fetch.

**Comment by LanceMcCarthy** [comment]
[Update] @Geordon  I was able to get OpenAudible (on PC) to parse all the books by doing a "Full Library Sync" and manually switching tabs. The app would pick up the books on 2nd and 3rd page as I scrolled through.

**Comment by Geordon** [comment]
@LanceMcCarthy That's actually the first thing that I tried.  It picked up page 2, but not pages 3-6 on multiple attempts

**Comment by LanceMcCarthy** [comment]
@Geordon I can attest that it didn't work for me the first time either. Somethings changed after I closed the browser window, then selected "full sync" and opened browser again.

I noticed at the bottom of the browser window, there was a progressbar that updated each time I changed pages.

**Comment by openaudible** [comment]
The quick scan is supposed to just get pages until no new books are found. It assumes you are sorted by date purchased (new first) and have no date restrictions. It reads a page, finds the "next" button, and simulates a click on it. If it can't find a "Next" button, it writes out a message to the log window.
A full scan will also go thru the books until no "next" button is found. 

In a pinch, you should be able to manually click next and OA will know it is on a library page and import your books on that page. 

Feel free to check the Log message and keep the browser open while it does its rescan.. Feel free to post any errors or submit a bug report via the Tools menu.

**Comment by Geordon** [comment]
Ah HAH!  I think I found something.  Java error.  The output from the log console is below.

I am running Java 8 Update 241 on macOS 10.15.3

`
INFO: Command: Rescan_Library
Feb 19, 2020 9:17:13 PM org.openaudible.desktop.swt.manager.menu.CommandCenter handleMenuAction
SEVERE: ProcessMenu: Rescan_Library
java.lang.UnsupportedOperationException
	at java.util.Collections$UnmodifiableCollection.addAll(Collections.java:1067)
	at org.openaudible.Audible.findOrphanedFiles(Audible.java:631)
	at org.openaudible.desktop.swt.manager.AudibleGUI.checkOrphansGUI(AudibleGUI.java:273)
	at org.openaudible.desktop.swt.manager.AudibleGUI.refreshLibrary(AudibleGUI.java:344)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.execute(CommandCenter.java:277)
	at org.openaudible.desktop.swt.manager.menu.CommandCenter.handleMenuAction(CommandCenter.java:83)
	at org.openaudible.desktop.swt.manager.menu.AppMenu.widgetSelected(AppMenu.java:358)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(TypedListener.java:252)
	at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:89)
	at org.eclipse.swt.widgets.Display.sendEvent(Display.java:4406)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1512)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1535)
	at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1520)
	at org.eclipse.swt.widgets.Widget.notifyListeners(Widget.java:1324)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Display.java:4193)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:3810)
	at org.openaudible.desktop.swt.gui.GUI.runEventLoop(GUI.java:345)
	at org.openaudible.desktop.swt.gui.GUI.run(GUI.java:446)
	at org.openaudible.desktop.swt.manager.AppLoader.<init>(AppLoader.java:72)
	at org.openaudible.desktop.swt.manager.AppLoader.main(AppLoader.java:80)
	at org.openaudible.desktop.Application.main(Application.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.exe4j.runtime.LauncherEngine.launch(LauncherEngine.java:85)
	at com.install4j.runtime.launcher.MacLauncher.main(MacLauncher.java:52)
`

**Comment by Geordon** [comment]
Also, manually paging through the library does not load the additional books.  

`Feb 19, 2020 9:22:45 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=100 total=100}
Feb 19, 2020 9:22:49 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=100 total=100}
Feb 19, 2020 9:23:17 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
Feb 19, 2020 9:23:41 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=100 total=100}
Feb 19, 2020 9:23:53 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=100 total=100}
Feb 19, 2020 9:24:02 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=100 total=100}
`

**Comment by LanceMcCarthy** [comment]
I had the same errors. I went back tried it again to get steps for you to try.

1. Close the app (all windows) 
2. Reopen the app and immediately select Controls > Browser
3. Leave the page size at 20
4. Click 'Quick Sync' 

Even though I had set the page size to 50 in step 3, the app went back to page 1 and started over (with 20 per page setting) and went through all 8 pages automatically for me. 

Although I haven't inspected the BrowserWebClient class directly, I think the errors we saw were due to some state mismatch... Which leads to the subsequent Progress Bar errors as well.

**Comment by Geordon** [comment]
Ok, so I did the above per @LanceMcCarthy and OA looked through and saw all of my pages and books, but it did not mary any of them other than the ones that I had from my first report.  When I did "full sync" it didn't recognize any of the books that hadn't been recognized earlier.

Also, OA is now allegedly downloading 3 of 87, but the app appears to have frozen.

**Comment by openaudible** [comment]
@Geordon you found a bug and it is fixed for the next version. That only affects the full rescan and only when you have files in your media folders not associated with a book in your library. 

But I think these errors are the drop down menu for purchaseDatreFilter was not set to "all". I will add a little more debugging code or warnings.. maybe take another stab at setting the drop down item.

**Comment by LanceMcCarthy** [comment]
3 is the default maximum parallel downloads. You can change this in the settings json file

It sounds like it is working!

**Comment by Geordon** [comment]
> @Geordon you found a bug and it is fixed for the next version. That only affects the full rescan and only when you have files in your media folders not associated with a book in your library.

Interesting!  As a side note, this was with a fresh, clean, blank install for OA and the media folders.  I'm not sure how there could be a file there that is not associated with a book in the library.  Is there anything else that I can look at to help?

Also, do you have an idea of when the new version will be released?

**Comment by openaudible** [comment]
@Geordon that bug is pretty much solved but thanks for the offer. Yes, it turns out it can happen on a clean install without files. Not sure when I will have a new version. I fiddled around with trying to set the sort by (date descending) and purchase date=all.

**Comment by Geordon** [comment]
Sounds good.  I have an irritating habit of finding oddball bugs in
software that I use.  At least I've spent enough time in tech support
(about 20 years) to be able to provide most of the helpful information
without too much guidance!

—
Geordon VanTassle

On February 20, 2020 at 9:59:47 PM, openaudible (notifications@github.com)
wrote:

@Geordon <https://github.com/Geordon> that bug is pretty much solved but
thanks for the offer. Yes, it turns out it can happen on a clean install
without files. Not sure when I will have a new version. I fiddled around
with trying to set the sort by (date descending) and purchase date=all.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/openaudible/openaudible/issues/272?email_source=notifications&email_token=ABK7RCBMHQYHTDH5RZNBIGDRD5GTHA5CNFSM4KWWMPN2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMRNW7Q#issuecomment-589486974>,
or unsubscribe

**Comment by openaudible** [comment]
Thanks all. I improved the library scraping code for the next release. Re-open if not fixed in the next version.

**Comment by LanceMcCarthy** [comment]
Great turnaround, thank you!  

Cat Tax... If I had the time to jump back into Java, I'd give you a hand, but I' swamped with things like automatically flushing the toilet for cat 

[https://dvlup.com/2020/02/13/using-windows-iot-signalr-azure-custom-vision-and-xamarin-forms-to-flush-a-toilet/](https://dvlup.com/2020/02/13/using-windows-iot-signalr-azure-custom-vision-and-xamarin-forms-to-flush-a-toilet/)
