### ISSUE TITLE
Import fail: Book too new for version

### ISSUE THREAD

**Issue by moosimoosmann** [openaudible/openaudible#277]
Hi there!
I tried to import an audio book. Open Audible says 

"Feb 24, 2020 9:35:39 AM org.openaudible.desktop.swt.manager.ImportExport _importFile
WARNUNG: Unable to import book:D:\HP\Die Weisheit des Feu_B006OK2NCS_LC_64_44100_Stereo.aax : Book too new for version"

I checked the purchase date in the audible app as suggested in an earlier post.
The purchase date is correct (yesterday).

Maybe worth to mention: The downloaded file is split into four parts by audible (although the setting "Download library in parts" is set OFF).

Thanks for your help!
Matthias

**Comment by openaudible** [comment]
Currently books with wrong meta data is skipped in the import process. A log will show which meta data is wrong and what the value is. If the date is in the future, it is assumed to be wrong. 
Make sure your library "Audio Quality" is set to "Enhanced" Format, not "Format 4". OA only supports Enhanced, and only attempts to download the full book.
