### ISSUE TITLE
Convert to MP3 is grayed out

### ISSUE THREAD

**Issue by highlife7** [openaudible/openaudible#279]
Using Windows 7, 64 bit
Just downloaded latest version of openaudible.

The bottom window lists a bunch of titles -- some that were automatically transferred from an older version of openaudible (AAX files) and some that were just imported yesterday from new purchases (AAXC files).

Unable to convert to MP3 as the "Convert to MP3" action choice is grayed out.

I already uninstalled openaudible, downloaded it again (both times from your web site) and installed the new download --and I have the exact same problem.

**Comment by openaudible** [comment]
AAXC files are not supported-- they don't have a download button and we don't have a way to download them or convert them.  AAX files should be fine. When you select a book, it should say why it can't download or convert them under the "State" item in the Audio Book Info section of OA. You want to make sure at least some of the books have a "Download" button enabled. 

Also, check: https://openaudible.org/settings.html
