### ISSUE TITLE
Cannot download or convert any AAX files

### ISSUE THREAD

**Issue by stupiduser1** [openaudible/openaudible#28]
using build 1.1.6 on a windows 10 system with all AAX files downloaded to a local folder
cannot download or convert any AAX files - the only messages I receive are:
"Not downloaded"
Convert to Mp3 is grayed out
Let me know if any logs or other info is needed

**Comment by openaudible** [comment]
Try the latest update and let me know. If the files aren't downloaded as AAX, they can't be converted.. Open the console and select one book and click download.. copy and paste any errors.. Please re-open if not fixed in latest.

**Comment by stupiduser1** [comment]
I am using the latest, thx

**Comment by stupiduser1** [comment]
"Converting AAX files to MP3 is done by selecting one or more downloaded
files and choosing “Convert to MP3” from the Action menu. Or simply select
“Convert All to MP3” from the Controls menu. "

taken right from the OpenAudible home page
