### ISSUE TITLE
How do I get mp3 chapters in OpenAudible

### ISSUE THREAD

**Issue by ukmaroon** [openaudible/openaudible#282]
I have downloaded and converted to mp3 but is it one audio file; how can I get chapters?

**Comment by openaudible** [comment]
Splitting chapters is not automatic. You need to use the File Menu: Split... and select an MP3 to split. 
Chapter data is also stored in the mp3 file.

**Comment by ukmaroon** [comment]
Thanks, much appreciated.

Best regards
Mike Johnson
+44 7757 816316
