### ISSUE TITLE
I cannot convert aax file to mp3

### ISSUE THREAD

**Issue by xhj2007** [openaudible/openaudible#283]
I purchased the audiobook from audible.com. I tried to use this software to convert aax to mp3 file and failed. I wonder if this can be resolved.

**Comment by xhj2007** [comment]
Here I attached the error message
![Error message from openaudiobook](https://user-images.githubusercontent.com/61929897/76158164-b0d92280-60c7-11ea-9dc6-f0998aa00b0c.jpg)

**Comment by openaudible** [comment]
We are not compatible with all systems. That error message is as detailed as we can get. Try it on another computer. If you're a developer, try running "rcrack.exe" with the above arguments using a debugger and figure out the bug and notify the original authors.
