### ISSUE TITLE
Dark KDE Theme - cannot read some text in OpenAudible

### ISSUE THREAD

**Issue by MountainX** [openaudible/openaudible#285]
Long time Audible customer here. Without this project, I would have canceled my Gold membership long ago. Thanks for the good work and the Linux support.

I run the Dark Breeze theme on KDE. Several menus such as Preferences are very hard or impossible to read due to font color. The dialog background is light, but the font used has the system color from my dark theme, meaning the font color is also light (almost the same color as the background).

![Screenshot_20200308_185027](https://user-images.githubusercontent.com/48405/76172634-4af3a600-616e-11ea-973c-ad823fe1033f.png)

**Comment by openaudible** [comment]
I think fixed in next release.
