### ISSUE TITLE
Option to utilize more CPU cores for ffmpeg?

### ISSUE THREAD

**Issue by MountainX** [openaudible/openaudible#286]
When converting to MP3, I notice that OpenAudible uses no more than 3 cores for the ffmpeg process. I have a desktop computer with a lot more cores that could be used. Is there any option for changing this setting?

I'm running the binary from:
AUR (en) - openaudible-bin
https://aur.archlinux.org/packages/openaudible-bin/

BTW, I'm a long time Audible customer. Without this project, I would have canceled my Gold membership long ago. Audible earns more profits from me due to the existence of OpenAudible.  Thanks for the good work **and the Linux support**.

**Comment by openaudible** [comment]
We use FFMPEG which is already optimized for the number of threads/cores. 

If you run tests and find adjusting the "-threads" argument makes sense, feel free to re-open.

**Comment by MountainX** [comment]
Thanks for your reply. From the ffmpeg docs:

> threads integer (decoding/encoding,video)
>     Set the number of threads to be used, in case the selected codec implementation supports multi-threading.
>     Possible values:
>     ‘auto, 0’
>         automatically select the number of threads to set 
>     Default value is ‘auto’.

Do you currently set it to auto?

 I just tested on a dual Xeon server with 40 cores and no other load. The max threads used by OpenAudible for ffmpeg is 3. I would like to utilize the other 36 idle cores. (I will probably have to re-process my books now that I am going to rename the aax files with the book titles first.)

This may not be important to most users. However, if it is easy to add a `threads` key:value pair to settings.json, that would be awesome. I assume that the value for mp3Qscale is currently passed to ffmpeg, so maybe passing the value for threads could be done in the same way?

From my perspective, you would not even need to add this setting to the GUI. Just put it in settings.json with the default value you currently use, and allow power users to set it to 0 if they wish to utilize all cores.

Alternatively, if there is a way I can already override the values you pass to ffmpeg, please let me know. Thank you.

References:
https://streaminglearningcenter.com/blogs/ffmpeg-command-threads-how-it-affects-quality-and-performance.html

http://ffmpeg.org/ffmpeg-all.html

**Comment by MountainX** [comment]
Never mind. The setting `concurrentConversions` does what I wanted. With that setting I can utilize all my cores. Thanks!

**Comment by ollydixon** [comment]
I don't see a ```concurrentConversions``` setting for FFMPEG @MountainX ?

**Comment by openaudible** [comment]
concurrentConversions is an openaudible setting for number of conversions to do at once. 

Open the OpenAudible preferences. Click on the Preferences... Folder icon.. .(3rd item from top in current release.)
The "settings.json" file should be selected in your desktop.
 Carefully edit this file with a plain text editor.
You'll see something like:
```
concurrentConversions: 3,
```

Change the 3 to whatever number you want to experiment with (up to 20, I think, which could crush your cpu/memory). 
Restart the application and experiment with multiple conversions at once beyond the default "3".

@MountainX We looked at the ffmpeg -threads option and did not find any performance increase when setting it to auto versus 8 versus 24. 

You can experiment with this yourself by using a hidden feature to let you add arguments to ffmpeg mp3 conversion. Create a file in the settings directory (next to settings.json) called ffmpeg_args_mp3.txt and add your custom argument, one per line. So in your case you could add: 
```
-threads
24
````
See #725 

But I'm pretty sure you will not see a performance change. 

Hope that helps!
