### ISSUE TITLE
Feature Request: Rename File Names Using Book Titles

### ISSUE THREAD

**Issue by MountainX** [openaudible/openaudible#287]
I want to have my MP3 files named according to the book titles instead of using a code or ASIN as the filename. I don't currently see an option to do this.

For now, I wrote a small python script to do it for me. I'm sharing it here in case anyone else finds it useful. I'm using this method, but it makes my MP3 files incompatible with OpenAudible, unfortunately. I still find it more useful to have my files named with meaningful titles. 

Can anyone suggest a better approach? Is there any reason this couldn't be incorporated into OpenAudible, which would resolve the problem I face while still providing the benefits of meaningful file names?

```
#!/usr/bin/env python
from os import rename, listdir
import re
import json

def remove_whitespace(string):
    nowhitespace = re.sub(r"[*$<,>?!']", "", string)
    nowhitespace = re.sub(r'\W+', '_', nowhitespace)
    nowhitespace = re.sub(r'_+', '_', nowhitespace)
    return nowhitespace

books = json.loads(open('~/OpenAudible/books.json').read())
filenames = listdir('/path/to/audible/mp3/')

for book in books:
    title = book['title']
    clean_title = remove_whitespace(title)
    orig_filename = book['filename']
    print(orig_filename, title)
    for f in filenames:
        if f.startswith(orig_filename):
            new_filename = clean_title + "_" + orig_filename + ".mp3"
            print(new_filename)
            rename(f, new_filename)
            break
```

**Comment by MountainX** [comment]
I notice that if I have the application create a "web page" it will also copy all the MP3 files into a web subdirectory and simultaneously rename them using titles. This is similar to what I had in mind, except in my case I would like to also remove certain characters from the file names.

I accomplished my goal in two steps. I imported all the original aax files (which had named based on ASINS). This generated a books.json. I used that and a version of the above python code to rename the aax files using the cleaned up titles.

Then I closed the app and deleted books.json, keys.json and any other files related to that first pass. 

I reopened the app and re-imported the aax files. Then I converted to MP3. Now both the aax files and the MP3 files have matching names based on the book titles. And the names don't include commas and other characters I wanted to avoid.

**Comment by openaudible** [comment]
What version are you using? We've switched to saving files with titles a long while ago.. Originally we used the product ID, to avoid file name collisions where the title isn't unique..

**Comment by MountainX** [comment]
I'm running openaudible-bin 1.6.5-1 from Arch's AUR. And yes, you are correct. It appears the issue stems from the way I downloaded the files in question.

BTW, the docs feature a link to https://www.addictivetips.com/ubuntu-linux-tips/back-up-the-audible-library-on-linux-openaudible/

In that article, the author gives outdated steps for installing on Arch. Your users might like to know that can be as easy as:

`yay -S openaudible-bin`
