### ISSUE TITLE
Importing files and case sensitive file names: AAX vs aax

### ISSUE THREAD

**Issue by MountainX** [openaudible/openaudible#289]
Linux is case sensitive, unlike some other platforms. I noticed that OpenAudible will only find aax files to import (from the filesystem) if they are named with all lowercase letters in the extension ("aax"). However, when it imports and copies those files it names them with an all uppercase extension ("AAX"). Is this a bug or a feature? (Maybe you do that to signal that the file has been imported? However, that would only work on case sensitive file systems, so maybe it is a bug? If it is not intentional, maybe the naming could be made consistent for those on case sensitive file systems.) 

It caused me a bit of confusion until I realized what was happening, so this issue is raised to alert anyone running into this and also to ask if this should be documented. Thanks again for your work on this helpful project.

**Comment by openaudible** [comment]
Yeah, that was an oversight. Fixed for next release. No ETA. Thanks!
