### ISSUE TITLE
Software Verification section not available in Audible JP

### ISSUE THREAD

**Issue by jun1perus** [openaudible/openaudible#290]
I can log in to my Audible Japan account just fine using OpenAudible's built-in browser. Library status shows 'connected: yes', and when I sync my library, I can see my books, albeit with a red dot. 'State' under Audiobook Info says "No MP3 or AAX or download link."

So I followed the instructions [here](https://openaudible.org/settings.html) but I can't find the Software Verification section to uncheck "Check for Audible Download Manager" in Audible Japan. It's just nowhere to be found.

I'm currently on the 30-day free trial of Audible. Maybe that's why the Software Verification section doesn't appear under Account Details?

I tried downloading the AAX files via the PC app and manually importing them into OpenAudible on Mac. But they still show a red dot and can't be converted into MP3.

Can anyone help me with this?

**Comment by openaudible** [comment]
I'm not sure if OA is compatible with Japan. I am not sure why there is no button that lets you download a book... A trial shouldn't be a problem. You should be able to find a recommended PC application to use to download and play apps.. and usually, if that is installed, a "Download" button appears next to the book in your library view in a browser. 

If you download them another way, dragging and dropping .AAX files onto OpenAudible should work. (Just found a bug, where .aax (lowercase) do not import.)

Maybe someone else from Japan has had success?

**Comment by jun1perus** [comment]
Thank you for your reply. 

> You should be able to find a recommended PC application to use to download and play apps.. and usually, if that is installed, a "Download" button appears next to the book in your library view in a browser.

I'm using a Mac (10.15.3 Catalina) and apparently Audible doesn't have a Mac app, but an iOS app and a PC app. When I view my library on a browser, I get a notice that says "Click on the orange button under the book titles to stream it. If you want to download the books, please use the Windows 10 app." 

Like you said, since I hadn't yet used any app to log into my Audible account, there was no "Download" button next to the books in my library. So I installed the Audible Windows 10 PC app on my husband's PC and downloaded the files. And now when I view my library, I see a little check mark next to the titles I downloaded via PC. 

You can see the notice and the "Downloaded" check mark in the image below shown with a red arrow.

<img width="1020" alt="audible_japan_1" src="https://user-images.githubusercontent.com/62157783/76702491-58afab00-66db-11ea-944e-3fa16780827c.png">

But the Account Details still show no Software Verification section as you can see below.

<img width="1028" alt="audible_japan_2" src="https://user-images.githubusercontent.com/62157783/76702890-792d3480-66de-11ea-89ce-c29dda89fe5e.png">

> If you download them another way, dragging and dropping .AAX files onto OpenAudible should work.

I reinstalled OpenAudible and dragged and dropped the downloaded files. This time it worked, I could convert the files into mp3. I don't understand why it didn't work the first time as I mentioned in the first post. Maybe my library status was still 'connected: yes' and I was actually viewing my Audible library through that connection, mistakenly thinking that those were the files I had manually imported? I don't remember.

Anyway, thank you very much for your help ^^

**Comment by jun1perus** [comment]
On a different note... OpenAudible created a folder entitled "javasharedresources" in my Home Folder. Inside, there is a text file as large as 67MB. Can I delete this folder or move it elsewhere?

I thought this issue didn't merit a separate entry, so I'm posting it here.

**Comment by openaudible** [comment]
Thanks for the update. Its unfortunate that you aren't able to download from OpenAudible but at least the drag and drop works. Will update the documentation.. It seems very strange that on a Mac Audible tells you to use Windows 10 to download the book... 

I've never seen a javasharedresources folder. I didn't think the java8 I include with OA would do that. 
A quick google says its ok to delete that folder if no apps are using java. 

Thanks for the feedback.
