### ISSUE TITLE
Highlight and Notes export

### ISSUE THREAD

**Issue by samjohn24** [openaudible/openaudible#292]
Hi all,

Is there a way to export highlights or notes to any json or csv file? 

Regards,
Sammy

**Comment by openaudible** [comment]
No plans for that. What are some books that contain additional downloads?

**Comment by samjohn24** [comment]
No, they aren't. I mean the bookmarks or notes you add to audiobooks while  you are reading in any Audible app.

**Comment by openaudible** [comment]
Oh... Unable but thanks for the suggestion...
