### ISSUE TITLE
Where's the latest code?

### ISSUE THREAD

**Issue by alehel** [openaudible/openaudible#293]
Hi, I'm a very happy user of the openaudible and came here to take a look at the code to see if there was anything I could contribute. I was suprised to see the comment in the readme that the code here is v 1.1.8. Is there a reason this repo is outdated? Is the code being hosted somewhere else? Moving away from being open-source?

**Comment by openaudible** [comment]
Had practically no useful code contributions. New code is on private repo. Keeping all options on the table.
