### ISSUE TITLE
"Split By Chapter" option in audiobook context menu

### ISSUE THREAD

**Issue by alehel** [openaudible/openaudible#295]
At the moment if one wishes to split an audiobook by chapter one has to go to File -> Split By Chapter. One then needs to find the audiobook in the filesystem. It would be convenient if the Split By Chapter function was also available as part of an audiobooks right-click menu. Then I would simply specify where to store the split files, saving me from having to browse the filesystem for the original mp3.

**Comment by openaudible** [comment]
Nice idea. OK.

**Comment by openaudible** [comment]
Added to 1.6.6

**Comment by alehel** [comment]
Works great. Thanks!
