### ISSUE TITLE
Cannot download a pre-paid book

### ISSUE THREAD

**Issue by CrustyApplesniffer** [openaudible/openaudible#296]
Hello,

I'm using open audible with a french account and today, when I refresh my list, I saw un red LED before  the title of a new book.
When I click on it the state of this book is : "no mp3 or AAX or download link".

I know this book is available because I downloaded it with the Audible App.

I try to refresh the book information but the state still remains the same.

The only difference I can see with other books was that it was the first book I pre-paid.

I could send you a bug report from open audible application if you want further information.

**Comment by openaudible** [comment]
When you look at the book in your library view using the audible browser, is there a "download" button? That is what gets scraped.. Are you sure it shows up when you do a library scan? 

That button can also be manually clicked to start a download.

**Comment by CrustyApplesniffer** [comment]
There is a 'download' button.
Moreover, today, I bought a new book and it has the same red LED :(

**Comment by openaudible** [comment]
Hm. When you do a library rescan or even just visit the library page that shows the new book, OA should get the new download link and make it available. Strange... I think the bug-report feature is now working, so you could try to: quit, restart, quick scan library, check that the book is in the first page of the library view.. and then send a bug report (tools menu) with the name of the book and issue 296.

**Comment by openaudible** [comment]
Also, you didn't say what happens if you click the "Download" button using the OA browser.

**Comment by CrustyApplesniffer** [comment]
![image](https://user-images.githubusercontent.com/37656975/77832256-00de5e80-7135-11ea-8fbf-2fb1f3eed2b7.png)


If I click on the download button, it switches to a page (see below) and download nothing
![image](https://user-images.githubusercontent.com/37656975/77832202-89103400-7134-11ea-8c45-90e530c0780f.png)

**Comment by CrustyApplesniffer** [comment]
Bug report sent

**Comment by CrustyApplesniffer** [comment]
Still the same with version 1.6.6
Could you re-open the issue ?

**Comment by openaudible** [comment]
I can't tell what that says-- I don't speak French,
But for the software to work, the AAX file must be able to be downloaded using the Audible Download Manager... You could ask support how to download the AAX file for that book.

It does appear that Audible is making changes to how books are accessible and to their library layout. And I don't have access to French audible.

**Comment by openaudible** [comment]
Can you try version 1.6.7? That fixes the NullPointerException. Manually clicking the download button may be required.
