### ISSUE TITLE
MP3 conversion doesn't work?

### ISSUE THREAD

**Issue by maherobaid15** [openaudible/openaudible#3]
Whenever I try to convert to MP3 it just gets stuck at `Converting frame= 1 fps = 0.0 q = 0.0 size =  1kB`

Console logs: https://hastebin.com/abadakefey.rb

**Comment by openaudible** [comment]
On line 37 of your paste is the ffmpeg command line that is supposed to convert the file. Can you try running that from the command line? It may take up to 10 minutes to convert. Have you tried converting your smallest audio book?

**Comment by openaudible** [comment]
Pushed a code change. Please re-open if not fixed in next release.
