### ISSUE TITLE
UX, It's not entirely clear if you're supposed to use the browser to download the audiobooks or if the app can just sync your full library.

### ISSUE THREAD

**Issue by chamunks** [openaudible/openaudible#30]
It doesn't seem clear initially whether or not the user is expected to use the [SSB](https://en.wikipedia.org/wiki/Site-specific_browser) included in OpenAudible to download the audiobooks manually then process them with OpenAudible itself.  

Granted I'm still trying to get OA to authenticate in the first place properly.

**Comment by openaudible** [comment]
Authentication is an area that is tricky. We are working on a solution. 
But, the idea is you log on with the browser, switch back to OA, then hopefully OA can use the cookies to automatically get your books. You don't download them from the included browser. Keep an eye out for new versions..
