### ISSUE TITLE
splitting by chapter cover art

### ISSUE THREAD

**Issue by abzman** [openaudible/openaudible#303]
I don't know if this is expected behavior, but when splitting by chapter the first file gets the cover art and all subsequent files have none.  I didn't look too hard for a setting and just fixed it so all my chapters have the same cover art in a different program, but I consider this an issue.

**Comment by openaudible** [comment]
Hadn't noticed that. Thanks for finding that. Did you by any chance find the ffmpeg command that keeps the video? It looks like cutting (adding a start time >0 seconds) causes the "video" to be skipped-- as the cover art is treated as "video" of length one frame... 
Anyway, will take a stab but low priority at the moment.

**Comment by openaudible** [comment]
Fixed in 2.0.3.
