### ISSUE TITLE
Unable to convert any books to mp3

### ISSUE THREAD

**Issue by TheronNightStar** [openaudible/openaudible#304]
I imported 48 books that I transferred from my android device to my computer (Win10). They imported just fine after I changed the file extensions to .axx from .axxc. The issue is that none of them will convert to mp3. I get one of three errors. Codes 1, 3, and 69. An example of each is attached.

Edit: OpenAudible version is 1.6.6

[Code_1.txt](https://github.com/openaudible/openaudible/files/4410693/Code_1.txt)
[Code_3.txt](https://github.com/openaudible/openaudible/files/4410694/Code_3.txt)
[Code_69.txt](https://github.com/openaudible/openaudible/files/4410695/Code_69.txt)

**Comment by openaudible** [comment]
AAXC files are not currently supported by ffmpeg. You can google "aaxc" "ffmpeg" or read the ffmpeg-devel mail list to see the progress.

**Comment by TheronNightStar** [comment]
Disregard. I found my solution elsewhere. It is an issue with the android format, not OpenAudible. Once I downloaded the file on the computer directly, it worked. I'm closing this of my own accord.
