### ISSUE TITLE
unable to see a book in openaudible library

### ISSUE THREAD

**Issue by Butterfly-Dragon** [openaudible/openaudible#307]
this book...
https://www.audible.com/pd/2nd-Gen-Audiobook/B07Z45GHWK

is present in my library (ordered by purchase date):
![image](https://user-images.githubusercontent.com/33538906/78376669-ed1c7780-75ce-11ea-9854-fe43766c8e47.png)
![image](https://user-images.githubusercontent.com/33538906/78377038-66b46580-75cf-11ea-9d3e-0187e4670bfe.png)

however... here, as seen ordered by purchase date it is not shown
![image](https://user-images.githubusercontent.com/33538906/78376747-0c1b0980-75cf-11ea-9568-33382e869c3c.png)

it does not even show up when ordered by title or anything...

This leaves me a bit confused.

**Comment by Butterfly-Dragon** [comment]
also... uhm.... i do have the download button:
![image](https://user-images.githubusercontent.com/33538906/78395605-100a5400-75ee-11ea-820d-f6e46810e9ff.png)

**Comment by openaudible** [comment]
If you click the download button and get a NullPointerException in the OA console, that's our bug. If you get an image that says open in the Audible App, that's an Audible issue we don't have a fix for.

**Comment by Butterfly-Dragon** [comment]
hmmmm.... i double checked something... went on a shopping spree to see which books would be affected. Bought around 30 books.

I can download any book i bought march 15th and before, any book bought march 27th and after apparently does not exist according to openaudible. Regardless of publication date.

Upon asking for a full library refresh it says "completed" immediately, even though i have nearly 70 pages of books to sift through... https://www.audible.com/lib to me looks like this:
![image](https://user-images.githubusercontent.com/33538906/78409669-8c129500-760a-11ea-915c-b3b6db102bf0.png)


Also upon login it always tries to login to audible.it instead of audible.com might be unrelated but might be related, i live in italy, but my library is on audible.com

**Comment by Butterfly-Dragon** [comment]
oh, and to answer your remark about `NullPointerException` it... literally does nothing. As in... if i click the download button in the openaudible browser it's as if i clicked no button at all.

**Comment by Drudoo** [comment]
Do you have the console open to look for the `NullPointerException` ? I have the same issue: 

1. Live in scandinavia and the browser redirect to audible.co.uk instead of audible.com. I press the 'go to audible.com' button and login. 

2. Upon going to my library view, i open the console (file -> console) and press the download button. 

3. Every book i have gives the `NullPointerException`. 

> Upon asking for a full library refresh it says "completed" immediately, even though i have nearly 70 pages of books to sift through... https://www.audible.com/lib to me looks like this

This is a bug currently, see #306

**Comment by Butterfly-Dragon** [comment]
@Drudoo yeah, i did as you said, i did not know what they meant with "console" but yeah, it's a `NullPointerException`, allright.

**Comment by openaudible** [comment]
Ok. 1.6.7 will fix the NullPointer bug so you can download books. Main issue of #306 about parsing the new library format hasn't started except to alert the user.

**Comment by Butterfly-Dragon** [comment]
👍💖

**Comment by Butterfly-Dragon** [comment]
seems like this error is a duplicate of #306 so you can close this as a duplicate, if it is not... i'll re-open it 😅

**Comment by openaudible** [comment]
Hi Butterfly, Thanks for the long report. We'll track the new audible changes in other issues.
