### ISSUE TITLE
Suggestion - Ability to designate which store to open

### ISSUE THREAD

**Issue by livtin** [openaudible/openaudible#308]
It would be great to be able to designate the store to open when logging in.
My account is with Audible.com as I became a member before there was a Canadian store.  Sometimes the integrated browser does not offer the option of changing the store.
It would also be nice if credentials could be stored and used automatically.

**Comment by Drudoo** [comment]
I don't think this is an issue openaudible can fix. It happens in most browsers too, without a clear way to fix this.

**Comment by openaudible** [comment]
We do save the "region" you are last connected to.. But Audible may decide to redirect you back to your regional site if they detect your IP address is out of the region.
