### ISSUE TITLE
BUG, INSTALLATION, weird hosts not dialogues spamming the screen and maybe being a symptom of why I cannot use OpenAudible

### ISSUE THREAD

**Issue by chamunks** [openaudible/openaudible#31]
Every time I try to log in I get about 15 separate dialogue boxes that are complaining about hostnames that don't exist. 
## First screenshot
![image](https://i.imgur.com/FP4SD9Y.png)

## Second screenshot
![image](https://i.imgur.com/OUZHgTj.png)

## Third screenshot
![image](https://i.imgur.com/QX1aXfL.png)

# Disclaimer
These go on for a while.  I'm going to attempt a different DNS provider locally but I thought that I'd get the ball rolling on attempting to get a fix started if you knew something about what might be going on here.  At the very least documenting the problem is good.

**Comment by chamunks** [comment]
# AdGuard DNS
is what was getting in the way of those domains being resolved basically it null routes or at least fails to resolve DNS queries to domains like DoubleClick.net and other trackers.

## New Screenshot
![image](https://i.imgur.com/v5d9pmD.png)

I really appreciate your time and effort on this app and if I can get it to work I might not actually cancel my Audible subscription I just hate buying things that I never really own and I want to not use that battery destroying Audible app on my phone.  Seems that it burns about 100x more battery than pretty much everything else I have.  I really want to be able to justify giving the creators money via this means its just this one last major issue.  Its why I cancel my audible sub every time I don't get a deal from them.

**Comment by chamunks** [comment]
On a separate attempt, I've gotten different results now.

It's asking me to uncheck the checkbox for "Check for Audible Download Manager" when it's already currently disabled in my account.

## Dialogs 
![Image](https://i.imgur.com/eszq5SQ.png)

## Checkbox shown as unchecked.
![Image](https://i.imgur.com/HTudPCW.png)

**Comment by openaudible** [comment]
Something is buggy. As far as I know, OA doesn't put up the error messages--they may be coming from the browser code, which isn't mine. Those are supposed to be ignored. Do you see anything in the Console when you try to browse? Its possible an error would be logged that shows where the alert is coming from. Ad blocking DNS is probably the cause, but it still is bad behavior. Not sure how to reproduce.

**Comment by openaudible** [comment]
Give 1.2 a try. If any problems, please create a new ticket. The new 1.2 has a whole new way of connecting. Having a DNS blocker is not supported-- you may need to allow domains that are blocked.
