### ISSUE TITLE
Enhancement Requst

### ISSUE THREAD

**Issue by tbgray** [openaudible/openaudible#312]
sorry if this isnt the appropriate forum but a dark option would be awesome. 

Sincerely,

An OpenAudible Donor

**Comment by openaudible** [comment]
What platform are you on? If you set your OS to dark mode, OA may turn on. We use the default system colors. It doesn't look great.. but I've done a quick test on windows and linux. You might also be able to google Eclipse SWT Dark Mode and see if you find a way to turn it on.

**Comment by tbgray** [comment]
Using windows10. I'll see if I can figure out one of those.

Thanks,
Tyler

**Comment by Butterfly-Dragon** [comment]
i have windows 10 and dark theme, it's very very white. 😂

**Comment by openaudible** [comment]
Its on the feature request list.
