### ISSUE TITLE
Missing dependency "org.w3c.dom.ElementTraversal"

### ISSUE THREAD

**Issue by mcgarrah** [openaudible/openaudible#314]
I'm working thru setting up and running under IntelliJ on Windows 10 64-bit. It's been a few years since I've used IntelliJ and Maven along with Java to any depth. After importing the project and trying with OpenJDK 8 then I moved to just the easy download inside IntelliJ to OpenJDK 14, I'm getting a missing dependency with both.

Here is the build error:
```
C:\Users\mcgarrah\IdeaProjects\openaudible\src\main\java\org\openaudible\audible\AudibleScraper.java
Error:(375, 30) java: cannot access org.w3c.dom.ElementTraversal
  class file for org.w3c.dom.ElementTraversal not found
```

I'm pretty sure I just need to add it to the pom.xml file and reimport if I can figure out which library to add.

Hope this is a quick and easy one for someone that has been in the Java world deeper recently. I'm still digging around on it and might figure it out myself.  I'll post if I do.

Thanks.

**Comment by mcgarrah** [comment]
So I have a workaround but not sure if this is a good one.

Adding the following to the pom.xml and a quick reimport gets me around the build issue.
```
        <!-- https://mvnrepository.com/artifact/xml-apis/xml-apis -->
        <dependency>
            <groupId>xml-apis</groupId>
            <artifactId>xml-apis</artifactId>
            <version>1.4.01</version>
        </dependency>
```

Adding version 2.0.2 led me on a merry chase and it continued to fail building. Adding the most current library below fails with the same error.
```
        <!-- https://mvnrepository.com/artifact/xml-apis/xml-apis -->
        <dependency>
            <groupId>xml-apis</groupId>
            <artifactId>xml-apis</artifactId>
            <version>2.0.2</version>
        </dependency>

```

**Comment by openaudible** [comment]
Yeah, that's a result of using java 14 to build our older code. You could build using the JDK version 8, which is what we do for our releases. But adding dependencies for java 14 should work like what you've done. Because we release a binary, we use an older java to ensure compatibility with older systems that may not support java 14.
