### ISSUE TITLE
Official AppImage, Flatpak, or Snap?

### ISSUE THREAD

**Issue by eduncan911** [openaudible/openaudible#315]
Hello!

Could you package up and release official appimage or flatpak?  I tried searching but there doesn't seem to be any created.

There are many of us not allowed to run JVMs nor install Java's JVM.  An AppImage or flatpak would self-enclose all of the required dependencies allowing it to run on anyone's machine, and **even as non-root**.

I don't think Snap is a good idea as it limits its scope. But, having all three available would open this application up to many different install types.

Thanks!

**Comment by openaudible** [comment]
I haven't looked at appimage, flatpak but will. Wish those were supported by our installer.. especially the non-root installer. (At least it runs as non root!) 

There is command line support for chocolatey and yay.. but we don't support them or do the install scripts. Adding as a feature request.

**Comment by openaudible** [comment]
Both AppImage and Flatpak look great. Getting a non-root drag and drop app would be nice.
 
I will support it if I can find time to build and test it. Or if anyone wants to volunteer to build it.. I can assist.

**Comment by eduncan911** [comment]
Yeah, I'm trying to find the time myself to give it a go.

There's a few builders that can be incorporated into Travis/CICD builds I was going to try.

Specifically, since you already create a `deb` file, a build script can extract the package into the appimage, install your Java of choice within it, and call in the day.

There's various tweaks to appimages that can come later, like desktop files and search indexing (for those that use dmenu or alike).

**Comment by openaudible** [comment]
Thanks for offering to help! 

I did see something about a .deb to flatpak script. But I am pretty sure our .deb hard codes paths like /opt/OpenAudible, which is an install4j convention. I think we can do better.

I'll post something here when I have a linux launcher that does a first pass at getting all the files into one .tgz file (appliaction jars, support directories, desktop icon, run script, jre.). Hopefully with 2.0.1 update. The only tricky part about my app is you need to link to the correct version of the "swt" jar that has native libraries for whatever system its running on and a few things on the java command line. I'll post a sample.

Finding a similar java app with simple file structure would be nice.  

I don't use Travis. But OK to run a command line on linux or docker to build something.

**Comment by openaudible** [comment]
FYI, I got AppImage to work. Watch for a OpenAudible-x86_64.AppImage next release. Seemed like the best choice... Will close when released.

**Comment by eduncan911** [comment]
I prefer appimage personally.  Nice!

**Comment by openaudible** [comment]
Posted our first AppImage for 2.0.1. Please reopen or let me know if you see any issues.
Looks pretty cool.
