### ISSUE TITLE
notification (demo limitation discussion)

### ISSUE THREAD

**Issue by lgkahn** [openaudible/openaudible#316]
Need to put a notificaiton on main landing page that tyhe new version 2.0 hobbles features that are no longer free such as importing books etc. (which is the only way the app is useable now with audible in the usa). In addition, there should be an option to stop the prompt to update everytime.

**Comment by openaudible** [comment]
I added another strong "Note:" under the Download header.

**Comment by openaudible** [comment]
Edited the title so anyone who wants to chime in about the commercial change can add to this issue.

**Comment by Geordon** [comment]
What features are not available in version 2.x that were in 1.x?

**Comment by lgkahn** [comment]
Import aax


What features are not available in version 2.x that were in 1.x?

**Comment by JayThirtySeven** [comment]
I updated and now I can't convert books to mp3; it says that's not supported by the demo version. What exactly is going on? There should be a clear and complete explanation of what the program can actually do for free and what you get by paying.

**Comment by lhanson** [comment]
I'm also confused by what isn't working because I haven't paid vs. what's an actual bug.

**Comment by Geordon** [comment]
Basically, all that the demo version does is download the library.  And, 1.6.7 has been crippled so that it refuses to do anything.  All it does is pop up a box saying that it's not compatible with the current Audible page.  When you click the button to dismiss the box, 1.6.7 closes.

**Comment by openaudible** [comment]
@Geordon OpenAudible 1.6.7 should not close.. it should still allow you to download books and convert them. 1.6.6 should is also available in releases and won't give the warning, but has incompatibilities.

**Comment by lgkahn** [comment]
with earlier version ie 1.6.6 1.6.7 insntall the windows audible player not the streamer version.. Then download your files..
yiu will find them under the audible locationi search for .aax.. then you can import these via the import fx in  1.6.7 and them convert/split etc.

---- Original Message ----

**Comment by tsuliwaensis** [comment]
I think it would be very helpful to clearly list all the features that are considered "Free" and "Pro". It would help users make a decision on downloading and/or paying. Currently,  users have no idea what they get and don't get which can be frustrating when a feature (e.g., importing) a user wants to try is not part of the free version.

**Comment by openaudible** [comment]
The following features are disabled in version 2.x until registered.
Export_Web_Page:
Export_Book_List:
Import_Books:
Split_By_Chapter:
Split_Selected_Book:
Convert Book:

All of those features are in the 1.x version. 

The 1.x version is not able to scrape your library from the new style audible library.

Some people use are using the 1.6.x versions along with the 2.x demo versions to get all of the functionality for free, with a little more work. 

The source code for 1.1.8 is also available to be forked and modified to work with the new library formats. 

And obviously there are other book management programs and conversion tools.
