### ISSUE TITLE
2.0 Bugs and Questions

### ISSUE THREAD

**Issue by openaudible** [openaudible/openaudible#317]
Post any bugs or questions about 2.0 and I'll answer them.
Issue 316 can be used to discuss the demo limits. 

Some early reports that downloading books is not working for some users. Need to identify if those books are available to download using the audible download helper or only available in aaxc format (which isn't supported by ffmpeg.)

Also known issue of "date purchased" column removed. Working to add that back in once we scrape data from a new location.

**Comment by goldharv** [comment]
No OpenAudible windows under XQuartz

I have been trying to get OpenAudible up on a VMWare Fusion 1.5.3 virtual Ubuntu 18.04 server running under OSx 10.15.3. I have it running directly under OSx, but when I run it via an SSH session logged into Ubuntu, I get:
OpenAudible 
Apr 12, 2020 2:06:05 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 2.0 for gtk swt 4930 jvm 11.0.6 file charset UTF-8

On Ubuntu, for the last few OpenAudible releases, I have seen the primary OpenAudible window, but when I try to log into Audible, the web interface is not usable.

The 2.0 version does not show any windows. For what it's worth, I normally run with several X windows, Firefox and Visual Slick Edit up. I test with xeyes and xclock.

**Comment by milegrin** [comment]
OpenAudible 2.0 on Ubuntu 19.10
Quick library sync work
Full library sync gives : "Unable to connect right now.  Try logging on to Audible from this web page and try again"
![image](https://user-images.githubusercontent.com/3263146/79096354-3605c600-7d5d-11ea-84bd-b9440e6e3f9c.png)

**Comment by milegrin** [comment]
OpenAudible 2.0 on Ubuntu 19.10 & Windows 10 & Windows 8
 Purchase date column is no longer present so unable to only download latest purchases (OpenAudible is only used as a download client)

**Comment by openaudible** [comment]
@milegrin What does the browser show when you see that message? Can you copy and paste from the console (CTRL-E)
Purchase date is coming back.

**Comment by lhanson** [comment]
I just downloaded 2.0, connected to Audible, did a "Full Library Sync", but I only see 20 books in OpenAudible even though I have many more than that.

**Comment by openaudible** [comment]
@lhanson Does your library URL contain /lib or /library ? 
I have one report of this on a Mac that had the old style /lib library view. Looking for a solution.

**Comment by lhanson** [comment]
The URL that comes up in the browser when I "Connect to Audible" is https://www.audible.com/library/titles. This is on Linux FWIW.

**Comment by openaudible** [comment]
Ok. That is a top priority for 2.0.1. If you watch the browser when you do a full resync, do a lot of pages flash by or does it stop after one page? If you want, you could quit and relaunch OA, connect to audible, and do a full resync. Then send a bug from the About menu.. reference #317 not getting all books.

**Comment by KeinNerd** [comment]
I love it. And have buy'd a licence. Keep up the good work. But one thing. Please store the Login Credentials so we dont need after restart to login again and again.

Thank you!

**Comment by mcgarrah** [comment]
On Windows 10 with OpenAudible 2.0 with a "Valid" purchased license.

I cannot get the "Audible Download Manager" (ADM) to work in the browser. From documentation, I can see that in the past, I should be able to hit the Download button and it use the ADM to get the files to my computer. I can get a full list of my titles now in 2.0 which is a step in the right direction.

Downloading the Audible App from the Microsoft Store let me pull down the AXX files and I can process them if I import them manually. That is not ideal and interested in how to get the integrated download and convert that appears to have worked earlier.

Thanks.

**Comment by openaudible** [comment]
@mcgarrah What happens if you click on a download button in the library page or on a book info page when logged in? Did you check your Audible Download settings: https://openaudible.org/settings.html
What region are you in (US,DE,FR?)

**Comment by mcgarrah** [comment]
> @mcgarrah What happens if you click on a download button in the library page or on a book info page when logged in? Did you check your Audible Download settings: https://openaudible.org/settings.html

It was originally set but I just unchecked it, closed OpenAudible, reopened and relogged into Audible checking the value to be off. Retried a Full Sync and it failed... thought about it and "deleted all the content" then shutdown again and reloaded.

On a second full resync, I'm now seeing a State of "Ready to download" for the first book.  So a bad sync earlier had to be cleared out.

Everything looks good now.  Thanks for the feedback.

> What region are you in (US,DE,FR?)
I'm US.

**Comment by eragon921** [comment]
On Windows 10 running 2.0 I am unable to export to an HTML page. When I select the file menu the Export as Web Page option is greyed out. The Export as Book List for CSV and JSON still work though. Any thoughts? This was an issue with 1.6.4 as well for me. I am running a fully licensed version 2.0.

**Comment by openaudible** [comment]
@eragon921 Fixed export as web in 2.0.1. Thank you!

**Comment by eragon921** [comment]
> @eragon921 Currently OA only exports books that have an associated MP3. Make sure you have at least 1 MP3... We may change that behavior though..

@openaudible That makes sense then since I only maintain M4B editions of my books and not MP3s!

**Comment by egauthier** [comment]
I was only getting 19 titles downloaded, then I opened browser window and switched the number of items to show to 50, I now get 48 items downloaded.

Mac OS

-Eric

**Comment by mdbookworm** [comment]
Seems to be downloading only the last part of multi-part books. I.e, for a couple books it downloaded only Part 2, on another one only Part 4.

**Comment by openaudible** [comment]
@mdbookworm We typically only attempt to download the full book. If this keeps happening in 2.0.1, let me know.. 

2.0.1 fixes the bug where some versions only get the first page of books. Also fixed a number of other bugs. 

Closing, but please create a new issue if you find bugs in 2.0.1.

**Comment by aureusphoenix** [comment]
Does 2.0 now support books that have multiple parts? In the old version, those did not work at all for me. I would be willing to buy 2.0. But only if this works now.
