### ISSUE TITLE
purchasing question

### ISSUE THREAD

**Issue by danielb2** [openaudible/openaudible#319]
It's unclear if this $12 is tied to a specific version of this is a lifetime license.  Can you please clarify ?

**Comment by openaudible** [comment]
Any licensed version can be used forever. The license includes free updates for 1 year.

**Comment by danielb2** [comment]
I suggest making that very clear during the purchase. I'm far less interested in a subscription model, which I consider such a short-term license to be, more or less.

**Comment by openaudible** [comment]
Updated https://openaudible.org/purchase
