### ISSUE TITLE
Convert to MP3 grayed out, and other opts too

### ISSUE THREAD

**Issue by stamster** [openaudible/openaudible#32]
I have imported AAX file from Android device Audible app. Import on OpenAudible does seems to work, all info is there, image of the artist etc. But play, convert o MP3 etc. opts are simply N/A, e.g. grayed out.

I have NOT connected to Audible service, is that required?

Info: using latest GNU/Linux release of the app.

**Comment by openaudible** [comment]
Your books should show in the table. The stats in the upper left should say To Convert: N (where N is not 0.) Selecting a book in the table should allow you to right click or select the "convert". Open the console window and see if you spot any errors. A screenshot or paste of console messages if still having issues.  I admit to rarely testing linux version.

**Comment by stamster** [comment]
Hello @openaudible 
Thanks for response.

Nope - it' 0 to convert...

console:

```
Sep 17, 2018 6:00:16 PM org.openaudible.desktop.swt.manager.AudibleGUI checkFFMPEG
INFO: using ffmpeg version 2.8.1-static http://johnvansickle.com/ffmpeg/  Copyright (c) 2000-2015 the FFmpeg developers
built with gcc 4.9.3 (Debian 4.9.3-4)
configuration: --enable-gpl --enable-version3 --disable-shared --disable-debug --enable-runtime-cpudetect --enable-libmp3lame --enable-libx264 --enable-libx265 --enable-libwebp --enable-libspeex --enable-libvorbis --enable-libvpx --enable-libfreetype --enable-fontconfig --enable-libxvid --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libtheora --enable-libvo-aacenc --enable-libvo-amrwbenc --enable-gray --enable-libopenjpeg --enable-libopus --enable-libass --enable-gnutls --enable-libvidstab --enable-libsoxr --enable-frei0r --enable-libfribidi --cc=gcc-4.9
libavutil      54. 31.100 / 54. 31.100
libavcodec     56. 60.100 / 56. 60.100
libavformat    56. 40.101 / 56. 40.101
libavdevice    56.  4.100 / 56.  4.100
libavfilter     5. 40.101 /  5. 40.101
libswscale      3.  1.101 /  3.  1.101
libswresample   1.  2.101 /  1.  2.101
libpostproc    53.  3.100 / 53.  3.100

Sep 17, 2018 6:00:21 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: http://openaudible.org/swt_version.json?platform=linux&version=1.1.7
```
ss:

![openaud_toconvert_0x00](https://user-images.githubusercontent.com/12804479/45634900-e3422a80-baa3-11e8-822b-e5350e489bdc.png)

**Comment by openaudible** [comment]
That is because the book has already been downloaded (AAX) and converted to MP3. Next action is "Show MP3" or File: "Export Web Site" 
If "Play" may be grayed out because on linux there is no "open mp3 file" command that reliably does anything. Show MP3 should work, but is also problematic on linux -- as there is no universal "explorer" or "finder". 

Feel free to re-open if you have suggestions or not the right answer.
