### ISSUE TITLE
Keyboard shortcuts not working

### ISSUE THREAD

**Issue by Butterfly-Dragon** [openaudible/openaudible#320]
For some reasons, once i click on a book in the list of books, i cannot download it.

I have to click on the summary or on the audiobook info zones before the `CTRL`+`D`  shortcut works to download said book..

When selecting multiple audiobooks this is even worse... as the only way to download books is to go through the actions menu.

This is also true of the `CTRL`+`R` shortcut to do a "quick library refresh"/"update book info" (i suppose they should be context sensitive, but it always ends up doing a full library update) and the `CTRL`+`L` shortcut to open a book on audible

once gone through the actions menu the shortcuts will work for "a while" (meaning an indeterminate/unknowable amount of time which i have been unable to reproduce consistently) even after clicking on the list of books. But they will stop working and will re-start working only after the actions menu is called up again.

**Comment by openaudible** [comment]
Are you on Linux or Windows?

Sometimes Eclipse Standard Widget Toolkit can be finicky. I can't seem to reproduce this, except on my mac, sometimes I start and the whole menu doesn't work until I click on the desktop and back to OA. I've tried to fix it, but gave up. 

There is a org.eclipse.swt.[platform].jar file in the application files that can be updated to newer (or older) SWT library by replacing that file. Different swt libraries are available to download at https://eclipse.org/swt ...  

You can also watch the console (CTRL-E) for errors being reported when you click menus.

**Comment by Butterfly-Dragon** [comment]
I am currently using windows.
I will now take your suggestion and see what happens, describing step by step.
• starting openaudible
• between each step i am switching here to describe what i am doing, so take this into account if task switching of the `ALT`+`TAB` variety comes into play
• got told version 2.0.1 is here so clicking `OK` and moving on.
• get redirected to internal browser (NOTE: please do not do that. Open update links on an external browser where i can download things and recover them  after the download for later use.)
• copying download link and downloading elsewhere. Continuing with version 2.0
• Maximizing original window since it looks like this:
![image](https://user-images.githubusercontent.com/33538906/79671157-7daaa880-81c8-11ea-83a8-0794137e4316.png)
• `CTRL`+`K` to connect open audible to the audible.com site.
• `CTRL`+`E` to see the log. i should have done this sooner, but i though it would be logging stuff anyway. I see i was right, will add the log as a text file later.
• `ALT`+`C`, `F` for full library update.
• clicked on the first book in the list
• `CTRL`+`D` started downloading the book
• cancelled job
• Clicked twice on "release date" to get to the latest book published. (Note: i usually would click on the ordering by "date bought" which is not present right now.
• clicked on the first in the list
• `CTRL`+`D`-ed a few times buuut no results now.
• there is no mention of any action inside the log at this moment.
• clicked on the second most recent book published.
• `CTRL`+`D`-ed a few times buuut no results again.
• `ALT`+`A`, then `D` to download downloads the book.
• `ALT`+`A`, then moved down to `cancel job` with the arrow keys correctly quits the job.
• switching to the log, i see the log has updated a lot  right now the last line i had seen has vanished.
• selecting everything in the log, putting it into a `TXT` file and adding it right now. Will not "censor" any data because (unfortunately) i do not have time to parse the entire log and see what data i am sharing. I am putting my faith in you people not sharing any personal data of mine inside this log, besides the info i just shared here anyway and the exact specifications of the events involved.
[log.txt](https://github.com/openaudible/openaudible/files/4497739/log.txt)

Now closing and updating to version 2.0.1 doing similar steps, but given that you were unable to reproduce the error, i am not expecting this to be solved, because if it was solved... it was by mistake.

Due to crappy connection the download is still only part-way done 65MB over 153

Sooo.... assume it did not work, unless i specify this time did work.

From what i did apparently it's the "reordering" of the books that stops the direct short cuts from working.

And the `ALT` shortcuts did still work.

**Comment by openaudible** [comment]
OK. I appreciate the feedback. Unfortunately unable to find any problems. Had an emergency bug to fix today. Good idea about downloading in external browser, but with 3 platforms I always worry one or more linux varieties won't know how to open a web browser.
