### ISSUE TITLE
special edition

### ISSUE THREAD

**Issue by ucs01** [openaudible/openaudible#321]
when the program converts, I want it to convert as the code of the book, not the title of the book. Like B075KJDST9.mp3 

I am ready to pay a license for this special version. Can you make this version for me?

**Comment by openaudible** [comment]
We used to save the file as the product ID.. but natural sounding file names make more sense for most people. However, the code is there.. and could use the ASIN.  Will consider it a feature request.

**Comment by ucs01** [comment]
I want to name it asin or product_id after converting audiobooks. and when I import mp3s that were made before, I want the name to change with asin code or product_id.

**Comment by openaudible** [comment]
And to be clear.. are you offering to buy a $12 license if I implement this... or were you interested in commissioning this feature? If so, you can send an offer to openaudible at email.tg

**Comment by openaudible** [comment]
Noting as a feature request.
