### ISSUE TITLE
incomplete download? mp3 file is 10 hours, should be 33

### ISSUE THREAD

**Issue by jaymanaz** [openaudible/openaudible#323]
i have a licensed version of 2.0. I try to download "the chronicles of narnia adult box set" and convert to mp3. i only get 10 hours of the audio. i also deleted the aax and mp3 and attempted again, and got the exact same result.

**Comment by openaudible** [comment]
OA uses an algorithm to figure out which download to use to find the "full book" versus all of its parts. Its possible the naming convention for the downloads has changed. I'd be interested in fixing this. If you (or someone with this bug) can send a bug report, we'll fix it.

Quit and start OA. Log on to audible. Page through your library page until you see the book in the list of titles. Then click the download button for the full book. From the About menu, submit a bug report with issue 323 and the name of the book. (From the About menu.) That will send the html for your library page and the console output.. and we can look at the download data and figure it out. 

Alternately, you could do a page source in any browser, get the page source, and send a snippet or the whole file to us. (or post the snippet here, removing any references to user id's.)

**Comment by jaymanaz** [comment]
I'm thinking this is an issue with conversion. I'm left with a 10 hour file again. The OA window during conversion should progress of XX of 33 hours, so it was seeing the right length in the AAX. Thoughts?

**Comment by hobhole** [comment]
Same is happening to me. I'm getting the second half of the book. Will try the above steps later.

**Comment by hobhole** [comment]
Yes a partial book is getting downloaded. When I manually download the full book via audible web site, then convert that aax to mp3 in openaudible, all is fine. The book was The Quantum Magician and I got only part 2 starting at chapter 41.

**Comment by jaymanaz** [comment]
how do you use the adh file to download the aax manually?

**Comment by aarmora** [comment]
@openaudible I've submitted a bug report as you suggested. Did the eye of the world and it cut off at 200mbs. Thanks!

**Comment by openaudible** [comment]
A fix is in progress. Please stand by for 2.0.2 with instructions on repairing this..

**Comment by openaudible** [comment]
Thank you for reporting this. This was part of the new library parser and affected a lot of books that were split. The 2.0.2 should fix it... Unfortunately you may need to re-download and re-encode some  of your books that you converted with 2.0 or 2.0.1.  Closing this for 2.0.1, but opening #325.
