### ISSUE TITLE
2.0.1 MP3 quality and Format question

### ISSUE THREAD

**Issue by JoshFink** [openaudible/openaudible#324]
Hi, I just purchased a license yesterday and I'm using this on my Mac. I had a question about MP3 quality. I'm not concerned about disk space but would like to get the best audio possible with the understanding that I get that it's an audiobook. 

What quality is the MP3 created at and is it possible to change this based on my preferences or is it static?

Along the same lines, is it possible to download the 'enhanced' version vs. the 'format-4' version? Seems like it might be better starting with a higher quality file. 

Thanks

**Comment by openaudible** [comment]
We use FFMPEG to encode and use a good middle of the road value for quality. It can be adjusted by editing the mp3Qscale in the prefs. See issue #220 or search mp3Qscale in issues to see previous discussions.  

I don't believe we support or use Format4, only Enhanced.
 
Closing and will add a note in the documentation.
