### ISSUE TITLE
Missing most of my library

### ISSUE THREAD

**Issue by gbgit9999** [openaudible/openaudible#327]
I did purchase a license. I have over 150 titles in my Audible library but the app only reports 17. It appears to be the 17 latest added to my library. 

Is this a bug or did I do something wrong?

**Comment by openaudible** [comment]
Can you check that you're using version 2.0.3?
Make sure your library page is set to show "All" and "Sort by Date Added"
Then do a "Full Library Rescan"

**Comment by gbgit9999** [comment]
> Can you check that you're using version 2.0.3?
> Make sure your library page is set to show "All" and "Sort by Date Added"
> Then do a "Full Library Rescan"
> That should go through your library and find all books! If not, write back.

Yes I have the latest version 2.0.3. I never did a scan, I just selected the Connect option and I sw the 17 title appear. I did a rescan and it found all 168. Only other minor issue is the Library status shows 168 books but only 59.5 total hours. Not a big deal, just wanted to let you know. I appreciate the rapid response and will certainly provide additional feedback as needed.

**Comment by openaudible** [comment]
I guess it could be more clear! (What, you didn't read every sentence of the new and improved documentation?) 

Thanks for the note on the duration totals. That bit of meta data moved recently. It should get filled in when you download or convert a book.
