### ISSUE TITLE
multi book packs issues

### ISSUE THREAD

**Issue by Patrickg56** [openaudible/openaudible#329]
Greetings;

I have a large audible library and openadible works great for most of it. but I have a couple issues. The Multi book packs like "Galaxy Outlaws: The Complete Black Ocean Mobius Missions, 1-16.5" is an 80 hour set of books. Down loading it from Audible it comes down in 8 parts. However, the automated process only processes the first download. I have attempted to down load all 8 parts then have OpenAudible import and convert them, but that does not appear to be working.

There is another type of multiple part book like "Everyday Meditation" series has 20 different short books that again did not get processed. I tried the same process as above with the same result.

Suggestions?

**Comment by openaudible** [comment]
1. Make sure you're using 2.0.3 or the latest version.
2. Make sure your library audio format is set to "Enhanced"
3. Do a "full rescan" and try again (or simply type in the name of the book into the library view so it shows up and can be parsed in the library browser page. (That picks up the new download link.) 
When you log in from another browser (not the OA browser), and click the "Download link, you should see a "Full" followed by the "parts". That full one should be picked up by OA.
IF you tried all of the above, feel free to send a bug report and reference this issue.
