### ISSUE TITLE
[Question] Does this convert to MP3 by chapter?

### ISSUE THREAD

**Issue by IOI-655321** [openaudible/openaudible#33]
Just curious as that would be a very useful feature to convert to MP3 by chapter as otherwise only M4B supports chapter info.  A per chapter MP3 file is great for uploading to sites such as Google play music which have a file limit of around 50mb.

**Comment by openaudible** [comment]
Not a fan of many MP3s. Chapter information is stored in the mp3 file as meta data. I recommend using an audio book player that is great for remember last played position and lets you adjust playback speed... but its open source so feel free to modify.. however, I think it is non-trivial. But appreciate the suggestion.
