### ISSUE TITLE
Doesn't install on Windows

### ISSUE THREAD

**Issue by orish1** [openaudible/openaudible#331]
Hello, I downloaded OpenAudible_2.0.3_win.exe and tried to execute it - but nothing happened at all.

I tried downloading it again in case it had got corrupted. But still nothing. The cursor changes to a hourglass icon for a few seconds and then reverts to an arrow.

I have Windows 10 64-bit version.

Do I need to adjust compatibility settings or is there another version to download or the file corrupt?

Thanks and regards,
Gary

**Comment by nikolayganovski1** [comment]
@orish1 do you have Java installed(JRE/JDK) ?

**Comment by orish1** [comment]
no, it seems that I didn't have Java installed, but I did manage to install OpenAudible by changing the compatibility to Windows 8. OpenAudible is now installed and seems to be working fine for now.

Surely, if the *installer* needs Java (or the app itself) then you should detect whether it's installed and display a message to do so if it isn't.

But, it seems that Java is NOT required, coz it's working fine without it (just the installer program won't run).

**Comment by openaudible** [comment]
Check your anti-virus app. Currently, we have an unsigned application which is blocked by many anti-virus programs. You might be able to right-click the installer and "scan with anti-virus" or just run Windows Defender to see what virus software you have.

**Comment by openaudible** [comment]
Going to close since you got it installed.. But feel free to add any additional error messages or hints. Running in Windows 8 compatibility mode should not be needed, but now people have another thing to try.
