### ISSUE TITLE
Can't connect to my Audible account

### ISSUE THREAD

**Issue by orish1** [openaudible/openaudible#332]
Hello
When I click on Controls -> Connect to Audible, it opens the following page:

https://www.amazon.com/ap/signin?clientContext= <a bunch of stuff...? www.audible.com <more stuff>

There doesn't seem to be a mechanism to select which Amazon / Audible marketplace. My Audible account is in the UK, not USA. So please could you fix this.

[UPDATE]

Workaround. I'm not sure which action worked. One thing I did was to change the .com in audible.com in the URL to .co.uk. I don't think that worked.

I then re-opened the browser and just entered audible.co.uk and then logged in to my UK account.

That seemed to work and OpenAudible was then able to connect to my (UK) Audible library and download the books.

OpenAudible seems to be a really convenient app, I've got around 350 audible books and it would take forever to download them, even with Amazon's Audible app. I sometimes get locked out of my Audible account because of being offline or some kind of security glitch. This way, I can be sure to have access to the audiobooks I purchased, and can even edit them if necessary!

(So thank you!)

**Comment by openaudible** [comment]
you again. :)
First time logging on to your audible account we assume audible.com. That is supposed to redirect you to your correct region.. but you may need to manually enter it, as you did. Once you go to a new region, we remember the choice.. But also hard for us to test alternate regions, so good to know when there are issues. Maybe if region is unknown we add a "Select region".. but didn't think that was needed.
