### ISSUE TITLE
43 books in library status, 0 to convert, options greyed out

### ISSUE THREAD

**Issue by M-Cath** [openaudible/openaudible#334]
Hi, I have 43 audiobooks, all AAX. See image.  There are seen, but download is greyed out, convert to MP3 is greyed out and so are most other options. I use version 2.0.3 with license.  All the books have the same status of no download link, no AAX and no MP3.
Can this have anything to do with the fact that I use region DE?
![Openaudible](https://user-images.githubusercontent.com/64259061/80207651-d34edd00-862e-11ea-9708-5e232fcc3482.png)

**Comment by openaudible** [comment]
We have a bug where we forgot to tell you to change a setting:
https://openaudible.org/settings.html
Make that change and do a full rescan of your library and you'll be all set.

**Comment by M-Cath** [comment]
Ah, just changed it and it is busy downloading and two books have been converted already. 
Thank you very much, brilliant!
