### ISSUE TITLE
1 book in library seemingly unable to download

### ISSUE THREAD

**Issue by maxwelljordanwhite** [openaudible/openaudible#335]
I've tried reconnecting to Audible from in the app, I'm running the latest version (at the time of writing this) 2.0.3. New audiobooks download successfully, but this one doesn't seem to want to. The state is "No MP3 or AAX download link"; but why would that be if I can play it in the audible library (from the web, I mean)?

[If it helps, here is the link to the title I'm having this issue with.
](https://www.audible.com/pd/Its-Not-About-You-Audiobook/1799754898)
Please let me know if there's anything else I can do to troubleshoot this and provide more info. Thanks and loving the app!

**Comment by openaudible** [comment]
Some books and podcasts are only playable from the web or from a mobile device. Mostly free books or things like "Romance Package" where you have unlimited books, but can't download them to a PC. OpenAudible is just for books you purchased. 

To trouble shoot, view the book in a regular browser in the library page and look for the "Download" button. If there isn't a "Download" button, Audible says its not yours to download. If you do manage to download it and it saves as an AAXC file, that isn't supported either. But if it downloads as an AAX file, it can be imported. 

Hope that helps.

**Comment by maxwelljordanwhite** [comment]
@openaudible It does. Thank you. I'll give that a try. I suspect that's the case, but will confirm. All the best!

**Comment by openaudible** [comment]
Ok. Updating documentation and adding a little more debugging info to figure out which books aren't downloadable and why. Closing but feel free to reopen.

**Comment by openaudible** [comment]
Version 3.6 adds support for additional included titles.
