### ISSUE TITLE
Missing most of Metadata

### ISSUE THREAD

**Issue by gbgit9999** [openaudible/openaudible#336]
I have my library set to All and sort by Date Added. I do a full sync and it sees all 168 of my books but never stops the scan, so I eventually have to hit Cancel. Is this maybe why the majority of my books are missing metadata? They all have Titles but other data like Duration, Release Date, Duration are all empty. Below is a screen print to show what I am referring to. Any guidance is appreciated.
![MissingData](https://user-images.githubusercontent.com/64103209/80227043-228b1280-861b-11ea-9d65-f1f1b0b248b3.png)

**Comment by openaudible** [comment]
Audible has changed some things around. We used to get most from the library view.. now we have to get more from the Page info. Some we get from the downloaded book.
So.. Try to select a book, then Action: Refresh. It should fill in more.  If that works, you can select all and refresh all books. Be sure you're logged in to get the correct "Date purchased".

Then try downloading a book.. you may see more details.

**Comment by gbgit9999** [comment]
Yup, that did it. I selected all and did a refresh and 99% of data got populated. Excellent support, really appreciate your efforts.
