### ISSUE TITLE
Command Line support

### ISSUE THREAD

**Issue by jakeswenson** [openaudible/openaudible#337]
First of all, I love this app and have purchased a license, so thank you for that. (I am sad you had to go the way of a paid license model though...)

I would like to request a CLI/command line support for this app.
I'd like to run this to download from my server instead of personal computer.

Thanks

**Comment by openaudible** [comment]
That was the original goal. But with captchas and logins, it wasn't reliable. 
An API would work better.. but trying not to go crazy on new features. Need to remember people buy books a couple of times a month is all.
As far as going paid, we got almost no code PR's and our largest donation was $100. And zero from you and 99.9% of the users.
