### ISSUE TITLE
More bugs

### ISSUE THREAD

**Issue by orish1** [openaudible/openaudible#338]
I sent a bug report via the Send Bug report form in the app, but I think it got lost. I can't remember what that bug was about, so hopefully I'll see it again soon.

Anyway the bug reporter itself has a bug, so either fix it or just leave it off the app and just send users to the github issues page instead in future.

Two more small bugs:

1. Ctrl D doesn't work to download a book (but Ctrl N) does work for refreshing, for instance). I haven't tested the other shortcuts yet.

2. If I click on Send in this Bug Report form and there's an error (e.g. internet connect or something like: "account prevented from sending bug report") then the form just disappears and everything typed in the form is thrown away, and you have to start all over again with another bug report. (Now what I will do is to select all / copy in case it happens again.)

Sorry. Failed to send bug report. Pheraps bug reporting is disabled or there is a bug in a bug reports. Error: javax.net.ssl.SSLException: Connection reset by peer: socket write error.

**Comment by orish1** [comment]
BTW I got two separate errors when trying to send the bug report (not both at the same time).

**Comment by openaudible** [comment]
I fixed the debug sender to allow a retries. Maybe a firewall issue or anti-virus? 
Bug reports are really only helpful if they contain an error that logs a bunch of stuff to the console or if you're seeing issues parsing html book information. If its "my control keys don't work", an Issue would be better (include OS/version and any steps to reproduce.) 
 
I've seen at least one other report on command key shortcuts not working. They always seem to work on my windows developer machine. But we use a funky cross-platform system that has bugs. For instance: https://bugs.eclipse.org/bugs/show_bug.cgi?id=402073   is an old bug.. but maybe there is a newer one.  I can upgrade the SWT libraries.

Thanks for the feedback!
