### ISSUE TITLE
Can't login with "Audible account"

### ISSUE THREAD

**Issue by dny238** [openaudible/openaudible#339]
Audible provides two login options. Amazon account and the legacy Audible account. 
I use my Audible username still and it's no longer working. 

I upgraded to the 2.0 app and paid hoping that would help. Still not working. 
What information can I provide? there isn't an apparent error on the login form. 
Pick 'Controls->Connect to Audible->Audible Account. 
Once I put in username and password, hit 'Sign in'
the password banks and I"m on the same page. 

Chrome works. 

Resulting url is....

**Comment by dny238** [comment]
Actually, if I put that URL into Chrome it doesn't work. 

It does redirect me to here, which then works in Chrome.

https://www.audible.com/ap/signin?clientContext=134-2612865-6643131&openid.return_to=https%3A%2F%2Fwww.audible.com%2Flib&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_audible_lap_us&openid.mode=checkid_setup&marketPlaceId=AF2M0KC94RCEA&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_audible_lap_us&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.pape.max_auth_age=7776000&siteState=audibleid.userType%3Dadbl%2Caudibleid.mode%3Did_res%2CclientContext%3D146-0990664-5397114%2CsourceUrl%3Dhttps%253A%252F%252Fwww.audible.com%252Flib%253F%2Csignature%3DknUBYmW9q9fQxJeOA0VuHMrGdUcj3D

**Comment by dny238** [comment]
From the console log.

```
INFO: Debug: C:\Users\rob\OpenAudible\tmp\no_signin.html
May 01, 2020 3:32:36 PM org.openaudible.audible.parser.AudibleParser logInState
WARNING: Expected sign-in or sign-out hrefs in https://www.audible.com/ap/signin?clientContext=131-8936780-9684060&openid.return_to=https%3A%2F%2Fwww.audible.com%2Flib&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_audible_lap_us&openid.mode=checkid_setup&marketPlaceId=AF2M0KC94RCEA&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_audible_lap_us&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.pape.max_auth_age=7776000&siteState=audibleid.userType%3Dadbl%2Caudibleid.mode%3Did_res%2CclientContext%3D139-5892346-2057114%2CsourceUrl%3Dhttps%253A%252F%252Fwww.audible.com%252Flib%253F%2Csignature%3DxcLp9DsZIwzAKj2BjbRC49YVDS2qsj3D. Wrote page to disk.
May 01, 2020 3:32:36 PM org.openaudible.desktop.swt.manager.AudibleGUI connectTask
WARNING: connectTask failed to log in: 
org.openaudible.audible.AudibleLoginError: Not logged in:AudiblePage:https://www.audible.com/ap/signin 58141 bytes html
	at org.openaudible.audible.AudibleScraper.throwNotLoggedIn(AudibleScraper.java:213)
	at org.openaudible.audible.AudibleScraper.lib(AudibleScraper.java:192)
	at org.openaudible.desktop.swt.manager.AudibleGUI.connect(AudibleGUI.java:515)
	at org.openaudible.desktop.swt.manager.AudibleGUI.connectTask(AudibleGUI.java:419)
	at org.openaudible.desktop.swt.manager.AudibleGUI$2.run(AudibleGUI.java:439)

May 01, 2020 3:32:39 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: changing LocationEvent{Browser {} time=0 data=null location=https://www.audible.com/ap/signin top=false doit=true}
May 01, 2020 3:32:39 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: changing LocationEvent{Browser {} time=0 data=null location=https://www.audible.com/lib?openid.assoc_handle=amzn_audible_lap_us&openid.claimed_id=https%3A%2F%2Fwww.audible.com%2Fap%2Fid%2Famzn1.account.AHTRZDHQM42BNQ3L7ACQPX57F2NA&openid.identity=https%3A%2F%2Fwww.audible.com%2Fap%2Fid%2Famzn1.account.AHTRZDHQM42BNQ3L7ACQPX57F2NA&openid.mode=id_res&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.op_endpoint=https%3A%2F%2Fwww.audible.com%2Fap%2Fsignin&openid.response_nonce=2020-05-01T21%3A32%3A43Z3782660313027483152&openid.return_to=https%3A%2F%2Fwww.audible.com%2Flib&openid.signed=assoc_handle%2Cclaimed_id%2Cidentity%2Cmode%2Cns%2Cop_endpoint%2Cresponse_nonce%2Creturn_to%2CsiteState%2Cns.pape%2Cpape.auth_policies%2Cpape.auth_time%2Csigned&openid.ns.pape=http%3A%2F%2Fspecs.openid.net%2Fextensions%2Fpape%2F1.0&openid.pape.auth_policies=http%3A%2F%2Fschemas.openid.net%2Fpape%2Fpolicies%2F2007%2F06%2Fnone&openid.pape.auth_time=2020-05-01T21%3A32%3A43Z&openid.sig=BW%2BD4X%2BlcDcjIvWiSm8PODt%2BDDWnnykdvbGZYyzEdkI%3D&serial=&siteState=audibleid.userType%3Dadbl%2Caudibleid.mode%3Did_res%2CclientContext%3D139-5892346-2057114%2CsourceUrl%3Dhttps%253A%252F%252Fwww.audible.com%252Flib%253F%2Csignature%3DxcLp9DsZIwzAKj2BjbRC49YVDS2qsj3D top=false doit=true}
May 01, 2020 3:32:39 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: changing LocationEvent{Browser {} time=0 data=null location=https://www.audible.com/lib top=false doit=true}
May 01, 2020 3:32:39 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: changing LocationEvent{Browser {} time=0 data=null location=https://www.audible.com/ap/signin?clientContext=131-8936780-9684060&openid.return_to=https%3A%2F%2Fwww.audible.com%2Flib&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_audible_lap_us&openid.mode=checkid_setup&marketPlaceId=AF2M0KC94RCEA&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_audible_lap_us&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.pape.max_auth_age=7776000&siteState=audibleid.userType%3Dadbl%2Caudibleid.mode%3Did_res%2CclientContext%3D139-5892346-2057114%2CsourceUrl%3Dhttps%253A%252F%252Fwww.audible.com%252Flib%253F%2Csignature%3DxcLp9DsZIwzAKj2BjbRC49YVDS2qsj3D top=false doit=true}
May 01, 2020 3:32:40 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: changed LocationEvent{Browser {} time=0 data=null location=https://www.audible.com/ap/signin?clientContext=131-8936780-9684060&openid.return_to=https%3A%2F%2Fwww.audible.com%2Flib&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_audible_lap_us&openid.mode=checkid_setup&marketPlaceId=AF2M0KC94RCEA&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_audible_lap_us&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.pape.max_auth_age=7776000&siteState=audibleid.userType%3Dadbl%2Caudibleid.mode%3Did_res%2CclientContext%3D139-5892346-2057114%2CsourceUrl%3Dhttps%253A%252F%252Fwww.audible.com%252Flib%253F%2Csignature%3DxcLp9DsZIwzAKj2BjbRC49YVDS2qsj3D top=true doit=false}
May 01, 2020 3:32:40 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan page completed:ProgressEvent{Browser {} time=0 data=null current=0 total=0}
May 01, 2020 3:32:40 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: GetSourceCodeTask len=57928
May 01, 2020 3:32:41 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 55317 to disk:C:\Users\rob\OpenAudible\tmp\no_signin.html
May 01, 2020 3:32:41 PM org.openaudible.util.HTMLUtil debugHtml
INFO: Debug: C:\Users\rob\OpenAudible\tmp\no_signin.html
May 01, 2020 3:32:41 PM org.openaudible.audible.parser.AudibleParser logInState
WARNING: Expected sign-in or sign-out hrefs in https://www.audible.com/ap/signin?clientContext=131-8936780-9684060&openid.return_to=https%3A%2F%2Fwww.audible.com%2Flib&openid.identity=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&openid.assoc_handle=amzn_audible_lap_us&openid.mode=checkid_setup&marketPlaceId=AF2M0KC94RCEA&openid.claimed_id=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0%2Fidentifier_select&pageId=amzn_audible_lap_us&openid.ns=http%3A%2F%2Fspecs.openid.net%2Fauth%2F2.0&openid.pape.max_auth_age=7776000&siteState=audibleid.userType%3Dadbl%2Caudibleid.mode%3Did_res%2CclientContext%3D139-5892346-2057114%2CsourceUrl%3Dhttps%253A%252F%252Fwww.audible.com%252Flib%253F%2Csignature%3DxcLp9DsZIwzAKj2BjbRC49YVDS2qsj3D. Wrote page to disk.
```

**Comment by openaudible** [comment]
What region are you in? We assume US, but if you're in another geographical region, it may take a while to log in... basically... use the OpenAudible browser (CTRL-B) to log into your audible.. there may be capchas or redirects.. but eventually it will say you are logged in. (otherwise, I'd get a flood of unhappy reports.)  We don't attempt to fill in any details.. but cookies are saved that makes logging in later easier. Once logged in, go to your library view, and the other features (resync & refresh) should work fine. 

[Deleted some of the long URLs in your posts to protect your identity].

**Comment by dny238** [comment]
Ok. It wasn't working, so I used the browser to visit audible.com. It knew my name, but wouldn't let me view my library without a login prompt. 
So I hit my name, logged out fully. 
After logging in from scratch it worked. 

Not sure if it's a condition you can test for, but maybe a logout option in the menu would have inspired me, if you can't detect it.

**Comment by openaudible** [comment]
If you're not logged out, we can't log you out.. so we'll update the docs to reiterate that logging in is required before the product does much.

**Comment by dny238** [comment]
> If you're not logged out, we can't log you out.. so we'll update the docs to reiterate that logging in is required before the product does much.

That's the thing, your app made it look like I was logged out and was trying to log me in. I had to use your browser to go to Audible and log myself out. The 'Connect' option in  your app just had me try to login over and over. 
To be clear, your app wouldn't work either, it wouldn't refresh my library, etc. It made sense if it wasn't working to try to Connect again.
I had to over ride the application's default behavior and log myself out, something that didn't seem necessary to allow it to properly login.
Hope that helps you improve things for the next guy...

**Comment by openaudible** [comment]
Ah. Thanks for the feedback.  It is hard to know what people are seeing when they first attempt to connect. Maybe I can add a help dialog if the standard "Connect" is called more than a couple of times without success. I can also add a "log out and clear cookies" option... which might help reset things.
I do appreciate the feedback!

**Comment by dny238** [comment]
Exactly, that'd have been perfect. 
Or if you can tell I tried to login, that the system returned me to the login screen, without the message that my password was bad. It was just the login screen again for some reason. Over and over. 
Love the app! Keep up the good work.
