### ISSUE TITLE
Duration in List View and Librarystatus is off.

### ISSUE THREAD

**Issue by tomtom90** [openaudible/openaudible#341]
Hey everyone,
nothing important, but it seems as if you use time as `mm:ss` only and trim the `hh` port of the duration.
This in turn seems to take it's toll on the librarystatus duration as well. In my case it's __off by__ about __550h__.
| Librarystatus |Real Total|
|---|---|
|85.5h|636.5h|

I'd suggest the duration to be either formatted as `dd:hh:mm:ss` or `hh:mm:ss` (with `hh >= 60` possible) in order to correct that.

Thanks for your great work.

**Comment by openaudible** [comment]
Check that each book in your library has a duration (sort by duration). 

Audible changed where the duration info is saved and it isn't always retrieved. You may need to download the book or select books with an empty duration and Action: Refresh (when logged in.)

**Comment by tomtom90** [comment]
Hey, thx for your response.
I already did the refresh and it went up from about 65h to 85.5h but that was all (for at least an hour after all rows where populated).
I left openaudible unattended since filing the issue. In order to test your suggestion I just opened and sorted it by duration, now the total is correct. However I did not check before sorting it by duration again.

**Comment by openaudible** [comment]
The total should be a correct sum of all known durations. I think it is.. But some durations may not be able to be determined if the book isn't downloaded and not in your library.
