### ISSUE TITLE
Problems with rcrack.exe

### ISSUE THREAD

**Issue by nearlymad** [openaudible/openaudible#342]
I have updated the rcrack.exe executables. I have made all programs within the Open Audible directory to run as administrator. I have updated my Java, I have both 32 & 64-bit on my machine (Surface Pro 7 running Windows 10 Home, version 1909, build 18365:815), but I keep getting this error message and the files will not convert to mp3:

May 04, 2020 1:45:57 PM org.openaudible.util.queues.ThreadedQueue jobError
INFO: ConvertQueue error processing convert No Excuses: Existentialism and t
java.io.IOException: Error running rcrack. Check console.
	at org.openaudible.convert.LookupKey.lookupKey(LookupKey.java:147)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:95)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:104)
	at org.openaudible.convert.ConvertJob.getActivationBytes(ConvertJob.java:324)
	at org.openaudible.convert.ConvertJob.createMP3(ConvertJob.java:135)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:340)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:391)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:420)

**Comment by openaudible** [comment]
This is hard to diagnose. We didn't write that app. I think it happens rarely, since I've only seen the report a couple of times (but to you it happens always.). It only needs to be run once to get your audible key. Could it be an anti-virus app? Can you run a different computer? You might be able to find a newer version of the rcrack.exe app and test that. Or you could attempt to build rcrack from source code and run it... I might be able to build a debug version and see if we can get a better stack trace.. Lots of options.. but I don't have anything ready to go at the moment.

**Comment by brokencork** [comment]
I am having the same problem.  Windows Defender is turned off and not running any other anti-virus apps.

**Comment by openaudible** [comment]
How much memory do you have? Its possible the app is trying to allocate too much. ?

Anyone know how to use a C++ compiler and debugger on windows? Me either.. haha.  

Can you paste the output from the console about the exit code?

I believe you are seeing an error code c0000005, an access violation. Which is the app reading or writing to memory it shouldn't. not sure if memory is exhausted. 

Googling doesn't turn up..

**Comment by brokencork** [comment]
Running 8GB RAM.  No other apps are running when trying to convert to mp3.  I am getting error code c0000005.  See output below:

OpenAudible uses the open source application 'rainbow crack' to look up your audible keys. This process returned an error.
Perhaps your anti-virus program is blocking the executable from running.
You can try updating your version of 'C:\Program Files\OpenAudible\bin\win\crack.exe' or just run OpenAudible on a compatible system and copy the keys.json file to this computer.

Check the console for more information. The error reported was:
cmd:"C:\Program Files\OpenAudible\bin\win\rcrack.exe" "C:\Program Files\OpenAudible\bin\tables" -h a9e6f042b927ab609ad004d78f6232fed8ecc33b
error code:-1073741819(C0000005)
stdout:
stderr:

**Comment by openaudible** [comment]
Hmm. 8GB seems like plenty.. but haven't tried it on an 8GB system. 

I will try to build a developer version of it that might give better error messages. I'll post an update here as soon as I get something. I'll need some help testing... Thanks in advance!

**Comment by openaudible** [comment]
2.0.6 has a possible fix. Give it a try and reopen if any questions.
