### ISSUE TITLE
Cant get it to run on Windows 10 insider version

### ISSUE THREAD

**Issue by dpm0** [openaudible/openaudible#343]
![image](https://user-images.githubusercontent.com/64821363/81032793-7aa3fd80-8ed4-11ea-8eff-6e04963f3b19.png)
The image above is the version of win 10 that I have on this PC. It is a Windows insider build. It is working well on my laptop, which is a Standard Win 10 Pro edition.

**Comment by openaudible** [comment]
OpenAudible requires a 64bit machine to run.  What error do you get when you run the installer?

**Comment by dpm0** [comment]
Hi, thanks for the reply. It is a 64 bit machine. There were no errors upon installation, the icons, folders etc were created as expected. There is a service running, but no GUI after clicking.
It's not a biggie, I really only raised a case since it may herald issues that you might come accross later when MS does an update to windows.

Regards

David Maher




---- On Wed, 06 May 2020 01:42:17 +1000 openaudible <mailto:notifications@github.com> wrote ----




OpenAudible requires a 64bit machine to run.  What error do you get when you run the installer?

**Comment by openaudible** [comment]
Hmm. Maybe try running it from the command line to get an error message?
I was signed up for the advanced windows beta program for another issue... so I haven't seen any issues.

**Comment by dpm0** [comment]
I'll give it a try tomorrow.

Regards

David Maher




---- On Wed, 06 May 2020 14:01:58 +1000 openaudible <mailto:notifications@github.com> wrote ----




Hmm. Maybe try running it from the command line to get an error message?
 I was signed up for the advanced windows beta program for another issue... so I haven't seen any issues.

**Comment by jbferguson75** [comment]
I just updated from v.1.5.4 which worked previously to v.2.0.4 and I'm having the exact same issue.  It runs and starts a background process but no GUI starts.  My Windows 10 Home is up to date but not running any preview builds.

**Comment by openaudible** [comment]
Can you look to see if a log was created in:
C:\Users\USER\OpenAudible\tmp\log.txt
?

**Comment by jbferguson75** [comment]
There was one in there but it only referred to the 1.5 version I previously had.  I deleted it and then ran OpenAudible 2 a couple of times more killing it in the task manager and no new log file was created.

**Comment by openaudible** [comment]
Thanks for checking. We set up logging to the tmp directory right after starting, before doing any weird GUI code (that can fail).. So it sounds like perhaps the java isn't working. Do you have java installed on your computer? (Run java -version from the command line.) It looks like the windows installer is set to only install a bundled java jre if a suitable one isn't found.. So if yours is damaged or gets removed, it might cause the failure. I am researching a fix.

**Comment by jbferguson75** [comment]
I’ve got java version “11.0.5” 2019-10-15 LTS.

I can uninstall it since I don’t use it very often and have the installer install another one.  It seems like I installed java 11 for a project I did for work but didn’t end up using it.

**Comment by jbferguson75** [comment]
That was the problem.  I uninstalled the JDK 11 and reinstalled the 1.8 jre.  I then reinstalled openaudible and now it’s all working.

Thanks for the help.

**Comment by openaudible** [comment]
Ok. Including a full JRE in 2.0.6 and later... as well as a debug.bat or debug.sh script to debug failure to start issues.
