### ISSUE TITLE
Mac -- there is no "OpenAudible License window under the About Menu"

### ISSUE THREAD

**Issue by Amazondoc** [openaudible/openaudible#344]
I'm a longtime OpenAudible user. Donated to the project in the free versions. Downloaded version 2.0.4 today. Tried to use it -- got a "you've selected a feature that is not available in the demo version" error message. Went to the OpenAudible website, paid for the new version (at only $12, it's worth paying for again). Got my license code.

BUT --

There is no place to enter the license code under the "about" option. See screenshot below. There is only an option to "donate" -- aka pay -- again, even though I've already paid.

Please advise.

<img width="334" alt="Screen Shot 2020-05-05 at 12 57 26 PM" src="https://user-images.githubusercontent.com/64862365/81099854-2ba89900-8ed1-11ea-848b-d3825d2fa81c.png">

**Comment by openaudible** [comment]
Look under the About Menu, not "About OpenAudible." 
We'll remove the link to the Donate.. That wasn't supposed to be there!

**Comment by Amazondoc** [comment]
That got it, thanks!

Do you think maybe having two "About" options could be a bit confusing? ;-)

**Comment by openaudible** [comment]
Updated the documentation.. !
