### ISSUE TITLE
Custom Filename Support

### ISSUE THREAD

**Issue by theswordsmahin** [openaudible/openaudible#346]
Just discovered this program and really like it! Would be really cool though if there was support for customizing the final directory/filename structure using some sort of pattern, so you could get mp3's in `<author>/<title><book_x>/<filename>.mp3` or something. Would this be possible? 
Thanks!

**Comment by openaudible** [comment]
It's a harder problem than you might expect.. Recommend you export as web or JSON and write a little program to rename as you see fit. But appreciate the kind words and suggestion.
