### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by spelunkerofbasil** [openaudible/openaudible#349]
When I select File->Export Web Page and then tick the "Show Images" box, no images are shown.
Macbook Pro with the latest system and lots of memory.  Saw the same behavior in 5.0.4.

I thought that this might be because I have a large library and must store the files on an external drive that is not always mounted, but that seems not to be the case since even when I mount the external drive and set the paths and restart OpenAudible and repeat the "Export Web Page" command, I still see no images.

![Screenshot2020-05-08_06-15-06_PM](https://user-images.githubusercontent.com/11848048/81460123-15f8d500-9158-11ea-82b5-fb99f7c269a4.png)

**Comment by openaudible** [comment]
Do the images show up in the application when you click on a book? If not, select one or more books and select Action: Refresh to grab a copy of the book cover image.

**Comment by evotodi** [comment]
I can confirm the images are not showing on the webpage. They do show in the app however.
![Capture](https://user-images.githubusercontent.com/1625853/81501029-fc64a400-92a3-11ea-81e5-3689c475aeed.png)
![Annotation 2020-05-10 095352](https://user-images.githubusercontent.com/1625853/81501060-2a49e880-92a4-11ea-9cc2-d2c4ead56ae8.jpg)

**Comment by openaudible** [comment]
Fixed in 2.0.7! Thank you for the detailed bug report.. Sorry-- it got broken when I added the "quick feature to add support for M4A."
