### ISSUE TITLE
Genre

### ISSUE THREAD

**Issue by 1234shai** [openaudible/openaudible#35]
Is it possible to pull the genre from the Audible data and add it to the list of Audio Book Info that you get?  The Excel file seems to have a column for it, but only "Audiobook" appears in it.

**Comment by openaudible** [comment]
Good suggestion. Genre appears to be in a tree struture, such as:
Fiction -> Historical
Fiction -> Contemporary
Sci-Fi & Fantasy ->  Sci-Fi: Contemporary 

Will attempt.

**Comment by openaudible** [comment]
Give 1.2 a try. We collect the genre and export it to web, but we're not currently setting as an MP3 tag.. You will need to "Refresh Info" for each book you want the new genre on.
