### ISSUE TITLE
Display issues in the exported Website (OpenAudible 2.0.6)

### ISSUE THREAD

**Issue by matschundbrei** [openaudible/openaudible#351]
Version: OpenAudible 2.0.6
Licensed today (2020-05-09)
OS: Windows 10/64/US-EN
Filesystem: Working Directory/Settings  = Local/Default, Website-Directory = CIFS Share on NAS
Languages: Tried in German and English, no difference

The following things do not work at in the exported Website:
- displaying images (all images are in place and a seemingly correct filename is present in the JSON)
- displaying dates (all dates are in the JSON and displayed in the overview, but only 'Value' is shown on details modal)
- mp3/m4a-links are missing completely (mp3 is not exported any more and there are no filenames in the mp3 field on the JSON data)

**Workaround**
When I manually create the mp3 folder (but nothing else) in the target directory the mp3 files get copied and there are only minor file-name issues. Some of the mp3-files are using wrong/old names from previous encodings.
The images are shown correctly. The values for 'Duration', 'Purchase Date' aso are still not shown correctly in the detail-modal.
Here's a small bash script, that might show you all non-existant files mentioned in the JSON from the web-export:
```bash
#!/bin/bash
IFS=$'\n'
for encoded in `jq -r '.[].mp3' < books.json`; do
  if [[ ! -f mp3/${encoded} ]]; then
    echo "Missing mp3: ${encoded}"
  fi
done
```

Now here's what happens, when either the mp3-folder does not exist or it exists with old files in it:

Here's an example json from one of my audio-books:
```json
[
  {
    "title": "Change Agent",
    "author": "Daniel Suarez",
    "narrated_by": "Jeff Gurner",
    "mp3": "",
    "m4a": "",
    "image": "Change Agent.jpg",
    "description": "",
    "summary": "<p><i>New York Times</i> best-selling author Daniel Suarez delivers an exhilarating sci-fi thriller exploring a potential future where CRISPR genetic editing allows the human species to control evolution itself. </p> \n<p>On a crowded train platform, Interpol agent Kenneth Durand feels the sting of a needle - and his transformation begins.... </p> \n<p>In 2045 Kenneth Durand leads Interpol's most effective team against genetic crime, hunting down black market labs that perform \"vanity edits\" on human embryos for a price. These illegal procedures augment embryos in ways that are rapidly accelerating human evolution - preying on human-trafficking victims to experiment and advance their technology. </p> \n<p>With the worlds of genetic crime and human trafficking converging, Durand and his fellow Interpol agents discover that one figure looms behind it all: Marcus Demang Wyckes, leader of a powerful and sophisticated cartel known as the Huli jing. </p> \n<p>But the Huli jing have identified Durand, too. After being forcibly dosed with a radical new change agent, Durand wakes from a coma weeks later to find he's been genetically transformed into someone else - his most wanted suspect: Wyckes. </p> \n<p>Now a fugitive, pursued through the genetic underworld by his former colleagues and the police, Durand is determined to restore his original DNA by locating the source of the mysterious - and highly valuable - change agent. But Durand hasn't anticipated just how difficult locating his enemy will be. With the technology to genetically edit the living, Wyckes and his Huli jing could be anyone and everyone - and they have plans to undermine identity itself. </p>",
    "duration": "15:02",
    "rating_average": "4.448717948717949",
    "rating_count": "312",
    "link_url": "https://www.audible.de/pd/Change-Agent-Hoerbuch/B06XPKFNDN",
    "purchase_date": "2017-08-15",
    "release_date": "2017-04-18",
    "publisher": "Penguin Audio",
    "author_url": "https://www.audible.de/author/Daniel-Suarez/B001V206AK"
  }
]
```

Just for reference ran from the export folder(on another host):
```shell
 $ ls -1 thumb/Change\ Agent.jpg cover/Change\ Agent.jpg mp3/Change\ Agent.mp3
'cover/Change Agent.jpg'
'mp3/Change Agent.mp3'
'thumb/Change Agent.jpg'
```
The mp3-folder was not created by the website-export-function, I moved it there manually.

But when an audiobook was initially downloaded after the start, it's mp3 was moved there.

A screenshot from the modal with the missing values:
![modal with missing values](https://user-images.githubusercontent.com/9265808/81471401-037eaa00-91f1-11ea-96ec-522a3e5da148.png)

Console output, after removing all files from the website directory on my CIFS/NAS, only shows an error for the mp3-file, everything else seems to be created as expected:
```console
SEVERE: error copying:C:\Users\REDACTED\OpenAudible\mp3\Change Agent.mp3 to X:\REDACTED\mp3\Change Agent.mp3 for book Change Agent
java.io.FileNotFoundException: X:\REDACTED\mp3\Change Agent.mp3 (The system cannot find the path specified)
	at java.base/java.io.FileOutputStream.open0(Native Method)
	at java.base/java.io.FileOutputStream.open(FileOutputStream.java:292)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:235)
	at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:185)
	at org.openaudible.util.CopyWithProgress.copyWithProgress(CopyWithProgress.java:57)
	at org.openaudible.feeds.pagebuilder.WebPage.buildPage(WebPage.java:188)
	at org.openaudible.desktop.swt.manager.ImportExport$PageBuilderTask.run(ImportExport.java:844)
```

**Comment by openaudible** [comment]
Thank you for the detailed report. I messed it up when I added the support for m4a books. It should be  fixed with 2.0.7. We did change the file naming around as well.. we used to save books as the product ID and then used the web export to rename them to something useful.. now we save all books in a more human readable form. Might mean you need to re-build the web directory from scratch.. but not sure!  Let me know if 2.0.7 has any issues.
