### ISSUE TITLE
License transaction

### ISSUE THREAD

**Issue by bojancalic** [openaudible/openaudible#352]
Credit card transaction completed from my side, funds deducted, however your website doesn't seem to know of any license under my account.

**Comment by openaudible** [comment]
I didn't see your name on the order list. Try the following help links:

It may be just a temporary hold on the funds.. and if the charge is declined, the bank can be slow to remove the hold. You may need to call your CC company.

https://fastspring.com/question-a-charge/

https://openaudible.org/license

I updated our html to make the help links easier to find. email me at openaudible at email.tg if any questions.
