### ISSUE TITLE
MP3 conversions: some seconds are removed at the end of each and every chapter.

### ISSUE THREAD

**Issue by stuttgart786** [openaudible/openaudible#353]

**Comment by alehel** [comment]
Possibly same bug as my own issue from yesterday https://github.com/openaudible/openaudible/issues/348

**Comment by openaudible** [comment]
Splitting chapters is done with ffmpeg using the chapter timing info from audible. 
I'm unable to reproduce this on my end.. So need to know:
Are all books showing bad? 
Are all chapters bad? Someone said the "This is audible" part was clipped-- but that should be really hard to have happen-- the start time should be 0.. but if it is happening, a that should be easy to debug.
Are you spitting M4A or MP3?

**Comment by alehel** [comment]
@openaudible I'm the one with the clipped "This is audible part". As I mentioned in a different issue, I've deleted my mp3s as I prefer to have them in m4a format. I remember which books I had issues with and made new conversions. Absolutely no problem this time round, which is strange. So I guess we'll just have to put that one down as "Can't reproduce".

**Comment by stuttgart786** [comment]
Hello.
I’m trying to play MP3 chapters on iPod.

I have done split 2 books thus far:
Lee Child: Blue Moon
John Le Carre: Agent running in the field.

On closer review I fear the playing platform is relevant.
I lose something between 5 and ten seconds from every chapter when playing on iPod.

Windows: I am seeing a discrepancy between the timing presented by iTunes on windows and the audio itself. The timing is short by some seconds.
iPod shuffle: If I use my iPod shuffle – no screen -  the audio stops playing although the chapter is invariably not yet completed.

I appreciate your software appears to split correctly since the chapters are fine when played on foobar on windows.
Bit of a bugger though since I wanted your software to listen to audible on my (tiny little) ipod but the import into itunes seems to be screwing up.

Hope this helps.
Jeff

**Comment by openaudible** [comment]
Ok. I think the data is correct. But re-open if you can find a bug that I can fix. Pretty sure the code to split is correct-- but maybe there is some weird meta data that is confusing some players?

**Comment by fgweller** [comment]
Can confirm that this is a device-specific issue - the final 5 seconds get chopped off on iPod Shuffle, but it's fine on an AGPTEK player or on Windows.
