### ISSUE TITLE
2.0.6 doesn't remember chosen output format

### ISSUE THREAD

**Issue by alehel** [openaudible/openaudible#354]
I deleted my mp3's, chose m4a as output format and converted my collection. This worked well. However, when I quit, and then go back into OpenAudible, the output format is set back to mp3, and the application asks me if I want to convert all my titles, ignoring the fact that I've already done this in the m4a format.

**Comment by openaudible** [comment]
Shoot.

**Comment by openaudible** [comment]
Will fix for next release. You'll have to change each time or keep it running until the next upgrade.  Sorry!

**Comment by alehel** [comment]
That's great, thanks. Really pleased we now have m4a support :).

**Comment by rsr-at-mindtwin** [comment]
Hey, while this issue is open, can I ask whether m4a is the native content of the aax format?  I had no idea.  Would it be worth re-converting all of the titles that were previously converted to mp3, assuming that m4a is a format that works for playback (for me)?

**Comment by openaudible** [comment]
Well, it would help if I tested things better. 
Yes, the copy to native format is fast and keeps quality the same.
Auto-convert after import should be fixed for next release.

**Comment by openaudible** [comment]
Fixed in 2.0.7! Thank you!
