### ISSUE TITLE
2.0.6 Show AAX and show m4a not working (show mp3 works fine).

### ISSUE THREAD

**Issue by alehel** [openaudible/openaudible#355]
If I right click a book, and select the option "Show aax", openaudible opens the file explorer and shows me the location of the mp3, not the aax. If I select "Show m4a", nothing happens. If I select "Show mp3" it shows me the mp3. I have the book in question in all 3 formats, as you can see in the included image.

![image](https://user-images.githubusercontent.com/22277624/81480028-452a4780-9227-11ea-862d-b595627144ba.png)

If I try on a book which I only have locally in aax and m4a format (i.e. not mp3), then "Show mp3" is greyed out as expected, but the "Show aax" and "Show m4a" buttons do nothing. 

This is on Windows 10.

**Comment by openaudible** [comment]
THANK YOU!
Confirmed and fixed for next release.
