### ISSUE TITLE
Bug report sending does not work

### ISSUE THREAD

**Issue by simudvarac** [openaudible/openaudible#357]
<img width="1050" alt="Bildschirmfoto 2020-05-10 um 12 15 16" src="https://user-images.githubusercontent.com/272210/81496592-f6c58900-92b8-11ea-886c-bbe97cfe477d.png">

**Comment by Geordon** [comment]
Same issue here.  I wonder if it's not related to what appears to be a java error with M4B conversion

**Comment by openaudible** [comment]
Fixed for next release. Shoot, was testing error handing in the bug reporter and left in the test error. Thank you for the heads up. No wonder no bug reports!

**Comment by amiira1012** [comment]
also reproduced this error - from console:

INFO: Command: Send_Bug_Report
May 11, 2020 1:06:55 PM org.openaudible.desktop.swt.manager.views.BugReportDialog run
SEVERE: java.lang.Exception: Test error
May 11, 2020 1:06:55 PM org.openaudible.desktop.swt.manager.views.BugReportDialog okPressed
SEVERE: send error
java.lang.Exception: Test error
	at org.openaudible.desktop.swt.manager.views.BugReportDialog$2.run(BugReportDialog.java:89)

May 11, 2020 1:06:55 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: MESSAGE_BOX_TITLE_ERROR
Error
May 11, 2020 1:06:55 PM org.openaudible.desktop.swt.gui.MessageBoxFactory checkShell
INFO: Active shell:Shell {OpenAudible} visible=true input shell:Shell {Send Bug Report}

**Comment by openaudible** [comment]
Fixed in 2.0.7, available now. (Hopefully you won't be able to find any bugs.)
