### ISSUE TITLE
Enhancement request: Close window exits program.

### ISSUE THREAD

**Issue by Geordon** [openaudible/openaudible#358]
Clicking on "close" window button exits program.  Please make it optional to close -> minimize to icon

**Comment by openaudible** [comment]
Which OS? Isn't there already a minimize button?

**Comment by Geordon** [comment]
Sorry, macOS Catalina.  The yellow button doesn't always minimize, but rather returns the window to a smaller size from before the green button was clicked.  Many apps allow the red button to close the window but not the app.

**Comment by openaudible** [comment]
I'm going to request that you use "option click desktop" to hide OpenAudible.. it will continue to run in the background. I did just find out CMD-H is supposed to hide the app.. but instead, brings up the help. But appreciate the feature request.
