### ISSUE TITLE
Error when joining mp3 files

### ISSUE THREAD

**Issue by amiira1012** [openaudible/openaudible#359]
hi Open Audible team! :)
I'm trying to join a bunch of mp3s together into one file, but keep getting the same error (see console text below).
there was a similar error previously (#252) but i don't recognise the same error in the console log that user posted.
i've updated to version 2.0.6 yesterday and i have a valid license.
thanks for your help and your amazing program!

----------------------------------------------------- 

INFO: Command: Join_Audio_Files
May 11, 2020 1:02:30 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: "C:\Program Files\OpenAudible\bin\win\ffmpeg.exe" -f concat -safe 0 -i C:\Users\Carina\OpenAudible\tmp\1589173350674.txt -c copy "D:\Music\!Audiobooks\Jacqueline Carey\Kushiel's Dart\Kushiel's Dart.mp3" 
May 11, 2020 1:02:32 PM org.openaudible.convert.SplitJoinAudio join
SEVERE: No output file for join:cmd:"C:\Program Files\OpenAudible\bin\win\ffmpeg.exe" -f concat -safe 0 -i C:\Users\Carina\OpenAudible\tmp\1589173350674.txt -c copy "D:\Music\!Audiobooks\Jacqueline Carey\Kushiel's Dart\Kushiel's Dart.mp3" 
error code:1(1)
stdout:
stderr:ffmpeg version N-96343-g029cc9883f-ffmpeg-windows-build-helpers Copyright (c) 2000-2020 the FFmpeg developers
  built with gcc 8.3.0 (GCC)
  configuration: --pkg-config=pkg-config --pkg-config-flags=--static --extra-version=ffmpeg-windows-build-helpers --enable-version3 --disable-debug --disable-w32threads --arch=x86_64 --target-os=mingw32 --cross-prefix=/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/bin/x86_64-w64-mingw32- --enable-libcaca --enable-gray --enable-libtesseract --enable-fontconfig --enable-gmp --enable-gnutls --enable-libass --enable-libbluray --enable-libbs2b --enable-libflite --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libilbc --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libtwolame --enable-libvo-amrwbenc --enable-libvorbis --enable-libwebp --enable-libzimg --enable-libzvbi --enable-libmysofa --enable-libopenjpeg --enable-libopenh264 --enable-liblensfun --enable-libvmaf --enable-libsrt --enable-demuxer=dash --enable-libxml2 --enable-libdav1d --enable-libsvthevc --enable-libaom --enable-libvpx --enable-nvenc --enable-nvdec --extra-libs=-lharfbuzz --extra-libs=-lm --extra-libs=-lpthread --extra-cflags=-DLIBTWOLAME_STATIC --extra-cflags=-DMODPLUG_STATIC --extra-cflags=-DCACA_STATIC --enable-amf --enable-libmfx --enable-gpl --enable-avisynth --enable-frei0r --enable-filter=frei0r --enable-librubberband --enable-libvidstab --enable-libx264 --enable-libx265 --enable-libxvid --enable-libxavs --enable-avresample --extra-cflags='-mtune=generic' --extra-cflags=-O3 --enable-static --disable-shared --prefix=/ffmpeg-windows-build-helpers/sandbox/cross_compilers/mingw-w64-x86_64/x86_64-w64-mingw32 --enable-nonfree --enable-decklink --enable-libfdk-aac
  libavutil      56. 38.100 / 56. 38.100
  libavcodec     58. 65.103 / 58. 65.103
  libavformat    58. 35.102 / 58. 35.102
  libavdevice    58.  9.103 / 58.  9.103
  libavfilter     7. 71.100 /  7. 71.100
  libavresample   4.  0.  0 /  4.  0.  0
  libswscale      5.  6.100 /  5.  6.100
  libswresample   3.  6.100 /  3.  6.100
  libpostproc    55.  6.100 / 55.  6.100
[concat @ 0000026f3b991040] Impossible to open 'D:\Music\!Audiobooks\Jacqueline Carey\Kushiels'
C:\Users\Carina\OpenAudible\tmp\1589173350674.txt: No such file or directory

**Comment by openaudible** [comment]
Not sure what happened. I didn't see any of the expected log messages when joining files. Make sure you select multiple audio files. OA creates a text file that contains all the files to convert. I can't tell if the text file couldn't be opened or one of the files inside can't be opened or if there was a mistake in the text file. Another line in the log should have said: "Text file contents:" followed by the text file contents. The files to be  joined also have to be able to be read and the output directory needs to be able to be written to.

**Comment by openaudible** [comment]
Added logs.. Give it another shot.. And copy and paste the whole log.. Or send a bug report. Also see note above.
