### ISSUE TITLE
Cannot sync library

### ISSUE THREAD

**Issue by wormyren** [openaudible/openaudible#36]
I get this message in the log window:
INFO: Warning, problem parsing book: Dune error: required:product_id missing from Dune
Oct 01, 2018 8:50:20 PM org.openaudible.audible.LibraryParser parseLibraryFragment

For each book in my library. So it can see them on my account but can't retrieve some asset needed to download the files? It also will not display these titles in OpenAudible even though they are in my library on the browser. The setting about the download manager is unchecked so that's not it, any other troubleshooting suggestions? Thank you in advance!

**Comment by r3lax** [comment]
I have the same issue on a fresh install.

**Comment by openaudible** [comment]
Looks like Audible removed the ability to "download" files from the library page html page. 
This breaks a number of things for us. Not sure if possible to fix. You may be able to download the AAX files using an audible supported Audible Manager (Audible Manager, Audible Download Manager) and let OpenAudible still convert etc.. but this is now a known bug and presents a real problem.

**Comment by openaudible** [comment]
Update. It looks like you may just need to toggle a setting in your audible account prefs.
Symptom: When you view your library and click on a download button, you should get a download of some kind, not be redirected to a /howtolisten page. If you're getting the how to listen page, you need to change a setting:

Audible: -> Account Details -> Update Settings
Check the box that says Software Verification Check for Audible Download Manager

Feel free to confirm.

**Comment by r3lax** [comment]
I've confirmed the box is unchecked, and has been.  Still having the same issues.

**Comment by minexew** [comment]
What @r3lax said. My account is on the free 30-day trial if that makes a difference.

**Comment by wormyren** [comment]
> Update. It looks like you may just need to toggle a setting in your audible account prefs.
> Symptom: When you view your library and click on a download button, you should get a download of some kind, not be redirected to a /howtolisten page. If you're getting the how to listen page, you need to change a setting:
> 
> Audible: -> Account Details -> Update Settings
> Check the box that says Software Verification Check for Audible Download Manager
> 
> Feel free to confirm.

It worked!

**Comment by minexew** [comment]
FWIW, the Audible website doesn't let me download an AAX file either, instead it serves me an `admhelper.adh`

**Comment by theOryol** [comment]
> Update. It looks like you may just need to toggle a setting in your audible account prefs.
> Symptom: When you view your library and click on a download button, you should get a download of some kind, not be redirected to a /howtolisten page. If you're getting the how to listen page, you need to change a setting:
> 
> Audible: -> Account Details -> Update Settings
> Check the box that says Software Verification Check for Audible Download Manager
> 
> Feel free to confirm.

Worked for me also

**Comment by ishiharas** [comment]
Hello everyone, 
on os x I still have a similar issue as mentioned previously. 
The checkbox in my audible settings is set on true, but openAudible can't get my library correctly.
Is it possible, that this will only continue to work on windows? 
This is the output I get in the console: 
```

INFORMATION: Command: Quick_Refresh
Jan 08, 2019 8:30:15 PM org.openaudible.audible.AudibleScraper _fetchLibrary
INFORMATION: ******************* LIBRARY PAGE 1
Jan 08, 2019 8:30:15 PM org.openaudible.audible.AudibleScraper setPageFilter
WARNUNG: setPageFilter Unimplemented
Jan 08, 2019 8:30:15 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Das goldene Garn - Teil 1: Reckless 3,duration=7 Std. 38 Min.,
Jan 08, 2019 8:30:15 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Das goldene Garn - Teil 2: Reckless 3,duration=6 Std. 50 Min.,
Jan 08, 2019 8:30:15 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Die Stimmen des Abgrundes - Teil 1: Demon Zyklus 6,duration=8 Std. 40 Min.,
Jan 08, 2019 8:30:15 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Die Stimmen des Abgrundes - Teil 2: Demon Zyklus 6,duration=8 Std. 42 Min.,
Jan 08, 2019 8:30:15 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Das Leuchten der Magie - Teil 1: Demon Zyklus 5,duration=10 Std. 20 Min.,
Jan 08, 2019 8:30:15 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Das Leuchten der Magie - Teil 2: Demon Zyklus 5,duration=10 Std. 10 Min.,
Jan 08, 2019 8:30:15 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Aufgespießt - Teil 1: Die Chronik des Eisernen Druiden 8,duration=4 Std. 28 Min.,
Jan 08, 2019 8:30:15 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Aufgespießt - Teil 2: Die Chronik des Eisernen Druiden 8,duration=4 Std. 20 Min.,
Jan 08, 2019 8:30:15 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Aufgespießt - Teil 3: Die Chronik des Eisernen Druiden 8,duration=4 Std. 10 Min.,
Jan 08, 2019 8:30:15 PM org.openaudible.util.HTMLUtil debugHtml
INFORMATION: Debug: /Users/ishiharas/Library/OpenAudible/tmp/empty lib page.html
Jan 08, 2019 8:30:15 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Library page contains: 0 book(s)
Jan 08, 2019 8:30:15 PM org.openaudible.audible.AudibleScraper _fetchLibrary
INFORMATION: pageNum=1 total=0 new=0 partial=0
Parsed:0 books

Jan 08, 2019 8:30:15 PM org.openaudible.Audible updateLibrary
INFORMATION: Updated 0 books

```
