### ISSUE TITLE
No VBR header after updating to OpenAudible v. 2.0.7

### ISSUE THREAD

**Issue by ltsjoe** [openaudible/openaudible#362]
I noticed the MP3 I had converted today was not indicating the correct duration. I checked it with MP3val and it's stating that the VBR header is missing. I had upgraded from v. 2.0.1 to v. 2.0.7 after noticing 2.0.1 no longer launched on my Windows 10 machine. I also updated my Ubuntu machine to v. 2.0.7 and it is giving me the same issue.

Analyzing file "C:\temp\The Outcast Dead The Horus Heresy, Book 17.mp3"...
WARNING: "C:\temp\The Outcast Dead The Horus Heresy, Book 17.mp3": VBR detected, but no VBR header is present. Seeking may not work properly.
INFO: "C:\temp\The Outcast Dead The Horus Heresy, Book 17.mp3": 2129608 MPEG frames (MPEG 2 Layer III), +ID3v2, no VBR header
Done!

**Comment by ARx6WtNN7Z7em** [comment]
I have the same problem on v. 2.0.7 it seems. I am not able to verify the technical part of this issue, but my converted MP3 is not indicating the correct duration in the audio player i am using. This is resulting in a file that plays, but if i try to skip ahead, pause or rewind the track jumps to a random place in the beginning of the track. Making it impossible to listen to audio books.

**Comment by ltsjoe** [comment]
> 
> 
> I have the same problem on v. 2.0.7 it seems. I am not able to verify the technical part of this issue, but my converted MP3 is not indicating the correct duration in the audio player i am using. This is resulting in a file that plays, but if i try to skip ahead, pause or rewind the track jumps to a random place in the beginning of the track. Making it impossible to listen to audio books.

 ARx6WtNN7Z7em you can use the opensource program [MP3Val](http://mp3val.sourceforge.net/) to check the audio file and confirm that it's a lack of VBR header in the MP3 file. From your description it sounds just like my issue though.

**Comment by ARx6WtNN7Z7em** [comment]
Thanks for the tip ltsjoe. I got the following result: 

Analyzing file "Secret History Mistborn.mp3"...
WARNING: "/OpenAudible/mp3/Secret History Mistborn.mp3" (offset 0x4c187): MPEG stream error, resynchronized successfully
WARNING: "/OpenAudible/mp3/Secret History Mistborn.mp3": VBR detected, but no VBR header is present. Seeking may not work properly.
INFO: "/OpenAudible/mp3/Secret History Mistborn.mp3": 757928 MPEG frames (MPEG 2 Layer III), +ID3v2, no VBR header
Done!

**Comment by openaudible** [comment]
Can you try this version and let me know? 
https://openaudible.org/prerelease

**Comment by ltsjoe** [comment]
> 
> 
> Can you try this version and let me know?
> https://openaudible.org/prerelease

I downloaded the prerelease, uninstalled the previous install, installed the prerelease, downloaded the file again and converted it. It's still giving the same VBR header error and the duration is still messed up. MP3val is giving the same output as well.

Analyzing file "C:\temp\The Outcast Dead The Horus Heresy, Book 17.1.mp3"...
WARNING: "C:\temp\The Outcast Dead The Horus Heresy, Book 17.1.mp3" (offset 0x7432c): MPEG stream error, resynchronized successfully
WARNING: "C:\temp\The Outcast Dead The Horus Heresy, Book 17.1.mp3": VBR detected, but no VBR header is present. Seeking may not work properly.
INFO: "C:\temp\The Outcast Dead The Horus Heresy, Book 17.1.mp3": 2129608 MPEG frames (MPEG 2 Layer III), +ID3v2, no VBR header

**Comment by ARx6WtNN7Z7em** [comment]
Im getting the exact same result with the appimage of the prerelease as well. Doing the same procedure as Itsjoe.

Analyzing file "Secret History Mistborn.mp3"...
WARNING: "/OpenAudible/mp3/Secret History Mistborn.mp3" (offset 0x4c187): MPEG stream error, resynchronized successfully
WARNING: "/OpenAudible/mp3/Secret History Mistborn.mp3": VBR detected, but no VBR header is present. Seeking may not work properly.
INFO: "/OpenAudible/mp3/Secret History Mistborn.mp3": 757928 MPEG frames (MPEG 2 Layer III), +ID3v2, no VBR header
Done!

**Comment by openaudible** [comment]
OK. I uploaded a new prerelease.  https://openaudible.org/prerelease
Be sure to delete any old mp3's that are broken (Sorry!)
I've tested Mac and Windows and seems OK.

The problem I have is there are 3 or 4 known bugs in ffmpeg.. and the latest versions of ffmpeg 4.2 binaries don't include the latest MP3 LAME encoder with the bug fixes..  I don't totally know how that VBR bug gets in there either. Ugh! 

THANK YOU for the reports and tip about the MP3Val scanner. 

Let me know and I'll wrap these changes into a new 2.0.8.

**Comment by ARx6WtNN7Z7em** [comment]
Thank you so much for looking in to this so fast mate! 

Im using the Linux GTK (x64) AppImage.

Ok so something changed. Now i can navigate an audiobook on my pc, that was not possible before. The length of the file (audio track) is still off. But i can skip ahead, pause or rewind the track without the previous error. On my pc (Manjaro Linux) i am using "Lollypop" to play the mp3. However, the mp3val check is giving the same result as before and the previous error is still present when i try playing the mp3 file on my phone. On my phone i am using the app AudioAnchor.

**Comment by ltsjoe** [comment]
Windows build appears to be working now on my end as well. The MP3 file is listing the correct duration. Tracking seems to be working and both VLC and Plex show the correct duration. MP3val is listing the file as good as well.

The Linux build still needs some work on it. Out of that 15.5 hour book, it's only grabbing half of it. Maybe it's my laptop's connection? I'm running Ubuntu 20.04 on my laptop. The deb file wouldn't download, but the SH file installed correctly.

**Comment by openaudible** [comment]
Ok. Looks like the AppImage builder was busted. I posted a new version on the prerelease site. No other files have been updated. 
Again, thanks.

**Comment by openaudible** [comment]
Fixed in 2.0.8.
