### ISSUE TITLE
License not activating openaudible

### ISSUE THREAD

**Issue by jonbugg** [openaudible/openaudible#363]
<img width="858" alt="Screen Shot 2020-05-18 at 4 15 01 PM" src="https://user-images.githubusercontent.com/65567200/82255512-c4ec9c00-9922-11ea-8227-d25262d291b4.png">
I purchased a license, but it is not working to activate the program.

**Comment by openaudible** [comment]
Something is preventing a  secure connection... There is a manual license method in the URL 
https://openaudible.org/license
You're on Windows?
