### ISSUE TITLE
Split to chapter as optional default

### ISSUE THREAD

**Issue by milegrin** [openaudible/openaudible#364]
Please add the ability to automatically convert all books by chapter as part of the conversion process with the ability to specify path & file name (default in most if all ripping apps)
EG : VLC - https://wiki.videolan.org/Documentation:Format_String/
Which has the following expansion are performed:
*  $a : artist
*  $b : album
*  $c : copyright
*  $d : description
*  $e : encoded by
*  $f : total decoded frame count (since VLC started)
*  $g : genre
*  $l : language
*  $n : track number
*  $o : track total
*  $r : rating
*  $t : title
*  $u : url
*  $A : date
*  $B : audio bitrate (in kb/s)
*  $C : chapter (as in DVD chapter number)
*  $D : duration
*  $I : title (as in DVD title number)
*  $N : name (media name as seen in the VLC playlist)
*  $O : audio language
*  $R : rate
*  $S : audio sample rate (in kHz)
*  $T : time code of the video
*  $U : publisher
*  $<any other char> : <any other char> (for example: $$ transforms to $)
*  Convert all to lower case
*  Remove spaces

So : $a/$b/$a-$t-$nof$0.mp3
Would translate to: /<path to openaudible mp3 directory/book_author/album_name/book_author-book_title-01of12.mp3   (assuming lower case & no spaces selected)

**Comment by openaudible** [comment]
It's marked as a feature request. But that's a lot of work.. and well, we export to csv and json and web, etc... so easy to hire a programmer to write a little script.

**Comment by milegrin** [comment]
Never mind
I have managed to cobble together a shell script to this all and more with re-get (restart failed failed downloads) etc so no longer need openaudible for that
Extracting the book details was nice but doing that manually to a NFO is not a major issue; was doing it mostly myself anyway since OpenAudible can't.
