### ISSUE TITLE
Audible India Account

### ISSUE THREAD

**Issue by sharadaprasad** [openaudible/openaudible#365]
Hello there,

Thank you for this beautiful piece of software. 

I have Audible India account and I could not access my account as openaudible always connects to Audible.com while I use audible.in

Will you be adding audible account support for other countries soon?

best,
Sharada

**Comment by Bhlowe** [comment]
Just use the built in browser to log into your India account and it will work and remember your region.

**Comment by openaudible** [comment]
Just log in to your audible account and it should work in your region.

If that was you who submitted a bug report, some audible titles are not downloadable, including podcast episodes, "free" titles, romance series, etc.
