### ISSUE TITLE
Offer 64-bit RPMs.

### ISSUE THREAD

**Issue by jtagcat** [openaudible/openaudible#366]
Major distros are dropping 32-bit support, please offer 64-bit RPMs.
RPMs and DEBs should also reach repos, it's quite annoying having to download and update the rpm yourself and does not scale.

**Comment by openaudible** [comment]
All our releases should be 64bit only AMD64. We don't have anything that runs on 32bit. 
We label them x86_64, which is the same as AMD64.
What makes you think our rpm is 32bit? Let me know if we made an error in our packaging/installers.

**Comment by jtagcat** [comment]
```
$ dnf info OpenAudible
[output ommited by jtagcat]
Installed Packages
Name         : OpenAudible
Version      : 2.0.8
Release      : 1
Architecture : i386
Size         : 391 M
Source       : (none)
Repository   : @System
From repo    : @commandline
Summary      : 
URL          : http://openaudible.org
License      : 
Description  : OpenAudible
```
I saw i386 as the architecture while installing with `$ sudo dnf install ./longpackagename.rpm`.

**Comment by openaudible** [comment]
That is the install4j launcher which is a 3rd party installer.
I assume it runs in 32bit but launches the 64 bit jre.
