### ISSUE TITLE
Split By Chapter: Append chapter names to splitted files.

### ISSUE THREAD

**Issue by jtagcat** [openaudible/openaudible#367]
Some books have chapter titles, instead of splitting as `$book_title 01.mp3`, `$book_title 02.mp3` and so on, split as `$book_title 01 $chapter_title_1.mp3`, `$book_title 02 $chapter_title_2.mp3`.

**Comment by jtagcat** [comment]
Duplicate of #153

**Comment by openaudible** [comment]
Still listed as a feature request in #153.

**Comment by jtagcat** [comment]
Thought closed issues (even feature requests) count as wont-implement, unless otherwise noted on GH/GL issue trackers.
