### ISSUE TITLE
Frequent crashes

### ISSUE THREAD

**Issue by jtagcat** [openaudible/openaudible#369]
While using the app today, it crashed around 1-2 times per book. This is unacceptable for a paid product.

I noticed that most of the crashes occurred while interacting with the built-in browser, sometimes while opening a page or even interacting with it, but most often, when closing the browser.

OpenAudible would always hang indefinitely, even when waiting after gnome prompted to kill the app, it did not revive.

If the app gets killed, while in the middle of a conversion, ffmpeg keeps running in the background, taking up a considerable amount of resources. After re-opening, you could start the conversion again. I would question, what would happen when the old and new ffmpeg instances collided.

**Comment by openaudible** [comment]
I am not aware of any known issues with random crashing with the web browser. It usually either works or it doesn't. I test on mac, windows, ubuntu and centos, but have limited ability to test on all the different flavors of linux desktop systems. 

If you are seeing crashes, a log file or bug report would be appreciated. 

To do this, you can run OpenAudible from the command line. 

cd to the openaudible directory ( /opt/openaudible?) and there should be a ./debug_linux.sh file you can run. (which basically calls:

` java -cp "openaudible-jar-with-dependencies.jar:org.eclipse.swt.gtk.linux.x86_64-4.6.jar" -Dfile.encoding=UTF-8 org.openaudible.desktop.Application
`

If/when it crashes, you may see an error in the terminal, or the JRE may dump a hs_xxx error file.

From there, you can inspect it or send it to me openaudible at email.tg Most root errors can be googled to find the underlying cause. 

Our software uses eclipse swt libraries to do cross platform desktop app. We write once, run on many systems..  but are unable to edit the underlying C code that runs behind the scenes to manage desktop.

**Comment by openaudible** [comment]
Closing. Feel free to post error logs or messages from message above.
