### ISSUE TITLE
[Help] 40kbps is the highest bitrate possible?

### ISSUE THREAD

**Issue by raiytu4** [openaudible/openaudible#37]
Hi,

I download the aax file from audible (Audio Quality Enhanced selected) the file was 236mb, after the conversion, the output file is 175mb 40kbps 22khz. Is this the maximum quality I can get? If not, how can I configure it or it depends on the source file?

Thank

**Comment by nessguy** [comment]
The bitrate of audio books is surprisingly low. That said, I've made a branch that allows you to set the audio quality of the conversion. I'll see about putting in a pull request when I get home from work tonight.

**Comment by raiytu4** [comment]
@nessguy thanks for the response, I am looking forward to seeing results from you

**Comment by openaudible** [comment]
Changing the qaScale quality in ConvertJob from 6 to 4 should do the trick. Trying to keep the UI simple, but could add it to the prefs if someone really wanted it higher or lower. 
Have been working on a new version and will add.. but happy to look at a pull request!

**Comment by openaudible** [comment]
OK. Got new version 1.2 out and it bumps the quality and writes the value to the settings.

**Comment by raiytu4** [comment]
I've tried the 1.2.0
The size is bigger but the quality is still the same. I determine it via a program called Spek

1.1.7 175mb the spectrum is at 10kHz
![bk_hcuk_003089 - from openaudible 1 1 7 mp3](https://user-images.githubusercontent.com/25586304/46567773-6ba94200-c963-11e8-968f-5f6c15ea943a.png)


1.2.0 258mb the spectrum is at 10kHz
![bk_hcuk_003089 mp3](https://user-images.githubusercontent.com/25586304/46567791-d490ba00-c963-11e8-96c1-00e4d4a40367.png)



A typical mp3 128kbps usually have 16kHz in its spectrum.
![th ng nhi u h n noi - nhom nh c - nh c rap vi t hay nh t v tinh yeu - various artists - album 320 lossless mp3](https://user-images.githubusercontent.com/25586304/46567779-824f9900-c963-11e8-819d-a8d269a27de5.png)


So the problem is we don't know what the original spectrum value of the source from audible. From this value, we can produce a perfect mp3 file since we don't want the output file size is too big or too small

I planned to record the audio from audible while it's playing through my computer and inspect the recorded file via Spek to see the actual spectrum. Any thought on this?

**Comment by MRGEE223** [comment]
I know this one is old, but I have 1.5.5 and there is no spot to change the bitrate. 32K is what VLC says mine are converting to.
I would like 112 or even 96.  
Is there a way to do this I am not seeing?
