### ISSUE TITLE
Feature Request: Enable QuickSync for FFmpeg

### ISSUE THREAD

**Issue by Etumos** [openaudible/openaudible#373]
I would like to take advantage of Intel Quick sync that is available in FFmpeg please add an option that will allow this to be added into the FFmpeg command.
example:
`ffmpeg -hwaccel vaapi -hwaccel_device /dev/dri/renderD128 -hwaccel_output_format vaapi`

From the FFmpeg docs:
-hwaccel[:stream_specifier] hwaccel (input,per-stream)
Use hardware acceleration to decode the matching stream(s). The allowed values of hwaccel are:

none
Do not use any hardware acceleration (the default).

auto
Automatically select the hardware acceleration method.

vdpau
Use VDPAU (Video Decode and Presentation API for Unix) hardware acceleration.

dxva2
Use DXVA2 (DirectX Video Acceleration) hardware acceleration.

vaapi
Use VAAPI (Video Acceleration API) hardware acceleration.

qsv
Use the Intel QuickSync Video acceleration for video transcoding.

Unlike most other values, this option does not enable accelerated decoding (that is used automatically whenever a qsv decoder is selected), but accelerated transcoding, without copying the frames into the system memory.

For it to work, both the decoder and the encoder must support QSV acceleration and no filters must be used.

This option has no effect if the selected hwaccel is not available or not supported by the chosen decoder.

Note that most acceleration methods are intended for playback and will not be faster than software decoding on modern CPUs. Additionally, ffmpeg will usually need to copy the decoded frames from the GPU memory into the system memory, resulting in further performance loss. This option is thus mainly useful for testing.

-hwaccel_device[:stream_specifier] hwaccel_device (input,per-stream)
Select a device to use for hardware acceleration.

This option only makes sense when the -hwaccel option is also specified. It can either refer to an existing device created with -init_hw_device by name, or it can create a new device as if ‘-init_hw_device’ type:hwaccel_device were called immediately before.

-hwaccels
List all hardware acceleration methods supported in this build of ffmpeg.

**Comment by openaudible** [comment]
If hardware acceleration makes sense, I'd rather leave it up to the ffmpeg developers to use it when it makes sense. 

Have you done a test to see how much it improves performance?  We echo all ffmpeg command to the console so it should be easy to copy and paste the command and add the extra arguments. 

Maybe if it sped things up 50% I could see adding it.. but encoding happens in the background.. and adding anything to ffmpeg out of the ordinary adds the risk of breaking things on some percentage of users.  I've run into 4 ffmpeg bugs that creep in are a pain to make sure all platforms avoid.

**Comment by Etumos** [comment]
Yes I use this in particular for many things from transcoding via tdarr to plex. It makes a significant difference if you have the cpu enabled. Example when doin my library yesterday it was pegging the cpu out at 100% across all cores. but on the same machine in tdarr I can run 4 transcodes at once and only see 40% cpu usage.

**Comment by Etumos** [comment]
I think the thing that would be most useful is to allow the users to have the ability to do custom FFmpeg scripts. Its all just passing via CLI anyhow.

**Comment by openaudible** [comment]
Unless you run a test that shows otherwise, I'm going to assume GPU flags won't make much of a difference. The encoding is done using the LAME MP3 library-- which knows nothing about new flags for GPU optimization. 

Adding extra args is a possibility, but I am trying to avoid feature creep.

**Comment by Etumos** [comment]
I certainly understand feature creep as an issue. In this case I think it is more of an issue during initial or bulk imports. They are just not friendly to using your computer for anything else while they occur whic his not a great user experience for paid for software.

**Comment by openaudible** [comment]
You can edit the settings.json file to change the number of concurrent ffmpeg conversions. I think 3 is the default value.
