### ISSUE TITLE
Does not download the whole book for Audible India

### ISSUE THREAD

**Issue by sharadaprasad** [openaudible/openaudible#374]
Hello there,

I have an Audible India as well as an Audible US account. Open Audible downloads multi-part audio books as one mp3 for Audible US account but it only downloads first part for Audible India account. Just wanted to bring this issue to your notice and understand how I can download all parts of the book

regards,
Sharada

**Comment by openaudible** [comment]
Thanks for the report.

Is this all books or just some? Did you import any AAX files or was this just using the OA browser?

When you are viewing your library, you should see a download button near your book. There may also be a button that lets you download it as "parts". We use logic to determine what is the "whole book" and what is the parts--this has been known to change depending on the region. 

It may be different in India. Can you view the book in question in your "Library" view on the OA browser.. and send a bug report from the About menu with reference to 374? That will send us some HTML that will help us fix it. 

Or let me know the name of the book you're seeing this with and I can perhaps have someone buy the book and take a look.

**Comment by openaudible** [comment]
Fixed in 2.0.9.

**Comment by openaudible** [comment]
Shoot. Just did a test and looks like one more broken thing in India. Stand by for 2.1
