### ISSUE TITLE
this is ... going to be a big issue

### ISSUE THREAD

**Issue by Butterfly-Dragon** [openaudible/openaudible#375]
![image](https://user-images.githubusercontent.com/33538906/82941743-2eaa1d00-9f97-11ea-87e2-7bdf92b1d42e.png)
uhm.... OUCH! 😅

**Comment by LanceMcCarthy** [comment]
I was coming here to open an issue, lol. You beat me by 6 minutes :)

However, it looks like you can still keep using M4A by changing a setting in your account https://audible.custhelp.com/app/answers/detail/a_id/5116/kw/enhanced%20format

**Comment by freeAgent85** [comment]
@LanceMcCarthy I'm not sure that option will still exist after 6/30/2020. The way it sounds to me, they are removing the option to use different formats and everything available for download will be in the "Enhanced" format. It seems like as a side effect they're going to break compatibility with older Audible-compatible MP3 players.

**Comment by Butterfly-Dragon** [comment]
yup
that said is this going to be an issue?
from wha i understand i have been downloading in format 4 because i was downloading with openaudible in order to get mp3s

**Comment by openaudible** [comment]
I believe OpenAudible actually prefers Enhanced downloads over Format4 audio files, as they currently show in the library download format selector. 

But if audible removes the ability to download titles from the library page, that will certainly be a problem.

**Comment by freeAgent85** [comment]
I think OpenAudible downloads AAX files (at least by default) and converts to MP3 from there, so perhaps it is already using the "Enhanced" format. Since Audible's email and naming conventions are pretty vague, I really don't know.

**Comment by LanceMcCarthy** [comment]
I don't think we have to worry about (at least not yet) from the language they used:

_Your Audible titles are yours to keep and will be available for download in the new, higher-quality audio format._

As long as OpenAudible can convert the Enhanced Format type to mp3, and we can download from our account, we're safe.

**Comment by Butterfly-Dragon** [comment]
all the files i have ever seen were AAX, if anything, but it says i have been downloading format 4 (AAC) for some reason.

**Comment by Hooey** [comment]
I hope it's not an issue. I just bought a license for OpenAudible two days ago!

**Comment by alehel** [comment]
Every one of my audible books was downloaded by OpenAudible in the aax format. I imagine this isn't an issue, as OpenAudible will probably continue to function as before. I always make sure to download and convert to M4A as soon as i purchase a new book though, just in case they change their encryption one day.

**Comment by Butterfly-Dragon** [comment]
I prefer split chapter MP3 it's more compatible and more digestible by players everywhere.

And i don't have to worry about finding again chapter and minute if my phone gets touched mid-reproduction.

It would not be the first time i lose a bookmark because of me "picking up my phone wrong" and daring to touch the screen...

...or an update or something.

At least this way i have at most to restart the latest chapter. 😅

Plus, books of 24+hour seem to be rather... hard to digest for most players.

Aaaand with split-chapter MP3s i can do more easily a "wipe all metadata and put the metadata i tell ya" thing which with M4A or "chaptered" MP3s is... finnicky as you can lose the chapter bookmarks depending on where or how the metadata is stored.

(not accounting also for the fact that some players read the chapters on some metadata, other players read it on different metadata).

Soooo losing the proprietary Audible format with its crappy player that insists i should listen from the cloud and therefore stops me from listening many books... is the main reason why i switched to OpenAudible.

I might be paying for the privilege, but... i mean... >freedom<. *hair swoosh*

**Comment by openaudible** [comment]
I'm going to close this until there is something that can be done. Marked as: Watch for future changes.
