### ISSUE TITLE
Frequent Crashes on 2.0.8

### ISSUE THREAD

**Issue by JamesSwift** [openaudible/openaudible#376]
I'm experiencing frequent crashes with 2.0.8. Audiobooks are often truncated when converting, if you press "Show MP3" the folder opens but the application locks up. Sometimes it crashes just doing nothing. If you tell me where to find crash dumps I'll submit them. For now I've reverted to 2.0.7 to see if it helps.

**Comment by openaudible** [comment]
Check out the answer on #369 for logging crashes. 

But most crashes are due to the operating system not playing well with the "eclipse swt widget desktop library". They might be related to extensions on your OS (are you Mac, Windows or linux?), anti-virus, low-memory, low-disk space, etc.

**Comment by openaudible** [comment]
FYI, I updated the debug scripts in 2.0.9, released today. To use:
open the command line, cd to the OpenAudible application directory.
(For Mac, its /Applications/OpenAudible/Contents/Resources/app )
Then there is a debug_xxx script (mac,win,linux) that starts the app in the console.
If you get a crash, feel free to send a bug report from the application or email us, or open a new issue with details (platform, memory, etc.)
