### ISSUE TITLE
Feature Request: Keyboard Shortcut for File > Join Audio Files

### ISSUE THREAD

**Issue by brianbeergod** [openaudible/openaudible#379]
I would like to request a new simple feature - could you add a keyboard shortcut for the option to join audio files?

I think something like Control/Command + J would work for this use case.

**Comment by openaudible** [comment]
Done in 2.1.1

**Comment by brianbeergod** [comment]
Awesome. Thank you very much!

**Comment by brianbeergod** [comment]
Tested and confirmed that it's working in 2.1.1.

Thank you again.
