### ISSUE TITLE
Audible Escape Borrow History

### ISSUE THREAD

**Issue by traviam** [openaudible/openaudible#381]
I just purchased your product and it's by far better that the information available through a script. However, one key component that I am hoping can be added is the borrow history? I have the Audible Escape plan (yes, I love romance/erotica books - don't judge) and need to know which books I have already borrowed.

![image](https://user-images.githubusercontent.com/66137407/83292313-7e633100-a1af-11ea-9f41-66f2046e438c.png)

**Comment by openaudible** [comment]
Adding as a feature request. 

But we mostly just want to work with books you purchase individually. So it isn't high on the list.  

I would point you to something like "GoodReads" to keep track of all the books you've actually read and want to read.

But thanks for the compliment and appreciate the suggestion!
