### ISSUE TITLE
Pause Conversion

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#383]
Is there any way to pause the conversion process once underway?

**Comment by oboe45** [comment]
Is there any way to see which files are actively being converted or downloaded?  If I click downloading or Converting it shows the entire queue for each instead of a short list of those actually being processed.

**Comment by oboe45** [comment]
The "Action" menu contains a "Cancel Job" action.  I have conversion running and downloads happening - which of these (or both?) are stopped if I click Cancel Job.

**Comment by openaudible** [comment]
No, you can't pause conversions. 

No, there is no way to just show exactly what books are downloading/converting... You could check the log window.. Or click on each book to find the one with the State: that shows what it is doing. 

Cancel action will cancel conversions or downloads, depending on which action is taking place. (Both can't be happening to the same book, but selecting multiple books and canceling would stop any books download OR converting.

**Comment by oboe45** [comment]
Pause - OK - just asking

Show status at book level - Hard to do if several hundred items are in queues. --But, again, just asking

What happens to the book that was undergoing conversion, presumably the AAX file is intact and any partial conversion is discarded.  Similarly the download obviously stops and the partial download is discarded?

All of these apparently spurious questions are asked since the download and conversion is likely to take several days, and I wanted to see what if any conversion over the processes I have.  For example it seems to me - after running for 12 hours download and conversion, it is probably more efficient to run download and then conversion but not concurrently?

Thanks

**Comment by openaudible** [comment]
Just need to be patient. 
But canceling jobs will clean up any partial/temp files-- and should only be a few minutes of lost "work".  
Doing downloads and conversions at the same time is fine and probably faster in the long run. Switching to M4A as the format makes the conversions much faster.
