### ISSUE TITLE
Integrate freac’s superfast codec support

### ISSUE THREAD

**Issue by Strider3000** [openaudible/openaudible#385]
Freac devs engineered multithreaded conversion into LAME and enabled it for other codecs. Any way to integrate their hard work? I get a 4-8x speedup for conversions to mp3 over ffmpeg. It could save an enormous amount of conversion time in open audible for multi thread machines.

https://www.freac.org/developer-blog-mainmenu-9/14-freac/290-freac-development-status-update-082018

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by openaudible** [comment]
Is this related to #384   No real plans to change anything. Happy to look at it if you have example code to show existing ffmpeg commands vs. freac.  Plus I need static binaries for mac,win,amd64.

**Comment by openaudible** [comment]
I'm going to close this. If you find a version for mac, linux and windows that is LGPL or free, and you have scripts that does what ffmpeg does.. Please re-open or send a pull request.
