### ISSUE TITLE
Ability to view activation_bytes

### ISSUE THREAD

**Issue by solderjs** [openaudible/openaudible#386]
I'm assuming that the `activation_bytes` are either stored on the file system or in the system key chain.

How do I get access to that so that I can use it with other programs as well?

**Comment by solderjs** [comment]
Sleuthing around I was able to discover my activation bytes in the logs but... surely there is a nicer way?

```bash
grep -r activation_bytes /Users/aj/Library/OpenAudible/tmp/log.txt
```

Also, one of the books I imported was from a secondary account that I used to take advantage of a limited time deal a while back... and yet I didn't have to log into that account in order to retrieve the activation bytes. How can it be?

**Comment by openaudible** [comment]
The first rule of activation bytes...
