### ISSUE TITLE
mp3 error while seeking / unreliable seek

### ISSUE THREAD

**Issue by Zauberfisch** [openaudible/openaudible#388]
I've downloaded and converted a book to mp3 with openaudible.

Normal playback of the mp3 seems fine, but when I seek/jump to a specific position in the audio book, it's not consistent what sound is played at that point in time.

The book I tried is `Blood of Elves The Witcher, Book 1.mp3` which is about 10 Hours long.
If I click on the timeline and jump to 4:44:00 I hear "When I was younger, I ....". If I then seek to some other point and then back to 4:44:00 "Now I know she said suddenly ..."

Sometimes, the audio player also presents an error message, though not every time. (see read line at bottom)
![Screenshot_2020-06-07_09-09-17](https://user-images.githubusercontent.com/186158/83962608-fb249800-a89e-11ea-9705-274a3cedcf04.png)

Same behavior is experienced across different audio players, so I guess that's ruled out as the source of the problem.
It might very well be a ffmpeg problem though. But I am unsure and given that I didn't interact with ffmpeg directly (only used interacted with openaudible), I decided to report it here.

**Comment by openaudible** [comment]
We did have some earlier versions with a bad ffmpeg encoder, which caused some problems seeking. Can you delete the mp3 file and re-encode it and see if this is a current problem?

**Comment by Zauberfisch** [comment]
Oh, indeed. Sorry, I should have included that I converted those mp3s a few weeks ago.
The updated version seems to work fine now.
