### ISSUE TITLE
include mp3 metadata

### ISSUE THREAD

**Issue by rob-miller** [openaudible/openaudible#391]
Please adjust command(s) for joining mp3 chapters together to at least keep the metadata from the first chapter?  Currently the process for importing actually wipes out any existing tags, so not satisfactory to "manage all your audio books ".

As a side note / personal request, my interest is more in the "cross-platform audiobook manager" part rather than the "designed for Audible users" part.  I would really suggest playing with some mp3 audiobooks from OpenAudible and other sources like OverDrive and/or LibriVox to compare how they work in OpenAudible, mp3 players (displaying info and artwork), and just inspecting tags with e.g. id3v2.

**Comment by openaudible** [comment]
That is a good idea.. Will check that. And yes, was thinking librivox might be good to start integrating with..

**Comment by openaudible** [comment]
Try the new version 2.2.  There is no "standard" for audio books when it comes to joining.. but will make a stab at making it easier to browse and download librivox if I get some free time.
