### ISSUE TITLE
Unable to split file when sending to Network drive

### ISSUE THREAD

**Issue by WeyldFalcon** [openaudible/openaudible#392]
I am getting an error when I try to split mp3's into chapters
"Unable to split Name.mp3
Error:Unable to add artwork V:\Location\name.jpg to V:\Loacation\name 03.mp3
OK"
I have tried 2 different files and restarted my computer and made sure I was not downloading or converting at the same time.
Why is the software having trouble splitting the mp3? I don't actually care about adding the jpg can you fix this or at least fix it by adding an option to not add the jpg, I just want the files split I can manage the image myself later.

**Comment by WeyldFalcon** [comment]
I finally tried switching to the C drive and now it is working. Why does it not work on network drives? Some of these files get big, I want to keep them on my network not on my local drive. Can this be fixed for Network drives?

**Comment by openaudible** [comment]
Can you paste the full error message you're seeing from the Console?
I am able to split to a NAS mapped network drive.

**Comment by WeyldFalcon** [comment]
"Unable to Split file
Unable to split The Wretched of Muirwood Legends of Muirwood, Book1.mp3
Error:Unable to add artwork V:\Audio Books\Jeff Wheeler\Legends of Muirwood\01 The Wretched of Muirwood\The Wretched of Muirwood Legends of Muirwood, Book 1.jpg to V:\Audio Books\Jeff Wheeler\Legends of Muirwood\01 The Wretched of Muirwood\The Wretched of Muirwood Legends of Muirwood, Book 1.mp3"

**Comment by openaudible** [comment]
Hmm. Adding art wasn't supposed to be a fatal error. Will check on that before next release.

**Comment by openaudible** [comment]
Fixed in 2.2. Thanks for the feedback!
