### ISSUE TITLE
Unable to finish downloading any book.

### ISSUE THREAD

**Issue by SirPiken** [openaudible/openaudible#393]
Tested multiple books and restarted the program multiple times and I am unable to finish downloading any title.

**Comment by openaudible** [comment]
Can you paste the error message in the File: Console (CTRL-E)

**Comment by oboe45** [comment]
Every case is different I suppose, I downloaded my 800 plus Audible files and converted all of them to MP3 for local use - took days, but managed without a single hiccup.  Great product!
