### ISSUE TITLE
Unable to split file No chapter data

### ISSUE THREAD

**Issue by WeyldFalcon** [openaudible/openaudible#394]
I am getting this error
"Unable to split Calamity The Reckoners, Book3.mp3
Error:No chapter data available for this file."
I tried refreshing the file. No luck. Is there a way to go find the chapter data?
ID for this book if that helps is BK_ADBL_011760B019P7DVPE

**Comment by openaudible** [comment]
It's possible the AAX didn't have any chapter data (an error audible? Do chapters show in the audible app?)

You can try running "ffprobe" on the AAX and MP3 files. Command line knowledge required. 

Maybe delete the Mp3 and re-encode it?

You can also Quit OA, relaunch, try to split that book, then (if it fails), About: Send Bug Report with #394 as the subject. I can look at the full log and probe output.

**Comment by WeyldFalcon** [comment]
Deleting the mp3, aax and redownloading and reconverting did the trick. I will try just restarting the software next time.

**Comment by openaudible** [comment]
Strange. If it happens again, check the error log in the console.
Cheers
