### ISSUE TITLE
Split into chapter uses different tag versions

### ISSUE THREAD

**Issue by extrasqueaky** [openaudible/openaudible#395]
The functionality to split an existing mp3 (converted from aax) into separate chapters creates different tag versions. The first file tag is always ID3v2.4, while all the following tags have version ID3v2.3.

I use the Perl module MP3::Tag to mass update tags, and it's unable to update ID3v2.4 tags unfortunately, and that's why I stumbled about this inconsistency (using different tag versions).

**Comment by openaudible** [comment]
Ok. Confirmed. Looking into fixes.
