### ISSUE TITLE
Audiobook split not completing

### ISSUE THREAD

**Issue by 3vilpyro** [openaudible/openaudible#396]
I am seeing this error on multiple audiobooks (using version 2.1.1)

For example Gideon the Ninth should be splitting into 41 parts. 

Then I get this error at a random point
![Capture](https://user-images.githubusercontent.com/67028875/84835198-0d21db80-b001-11ea-9d6a-713a3466cccf.PNG)

and a duplicate file appears
![Capture2](https://user-images.githubusercontent.com/67028875/84835207-127f2600-b001-11ea-8a87-71ad7da03819.PNG)

The split then never completes

**Comment by openaudible** [comment]
I am re-writing the split/join code. Should be fixed for next release.

**Comment by openaudible** [comment]
Hopefully fixed in 2.2. Thanks for the feedback!

**Comment by 3vilpyro** [comment]
Thanks very much! So far so good!
