### ISSUE TITLE
Feedback on new "books" directory to replace "MP3" and "M4A" directories

### ISSUE THREAD

**Issue by openaudible** [openaudible/openaudible#398]
We're looking at making a change on how we save books in OpenAudible. 

We'll add a "Books" directory that can hold MP3, M4A, M4B, and directories. Directories that have audio files in them will be considered entire books, that could be imported from Librivox zip files.

We're also planning to do a better job supporting split books out of the box.. And working on those open split book issues. 

Any feedback will be appreciated..

**Comment by oboe45** [comment]
Definitely prefer the "Books" directory for saved location.  No bias on split books, I spend my time rejoining books that were split!

**Comment by mjoshd** [comment]
A centralized 'books' directory sounds like a good plan. treating some directories containing multiple files as a single book also sounds great. Looking forward to the improvements!

**Comment by rloomans** [comment]
I think it's a good idea.

You mention M4B... Does that mean a convert to M4B is on the roadmap and I don't need to file a feature request? :)

**Comment by openaudible** [comment]
M4B will likely be supported, but I'm not a fan because they require splitting to work on larger books. 1 book, 1 file is best! :) 
What audio player are you using that doesn't work with M4A but works for M4B?

**Comment by Geordon** [comment]
What’s “best” is really determined by the use case.


On June 24, 2020 at 12:44:02 PM, openaudible (notifications@github.com)
wrote:

M4B will likely be supported, but I'm not a fan because they require
splitting to work on larger books. 1 book, 1 file is best! :)
What audio player are you using that doesn't work with M4A but works for
M4B?

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/openaudible/openaudible/issues/398#issuecomment-648967129>,
or unsubscribe

**Comment by rloomans** [comment]
> M4B will likely be supported, but I'm not a fan because they require splitting to work on larger books. 1 book, 1 file is best! :)

I would agree that fewer is better, but I'm willing to trade off for other conveniences...  

> What audio player are you using that doesn't work with M4A but works for M4B?

I use the Books app on my iPhone and it's much easier to get the book added and synced if it's an M4B than both M4A or MP3.

**Comment by maphew** [comment]
1 file per book works when they're normal books. However I recently bought 3 "books" which are actually collections or a whole series in one file. At 1 to 2 GB each (50 to 70 hours) they're too big to put on my listening device.

I would like to see Split options where the file name and length are based on the chapter title (where available) and not just sequential numbers and arbitrary minutes. For example [Sherlock Holmes The Definitive Collection](https://www.audible.ca/pd/Sherlock-Holmes-The-Definitive-Collection-Audiobook/B07232B6H8) currently splits in to 125 files and there's no way to match those to the book and chapter list (see linked page).

**Comment by openaudible** [comment]
Chapter titles are difficult to get from Audible. It is possible and we have a little experimental code that does it. Seems to be available only on some books. 

@rloomans Thanks for letting me know the app.  You might be able to just change the file from .m4a to .m4b and drop it into "Books". I've tried it with iTunes and it seems to automatically set it as a book.

**Comment by archdeac0n** [comment]
Would it be possible to change the title to contain the chapter number instead of re-iterating the album name - it makes it easier to see where you got up to?

**Comment by drewblyth** [comment]
Like the idea of a Books directory: would also like to put forward the idea of making it compatible with Subsonic/Booksonic which has a seperate sub folder for each book containing audio file(s), description file and folder.jpg (book cover)

**Comment by SlowDowne** [comment]
Append 'preferences dialog' so that Split book filenames can be default named. i.e. [splitepath]\{title]\{title}-(author)-Chapter-{section}, etc... for example, similar to the model Handbrake uses to name output files (or VLC or just about every other mp3/m4a/m4v, etc... conversion program.

**Comment by unitof** [comment]
Was just going to ask for an option to convert to `m4b` extension instead of `m4a` (same file format, just different extension to designate it as "book" and have a different default application to open)! Love this new simplified directory.

**Comment by m3m0ry** [comment]
Having a book directory, where every book has its own folder, with all the data (mp3, mp4, aax, ...) as subfolders would be my preferred choice.
```
MainOpenAudibleFolder
    |--<Some Book>
        |--aax
        |--m4a
        |--mp3
        |--chapters
    |--<Some other Book>
        |--aax
        |--m4a
        |--mp3
        |--chapters
```
This would allow me to copy whole books, without the need of looking for splits.

**Comment by unitof** [comment]
My understanding was M4B is exactly the same spec as M4A, just with a different extension for easier assigning of a default app. So far I've always just been renaming the extension on my OpenAudible converted M4A files so they open in Books.app, and so far everything seems to work including 12h+ books.

@openaudible where does the spec requiring them to be split come from?

**Comment by kai-uwe-rommel** [comment]
About splitting books into single files for the original chapters:
I like this and always do it for the books after downloading and converting them to MP3.
I use https://github.com/gbouthenot/mp3splitter-js for this purpose and it works fine.
The chapter data is already in the MP3 files that OA creates when converting, apparently.

**Comment by openaudible** [comment]
I'm planning on migrating from .m4a to .m4b. I don't think there are any players that play ".m4a" that can't play ".m4b".

I'm still working on the books directory to support adding "split books" that may have been downloaded from other sources (librivox) or split using OpenAudible. 

Might make the .m4b change sooner and see if anyone freaks out that .m4a is no longer used.

**Comment by Geordon** [comment]
Yay, direct to m4b!

**Comment by stefwill** [comment]
It would be great is we could specify what elements we want in the path.
like: ~/books/{{Author}}/{{Title}}/{{Format}}/file.ext
