### ISSUE TITLE
Missing Download Link for all items

### ISSUE THREAD

**Issue by bjoernbusch** [openaudible/openaudible#399]
I'm on version 2.1.1., just bought a license and I'm working with audible.de. I'm on a mac. I can successfully log in and sync the library, but for all 147 books I'm getting missing link and none of them can be downloaded. From the log I can't really tell whether something is going wrong or whether something on the website structure changed and the link just can't be found.

In the library view I see the download links, in the individual items view there is no download link, but only a "listen now" link. When I manually navigate to the library and click the download link I get a `INFO: Unable to download:` in the log.

Let me know whether I should supply the log file or other additional information.

**Comment by openaudible** [comment]
You should see a "Download" button next to each book when you view your library. 

If not, check your settings: 
https://openaudible.org/settings.html

If that doesn't help, let us know what region youre in (US?). Also, the books need to be purchased by you-- (can't be podcasts or romance series, etc.)

**Comment by bjoernbusch** [comment]
Perfect, thanks, it was due to the 'Check for Audible Download Manager' setting, it was enabled. After a Full Refresh of the Library, it works now like a charm.
