### ISSUE TITLE
Domain name for audible.co.jp is wrong

### ISSUE THREAD

**Issue by cloud-dx** [openaudible/openaudible#4]
The current domain name in the software is audible.jp. The actual one is audible.co.jp.

Thank you for your efforts.

**Comment by openaudible** [comment]
Fixed for the next binary/installer release. All non-US regions remain experimental and rely on user reports like yours. Thanks.

**Comment by openaudible** [comment]
Fixed in the latest binary/source code release, version 1.1. Untested. Let me know..
