### ISSUE TITLE
Feature Request: Allow control over naming of converted files

### ISSUE THREAD

**Issue by rooneyp** [openaudible/openaudible#400]
Can we have a feature to allow customising the naming of converted files?

At the moment it seems to be based on book name, 
it would be great to have the option to name them with params like
 'book name'-'author'-'narrator'

also, fields like 'Release date', 'series' would be useful

**Comment by extrasqueaky** [comment]
I second that request, and would like to expand it to the "split chapter" functionality as well, 
e.g. having an option/preferences where you provide a pattern for the mp3/m4a/.. file name like this:
<Artist> - <Year> - <Title>

**Comment by openaudible** [comment]
Yes, saving as a feature request.
