### ISSUE TITLE
Metadata Titel seems to be empty

### ISSUE THREAD

**Issue by ApollonWrock** [openaudible/openaudible#401]
Just converted around 130 Audiobooks and out of them a most of them seem to have an empty 'Titel' in their metadata.

Instead, 'Album' seems to have all the actual names instead.

**Comment by openaudible** [comment]
Should be a meta data item called "title", not "Titel".  What format? MP3 or M4A? 
Have you tried with a program like ffprobe or "mp3Tag.exe" ?

**Comment by ApollonWrock** [comment]
My windows is in german, hence at least the visual is called Titel

MP3. And as said at a few it did work, at some others it didn't.

I used a 3rd-party tool for now and copied the album content to title.

 > Have you tried with a program like ffprobe or "mp3Tag.exe" ?
No I didn't. Anything special I should try?

**Comment by openaudible** [comment]
I'm having a hard time understanding the problem. 

Title should be set correctly in the application window (first column of table) and in the aax/mp4/mp3 files. 

Is title showing correctly in the application?

You could try deleting the mp3, then (if title is correct in table), select: Convert to MP3.
About: Send Bug Report (add 401 to description) 
(If the tags are not correct. Since I don't read German, please say: title should be xxxx, but instead is yyyy.

**Comment by ApollonWrock** [comment]
Ok I tried to re-create it.

as an example book I choose this one, but it happened with about 97% of all the books.
https://www.audible.de/pd/2001-Hoerbuch/B004V6UKHM

Given the example above I expected mp3 metadata of:

> Title: 2001: A Space Odyssey
> Album: Space Odyssey Series, Titel 

instead, it is

> Title: <empty>
> Album:  2001: A Space Odyssey

![grafik](https://user-images.githubusercontent.com/37675005/85382862-aab86600-b53f-11ea-9c52-1da918109326.png)


Steps to reproduce:

1. Sync account
2. Download the audiobook as aax.
--> Metadata of the book is shown correctly in openaudible.
--> Metadata of aax file in openaudible/aax is empty (expected i assume)

3. Converting aax to mp3 thorugh auto conversion
4. Metadata 'Title' of mp3 is empty. Instead, 'Album' seems to hold the desired content of 'title'




Test Setup: Windows 10
OPS Language: German (in case it does make a difference)

**Comment by openaudible** [comment]
Actually, the AAX file tags should be correct. Viewing the AAX in Windows should show the title, (subtitle blank). Will review the bug report. I should be able to set the title if it is blank in the AAX. 
Thanks for your help.. Will let you know if I need anything.
