### ISSUE TITLE
Not downloading complete AAX on long (splitted into multiple download parts) books

### ISSUE THREAD

**Issue by burk-castlehard** [openaudible/openaudible#402]
since audible setup that download-dialogue asking for 'download - complete / part 1 / part 2 / part 3' openaudible does not download the whole AAX file. So i get the info for the playtime of 31h 55min  (
as for example on Seveneves A Novel -- Neal Stephenson) but the downloaded file I get is only about 10hours of playtime. (download size by open audible is 316MB instead of 929MB that I get by using the webbrowser.)
So for large Audible books that are split into multiple parts open audible is useless for the moment.

**Comment by openaudible** [comment]
What format are you using for the file? It should be "Enhanced" which should have a download link for the entire book. Try setting the format to enhanced, which should be in the upper right on your library view in the web browser. 

If still unable, send a bug report from the About menu after viewing your library page. (Are you outside of the US?) 

Great book, by the way!

**Comment by burk-castlehard** [comment]
So I'm from Germany, and this setting is to "Beste Qualität" what should be equal to "enhanced". I tried downloading / converting from the file list in OpenAudible GUI not from the connected browser, IF using the browser everything is fine and i get the choice for 'part 1 / 2 / 3' OR even the 'complete book'.

The bug report is on its way. For everyone to read: Running Ubuntu Mate 20.04 LTS and OA 2.1.1

Thanks for that comment on the book ;) And just to clarify:  the problem is not only about downloading THIS book, it affects every multi-part book in my library.

**Comment by openaudible** [comment]
Can you give 2.2 a try.. I don't know if it is fixed.. but think I would hear more if all of germany was having the problem.. Maybe just linux and .de ? The "Full Download" link is what I need.. and the logic to determine which is the full download and what is the partial might need adjusting for some users.. Will check out that bug report.

**Comment by burk-castlehard** [comment]
Checked out 2.2. No change, still it prefers 'part 1' over the 'complete book' when downloading using the OA user interface.
I copied the links I can see when using my standard web browser:
Full download: https://cds.audible.de/download?asin=B00WNC5B6Q&cust_id=REMOVED&codec=LC_64_22050_Stereo&source=Audible&type=AUDI
Part 1: https://cds.audible.de/download?asin=B00WNC5FFI&cust_id=REMOVED&codec=LC_64_22050_Stereo&source=Audible&type=AUDI

**Comment by openaudible** [comment]
Thanks for the report. It does look like we were using the product id to determine whole vs. partial.. and you only have two seemingly random ASIN ID's for the two downloads. Will need to look more at that.

**Comment by Strider3000** [comment]
Having the same problem here (US) on "Jane Austen - The Complete Novels" which comes in 8 parts. I'll note that Audible software itself has issues downloading the parts for these books (Audible Sync for Windows does not work - only the official Microsoft Store Audible App works). Only the Microsoft Store Audible App allowed me to download each part individually (not the whole book). I was then able to use the OpenAudible "Import Books" option by pointing to a folder with all the parts. Even then, OA renamed all the parts to "Part 1, Part 2, etc" which made importing additional multipart books weird (subsequent .aax files were renames "Part1.1, Part2.1, etc". It would be helpful if OA could recognize multipart books and download each part and name them something intuitive (Like "<name of book> - <Part 1>", etc).

**Comment by openaudible** [comment]
@Strider3000 When you view your library in the OA browser, for the listing of "Jane Austin", there should be a Download button. 
 Hover over that button and there should be a "FULL" as well as Part 1, Part 2... OA is only supposed to download the FULL version. Can you try manually downloading the file marked "FULL"? Are other books working?

**Comment by Strider3000** [comment]
Hello, I was never able to download the "FULL" version, even with Audible's own software. I always had to download the file part by part.

**Comment by burk-castlehard** [comment]
Cannot confirm the bug is closed! Still not downloading the Stephenson book completly even using Version 2.3.1.

**Comment by burk-castlehard** [comment]
to clarify: if i do a "refresh info", the book shows a runtime of 31:55   and when i start downloading it ends at 300something MB and the runtime shown now tells me 10hours and something more. If i close OA and restart, it tells me its "redy to cenvert" and the runtime is switched back to 31:55, And, as expected the converted result is running for 10 hours and some minutes.
So still the complete download of a larger book won't work as expected and as it should.
Send out another bug report using the OA GUI  right now.
