### ISSUE TITLE
Feature Request: Split Multiple Books at once

### ISSUE THREAD

**Issue by ApollonWrock** [openaudible/openaudible#403]
It would be nice to be able to split multiple books at once/ as a batch job to modify all books in the library.

At the moment you would have to start splitting each books separately and only one after another.

**Comment by extrasqueaky** [comment]
I second the feature request. Takes quite a while to split 100+ books one-by-one manually.

**Comment by ApollonWrock** [comment]
Ye i basically gave up after a few...takes hours

In the meantime I try to get the standalone splitter running, but at least the pre-compiled seems to have problems.
Trying to compile it manually again and see if it works.

https://github.com/PrometeoConseil/AudioBookSplitter

**Comment by openaudible** [comment]
Yes. I have been working on that. Will be done for the next release!

Also working on better joining of books to keep the meta data, add cover art, and set chapters.

**Comment by ApollonWrock** [comment]
In the meantime here are powershell lines for anyone batch converting it on windows (should be similar on linux/bash) for a everything in a folder.

https://github.com/PrometeoConseil/AudioBookSplitter

> $files = Get-ChildItem "."
>
> foreach ($f in $files){
>    $sourcefile = $f.FullName 
>	D:\path\to\AudioBookSplitterCmd.exe -s $sourcefile -o E:\outputpath
> }

**Comment by openaudible** [comment]
Fixed in 2.2. Thanks for the feedback!

**Comment by ApollonWrock** [comment]
Just downloaded 2.2 and tested that future but can't confirm it's functionality.

It is possible to multi select books and click the menu item but nothing happens afterwards.

Already send the bug report via GUI

**Comment by openaudible** [comment]
OK.. Looks like there are some bugs remaining. Thanks for the report.

**Comment by openaudible** [comment]
This should be fixed in 2.3. Please open a new issue if not!
