### ISSUE TITLE
Adding split MP# and M4A files to OpenAudible library

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#404]
1. Probably an easy question, but can I add MP3 files to the library that are already split - but with different (distinct) filenames to the library and thence to the web page?
2. Can I update any of the metadata on the files on the web page?  For example most of the Mp3 files in note 1 have image thumbnails, but no narrator or release date and I would like to add these data.
3. Can I add missing or new thumb nails?  How?

Thanks, great application that has kept me busy organizing my library during shutdown.

**Comment by openaudible** [comment]
1. Yes. As long as the file names are alphabetically in order and of the same type (mp3), you can join them into a single file. 
2.&3. Currently no. You can use a program like mp3tag or other.  

Next version will have better joining of files that allows you to add a cover image by just having a jpg/png in a folder of audio files.
