### ISSUE TITLE
OA 2.2 crashing ffmpeg

### ISSUE THREAD

**Issue by wx007** [openaudible/openaudible#405]
Open Audible 2.2 consistently displays a dialog box stating that ffmpeg has quit unexpectedly while trying to convert aax to mp3. Conversion does NOT complete.
My computer is running OS X 10.13.6

The crash report includes:

```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x4] Symbol missing

Dyld Error Message:
  Symbol not found: ____chkstk_darwin
  Referenced from: /Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffmpeg (which was built for Mac OS X 10.15)
  Expected in: /usr/lib/libSystem.B.dylib
```

I didn't see a system requirement for OS X 10.15 and the previous version (2.0.6) worked fine.

**Comment by oboe45** [comment]
For what it may be worth, using 10.13.6 here with no issues after a hundred AAX to MPS conversions yesterday and today

**Comment by openaudible** [comment]
We had to recompile all the ffmpeg binaries to comply with their licensing. 
Looks like we didn't do it right for mac users. Suggest going back to 2.11 or updating your ffmpeg/ffprobe from earlier sources. 
Working on a fix.

**Comment by openaudible** [comment]
Give this a try:
https://openaudible.org/prerelease/OpenAudible_2.2.dmg

**Comment by wx007** [comment]
Error trying to download the dmg:

```
Error Page

Status code: 404
Exception Message: N/A

Debug:
```

**Comment by openaudible** [comment]
Sorry! 
http://openaudible.org/prerelease/OpenAudible_2.2_mac.dmg

**Comment by openaudible** [comment]
OK.. I uploaded a new version that disables the library in question. 
Please try this version: https://open.spotify.com/preprelease/OpenAudible_2.2_mac.dmg
and let me know!  Thank you for the feedback.

**Comment by wx007** [comment]
You sure that URL is correct? File not found.

**Comment by openaudible** [comment]
Fixed URL..
https://openaudible.org/prerelease/OpenAudible_2.2_mac.dmg

**Comment by wx007** [comment]
Well, the app doesn't crash but it fails to convert to mp3.

**Comment by openaudible** [comment]
Ugh. Thanks for the report. I am unable to reproduce. Can you post a console log snippet?

**Comment by wx007** [comment]
Sure, where do I find it?

**Comment by openaudible** [comment]
New version posted:
https://openaudible.org/prerelease/OpenAudible_2.2_mac.dmg

**Comment by wx007** [comment]
Mp3 conversion worked! 
Confirmed m4a conversion still working as well.
Thanks!
