### ISSUE TITLE
Split book does not seem to work with long book titles

### ISSUE THREAD

**Issue by Strider3000** [openaudible/openaudible#407]
OpenAudible 2.2.

Got a long audible book title and the split by chapter function does not seem to work.
Title:  "The Adventure Collection Treasure Island, The Jungle Book, Gullivers Travels, White Fang, The Merry Adventures of Robin.mp3"
Attempted output path (from the log file): "C:\Users\Colin\OpenAudible\tmp\The Adventure Collection Treasure Island, The Jungle Book, Gullivers Travels, White Fang, The Merry Adventures of Robin\The Adventure Collection Treasure Island, The Jungle Book, Gullivers Travels, White Fang, The Merry Adventures of Robin 151.mp3" (278 characters).

Here's a link to my log file: https://www.dropbox.com/s/q5dhnzphf3tpk53/log.txt?dl=0

I have tested splitting other audiobooks at it works fine.

**Comment by openaudible** [comment]
Confirmed. Think just on Windows. Truncating a file name isn't super easy.  


Q. How do I enable long file name support in Windows 10?

A. In the past the maximum supported file length was 260 characters (256 usable after the drive characters and termination character). In Windows 10 long file name support can be enabled which allows file names up to 32,767 characters (although you lose a few characters for mandatory characters that are part of the name). To enable this perform the following:

Start the registry editor (regedit.exe)
Navigate to HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem
Double click LongPathsEnabled
Set to 1 and click OK
Reboot

**Comment by Strider3000** [comment]
I saw your feedback and I figured it would be an easy fix.
I ended up getting nowhere in the last hour or so.
I then followed every fix on this link with no luck: https://superuser.com/questions/1119883/windows-10-enable-ntfs-long-paths-policy-option-missing

Any way we can get a truncation option? This would be an enhancement.
Alternatively I can try the chapter split on my Ubuntu machine but it would be highly inconvenient.

**Comment by openaudible** [comment]
Added for next version!

**Comment by openaudible** [comment]
Yeah, I don't know why enabling long file names in windows doesn't fix it. I posted that and waited a day to reboot and test... no luck.  

Logic will be something like, if windows and book name is > 200 chars, will use ASIN, short title, or product ID instead. If chapter name is longer than 200 chars, will use "Chapter 1" etc.  Trying to chop out the beginning, middle or end of a title is a problem. 


Reopen if not fixed in next release.
