### ISSUE TITLE
mp3 conversion not possible in 2.2

### ISSUE THREAD

**Issue by Sammeeey** [openaudible/openaudible#409]
Is it right, that in the new 2.2 the basic function of aax to mp3 conversion is not included anymore?
Or did I get something wrong?

**Comment by openaudible** [comment]
It is still supported. If you're on an old Mac, you may need to download a new version...  which we're waiting to hear if it fixes a problem.

http://openaudible.org/prerelease/OpenAudible_2.2_mac.dmg

Let me know if it works and I'll add it to the next official release.

**Comment by Sammeeey** [comment]
I am on Windows 10.
I just installed the latest release and was wondering about the commercial change.
