### ISSUE TITLE
Can't change default folder location

### ISSUE THREAD

**Issue by asquartz** [openaudible/openaudible#410]
Hello,

I'd like to change the default folder location from /home/username/OpenAudible, to /home/username/software/OpenAudible, to keep my home folder tidy.  So I go to preferences, and change the two folders there to my liking, restart OpenAudible and all seems fine.

But as soon as I delete the old OpenAudible folder set at in /home/username/OpenAudible (which should not be being used any more) then when I next start OpenAudible my settings are reset and I am back in Demo mode and the original folder set gets re-created.

How do I permanently set the OpenAudible folders to a different location and delete the originals?

I am using Linux Mint 19.3 Cinnamon, with OpenAudible 2.2 from the.deb file on the OpenAudible website.

**Comment by openaudible** [comment]
At the end of the day, we need a location to hold a little bit of meta data about where things are saved. On linux, it could have been /etc/openauduble, but we decided not to do that for permissions issues and to stay consistent between platforms.

You can create a new "Working" directory, which holds books and artwork etc. But some data needs to be in the /home/username/OpenAudible. 

We do have a problem where changing the working dir to a new location can find an older copy of the books.json file and move it to the new location. That should be fixed for the next release. But that isn't exactly what you're reporting.

**Comment by asquartz** [comment]
OK, thank you for the reply.  Maybe the wording of the options needs to be a little clearer then?
