### ISSUE TITLE
Won't Download to Mac

### ISSUE THREAD

**Issue by AlbusTribe** [openaudible/openaudible#411]
Help.

![Screen Shot 2020-06-30 at 8 46 51 am](https://user-images.githubusercontent.com/67614515/86070341-04c0aa80-baaf-11ea-96e8-b6f2d8c09bf1.png)

**Comment by openaudible** [comment]
Right-Click on the OpenAudible app and select "Open". You may need to change your security settings to allow unsigned apps to run if they are set too restrictive.

**Comment by Geordon** [comment]
To expand on what @openaudible said, you will want to go to wherever you put the OpenAudible app (usually /Applications) and right-click, select OPEN.  If I remember correctly, it will ask you if you are sure that you want to open it.

This is the required process for the first time you open any app that is not signed with an (expensive, as I understand) Apple Developer ID.  Ever time a new version is installed, you will have to do the same thing the first time.
