### ISSUE TITLE
Failed to convert to mp3

### ISSUE THREAD

**Issue by circuschaser** [openaudible/openaudible#415]
Connection to Audible worked fine.
Download worked fine.
Prompt to auto-convert to mp3 came up, clicked yes.
Indicated "converting" then failed, said check console for details.

Jul 06, 2020 12:00:30 PM org.openaudible.convert.LookupKey lookupKey
INFO: 917baf06
Jul 06, 2020 12:00:30 PM org.openaudible.convert.ConvertJob doConversion
INFO: converting: [redacted] to temp file: /Users/[redacted]/Library/OpenAudible/tmp/asin_[redacted]_temp.mp3 from source /Users/[redacted]/Library/OpenAudible/aax/[redacted].AAX length=236334867
Jul 06, 2020 12:00:30 PM org.openaudible.convert.ConvertJob doConversion
INFO: [redacted]
Jul 06, 2020 12:00:30 PM org.openaudible.convert.ConvertJob doConversion
INFO: create MP3 /Users/[redacted]/Library/OpenAudible/aax/[redacted].AAX result:134
Jul 06, 2020 12:00:30 PM org.openaudible.convert.ConvertJob doConversion
SEVERE: conversion got non-zero result:134 
stdErr:3356, ...    Metadata:,       title           : Chapter 22,     Stream #0:0(eng): Audio: aac (LC) (aavd / 0x64766161), 22050 Hz, stereo, fltp, 62 kb/s (default),     Metadata:,       creation_time   : 2020-07-06T16:59:04.000000Z,       handler_name    : ?Apple Sound Media Handler,     Stream #0:1(eng): Data: bin_data (text / 0x74786574) (default),     Metadata:,       creation_time   : 2020-07-06T16:59:05.000000Z,       handler_name    : ?Apple Text Media Handler,     Stream #0:2: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn, 90k tbc (attached pic), Stream mapping:,   Stream #0:2 -> #0:0 (mjpeg (native) -> png (native)),   Stream #0:0 -> #0:1 (aac (native) -> mp3 (libmp3lame)), Press [q] to stop, [?] for help, [swscaler @ 0x7fcf49852e00] deprecated pixel format used, make sure you did set range correctly, [swscaler @ 0x7fcf49852e00] No accelerated colorspace conversion found from yuv420p to rgb24., [mp3 @ 0x7fcf4980a000] Frame rate very high for a muxer not efficiently supporting it., Please consider specifying a lower framerate, a different muxer or -vsync 2, dyld: lazy symbol binding failed: Symbol not found: ____chkstk_darwin,   Referenced from: /Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffmpeg (which was built for Mac OS X 10.15),   Expected in: /usr/lib/libSystem.B.dylib, , dyld: Symbol not found: ____chkstk_darwin,   Referenced from: /Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffmpeg (which was built for Mac OS X 10.15),   Expected in: /usr/lib/libSystem.B.dylib, 
Jul 06, 2020 12:00:30 PM org.openaudible.convert.ConvertJob convert
SEVERE: Error converting book:[redacted]
java.io.IOException: Failed to convert /Users/[redacted]/Library/OpenAudible/aax/[redacted].AAX. Check console for details.
	at org.openaudible.convert.ConvertJob.doConversion(ConvertJob.java:318)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:399)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:451)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:420)

**Comment by openaudible** [comment]
I think we may have just fixed this bug. Please re-download the Mac version and re-install by dropping it into the Applications directory. Let me know!

**Comment by circuschaser** [comment]
Wasn't sure how long it would take for someone to get to this, so yesterday I uninstalled the software and requested a refund. Happy to say that won't be necessary now, because this bug-fix solved my problem.

Re-downloaded and installed, and conversion to mp3 now works, both manually and automatically.
Thanks so much.

Also, just a heads-up: there's a typo in the "operation cancelled" screen. 
"Cancelled" is misspelled.

<img width="770" alt="Screen Shot 2020-07-07 at 9 33 03 AM" src="https://user-images.githubusercontent.com/4381255/86799279-65179500-c037-11ea-8bd6-f74b5bb0bdd3.png">
