### ISSUE TITLE
Book Splitting issues

### ISSUE THREAD

**Issue by sharadaprasad** [openaudible/openaudible#417]
Recently I am realizing that splitting of some of the books does not work for some of the books. It looks like it is splitting (I see the number of parts, progress etc) but there are no files in the split folder other than album art. It happened with the following books:

www.audible.in/pd/Feminism-Is-Audiobook/B085D933FS

https://www.audible.in/pd/Conquering-the-Electron-Audiobook/B084SSDSTJ

I can attach the downloaded mp3, if that helps. Please let me know.

**Comment by openaudible** [comment]
What errors are you seeing in the console? Look at the console.. start the splitting.. and copy and paste the console (or look at it for a reason if nothing is output.) Chapter data must be available..

**Comment by sharadaprasad** [comment]
Thank you. I have sent a bug report and also attaching the log for your convenience.
[Open Audible Console Log.txt](https://github.com/openaudible/openaudible/files/4934057/Open.Audible.Console.Log.txt)

**Comment by openaudible** [comment]
Ah- that is a Windows bug. :)  Maximum file path length is 260 characters. Also reported in #403

Will fix in next release.

**Comment by sharadaprasad** [comment]
So, for the book, Conquering Electron, changing the directory to C drive worked and the book was split without any issues. That was a path length issue.

The second book split is behaving the same, however. Attaching the log for your reference.
[Console log for Feminism Is.txt](https://github.com/openaudible/openaudible/files/4934892/Console.log.for.Feminism.Is.txt)

**Comment by sharadaprasad** [comment]
Might it be because of the name of the book (in ends with two dots and a space)?

**Comment by openaudible** [comment]
I recall from a past life that you can't have a windows file name end with a space. Will add to the list to fix.

**Comment by openaudible** [comment]
Please give 2.3 a try and open a new issue (with error logs) if you see any issues. Hopefully fixed!
