### ISSUE TITLE
[Suggestion] Checkbox option for Start Jobs options.

### ISSUE THREAD

**Issue by OmegaRea** [openaudible/openaudible#418]
Currently when you sync the library you get the following dialog box..

![OpenAudibleOption](https://user-images.githubusercontent.com/56102453/87191145-6bb53f00-c2b9-11ea-836c-5bb2f8d75cc4.jpg)

Would it be possible to add check boxes to show which jobs to start, instead of having to back out, just to download the books?

Also the dialog only show the covert option to MP3 and not M4A,could that be added.

**Comment by openaudible** [comment]
Just say "no" and select the files you want to convert and or download. Don't want to add too many complex dialog boxes.
