### ISSUE TITLE
Could not find aax file checksum (this time on Windows)

### ISSUE THREAD

**Issue by dienekes00** [openaudible/openaudible#419]
Hello, all! I see that a similar issue was recently discovered and fixed on the Mac client, but I am now having it on the Windows client. I've tried restarting, rebooting, uninstalling/reinstalling. Can you please help? Thanks so much!

Providing the log info, below:

Jul 21, 2020 11:29:38 AM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 2.2 for win32 swt 4623 jvm 12 file.encoding UTF-8
Jul 21, 2020 11:29:39 AM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 2.2
Jul 21, 2020 11:29:39 AM org.openaudible.Directories getPrefs
INFO: loaded settings 1595345923332
Jul 21, 2020 11:29:39 AM org.openaudible.Directories getPrefs
INFO: loaded settings 1595345923332
Jul 21, 2020 11:29:39 AM org.openaudible.Audible load
INFO: Loading C:\Users\Gabe\OpenAudible\books.json
Jul 21, 2020 11:29:39 AM org.openaudible.Audible checkLibrary
INFO: loaded 183 books.
Jul 21, 2020 11:29:40 AM org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFO: applicationStarted took 464 ms. to complete.
Jul 21, 2020 11:29:42 AM org.openaudible.audible.bookstatus.BookFilterManager setFilter
INFO: Filter Changed: from none to status To_Convert
Jul 21, 2020 11:29:42 AM org.openaudible.desktop.swt.manager.views.SearchField modifyText
INFO: modifyText: To Convert text status:To_Convert index=6 event=ModifyEvent{Combo {To Convert} time=328435437 data=null} listen=true
Jul 21, 2020 11:29:44 AM org.openaudible.desktop.swt.manager.AudibleGUI _checkAutomation
INFO: Start auto conversion:2
Jul 21, 2020 11:29:47 AM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:Proceed? body:Automatic conversions are enabled. Start 2 conversions(s) now? response:BUTTON_YES
Jul 21, 2020 11:29:47 AM org.openaudible.util.queues.ThreadedQueue run
INFO: Starting job convert 21: The Final Unfinished Voyage  In progress:2 queue: 0 threads:
Jul 21, 2020 11:29:47 AM org.openaudible.util.queues.ThreadedQueue run
INFO: Starting job convert Spinning Silver In progress:2 queue: 0 threads:
Jul 21, 2020 11:29:47 AM org.openaudible.Audible jobStarted
INFO: ConvertQueue started:Spinning Silver size:0
Jul 21, 2020 11:29:47 AM org.openaudible.Audible jobStarted
INFO: ConvertQueue started:21: The Final Unfinished Voyage  size:0
Jul 21, 2020 11:29:47 AM org.openaudible.util.SimpleProcess <init>
INFO: Running: "C:\Program Files\OpenAudible\bin\win\ffmpeg.exe" -i "C:\Users\Gabe\OpenAudible\aax\Spinning Silver.AAX" 
Jul 21, 2020 11:29:47 AM org.openaudible.util.SimpleProcess <init>
INFO: Running: "C:\Program Files\OpenAudible\bin\win\ffmpeg.exe" -i "C:\Users\Gabe\OpenAudible\aax\21 The Final Unfinished Voyage of Jack Aubrey.AAX" 
Jul 21, 2020 11:29:47 AM org.openaudible.convert.ConvertJob convert
SEVERE: Error converting book:21: The Final Unfinished Voyage 
java.io.IOException: Could not find aax file checksum:C:\Users\Gabe\OpenAudible\aax\21 The Final Unfinished Voyage of Jack Aubrey.AAX. size=74425165 exists=true
err=
out=
	at org.openaudible.convert.LookupKey.getFileChecksum(LookupKey.java:86)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:103)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:116)
	at org.openaudible.convert.ConvertJob.getActivationBytes(ConvertJob.java:382)
	at org.openaudible.convert.ConvertJob.getMp3Args(ConvertJob.java:140)
	at org.openaudible.convert.ConvertJob.getConversionArgs(ConvertJob.java:245)
	at org.openaudible.convert.ConvertJob.doConversion(ConvertJob.java:260)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:399)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:451)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:420)

Jul 21, 2020 11:29:47 AM org.openaudible.util.queues.ThreadedQueue jobError
INFO: ConvertQueue error processing convert 21: The Final Unfinished Voyage 
java.io.IOException: Could not find aax file checksum:C:\Users\Gabe\OpenAudible\aax\21 The Final Unfinished Voyage of Jack Aubrey.AAX. size=74425165 exists=true
err=
out=
	at org.openaudible.convert.LookupKey.getFileChecksum(LookupKey.java:86)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:103)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:116)
	at org.openaudible.convert.ConvertJob.getActivationBytes(ConvertJob.java:382)
	at org.openaudible.convert.ConvertJob.getMp3Args(ConvertJob.java:140)
	at org.openaudible.convert.ConvertJob.getConversionArgs(ConvertJob.java:245)
	at org.openaudible.convert.ConvertJob.doConversion(ConvertJob.java:260)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:399)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:451)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:420)

Jul 21, 2020 11:29:47 AM org.openaudible.convert.ConvertJob convert
SEVERE: Error converting book:Spinning Silver
java.io.IOException: Could not find aax file checksum:C:\Users\Gabe\OpenAudible\aax\Spinning Silver.AAX. size=522461817 exists=true
err=
out=
	at org.openaudible.convert.LookupKey.getFileChecksum(LookupKey.java:86)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:103)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:116)
	at org.openaudible.convert.ConvertJob.getActivationBytes(ConvertJob.java:382)
	at org.openaudible.convert.ConvertJob.getMp3Args(ConvertJob.java:140)
	at org.openaudible.convert.ConvertJob.getConversionArgs(ConvertJob.java:245)
	at org.openaudible.convert.ConvertJob.doConversion(ConvertJob.java:260)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:399)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:451)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:420)

Jul 21, 2020 11:29:47 AM org.openaudible.util.queues.ThreadedQueue jobError
INFO: ConvertQueue error processing convert Spinning Silver
java.io.IOException: Could not find aax file checksum:C:\Users\Gabe\OpenAudible\aax\Spinning Silver.AAX. size=522461817 exists=true
err=
out=
	at org.openaudible.convert.LookupKey.getFileChecksum(LookupKey.java:86)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:103)
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:116)
	at org.openaudible.convert.ConvertJob.getActivationBytes(ConvertJob.java:382)
	at org.openaudible.convert.ConvertJob.getMp3Args(ConvertJob.java:140)
	at org.openaudible.convert.ConvertJob.getConversionArgs(ConvertJob.java:245)
	at org.openaudible.convert.ConvertJob.doConversion(ConvertJob.java:260)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:399)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:451)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:420)

Jul 21, 2020 11:29:47 AM org.openaudible.Audible jobCompleted
INFO: ConvertQueue completed:Spinning Silver remaining queue size:0
Jul 21, 2020 11:29:47 AM org.openaudible.Audible jobCompleted
INFO: ConvertQueue completed:21: The Final Unfinished Voyage  remaining queue size:0
Jul 21, 2020 11:29:47 AM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error converting Spinning Silver: Could not find aax file checksum:C:\Users\Gabe\OpenAudible\aax\Spinning Silver.AAX. size=522461817 exists=true
err=
out=
Jul 21, 2020 11:29:47 AM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error converting Spinning Silver: Could not find aax file checksum:C:\Users\Gabe\OpenAudible\aax\Spinning Silver.AAX. size=522461817 exists=true
err=
out=
Jul 21, 2020 11:29:50 AM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Jul 21, 2020 11:31:05 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by openaudible** [comment]
That is strange. Probaby an anti-virus is not allowing OA's ffmpeg to run.  I've improved the error message. 

Can you try selecting a book and doing Action Menu: Book Report (then look at your browser output?) It should show the results of "ffprobe" on the audio file. 

That should generate a bunch of info about the selected book. If that fails, that might provide a better clue.

**Comment by openaudible** [comment]
I added some additional logging in 2.3.. I didn't change anything, so it may still not run.. but it should report a better error message.
I'm interested in the log starting with:
WARNING: error converting ....

Also, check your anti-virus and make sure it can run the apps in the OpenAudible bin/win directory.

**Comment by JKamsker** [comment]
@openaudible You wouldnt even need FFMPEG to get the activationbytes checksum. Its right in the file at position 653 read 20 bytes. That would prevent users from running into this error 😅

**Comment by openaudible** [comment]
Thank you @JKamsker Will add that to the next release. 7x speedup on that operation. 

Not sure why the ffmpeg isn't working though.. Only time it fails is when the aax is damaged or not working.. or maybe the ffmpeg is being blocked by his anti-virus.

**Comment by dienekes00** [comment]
Interesting. I don't use an anti-virus. But, I do use a VPN that may be
doing some similar things. I could have sworn I had it turned off while
working on this, though.

I'm out of town and away from my desktop, right now, but I'm grateful for
the help. Looks like there may already be a good fix that speeds things up,
already, but I'll be sure to send the new log as well. I want you guys to
have all the info you can get.

Thanks!

**Comment by dienekes00** [comment]
Here is the requested Book Report:

Aug 10, 2020 2:52:11 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 2.3.1 for win32 swt 4623 jvm 12 file.encoding UTF-8
Aug 10, 2020 2:52:11 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 2.3.1
Aug 10, 2020 2:52:11 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1595345923332
Aug 10, 2020 2:52:12 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1595345923332
Aug 10, 2020 2:52:12 PM org.openaudible.Audible load
INFO: Loading C:\Users\Gabe\OpenAudible\books.json
Aug 10, 2020 2:52:12 PM org.openaudible.Audible checkLibrary
INFO: loaded 183 books.
Aug 10, 2020 2:52:12 PM org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFO: applicationStarted took 448 ms. to complete.
Aug 10, 2020 2:52:17 PM org.openaudible.desktop.swt.manager.AudibleGUI _checkAutomation
INFO: Start auto conversion:2
Aug 10, 2020 2:52:18 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:Proceed? body:Automatic conversions are enabled. Start 2 conversions(s) now? response:BUTTON_NO
Aug 10, 2020 2:52:22 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Aug 10, 2020 2:52:23 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Connect
Aug 10, 2020 2:52:25 PM org.openaudible.audible.AudibleConnectionState setRegion
INFO: Setting audible region to US
Aug 10, 2020 2:52:26 PM org.openaudible.desktop.swt.manager.browser.AudibleBrowser setUrl
INFO: AudibleBrowser setURL: about:blank
Aug 10, 2020 2:52:31 PM org.openaudible.audible.bookstatus.BookFilterManager setFilter
INFO: Filter Changed: from none to status To_Convert
Aug 10, 2020 2:52:31 PM org.openaudible.desktop.swt.manager.views.SearchField modifyText
INFO: modifyText: To Convert text status:To_Convert index=6 event=ModifyEvent{Combo {To Convert} time=66657671 data=null} listen=true
Aug 10, 2020 2:52:36 PM org.openaudible.desktop.swt.manager.AudibleGUI _checkAutomation
INFO: Start auto conversion:2
Aug 10, 2020 2:52:37 PM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:Proceed? body:Automatic conversions are enabled. Start 2 conversions(s) now? response:BUTTON_NO
Aug 10, 2020 2:52:40 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Book_Report
Aug 10, 2020 2:52:40 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: "C:\Program Files\OpenAudible\bin\win\ffprobe.exe" -hide_banner "C:\Users\Gabe\OpenAudible\aax\Spinning Silver.AAX" -show_streams -show_chapters -show_error -show_format -print_format json 
Aug 10, 2020 2:52:40 PM org.openaudible.util.SimpleProcess getResults
WARNING: Non-zero for cmd:"C:\Program Files\OpenAudible\bin\win\ffprobe.exe" -hide_banner "C:\Users\Gabe\OpenAudible\aax\Spinning Silver.AAX" -show_streams -show_chapters -show_error -show_format -print_format json 
error code:-1073741515(C0000135)
stdout:
stderr:
Aug 10, 2020 2:52:40 PM org.openaudible.convert.FFProbe probe
SEVERE: cmd:"C:\Program Files\OpenAudible\bin\win\ffprobe.exe" -hide_banner "C:\Users\Gabe\OpenAudible\aax\Spinning Silver.AAX" -show_streams -show_chapters -show_error -show_format -print_format json 
error code:-1073741515(C0000135)
stdout:
stderr:
Aug 10, 2020 2:52:40 PM org.openaudible.convert.FFProbe probeFiles
SEVERE: Error
java.io.IOException: ffprobe error
	at org.openaudible.convert.FFProbe.probe(FFProbe.java:48)
	at org.openaudible.convert.FFProbe.probeFiles(FFProbe.java:91)
	at org.openaudible.desktop.swt.manager.AudibleGUI.getInfo(AudibleGUI.java:1874)
	at org.openaudible.desktop.swt.manager.AudibleGUI$11.run(AudibleGUI.java:1908)

Aug 10, 2020 2:52:40 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: "C:\Program Files\OpenAudible\bin\win\ffprobe.exe" -hide_banner "C:\Users\Gabe\OpenAudible\art\Spinning Silver.jpg" -show_streams -show_chapters -show_error -show_format -print_format json 
Aug 10, 2020 2:52:40 PM org.openaudible.util.SimpleProcess getResults
WARNING: Non-zero for cmd:"C:\Program Files\OpenAudible\bin\win\ffprobe.exe" -hide_banner "C:\Users\Gabe\OpenAudible\art\Spinning Silver.jpg" -show_streams -show_chapters -show_error -show_format -print_format json 
error code:-1073741515(C0000135)
stdout:
stderr:
Aug 10, 2020 2:52:40 PM org.openaudible.convert.FFProbe probe
SEVERE: cmd:"C:\Program Files\OpenAudible\bin\win\ffprobe.exe" -hide_banner "C:\Users\Gabe\OpenAudible\art\Spinning Silver.jpg" -show_streams -show_chapters -show_error -show_format -print_format json 
error code:-1073741515(C0000135)
stdout:
stderr:
Aug 10, 2020 2:52:40 PM org.openaudible.convert.FFProbe probeFiles
SEVERE: Error
java.io.IOException: ffprobe error
	at org.openaudible.convert.FFProbe.probe(FFProbe.java:48)
	at org.openaudible.convert.FFProbe.probeFiles(FFProbe.java:91)
	at org.openaudible.desktop.swt.manager.AudibleGUI.getInfo(AudibleGUI.java:1874)
	at org.openaudible.desktop.swt.manager.AudibleGUI$11.run(AudibleGUI.java:1908)

Aug 10, 2020 2:52:40 PM org.openaudible.desktop.swt.manager.browser.AudibleBrowser setUrl
INFO: AudibleBrowser setURL: file:/C:/Users/Gabe/OpenAudible/tmp/Spinning%20Silver.html
Aug 10, 2020 2:52:50 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console


This issue has not been resolved by the most recent update. Anything else I can do?

**Comment by openaudible** [comment]
Do you have a an anti-virus program? Make sure you allow all the files in Program Files/OpenAudible/bin/win to be able to run.

Are you on Windows 10 N? (If so, see issue #430 ) or try installing Installing the Media Feature Pack as an optional feature seems to resolve the issue.

You could also try running the OA ffmpeg from the command line.
