### ISSUE TITLE
New audio books are missing purchase date

### ISSUE THREAD

**Issue by matthewb1999** [openaudible/openaudible#420]
Hi,

Recently I have noticed any book that I have purchased April 2020 is missing the purchase date, so when I sort the books by that they are not in the proper order. I have attached an image of what I am talking about.

Any help with this would be appreciated. 

![image](https://user-images.githubusercontent.com/62423430/88304105-bbefc080-ccff-11ea-8e91-217865c2991f.png)

**Comment by openaudible** [comment]
That data got moved.. so you'll need to to a "refresh" on books with missing info after logging into your account from the OA Browser.
