### ISSUE TITLE
Feature requests, show authcode and make extraction to m4b selectable

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#421]
i get the audible authcode using https://github.com/inAudible-NG/audible-activator i then only use openaudible to download the AAX files.
then i use AAXtoMP3 -e:m4b -c -A {my-authcode} filename.AAX to convert to m4b which it is faster at converting to than mp3 (it automatically breaks at chapter marks in the AAX file) i then manually edit the id3 tags and my media library plays the m4b files fine....
it would be nice if openaudible could do some of this for me so i don't also need AAXtoMP3, audible-activator is only needed once per account but having somewhere in openaudible that shows the authcode would be nice too

**Comment by openaudible** [comment]
Sounds like a good system for you. We only look up the auth code on conversion and it is displayed in the console. Thanks.
