### ISSUE TITLE
OpenAudible 2.3 long name split issue for Windows partially remains

### ISSUE THREAD

**Issue by Strider3000** [openaudible/openaudible#423]
I can now successfully split books with long names in Windows by manually selecting an MP3 file (mp3 file generated from OpenAudible) via "File" --> "Split By Chapter" --> (manually choose mp3 file).

I *cannot* successfully split books with long names in Windows by selecting the book in the OpenAudible windows and choosing "Actions" --> "Split Selected Books". 

Would it be possible for both functions to work (instead of needing to manually choose the MP3?

Link to logfile and video of the issue here: https://www.dropbox.com/s/qif2pb3p2tjbd8m/SplitError.zip?dl=0

**Comment by openaudible** [comment]
It looks like it skipped that because the directory already exists. I don't know if the book is already split or if the directory is empty. (We don't check.)
Check again or look at the log you submitted where it says the path of the book skipepd.

**Comment by Strider3000** [comment]
I took a look and there was no existing directory.
Here's a new logfile and video showing that the "split" process creates the directory (it does not exist before executing the split process). https://www.dropbox.com/s/c4luen7j0v6qdzp/SplitError2.zip?dl=0

**Comment by openaudible** [comment]
Thank you for clarifying. I guess I didn't have enough long book names for testing.  Will fix ASAP and update you.
Thx

**Comment by lgkahn** [comment]
same problem here. split just pops up something that quickly dissappears. no indication of what happened

**Comment by openaudible** [comment]
Try version 2.3.1 and reopen if any problems found.

**Comment by Strider3000** [comment]
I have confirmed that my problem is solved in 2.3.1.
