### ISSUE TITLE
OpenAudible 2.3 cannot join audio files in Windows

### ISSUE THREAD

**Issue by Strider3000** [openaudible/openaudible#424]
Using OpenAudible 2.3 in Windows to attempt to join chapters of a previously-split book (previously split by OpenAudible on 2.3).
The program throws a "java io error".
See logfile and video here: https://www.dropbox.com/s/wrjdsbkvm7scagv/JoinError.zip?dl=0

**Comment by openaudible** [comment]
I think we got that fixed. Was having a problem joining files that had two periods in the file name. Try 2.3.1

**Comment by Strider3000** [comment]
I have verified that my issue has been fixed in 2.3.1. Thanks!
