### ISSUE TITLE
2.3.1 split still not working

### ISSUE THREAD

**Issue by lgkahn** [openaudible/openaudible#427]
2.3.1 split still not working for me. Unless I manually to it from file menu. I said latest version. It is nit fixed.

**Comment by SlowDowne** [comment]
Seems to be related to the change to /books directory. Esp for folks that upgrade from an older version and don't have a /books directory. Attempting to split just causes the 'Select Folder' dialog to error (needs a try catch maybe?), flash, and not proceed. Sometimes a log error is shown stating that the file needing to split cannot be found in the [openaudible path]...\books directory. Which it won't be if the downloads and conversions are still going to the file structure in 2.2. Needed to revert to 2.2 to get the split working again. In addition, would be a good idea to place more default path control in the preferences dialog so location of downloads/conversions/splits can be set and clearly determined. Or record fully configured path in a database and use that for source needed for splitting.

**Comment by SlowDowne** [comment]
In addition, tell user if split book already exists. Ask to overwrite. 

In 2.2 requesting to re-split seems to do nothing (probably checks for a file folder), does not show a 'Select Folder' dialog (in case the user wants to split to a new location) and does not tell user that the book has been previously split. i.e. seems to do nothing.

**Comment by openaudible** [comment]
Can you post some error logs? 

Any time there are lots of books to split, its hard to have dialogs come up and ask if you want to overwrite a particular one. Is this for Windows? Windows adds the complexity of having to shorten long file names..

**Comment by emarkp** [comment]
I was able to get this to work after seeing this error when right-clicking in Windows and selecting "split selected":
Split Artemis to C:\Users\<USER>\OpenAudible\books\Artemis

That folder "books" didn't exist, as a sibling to mp3, tmp, web, etc.  Once I create the "books" folder, I successfully got split to work with the latest release.

**Comment by openaudible** [comment]
Thank you for that! I think that was the problem. Working on a new release now..

**Comment by openaudible** [comment]
Please try 2.3.4 and reopen and/or submit a bug report from the about menu if it persists.
