### ISSUE TITLE
Problem with conversion

### ISSUE THREAD

**Issue by openpat28** [openaudible/openaudible#428]
I bought a book in Audible. This book in audible is in 2 parts (to provide lightweight downloads). Open  audible do downlaod the all file in AAx format. The conversion only gibes the 2nd part in MP3. So I don' have the first part in MP3. I'm sure all is downloaded because the duration indicated in openaudible is the sum of the 2 parts durations. So something goes wrong in the conversion process...

**Comment by openaudible** [comment]
Trying to fix this one. One way to fix may be to delete the book, navigate to the library page and manually download the "Full" book by clicking the download (Full) button. That file should be able to be converted to the whole book. 
I am trying to get a few more bug reports to determine why that is happening.. I think mostly for out of the US regions?

**Comment by openaudible** [comment]
Please try 2.3.4 and reopen and/or submit a bug report from the about menu if it persists.
