### ISSUE TITLE
Follow-up to #402. Still not downloading large books splitted into multiple parts

### ISSUE THREAD

**Issue by burk-castlehard** [openaudible/openaudible#429]
Everything as described in #402 commets of today, even using OA 2.3.1

**Comment by domhaas** [comment]
Can confirm this.

**Comment by openaudible** [comment]
OK. Can you quit and restart OpenAudible, do navigate to the library page where the book is.. Then request the book be downloaded. You could also try clicking on the "Full Download" link if there is one for the book. 

Then send a bug report from the about box with the name of the book and #429 as the issue and mention any of the steps above you completed.

I'll take a look and see what's going on. I've bought several of the large books people mention as examples and it seems to work fine on my end. Can't tell if this is a regional thing (outside of the US?) or something else.

Appreciate the follow up.

**Comment by domhaas** [comment]
hey @openaudible thanks for the quick reply.
I got the issue on this book:
https://www.audible.de/pd/Die-zwei-Tuerme-Hoerbuch/B005CHCW70

Yeah, German-Version of audible.
Full download works and also the conversion via openaudible.

**Comment by openaudible** [comment]
I made a potential fix in 2.3.4. Please give it a try.
https://openaudible.org/
If it doesn't work, please submit a bug report and/or re-open this issue.

**Comment by domhaas** [comment]
> I made a potential fix in 2.3.4. Please give it a try.
> https://openaudible.org/
> If it doesn't work, please submit a bug report and/or re-open this issue.

Thank you for the quick fix. Seems to work now.
