### ISSUE TITLE
Feature Request: Split files into Chapters?

### ISSUE THREAD

**Issue by willcormier** [openaudible/openaudible#43]
Not sure if this is at all possible, but would it be able to split the MP3 files into separate files for each chapter?

**Comment by raiytu4** [comment]
same request

**Comment by Bommes** [comment]
I'd also love to see this feature, especially since there already seem to be tags in place for each chapter. If anyone has a suggestion for splitting the existing mp3 with a different software in the interim I'd be thankful to hear it as well.

**Comment by openaudible** [comment]
The chapter info is available in both the aax and mp3.. you can view it by using ffprobe:

ffprobe -v quiet -print_format json -show_chapters  filename.mp3

So there should be plenty of apps that can do what you're looking for.. but it is beyond the scope of this app. If you find a utility that works, feel free to post as a comment here. 

A quick google search shows many apps and scripts. 
https://www.google.com/search?q=mp3+split+by+chapter

**Comment by willcormier** [comment]
That's unfortunate. I've searched online for a good open source splitter. You either have to pay for them, or split them all manually.

**Comment by DrPhant0m** [comment]
Could this (or similar) be integrated?
https://github.com/watchduck/split_audiobooks

**Comment by gbouthenot** [comment]
You can use [mp3-splitter-js](https://github.com/gbouthenot/mp3splitter-js).
You just have to pass the mp3 filename and it will split it according to the chapters integrated in tags.

**Comment by openaudible** [comment]
Split MP3 by chapter has been added to OpenAudible under the file menu.

**Comment by milegrin** [comment]
https://sourceforge.net/projects/aaxtomp3/
This is what I use to split the downloaded AAX file into chapter split MP3's
