### ISSUE TITLE
Unable to connect with 2.3.1 (browser issue)

### ISSUE THREAD

**Issue by kategray** [openaudible/openaudible#431]
Hello,

I've tried on two separate computers, with and without a US VPN.  I can open the browser and login, but it does not scan the library or show options to download the book list.

![image](https://user-images.githubusercontent.com/2415200/90349423-c99b1c00-e007-11ea-8ac0-f3c81fe92bdc.png)

![image](https://user-images.githubusercontent.com/2415200/90349437-dcadec00-e007-11ea-8228-172f5955ab7f.png)

**Comment by kategray** [comment]
Interestingly, the error seems to be related to the use of the embedded Internet Explorer 6? rendering engine.  I don't know if it's the default on standard Windows 10.  It might be an enterprise thing.

When I force the browser to upgrade to the newer Edge rendering engine, it works just fine.  I did this with the following .reg file.

```Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Internet Explorer\Main\FeatureControl\FEATURE_BROWSER_EMULATION]
"OpenAudible.exe"=dword:00002af8```

**Comment by kategray** [comment]
I believe that key also works in HKCU, if you wanted to use it in an installer.

**Comment by openaudible** [comment]
Hm. Haven't seen this. But yes, some kind of explorer rendering engine has to be available.. no idea why it wouldn't be.
Is there no "log in" link?

**Comment by openaudible** [comment]
Do you see errors in the console? (CTRL-D)
