### ISSUE TITLE
Can't install: Error creating directories

### ISSUE THREAD

**Issue by Joeeey80** [openaudible/openaudible#433]
(Sorry, total noob) I'm not able to install openaudible under Windows 10. All I get is the error message "Error creating directories! Unable to create or load required directories. Check that the drives are read/writable. Error: Null. You could also look at or erase the directories.json file."
Weird, don't get why the selected installation folder might be protected or something else. Any suggestions what to do? 
TIA
jk

**Comment by openaudible** [comment]
Fixed in 2.3.3. That was our bug. Thanks for reporting it!
