### ISSUE TITLE
Failed to convert error

### ISSUE THREAD

**Issue by duckiepopo** [openaudible/openaudible#434]
Purchased OpenAudible today. I downloaded a book purchased from Audible on to Open Audible. Tried to convert to MP3 and got an error - Failed to convert [book name] Check console for details.

From the console:

Aug 19, 2020 6:47:27 AM org.openaudible.Audible jobCompleted
INFO: ConvertQueue completed:One to Watch: A Novel remaining queue size:0
Aug 19, 2020 6:47:27 AM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error converting One to Watch: A Novel: Failed to convert /Users/lyssa919/Library/OpenAudible/aax/0593210123.AAX. Check console for details.
Aug 19, 2020 6:47:40 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by stevejordi** [comment]
Same for me.
Just bought it and since I paid, no more converting.
Same message as you.
My Mac is authorized against audible. Titles play in Apple Books without problems.
Now I have no Java installed on my machine. Is the Java error mentioned embedded?
All previous free versions worked flawlessly.

**Comment by JelbertHoltrop** [comment]
Same here. Did buy a license try to convert to mp3 and failed to convert.

INFO: Unable to get additional book details from AAX.
java.lang.Exception: product id mismatch for Transcending the Levels of Consc [BK_HAYH_001057UK] and Transcending the Levels of Consc file [BK_HAYH_001057]. File is: .../Library/OpenAudible/aax/Transcending the Levels of Consciousness The Stairway to Enlightenment.AAX
	at org.openaudible.convert.AAXParser.updateBookFromAAX(AAXParser.java:272)
	at org.openaudible.convert.AAXParser.update(AAXParser.java:258)
	at org.openaudible.Audible.jobCompleted(Audible.java:1111)
	at org.openaudible.Audible.jobCompleted(Audible.java:39)
	at org.openaudible.util.queues.ThreadedQueue.jobCompleted(ThreadedQueue.java:293)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:430)

Aug 19, 2020 3:29:46 PM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error converting Transcending the Levels of Consc: Failed to convert .../Library/OpenAudible/aax/Transcending the Levels of Consciousness The Stairway to Enlightenment.AAX. Check console for details.
Aug 19, 2020 3:29:51 PM org.openaudible.desktop.swt.manager.AudibleGUI _checkAutomation
INFO: Start auto conversion:3
Aug 19, 2020 3:32:17 PM org.openaudible.desktop.swt.manager.browser.AudibleBrowser setUrl
INFO: AudibleBrowser setURL: about:blank
Aug 19, 2020 3:32:32 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by Beejay1963m** [comment]
Exactly the same problem for me. Every time I click on convert to MP3 I get a message stating 'Converting Failed to convert'. I have purchased a licence this evening but it still isn't converting the files. :-(

**Comment by Beejay1963m** [comment]
regarding my message above this is from the console:

Aug 19, 2020 8:07:32 PM org.openaudible.convert.ConvertJob doConversion
INFO: create MP3 /Users/billjohnson/Library/OpenAudible/aax/Building an Empire The Most Complete Blueprint to Building a Massive Network Marketing Business (Next Level Edition).AAX result:1
Aug 19, 2020 8:07:32 PM org.openaudible.convert.ConvertJob doConversion
SEVERE: conversion got non-zero result:1 
stdErr:ffmpeg version N-98470-g7772666e5b-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers,   built with Apple clang version 11.0.0 (clang-1100.0.33.17),   configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-libmp3lame --pkg-config-flags=--static --disable-securetransport --disable-ffplay,   libavutil      56. 55.100 / 56. 55.100,   libavcodec     58. 95.100 / 58. 95.100,   libavformat    58. 48.100 / 58. 48.100,   libavdevice    58. 11.101 / 58. 11.101,   libavfilter     7. 87.100 /  7. 87.100,   libswscale      5.  8.100 /  5.  8.100,   libswresample   3.  8.100 /  3.  8.100, [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fe269700040] Error setting option activation_bytes to value <notfound>., /Users/billjohnson/Library/OpenAudible/aax/Building an Empire The Most Complete Blueprint to Building a Massive Network Marketing Business (Next Level Edition).AAX: Invalid argument
Aug 19, 2020 8:07:32 PM org.openaudible.convert.ConvertJob convert
SEVERE: Error converting book:Building an Empire
java.io.IOException: Failed to convert /Users/billjohnson/Library/OpenAudible/aax/Building an Empire The Most Complete Blueprint to Building a Massive Network Marketing Business (Next Level Edition).AAX. Check console for details.
	at org.openaudible.convert.ConvertJob.doConversion(ConvertJob.java:318)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:400)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:452)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:420)

Aug 19, 2020 8:07:32 PM org.openaudible.util.queues.ThreadedQueue jobError
INFO: ConvertQueue error processing convert Building an Empire
java.io.IOException: Failed to convert /Users/billjohnson/Library/OpenAudible/aax/Building an Empire The Most Complete Blueprint to Building a Massive Network Marketing Business (Next Level Edition).AAX. Check console for details.
	at org.openaudible.convert.ConvertJob.doConversion(ConvertJob.java:318)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:400)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:452)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:420)

Aug 19, 2020 8:07:32 PM org.openaudible.Audible jobCompleted
INFO: ConvertQueue completed:Building an Empire remaining queue size:0
Aug 19, 2020 8:07:32 PM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error converting Building an Empire: Failed to convert /Users/billjohnson/Library/OpenAudible/aax/Building an Empire The Most Complete Blueprint to Building a Massive Network Marketing Business (Next Level Edition).AAX. Check console for details.
Aug 19, 2020 8:07:37 PM org.openaudible.desktop.swt.manager.AudibleGUI _checkAutomation
INFO: Start auto conversion:4
Aug 19, 2020 8:07:38 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by openaudible** [comment]
Looks like something happened.. Are all you Mac people? 
I'm going through logs to see what happened but looks like the 2.3.3 version may be no good. 
Try 2.3.1 from: https://github.com/openaudible/openaudible/releases

**Comment by openaudible** [comment]
Can you try this version?
https://openaudible.org/prerelease

**Comment by stevejordi** [comment]
Still the same problem with the prerelease
Log attached
[STJConsole.log](https://github.com/openaudible/openaudible/files/5103227/STJConsole.log)

**Comment by stevejordi** [comment]
> Looks like something happened.. Are all you Mac people?
> I'm going through logs to see what happened but looks like the 2.3.3 version may be no good.
> Try 2.3.1 from: https://github.com/openaudible/openaudible/releases

2.3.1 works without problem on my side.

**Comment by JelbertHoltrop** [comment]
Yes I use a mac 10.15.5
Does not work:

INFO: Command: Convert
Aug 20, 2020 3:22:16 PM org.openaudible.util.queues.ThreadedQueue run
INFO: Starting job convert Letting Go: The Pathway of Surre In progress:1 queue: 0 threads:
Aug 20, 2020 3:22:16 PM org.openaudible.Audible jobStarted
INFO: ConvertQueue started:Letting Go: The Pathway of Surre size:0
Aug 20, 2020 3:22:16 PM org.openaudible.convert.ConvertJob doConversion
INFO: converting: Letting Go: The Pathway of Surre to temp file: .../Library/OpenAudible/tmp/BK_HAYH_000323UK_temp.mp3 from source .../Library/OpenAudible/aax/Letting Go The Pathway of Surrender.AAX length=360847070
Aug 20, 2020 3:22:16 PM org.openaudible.convert.ConvertJob doConversion
INFO: /Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffmpeg -activation_bytes <notfound> -i ".../Library/OpenAudible/aax/Letting Go The Pathway of Surrender.AAX" -map_metadata 0 -metadata:s:v "title=Album cover" -metadata:s:v "comment=Cover (front)" -codec:a libmp3lame -qscale:a 4 -id3v2_version 3 -metadata product_id=BK_HAYH_000323UK -metadata asin=B00ZJGGQXU -metadata "narrated_by=Peter Lownds PhD" -metadata "book_genre=Politics & Social Sciences:Philosophy" -metadata major_brand= -metadata minor_version= -metadata compatible_brands= -metadata title= -metadata "author=David R. Hawkins MD. PHD." -metadata year=2014-12-28 -metadata comment= -metadata json64=eyJzdW1tYXJ5IjoiPHA+PGk+TGV0dGluZyBHbzxcL2k+IGRlc2NyaWJlcyBhIHNpbXBsZSBhbmQgZWZmZWN0aXZlIG1lYW5zIGJ5IHdoaWNoIHRvIGxldCBnbyBvZiB0aGUgb2JzdGFjbGVzIHRvIGVubGlnaHRlbm1lbnQgYW5kIGJlY29tZSBmcmVlIG9mIG5lZ2F0aXZpdHkuIER1cmluZyB0aGUgbWFueSBkZWNhZGVzIG9mIHRoZSBhdXRob3IncyBjbGluaWNhbCBwc3ljaGlhdHJpYyBwcmFjdGljZSwgdGhlIHByaW1hcnkgYWltIHdhcyB0byBzZWVrIHRoZSBtb3N0IGVmZmVjdGl2ZSB3YXlzIHRvIHJlbGlldmUgaHVtYW4gc3VmZmVyaW5nIGluIGFsbCBvZiBpdHMgbWFueSBmb3Jtcy4gVGhlIGlubmVyIG1lY2hhbmlzbSBvZiBzdXJyZW5kZXIgd2FzIGZvdW5kIHRvIGJlIG9mIGdyZWF0IHByYWN0aWNhbCBiZW5lZml0IGFuZCBpcyBkZXNjcmliZWQgaW4gdGhpcyBib29rLsKgPFwvcD4gPHA+RHIuIEhhd2tpbnMnIHByZXZpb3VzIGJvb2tzIGZvY3VzZWQgb24gYWR2YW5jZWQgc3RhdGVzIG9mIGF3YXJlbmVzcyBhbmQgZW5saWdodGVubWVudC4gT3ZlciB0aGUgeWVhcnMgdGhvdXNhbmRzIG9mIHN0dWRlbnRzIGhhZCBhc2tlZCBmb3IgYSBwcmFjdGljYWwgdGVjaG5pcXVlIGJ5IHdoaWNoIHRvIHJlbW92ZSB0aGUgaW5uZXIgYmxvY2tzIHRvIGhhcHBpbmVzcywgbG92ZSwgam95LCBzdWNjZXNzLCBoZWFsdGgsIGFuZCwgdWx0aW1hdGVseSwgZW5saWdodGVubWVudC4gVGhpcyBhdWRpb2Jvb2sgcHJvdmlkZXMgYSBtZWNoYW5pc20gZm9yIGxldHRpbmcgZ28gb2YgdGhvc2UgYmxvY2tzLsKgPFwvcD4gPHA+VGhlIG1lY2hhbmlzbSBvZiBzdXJyZW5kZXIgdGhhdCBEci4gSGF3a2lucyBkZXNjcmliZXMgY2FuIGJlIGRvbmUgaW4gdGhlIG1pZHN0IG9mIGV2ZXJ5ZGF5IGxpZmUuIFRoaXMgYXVkaW9ib29rIGlzIGVxdWFsbHkgdXNlZnVsIGZvciBhbGwgZGltZW5zaW9ucyBvZiBodW1hbiBsaWZlOiBwaHlzaWNhbCBoZWFsdGgsIGNyZWF0aXZpdHksIGZpbmFuY2lhbCBzdWNjZXNzLCBlbW90aW9uYWwgaGVhbGluZywgdm9jYXRpb25hbCBmdWxmaWxsbWVudCwgcmVsYXRpb25zaGlwcywgc2V4dWFsaXR5LCBhbmQgc3Bpcml0dWFsIGdyb3d0aC7CoDxcL3A+IDxwPkl0IGlzIGFuIGludmFsdWFibGUgcmVzb3VyY2UgZm9yIGFsbCBwcm9mZXNzaW9uYWxzIHdobyB3b3JrIGluIHRoZSBhcmVhcyBvZiBtZW50YWwgaGVhbHRoLCBwc3ljaG9sb2d5LCBtZWRpY2luZSwgc2VsZi1oZWxwLCBhZGRpY3Rpb24gcmVjb3ZlcnksIGFuZCBzcGlyaXR1YWwgZGV2ZWxvcG1lbnQuwqA8XC9wPiA8cD48Yj5QTEVBU0UgTk9URTogV2hlbiB5b3UgcHVyY2hhc2UgdGhpcyB0aXRsZSwgdGhlIGFjY29tcGFueWluZyBQREYgd2lsbCBiZSBhdmFpbGFibGUgaW4geW91ciBBdWRpYmxlIExpYnJhcnkgYWxvbmcgd2l0aCB0aGUgYXVkaW8uPFwvYj48XC9wPiIsInJhdGluZ19hdmVyYWdlIjoiNC41NTkyMzU2Njg3ODk4MDkiLCJhdXRob3IiOiJEYXZpZCBSLiBIYXdraW5zIE1ELiBQSEQuIiwibGFuZ3VhZ2UiOiJlbmdsaXNoIiwidGl0bGUiOiJMZXR0aW5nIEdvOiBUaGUgUGF0aHdheSBvZiBTdXJyZW5kZXIiLCJpbmZvX2xpbmsiOiJodHRwczovL3d3dy5hdWRpYmxlLmNvLnVrL3BkL0xldHRpbmctR28tQXVkaW9ib29rL0IwMFpKR0dRWFUiLCJyYXRpbmdfY291bnQiOiI3ODUiLCJkdXJhdGlvbiI6IjEyOjIzOjAwIiwiZmlsZW5hbWUiOiJMZXR0aW5nIEdvIFRoZSBQYXRod2F5IG9mIFN1cnJlbmRlciIsIm5hcnJhdGVkX2J5IjoiUGV0ZXIgTG93bmRzIFBoRCIsInJlbGVhc2VfZGF0ZSI6IjIwMTQtMTItMjgiLCJwcm9kdWN0X2lkIjoiQktfSEFZSF8wMDAzMjNVSyIsImdlbnJlIjoiUG9saXRpY3MgJiBTb2NpYWwgU2NpZW5jZXM6UGhpbG9zb3BoeSIsInB1Ymxpc2hlciI6IkhheSBIb3VzZSIsImFzaW4iOiJCMDBaSkdHUVhVIiwicHVyY2hhc2VfZGF0ZSI6IjIwMjAtMDgtMTkifQ== .../Library/OpenAudible/tmp/BK_HAYH_000323UK_temp.mp3 
Aug 20, 2020 3:22:16 PM org.openaudible.convert.ConvertJob doConversion
INFO: create MP3 .../Library/OpenAudible/aax/Letting Go The Pathway of Surrender.AAX result:1
Aug 20, 2020 3:22:16 PM org.openaudible.convert.ConvertJob doConversion
SEVERE: conversion got non-zero result:1 
stdErr:ffmpeg version N-98470-g7772666e5b-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2020 the FFmpeg developers,   built with Apple clang version 11.0.0 (clang-1100.0.33.17),   configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-libmp3lame --pkg-config-flags=--static --disable-securetransport --disable-ffplay,   libavutil      56. 55.100 / 56. 55.100,   libavcodec     58. 95.100 / 58. 95.100,   libavformat    58. 48.100 / 58. 48.100,   libavdevice    58. 11.101 / 58. 11.101,   libavfilter     7. 87.100 /  7. 87.100,   libswscale      5.  8.100 /  5.  8.100,   libswresample   3.  8.100 /  3.  8.100, [mov,mp4,m4a,3gp,3g2,mj2 @ 0x7fac17c0fe00] Error setting option activation_bytes to value <notfound>., .../Library/OpenAudible/aax/Letting Go The Pathway of Surrender.AAX: Invalid argument
Aug 20, 2020 3:22:16 PM org.openaudible.convert.ConvertJob convert
SEVERE: Error converting book:Letting Go: The Pathway of Surre
java.io.IOException: Failed to convert .../Library/OpenAudible/aax/Letting Go The Pathway of Surrender.AAX. Check console for details.
	at org.openaudible.convert.ConvertJob.doConversion(ConvertJob.java:318)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:400)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:452)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:420)

Aug 20, 2020 3:22:16 PM org.openaudible.util.queues.ThreadedQueue jobError
INFO: ConvertQueue error processing convert Letting Go: The Pathway of Surre
java.io.IOException: Failed to convert .../Library/OpenAudible/aax/Letting Go The Pathway of Surrender.AAX. Check console for details.
	at org.openaudible.convert.ConvertJob.doConversion(ConvertJob.java:318)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:400)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:452)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:420)

Aug 20, 2020 3:22:16 PM org.openaudible.Audible jobCompleted
INFO: ConvertQueue completed:Letting Go: The Pathway of Surre remaining queue size:0
Aug 20, 2020 3:22:16 PM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error converting Letting Go: The Pathway of Surre: Failed to convert .../Library/OpenAudible/aax/Letting Go The Pathway of Surrender.AAX. Check console for details.
Aug 20, 2020 3:22:16 PM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error converting Letting Go: The Pathway of Surre: Failed to convert .../Library/OpenAudible/aax/Letting Go The Pathway of Surrender.AAX. Check console for details.
Aug 20, 2020 3:22:21 PM org.openaudible.desktop.swt.manager.AudibleGUI _checkAutomation
INFO: Start auto conversion:2
Aug 20, 2020 3:22:29 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by jiuks** [comment]
I have the same issue - trying 2.3.1

**Comment by SamuelBlickle** [comment]
Same here on my Mac. 
2.3.1 works fine.

**Comment by openaudible** [comment]
I pushed another pre-release just now... Should be working.. Will update to 2.3.4 shortly.
https://openaudible.org/prerelease

**Comment by duckiepopo** [comment]
It's working for me now. Says it's version 2.3.3

**Comment by openaudible** [comment]
Oh good. Thanks for the update. Yeah, we don't have a great pre-release versioning system. Will post an update soon.

**Comment by openaudible** [comment]
Sorry for the problems.. Should be fixed now. 
Try the 2.3.4 version. If it doesn't work, please submit a bug report from the About menu and reference #436.
