### ISSUE TITLE
Only downloading from Audible the 1st track of an 2 or 3 tracks long audiobook

### ISSUE THREAD

**Issue by Ratatinator97** [openaudible/openaudible#436]
Many times OpenAudible only downloads the 1st part of the audiobook. (I guess there's an XPATH to correct ;) )

**Comment by openaudible** [comment]
Are you outside of the US? It isn't always clear what the "full download" is.. so we're working on that. Should have a fix soon.

**Comment by openaudible** [comment]
OK. Try the 2.3.4 version. If it doesn't work, please submit a bug report from the About menu and reference #436.
