### ISSUE TITLE
Paid twice

### ISSUE THREAD

**Issue by guszernial** [openaudible/openaudible#438]
I installed OpenAudible to Linux 7/30 and to convert .aax to .mp3 it required a license, which I purchased thru PayPal, see below.

I upgraded OpenAudible to 2.3.4 on Linux today 8/23 and to convert .aax to .mp4a it again required a license, which I also purchased thru PayPal, see below.

Supposedly my initial license covers upgrades for a year, but I couldn't figure out how to apply the previous license. How do I do so? 

![Screenshot_20200823_113419](https://user-images.githubusercontent.com/41842429/90986025-cb4b6f00-e534-11ea-8558-2a075a47cca2.png)
![Screenshot_20200823_113626](https://user-images.githubusercontent.com/41842429/90986048-e74f1080-e534-11ea-95ec-67e308388ca4.png)

**Comment by openaudible** [comment]
Yes, a license is good forever-- and includes free updates for a year. Once license is fine for multiple computers in a family, up to 5 audible accounts.  

Just ask fastspring for a refund on the duplicate.  (I can't tell your name/email to look you up.)

This link should help:  https://openaudible.org/license
