### ISSUE TITLE
Switching to a different Audible account

### ISSUE THREAD

**Issue by HendonRunner** [openaudible/openaudible#439]
As there is no "Disconnect from Audible account" option, do you have to uninstall OpenAudible, and then re-install it to be abe to connect to a different Audible account than the first one used?  Thanks

**Comment by openaudible** [comment]
Just open the OpenAudible browser, and log out of your Audible Account and log into the new account. 

If you want to keep the libraries separate, you need to change the library destination directory in the preferences.
