### ISSUE TITLE
please package with openssl on linux

### ISSUE THREAD

**Issue by stfl** [openaudible/openaudible#44]
I am on Fedora 27 with openssl 1.1.0 installed. rcrack needs 1.0.0 though.
I haven't managed to build RaindbowCrack-NG against my openssl 1.0.0

Please ship the library with the installer. thanks

**Comment by openaudible** [comment]
Me either. Closing as "Won't fix" unless a linux expert comes up with a solution. 

rcrack is open source:
https://github.com/inAudible-NG/RainbowCrack-NG
