### ISSUE TITLE
Some suggestions regarding podcasts

### ISSUE THREAD

**Issue by JohnPeacock** [openaudible/openaudible#442]
I was able to successfully download podcasts that I had purchased within the app by clicking on the podcast "title" page, which took me to a list of individual episides. Clicking download there automatically DTRT (download/convert). If the OpenAudible app could do the same thing, that would be helpful. Perhaps instead of showing the red "missing link" icon, that could provide a secondary drill down to the list of episodes for selection/download.

The other thing was that the filenames for the downloaded episodes were the abstract "internal" filenames. But the metadata was complete, so there is no reason that OpenAudible couldn't save the file as "${Album} - ${Title}" (which is all I did in EasyTAG).

**Comment by openaudible** [comment]
So when you click on a download button, the file gets added to OpenAudible and can be converted? I'll need to look into that more. Sounds promising.

**Comment by JohnPeacock** [comment]
Yes, everything works fine except that the default title list shows the podcast as "No file available for download" but the individual episodes do show up in the listing (once I manually download them in the browser window).

**Comment by openaudible** [comment]
Just getting around to looking at this. It looks like most podcasts are now included in audible. Clicking on the "Episodes", there is only a "Play" button.. What podcast are you looking at or do you have an example of one that is paid? I assume if you go to any random podcast, there is no "Download" for each? For instance: https://www.audible.com/pd/Joe-Exotic-Tiger-King-Podcast/B08D7X8YXQ

**Comment by openaudible** [comment]
Marking this as a "feature request". OpenAudible is mostly for backing up your audio book purchases.  If they're "free" or included with your Audible subscription, we don't have any ability to download them for backup.
