### ISSUE TITLE
Edit chapter metadata?

### ISSUE THREAD

**Issue by TheMeanCanEHdian** [openaudible/openaudible#445]
Is it possible to edit the chapter metadata like with inAudible? I've paid for the full version but I don't see any ways to do this.

Thanks!

**Comment by openaudible** [comment]
No tag editing is currently supported. Its kind of a big task. We're hoping to find a way to scrape the chapter names but I can think of any good mp3 tag editing programs that support chapter meta data. But marking this as a bug suggestion.

**Comment by Xan-Kun** [comment]
Hello, full version here too :-) Recently the chapter titles of some books got strange, sometimes it was just the book title over and over (?!) and mostly it's just the numbers (e.g. chapter 1, chapter 2, etc).
Before I open a new ticket, I just wanted to check. if that is the inteded behaviour, even if the chapters on audible have proper names.
