### ISSUE TITLE
MP3 book file name not the name as the AAX book name

### ISSUE THREAD

**Issue by emreid9997** [openaudible/openaudible#447]
While this is not a big issue, I would really like a setting / options for setting the MP3 file name the same as the book name. The last time I updated (2.1.1) the MP3 files had the same name as the AAX file names. This was nice I redownloaded my entire lib and reconverted them just to get the names on the files (over 450 books). I upgraded to the latest version (2.3.4) yesterday and it is now back to some criptic names for the MP3 files. If there is a setting for  this, I would love to know how to set it, if not it would be great to see it as an option in future versions. 
I only listen to my books on my cell phone so having the real name on the MP3 files would be great. 

Also great program 
Thanks,

**Comment by openaudible** [comment]
Hmm. OA is supposed to use reasonable file names for your books. Early versions used the product ID.. but once we switched to the title, we've tried to keep the names the same. However, if the title is very long, we've played around with trying to shorten the name-- especially for splitting books (as windows has a 250 character file name path).

Feel free to select a book with a cryptic file name and select "Book Report". Also, make sure the book is in your library and you're using OpenAudible to download the book..  you can paste the content of the book here, or send an email or bug report.

Thanks for saying it's a great program!

**Comment by emreid9997** [comment]
Operator issue, I downloaded files from connection window, and not through OA. This cause the issue I was seeing.
