### ISSUE TITLE
Downloading

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#448]
It would be helpful to know which books were actually downloading at any point in time.  I have a very large Audible library and the downloading queue shows several hundred books in the Q, but there is no indication of which book(s) are actually downloading at any point in time.  I can of course scroll through the list, and the Downloading tag will show me if a book is downloading, but it would be helpful if this was always visible for the books that are actually downloading.  Could this be added??

**Comment by openaudible** [comment]
Click on the "Downloading:" text in the Library Status and it will show all books being downloaded.

In the UI, if something has blue text, you can click on it to get matching books or find out more details. So this works to find all books that have mp3s, missing links, your ignored books, etc.  
 
Thanks for the suggestion!
