### ISSUE TITLE
Multi-part books are not downloaded completely

### ISSUE THREAD

**Issue by m3m0ry** [openaudible/openaudible#449]
OpenAudible has trouble downloading titles, which contain more than one part, e.g. when a book is split up by audible. It seems OpenAudible picks one part and downloads just that.

I have now 2-4 titles, which cannot be downloaded properly.

Here are some books, where the download does not work.
If you look at them in the official audible app, you can download parts of it.
Sadly there is no information on audible's website, that the book indeed contains multiple parts.
Not working books:
* [Biology: The Science of Life](https://www.audible.de/pd/Biology-The-Science-of-Life-Hoerbuch/B00DB6RCS8?qid=1600353134&sr=1-1&ref=a_search_c3_lProduct_1_1&pf_rd_p=e54013e2-074a-460e-861f-7feac676b789&pf_rd_r=4ZGMS12YHMYMJ3DK24AG)
* [Der Name des Windes](https://www.audible.de/pd/Der-Name-des-Windes-Hoerbuch/B0092PNN4O?qid=1600353015&sr=1-1&ref=a_search_c3_lProduct_1_1&pf_rd_p=e54013e2-074a-460e-861f-7feac676b789&pf_rd_r=J7RMHA58YRCQ6EYN6482)
* [Neues Leben - Die Hörbibel](https://www.audible.de/pd/Neues-Leben-Die-Hoerbibel-Hoerbuch/B07D538HFP?qid=1600353068&sr=1-4&ref=a_search_c3_lProduct_1_4&pf_rd_p=e54013e2-074a-460e-861f-7feac676b789&pf_rd_r=0VRZRQJXHW3NQ0KGZD78)

Since I am in germany, i use audible.de, however this shouldn't be a problem.

System info.
* OpenAudible 2.3.4
* Linux - Debian-testing amd64
* Installed from: [OpenAudible_2.3.4_x86_64.deb](https://openaudible.org/latest/OpenAudible_x86_64.deb)

P.S.: I was not sure, if this is the "split book problem" mentioned in other issues, or whether this is a completely different one.

**Comment by m3m0ry** [comment]
Update!

I probably did not delete the books properly, after updating OpenAudible.
The first two books do work and as far as I can see, they are downloaded completely into one mp3 file.

The last book "Neues Leben - Die Hörbibel" still does not work.
In the "State:" of OpenAudible I get a text in German (I am located in Germany), roughly translated as "This audio format is not supported. Please use a different audio format in order to download this title..."

**Comment by openaudible** [comment]
Regarding the last book that isn't converting.. Delete the previous AAX version.. then try using the OpenAudible browser to navigate to that last book in your library. There should (must) be a "Download (Full)" button next to the book. Click that, and hopefully it will download to the Openaudible library. From there try to convert. If that still fails.. please send a bug report from the about menu and reference 449

**Comment by m3m0ry** [comment]
It seems that the problem is with audible itself. I am not able to download the whole thing. In a browser, or in the OpenAudible browser, I get the exact same error message.
I could download the 13 individual parts.
Now I don't know how to merge them together or force OpenAudible to convert them one by one, so I can merge the mp3 by myself.

I tried to convince OpenAudible (via the `books.json` file, but it insists, that the file (even if I rename it) was not downloaded yet.
Is there some command on the terminal I can use? Something like `OpenAudible --convert --intput foo.aax --output bah.mp3`?

**Comment by openaudible** [comment]
I'd contact Audible support and say you're unable to download the whole book. 

We don't have good support for handling parts of a book in OpenAudible. However, the conversion is done by ffmpeg and the output of the commands used to convert from aax to m4a (or mp3) is shown in the console window.  If you're savvy, you could copy and paste the command, edit it, and run it for each part.. save them alphabetically and use the "join" feature in OpenAudible.
