### ISSUE TITLE
[Request] File format M4A

### ISSUE THREAD

**Issue by mumi** [openaudible/openaudible#45]
Would be nice if you could choose the File Format/Codec. I'm recently converting my audiobooks with a self-compiled FFmpeg where you can use the Fraunhofer FDK AAC Codec and save it into an .m4a. It's the Codec which is used by Audible

**Comment by openaudible** [comment]
Noted.

**Comment by alvarow** [comment]
This would be cool... perhaps a fallback to mp3 is certain size is reached or to .m4a. Or make it the transcoding command a user editable field so we could tweak things.

**Comment by iconoclasthero** [comment]
Personally, I would like to see the option to export as .wav and then one could do what one will with the format (e.g., with ffmpeg).  I prefer .opus at 24 kb/s which is pretty much transparent and quite small.

**Comment by openaudible** [comment]
Revisiting.. M4A is an interesting or good option... and can be done quickly.   Unfortunately it isn't widely supported.. For instance, VLC doesn't play them. Still on the maybe someday.. For now, easy to do with ffmpeg: 
`ffmpeg -activation_bytes XXXXX -i "test.AAX" -c:a copy test.m4a`

@iconoclasthero Wav files are limited to 4GB.. Which makes them worthless for audio books. Maybe a future version can do opus but I wanted to keep the UI simple. Same problem as many players don't do opus.

FYI, MP3 Audio quality can be edited in the settings.json mp3Qscale:4 But good to remember its Its an audio book, not a symphony.

**Comment by Presjar** [comment]
There are many android apps that can play back the .m4a converted audiobook while keeping tack of current location and bookmarks. I believe adding direct .m4a conversion would be a great addition to the project.

**Comment by iconoclasthero** [comment]
@openaudible:  Point taken, I hadn't thought of that.  That said, it would be nice if the files could be encoded in something lossless to preserve the original quality (i.e. .flac) as well as mp3 for ease of use generally.  From there, I'll put it in whatever format I want (.opus) via ffmpeg.  Obviously lossy -> lossless doesn't make the source better it just preserves the integrity of the original significantly better than lossly (aax) -> lossly (mp3) -> lossy (opus/m4a).  

WRT to "many players don't do opus," I'm not bothered by that.  All Android devices going back to at least my original Google Nexus can play .opus (though sometimes the files need to be renamed .ogg) and as "Smartphones running the Android operating system hold an 87 percent share of the global market in 2019 and this is expected to increase over the forthcoming years. The mobile operating system developed by Apple (iOS) has a 13 percent share of the market."  _Source:  Statista, Sep 13, 2019_, globally only those who intentionally use a locked down OS (i.e., they've purchased incompatibility as a "feature") are likely to have a problem.  VLC is platform-independent and can play .opus and it is the standard for YouTube, SoundCloud, Spotify, etc.  With the industry behind it, .opus will eventually overtake other formats in a way that Vorbis never could have.  For those who are still using .mp3 players...well, it is the second decade of the 21st century...

The audiobook app I use (Smart AudioBook Player) plays .opus natively w/o needing them named .ogg and it was the first and only audiobook app I've ever tried so either I got lucky or Android app developers are already using libraries that have .opus in them.

**Comment by alvarow** [comment]
> Revisiting.. M4A is an interesting or good option... and can be done quickly. Unfortunately it isn't widely supported.. For instance, VLC doesn't play them. Still on the maybe someday.. For now, easy to do with ffmpeg:
> `ffmpeg -activation_bytes XXXXX -i "test.AAX" -c:a copy test.m4a`

This is what I've been doing, this is the best option for me, it simply removes DRM and leaves the exact lossless audio from Audible. VLC certainly plays .m4a. I myself use BookPlayer app on iPhone. I can't complain about the quality of the MP3s OpenAudible produces.

Thanks for all the work on OpenAudible!

**Comment by alvarow** [comment]
> @openaudible: Point taken, I hadn't thought of that. That said, it would be nice if the files could be encoded in something lossless to preserve the original quality (i.e. .flac) as well as mp3 for ease of use generally. From there, I'll put it in whatever format I want (.opus) via ffmpeg. Obviously lossy -> lossless doesn't make the source better it just preserves the integrity of the original significantly better than lossly (aax) -> lossly (mp3) -> lossy (opus/m4a).
> 
> WRT to "many players don't do opus," I'm not bothered by that. All Android devices going back to at least my original Google Nexus can play .opus (though sometimes the files need to be renamed .ogg) and as "Smartphones running the Android operating system hold an 87 percent share of the global market in 2019 and this is expected to increase over the forthcoming years. The mobile operating system developed by Apple (iOS) has a 13 percent share of the market." 

> To put it another way: why should the vast majority of mobile-device users running Android have to suffer because of the minority who use iOS?

Well, if you look the markets where Audible operates, I think iOS usage is a lot higher than 13%... so take scope into consideration here. .AAX files are .m4a with DRM, simply stripping the DRM yelds a .m4a file with no loss in quality, from which point you can Opus/mp3/etc ... and it works on mp3 players from the 20th century, iOS and Android.

**Comment by iconoclasthero** [comment]
The solution with the ffmpeg -copy to m4a is not reencoding so that means
that I can just -acodec libopus -b:a 17k from the .aax to .opus as well.  I
will look into and try this and that will be the end of my concern.

--sent from my mobile device

**Comment by openaudible** [comment]
In progress for next release.

**Comment by openaudible** [comment]
M4A support has been added to 2.0.6 and newer.

**Comment by Presjar** [comment]
Thank you for this update!
