### ISSUE TITLE
Unable to create or load required directories.

### ISSUE THREAD

**Issue by kaiamaeve** [openaudible/openaudible#451]
So I changed the folders for my app to point to my external hard drive, and now upon trying to open the app, I get this error message. I did not make sure my drive had read/write permissions. Oops.

Unable to create or load required directories. Check that the drives are read/writeable. Error: Unable to create directory: /Volumes/easystore/aax You could also look at or erase the directories.json file.

How do I fix this, without messing with the code? Thanks!

**Comment by openaudible** [comment]
I don't recommend setting the working directory to an entire volume (easystore).
You might try creating a new folder on /Volumes/easystore/OpenAudible
Then set that as the "working" directory. 

If you get the same error, open the terminal.app and type
chmod r+w /Volumes/easystore/OpenAudible
