### ISSUE TITLE
Conversion isn't working

### ISSUE THREAD

**Issue by dochertp** [openaudible/openaudible#452]
OpenAudible connects to my account (UK) just fine.

- I see a list of my books.
- I chose book "Brazil" by Michael Palin as a test.
- The file starts downloading no problem:
![Downloading](https://user-images.githubusercontent.com/71666087/93807670-3dee5e00-fc4b-11ea-8a20-36da00729613.PNG)

- When the file is downloaded, I see this in the "state" field
![Downloaded](https://user-images.githubusercontent.com/71666087/93807860-873ead80-fc4b-11ea-8d49-6847d74c6085.PNG)

- I can see the downloaded file in Windows Explorer, with name Brazil.AAX.part
![TMP_Folder](https://user-images.githubusercontent.com/71666087/93808008-b7864c00-fc4b-11ea-8c49-d130f18f56c8.PNG)

- Back in OpenAudible, I can't choose the action "convert" - it is greyed out.
![CantConvert](https://user-images.githubusercontent.com/71666087/93807977-b05f3e00-fc4b-11ea-87a4-4d63ae453173.PNG)

- For reference, my account settings:
![AccountSettings](https://user-images.githubusercontent.com/71666087/93808613-83f7f180-fc4c-11ea-849e-3fe40d53bac7.PNG)

**Comment by sirangler** [comment]
Hi Paul,
I have been considering buying OpenAudible so that I can convert my AAX protected files to clean MP3 files and play them wherever I want. It seems like you are having problems with that exact feature, one that OpenAudible claims it easily does. I would like to be notified if OpenAudible solves your problem Quickly and without putting you through a lot of grief. Good luck. Thanks,
Mark

**Comment by openaudible** [comment]
Hi,

Sorry you're having the problem. The file Brazil.aax.part looks like a partially downloaded file. Check the log messages (CTRL-D) and see if you got any errors in the download process. If there was an error, that .part file should have been deleted (and an error printed.) or if it finished successfully, it should have been renamed without the .part "brazil.aax")

Give the book more time to download and or check for errors in the log. 

Your report was really detailed-- but the log messages would have been most helpful. Almost every action is pretty well logged. So you could restart the application, re-download, and try a conversion.. and keep an eye on the logs for errors. Sometimes its as simple as being out of hard disk space in the destination directory. 

We got a little behind on tech support. But of course, if you can't get it to work, you can get a full refund. But 99% of our users are successful. 

Please re-open if you add to this.

**Comment by dochertp** [comment]
Hi,
Please find attached a log file.  This time I tried book "Caliban's War: The Expanse, Book 2".  The file seems to download just fine, but it retains the *.AAX.part extension.
![TMP_folder_2](https://user-images.githubusercontent.com/71666087/95086904-51a4c480-0721-11eb-82d0-858a78eaa4c1.PNG)
[log.txt](https://github.com/openaudible/openaudible/files/5327726/log.txt)

Looking in the log file (and I'm only guessing), it is a little confusing.  The second last message states "DownloadQueue completed:Caliban's War: The Expanse, Book remaining queue size:0".  But then the last message states "error downloading Caliban's War: The Expanse, Book: C:\Users\pa..."

**Comment by dochertp** [comment]
I also want to add that I just uninstalled version 2.3.4, and went back to 2.0.6 (which I had in an archive).  Here download and conversion seems to be working perfectly.

**Comment by openaudible** [comment]
The program appears to be failing to move the temp download file to the final destination. We use a system level call to do this, and we check that the file exists and the destination is not in use..  I've added some code to manually copy the file if the "system move file" fails. That should fix it. I'll try to get a new release out soon and post an update.

**Comment by dochertp** [comment]
Amazing :) Thanks for the update.

**Comment by openaudible** [comment]
Give the latest 2.3.5 a try. And send a copy of the transcript if it happens again.

**Comment by dochertp** [comment]
Fixed, working perfectly!!  Thanks!
