### ISSUE TITLE
Returned books showing up as purchased.

### ISSUE THREAD

**Issue by MN-Joe** [openaudible/openaudible#453]
So in 450 books I have one that was not what I felt it was presented as and I returned it so I do now own it but it shows in my list.  I'm able to ignore it but it comes back when I poll for all books.

**Comment by openaudible** [comment]
Hm. Once you ignore it, it should not "come back". But go ahead and delete it. If it shows up in your "Library" view (in the web browser) maybe its not really returned? Not sure. Sorry!
