### ISSUE TITLE
Sorry but don't know how to request features via GitHub?

### ISSUE THREAD

**Issue by MN-Joe** [openaudible/openaudible#454]
In the downloads it doesn't show if a book is finished?  I see that status in the Audible library but don't see it in the OpenAudible fields.  If if there was a manual entry where I could track that it would be most helpful.

**Comment by openaudible** [comment]
Do you mean "finished reading" or finished downloading? We don't track whether you've read the book or where your last position is.

**Comment by MN-Joe** [comment]
Finished the book.  You see it in audible is why I asked.  The library shows you.  Even a manual field would b e helpful.


________________________________

**Comment by openaudible** [comment]
I'm trying to avoid "feature creep" (adding too many features that complicate the program, are hard to maintain and don't add a ton of value.) But marked as a feature request. Thanks for checking in.
