### ISSUE TITLE
Windows 10 blocked download

### ISSUE THREAD

**Issue by mamasloth** [openaudible/openaudible#455]
I want to purchase OpenAudible but Windows10 blocked the download, stating that it could harm my device. I'm using the default Windows virus protector, Defender Smart Screen. Is there any way to get around this and why would it report openaudible as malicious?

**Comment by openaudible** [comment]
OpenAudible is unsigned, meaning some anti-virus programs will warn you. You should be able to mark it as safe or remove it from "quarantine". Most of our users are on Windows 10, so maybe your machine's security settings are set higher than normal.
