### ISSUE TITLE
Failed to Convert error

### ISSUE THREAD

**Issue by meatcakes** [openaudible/openaudible#456]
One of my books synced and converted perfectly.  But my second book keeps saying "failed to convert" under the state section.  It will go through the whole file and then right at the last second says this error but I can't find any explanation as to why.
![image](https://user-images.githubusercontent.com/71905199/94316504-50adaf00-ff39-11ea-9482-389d29c9bfc4.png)

**Comment by openaudible** [comment]
Would need to see the error console. CTRL-D. and copy and paste.

**Comment by openaudible** [comment]
Give the latest 2.3.5 a try. And send a copy of the transcript if it happens again.
