### ISSUE TITLE
Can't login with "Audible account"

### ISSUE THREAD

**Issue by airtac** [openaudible/openaudible#458]
Hi,
Just installed version 2.3.4 and tried to connect to audible.com.  The site opens but I cannot enter my login info.  I have tried just using your browser and going too audible.com and it will display anything.  I also tried going to about purchase and your browser open and it show nothing.   

system info
Ubuntu 20.04

Doug

**Comment by airtac** [comment]
Hi,  
I think I may have  found something.
 I found the program and trying running it as root.  By starting it in a terminal.   Here is the error when I try to open a browser.


(WebKitWebProcess:727343): Gdk-ERROR **: 17:44:04.828: The program 'WebKitWebProcess' received an X Window System error.
This probably reflects a bug in the program.
The error was 'BadValue (integer parameter out of range for operation)'.
  (Details: serial 211 error_code 2 request_code 151 (GLX) minor_code 34)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
Sep 26, 2020 5:44:11 PM org.openaudible.desktop.swt.manager.browser.AudibleBrowser setUrl
INFO: AudibleBrowser setURL: about:blank
Sep 26, 2020 5:44:13 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Purchase
Sep 26, 2020 5:44:13 PM org.openaudible.desktop.swt.manager.browser.AudibleBrowser setUrl
INFO: AudibleBrowser setURL: https://openaudible.org/purchase

Hope this helps

DougD

**Comment by openaudible** [comment]
A standard Ubuntu install usually works just fine. This is a new bug for us. 
Google doesn't turn up any easy fixes, but has some other people with the same error.

https://www.google.com/search?q=Details%3A+serial+211+error_code+2+request_code+151+(GLX)+minor_code+34&rlz=1C1CHBF_enUS917US917&oq=Details%3A+serial+211+error_code+2+request_code+151+(GLX)+minor_code+34

I wish we could say we run on all linux systems.. No real suggestions at this time. Sorry!

**Comment by airtac** [comment]
Hi

I have been running Ubuntu for a long time and I do not do any mods.  
System info
Ubuntu 20.04 LTS
OS type 64bit
GNOME Version 3.36.3
Windowing System X11
Memory 31.3GIB
Processor Intel Core I9-9900K CPU 3.60GHz X 16
Graphics NVIDIA TU104 [GeForce RTX 2080 Super]

Hope this helps

**Comment by openaudible** [comment]
I'm really sorry. We use Eclipse SWT for the application engine and WebKit to create a browser. The webkit isn't working on your system. My guess is the high-end graphics card or driver is causing a problem. You could try installing "Eclipse IDE" which might upgrade/install a required dependency. 

sudo snap install --classic eclipse

(You can delete it later)
