### ISSUE TITLE
Help with "Invalid" License

### ISSUE THREAD

**Issue by gradalis** [openaudible/openaudible#459]
Hello! OpenAudible is not accepting the license I purchased in May of this year. My operating system is a Mac OS 10.13.6. I tried activating my license several time but I keep getting a window that says my license is invalid. On the same page, it shows my name and indicates that I have free updates until May of 2021. I have tried turning off my firewall, but to no avail. Any help would be appreciated. Please help! My email address is gradalis@comcast.net. :(

**Comment by gradalis** [comment]
UPDATE: I have tried contacting OpenAudible with this issue but have not yet received a reply. Does OpenAudible have a a customer support number that is available to reach by telephone? I just purchased my license in May 2020, so I am puzzled that their software won't accept the very license code that they issued me five months ago. Thank you!

**Comment by gradalis** [comment]
UPDATE 2: A Google search using the terms "openaudible,"  "license," and "invalidated" just yielded me the following text: 

> "License Invalidated. Usually this is due to returning the product. If you bought two copies, one order may be deleted and the other kept. Occasionally a license is invalidated if excessive audible accounts are used or if a license has been shared or made public."

I have neither returned my product, nor have I purchased two copies. I am the only person to have used this account and have not shared my license or password with anyone. This is very frustrating. I hope someone will contact me very soon.
This is  disappointing, as the software worked as expected and I was otherwise extremely happy with my purchase. Let's hope someone from OpenAudible reads this message soon. Fingers crossed...

**Comment by openaudible** [comment]
This can happen if you use more than 5 accounts on a single license. Perhaps the license key was made public, or you have a LOT of family members. We're working on a little more heads up in this regard.. Will look for "locked/invalid" licenses and see what I can do. But generally, if you are abusing the license, we recommend you stop using the product and request a refund.

**Comment by gradalis** [comment]
Hi. Please read my updates (see above). I have neither returned my product, nor have I purchased two copies. I am the only person to have used this account and have not shared my license or password with anyone. To the best of my knowledge, I have not misused my license in any way. What information can I provide you to help resolve the situation? My email is gradalis@comcast.net.

**Comment by gradalis** [comment]
![BDE1D097-7D2C-4D40-91B1-CAA9C45466CA](https://user-images.githubusercontent.com/71987863/94624556-8f11d980-026b-11eb-8e02-32cd32e305ed.jpeg)

**Comment by openaudible** [comment]
I reset the license code and sent a personal email. Closing.
