### ISSUE TITLE
More progress with Syncing my library on OS X

### ISSUE THREAD

**Issue by Leopere** [openaudible/openaudible#46]
I'll post the console output in a self-destructing paste again in case it has secrets.  https://haste.nixc.us/ayikahukoxay.cs

**Comment by openaudible** [comment]
When you're viewing your libarary in the browser, when you hover over (or click) a "Download" link, it needs to link to the book. If it takes you to a page called "How to listen", one of your Audible settings needs to be changed. In Audible, go to Account Details:, Settings -> then toggle the: Software Verification.

**Comment by Leopere** [comment]
Okay as per your instructions I've enabled Software Verification, as it was off prior to your instruction to toggle said setting.

**Comment by Leopere** [comment]
It works! How wonderful I thought that setting was supposed to be set to unchecked.  Thanks very much for your time and attention the software appears to be functional.
