### ISSUE TITLE
demo

### ISSUE THREAD

**Issue by gogginguy** [openaudible/openaudible#461]
(This seems to be the only way of contacting you, so...)

Exactly what is the 'demo' version demo-ing?  It doesn't seem to do anything I can evaluate other than read from my audible library, and that falls well short of what I'm needing it to do?  It doesn't export.  Does it play?

**Comment by openaudible** [comment]
The demo reads your audible library and gets a list of your books. From there, AAX files can be downloaded. Conversion to MP3 and/or M4A is disabled. Exporting or importing books is also disabled. We don't include a player-- converted files will play with any audiobook player.
