### ISSUE TITLE
refreshing info doesn't give genre

### ISSUE THREAD

**Issue by taratears** [openaudible/openaudible#463]
I read that if I used refresh info it would update the genre tags but that doesn't seem to work. Is there anything else I can do or am I just doing something wrong? Thank you for any help.

**Comment by openaudible** [comment]
OpenAudible should if you select the book and select "Refresh".
However, it can fail for a few reasons: Try "Action: View in Audible". That should display the audio book page and the genre is supposed to be scraped from there, for instance, above the book image, it might say: Biographies & Memoirs  Art & Literature

If the link is broken or not present, that can be why it isn't filled in.

If it does show up and the genre isn't filled in, it could be a bug on our end, especially if you're from a country outside of the US.  Feel free to send more details.

**Comment by taratears** [comment]
View in Audible is greyed out, I'm in the states, if that helps. If the link is missing, how do I fix that? Thank you.

**Comment by openaudible** [comment]
You could try doing a full rescan of your library. If the book is in your library, hopefully that will fill in. If the book was imported from another backup, it may not come back.

**Comment by openaudible** [comment]
And, at some point we may add a "tag editor" to the application to allow users to modify the meta data.
