### ISSUE TITLE
Using Audible books on bone conduction headphones (Xtrainerz by Aftershocz))

### ISSUE THREAD

**Issue by rlewiseyemd** [openaudible/openaudible#464]
When I download a book on Audible, I have to convert to an MP3 format on OpenAudible. Yet, there are no separations in the download by chapter/section/whatever.  If I lose my place, it is hard to get back to where I left off.  Is there a way to introduce  sections or use the existing chapters in the OpenAudible download?

**Comment by openaudible** [comment]
No, we just convert the audio as it was provided. You can contact Aftershokz and let them know as a feature request.
