### ISSUE TITLE
Add Favicon

### ISSUE THREAD

**Issue by LanceMcCarthy** [openaudible/openaudible#468]
Hi team, this is a feature request for when OpenAudible generates the website.

Please do either or both:

* Use your default favicon when generating the website
* Let us select a favicon when generating the website.

### Temporary Workaround

As a workaround, I am manually editing the index.html and adding them in:
![image](https://user-images.githubusercontent.com/3520532/95363514-8dfd2f80-089d-11eb-8776-2b45e8642745.png)

**Comment by openaudible** [comment]
Done for next version. Thanks for the suggestion!

**Comment by LanceMcCarthy** [comment]
Fantabulous. 

I must say, I am constantly reminded that paying for this app when I went from v1 to v2 was one of the best investments I've made (in both personal media as well as OSS).

**Comment by openaudible** [comment]
Thanks! Added the favorite icon to the web site.

**Comment by LanceMcCarthy** [comment]
Just regenerated the page after the update, nice job! Thanks :)

![image](https://user-images.githubusercontent.com/3520532/95759008-2a954800-0c77-11eb-8f13-7aff555f6a06.png)
