### ISSUE TITLE
Version 2..3.5 - Mac OSX - 10.15.7

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#469]
Not a big deal, but in the hyperlinks under "about", Help and Project Web Page do not link on my system.

**Comment by openaudible** [comment]
I am unable to reproduce any problems.
I open About OpenAudible dialog
Clicking on https://openaudible.org opens the internal web browser.
Clicking on Registered to [name] opens the License dialog.

If you see any errors in the console (CMD-E) let me know and I might be able to fix.
