### ISSUE TITLE
Cannot Sync Library (Quick Start & UI -- missing essential instructions?)

### ISSUE THREAD

**Issue by brianjlacy** [openaudible/openaudible#47]
After connecting my Audible account, I clicked "Full Library Sync". It told me the Sync completed successfully, but no content was downloaded.

I noticed a previously closed Issue [here](https://github.com/openaudible/openaudible/issues/36#issuecomment-427436339) which suggested checking the box to verify the Audible Download Manager. I tried this, and so far it seems to have fixed the problem.

However, I did not see this mentioned anywhere in the Quick Start or in the application UI. If this is required for the sync to function, this should be clearly stated in both locations.

See my [console log](https://pastebin.com/K9gH2tZV).

**Comment by openaudible** [comment]
Added some new help messages.. https://openaudible.org/settings.html
Thanks for the feedback.
