### ISSUE TITLE
It doesn't work with Audible.ES

### ISSUE THREAD

**Issue by heyvoon** [openaudible/openaudible#471]
Awesome app but it doesn't work with Audible.ES! Is there a possibility to make it work with ti?

**Comment by openaudible** [comment]
We don't have an account there. But there needs to be an audible page where you view your library and have the option to download your books. (Usually, a "Download" button.) Some regions, like Japan and Italy don't have that. So let me know if there is an option to download your books. Alternately, there may be an Audible Download Manager PC app that might allow you to get the .AAX file for your books-- then OpenAudible could convert them.

**Comment by heyvoon** [comment]
Unfortunately Audible.ES doesn't seem to have download button nor a Download Manager App for PC. When trying to download the PC app from Spanish website I am redirected to the US one Download Manager which doesn't show my spanish library.😒
![image](https://user-images.githubusercontent.com/3281265/96689927-5608e880-1383-11eb-8edf-c6fb1c1f3cfc.png)

**Comment by openaudible** [comment]
Appreciate the report. Unfortunately, it isn't something we can fix on our end. I believe Italy, Japan (?) and Spain all have this and are not compatible with OpenAudible.
