### ISSUE TITLE
Building the Web Page

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#472]
I downloaded my 8900 plus AAX files from my Audible account - all in a directory .AAx.  MP3 conversions are all in  .mp3.  Starting from that position, how, exactly do I generate the web page?  Every attempt I make seems to omit more than 70% of the book cover images and/or, omits the "descriptive" test associated with each book.

Can you explain the exact structure of the files needed in the directory that supports downloads, conversions and web. It may be obvious, but I am obviously not getting it.

The only time I have had a successful result from this was several months back when the AAX download was followed immediately by conversion and web export - which took about 9 days from start to finish - there must be a way to get to the end result with all of the intermediate files available without additional download!  

Please help - great program - the problems are mine, not the developers!

**Comment by oboe45** [comment]
That should read "890" AAX files, and "Descriptive" text not test. Brain is faster than my fingers

**Comment by openaudible** [comment]
If meta data and images are missing, you may need to re-sync your library with OpenAudible -- Controls: Full Library Sync.

Then select some books and make sure the images and data are there. If not, maybe the book was returned or no longer has a valid audible http link?

If a particular book is missing an image, you could try selecting it, then:  F5 (Action: Refresh Info) and check the log for any errors.  

We log a bunch of stuff to the console when building the web page.. so maybe you can find helpful errors about missing images, etc.
