### ISSUE TITLE
novice questions

### ISSUE THREAD

**Issue by rbkrdf** [openaudible/openaudible#475]
Hi All, 
I have two novice questions and I'm guessing/hoping the answers are simple but having spent over an hour trying to figure them out, I've had no success: 

(1)I can't for the life of me find the folder created by the app. to keep the files in it. I'm on a mac (Catalina 10.15.7) and have scoured every folder  on the drive, in Home etc. and see nothing, the only thing that comes up in the finder when I put in OpenAudible is the app. I have successfully converted a file so I know that it has to be housed somewhere. 

(2) I haven't been able to split it into chapters. When I click that option I am taken to a screen (see attached shot) that appears to be asking me to pick a destination folder, but the "open" option is greyed out. 

Any help is much appreciated! Thank you!

<img width="878" alt="Screen Shot 2020-10-23 at 10 25 47 AM" src="https://user-images.githubusercontent.com/73350469/97016003-3657f880-151a-11eb-9137-8382ab53bf08.png">

**Comment by openaudible** [comment]
Yeah, on a Mac, the preferences are hard to find. Menu: Edit: Settings
It should show you where output files are saved (web and books)
Also, at the bottom, there is a button to show the OA preferences directory (setting files). 
To Split a book in your library, select it and right-click "Split Book". It should show up in your "books" directory.
To split an MP3/m4a, use the file menu split. (But not recommended.)
