### ISSUE TITLE
Feature Request: Conversion multi-thread options

### ISSUE THREAD

**Issue by tomtom90** [openaudible/openaudible#479]
It would be great to be able to configure the thread-pool size for conversions as the amount of max simultaneous conversions (Default to 50% of available threads or something).
This would be future proofing the software and improve the first use experience and accelerate full library conversions.

**Comment by openaudible** [comment]
You can change the number of concurrent conversions and downloads, up to 10, by manually editing the settings.json file and restarting the app. It shouldn't make much of a difference in overall performance though, so we haven't bothered to change the preferences UI. (Search settings.json in the Issues to find more details.)
