### ISSUE TITLE
Linux. "Play Audio book" option grayed out

### ISSUE THREAD

**Issue by icodeiexist** [openaudible/openaudible#480]
Hello, I bought the full version. I read in another issue that there is no reliable way to open mp3 files on Linux, but I wonder, is there any way to specify openaudible how to? like in a config file or maybe a compile-time option? I would use something like xdg-open myfile.mp3

**Comment by openaudible** [comment]
Yeah, it is a known limitation. 

Will work on fixing that.. Will probably make you define a command line to run.

One problem is that if you start playing your book, then quit OpenAudible, your book will (probably) stop playing as well (as it is a child process.)  Was also trying to keep the preference dialog simple...  

Will update you on the progress.

**Comment by openaudible** [comment]
Fixed in next release and in beta. Any feedback appreciated. See #510
