### ISSUE TITLE
Location of preferences

### ISSUE THREAD

**Issue by kausban** [openaudible/openaudible#481]
Is there a way to modify the location of preferences? It currently seems to be hardcoded to "/home/username/OpenAudible"?

Furthermore, a default could be "$XDG_DATA_HOME/OpenAudible" or "$XDG_CONFIG_HOME/OpenAudible" (see: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html).

**Comment by heartburn22** [comment]
I would love to be able to move my OpenAudible folder!

**Comment by openaudible** [comment]
Preference directory is currently hard coded. 

I just added some code to check environment variable $OPENAUDIBLE_HOME and if it points to a directory, we'll use that. Should be in the next version and will work with all platforms. 

$XDG_DATA_HOME was a good thought, but isn't used by Ubuntu and would get messy trying to use and not break existing users. 

This feature will be added to all versions after 2.3.5.

**Comment by kausban** [comment]
Thanks. This would already be a nice alternative. :+1: 

"$XDG_DATA_HOME was a good thought, but isn't used by Ubuntu and would get messy trying to use and not break existing users." - could you clarify what you mean (I am admittedly not familiar with ubuntu). 

AFAIK: "If an environment variable is either not set or empty, its default value as defined by this specification should be used instead." see: https://specifications.freedesktop.org/basedir-spec/latest/ar01s04.html

So should work the systemd based ubuntu systems I presume.

**Comment by openaudible** [comment]
I'll take another stab at adding support for XDG_DATA_HOME.

**Comment by openaudible** [comment]
Give the beta a try. Should work with XDG_DATA_HOME or OPENAUDIBLE_HOME .  Re-open if not fixed.

**Comment by wsm4826** [comment]
I apologize in advance for what may be a simple task for most

I am trying to change full library to external drive - web directory allows me to point to correct location - but preferences is static and asks "to set an environment variable to OPENAUDIBLE_HOME that points to the directory location" - running macos catalina and I have no clue as to the steps to accomplish this - thanks for our help
