### ISSUE TITLE
Purchase date scrape not working - consider adding "purchase order"?

### ISSUE THREAD

**Issue by jegirard** [openaudible/openaudible#484]
I would like to be able to see new books that I have recently purchased at the top of the library list in OpenAudible. That way, the list of books can show up in the same order they show in Audible - reverse chron by purchase date.

Currently, most of the purchase date data points are missing for my books (3 of 160 are available - and I actually don't think the few that do exist are correct).

Suggest either tuning the scraping of purchase date OR allowing sort by Audible order (which SHOULD allow for "reverse chron by date of purchase" sorting) - presumably this would be straightforward since the app just clicks through page by page to sync library.

<img width="1700" alt="2020-11-07_07-09-19" src="https://user-images.githubusercontent.com/8964708/98444752-4948fc00-20c8-11eb-94e8-a905a60b189b.png">

**Comment by siditm** [comment]
Already suggested it: https://github.com/openaudible/openaudible/issues/426#issuecomment-700885118

Also if you are on v2.3.5 the issue has been **partially resolved for some users** _(date format is incorrect at least in my case YYYY-DD-MM with breaks sorting :( )_, it also had been closed?!
This worked for me (_except screwed date format_): https://github.com/openaudible/openaudible/issues/426#issuecomment-710043985

**Comment by openaudible** [comment]
To be fixed in the next release. Also available in the beta.

**Comment by jegirard** [comment]
Great to hear thank you!

- John
415-595-1820
