### ISSUE TITLE
How do I add a folder with existing subfolders/mp3 books

### ISSUE THREAD

**Issue by Andytr1** [openaudible/openaudible#485]
Hello,
I just purchased the "full" version of the openaudible. I already have a folder structure with subfolders that contain mp3 audio books. How do I add them to openaudible all at once?

**Comment by openaudible** [comment]
If the book files are single MP3's or M4A's, you can drag and drop them into the app and a copy will be made and stored in the MP3 or M4A dir. If they are files separated by chapter, you would need to join the books first.. then import that file into OpenAudible.
