### ISSUE TITLE
Long book / large file conversion crashes...

### ISSUE THREAD

**Issue by ollybain** [openaudible/openaudible#486]
Hi!

I've been using OpenAudible a lot, awesome as it is, but I don't seem to be able to convert long books / big files to mp3. It starts off happily enough, but then grinds to a halt and takes the whole computer (manjaro linux system) with it into a gigantic stall, before finally crashing the session.

Is there anything I can do about this? I have tried running the ffmpeg directly from the command line but it still happens. Also, it happens on both XFCE and LXQT desktops. It is very annoying, as I have a small subset of Audible books that I can't listen to!

O.

**Comment by openaudible** [comment]
If the jvm crashes, there should be a log. You can try running from the command line. There is a usually a debug_linux.sh script in the application directory that you can run from the command line. When it freezes, would be nice to see what it was doing. After a crash, you could send the last of the output. 

Or to run from the command line, cd to the application dir and type: 

java -Dfile.encoding=UTF8 -cp ./lib/org.eclipse.swt.gtk.linux.x86_64.jar:./lib/openaudible-jar-with-dependencies.jar org.openaudible.desktop.Application

There are some other things to try as well. but obviously shouldn't be happening.

**Comment by ollybain** [comment]
I don't entirely follow that, but will try. I can report that if I run the ffmpeg command from the command line, and add in -report, I get about 600MB of the following (excepting the preamble, of course):

"
cur_dts is invalid st:0 (0) [init:1 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
[mp3 @ 0x55fee33c5580] Delay between the first packet and last packet in the muxing queue is 10004898 > 10000000: forcing output
[mp3 @ 0x55fee33c5580] Delay between the first packet and last packet in the muxing queue is 10004898 > 10000000: forcing output
cur_dts is invalid st:0 (0) [init:1 i_done:0 finish:0] (this is harmless if it occurs once at the start per stream)
[mp3 @ 0x55fee33c5580] Delay between the first packet and last packet in the muxing queue is 10004898 > 10000000: forcing output
[mp3 @ 0x55fee33c5580] Delay between the first packet and last packet in the muxing queue is 10004898 > 10000000: forcing output
[mp3 @ 0x55fee33c5580] Delay between the first packet and last packet in the muxing queue is 10004898 > 10000000: forcing output
[mp3 @ 0x55fee33c5580] Delay between the first packet and last packet in the muxing queue is 10004898 > 10000000: forcing output
[mp3 @ 0x55fee33c5580] Delay between the first packet and last packet in the muxing queue is 10004898 > 10000000: forcing output
"

In order to save some time, I should say that it doesn't instantly crash, the whole system slows down to a crawl, implying that the conversions is hogging all the resources. Should I still do what you said? Obviously, I can't commit to more than an hour of time pre-slowdown before the problem seriously triggers.

Also, which application dir do you mean? The OpenAudible, the ffmpeg supplied with it, the one native to the system, or even java?

Thank you kindly!

OB.

**Comment by openaudible** [comment]
So you're saying FFMPEG is slow when you run it from the command line? You got enough memory and CPU? The ffmpeg is pretty well debugged and solid. You could try downloading a new/different version of ffmpeg and try that. 

If its just OpenAudible running ffmpeg that is slow, that's a separate issue.

One strategy is to set the conversion format to M4A. Those conversions are fast and take less cpu/ram/time.

**Comment by pcarrick** [comment]
ollybain,

I have a huge library that I was able to download more than 3,000 books. Some of them are very long. I had success using OpenAudible to download and it is an amazing tool! Super awesome! I did have trouble with the volume of books and with size. I found some tricks to get things to work and for conversion I wrote a simple script It seemed to work better on large books. Let me know if you want me to share it.

Cheers,

**Comment by ollybain** [comment]
I thought that 4GB of memory and 3.33 Ghz of CPU would be enough for anything I would ever do, but maybe I was wrong?

If I export to m4v instead, will it still be possible to split the file by chapter? It sounds like a sensible move to make, if the 35 hours of content can still be automatically cut up.

I've run the ffmpeg inside OpenAudible and the one installed directly on my system, so there's probably no way around the problem as it is. ffmpeg must hold everything in memory before dumping the final output, then, which sounds ludicrous.

Thank you for the answer. Very kind.




________________________________

**Comment by ollybain** [comment]
> ollybain,
> 
> I have a huge library that I was able to download more than 3,000 books. Some of them are very long. I had success using OpenAudible to download and it is an amazing tool! Super awesome! I did have trouble with the volume of books and with size. I found some tricks to get things to work and for conversion I wrote a simple script It seemed to work better on large books. Let me know if you want me to share it.
> 
> Cheers,

Hi pcarrick!

That could be very useful. Yes, please!

O.

**Comment by openaudible** [comment]
4GB and 3.33 is fine. 
Just to be clear though... ffmpeg from the command line is slow. 
Can you run "top" and just verify that ffmpeg is what is taking up the resources?  Double check it isn't a remote file server?
I have tested some 80 hour books that are huge and haven't had any crashes or real slow-downs--so the whole book definitely doesn't need to fit in memory. 

Feel free to share any scripts, tips or suggestions. 

Try also converting to m4a.

**Comment by pcarrick** [comment]
The only reason I used the command line was because of the library size. I didn't have a harddrive that was big enough to handle the entire library all at once and OpenAudible would get stuck before finishing and then I had to restart from scratch. I finally tricked it into downloading all of them and then I just converted outside of OpenAudible. 

The script I used is below. I had to dig up a method of getting my activation key. Let me know if you can't find it with a quick search and I'll dig it up.

`ffmpeg -y -activation_bytes youractivationkey -i audiobook.aax -c:a copy -vn audiobook-tmp.m4a`

Let me know if you have any questions.

**Comment by pcarrick** [comment]
I did the quick search anyway. : )

https://github.com/inAudible-NG/audible-activator

**Comment by ollybain** [comment]
Hi!

HOW would I convert to m4a instead? It doesn't seem to be an active option?

And thank you kindly. It is very much appreciated. I'm not sure how I'm going to look at top while the system is crawling and unresponsive, but I'll do my best.

O.

________________________________

**Comment by openaudible** [comment]
@ollybain Converting to m4a is an option you can choose from the main OpenAudible preferences. It uses a lot less system resources. 

@pcarrick Yes, the activation bytes are also shown in the OpenAudible log console window along with the whole ffmpeg command line... which usually can be copied and pasted into the command prompt to test ffmpeg by itself.
