### ISSUE TITLE
Support .m4b format

### ISSUE THREAD

**Issue by esny23** [openaudible/openaudible#487]
I recently realized that you can rename the .m4a files as .m4b and in doing do you can get chapter data, and the files play very nicely with Apple's Books app. I wish the app natively could convert to .m4b, when I rename the files myself it shows up as not converted, so I have to create an m4b folder to manage and maintain my files. 

PS: I also realized that .m4a conversion is way faster than .mp3 and the audio quality is better, perhaps openaudible could have a wizard similar to Stanza, the epub converting app. A lot of the beneficial settings in OpenAudible are hidden in preferences, and there isn't a good explanation of what they do.

**Comment by openaudible** [comment]
What app are you wanting to play the m4b files with? 

Have you tried renaming a .m4a as .m4b ? The formats are very similar, but the .m4b has a length limitation. Maybe your book player can handle m4a renamed as m4b? 

Before we implement .m4b (which is a pain, due to the length maximum) I wanted to see if just calling it m4b would be enough for most or all players.

**Comment by esny23** [comment]
Like I said in my first comment, I'm renaming .m4a files to .m4b and everything works perfectly. I'm able to sync the .m4b files to my iPhone and use iOS's Book app just fine. I have dozens of lengthy files renamed .m4b and there is no issue. Renaming the files .m4b works for me, but the issue is when I rename the files .m4b, openaudible is no longer aware that those files have been converted and the icons go from green to orange.

**Comment by openaudible** [comment]
Got it. Its a good idea. Was trying to judge if there are any apps that will fail if an .m4a file is renamed .m4b.  Should be ok. Will add to a later version.

**Comment by openaudible** [comment]
M4B is now supported in the beta as described in #510 
Closing as this issue should be resolved when the beta is merged into the production release.
