### ISSUE TITLE
Purchased books appear in list as downloaded but not there

### ISSUE THREAD

**Issue by livtin** [openaudible/openaudible#488]
I have 3 books which were at one point in my Open Audible Library.  All of these books were paid for and are available on my audible app (Android).  When I do a library sync, they show as available to download (2 titles) and then the download fails.  The 3rd book shows as downloaded but us not on the drive.  I have trued to manually download the files using the download button but this does not work either

**Comment by openaudible** [comment]
You could try to make a backup and delete those books.. Then do a library sync. 
The download button should also work-- but might be giving some kind of error. Check the log for that... ?

**Comment by openaudible** [comment]
Only other thing I can recommend is log into Audible from the OpenAudible browser, go to your library, find the title, and make sure there is a download button next to it.. and click it. 

Good luck!
