### ISSUE TITLE
Library Sync only gets first page

### ISSUE THREAD

**Issue by subsquash** [openaudible/openaudible#489]
This looks like the same issue as some previous issues including #191 which may have come back.  I'm using version 2.3.5 on Windows 10.  When I first installed OpenAudible a couple months ago, it was able to download 20+ pages of books.  Now a quick or full sync only gets the first page.  It flips to the second page but does not get any of the books on it and times out after about a minute. From the log/console window, there's this:
```
Nov 23, 2020 11:04:46 PM org.openaudible.desktop.swt.manager.browser.GetPageTask getPage
INFO:  getPage:https://www.audible.com/library/titles?ref=a_library_t_c6_pageNext&pf_rd_p=SOMEKINDOFID&pf_rd_r=SOMEHASH&page=2 js=true
Nov 23, 2020 11:05:46 PM org.openaudible.desktop.swt.manager.browser.GetPageTask task
SEVERE: 0:getPage:https://www.audible.com/library/titles?ref=a_library_t_c6_pageNext&pf_rd_p=SOMEKINDOFID&pf_rd_r=SOMEHASH&page=2 error java.lang.Exception: Timeout waiting for page60498 ms
11:04:46.757	05:00:00.329	waitForPageLoad:start
11:04:47.282	05:00:00.854	browser state unknown -> loading
11:04:48.460	05:00:02.032	event:LocChanged -> LocationEvent{Browser {} time=0 data=null location=https://www.audible.com/library/titles?ref=a_library_t_c6_pageNext&pf_rd_p=SOMEKINDOFID&pf_rd_r=SOMEHASH&page=2 top=true doit=false}
11:04:48.641	05:00:02.213	browser state loading -> complete
11:05:46.926	05:01:00.498	Warning.. timeout waiting for page load
```
There's a long java exception regarding the Timeout after that.

**Comment by openaudible** [comment]
Do you have a firewall proxy like pi-hole? OpenAudible does not work well with some types of blocking systems (from user reports)

What if you manually go through the library pages?

I can add some debugging code.. but seems similar to #492

**Comment by subsquash** [comment]
No proxy or firewall. Manually going through the pages using the > button at the bottom of each page works fine.  I am noticing now that when I try to sync, when it loads the second page in the popup browser the green progress bar loads all the way across but doesn't go away indicating it's done loading.  When I manually go from page to page the green bar loads quickly and goes away immediately when done loading the page.
<img width="322" alt="Screenshot 2020-11-29 190633" src="https://user-images.githubusercontent.com/74949984/100561379-079a1400-3276-11eb-983f-c83c4a69eaa6.png">

**Comment by subsquash** [comment]
I deleted the books.json and the tmp folder, then did a full sync and it worked fine.
