### ISSUE TITLE
Automatic conversions

### ISSUE THREAD

**Issue by klarvu** [openaudible/openaudible#490]
(Version 2.3.5)
After downloading, the message "Automatic conversions are enabled. Start 1 conversion(s) now?" needs confirmation.
That is not very automatic in my opinion. Should be automatically started or manually triggered.

**Comment by openaudible** [comment]
I'll take a look. Thanks. (That was supposed to show up just once, or after changing the settings.. but could be broken.)

**Comment by openaudible** [comment]
Fixed in the next release.. also available to test in the https://openaudible.org/beta
