### ISSUE TITLE
FYI - Download Manager Deprecation

### ISSUE THREAD

**Issue by LanceMcCarthy** [openaudible/openaudible#494]
Just in case this affects any APIs that OpenAudible might be using:

![image](https://user-images.githubusercontent.com/3520532/100773138-78544400-33ce-11eb-9a25-f8fe2f246eb3.png)

although deeply buried in the FAQs, it appears the the download button is still an option to get the raw mp3 for your books, see https://help.audible.com/s/article/how-do-i-transfer-a-title-to-an-mp3-player-using-the-audiblesync-app?language=en_US

**Comment by openaudible** [comment]
I downloaded the sync app and couldn't get logged in. Will be monitoring the situation. Get your backups made sooner rather than later.

**Comment by timaster1** [comment]
I had the same issue, @openaudible , but they pushed version 1.8.5 and now I can log in.

**Comment by timaster1** [comment]
@LanceMcCarthy it appears that it does not download an MP3, but instead uses the DRM format and only syncs with a specific list of MP3 players (which probably preserve the DRM chain from Audible over to those three players), and probably plays that format without conversion.

**Comment by mcblum** [comment]
Does this mean the app will no longer work? That would be such a shame.

**Comment by openaudible** [comment]
It looks like we'll need to change some things once the download button goes away on the main audible web site. 

AudibleSync app downloads aax files to your computer here:  
C:\Users\NAME\AppData\Roaming\AudibleSync\downloads

These files can be drag and dropped into OpenAudible for normal backup/conversion. 

For linux users, we're not sure what will happen. Its possible we can mimic the same audible sync behavior.. but not sure!

**Comment by Geordon** [comment]
@openaudible do you have any idea if you will be able to work something out for Mac?  Or, is there any help that I can offer as a long-time Mac and *NIX user and system support person?

**Comment by openaudible** [comment]
@Geordon Whatever we come up with should work fine for all platforms. 

I'm looking for help figuring out the URL used by AudibleSync to bring up their app. 
Or how to run AudibleSync from Chrome or another js debugger (on Mac or PC). 
If we can run the AudibleSync from our internal web browser, that should let us get what we need to have a list of our books.

**Comment by LanceMcCarthy** [comment]
When clicking the Download button, the following requests are made:

1. Auth Url
`http://cds.audible.com:443`

2. Download Uri
`https://cds.audible.com/download?cust_id=REDACTED&asin=1774241730&codec=LC_64_22050_stereo&source=audible`

If you want the Fiddler .saz session, email me ( lance@dvlup.com ), I cant share it publicly... for obvious reasons :)


One potentially annoying thing is they're captcha-gating the sign in. 2 times they hit you with increasingly difficult captchas.

![image](https://user-images.githubusercontent.com/3520532/101100838-3d503d00-3595-11eb-9801-c202e08d0dd2.png)

**Comment by openaudible** [comment]
We are removing our web scraper method of getting books and switching to an API based library scanner. Should not be an issue, but of course, things can always change. Beta now available #510

**Comment by LanceMcCarthy** [comment]
Just following up here in case someone else ends up on it... the switch to using the API is such a nice improvement in UX.  It's so good, I have switched over my primary installation to the Beta channel.

Kudos!
