### ISSUE TITLE
Request: purge downloaded files after conversion

### ISSUE THREAD

**Issue by Geordon** [openaudible/openaudible#495]
Is there some way to have OA purge downloaded AAX files once they have been converted?  If not, can we please do that and maintain the list of books that have already been downloaded and converted?

As a side question, I'm seeing copies of the converted books in both 
OpenAudible/m4a

and
OpenAudible/web/m4a

So, at the moment, I have a total of three copies of the audiobooks downloaded.  Is there some way that this can be reduced?

**Comment by pcarrick** [comment]
Geordon,

I had a similar problem. I was able to "zero" out the file, using a command line script to remove all the content. It tricked Open Audible into thinking the file had been downloaded, but didn't continue to consume space. 

I hope that helps.

**Comment by Geordon** [comment]
> Geordon,
> 
> I had a similar problem. I was able to "zero" out the file, using a command line script to remove all the content. It tricked Open Audible into thinking the file had been downloaded, but didn't continue to consume space.
> 
> I hope that helps.

Interesting, thank you.  Mind if I ask what process you used to do that?  I have a couple fo ideas on what that could be, but I would like to see what you did as a known-good process. :D

**Comment by pcarrick** [comment]
> > Geordon,
> > I had a similar problem. I was able to "zero" out the file, using a command line script to remove all the content. It tricked Open Audible into thinking the file had been downloaded, but didn't continue to consume space.
> > I hope that helps.
> 
> Interesting, thank you. Mind if I ask what process you used to do that? I have a couple fo ideas on what that could be, but I would like to see what you did as a known-good process. :D

I can't find my script. Roughly outlining what I did was...
- check for existence of the converted file
-  if it existed then clear the original

I was using a linux computer, I simply used one of the many empty commands. I don't remember it causing problems so I'm assuming it was a simple work around.

some options:
https://www.cyberciti.biz/faq/remove-log-files-in-linux-unix-bsd/

I hope that helps.

**Comment by Geordon** [comment]
Excellent, thank you!  I'm currently using a Mac and am a long time command-line ranger, so Linux commands are simple enough.  Thanks!

**Comment by openaudible** [comment]
It's a good idea. I'll try to come up with a solution for a later version when I have time.

**Comment by openaudible** [comment]
Marking and closing as "feature request". 
Setting the file size to 0 is probably the easiest work around for now.
