### ISSUE TITLE
OpenAudible: Split by chapter -- mutiple titles?

### ISSUE THREAD

**Issue by sgp000** [openaudible/openaudible#496]
Help says "Select one or more books and select Action:Split by Chapter and set a destination directory."

I am able to select only one book at a time.

Running current version, Windows 10.

Any thoughts or suggestions?

Thanks

**Comment by openaudible** [comment]
This means to select two or more books in the OpenAudible library table. On Windows, select one book, then hold the Crtl key down and select one or more books. Then let go of CTRL and select Split Selected Book(s) from Action menu.

**Comment by sgp000** [comment]
That does not work.  Holding the ctrl key and selecting a 2nd books simply changes the selection from the 1st to the 2nd.
It does not facilitate both books being processed/split.

**Comment by openaudible** [comment]
The main Book Table in the application should allow multiple selections, even "Select All" for example (not recommended for splitting.) 

You can't select multiple books to split from the File Chooser under File Menu: Split By Chapter.

**Comment by sgp000** [comment]
I don't see "Book Table" in the application or in the browser.
In the application my choices are "file, Edit, Controls ..."
in the browser my choices are "Back, Stop, Refresh ..."

I'm sure I'm missing something obvious, and I appreciate your help

**Comment by subsquash** [comment]
Step 1: Click on a book
Step 2: Press and hold the Ctrl key at the bottom left of your physical keyboard
Step 3: Click on another book
Step 4: Release the Ctrl key on your physical keyboard
Step 5: Click on the Actions menu
Step 6: Select "Split Selected Books"
![image](https://user-images.githubusercontent.com/74949984/101227676-ef4f3e00-3655-11eb-8f83-07162c73863d.png)

**Comment by openaudible** [comment]
You need to download the book, and convert it to mp3 or m4a first.

**Comment by sgp000** [comment]
Of course. I have downloaded hundreds and converted them to mp3 using OA.
They reside the the mp3 subdirectory.

The only way I see to split is the method I described, and that allows only one at a time.

⁣- sgp

**Comment by subsquash** [comment]
If the instructions I provided with the screenshot above don't work, you can try converting to m4a instead, then rename the .m4a to .m4b and see if your player handles the encoded chapter information for the same effect?  That worked for me and I find it easier to work with the single file while still being able to seek by chapter.

**Comment by openaudible** [comment]
@sgp000 The screenshot you provided says 0 converted files (0 MP3 and 0 M4A.) 
You have to have m4a or mp3 files already created before you can split them.

**Comment by subsquash** [comment]
I provided the screenshot, I'm not the OP (sgp000).  Ignore the fact that I don't have books downloaded as I'm not personally trying to split anything.  I was trying to help sgp000 by showing where to click since they were confused.

**Comment by sgp000** [comment]
Thank you subsquash!! That worked well and your instructions were great!
