### ISSUE TITLE
change directory

### ISSUE THREAD

**Issue by ajcevu** [openaudible/openaudible#497]
I would like to move openaudible from my C drive to my D drive, but I can't work out how to do it. I have already downloaded some titles (onto the C drive) which is now totally full so i am unable to download more. Should I uninstall it and start again and hope there is something I missed before so that it can be installed on my D drive? I'm not very technologically savvy. I have a Windows 10 PC. 
Thanks

**Comment by ajcevu** [comment]
I uninstalled it from Drive C and reinstalled it to Drive D, but it keeps on trying to copy everything to my C Drive. I don't understand how to make it work! Please help someone :)

**Comment by adragor** [comment]
Go to Preferences on the Edit menu and set the various directories to be on the D drive.

**Comment by ajcevu** [comment]
Thanks - I was able to set the 3 directories to the D drive, but it still keeps going automatically to the C drive. There is another bit on the preferences page down the bottom that is Preferences and i can't change it at all. I can't double click on it like i did on the directories, and there is no set option like there is on the directories. Thanks

**Comment by openaudible** [comment]
We are adding a feature in the next release to allow you to change the application directory via environment variable (which is the C drive path you see.) Current version 2.3.5 doesn't allow you to change that--but it might work by quitting OA, moving the directory to the C drive, and using a shortcut to the new location. (Have not tested this!).
 
We're also working on other ways to make managing multiple libraries better. But its a big change and we're trying to get it right the first time.

**Comment by blurfl** [comment]
> We're also working on other ways to make managing multiple libraries better.

--This!-- I have two Audible accounts. Currently I use scripts and two versions of directories.json to switch between them (separate directory structures). I would love if OpenAudible could access both accounts to maintain one archive.

**Comment by JoshFink** [comment]
> > We're also working on other ways to make managing multiple libraries better.
> 
> --This!-- I have two Audible accounts. Currently I use scripts and two versions of directories.json to switch between them (separate directory structures). I would love if OpenAudible could access both accounts to maintain one archive.

@blurfl Could you elaborate on how you're working to make multiple accounts work. I have multiple accounts but haven't attempted it yet.

**Comment by blurfl** [comment]
@JoshFink, I always run OS using shell scripts for each account, and make use of the environment variable OPENAUDIBLE_HOME instead of swapping out the directories.json. The script sets the environment variable and opens OA. The environment variable only applies to the session started by the script. I've found it's useful to log out of Audible from the OA/Controls menu before quitting OA, to avoid cross-"contamination" (getting data from one account into the wrong account). For the same reason, in my setup running OA without the script aims OA at its default directory, which I keep empty.

```
#!/bin/sh
export OPENAUDIBLE_HOME="/Volumes/<disk holding account directoriers>/<directory for account>"
open --fresh /Applications/OpenAudible.app
```
