### ISSUE TITLE
What's the point of the demo on Linux?

### ISSUE THREAD

**Issue by VinceLewis** [openaudible/openaudible#499]
In the demo version - 

I downloaded and installed the .deb file. 
connected to audbile. 
synced.
downloaded a book.
There's no option to play it
and the option to convert it is greyed out.

Is that what's supposed to happen? What am I missing?

**Comment by openaudible** [comment]
The demo version shows you can import your list of books and download the encrypted AAX audio file. 
If you're satisfied that works and think that is worth the $, you can purchase the full version to unlock everything else including the most important feature of conversion to mp3 or m4a. Earlier copies of OpenAudible (and other utilities including ffmpeg) can convert the AAX files without having to pay.
 
OpenAudible is not a book player-- the "Play" option just opens the file in an external player.
