### ISSUE TITLE
audible authentication failing

### ISSUE THREAD

**Issue by rsrsps** [openaudible/openaudible#5]
As of today, the scraper is raising this exception: 

        String downloadCustId = getHidden("downloadCustId");
        String downloadUserId = getHidden("cust_id");
        if (downloadCustId == null || downloadUserId == null) {
            HTMLUtil.debugNode(page, "lib-no-cust");
            throw new IOException("Unable to determine required library variables in library:");
        }

I'm not quite sure what this is looking for in terms of the page content.

**Comment by openaudible** [comment]
Fixed for version 1.1, posted today. Audible updated their web formatting.
