### ISSUE TITLE
GUI and Scheduling closing unexpectedly

### ISSUE THREAD

**Issue by tomtom90** [openaudible/openaudible#50]
The GUI and schedule process (OpenAudible.exe) keeps closing after the very first convert process is done. win_ffmpeg and Hosts for console for other converting task keep running till they finish, but the files are not coppied to the mp3 target folder.
The GUI closes independetly from the converting process after exactly 10 min.

Host: Win 10 Pro 64 Bit
OpenAudible: 1.2.3

**Comment by openaudible** [comment]
There may be something crashing.. the convert stage has two steps--reading or writing a "keys.json" file.. and running ffmpeg. Not sure why either would crash the app. See if you can spot an error message in the console. I can add instructions on how to run the app from PowerShell so you can see the last errors reported.

**Comment by openaudible** [comment]
Try running from the command line:
Open Power Shell.

cd  "C:\Program Files\OpenAudible"
java -ea -cp * org.openaudible.desktop.Application

Copy and paste any errors that show when the app quits and re-open this issue if it happens with 1.2.5
