### ISSUE TITLE
Japanese audible site: no option to uncheck "check for audible download manager" in the account settings 

### ISSUE THREAD

**Issue by Portogoose** [openaudible/openaudible#500]
I have all red circles next to my Japanese audible library in openaudible.

In this case, is there a way I can I use my product still? The common fix for this problem is not possible on the Japanese audible website. Has anyone ever successfully used this in Japan, I wonder?

![image](https://user-images.githubusercontent.com/75664800/101456610-a9f18000-3977-11eb-8152-d6585de51509.png)

Thanks

**Comment by openaudible** [comment]
Unfortunately Japan and Italy don't have the Download option on their web site.
You could try using the new "AudibleSync" app, download the AAX files, and drag and drop into OpenAudible.
https://help.audible.com/s/article/what-is-the-audiblesync-app

Downloads are saved: %APPDATA%\Roaming\AudibleSync\downloads

We are working on an improved solution for Italy and Japan!
