### ISSUE TITLE
Only syncing 20 books

### ISSUE THREAD

**Issue by mshnryman** [openaudible/openaudible#502]
My issue is similar to #489 and #492 , but I have turned off my firewall and deleted tmp and books.json, and then I even uninstalled and deleted the program files and the folder in users/, but I always get the same issue.

Every time I do a sync, it gets the first page, then goes to the 2nd and leaves the count at 20. It doesn't give an error unless I try to do another sync before closing and reopening the program.

I can't seem to get past the first page and this program used to work for me...what's going on?

**Comment by steve5053872** [comment]
Same issue here.  I have deleted /tmp directory and books.json.

**Comment by dlake1234** [comment]
I am having the same issue. Tried on my main computer which has worked forever and then installed on a new computer and had the same issue. I have tried on my home network my work network as well as with and without a VPN.

**Comment by mshnryman** [comment]
> I am having the same issue. Tried on my main computer which has worked forever and it failed to get to the second page. Then installed on a new computer and had the same issue. I have tried on my home network my work network as well as with and without a VPN.

Yeah, same here. It used to work on this computer with the current version. I haven't updated it or really made many changes to my computer and now it doesn't work anymore.

**Comment by steve5053872** [comment]
Is there an estimate for when this issue will be assigned to someone to be worked on?

**Comment by valhalar** [comment]
they havent looked my entry on this issue. posted it a few days ago

**Comment by openaudible** [comment]
We're working on it. Have a new beta that we're testing internally that completely rewrites how we get book data. 
As soon as today, but possibly early next week if we find any big things in our initial tests. Will update you soon.

**Comment by mshnryman** [comment]
> We're working on it. Have a new beta that we're testing internally that completely rewrites how we get book data.
> As soon as today, but possibly early next week if we find any big things in our initial tests. Will update you soon.

Thank you, glad to hear you're looking into it!

**Comment by openaudible** [comment]
Feel free to try the beta as described in #510 
Closing as this issue should be resolved when the beta is merged into the production release.
