### ISSUE TITLE
Only syncing 20 books.  Same issue as numbers 191, 489, 492, and 502.

### ISSUE THREAD

**Issue by steve5053872** [openaudible/openaudible#503]
I have deleted the /tmp directory and books.json in c:\users\<user id>\openaudible.  I have also confirmed that OpenAudible.exe is set to "Allow" by Norton Security Suite > Settings > Firewall > Program Control.  I am running JRE Version 8 Update 261.  My version of OpenAudible is 2.3.5.

I have attached OpenAudible.zip which includes the files in C:\users\<user ID>\OpenAudible and the C:\users\<user ID>\OpenAudible\tmp and C:\users\<user ID>\OpenAudible\web directories.

Thanks in advance,
Steve

[OpenAudible.zip](https://github.com/openaudible/openaudible/files/5675601/OpenAudible.zip)

**Comment by openaudible** [comment]
Ok. Received report and zip. Working on a fix. Removed link to files. 
You may need to manually go through the library pages. It seems to be getting stuck on a tracking web url and the web page never reports as fully "complete".

**Comment by openaudible** [comment]
Closing as duplicate. Working on this today.

**Comment by steve5053872** [comment]
Thanks for the reply, I have tried having Page 2(and 3, 4…) open in the OA browser before I initiate Full Library Scan.  When initiated, page 1 is reopened.  No additional books are found. Regards,Steve From: openaudibleSent: Friday, December 11, 2020 10:08 AMTo: openaudible/openaudibleCc: steve5053872; AuthorSubject: Re: [openaudible/openaudible] Only syncing 20 books. Same issue as numbers 191, 489, 492, and 502. (#503) Ok. Received report and zip. Working on a fix. Removed link to files.You may need to manually go through the library pages. It seems to be getting stuck on a tracking web url and the web page never reports as fully "complete".—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by steve5053872** [comment]
Can we get a status update?  Thanks in advance.

**Comment by openaudible** [comment]
Working on a new version that will solve this.. but trying to get it tested. Will have a beta version within a week. Will post more details here.
Sorry for the trouble.
