### ISSUE TITLE
PiHole ad blocker causes two error windows for each item processed

### ISSUE THREAD

**Issue by bluebeeryale** [openaudible/openaudible#504]
There is a PiHole ad blocker on our network.  Consequently, I get two modal error windows  for yada yada doubleclick.net tracker "Page load failed with error: A server with the specified hostname could not be found."

**Comment by blurfl** [comment]
I see this as well. The Audible site doesn't seem to care that these links are blocked. Perhaps OpenAudible could ignore them, or log them but not put up the dialog?

**Comment by jdhorne** [comment]
Yep, happens for me as well. Would be thrilled if those errors were just ignored/logged. I've been temporarily disabling PiHole before syncing my collection as a workaround.

**Comment by bluebeeryale** [comment]
"Logging and ignoring" would be ideal since the privacy trackers don't really have any impact on functionality.  

@jdhorne, as an aside, I recently started messing around with HomeBridge (to HomeKit enable devices that don't specifically support the Apple protocol) which has a PiHole plugin.  From your iOS Device Control Center you can do a temporary pause on the PiHole to get around blocking when you need to permit a tracker.

**Comment by openaudible** [comment]
Feel free to try the beta as described in #510 
Closing as this issue should be resolved when the beta is merged into the production release.
