### ISSUE TITLE
Crashing in Big Sur

### ISSUE THREAD

**Issue by importantnotimportant** [openaudible/openaudible#505]
First time download -- I drag app to Applications, open, and it spins out -- there's actually no way to force quit so I keep having to restart the whole machine. Odd. 

M1 MBP on 11.0.1, OpenAudible 2.3.5. Would love any tips -- thanks!

**Comment by openaudible** [comment]
Maybe it doesn't like the unsigned executable? Have you tried right-clicking on the app and select "Open?"


There is a command line version you could try to get details about where it is crashing.. 

Open Terminal.app
```
cd /Applications/OpenAudible.app/Contents/Resources/app
./debug_mac.sh
```

**Comment by importantnotimportant** [comment]
Tried to run that in Terminal and it says Permission Denied

**Comment by importantnotimportant** [comment]
I appreciate the help -- would love to figure it out.

**Comment by importantnotimportant** [comment]
<img width="273" alt="Screen Shot 2020-12-19 at 2 19 21 PM" src="https://user-images.githubusercontent.com/66337498/102697618-349e6e80-4205-11eb-9cdb-356fe1fe1401.png">

**Comment by openaudible** [comment]
You need to change your GateKeeper settings in Settings to allow unsigned apps to run. Then right-click the application and select Open. After that, it should run normally.

**Comment by importantnotimportant** [comment]
Big Sur doesn't allow for issuing blanket permission for unsigned apps -- see screenshot. Usually opening one that's unsigned asks if I want to open it anyways, or it shows up in settings with the same prompt, but that's not happening with this app. The dialogue box here pops up, and then it freezes out the entire machine.

<img width="809" alt="Screen Shot 2020-12-20 at 11 50 56 AM" src="https://user-images.githubusercontent.com/66337498/102719630-0c724680-42bd-11eb-8321-cf007cb5883c.png">

**Comment by openaudible** [comment]
Haven't tried Big Sur yet, but it seems like people are discussing this new apple policy.

You could try: 
https://github.com/wynioux/macOS-GateKeeper-Helper

**Comment by openaudible** [comment]
Someone also reported Big Sur works, but requires two attempts to "Right-Click app and select Open". ? Not sure. Will try to get the new update and test. Thanks for the heads up.

**Comment by importantnotimportant** [comment]
I appreciate it! It’s weird one. Just can’t sort it.

**Comment by openaudible** [comment]
Can anyone comment on Big Sur's compatibility with OpenAudible? My mac is too old to run Big Sur. And the Apple stores are closed.

**Comment by blurfl** [comment]
I run OpenAudible on Mojave and Big Sur. It seems to work the same on both. Any specific questions or tests?

**Comment by openaudible** [comment]
Thanks @blurfl, I just need to document how to get past the Gatekeeper that prevents some users from launching OpenAudible on Macs. Usually just "Right-Click, select Open" and confirm running it. Will close for now and keep an eye on reports.

**Comment by blurfl** [comment]
The first time I "right-Click, select Open", this dialog opens:
![First right-click](https://user-images.githubusercontent.com/1851315/104111247-ad3c9c00-5294-11eb-80de-e41ec6d5a903.jpg)

Then the second "right-Click, select Open" brings this dialog:
![Second right-click](https://user-images.githubusercontent.com/1851315/104111254-cc3b2e00-5294-11eb-9467-c07bd45dcc35.jpg)

and having clicked 'Open' in that second dialog the app opens and is blessed to open normally in future.

**Comment by importantnotimportant** [comment]
Unfortunately I still can’t get past that first “cannot check it for malicious software” dialog before it crashes the computer again. I’ve never seen the second one. Again I’m on a new M1 MBP that’s up to date everywhere else software-wise. I’m mostly frustrated because this seems like such a great tool and I only need to run it once to grab all of my legacy Audible stuff before I move to Libro!

**Comment by openaudible** [comment]
I'm not sure what you mean by "crash". Can't open, I understand. Is Safari deleting the app or are you allowed to move it to the Applications folder?

Did you try running OpenAudible from Terminal that was suggested in the second reply?

**Comment by importantnotimportant** [comment]
I’ve tried it all. It’s in the Applications folder. I’ve tried running it from terminal.

And by crash, I mean, I right click, open, the first dialogue shows up, the pinwheel starts to spin, then freezes, and the computer is inoperable until I do a full restart.

**Comment by openaudible** [comment]
Hi @importantnotimportant ,

Thanks for the update. Spinning cursor is weird. Usually you should be able to Option + Command + Escape simultaneously to open the Force Quit menu. From there, you can select a program and click "Force Quit" to end it.

Does running from Terminal also create the spinning cursor? Anything logged in the terminal as the applications starts?
Do you have any (non-Apple) anti-malware or anti-virus software installed? Corporate software that might be interfering?

So far I think you're the only one reporting this out of many many downloads.

**Comment by blurfl** [comment]
Is the M1 Mac running OpenAudible in the Rosetta2 emulator?

**Comment by importantnotimportant** [comment]
Force quit doesn’t work, the whole machine is frozen and requires manual restart.

Terminal same effect.

No anti-virus software.

No corporate software.

And I’m not sure if it’s running in Rosetta2 or not — how do I check?

**Comment by blurfl** [comment]
I don't have an M1 machine to answer first-hand, but [this article](https://www.macrumors.com/how-to/install-rosetta-m1-apple-silicon-mac/) describes the process of setting Rosetta up. If you've already done the installation previously, that fact would be helpful for chasing a solution. If not,

**Comment by openaudible** [comment]
You probably found a bug in Apple's software. There really should be no way for a java program like OA to "hang" a Mac. 

You can send feedback to Apple: (But I've never had much luck!) 
https://osxdaily.com/2020/09/15/how-report-bugs-macos-big-sur-beta/

There are ways to debug an app (or at least tell what is "hanging" by using a bash command like "top" and report the "unresponsive" processes. Or open the "Force Quit" dialog, then run OpenAudible from Terminal.. and see what if anything shows as "not responding". 

I googled, and it looks like rosetta2 is an emulator that that works with the new M1 macs.

**Comment by blurfl** [comment]
Another bit of information that might help:

Click the OpenAudible  app’s icon in the Finder.
Click the File menu in the Finder and choose the option “Get Info”.
In the Get Info window, what is the state of the the checkbox next to “Open using Rosetta”?

**Comment by importantnotimportant** [comment]
Weirdly, don’t see that checkbox

**Comment by blurfl** [comment]
It may be that the checkbox isn't available for apps that only run in Intel mode. Have you tried the version 9 beta to see if that reacts differently? Available [here](https://openaudible.org/beta).

**Comment by importantnotimportant** [comment]
I’ll give it a shot! If it doesn’t work, I’ll just borrow my wife’s computer and try to run it. I really only need to do it once to grab all of my stuff before I decamp to Libro. Thanks for all the troubleshooting.

**Comment by blurfl** [comment]
Always good to have a backup plan 😁 I'm interested to hear whether the beta runs on the M1, though.
