### ISSUE TITLE
20 book sync issue

### ISSUE THREAD

**Issue by valhalar** [openaudible/openaudible#507]
the program is only seeing 20 books. I have way more. it only loads 20. attached are screenshots

Having looked at the other similar tickets I do not have a proxy or special firewall running.
![Screenshot 2020-12-14 21 09 35](https://user-images.githubusercontent.com/25445024/102166336-74ee9d00-3e51-11eb-9042-7248be5e0605.png)
![Screenshot 2020-12-14 21 11 02](https://user-images.githubusercontent.com/25445024/102166347-7e780500-3e51-11eb-987a-40f8ffeba84b.png)

**Comment by openaudible** [comment]
We are close to releasing a beta that uses a new method of getting book data. Will post an update soon.

**Comment by openaudible** [comment]
Feel free to try the beta as described in #510 
Closing as this issue should be resolved when the beta is merged into the production release.
