### ISSUE TITLE
Changing Information in the Data Card

### ISSUE THREAD

**Issue by 1234shai** [openaudible/openaudible#508]
Is there a way to change the information in our own databases that was downloaded from Audible?  

As an example of why I would want to do this, I see that Dostoevsky is spelled as well as Dostoyevsky in the information that was pulled from Audible and placed into the data card for the book.  

Or, sometimes the author is listed together with the translator - when all I want is the author.  

Due to this, when I export the list of books to excel, I cannot sort/filter accurately.   If I can change the information in my list, and just as important - have it "stick" when I update - , that could be useful as a feature.

**Comment by openaudible** [comment]
There is no way to do that currently.

I can envision allowing a user to change meta data.. but rescanning your library would typically fill in the data again... Which makes it a more complex problem.  Marking this as a feature request.. but I suspect we'll add a "tag editor" type feature first-- let you set meta data in the .mp3/.m4a that won't get overwritten.

The best solution might be to write some code in excel to "If field says xxx replace it yyy".
