### ISSUE TITLE
Cover Art Tag

### ISSUE THREAD

**Issue by tomtom90** [openaudible/openaudible#51]
The 'Cover Art Type' is 'other' (according to mp3tag), should be 'front cover' or so.
This would enable the file to show the cover art in windows by default.

**Comment by openaudible** [comment]
We use ffmpeg to convert the aax file to mp3. Tags are handled by ffmpeg. The command line we use to convert the book is displayed in the console. If you can recommend a change to the ffmpeg command, we can incorporate that into the next version.

**Comment by tomtom90** [comment]
Hey, thanks for your response.
I'm not to familiar with the ffmpeg parameters. As to what I found so far:
the idtag Version should be specified as
-id3v2_version <n>

Im not sure as how to set it, yet there should be a 'comment="Cover (front)"' for the "Album Art" Tag.

The example I found at stackoverflow:
ffmpeg -i in.mp3 -i test.png -map 0:0 -map 1:0 -c copy -id3v2_version 3 -metadata:s:v title="Album cover" -metadata:s:v comment="Cover (front) out.mp3

I hope it helps a little.
Best regards
Thomas

**Comment by openaudible** [comment]
I checked and album art does not show in windows 7 file explorer, but shows up in windows 10. MP3 tag version is 3.2.4  (not 3).  You can submit a bug report to microsoft. Haha. 

If you want to keep exploring, you can run the above ffmpeg command using a link to one of your books and the link to the artwork and see if it works. Been meaning to add some additional meta data into the mp3.

**Comment by openaudible** [comment]
OK. Fixed for next release. It is nice that they books show up with the correct artwork in Win 7.
