### ISSUE TITLE
OpenAudible Beta

### ISSUE THREAD

**Issue by openaudible** [openaudible/openaudible#510]
A beta (pre-release) version of OpenAudible is available at https://openaudible.org/beta 

it uses the audible API to access your library (emulating an iPhone.). 

It should be faster, more accurate, and more detailed than the previous method of scraping audible desktop web pages. 

It should address many of the open issues. That includes people only getting 20 books, missing date purchased, etc. 

We added support for .m4b extension. These are simply m4a files renamed to m4b so there is no max size limit. Let us know if any m4b players have trouble playing the m4b files. (We may discontinue .m4a format.) 

We also updated the set UI library we use. 

Looking forward to any feedback, especially from non-US audible users. 

Will post updates to the beta as needed. 

Known issues: 
* Quick Rescan not working-- fixed in next release.

**Comment by blurfl** [comment]
Great stuff! The beta deals with the PiHole issue and syncs my whole book list. 

I have two accounts, though. One, an Amazon account uses an email address. This works properly with the beta. The other, an older Audible account, uses a username. That one won't log in. The beta doesn't seem to offer a way to choose between the two sign-in methods. The release version shows a link near the bottom of the window to choose the alternate option. 

Have I missed a setting somewhere?

**Comment by zac9** [comment]
I was affected by the 1 page / 20 book problem. The beta discovered the full library 233 and is working on download now. US server selected. 
Thank you.

**Comment by blurfl** [comment]
Running beta1 alerted me to the beta2 available (very nice), but the link in the 'Ok' button takes one to the release downloads instead of the beta...

**Comment by openaudible** [comment]
Oops. Will fix. Just go to the beta page, same link above.

**Comment by mattdsteele** [comment]
Just gave this a shot (Windows). It's working great for me, including handling 2FA and a captcha challenge. Great work! I would never have guessed there was an actual API you could use! 💪

**Comment by blurfl** [comment]
Notes using Beta3 

I'm not sure what is addressed in this beta, I've found MacOS Big Sur seems happy with it (have to do the right-click and 'Open' trick two times to bless a new version of the app and launch it) and the environment variable $OPENAUDIBLE_HOME works to save onto remote volumes (so long as they're already mounted), so I poked at signing in with multiple accounts. I guess that is farther down the todo list. Here are some observations, though:

- 'Controls/Connect to Audible' only allows use of PublicSignin with email, though the menu 'Controls/Connect' still provides a way to use PrivateSignin with an Audible username. 
- 'Controls/Browser' menu triggers PiHole as in issue #504 regardless of which signin method was used
- If OpenAudible was exited while signed in to either account, that account's first Library page is displayed the next time the app is run and connected, regardless of which account was used to sign in this time. Only using the 'sign out' menu choice on Audible's web page corrects this.

**Comment by openaudible** [comment]
3rd beta fixed a bug where you couldn’t change your library directory. 


I’m not sure why the user name can’t be used. There is suppose to be a log in with username link. Will dig into that. 

For pihole, what page is hanging? View book in web? Do you get an error message or get stuck so that you can’t access features? I may get rid of the internal browser all together (except for logging in). Only reason it was there was to scrape the library pages and intercept the download clicks. So just open urls in user’s default browser. 

Will log out of web browser when logging out. Have some thoughts on better supporting more than one account. 

Thanks for the feedback! 

Still hoping to find feedback from international users.

**Comment by stub99** [comment]
2FA works for me. However it seems the country selection has no effect. I see no content when logging into audible.ca. I have no content on Audible US.

**Comment by LanceMcCarthy** [comment]
## Webpage Generation Issue (observed in beta 3 and beta 4)

It seems like the web page is not being updated/generated. I had one new addition to my library, but it is not in the web page's output.

Here is my order of operations that led to this current state

1. I had the latest prod release installed with working webpage settings
2. I updated to Beta 3 (2.4.0.3beta) a couple days ago
3. I synced my library and there was 1 new title (a good test result)

However, I noticed my webpage never got the new title. I double checked by directly looking in the website's mp3 folder and confirmed that the new mp3 was never copied over and the webpage was not regenerated

Here's a screenshot ( @openaudible I can give you my webpage URL if you email me directly lance[at]dvlup[.]com):

![image](https://user-images.githubusercontent.com/3520532/103301381-4c2ce280-49cf-11eb-985c-cc457a1e30eb.png)

**Comment by cwapenhans** [comment]
Hello, I'm from Germany and i use audible.de. I tested the beta, because i didn't get all books. With the beta it's mostly fine. But i missed some books: they are from a magazine

![2021-01-01 22_41_44-Window](https://user-images.githubusercontent.com/47783596/103446714-144dc580-4c83-11eb-99e2-2c9c8e7fd33b.png)
![2021-01-01 22_44_24-Window](https://user-images.githubusercontent.com/47783596/103446715-14e65c00-4c83-11eb-90ab-df7a86bc41ab.png)

**Comment by openaudible** [comment]
Thanks for the report @cwapenhans . Especially nice to get from Germany. We don't currently support magazines, podcasts, Romance series, and many other free books. Only books that you purchase. Only books that have a "download" option next to them in your library.

**Comment by openaudible** [comment]
@LanceMcCarthy Thanks for the detailed report. No idea why it would skip books when generating the web page, but haven't spent much time testing that code-- it shouldn't have changed much. You could open the console window (CTRL-E), but a web page, and see if the name of the book pops up with an error message. Will try to test on my end.

**Comment by cwapenhans** [comment]
> Thanks for the report @cwapenhans . Especially nice to get from Germany. We don't currently support magazines, podcasts, Romance series, and many other free books. Only books that you purchase. Only books that have a "download" option next to them in your library.

This is very disappointing. It looks nearly the same for the magazines. they are a subpage und the format ist then the same.

{
 "summary": "Offen fÃ¼r die Zukunft beschreibt brand eins die Signale des Wandels, beleuchtet HintergrÃ¼nde und erÃ¶ffnet neue Sichtweisen...",
 "rating_average": "4.258064516129032",
 "author": "brand eins",
 "image_url": "https://m.media-amazon.com/images/I/31BN3qBFusL._SL500_.jpg",
 "abridged": "true",
 "language": "german",
 "title": "brand eins audio",
 "title_short": "brand eins audio",
 "info_link": "https://www.audible.de/pd/B004VLUINI",
 "rating_count": "31",
 "filename": "brand eins audio",
 "release_date": "2200-01-01",
 "product_id": "PE_BRND_000001DE",
 "genre": "Wirtschaft & Karriere",
 "publisher": "brand eins Medien AG",
 "files": [],
 "asin": "B004VLUINI",
 "purchase_date": "2020-12-18",
 "api_details": {
....

**Comment by riddledaxis** [comment]
Hi, I am from the UK and had the issue where only 20 books were downloaded, so I installed version 2.4.0.4beta as recommended for the 20 book issue.

My account has 69 books, of which 3 would be classed as links as they have several episodes inside them.

When I run either a full or quick sync of my library, the taskbar scrolls quickly, but is does show "Getting Page 1" "Loaded 20 books" and then ends up on "Your library appears up to date!..."

![sync 1](https://user-images.githubusercontent.com/47009467/103462350-950cd000-4d1c-11eb-98d9-04343fb49ae5.png)

The console shows very limited info for the scans
```
Jan 02, 2021 4:55:20 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Refresh_Files
Jan 02, 2021 4:55:23 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Rescan_Library
Jan 02, 2021 4:55:23 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 27524 to disk:C:\Users\pj73\OpenAudible\tmp\saved_books.json
Jan 02, 2021 4:55:23 PM org.openaudible.Audible save
INFO: Save books took 26 ms. to complete.
```
Also, the purchase date for all the books is 2021-01-01, which is when I ran the first sync of my library.

I have also filed a bug report for this issue

Any help you can give would be gratefully appreciated

**Comment by riddledaxis** [comment]
I updated today to 2.4.0.5beta and it now sees my 69 books, but when the app fails to download the remaining books.
![books](https://user-images.githubusercontent.com/47009467/103487591-84cd2180-4dfe-11eb-8c57-73235a55bdd6.png)

The console shows
```
Jan 03, 2021 7:49:14 PM org.openaudible.desktop.swt.manager.AudibleGUI _checkAutomation
INFO: Start auto download:0
Jan 03, 2021 7:49:14 PM org.openaudible.desktop.swt.manager.AudibleGUI downloadAAX
WARNING: Warning, 47 books had errors and were skipped
Jan 03, 2021 7:49:14 PM org.openaudible.desktop.swt.manager.AudibleGUI downloadAAX
INFO: Added 0 of 47
```
Not sure what it means by errors, as you can listen to the books through the Audible app?

**Comment by openaudible** [comment]
Hi @riddledaxis .. (or anyone having problems)... 
I would try the following: Quit and restart OA. Check for latest version (in About menu, or wait 15.)
Control Menu: Full Library Scan.  Select ~5 books for downloading and right-click, Download. These should be purchased books-- not podcasts, magazines, or free/all you can listen to books. If you still get these errors, send a bug report from the About menu. Thanks!

**Comment by riddledaxis** [comment]
Hi @openaudible 

Followed your advice and tried to download 3 of the books that won't download (the majority if not all of my library are purchased books) and kept getting this error "No Library Record Found for user. for ..." each book I tried to download.

The console output is 
```
Jan 04, 2021 12:06:13 PM org.openaudible.Audible save
INFO: Save books took 149 ms. to complete.
Jan 04, 2021 12:06:13 PM org.openaudible.desktop.swt.manager.AudibleGUI downloadAndConvertWithDialog
INFO: You have 47 book(s) to download.
 autoConvert=true
Jan 04, 2021 12:06:29 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Download
Jan 04, 2021 12:06:29 PM org.openaudible.desktop.swt.manager.AudibleGUI downloadAAX
INFO: Added 3 of 3
Jan 04, 2021 12:06:29 PM org.openaudible.util.queues.ThreadedQueue run
INFO: Starting job Download Aggressor In progress:2 queue: 1 threads:
Jan 04, 2021 12:06:29 PM org.openaudible.util.queues.ThreadedQueue run
INFO: Starting job Download 1984 In progress:2 queue: 1 threads:
Jan 04, 2021 12:06:29 PM org.openaudible.Audible jobStarted
INFO: DownloadQueue started:1984 size:1
Jan 04, 2021 12:06:29 PM org.openaudible.Audible jobStarted
INFO: DownloadQueue started:Aggressor size:1
Jan 04, 2021 12:06:29 PM org.openaudible.download.DownloadJob download
INFO: Downloading book: Aggressor url=https://cds.audible.com/download?asin=B00P9TGRBS&cust_id=lSSX_o9ETcIu0QnKAwQu8oICyBwVPHXZA9Q2i2us-jv3hLX9xyKQTFGvVC6xiQ&codec=LC_64_22050_stereo&source=audible_iPhone&type=AUDI
Jan 04, 2021 12:06:29 PM org.openaudible.download.DownloadJob download
INFO: Downloading book: 1984 url=https://cds.audible.com/download?asin=B016E6KWA6&cust_id=kTN4m81K704GNN9PI62ngX6lTin0HEDnq5uDTg-D0KTo4yS4kTHwCKMa7382Qg&codec=LC_64_22050_stereo&source=audible_iPhone&type=AUDI
Jan 04, 2021 12:06:29 PM org.openaudible.download.DownloadJob helperBodyToURL
SEVERE: helperToURL: No Library Record Found for user.
Jan 04, 2021 12:06:29 PM org.openaudible.download.DownloadJob handleError
SEVERE: Error downloading book:Aggressor
url=https://cds.audible.com/download?asin=B00P9TGRBS&cust_id=lSSX_o9ETcIu0QnKAwQu8oICyBwVPHXZA9Q2i2us-jv3hLX9xyKQTFGvVC6xiQ&codec=LC_64_22050_stereo&source=audible_iPhone&type=AUDI
dl=https://cds.audible.com/download?asin=B00P9TGRBS&cust_id=lSSX_o9ETcIu0QnKAwQu8oICyBwVPHXZA9Q2i2us-jv3hLX9xyKQTFGvVC6xiQ&codec=LC_64_22050_stereo&source=audible_iPhone&type=AUDI
err=Download error:No Library Record Found for user. for Aggressor
dl_body=No Library Record Found for user.
dl_body error:java.io.IOException: Expected assemble_url
Jan 04, 2021 12:06:29 PM org.openaudible.download.DownloadJob download
INFO: Download failed:C:\Users\pj73\Music\Audible books\aax\Aggressor.AAX Aggressor
Jan 04, 2021 12:06:29 PM org.openaudible.util.queues.ThreadedQueue jobError
INFO: DownloadQueue error processing Download Aggressor
java.io.IOException: Download error:No Library Record Found for user. for Aggressor
	at org.openaudible.download.DownloadJob.handleError(DownloadJob.java:116)
	at org.openaudible.download.DownloadJob.download(DownloadJob.java:227)
	at org.openaudible.download.DownloadJob.downloadNew(DownloadJob.java:327)
	at org.openaudible.download.DownloadJob.processJob(DownloadJob.java:334)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:425)

Jan 04, 2021 12:06:29 PM org.openaudible.Audible jobCompleted
INFO: DownloadQueue completed:Aggressor remaining queue size:1
Jan 04, 2021 12:06:29 PM org.openaudible.download.DownloadJob helperBodyToURL
SEVERE: helperToURL: No Library Record Found for user.
Jan 04, 2021 12:06:29 PM org.openaudible.download.DownloadJob handleError
SEVERE: Error downloading book:1984
url=https://cds.audible.com/download?asin=B016E6KWA6&cust_id=kTN4m81K704GNN9PI62ngX6lTin0HEDnq5uDTg-D0KTo4yS4kTHwCKMa7382Qg&codec=LC_64_22050_stereo&source=audible_iPhone&type=AUDI
dl=https://cds.audible.com/download?asin=B016E6KWA6&cust_id=kTN4m81K704GNN9PI62ngX6lTin0HEDnq5uDTg-D0KTo4yS4kTHwCKMa7382Qg&codec=LC_64_22050_stereo&source=audible_iPhone&type=AUDI
err=Download error:No Library Record Found for user. for 1984
dl_body=No Library Record Found for user.
dl_body error:java.io.IOException: Expected assemble_url
Jan 04, 2021 12:06:29 PM org.openaudible.download.DownloadJob download
INFO: Download failed:C:\Users\pj73\Music\Audible books\aax\1984.AAX 1984
Jan 04, 2021 12:06:29 PM org.openaudible.util.queues.ThreadedQueue jobError
INFO: DownloadQueue error processing Download 1984
java.io.IOException: Download error:No Library Record Found for user. for 1984
	at org.openaudible.download.DownloadJob.handleError(DownloadJob.java:116)
	at org.openaudible.download.DownloadJob.download(DownloadJob.java:227)
	at org.openaudible.download.DownloadJob.downloadNew(DownloadJob.java:327)
	at org.openaudible.download.DownloadJob.processJob(DownloadJob.java:334)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:425)

Jan 04, 2021 12:06:29 PM org.openaudible.Audible jobCompleted
INFO: DownloadQueue completed:1984 remaining queue size:1
Jan 04, 2021 12:06:29 PM org.openaudible.util.queues.ThreadedQueue run
INFO: Starting job Download Awful Auntie In progress:2 queue: 0 threads:
Jan 04, 2021 12:06:29 PM org.openaudible.Audible jobStarted
INFO: DownloadQueue started:Awful Auntie size:0
Jan 04, 2021 12:06:29 PM org.openaudible.download.DownloadJob download
INFO: Downloading book: Awful Auntie url=https://cds.audible.com/download?asin=B00NO492IK&cust_id=hm737UvXIGW8dUhysQbirJjnYId0zVLcntetwchiUW4hzRZ1t-ME4N4vnfx08Q&codec=LC_64_22050_stereo&source=audible_iPhone&type=AUDI
Jan 04, 2021 12:06:30 PM org.openaudible.download.DownloadJob helperBodyToURL
SEVERE: helperToURL: No Library Record Found for user.
Jan 04, 2021 12:06:30 PM org.openaudible.download.DownloadJob handleError
SEVERE: Error downloading book:Awful Auntie
url=https://cds.audible.com/download?asin=B00NO492IK&cust_id=hm737UvXIGW8dUhysQbirJjnYId0zVLcntetwchiUW4hzRZ1t-ME4N4vnfx08Q&codec=LC_64_22050_stereo&source=audible_iPhone&type=AUDI
dl=https://cds.audible.com/download?asin=B00NO492IK&cust_id=hm737UvXIGW8dUhysQbirJjnYId0zVLcntetwchiUW4hzRZ1t-ME4N4vnfx08Q&codec=LC_64_22050_stereo&source=audible_iPhone&type=AUDI
err=Download error:No Library Record Found for user. for Awful Auntie
dl_body=No Library Record Found for user.
dl_body error:java.io.IOException: Expected assemble_url
Jan 04, 2021 12:06:30 PM org.openaudible.download.DownloadJob download
INFO: Download failed:C:\Users\pj73\Music\Audible books\aax\Awful Auntie.AAX Awful Auntie
Jan 04, 2021 12:06:30 PM org.openaudible.util.queues.ThreadedQueue jobError
INFO: DownloadQueue error processing Download Awful Auntie
java.io.IOException: Download error:No Library Record Found for user. for Awful Auntie
	at org.openaudible.download.DownloadJob.handleError(DownloadJob.java:116)
	at org.openaudible.download.DownloadJob.download(DownloadJob.java:227)
	at org.openaudible.download.DownloadJob.downloadNew(DownloadJob.java:327)
	at org.openaudible.download.DownloadJob.processJob(DownloadJob.java:334)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:425)

Jan 04, 2021 12:06:30 PM org.openaudible.Audible jobCompleted
INFO: DownloadQueue completed:Awful Auntie remaining queue size:0
```
I have submitted a bug report as requested

**Comment by blurfl** [comment]
The MacOS version of OAbeta8 doesn't run when opened (Big Sur 11.2, Intel), it just bounces in the dock. It seems to be incomplete - the directory "OpenAudible-beta8.app/Contents/Resources/app/" contains only

```
.install4j
debug_mac.sh
openaudible-jar-with-dependencies.jar

```

The beta7 version of that directory has two additional subdirectories and a .jar file. 

```
.install4j
debug_mac.sh
openaudible-jar-with-dependencies.jar
bin
org.eclipse.swt.cocoa.macosx.x86_64.jar
webapp

```

FWIW, OSbeta8 does fully open when those items are copied from beta7, but I haven't taken it any further.

**Comment by ajw107** [comment]
I can confirm that beta 8 is incomplete on Windows as well.  I get the following error on startup:
![image](https://user-images.githubusercontent.com/2067004/104737850-b3bb8f80-573c-11eb-8af8-7bf6171487b9.png)

**Comment by openaudible** [comment]
Shoot, we broke the build system yesterday.  Turned off beta until we create, TEST, and post a new #9.

**Comment by Eilongi** [comment]
![image](https://user-images.githubusercontent.com/77516552/104788788-cadd9a00-579b-11eb-86a7-cc71e7d4166f.png)

Quick Library Sync doesn't work for me for quite some time. This one is fresh from 2.4.0.9. 
Full Library Sync works.

**Comment by openaudible** [comment]
@Eilongi That is a great bug find. Looks like we missed an & before "purchased_after".  Thank you.

**Comment by Eilongi** [comment]
> @Eilongi That is a great bug find. Looks like we didn't convert the "+" in "purchased_after". Glad you had a +2 GMT timezone. Thank you.
> 
> Also, I just uploaded a new copy of beta 9 that has your fix added. Give it a try.

Works great. Thank you.

**Comment by Eilongi** [comment]
"Split By Chapter" should show MP3/M4A/M4B yet it only shows MP3/M4A I've checked a couple of times while renaming the extension. M4A is there M4B not, renaming again and once again the file is there to choose from.

**Comment by openaudible** [comment]
@Eilongi Good catch. Will add that in. And thanks for the feedback on the quick scan.

**Comment by openaudible** [comment]
Fixed that @Eilongi in latest beta https://openaudible.org/beta

**Comment by Xan-Kun** [comment]
2.4.1.5beta
Using the new m4b format, when opening it in VLC, it shows an additional subtitle track. Although that would be a nice feature to have, I am not sure it is intended behaviour :-)

Thanks for the software!

**Comment by Strider3000** [comment]
2.4.1.5beta:
Neither full synch or quick synch find new titles in my audible library.

**Comment by openaudible** [comment]
@Strider3000 Do you get an error message? Maybe check the log messages File Console. 
Do you have multiple accounts (maybe signed into a different one) Are the books ones you've purchased (not free or podcast) 

@xan-kun I don't see anything about subtitles. What do the subtitles contain? (Text, nothing?)

**Comment by Strider3000** [comment]
@openaudible I get the "Up to Date!" message.

Console log for quick synch:

Feb 05, 2021 1:02:53 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Quick_Refresh
Feb 05, 2021 1:02:54 PM org.openaudible.util.BugReport sendBetaMetric
INFO: Bug report received: {"success": true}
Feb 05, 2021 1:02:54 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 372339 to disk:C:\Users\Colin\OpenAudible\tmp\saved_books.json
Feb 05, 2021 1:02:54 PM org.openaudible.Audible save
INFO: Save books took 28 ms. to complete.

Console log from full synch:

Feb 05, 2021 1:03:17 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Rescan_Library
Feb 05, 2021 1:03:18 PM org.openaudible.convert.BookMerge mergeItem
INFO: Update meta rating_average: 4.839584535487594 from 4.839522801616317
Feb 05, 2021 1:03:18 PM org.openaudible.convert.BookMerge mergeItem
INFO: Update meta rating_count: 5199 from 5197
Feb 05, 2021 1:03:18 PM org.openaudible.util.BugReport sendBetaMetric
INFO: Bug report received: {"success": true}
Feb 05, 2021 1:03:18 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 372339 to disk:C:\Users\Colin\OpenAudible\tmp\saved_books.json
Feb 05, 2021 1:03:18 PM org.openaudible.Audible save
INFO: Save books took 51 ms. to complete.

I have used multiple accounts in the past. I'm currently logged in via my primary account. System is Windows 10 x64. The books are ones that I have purchase, but the list in my Audible online library also include at least one book that is free.

**Comment by openaudible** [comment]
@Strider3000 Thank you. Ok. I guess our logging isn't that good. We should have shown how many books were processed etc. 

Free books will not be shown. If you bought a book, and you log in with the open audible browser, there may be a download link next to the book in your library. Click Download should add the book to your OA library.. but strange if it isn't showing in the full library sync.

**Comment by Xan-Kun** [comment]
@openaudible That's what i looks like in VLC
![Subtitles](https://user-images.githubusercontent.com/11686614/107271953-448c3f00-6a4d-11eb-9733-3dde38923931.png)

**Comment by openaudible** [comment]
Thank you everyone for your feedback and support. 3.0 is out!

**Comment by LanceMcCarthy** [comment]
Congrats!
