### ISSUE TITLE
OpenAudibleBeta Version 2.4.0.2 (Working Folder)

### ISSUE THREAD

**Issue by wartbump** [openaudible/openaudible#511]
Hello, I have the Beta installed in MacOS BigSur and Catalina. Both have fairly small M.2 HDDs so I would like to have the downloads go to an external HDD. I point the Folders in preferenses to this Ext.HDD but it still ends up downloading to "/Users/llysowain/Library/OpenAudible/aax".
Any help would be appreciated.
Thank You

**Comment by openaudible** [comment]
OK, hopefully fixed in the latest beta. Thank you for the report!
Re-open if not working. You'll probably have to set your directory to the new "Library" preference, which should contain your MP3/AAX/M4A directories.
