### ISSUE TITLE
The output web page

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#513]
It would be especially useful for those with very large libraries to make the top line of the generated web page ( with the Search box and the Image on check mark) stay fixed at the top of the scrolling page of books in all modes.  This saves going up and down a page of several hundred pages to retype a search criteria.

I am sure that most tech competent folks could do this in a heartbeat, but us old folks .......

Thanks

**Comment by LanceMcCarthy** [comment]
^ Aka Sticky Header

**Comment by openaudible** [comment]
OK. I tried to do it and failed. If anyone is a bootstrap 3 person, I'd accept any help.
The index.html file is created the first time, and if it is modified, it shouldn't get overwritten.. so the idea is you can modify the html and not have the changes lost each time you add books.

**Comment by LanceMcCarthy** [comment]
1. Go to my demo https://dojo.telerik.com/@Lance/EquGEKuc 
2. Click the blue "run" button to execute the code
3. Scroll the content to see the div get overlaid on top of the 

Here's the relevant code:

```html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
<!-- redacted section for clarity, see full example -->
  </head>
  <style>
    body {
      font-size: 29px;
    }
    .content {
      padding: 12px;
    }
    .stickyHeader {
      position: fixed;
      width: 100%;
    }
  </style>
  
  <body>
    <div id="navbar">
      <div class="col-md-3">
        <div class="input-group">
          <div class="input-group-btn">
            <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i>
            </button>
          </div>
          <input type="text" class="form-control" placeholder="Search" name="srch-term" id="filter">
        </div>
      </div>
      <div class="col-md-2">
        <div class="form-group">
          <label><input type="checkbox" name="checkbox" id="show_images">Show Images</label>
        </div>
      </div>

      <div class="col-md-2 align-text-bottom text-center">
        <strong><a href="http://openaudible.org">OpenAudible</a></strong>
      </div>
    </div>

<!-- redacted section for clarity, see full example -->
    </div>

  <script>
    var navbar = document.getElementById("navbar");

    var stickyHeader = navbar.offsetTop;

    window.onscroll = function() {
      if (window.pageYOffset >= stickyHeader) {
        navbar.classList.add("stickyHeader")
      } else {
        navbar.classList.remove("stickyHeader");
      }
    };
  </script>
  </body>
</html>
```

The key takeaways are the `navbar` id, the `.stickyheader` class and the `window.onscroll` event handler.

**Comment by LanceMcCarthy** [comment]
I have this working 99%: Visit my real site https://audible.dvlup.com/ (I disabled mp3 downloads to prevent redistribution)

The last remaining step is to add a top margin to the tables style. Below is the complete code

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- Generated by openaudible.org -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet"  href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/bootstrap-table.min.css">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.6/js/bootstrap.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-table/1.10.1/bootstrap-table.min.js"></script>
  <link rel="apple-touch-icon" sizes="180x180" href="/assets/icons/180x180.png">
  <link rel="icon" type="image/png" sizes="32x32" href="/assets/icons/32x32.png">
  <link rel="icon" type="image/png" sizes="16x16" href="/assets/icons/16x16.png">

  <link rel="stylesheet" type="text/css" href="assets/books.css">
  <script src="assets/openaudible.js" type="text/javascript"></script>
  <script src="books.js" type="text/javascript"></script>
  <!-- Created by OpenAudible export web page. -->
  <title>OpenAudible</title>
</head>

<style>
  .stickyHeader {
    position: fixed;
    width: 100%;
  }

  .table-padding{
    margin-top: 40px;
  }

  .search-bar {
    padding-top: 12px;
    z-index: 100;
    background-color: rgb(194, 194, 194);
  }
</style>

<body>
<div id="container">
  <!-- search filter row -->
  <div id="navbar" class="search-bar"> 
    <div class="col-md-3">
      <div class="input-group">
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit"><i class="glyphicon glyphicon-search"></i>
          </button>
        </div>
        <input type="text" class="form-control" placeholder="Search" name="srch-term" id="filter">
      </div>
    </div>
    <div class="col-md-2">
      <div class="form-group">
        <label><input type="checkbox" name="checkbox" id="show_images">Show Images</label>
      </div>
    </div>
    <div class="col-md-2 align-text-bottom text-center">
      <strong><a href="http://openaudible.org">OpenAudible</a></strong>
    </div>
  </div>

<!-- Table row -->
  <div class="row" class="book_table table-padding" id="compact_view"> 
    <div class="col-md-12">
      <table id="compact_table" class="table table-striped">
        <thead>
        <tr>
          <th data-field="title" data-sortable="true">Title</th>
          <th data-field="author" data-sortable="true">Author</th>
          <th data-field="narrated_by" data-sortable="true">Narrator</th>
          <th data-field="duration" data-sortable="true">Duration</th>
          <th data-field="release_date" data-sortable="true">Released</th>
          <th data-field="purchase_date" data-sortable="true">Purchased</th>
          <th data-field="description" data-sortable="true">Description</th>
        </tr>
        </thead>
        <tbody class="searchable">  <!-- Filled in using json. -->
        </tbody>
      </table>
    </div>
  </div>

  <div class="row" class="book_table  table-padding" id="image_view"> <!-- Table row -->
    <div class="col-md-12">
      <table id="image_table" class="table table-striped">
        <thead>
        <tr>
          <th data-field="image" data-sortable="true">Title</th>
          <th data-field="info" data-sortable="true">Info</th>
          <th data-field="release_date" data-sortable="true">Released</th>
          <th data-field="purchase_date" data-sortable="true">Purchased</th>
          <th data-field="summary" data-sortable="false">Summary</th>
        </tr>
        </thead>
        <tbody class="searchable">  <!-- Body of table filled in using populateBooks . -->
        </tbody>
      </table>
    </div>
  </div>

  <div id="detail_modal" class="modal fade" tabindex="-1" role="dialog"
       aria-labelledby="myModalLabel"
       aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;
          </button>
          <h4 class="modal-title" id="detail_title"></h4>
        </div>
        <div class="modal-body">

          <div class="row">
            <div class="col-md-5" id="detail_image">
            </div>

            <div class="col-md-7" id="detail_details">

              <table class="table">
                <tbody>
                <tr>
                  <th class="detail_key">Author:</th>
                  <td class="detail_value" id="author">Value</td>
                </tr>
                <tr>
                  <th class="detail_key">Narrated By:</th>
                  <td class="detail_value" id="narrated_by">Value</td>
                </tr>
                <tr>
                  <th class="detail_key">Duration:</th>
                  <td class="detail_value" id="duration">Value</td>
                </tr>
                <tr>
                  <th class="detail_key">Purchased</th>
                  <td class="detail_value" id="purchase_date">Value</td>
                </tr>
                <tr>
                  <th class="detail_key">Rating:</th>
                  <td class="detail_value" id="rating">Value</td>
                </tr>
                <tr id="mp3_details">
                  <th class="detail_key">Files:</th>
                  <!-- <td class="detail_value" id="files"></td> -->
                </tr>
                </tbody>
              </table>
            </div>
          </div>
          <div class="row">
            <div class="col-md-12">
              <div id="summary" class='summary'></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<script>
  function showImages(showImages) {
    if (showImages) {
      $("#image_table").show();
      $("#compact_table").hide();
      populateBooks(window.myBooks, "#image_table");
    } else {
      $("#image_table").hide();
      $("#compact_table").show();
      populateBooks(window.myBooks, "#compact_table");
    }

    var navbar = document.getElementById("navbar");
    var stickyHeader = navbar.offsetTop;

    window.onscroll = function() {
      if (window.pageYOffset >= stickyHeader) {
        navbar.classList.add("stickyHeader")
      } else {
        navbar.classList.remove("stickyHeader");
      }
    };
  }

  $(document).ready(function () {
    // handle show image checkbox change
    $('#show_images').change(function () {
      showImages($(this).prop('checked'));
    });
    showImages(false);      // display
    $('#filter').keyup(filter);
  });

</script>
</body>
</html>

```

**Comment by oboe45** [comment]
Thanks - that does exactly what I need, just have to figure how to get it
into the generated site, and, figure how it can be permanently there and
not over written on the next site update/generation.  Probably simple to
do, but a challenge for the older non-techy!   Thanks - I assume this will
not be in the next release, but is s one-off??

**Comment by LanceMcCarthy** [comment]
@oboe45 This will have to be implemented by @openaudible because index.html is overwritten every time you fetch new titles.

# Temporary Options

Before we go into the file update options, first you need to find where the index.html file is saved to 

![image](https://user-images.githubusercontent.com/3520532/104237374-f40dcb80-5425-11eb-866e-b9071b949f5c.png)

Now that you know where that is, we can move forward

## Automatic - Timer Based

You can write a powershell script that updates the index.html file with content from a backup file. For example save the file below as `update_openaudible_webpage.ps1`

```powershell
# This file contains your customizations
$backupIndexPath = C:\MyDocs\backup_index.html

# This is the file path to the one that always gets overwritten by Openaudible
$normalIndexPath = C:\MyWebsiteFolder\index.html

# Step 1 - Get the content form the backup file
$backupHtml = Get-Content -Path $backupIndexPath

# step 2 - Overwrite the website's index.html with the custom html
Set-Content -Path $normalIndexPath -Value $backupHtml
```

Now you can use Windows **Task Scheduler** to run the Powershell script. you can do it on a timer, like once a day, or you can do it when you log into the computer, etc. This tutorial is a nice and easy one to follow https://windowsloop.com/run-powershell-script-on-schedule-using-task-scheduler/ 

For example, here's what one of my PC's looks like 
![image](https://user-images.githubusercontent.com/3520532/104239231-2b7d7780-5428-11eb-943c-0090aa5eccbd.png)


## Manual Update

1. Go to the folder where your index.html file is located
2. Open it in your favorite text or code editor
3. Update the file contents with your backed up/custom content (save it is a separate file so you do not lose it)
4. Save it

That's it. Because this is a static website, you do not need to restart any webserver. It's just the contents of the html file that matter.

**Comment by oboe45** [comment]
Thanks for this, however, I work on a mac, so some of the infor
does'nt apply.  Instead, I saved a copy of my working index.html from the
web folder then imported the new index.html and executed as per usual.  The
works except that none of the files have the download link in the form
panel, presumably this is a result of the safety changes you made in the
new html?  Is there an easy fix for this, I cannot figure it from the html
code.  All of the other content of the web link is unchanged.

Thanks

**Comment by LanceMcCarthy** [comment]
yes, I commented out the line. Search for 'detail_value' and when you find it remove the comment block (delete these things)

![image](https://user-images.githubusercontent.com/3520532/104241004-fb83a380-542a-11eb-8a75-bd318c59eaa2.png)


Bash
Although [Powershell is now available for Mac](https://docs.microsoft.com/en-us/powershell/scripting/install/installing-powershell-core-on-macos?view=powershell-7.1), I would recommend sticking with the native Bash script  (`.sh` file instead of `ps1`). the script for that is slightly different, but the concept is the sa(copy the backup text into index.html). as far as scheduling goes, Mas OC has a similar capabilty https://dssw.co.uk/blog/2011-05-22-how-to-run-a-shell-script-every-day-on-a-mac/

**Comment by LanceMcCarthy** [comment]
@oboe45 I removed the public link to my website and re-enabled the mp3 code. You should be able to use it all, as-is.

**Comment by oboe45** [comment]
Thanks again, I found it just after I sent the email!!

My problem with openaudible is that it worked well till I started trying to
stay up tod ate with the beta versions, for reasons of my own stupidity, I
keep messing up the process.  So I have one working copy of the final
output website, generated a couple of months ago, and, till I can
re-educate myself, I will not use the app to regenerate the working site -
so I simply applied your changes to my own site on my local NAS and it
works as a great way to find and load any of the 2000 MP3, m4a and m4b
books that I have - most of which come from original MPX downloads but a
few hundred are from collections years ago.
Frankly, I prefer to use itunes on the mac to manage the files, but with
the latest Mac updates, support for itunes is rapidly disappearing and
support for audiobooks on the new OS just is not as simple and
comprehensive as Itunes,

Thanks again for the prompt responses - its working well now as long as I
do not attempt any suicidal changes to the working site!!

Bob Barker

**Comment by LanceMcCarthy** [comment]
@oboe45 I highly recommend checking out Plex. I have a Library just for OpenAudible's mp3s folder.

![image](https://user-images.githubusercontent.com/3520532/104242744-99786d80-542d-11eb-8eb3-aae698094c53.png)

My pro-tip is to use the custom scanner for that library. It always finds the perfect match for me https://github.com/dethrophes/Audiobooks.bundle

**Comment by oboe45** [comment]
Thanks will try Plex

**Comment by oboe45** [comment]
I noticed that the second line of the site also needs to be Sticky, or it
is not possible to sort or filter on the site after the site has been
scrolled down, The table headings are not reachable after the search line
has been scrolled.

**Comment by LanceMcCarthy** [comment]
HTML Table header can be sticky, too, but that's a separate topic. Instructions here https://stackoverflow.com/questions/55673873/sticky-table-header-with-two-header-rows

**Comment by openaudible** [comment]
Thanks for the new HTML! Will integrate into the next beta.
 
Tip: If you change the index.html, OpenAudible is not supposed to overwrite any changes you make. (At least, that is the logic I recall.) Which also means that the index.html may not get updated properly unless you delete the original index.html. Will have to experiment. 

Also open to Kendo, but it looks like it would need a license.. and not sure it would fall into a normal category of usage (re-distributed as part of a generated web app.) I'm also not an HTML guy, so would need to find someone to do a prototype.

**Comment by LanceMcCarthy** [comment]
You're correct about needing a licensed for Kendo Grid (most Kendo components are free, but not the data controls). Though one license covers your distribution reach (you would just use the Kendo CDN links instead of including any js libraries).

My last experience with index what that it was getting replaced, a while back I opened an issue (or we chatted over email) to fix an issue with the favicon or page headers. You pushed an update with the fix and I havent needed ot manually change it since :)

**Comment by openaudible** [comment]
I added your sticky header in beta 8. 
appreciate the prototype but think will pass on Kendo. But will try to figure out a way to only overwrite index when my index changes (infrequently, I hope). Or make it easier to create or share better html. 

reopen or open new issue if needed.
