### ISSUE TITLE
full library not downloaded using complete sync

### ISSUE THREAD

**Issue by soylentyellow** [openaudible/openaudible#515]
My library has more than 500 books; Downloaded 213 already. But all the others will not be recognized even with complete sync. Tried it several times; not luck. ANy idea what to do? I use version 2.3.5.

**Comment by openaudible** [comment]
Try the beta from issue #510 

Also, we only can download books you’ve purchased— free books and podcasts aren’t available to download.

**Comment by soylentyellow** [comment]
New beta already tested. Same result. Free books and podcasts were removed. I will check if older books are aax format. I am member of audible since 2008. May be there is the problem?

Am 24. Dezember 2020 19:00:37 MEZ schrieb openaudible <notifications@github.com>:
>Try the beta from issue #510 >
>>
>Also, we only can download books you’ve purchased— free books and
>podcasts aren’t available to download. >
>>
>-- >
>You are receiving this because you authored the thread.>
>Reply to this email directly or view it on GitHub:>
>https://github.com/openaudible/openaudible/issues/515#issuecomment-750936678

-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by openaudible** [comment]
The beta does not yet support user names that are not email addresses.
When you do a full sync, it should give an indication of how many books it finds. 
This should match the number of books in the web based "library" view. 
If you see errors in the console (File: Console) let me know. You should also see a bunch of log messages when doing a full sync. 

See if you can determine a specific book that is missing. Make sure it shows on your mobile device and in audible in your browser.

**Comment by openaudible** [comment]
Podcasts and free books are not available for download. Sorry.. OpenAudible is for backing up your purchases. Free books are not accessible.
