### ISSUE TITLE
OpenAudible

### ISSUE THREAD

**Issue by RogerWerner** [openaudible/openaudible#516]
i would like to carry openaudible to convert my books into mp3 but the demo version does not alow to test this function the price 12 € i am wiiling to pay but not before i know that it works for my reason. How can you help me with this

**Comment by openaudible** [comment]
Have faith. Read the reviews. The conversion is the easy part.

**Comment by RogerWerner** [comment]
thanks i will get it

**Comment by RogerWerner** [comment]
some trust is ok with open software but i will be very much pissed if i doest work because i am poor and 12€ is a lot of money for me thats food for 4 days dont cry its ok for me better than nothing

**Comment by RogerWerner** [comment]
germany takes care even for someone who is not able to work because of health disabelitiers so i am still lucky to live here

**Comment by openaudible** [comment]
Sounds good! And we do offer refunds if it doesn't work for you-- but I'm sure it will work fine for you. Merry Christmas.

**Comment by RogerWerner** [comment]
the first book is coverted but only as one file is this normal i had the hope that it will be with many mp3 files so i can stop and start again with the next file

**Comment by RogerWerner** [comment]
would you very angry if i want my money back because so i cannot use it  for me you it  dont work .

**Comment by RogerWerner** [comment]
i have opened a case by paypal the Adress is Paypal@itnetdesign.de if you stay on the promise of refund please close the case with the refund

**Comment by openaudible** [comment]
By default, OpenAudible converts one book to one file. From there, it can be optionally split by chapter.
You've been refunded and your software has been disabled.

**Comment by RogerWerner** [comment]
I very much thank you for refunding so fast. I didnt find that option before sorry for that. Iwill buy it again.
