### ISSUE TITLE
how to download all from audible to openaudible

### ISSUE THREAD

**Issue by denny1700** [openaudible/openaudible#518]
Can't
Controls: Download All From Audible
It's all grayed out.
Just bought the openaudible app a few days ago.  Very disappointing.  Not intuitive, can't convert one book at a time.

**Comment by openaudible** [comment]
First you have to log in, then scan your library.. your books should show in the GUI. From there, you should be able to "Download all". Hard to tell what steps you might have missed. There is a quick setup guide on our web page: https://openaudible.org/
