### ISSUE TITLE
Error in Converting Book, Embedded Chapter Information Incorrect

### ISSUE THREAD

**Issue by mgoodie99** [openaudible/openaudible#519]
Hey, I've used OpenAudible for a couple months now without issue, and this is the first and only time I've had it fail. When Converting, both the MP# or M4A, on just Rick Riordan's _The Serpent's Shadow_ it spits out the book with 44 chapters, none of which are actually a chapter maker. The actual book only has 23 chapters and that is correctly displayed when I play the book through Audible itself. There is no error message and it says that it "Converted OK" but it consistently fails on just this one book. Hopefully you can help figure it out.

**Comment by openaudible** [comment]
Sounds like Audible has an issue with that book. We don't try to do anything with the chapter data except feed it to ffmpeg to decode. You could try to contact audible and say one of the books you downloaded with audibe's download manager has bad chapter data.. But nothing we can do.
