### ISSUE TITLE
File Name Strategie

### ISSUE THREAD

**Issue by tomtom90** [openaudible/openaudible#52]
Is there a reason to name files by Product_ID?
For Audiobooks the title would be a good file name to make the file name humanly readable.

The check if a file is downloaded should be compared by tag instead of name.
The naming could probably be scripted as is in mp3tag and alterd in settings.

**Comment by openaudible** [comment]
If you export your books to a web page, the software creates an mp3 directory with human readable titles. The reason not to use the title is to avoid naming collisions and to avoid problems if the strategy changed (duplicate mp3s). It was a tradeoff.

**Comment by tomtom90** [comment]
Thanks for the response and explenation, and of curse for the good work you did so far.
