### ISSUE TITLE
Question: Is there an easy way to rename output files that keeps the system in sync?

### ISSUE THREAD

**Issue by JoshFink** [openaudible/openaudible#520]
My need for organization is killing me with the way that Audible names these files. I was hoping to make it a little more readable as well as have some kind of organization in the output folder. 

For instance, I have the book 'Veiled' part of the 'Alex Verus Series' and it's 'Book 6'

The name from Audible and thus the output filename is:

Veiled Alex Verus, Book 6

I'd like it to be Alex Verus - Book 6 - Veiled as when I go look at the folder this will group all of the Alex Verus books together. 

I can manually go in and change the output file name, the AAX filename and then go edit the books.json but it's a lot of work times several hundred books. Then I have to hope it doesn't get overwritten in the future by a change. 

Is something like this possible but in an easier manner that I might be overlooking? 

Thanks

**Comment by openaudible** [comment]
No easy way yet. (You figured out the hard way.) But it’s a feature that would be nice. Will take a look.

**Comment by JoshFink** [comment]
Thanks.. Appreciate the response and letting me know I'm not missing a much easier way to do it.

**Comment by openaudible** [comment]
OK, looks like most of the code was already there.. A Rename function has been added to the beta https://openaudible.org/beta and will also be in the next full version. Its a "one at a time" thing, and hasn't had much testing.. but pretty simple feature. If you have any problems, let us know in the bug reporter or re-open this issue. 

Thanks for the suggestion.

**Comment by JoshFink** [comment]
@openaudible Thanks for the rename support. This is a great first start on it and will save a lot of time. I appreciate it.

**Comment by RandmTask** [comment]
Hi,

Its a great feature thanks for adding it.

Any chance of having the rename being a bulk feature for every time a file is downloaded? ie with a custom rename mask such as Author/Author - Series - Title (Year) ?
