### ISSUE TITLE
Ubuntu/Pop_OS Dark Color Scheme hard to read

### ISSUE THREAD

**Issue by eduncan911** [openaudible/openaudible#522]
![image](https://user-images.githubusercontent.com/104980/103941908-8b5ce100-50fd-11eb-8098-95f8c5cb1e97.png)

Using Ubuntu/Pop_OS' default "Dark" theme, you can see this application does not properly honor the system color settings (not all of them anyways).

Ubuntu 20.10/Pop_OS 20.10
Default Gnome Dark color scheme (nothing custom)
Using the `AppImage` version of OpenAudible

**Comment by openaudible** [comment]
Just the blue text? There wasn't good code to determine if a user has dark mode enabled by the system.. so we just tried to pick a color that would show up in dark or light modes.. Will try to address. The blue signifies that the text can be clicked to do something.

**Comment by eduncan911** [comment]
Yep, just the dark blue.

And I didn't even know they could be clicked.  👍

**Comment by eduncan911** [comment]
> There wasn't good code to determine if a user has dark mode enabled by the system.

Then how come the rest of the backgrounds and colors changed to use my systems' dark mode colors and links?

**Comment by openaudible** [comment]
We don't set any text or background colors (except the blue) and the system automatically assigns the color that is used. 
I just added some code to correct the colors if dark mode is detected. Will be in next beta (number 8) or next release.

**Comment by openaudible** [comment]
Improved dark mode in beta. Just need to make new dark version images to complete.
