### ISSUE TITLE
Library Sync Issue - V2.3.5

### ISSUE THREAD

**Issue by byronholloway** [openaudible/openaudible#525]
I have a large library.   When I try to sync with Audible it downloads 1-2 pages then I get an 
"Unable to connect right now.  
Try logging on to Audible from this web page and try again"

I can't get past 59 books in my library.   

Console Log:
Jan 12, 2021 9:03:20 AM org.openaudible.desktop.swt.manager.browser.GetPageTask task
SEVERE: 09:02:20.171	06:00:00.001	waitForPageLoad:start
09:02:20.706	06:00:00.536	browser state unknown -> loading
09:02:21.803	06:00:01.633	browser state loading -> interactive
09:02:21.836	06:00:01.666	event:LocChanged -> LocationEvent{Browser {} time=0 data=null location=https://www.audible.com/library/titles?ref=a_library_t_c6_pageNext&pf_rd_p=560464e0-54f4-4eaa-a85e-683f4ff0233a&pf_rd_r=8KACSCFEHK8M5B2Q76VJ&page=2 top=true doit=false}
09:02:22.309	06:00:02.139	browser state interactive -> complete
09:03:20.445	06:01:00.275	Warning.. timeout waiting for page load
Jan 12, 2021 9:03:20 AM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 783 to disk:C:\Users\Byron\OpenAudible\tmp\0.txt
Jan 12, 2021 9:03:20 AM org.openaudible.audible.AudibleScraper setURL
INFO: got page:htmlPage(https://www.audible.com/library/titles?ref=a_library_t_c6_pageNext&pf_rd_p=560464e0-54f4-4eaa-a85e-683f4ff0233a&pf_rd_r=8KACSCFEHK8M5B2Q76VJ&page=2) html length:0 took 60.285 seconds to complete.
Jan 12, 2021 9:03:20 AM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 42 to disk:C:\Users\Byron\OpenAudible\tmp\empty lib page.html
Jan 12, 2021 9:03:20 AM org.openaudible.util.HTMLUtil debugHtml
INFO: Debug: C:\Users\Byron\OpenAudible\tmp\empty lib page.html
Jan 12, 2021 9:03:20 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFO: Library page contains: 0 book(s)
Jan 12, 2021 9:03:20 AM org.openaudible.audible.AudibleScraper takePageResults
INFO: Parsed library page. Added 0 updated 0 done=true
Jan 12, 2021 9:03:20 AM org.openaudible.audible.AudibleScraper rescanLibrary
INFO: Finished rescanLibrary library... took 62.715 seconds to complete.
Jan 12, 2021 9:03:20 AM org.openaudible.audible.AudibleScraper rescanLibrary
INFO: Start:Bad Download Link:0. Missing Download Link:21
End:  Bad Download Link:0. Missing Download Link:21
Jan 12, 2021 9:03:20 AM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 75222 to disk:C:\Users\Byron\OpenAudible\tmp\saved_books.json
Jan 12, 2021 9:03:20 AM org.openaudible.Audible save
INFO: Save books took 18 ms. to complete.
Jan 12, 2021 9:03:20 AM org.openaudible.desktop.swt.manager.AudibleGUI downloadAndConvertWithDialog
INFO: You have 1 book(s) to download.
You have 35 book(s) to convert to MP3
 autoConvert=false
Jan 12, 2021 9:03:25 AM org.openaudible.desktop.swt.gui.MessageBoxFactory task
INFO: MessageDialog: title:Start jobs? body:You have 1 book(s) to download.
You have 35 book(s) to convert to MP3
Would you like to start these job(s) now? response:BUTTON_NO
Jan 12, 2021 9:03:34 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: License
Jan 12, 2021 9:04:02 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Preferences
Jan 12, 2021 9:04:19 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by overbets** [comment]
I am getting the same issues. Support or a refund for a non-functioning product would be nice.

**Comment by kparadine** [comment]
Same issue, mine stops at 40 books.

**Comment by openaudible** [comment]
You can try the beta, which should address it.  We are getting close to the final beta before moving it to a final release.
https://openaudible.org/beta
Also, if you have "pihole", you may need to disable it.

**Comment by overbets** [comment]
Thanks I will give it a try today

**Comment by kparadine** [comment]
Beta fixed my problem.  Got all 110 Audible books downloaded and converted
last night.  Great tool.   The beta sounds like it should become the
release version, if not now, soon.

**Comment by overbets** [comment]
Looks like the beta is working for me too. It recognized 633 books and I am
trying to download them now. Looks like a great job on the update

**Comment by meibner-hub** [comment]
Same Problem but no Amazon Account just an old Audible Login

**Comment by openaudible** [comment]
@meibner-hub Not sure if the beta supports the old audible log in. Can you give it a try? You may need to convert your audible log in to email though.. Not sure!

**Comment by blurfl** [comment]
The beta does not presently support the 'old' audible log in, I check with each beta release.

 Converting to an email log in transfers the account to an Amazon account. This becomes problematic if the user already has a different Audible account linked to that Amazon account, as the two accounts cannot be combined.

 The Audible mobile app can handle log in to either the old username account or the email-linked account. The release OpenAudible app handles both as well, but so far the beta releases have not yet met this requirement.

**Comment by openaudible** [comment]
@blurfi - Unfortunately we haven't been able to figure out the best way to support older accounts.. I assume you don't have "pihole" or another site-wide ad-blocker installed on your network?

**Comment by openaudible** [comment]
@blurfl The beta now supports older Audible accounts that use usernames. Give it a try! 
Closing.
