### ISSUE TITLE
Removing mp3/m4a/m4b files 

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#527]
For a number of reasons, I have copies of many of my audiobooks in more than one of the formats listed in the output web page.  Not a big issue, just a waste of space, but is there a simple way to safely and quickly remove, for example, an mp3 which is duplicated in m4a/m4b format in the final web page, and then rebuild or amend the web page quickly?

**Comment by openaudible** [comment]
Not easily that I can think of. Some people like mp3 and m4b versions... but thinking of removing support for m4a (and just rename all m4a to m4b...) The web page is definitely wasted space. Trying to fix that.
