### ISSUE TITLE
"File or directory .\org.eclipse.swt.win32.win32.x86_64/jar not found or empty"

### ISSUE THREAD

**Issue by Dim3nsi0n** [openaudible/openaudible#528]
I purchased the software this week but was only able to view/download the first 20 books as others have reported. I installed the beta, OpenAudible_2.4.0.8_beta_win.exe, but now receive the following error window when attempting to open the program:

"File or directory .\org.eclipse.swt.win32.win32.x86_64/jar not found or empty"
![Capture](https://user-images.githubusercontent.com/33645563/104768418-764a0880-5722-11eb-94af-e2891fec0dfe.JPG)

This is all that is displayed and program will not open. Running Windows 10 x64. 

Thanks for your assistance.

**Comment by openaudible** [comment]
Beta 8 had a broken build. Please try version 9 at the same link. Sorry for the trouble.
