### ISSUE TITLE
Can't connect for quick sync

### ISSUE THREAD

**Issue by gottifire** [openaudible/openaudible#529]
Been using the program for about 6 months with no issues. 

Today I tried to do a quick sync and for the first time ever had a problem. 

I did successfully connect to audible beforehand. 

After the quick sync tries to connect for about 30 seconds a box then pops up saying:

"Unable to connect right now. 

Try logging on to Audible from this web page and try again. "

Same issue when I try a full sync

Any ideas?

My only thought is that I recently changed internet providers and that it has something to do with that. But my internet connection is fine

**Comment by openaudible** [comment]
Make sure you aren't using pihole. 
You can try the beta version which gets around the web scraping method of getting books.
https://openaudible.org/beta
