### ISSUE TITLE
Choose region in preferences [feature-request]

### ISSUE THREAD

**Issue by gigajosh** [openaudible/openaudible#53]
(Please excuse me if there is a better place to log a feature request for this program.)
I'd like to have an option in Preferences to select the region. 
I understand that Audible theoretically defaults to the correct region once a user has logged in, but in my case I have purchased audiobooks in both the audible.com store and the audible.co.uk store, but with the same Amazon account.
I see different libraries when I login to the audible.com site or the audible.co.uk site.
At present when I login with openaudible it always defaults to my audible.com account and there appears to be no way for me to switch to my audible.co.uk account.
I'd like to therefore request a feature that will let me opt to login to a specific region, perhaps by simply selecting an alternative domain extension in Preferences.

**Comment by ryancpwalsh** [comment]
Identical problem here, as an audible.ca issue, the library sync is not working.  I believe its hard coded to www.audible.com/lib vs. the more specific regionalized URLs.

**Comment by openaudible** [comment]
To switch accounts, open the built in browser and log out of the current region, and enter the URL for the new region and log in. From there, the code is supposed to recognize the new region and use that from there on. make sure you can view your book lib from the correct region without audible taking you back to the previous region.. 

However, if you're doing a library sync, and you see our app take you to the us region, that is a bug. It is supposed to recognize any audible.xx.xx/lib as your library page for that region. We simply haven't had much feedback or done any testing for other regions. 

If someone wants to send credentials for an empty account, or send a console transcript, that might help.. 

Adding a saved default region is probably a good idea.

**Comment by ryancpwalsh** [comment]
It's definitely displaying that its going to .com/lib in lieu of .ca in my case (if display is correct its not going to the correct region).

![image](https://user-images.githubusercontent.com/3332426/47735166-595cb400-dc42-11e8-8266-cde930306766.png)

**Comment by ryancpwalsh** [comment]
Note, I believe any amazon account works in any region, you should be able to create a blank one or use an existing one to test.  If you have library content in one region but not another, you should be able to see your content, and then NOT see your content when testing.  If your .com library is showing up even after you've specifically switched regions, its not pointed at the correct location.

Perhaps a regionalized drop down or something in the UI that manipulates the library URL would help?

**Comment by gigajosh** [comment]
I'd just like to add that if I simply download the AAX files directly from the Audible site and import them with the import feature, openaudible converts them.
I didn't realise this at first, as I didn't notice openaudible was doing this with my imported file (another minor point maybe) but I have the conversion functionality so am more than happy :)
Just to clarify my point about not noticing the conversion: when "Automatically convert to MP3" is selected in Preferences and none of the books are highlighted, there's nothing in the interface to indicate a conversion is taking place (just my poor old Mac's cpu fan ;)) So it may be worth adding a current job, panel at the top or some other indicator.

**Comment by ryancpwalsh** [comment]
Absolutely, when OpenAudible is "Connected", I can drop my AAX files into a folder manually and it'll decrypt / convert them to MP3 for me no problem.

**Comment by openaudible** [comment]
Mostly reproduced and will attempt to fix the region issue for next release. Yes, there are some work-arounds like clicking the "Download" link for any book in the browser and we can download and convert it. 
There is a "Converting N of X" in the status panel, but it is easy to miss. 
Please re-open a new issue if not working in next 1.2.5 release.

**Comment by ryancpwalsh** [comment]
Thank you for the update!
