### ISSUE TITLE
working from my downloaded library of AAX Files

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#530]
I have all of my AAX files from a previous download using OpenAudible - hundreds of them.  I want to create a new web page with all of these AAX files converted to m4b.  

Can I just "import books" for all of the already downloaded AAX files into OpenAudible so that it converts them to M4b and generates the web page with all of the data including audible link, cover page, descriptions etc that would have appeared if Openaudible had downloaded the AAX files directly?

If not, how can I regenerate the web page, completely, without a re-download of all of the AAX files since this stage takes days of download time!

I ask the question since each time I update the software, I seem to have to back to the start and reload everything all over again.

**Comment by openaudible** [comment]
Yes, you should be able to drag and drop the AAX files into OpenAudible (or use the "File:Import" menu).
The import makes a new copy of the AAX files, so heads up you might end up using twice as much disk space.. but you can delete the previous copies if all goes well.
You shouldn't have to re-import anything--unless you're using a custom directory and/or you delete the openaudible settings (in particular, directories.json) so not sure what happens to you.
