### ISSUE TITLE
Release Notes

### ISSUE THREAD

**Issue by DrGuns4Hands** [openaudible/openaudible#531]
For the Beta version is there somewhere I can find the full list of release notes. Example. I have 2.4.0.5 beta and haven't checked back in a few weeks. Now I see 2.4.0.9 and what is new in that release, but have no Idea what has changed in the other point releases in between.

Tracking them as the differential from stable might be best for being able to come in at any point and know what all is new.

**Comment by openaudible** [comment]
No official release notes... But we recommend upgrading to the latest beta. We released a new one today. There were some changes to fix "unregistering", support for m4b splitting/joining, new html for generated web pages, dark theme, and I'm sure a lot more.
