### ISSUE TITLE
France user Beta 2.4.0.9 fails at converting aax imported directly from hard drive 

### ISSUE THREAD

**Issue by jvjerry** [openaudible/openaudible#533]
Hi @openaudio, first and foremost, please forgive the lenght of this issue description. 

CONTEXT 
Congrats for your great app, love it. Tested with paid licensed OpenAudible_2.3.5_mac  and then uninstalled to install OpenAudible_2.4.0.9_beta_mac
Both connected well to Audible FRANCE and was able to sync my Audible library, AAX files where downloaded and converted to mp3 without any problem. 

NON CONVERSION ISSUE
 
My issue arose for A FRACTION (5 AAX files) of the 10 something Audible books that I had : 

a) Downloaded DIRECTLY to my hardisk from my Audible account website (aka without OpenAudible connected to my Audible account) before I knew the existence of OpenAudible, 

and that I had then b) RETURNED to Audible (aka these audible books are now AAX files on my hard drive but they're not anymore in my Audible Account Library). 

Precision : all of these files where Audible BOOKS I had bought (no Free, no romance serie etc), read, downloaded and then returned to Audible

The strange thing is : 

1/ MOST of these 10 AAX files I imported in OpenAudible from my Mac hard drive where correctly converted to MP3.

 2/ AND 5 ONLY of these files where coined by OpenAudible as MISSING LINKS (aka "No audio file or Download link").

As shown by their respective Book reports created with OpenAudible (see one example below) the corresponding AAX files: 
• are not AAXC (which I understood are not convertible),
• include all the audiobook Metadata (Chapters etc), 
• account for several hundreds of MB each (aka not empty files) 
• and where downloaded like a charm to muy Hard Drive with Audible download button from my audible account when I had them in my library, before returning them.

I provided all these details in order to justify my belief that these AAX books should / could be converted to MP3. 

Obviously the easy way to try to solve my issue could be to re-purchase these titles to Audible and re-download them again through OpenAudible once connected to my Audible account.... 
Ok but this is a test I would like to avoid as I had already returned these books to Audible before installing OpenAudible.

There must be other ways, maybe less easy but more universal, to solve the more general issue we face **WHEN OpenAudible FAILS AT CONVERTING THE  AAX FILES WE IMPORTED DIRECTLY FROM HARD DRIVE (files downloaded from Audible without connecting to OpenAudible).** 

**QUESTION : What can I do to TRY TO CONVERT TO MP3 THESE  "MISSING LINKS" AAX files ?** 

DONE WITHOUT SUCCESS : 
• I read extensively through Github OpenAudible open and closed topics.
• I closed - re-opened OA /refreshed books/re-synced my library / deleted and re-imported the files from my Mac's HD.  

As OpenAudible is a friendly UI  for FFMPEG (and a swiss knife much more than that), maybe the following hypothesis is not relevant (Please tell us) : 

**shall I try to force AAX to MP3 conversion for Missing link files with FFMPEG ?**

In order to convert my Missing link aaX files I WISH I COULD TRY THE FOLLOWING STEPS, but don't really know how to do it (only saw a few tutos to cut and paste on Google) and most importantly I don't know if it's worth a try (is there any other solution ??) : 

A/ Install FFMPEG on my Mac (apparently best through HomeBrew + some cut and paste commands in Mac Terminal ?)
B/ Find my Audible "Activation Bytes" for my AAX files (apparently best with https://audible-tools.github.io/ ?)
C/ Open my Mac Terminal (easy)
D/ Type the right sequence in the right Directory in Terminal command line to CONVERT these AAX files to MP3 with FFMPEG 

**MY THREE QUESTIONS :**

**Question I => Is it worth a try to use FFMPEG directly in the command line to try to force the Conversion for my Missing Links AAX files ?**
(I read somewhere that if OpenAudible didn't convert a file there wasn't much chance that FFMPEG would do it, since OA is based on FFMPEG. 
But I also read somewhere else that someone with a similar issue succeeded in forcing the conversion with FFMEPG. Unfortunately the guy didn't described how he used FFMPEG)

**Question II => Is there any simpler way than the one I described before (A-B-C-D) to force FFMPEG conversion of my Missing Links AAX files with or without OpenAudible ?**

**Question III => If Yes to Question I and No to Question II, could you please DETAIL THE PRECISE STEPS AND COMMANDS of the A-B-C-D SEQUENCE for the people like me, among OpenAudible licensed users, who are not at all command line geeks ??**

Please find enclosed : 

- **Book report** of one of my 5 Missing Links audiobook (which shows that the "No audio file or Download link" is an actual AAX audio file with all Metadata and Chapters included)
[BOOK REPORT Lemaitre Pierre Les Enfants du désastre 1 Au revoir la haut.pdf](https://github.com/openaudible/openaudible/files/5864168/BOOK.REPORT.Lemaitre.Pierre.Les.Enfants.du.desastre.1.Au.revoir.la.haut.pdf)

- **Diagnostic** (general info about my OA Beta 2.4.0.9 config settings, nothing exceptional)
[Diagnostic OpenAudible 2.4.0.9.pdf](https://github.com/openaudible/openaudible/files/5864169/Diagnostic.OpenAudible.2.4.0.9.pdf)

- **a screenshot of my 5 AAX files that OpenAudible qualified as Missing Links** (I know this won't serve more than illustrating the point) displaying the OpenAudible window and also the Finder window on my Mac for the 5 files concerned (these are the first 5 rows in the list of files). 
![2021 01 25 4h04 Screenshot](https://user-images.githubusercontent.com/77948911/105661475-c1f07500-5ecd-11eb-84d6-65fd1b84f79b.png)

Upon request : 
I could send a bug report with the number of this issue  

Looking forward to your answers, I thank you in advance, **hopping that @openaudible developers or someone else among OA users could :** 

i) suggest something else than "you should re-purchase these titles and re-download them again through OpenAudible"... There must be other solutions to try ? 

ii) share the problems and solutions found when importing AAX files directly from Hard Drive without connecting to Audible. Maybe this Missing Link issue is common, why and how should OA users solve it ?

iii) whatever the answers to the above, could anyone be so kind so as to teach us, the non geeks, how to use directly FFMPEG for some reluctant files like in my case ? 

With all my gratitude, and I believe the gratitude too of the (probably very small minority, among the readers and contributors to the OpenAudible GitHub) other non developer geeks, who nonetheless love OpenAudible !

**Comment by jvjerry** [comment]
I just saw that a new OA Beta was released 2.4.10. I would have liked to wait for @openaudible answers with my OA beta 2.4.09 before upgrading, but since 2.4.10 was released a new issue added to the subject of this thread : 

OA doesn't display any book anywhere anymore in the App (see screenshot) whilst all the files are still present on their respective OA directories (the AAX in AAX directory, the mp3 in Books directory. 

I closed and reopened and the pb persists, thus I guess I will have to upgrade to latest beta version in order to have all things up again...grr

**Question IV => ABOUT UPGRADING OpenAudible on a Mac from a previous version of OA :** 

what is best among the following procedures A/ B/ C/ in order to : 

• preserve in the upgrade the personalized folder path I had choosen in Beta OA 2.4.09 Preferences for the two eligible OA Directories (the Library Directory and the Web Directory) ?

• avoid any problem of MP3 books already converted from AAX with previous version not taken into account by last version (I had this issue when upgrading from 2.3.5 to beta 2.4.09 
In this occasion I had previously dropped the OA App to the Trash AND erased the OA folder in the Mac User Library folder).

**On a Mac shall we upgrade OpenAudible by doing :** 

A/ Install the latest release 2.4.10 overwriting the previous OA version 2.4.09 WITHOUT Uninstalling 2.4.09 ? 

B/ Or Uninstall the previous OA version 2.4.09 (by sending the App to the Trash on a Mac) before installing the latest OA beta release ? and do nothing more

C/ Or Do B + manually erase the Open Audible folder in the Mac User Library folder ?
 
Thks for your feedback on the matter and on the former questions I / II / III of this thread

**Comment by openaudible** [comment]
A lot to cover. We can't really help you with trying to recover a book you returned. 
You can import mp3, m4a (and next release m4b) files you already have into OA. Just drag and drop audiobook files onto the app.

Thank you for the feedback and will read and reply more.

**Comment by jvjerry** [comment]
Thks for this first beginning of answer @openaudible. 
Your detailed answers to Questions I & III /FFMPEG, and Question IV / Upgrading will be very welcomed by the community. Looking forward to them, be sure the effort is worth and will be appreciated. 

I apologize again for the lenght of my user experience feedback about the issues I faced with OA beta 2.4.0.9 and Audible France (who is not concerned by my issue). The first message of this thread is long because I tried to maker every point clear, aiming at easing your precise feedback, and also because I thought these issues might be of interest for other OA users and fans like me.

OA is a great tool that I believe is more powerful than other paid solutions around. These are not necessarily more expensive than OA but easier to use because less features, FAQs, customer service etc. But I belong to the people like the other here in Github, who believe in the superiority of open source programs and love them, in spite of their sometimes long learning curve (which is not the case of OA, which is quite intuitive at the UI level, bravo).

**Comment by jvjerry** [comment]
What is the best way to upgrade to latest OA beta version 2.4.10 while preserving the AAX and MP3 files in the same directories that had been choosen in previous OA version for Library and Web Directory ? 

A/ Install the latest release 2.4.10 overwriting the previous OA version 2.4.09 WITHOUT Uninstalling 2.4.09 ?

B/ Or Uninstall the previous OA version 2.4.09 (by sending the App to the Trash on a Mac) before installing the latest OA beta release ? and do nothing more

C/ Or Do B + manually erase the Open Audible folder in the Mac User Library folder ?

**Comment by jvjerry** [comment]
No answer from @openaudible and any one else ?
I'd like to upgrade de good way

**Comment by openaudible** [comment]
Sorry for the delay.

Unfortunately, there isn't a great way to go back from the beta to the non-beta. We made a few changes that are not backwards compatible. Which is why the beta is taking so long to release... there are a lot of changes. For windows, the installer automatically removes the previous version. For Mac, we recommend sticking with the beta until we release a new version. There may be a way to point OpenAudible to your library and Control: Rescan files to find any books in the directories.

Missing link files means we don't have any way to download the book. If you can recover a decent AAX file, you can import it. But AAXC files are not supported. And if you get repeated errors trying to download a file, that also means it is unavailable-- maybe download from the audible web page. 

There are other apps that do similar things. We try to avoid getting into obscure topics about converting books not purchased and available in your audible library. We do print pretty detailed log messages to the File:Console where you can see ffmpeg commands and any errors.
