### ISSUE TITLE
A few more minor items with 2.4.1.0 Beta

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#535]
Works well for me, just a couple of minor changes would improve it.

1. For very long booklists, it would be really helpful if the Table Title line was also "Sticky" so that sorting can be done without going back to the top of the form
2. The "Narrator" has a link back to the Audible site, very useful, but it would be even more helpful to have the Author as a link to the Audible site - this is easier to use than filtering by author, and used to be present in an earlier release.
3. Links always point to .... audible.com, could they not instead point to audible.ca or whichever is the audible region logged in?
4. Is is possible to show the book link (mp3, m4a or m4b) in the main list window and not just in the modal dialog?
5. I can import mp3 and M4a, works great - why cannot I also import m4b?

Thanks for all the earlier improvements - great app!

**Comment by openaudible** [comment]
1. Yeah, that's a lot harder. Open to suggestions, but don't want to use a commercial html product.
2. Good point
3. Will Check
4. Possible
5. Will fix -- thank you.

Expect 2,3,5 in next release.

**Comment by openaudible** [comment]
Closing for now. Marking 1 and 4 as feature requests. I did make a bunch of changes to the web in beta 13.
