### ISSUE TITLE
Export book list

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#538]
"Export Book List" is only enabled when "Export Web page" is also available.  Is it possible for the Export Book List menu item to be available always - its very useful for lots of reason.

Thanks

**Comment by wwalker** [comment]
+1 Great product!  But, for me, the books.json is the best feature.

**Comment by openaudible** [comment]
Export Book List is always available under the File Menu. I can't reproduce your issue or see any code that would prevent the Export Book List from being enabled (except running in demo mode.) 
 
If you select books in the gui, those are what get exported. If you select all (or none), you export all books.

**Comment by oboe45** [comment]
Here is a screen print of the menu and OA screen on a licenced version of
the latest beta[image: Screen Shot 2021-01-26 at 3.52.30 PM.png]

**Comment by oboe45** [comment]
The item for Export Book List is disabled unless a synch to Audible has
happened.  So, if the site is constructed from previous AAX downloads, mp3
files and m4a files, then the menu item is greyed unless and until OA is
synched with the Audible site.

Not an issue since a quck synch enables the menu item.

**Comment by openaudible** [comment]
The screen grab did not come through.

The only thing I see in the code is that there has to be books showing in your library for export book list to be enabled.

**Comment by oboe45** [comment]
There are mp3, m4a and m4b in the library - the screen shot shower the
counts for these books, the same screen print has the "download web site
and. the download books" options greyed out.
