### ISSUE TITLE
Settings.json file

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#539]
The Settings.json file is rewritten every time the app starts up and always contains the same default information.  Is this the intent?  

How can the default threads items be permanently changed?  

Other defaults in the file are also reset on every restart, is this intentional, should not "Output Options" and "Automation" options be preserved and re-used on every restart?

**Comment by openaudible** [comment]
Settings should only be written on startup if there is settings data missing or another error reading the settings file.
Check the log and check the json file for any syntax errors. Editing by hand can cause problems. Will add a reason message if we need to write the prefs. 

Threads can be permanently changed with values between 1 and 99

**Comment by oboe45** [comment]
The file is re-written every time the app is restarted.  If I change the
app options - to use m4b conversion for example, this is forgotten on the
next load of the program and the options defult to Mp3 conversion, and load
AAX files automatically.  Each time I load the app these options have to be
reset by me.  The file locations however are saved and reloaded.  I have
made no changes manually to the json file(s).  If I change the threads for
download or conversion threads in the JSON file, nothing happens in the app
and they are reset. to 3 on next reload.

**Comment by oboe45** [comment]
Here is a log print:
Jan. 26, 2021 6:53:56 P.M. org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 2.4.1.0 for cocoa swt 4940 jvm 12
file.encoding UTF-8
Jan. 26, 2021 6:53:57 P.M. org.openaudible.Directories isValid
SEVERE: Not found:/Applications/OpenAudible.app/Contents/Resources/app
Jan. 26, 2021 6:53:57 P.M. org.openaudible.desktop.swt.manager.AudibleGUI
<init>
INFO: audible desktop 2.4.1.0
Jan. 26, 2021 6:53:57 P.M. org.openaudible.Directories getPrefs
INFO: loaded settings 1611695818605
Jan. 26, 2021 6:53:57 P.M. org.openaudible.audible.AudibleConnectionState
setRegion
INFO: Setting audible region to CA
Jan. 26, 2021 6:53:58 P.M. org.openaudible.util.HTMLUtil writeFile
INFO: wrote 2 to
disk:/Users/robertbarker/Library/OpenAudible/tmp/saved_books.json
Jan. 26, 2021 6:53:59 P.M. org.openaudible.Audible save
INFO: Save books took 965 ms. to complete.
Jan. 26, 2021 6:53:59 P.M. org.openaudible.util.HTMLUtil writeFile
INFO: wrote 444 to
disk:/Users/robertbarker/Library/OpenAudible/settings.json
Jan. 26, 2021 6:53:59 P.M. org.openaudible.Directories getPrefs
INFO: loaded settings
Jan. 26, 2021 6:53:59 P.M. org.openaudible.util.HTMLUtil writeFile
INFO: wrote 464 to
disk:/Users/robertbarker/Library/OpenAudible/settings.json
Jan. 26, 2021 6:53:59 P.M. org.openaudible.Audible load
INFO: Loading /Volumes/Web/testFiles/books.json
Jan. 26, 2021 6:53:59 P.M. org.openaudible.Audible checkLibrary
INFO: loaded 0 books.
Jan. 26, 2021 6:53:59 P.M. org.openaudible.desktop.swt.manager.AudibleGUI
applicationStarted
INFO: applicationStarted took 246 ms. to complete.
Jan. 26, 2021 6:54:02 P.M. org.openaudible.desktop.swt.manager.VersionCheck
getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Jan. 26, 2021 6:54:12 P.M.
org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by openaudible** [comment]
Not sure. I'll add some debug statements into the code to show why I'm saving the prefs on start. It does look like the books file is initially empty, which is why the Export Books might not be enabled. 
Also seeing an error on startup: SEVERE: Not found:/Applications/OpenAudible.app/Contents/Resources/app which I don't recognize.

**Comment by openaudible** [comment]
I just posted a new beta version with some added debugging and other changes..
