### ISSUE TITLE
2.4.1.0 - Mac Catalina 10.15.7 - Cannot download new books when I updated

### ISSUE THREAD

**Issue by JoshFink** [openaudible/openaudible#542]
I had been on .9 of the beta. Since I hadn't purchased any new books in a bit I hadn't used it. I purchased a book yesterday and then downloaded the new version. I noticed that I couldn't download my new book. It didn't even see it. 

I did a quick sync and a full sync and neither saw it. 
I logged out and logged back in and nothing.
I went to Controls -> Browser and I saw it in the list there

I then went and reverted back to .9 and on opening the program it saw the new book right away. 

Thanks

**Comment by openaudible** [comment]
Hmm. I suspected it was a free book or podcast.. but you said you purchased it.. so not positive. We only support getting books that you've purchased. When you viewed in the browser, was there a "Download" button next to the book? If so, you can click that.. and it also means there may be a bug in the code. You can do a full rescan and see if the name of the book shows up in the console.

**Comment by JoshFink** [comment]
Yep, there was a download button next to the book and I could have done that. However, when I reverted back to 2.4.9 it worked fine and showed right up. I'm wondering if I could go and delete it, delete the m4b I created and then clear out the book line and try it out again on 2.4.9 or I just saw you released 2.4.11.

**Comment by JoshFink** [comment]
Alright. I was able to reproduce this. 

- Closed Open Audible
- Removed the entry from books.json
- Removed the aax and m4b file
- Installed 2.4.1.1 beta 

Whereas on open, version 9 of the beta showed 'Processing 105 books', when I opened up OpenAudible on 10 and 11 I now show 'Processing 104 books'.

If I click Controls -> Browser I can see the latest book and there is a Listen Now and Download button in the browser view.

BTW, if I go to About -> Diagnostics first and then go to Controls -> Browser it only shows about:blank in the browser window. If I go to Control -> Browser first it works but if I open back up Diagnostics I can't get back to the Library view from the browser until I close and reopen OA. 

 If you let me know where the logs are or what info you need I can provide it. I'll leave it at 11 for now. I don't need to get anything as of now so I should be fine.

**Comment by openaudible** [comment]
Try the latest beta if you don’t mind. If it skips books you can send a bug report from the Help menu. We do skip books that we can’t get a download link for. Usually those are podcasts that don’t have a download button in the web browser. But there may new exceptions. 

Thanks for the report on the diagnostics. Fixed.

**Comment by JoshFink** [comment]
Ok. I submitted a bug report through the app. Still doesn't work.

**Comment by openaudible** [comment]
Got the report. But we clear the temporary files when you restart the app, so some of the logs are missing. 

Usually it is because a book was discontinued, free, returned, a podcast, or something else is not available for download.  But since you say you can see the Download button in the web browser it is possible it is a new audio encoding method or something not supported by OA. We'd love to figure it out. Also, I assume when you click the "Download" button, the AAX is actually downloaded and added to OpenAudible?

Anyway, if you don't mind, restart OpenAudible, do a full library rescan, check for the book, and if it is not there, do a bug report and reference 542 and I'll look at the full logs.

**Comment by JoshFink** [comment]
> Usually it is because a book was discontinued, free, returned, a podcast, or something else is not available for download. But since you say you can see the Download button in the web browser it is possible it is a new audio encoding method or something not supported by OA. We'd love to figure it out.

Thanks. I submitted the report. 

One thing that confuses me is that if it was a new audio encoding method or something not supported by OA then why would it work fine in the .9 of the beta but since 10 on it hasn't worked. I can revert back to 9 and it works again. 

> I assume when you click the "Download" button, the AAX is actually downloaded and added to OpenAudible?

It does actually download when I open the browser and click download. It however doesn't download with any metadata but downloads with a title of: 1250787920

**Comment by openaudible** [comment]
Its a good question. Its possible we aren't finding a good encoding codec for the book. 

I saw the second bug report. Looks like you did a Rescan Files.. but not a "Full Library Update". 
So I wasn't able to see what book(s) were skipped or why. 
If you don't mind... can you do one more report with "Restart latest app, then: Controls: Full Library Rescan, Bug Report"
And let me know the name of the book (and/or ASIN) that is having problems.

**Comment by JoshFink** [comment]
is 'Full Library Update' supposed to be there? I don't have it. I have 'Quick Library Sync' and 'Full Library Sync'

![2021-02-01_13-06-42](https://user-images.githubusercontent.com/4679749/106499432-97368b80-648e-11eb-92f1-6913617da46b.png)

The ASIN is 1250787920 and the title is Prodigal Son: https://www.audible.com/pd/Prodigal-Son-Audiobook/1250787920

**Comment by openaudible** [comment]
Yes, meant: Full Library Sync.

Actually, we just changed the name in the next version to make it more clear: Full Audible Library Sync  and Quick Audible Library Sync *(Quick gets books added since the last successful rescan.)

**Comment by openaudible** [comment]
Got your report. That book looks fine. It "should" be added to your library when you do a rescan... and the download link "should" work... But obviously it isn't. Will dig deeper! Thank you!

**Comment by openaudible** [comment]
OK! Fixed it! Was a bug where we weren't waiting the right amount of time to get the download link. Thank you for the report.
https://openaudible.org/beta
Re-open or create a new bug if you find anything.

**Comment by JoshFink** [comment]
Thanks @openaudible , I appreciate you fixing it. I just loaded the new beta and everything worked great.
