### ISSUE TITLE
Version 4.1.1.1 Beta still does not preserve some preference settings

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#543]
Every restart of the app causes the settings to revert to the initial settings for Output Format and Automation, the file settings are however preserved and reloaded - see below,

1. I loaded the new version and started it.
2. Turned Console on - output attached
3. Checked preferences to ensure file locations all correct and that Output and Automation Options are set the way I prefer:  the file options are OK, but the output and Automation are set to values I don not want, so I change them to M4B and remove all automation checkmarks; then I click ok to save the changes.  The log file says that it wrote the changes, and if I inspect the settings.json file - yes, the changes are reflected.  I quit the program : I See log file so far here:
4.Jan. 28, 2021 12:40:06 P.M. org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 2.4.1.1 for cocoa swt 4940 jvm 12 file.encoding UTF-8
Jan. 28, 2021 12:40:06 P.M. org.openaudible.Directories load
INFO: Directories:{
 "META": "/Users/robertbarker/Library/OpenAudible",
 "APP": "/Applications/OpenAudible.app/Contents/Resources/app",
 "WEB": "/Volumes/Web/testFiles/web",
 "TMP": "/Users/robertbarker/Library/OpenAudible/tmp",
 "BASE": "/Volumes/Web/testFiles"
}
->{
 "META": "/Users/robertbarker/Library/OpenAudible",
 "APP": "/Applications/OpenAudible.app/Contents/Resources/app",
 "MP3": "",
 "ART": "",
 "WEB": "/Volumes/Web/testFiles/web",
 "TMP": "/Users/robertbarker/Library/OpenAudible/tmp",
 "AAX": "",
 "M4B": "",
 "M4A": "",
 "BOOKS": "",
 "BASE": "/Volumes/Web/testFiles"
}
Jan. 28, 2021 12:40:07 P.M. org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 2.4.1.1
Jan. 28, 2021 12:40:07 P.M. org.openaudible.Directories getPrefs
INFO: Loading /Users/robertbarker/Library/OpenAudible/settings.json exists=true size=464
Jan. 28, 2021 12:40:07 P.M. org.openaudible.Directories getPrefs
INFO: loaded settings 1611855170396
Jan. 28, 2021 12:40:07 P.M. org.openaudible.audible.AudibleConnectionState setRegion
INFO: Setting audible region to CA
Jan. 28, 2021 12:40:07 P.M. org.openaudible.util.HTMLUtil writeFile
INFO: wrote 2 to disk:/Users/robertbarker/Library/OpenAudible/tmp/saved_books.json
Jan. 28, 2021 12:40:07 P.M. org.openaudible.Audible save
INFO: Save books took 24 ms. to complete.
Jan. 28, 2021 12:40:07 P.M. org.openaudible.util.HTMLUtil writeFile
INFO: wrote 444 to disk:/Users/robertbarker/Library/OpenAudible/settings.json
Jan. 28, 2021 12:40:08 P.M. org.openaudible.Directories getPrefs
INFO: Loading /Users/robertbarker/Library/OpenAudible/settings.json exists=true size=444
Jan. 28, 2021 12:40:08 P.M. org.openaudible.Directories getPrefs
INFO: loaded settings 
Jan. 28, 2021 12:40:08 P.M. org.openaudible.desktop.swt.manager.AudibleGUI loadPrefs
INFO: Saving prefs on startup, reason: setting uid,setting lastVersion,
Jan. 28, 2021 12:40:08 P.M. org.openaudible.util.HTMLUtil writeFile
INFO: wrote 464 to disk:/Users/robertbarker/Library/OpenAudible/settings.json
Jan. 28, 2021 12:40:08 P.M. org.openaudible.Audible load
INFO: Loading /Volumes/Web/testFiles/books.json
Jan. 28, 2021 12:40:08 P.M. org.openaudible.Audible checkLibrary
INFO: loaded 0 books.
Jan. 28, 2021 12:40:08 P.M. org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFO: applicationStarted took 153 ms. to complete.
Jan. 28, 2021 12:40:10 P.M. org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
Jan. 28, 2021 12:40:11 P.M. org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Jan. 28, 2021 12:41:36 P.M. org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: About
Jan. 28, 2021 12:43:41 P.M. org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Preferences
Jan. 28, 2021 12:45:50 P.M. org.openaudible.desktop.swt.manager.views.Preferences okPressed
INFO: okPressed
Jan. 28, 2021 12:45:50 P.M. org.openaudible.desktop.swt.layout.Theme setTheme
INFO: Setting color theme to system
Jan. 28, 2021 12:45:50 P.M. org.openaudible.util.HTMLUtil writeFile
INFO: wrote 465 to disk:/Users/robertbarker/Library/OpenAudible/settings.json

5. I restart the application and turn on the log
6. The log says the the Settings file is loaded, but when I look into the file now, the settings are not those which were just saved,  the output format has changed to Mp3, and the automation check marks are back!
7. This is the log that shows the second openingJan. 28, 2021 12:50:13 P.M. org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 2.4.1.1 for cocoa swt 4940 jvm 12 file.encoding UTF-8
Jan. 28, 2021 12:50:13 P.M. org.openaudible.Directories load
INFO: Directories:{
 "META": "/Users/robertbarker/Library/OpenAudible",
 "APP": "/Applications/OpenAudible.app/Contents/Resources/app",
 "WEB": "/Volumes/Web/testFiles/web",
 "TMP": "/Users/robertbarker/Library/OpenAudible/tmp",
 "BASE": "/Volumes/Web/testFiles"
}
->{
 "META": "/Users/robertbarker/Library/OpenAudible",
 "APP": "/Applications/OpenAudible.app/Contents/Resources/app",
 "MP3": "",
 "ART": "",
 "WEB": "/Volumes/Web/testFiles/web",
 "TMP": "/Users/robertbarker/Library/OpenAudible/tmp",
 "AAX": "",
 "M4B": "",
 "M4A": "",
 "BOOKS": "",
 "BASE": "/Volumes/Web/testFiles"
}
Jan. 28, 2021 12:50:14 P.M. org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 2.4.1.1
Jan. 28, 2021 12:50:14 P.M. org.openaudible.Directories getPrefs
INFO: Loading /Users/robertbarker/Library/OpenAudible/settings.json exists=true size=465
Jan. 28, 2021 12:50:14 P.M. org.openaudible.Directories getPrefs
INFO: loaded settings 1611855608125
Jan. 28, 2021 12:50:14 P.M. org.openaudible.audible.AudibleConnectionState setRegion
INFO: Setting audible region to CA
Jan. 28, 2021 12:50:14 P.M. org.openaudible.util.HTMLUtil writeFile
INFO: wrote 2 to disk:/Users/robertbarker/Library/OpenAudible/tmp/saved_books.json
Jan. 28, 2021 12:50:14 P.M. org.openaudible.Audible save
INFO: Save books took 16 ms. to complete.
Jan. 28, 2021 12:50:14 P.M. org.openaudible.util.HTMLUtil writeFile
INFO: wrote 444 to disk:/Users/robertbarker/Library/OpenAudible/settings.json
Jan. 28, 2021 12:50:15 P.M. org.openaudible.Directories getPrefs
INFO: Loading /Users/robertbarker/Library/OpenAudible/settings.json exists=true size=444
Jan. 28, 2021 12:50:15 P.M. org.openaudible.Directories getPrefs
INFO: loaded settings 
Jan. 28, 2021 12:50:15 P.M. org.openaudible.desktop.swt.manager.AudibleGUI loadPrefs
INFO: Saving prefs on startup, reason: setting uid,setting lastVersion,
Jan. 28, 2021 12:50:15 P.M. org.openaudible.util.HTMLUtil writeFile
INFO: wrote 464 to disk:/Users/robertbarker/Library/OpenAudible/settings.json
Jan. 28, 2021 12:50:15 P.M. org.openaudible.Audible load
INFO: Loading /Volumes/Web/testFiles/books.json
Jan. 28, 2021 12:50:15 P.M. org.openaudible.Audible checkLibrary
INFO: loaded 0 books.
Jan. 28, 2021 12:50:15 P.M. org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFO: applicationStarted took 132 ms. to complete.
Jan. 28, 2021 12:50:17 P.M. org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console
Jan. 28, 2021 12:50:18 P.M. org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Jan. 28, 2021 12:51:39 P.M. org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Preferences
Jan. 28, 2021 12:52:29 P.M. org.openaudible.desktop.swt.manager.views.Preferences okPressed
INFO: okPressed
Jan. 28, 2021 12:52:29 P.M. org.openaudible.desktop.swt.layout.Theme setTheme
INFO: Setting color theme to system
Jan. 28, 2021 12:52:29 P.M. org.openaudible.util.HTMLUtil writeFile
INFO: wrote 464 to disk:/Users/robertbarker/Library/OpenAudible/settings.json

**Comment by oboe45** [comment]
Confirm that the preferences are loaded correctly now in 2.4.1.2_beta

Thanks will continue tests

**Comment by openaudible** [comment]
Thanks for your help.
