### ISSUE TITLE
connecting to library don't work with audible.de

### ISSUE THREAD

**Issue by carkrueger** [openaudible/openaudible#55]
Hi,

can you support login to audible.de?

greetings
Carsten

**Comment by openaudible** [comment]
Copy and paste the URL you see when you click on your "library" page to show your list of books.

**Comment by christgod** [comment]
I have the same problem. I can log in to audible.de, and audible.de/lib shows a list of my books, but OA does not appear to connect.
![image](https://user-images.githubusercontent.com/5426008/48162346-1b642d80-e2dd-11e8-9345-fe92c7b9cddf.png)

**Comment by christgod** [comment]
Here is the console output, it appears OA doesn't recognize that I'm logged in:
INFORMATION: Command: Connect
Nov 07, 2018 10:45:18 PM org.openaudible.desktop.swt.manager.AudibleGUI connectTask
INFORMATION: connectTask:https://www.audible.de/lib
Nov 07, 2018 10:45:18 PM org.openaudible.audible.AudibleScraper setURL
INFORMATION: setURL:https://www.audible.de/lib
Nov 07, 2018 10:45:18 PM org.openaudible.desktop.swt.manager.browser.GetPageTask getPage
INFORMATION:  getPage:https://www.audible.de/lib js=true
Nov 07, 2018 10:45:22 PM org.openaudible.desktop.swt.manager.browser.GetPageTask task
INFORMATION: 0:getPage:https://www.audible.de/lib completed 3656 ms
10:45:18.619	01:00:00.000	waitForPageLoad:start
10:45:21.556	01:00:02.937	event:LocChanged -> LocationEvent{Browser {} time=0 data=null location=https://www.audible.de/lib top=true doit=false}
10:45:21.556	01:00:02.937	event:ProgComplete -> ProgressEvent{Browser {} time=0 data=null current=0 total=0}
10:45:21.707	01:00:03.088	event:ProgComplete -> ProgressEvent{Browser {} time=0 data=null current=0 total=0}
10:45:21.785	01:00:03.166	event:ProgComplete -> ProgressEvent{Browser {} time=0 data=null current=0 total=0}
10:45:21.942	01:00:03.323	needQuery: last=0 new=4
10:45:22.275	01:00:03.656	query start: end:h_len=985257 hash=802E1A4F eq=false Last Query:333;ProgChanged:9ProgComplete:3LocChanging:0LocChanged:1;same=0;diff=0;url=https://www.audible.de/lib
10:45:22.275	01:00:03.656	waitForPageLoad exit:3656 result=h_len=985257 hash=802E1A4F inspect=Last Query:333;ProgChanged:9ProgComplete:3LocChanging:0LocChanged:1;same=0;diff=1;url=https://www.audible.de/lib
Nov 07, 2018 10:45:22 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFORMATION: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=0 total=0}
Nov 07, 2018 10:45:22 PM org.openaudible.desktop.swt.manager.AudibleGUI connectTask
SCHWERWIEGEND: connectTask failed to log in: org.openaudible.audible.AudibleLoginError: Not logged in:AudiblePage:https://www.audible.de/lib 985257 bytes html

**Comment by openaudible** [comment]
Give 1.2.6 a try. The .de site didn't have the standard "signout" link we were looking for to detect that you were connected. Thanks for the helpful reports. Please let me know and close this if it works.

**Comment by christgod** [comment]
I just tried 1.2.6.
The connection seems to be working, but the library sync doesn't find my books:

![image](https://user-images.githubusercontent.com/5426008/48298777-4e681600-e4c3-11e8-9b5f-6c9673ac9468.png)

Here's the console output:

`Nov 10, 2018 8:32:00 AM org.openaudible.desktop.swt.manager.AppLoader <init>
INFORMATION: Starting OpenAudible build 1.2.6 for win32 swt 4623 jvm 1.8.0_141
Nov 10, 2018 8:32:01 AM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFORMATION: audible desktop 1.2.6
Nov 10, 2018 8:32:01 AM org.openaudible.Audible checkLibrary
INFORMATION: bl=0, gl=0
Nov 10, 2018 8:32:01 AM org.openaudible.Audible findOrphanedFiles
INFORMATION: orphaned aax files:1
Nov 10, 2018 8:32:01 AM org.openaudible.Audible findOrphanedFiles
INFORMATION:  orphan: BK_LUEB_003018.AAX
Nov 10, 2018 8:32:01 AM org.openaudible.util.SimpleProcess <init>
INFORMATION: Running: "C:\Program Files\OpenAudible\bin\win_ffmpeg" -i C:\Users\Stoffele\OpenAudible\aax\BK_LUEB_003018.AAX -f ffmetadata - 
Nov 10, 2018 8:32:01 AM org.openaudible.Audible findOrphanedFiles
INFORMATION: orphaned mp3 files:1
Nov 10, 2018 8:32:01 AM org.openaudible.Audible findOrphanedFiles
INFORMATION: 	BK_LUEB_003018.mp3
Nov 10, 2018 8:32:01 AM org.openaudible.util.SimpleProcess <init>
INFORMATION: Running: "C:\Program Files\OpenAudible\bin\win_ffmpeg" -version 
Nov 10, 2018 8:32:01 AM org.openaudible.desktop.swt.manager.AudibleGUI checkFFMPEG
INFORMATION: using ffmpeg version N-76456-g6df2c94 Copyright (c) 2000-2015 the FFmpeg developer
Nov 10, 2018 8:32:03 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFORMATION: Command: Connect
Nov 10, 2018 8:32:06 AM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFORMATION: versionCheck: http://openaudible.org/swt_version.json?platform=win&version=1.2.6
Nov 10, 2018 8:32:07 AM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFORMATION: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=0 total=0}
Nov 10, 2018 8:32:07 AM org.openaudible.audible.AudibleConnectionState setRegion
INFORMATION: Setting audible region to DE
Nov 10, 2018 8:32:08 AM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFORMATION: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=0 total=0}
Nov 10, 2018 8:32:09 AM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFORMATION: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=0 total=0}
Nov 10, 2018 8:32:12 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFORMATION: Command: Rescan_Library
Nov 10, 2018 8:32:12 AM org.openaudible.audible.AudibleScraper _fetchLibrary
INFORMATION: ******************* LIBRARY PAGE 1
Nov 10, 2018 8:32:12 AM org.openaudible.audible.AudibleScraper setPageFilter
WARNUNG: setPageFilter Unimplemented
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=We Are Legion (We Are Bob) Part 1: Bobiverse, Book 1,duration=5 Std. 26 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=We Are Legion (We Are Bob) Part 2: Bobiverse, Book 1,duration=4 Std. 4 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Sherlock Holmes: The Definitive Collection Part 1,duration=6 Std. 34 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Sherlock Holmes: The Definitive Collection Part 2,duration=13 Std. 20 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Sherlock Holmes: The Definitive Collection Part 3,duration=13 Std. 30 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Sherlock Holmes: The Definitive Collection Part 4,duration=14 Std. 7 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Sherlock Holmes: The Definitive Collection Part 5,duration=9 Std. 15 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Sherlock Holmes: The Definitive Collection Part 6,duration=15 Std. 8 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Origin Part 1: A Novel,duration=9 Std. 38 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Origin Part 2: A Novel,duration=8 Std. 31 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Das Erbe der Elfen - Teil 1: The Witcher 1,duration=6 Std. 11 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Das Erbe der Elfen - Teil 2: The Witcher 1,duration=6 Std. 23 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=The Black Echo: Harry Bosch Series, Book 1 Part 1,duration=6 Std. 44 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=The Black Echo: Harry Bosch Series, Book 1 Part 2,duration=7 Std. 4 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Tyll - Teil 1,duration=5 Std. 36 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Tyll - Teil 2,duration=5 Std. 40 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Promise of Blood Part 1: The Powder Mage Trilogy, Book 1,duration=6 Std. 25 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Promise of Blood Part 2: The Powder Mage Trilogy, Book 1,duration=6 Std. 31 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Promise of Blood Part 3: The Powder Mage Trilogy, Book 1,duration=6 Std. 4 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=The Dragonbone Chair Part 1: Memory, Sorrow & Thorn, Book 1,duration=10 Std. 48 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=The Dragonbone Chair Part 2: Memory, Sorrow & Thorn, Book 1,duration=11 Std. 13 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=The Dragonbone Chair Part 3: Memory, Sorrow & Thorn, Book 1,duration=11 Std. 10 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Different Seasons Part 1,duration=11 Std. 13 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Different Seasons Part 2,duration=8 Std. 36 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Eine kurze Geschichte der Menschheit - Teil 1,duration=8 Std. 43 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Unable to get ASIN: fullTitle=Eine kurze Geschichte der Menschheit - Teil 2,duration=8 Std. 19 Min.,
Nov 10, 2018 8:32:12 AM org.openaudible.util.HTMLUtil debugHtml
INFORMATION: Debug: C:\Users\Stoffele\OpenAudible\tmp\empty lib page.html
Nov 10, 2018 8:32:12 AM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Library page contains: 0 book(s)
Nov 10, 2018 8:32:12 AM org.openaudible.audible.AudibleScraper _fetchLibrary
INFORMATION: pageNum=1 total=0 new=0 partial=0
Parsed:0 books

Nov 10, 2018 8:32:12 AM org.openaudible.Audible updateLibrary
INFORMATION: Updated 0 books
Nov 10, 2018 8:34:05 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFORMATION: Command: Console
`

**Comment by christgod** [comment]
I just found the other comment recommending to set the "Software Verification" option in the account details (
(https://github.com/openaudible/openaudible/issues/36#issuecomment-432925187)
After setting this I started the audible download manager on my pc, and now Open Audible seems to work.

The setting on the German account page:
![image](https://user-images.githubusercontent.com/5426008/48298964-4e1d4a00-e4c6-11e8-9b83-f51197241ec2.png)

Is the download manager required for Open Audible?

**Comment by openaudible** [comment]
The download manager is not required. But that option is required to be set correctly. Thanks for the feedback.

**Comment by GianniGi** [comment]
unable to connecto to audible.it
