### ISSUE TITLE
Not more than 255 chapters possible (M4A)

### ISSUE THREAD

**Issue by chbks335** [openaudible/openaudible#550]
unfortunately, titles with more than 255 chapters are being capped. Means, the chapters after 255 are cut and not available in the created m4a. Whereas they are included in the aax.

**Comment by openaudible** [comment]
That is unfortunate. Sounds like a limitation of ffmpeg. 
Can you give me the name of any books with more than 255 chapters? Maybe I can do a little research.

**Comment by chbks335** [comment]
yeah, thats reasonable, because other tools have the same problem. I only can name german books, for example Frank Schätzing Breaking News. This one has over 300 Chapters. Thanks for checking that out.

**Comment by openaudible** [comment]
Feel free to send a bug report on that aax file to https://openaudible.org/check.html and we can look at the meta data for that file. Maybe file a report with ffmpeg.

**Comment by chbks335** [comment]
Just sent the report. Thanks for checking it! Oh yeah, btw: There is also a problem with the umlaut in the comments, they are not correctly displayed, but only in that metadatafield, it doesn't affect the title or author.

**Comment by openaudible** [comment]
Thank you for submitting.  

I think this is a bug in your audio PLAYER. If you do a "Controls:Book Report" for your book, you'll see that all your chapters are shown for aax and m4a/b files.

Closing, but feel free to send any updates.

**Comment by chbks335** [comment]
Well i'm not an expert, but in the log i can see all chapters. Still more than one Tool can only read 255 of them (VLC and MKVmerge) and iTunes ignores the Chapters completely.
Attached i included a picture where i have draged the original aax and the m4a/m4b into mkvmerge. The AAX is correct, but for the m4a/m4b only 255

[Logs.zip](https://github.com/openaudible/openaudible/files/5940027/Logs.zip)

**Comment by openaudible** [comment]
This is a limitation of the original mp4 specification that sets the number of chapters using one byte in the "chpl" box.  Google mp4 "chpl" shows the Count of chapters is represented as a single byte, which has a 0-255 range.

**Comment by chbks335** [comment]
Ah, OK! Thank you very much!
