### ISSUE TITLE
Not releasing book list when logging out of one region and logging on to  new one.

### ISSUE THREAD

**Issue by wartbump** [openaudible/openaudible#556]
Hello I a runnining version beta 2.4.1. beta. on MAC Big Sur 11.01.
I login to Audible US and do a full refrshh and get the correct book list.
I logout of the US region and in to the UK region.
No matter what I do , restart, refresh etc. it still shows all the books from the US region !
Any help would be apprecitaed, thank you.

**Comment by openaudible** [comment]
Can you try the beta? Amazon makes it tricky to go to a region not associated with your IP address. 
Openaudible.org/beta

**Comment by wartbump** [comment]
I am runnining version beta 2.4.1. beta. on MAC Big Sur 11.01

**Comment by openaudible** [comment]
Oh. So.. You would need to change your library path in addition to logging in or out.
From preferences, you would change the library path.. (Say, to "user_x_books") and then restart and log in as user x.

**Comment by wartbump** [comment]
OK, thanks I´ll try that

**Comment by openaudible** [comment]
Closing and marking as a feature request.
