### ISSUE TITLE
Unable to register a device (Australia)

### ISSUE THREAD

**Issue by stefwill** [openaudible/openaudible#557]
Using 2.4.1 beta
Click Connect to Audible
Select Region AU - www.audible.com.au
Enter Login details click continue
Get the following error dialogue 
Error Registering Connection
Unable to register a device
![image](https://user-images.githubusercontent.com/32256920/107712598-cdd99500-6d1d-11eb-8db9-881e86e7efa5.png)

**Comment by openaudible** [comment]
Hmm. I don't know that we have any AU users. I assume you were able to log in OK. Would you mind trying again and then send a bug report? Additional log messages would be sent that can be helpful.

**Comment by stefwill** [comment]
Yes, I can log into Audible.com.au just fine.
Bug report sent

**Comment by openaudible** [comment]
Thank you for the report. It may be that OpenAudible is not yet compatible with Australia. I’ll look at your report and hopefully have something. By chance have you tried libation? https://github.com/rmcrackan/Libation/releases/latest  our beta uses a similar API. It works on Windows.

**Comment by stefwill** [comment]
Hi, It worked just fine up until a few weeks ago.

**Comment by mkb79** [comment]
@stefwill 
It seems openaudible uses parts of my code to login and register a new Audible device. I‘ve identified the problem. More information can be found [here](https://github.com/mkb79/Audible/issues/37).

**Comment by openaudible** [comment]
Wow that’s great news. Only our beta uses the API. Would love to give you (and/or others) credit for the api work. Feel free to drop me an email at openaudible@email.tg if you want.

**Comment by openaudible** [comment]
Thank you to @mkb79 there should be a working beta:
https://openaudible.org/beta
Please re-open if not fixed.
