### ISSUE TITLE
no status shown when starting app

### ISSUE THREAD

**Issue by TomW1605** [openaudible/openaudible#56]
when i start the app (latest version) there is no status shown. 
here is a screenshot showing what i get:
![screenshot](https://user-images.githubusercontent.com/17092573/47984009-2e75d280-e110-11e8-869e-f6f4dd9fda69.png)
if you want any more info let me know.

**Comment by openaudible** [comment]
What OS are you using? The font sizes look really large. With linux we decrease all font sizes by 1... but we do hard-code the size of the StatusPanel to 170 in MainWindow which is probably the problem--that and your oversized fonts!

Will change for the next version.

**Comment by TomW1605** [comment]
i am running windows 7 Premium x64 but i think the font problem is probably due to my 4k display and 150% scaling

**Comment by openaudible** [comment]
Fixed in 1.2.6 released yesterday.

**Comment by TomW1605** [comment]
thanks
i have started using the github version with some modification to make it work with my scaling and to be more useful for my situation
