### ISSUE TITLE
Windows / hidpi screen: menu not shown correctly

### ISSUE THREAD

**Issue by rcoenen** [openaudible/openaudible#566]
See below. Windows 10. HiDpi screen. Scaling set to 200%

![image](https://user-images.githubusercontent.com/753704/108586915-37a9fe00-731f-11eb-8e9e-749b2216bda8.png)

**Comment by openaudible** [comment]
Thank you. Will fix for next release.

**Comment by openaudible** [comment]
Maybe fixed in beta. Feel free to give it a try. Don't have a HiDPI monitor. 
https://openaudible.org/beta
Please re-open if not fixed.

**Comment by rcoenen** [comment]
works beautifully now... Thanks!
![image](https://user-images.githubusercontent.com/753704/109399445-dbdc0800-7910-11eb-8440-a673ab4e73dd.png)

**Comment by rcoenen** [comment]
Works beautifully now... Thanks!
![image](https://user-images.githubusercontent.com/753704/109399474-075ef280-7911-11eb-9de5-b4e3bbf342b7.png)

**Comment by rcoenen** [comment]
Works beautifully now... Thank you!
![image](https://user-images.githubusercontent.com/753704/109399636-08445400-7912-11eb-8a5b-ca78cc675380.png)
