### ISSUE TITLE
Feature Request: Add / Store associated PDFs

### ISSUE THREAD

**Issue by fantapop** [openaudible/openaudible#567]
Some of my audiobooks have accompaniment PDFs. It would be great if open Audible could store the PDFs alongside the audio files.

**Comment by 1234shai** [comment]
Excellent idea.  When by the way can we expect the edits to be complete, and the next non-beta version to be released?

**Comment by openaudible** [comment]
It’s a good idea. Marked as feature request. No ETA. 

Beta seems to work well for most users. But not working in Australia. Not tested everywhere. So holding off releasing until working everywhere.

**Comment by openaudible** [comment]
Added this feature to latest beta:
https://openaudible.org/beta
Looking for feedback.
