### ISSUE TITLE
Failed to Convert (Great Courses)

### ISSUE THREAD

**Issue by Northness** [openaudible/openaudible#568]
I have just downloaded, among others, a Great courses Audible (Economics, 3rd Edition.AAX).  Running under Windows 10.

On trying to convert to MP3 it gives me a "Failed to Convert" error.

All other books I downloaded converted fine.

I wondered if this issue is because it is "Great Courses", but I have other GC downloads from before that have converted.

Any thoughts ?

**Comment by openaudible** [comment]
Not sure. Make sure the AAX file is downloaded from OpenAudible. If you want, you can send a copy of the AAX file so we can view the meta data at: https://openaudible.org/check.html

**Comment by Northness** [comment]
Uploaded Great Courses - Economics, 3rd Edition.AAX (can't uploaded in this msg as "We don't support that file type".

**Comment by Northness** [comment]
... ok; got a bit ahead of myself; it was uploading while I typed msg above; it failed because storage full (see attachment)
![audible](https://user-images.githubusercontent.com/11797511/109387567-ba0a6300-78c7-11eb-8ebb-b85d5d3acdf6.JPG)

**Comment by openaudible** [comment]
Give it another try when you get a chance.

**Comment by markshanehokanson** [comment]
Github issue #562, mulitple titles failing to convert, including Great Courses Series titles that were mentioned in the the initial post on Github, but many others as well, including the following titles: Angels and Demons, Wolves of the Calla: Dark Tower, The Dark Tower, On Writing: A Memoir of the Craft, The Modern Scholar: Rings, Swords, and Monsters, Salem's Lot, The World of Ice and Fire, The Power of Habit, The Shining, Ready Player one....I could keep going. Definitely more failing than succeeding, which is frustrating since I just barely purchased a license for the software.

**Comment by openaudible** [comment]
Can you try again to send one of the aax files to the https://openaudible.org/check.html page?
Would love to solve.

**Comment by markshanehokanson** [comment]
Will do, later this morning. Thanks for the quick response.

**Comment by Northness** [comment]
Economics, 3rd Edition.AAX uploaded.
[Economics, 3rd Edition.txt](https://github.com/openaudible/openaudible/files/6069158/Economics.3rd.Edition.txt)

**Comment by markshanehokanson** [comment]
Deleted all of my AAX files, then uninstalled/reinstalled. Currently in the
process of converting newly downloaded AAX files, will report back with
details and any AAX files that failed .

**Comment by markshanehokanson** [comment]
Uninstall/reinstall, then redownloading AAX files seems to have fixed my
issue. Thank you for your time.

**Comment by openaudible** [comment]
Oh good. Its likely that just deleting the AAX and re-downloading the AAX using our app would do it. Maybe you downloaded from an android device and imported it into OpenAudible? I'll try to improve the error message. Thanks for the update.

**Comment by markshanehokanson** [comment]
That is exactly the case, ie I downloaded the AAX files from an android
device, then imported them. And you are also correct, re-downloading them
via Open audible seems to have resolved the issue.

Thanks for the quick response.
