### ISSUE TITLE
(Feature Request) Support Converting iTunes DRM Protected M4B Files to MP3

### ISSUE THREAD

**Issue by palomban** [openaudible/openaudible#569]
Audiobooks purchased from iTunes are DRM protected M4B files. It would be a great feature if OpenAudible could convert these files to the MP3 format. Hopefully, this is not outside the scope of this project.

![image](https://user-images.githubusercontent.com/74151076/108798936-f4d56980-755c-11eb-8f3f-31830346a8cf.png)

**Comment by openaudible** [comment]
No real plans. But will be marked as a feature request.
