### ISSUE TITLE
GitHub repository out of date

### ISSUE THREAD

**Issue by TomW1605** [openaudible/openaudible#57]
the latest release on your website is 1.2.5, the latest release on GitHub is 1.2.3 and the source code on GitHub is 1.1.8. can you please update github particular the source code. i was hoping to compile this myself to try and fix some issues i am having (see issue #56) but was disappointed when this got me a completely different version of the program.

**Comment by openaudible** [comment]
Hi Tom,

We have been considering closing the source code and haven't pushed the last few versions. 

With regard to the other issue, the UI bug you found is probably in the code you checked out.. and I described the steps that will be taken to fix it for the next release. 

Thanks,

**Comment by TomW1605** [comment]
in that case can i suggest you put a few lines at the top of the readme just to let people know
