### ISSUE TITLE
[Feature] Single folder for Library and Web page

### ISSUE THREAD

**Issue by LanceMcCarthy** [openaudible/openaudible#571]
Currently, I am forced to have different root folders for the auto-generated web and the rest of the normal OpenAudible content.

This is a waste of a lot of disk space due to having to have a duplicate copy of the mp3 folder  (I have hundreds of books, currently at ~100 GB)

What is the technical limitation of not sharing the same folder for both? They both seem to have an `./mp3/` folder with the same content. The only difference I see is the web folder has the js and html assets

![image](https://user-images.githubusercontent.com/3520532/109352818-66593480-7849-11eb-81d4-e8dfd7a89f39.png)

**Comment by openaudible** [comment]
Yes, we are working on that. Not sure when, but hopefully soon. Marked as feature request.
