### ISSUE TITLE
Beta 2.4.1.7

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#573]
Excellent Beta Version, works exactly as advertised!

I like the transparent view of the image and search boxes, great for long book lists.  

Is there any chance of extending this functionality to the first line of the book list so that the sort tags are also always available - not essential, but nice when the book list is very long?  

Also is there any way to make the images show when loaded "as the default page view"

Thanks

**Comment by openaudible** [comment]
Not easily. Someone gave out an idea about using a commercial html framework in another issue. Marking as feature request and possible duplicate. Thanks for the feedback!
