### ISSUE TITLE
Beta 2.4.1.7 - Differences between Chrome and Safari on Mac 11.2.2

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#575]
Names for Author and for Narrator are clickable hyperlinks on Chrome in the modal dialog and in the Image page and the non-image page:  In Safari, the items are not hyperlinks in the modal dialog, but are OK in the non-image and image page.  Why would this happen?

**Comment by openaudible** [comment]
I need an html guru. Might try to outsource thanks for the heads up.
