### ISSUE TITLE
Can you try again to send one of the aax files to the https://openaudible.org/check.html page?

### ISSUE THREAD

**Issue by Northness** [openaudible/openaudible#576]
Can you try again to send one of the aax files to the https://openaudible.org/check.html page?
Would love to solve.

_Originally posted by @openaudible in https://github.com/openaudible/openaudible/issues/568#issuecomment-788630399_

**Comment by Northness** [comment]
This is fro an issue that got closed before I had chance to upload.  I did anyway, but nor sure if it gets picked up if issue was closed.  Here is text file of what was uploaded:
[Economics, 3rd Edition.txt](https://github.com/openaudible/openaudible/files/6069172/Economics.3rd.Edition.txt)

**Comment by openaudible** [comment]
Got it. Looks like a bug. Will work on a fix for you and update you via previous issue.
