### ISSUE TITLE
Conversion Problem - First second after silence

### ISSUE THREAD

**Issue by Remigrator** [openaudible/openaudible#579]
Hello, I bought OpenAudible and had high hopes to get my ebooks to MP3 to listen to them from my MP3 Player. Wether I convert the AAX to MP3, M4A or M4B, in any version, even beta, I have the following issue which renders OpenAudible unusable to me:
Whenever there is a silence, a pause in the ebook audio, the first ~ 1 seconds of speech is then missing i.e. cut off somehow. Whenever the narrator speaks up again after a longer pause i.e. silence, the the audio resumes mid-sentence, as the first ~1 second is missing each time. While the narrator keeps on talking, it is all good, but after each silence the first 2-3 words are then missing i.e. cut off.

I am using Manjaro Linux but I also tried it on Ubuntu 20.04 on another PC with the same devastating result. Doesn't anyone else have this issue?

**Comment by mkb79** [comment]
That sounds really strange. If you had this issue on MP3 only, I had thought on an encoding problem. M4B, as far as I know, leaves the encoding untouched and removes the encryption only. On this files M4B and AAX quality are be same.

**Comment by openaudible** [comment]
Never heard of this. I suspect your player is having trouble with the file format. Can you move the converted file to another PC or try another audio player (like VLC) and report back? Audio on linux can be a challenge. And yes, ffmpeg does the conversion and the whole command line is written to the console so you can run the command yourself.. but likely its your ubuntu setup.

**Comment by openaudible** [comment]
Closing as not reproducible and unresponsive.

**Comment by maasdorp** [comment]
This is not a conversion problem, but actually a bluetooth speaker power-saving problem.
