### ISSUE TITLE
Sorting books by date

### ISSUE THREAD

**Issue by christgod** [openaudible/openaudible#58]
I tried to sort my books by date by clicking on the "Purchased" column, but apparently the dates are incorrectly handled as strings rather than dates:
![image](https://user-images.githubusercontent.com/5426008/48298929-e0711e00-e4c5-11e8-8720-e09b6893c7d5.png)

**Comment by openaudible** [comment]
What region are you in? (DE, CA, JP, etc.) It looks like we expected dates to be in a western format when we parse it from the web site.

**Comment by openaudible** [comment]
Should be fixed in the next release, 1.2.7.  Should be out soon.

**Comment by christgod** [comment]
The format was indeed Day.Month.Year (Germany).
I just checked and it is indeed fixed in 1.2.7. 
Thanks!

**Comment by christgod** [comment]
I think I was too quick to mark this as closes, I checked again and the sorting is off in 1.30:
![image](https://user-images.githubusercontent.com/5426008/50383356-4c909580-06b2-11e9-8f88-9df916992753.png)
it appears the date can't be parsed correctly, here is an example console output:
WARNUNG: Unable to parse audible date: 08-OCT-2007 region=DE

**Comment by TomW1605** [comment]
i had the same problem in my fork and eventually solved it by using the java builtin string.matches() to trial and error regular expression matches to find the original format then use SimpleDateFormat to convert it to a sortable format. my code can be found [here](https://github.com/TomW1605/openaudible/blob/0de3279ae93d7eaa745cdb14e5a8d5aefce0d403/src/main/java/org/openaudible/books/Book.java#L451) (if i have missed a date format or one is incorrectly guessed then let me know

**Comment by openaudible** [comment]
Hi Tom,

That's a nice way to do it.

I am worried if some regions use mm-dd and others use dd-mm but books may contain meta data that is in another format. How would I know I have a dd-mm vs. a mm-dd unless I specifically state I am pulling the data from meta vs. a web page. Its a bit of a mess. I wonder if I can set the browser to request en-US, would the dates be in an expected format? And then would the description be in english vs. DE? No idea.

**Comment by openaudible** [comment]
Posted 1.4. Please try again.. reopen if you see problems and or post a bug report.
