### ISSUE TITLE
Filenames are missing non utf8-chars after converting to mp3

### ISSUE THREAD

**Issue by Gallenkamp** [openaudible/openaudible#580]
Example filename is DieFlssevonLondonDiemagischenFlledesPeterGrant1_ep7.mp3  which is also the downloaded AAX filename.

Solution could be adding an option for creating the file names from UTF8 audio book title from books.json. That file is containing the correct spelling without missing characters any.

**Comment by openaudible** [comment]
Titles can be messy— long with illegal characters (:/\| etc).  There is a rename command under actions.  Will add as feature request.
