### ISSUE TITLE
v 2.3.5 - Windows - Typo when Cancelling Downloads

### ISSUE THREAD

**Issue by theonlymajortom** [openaudible/openaudible#581]
Hello.

I spotted a small typo in the dialogue box when cancelling the download queue in Version 2.3.5 for Windows.

When you click cancel the dialogue box says "Operation was caneled". Should be "cancelled"

This may have already been fixed in the beta with the new download method.

![Screenshot 2021-03-04 101457](https://user-images.githubusercontent.com/30875320/109948809-959cf500-7cd2-11eb-876d-f0a63194772f.png)

**Comment by openaudible** [comment]
Fixed for the next release. Also added to for internationalization.  Thank you!
