### ISSUE TITLE
Page load failed with error: Could not connect to the server.

### ISSUE THREAD

**Issue by smashedavocado** [openaudible/openaudible#583]
This message pops up: 'Page load failed with error: Could not connect to the server.' when trying to connect to https://www.audible.com/library

Controls > Connect to Audible > ( Running task) https://www.audible.com/library >  'Page load failed with error: Could not connect to the server.'
Have Audible blocked access to this version of OpenAudible 2.3.5? Anything else I might try?
Running Mac Catalina 10.15.7 on MacBook Pro

**Comment by openaudible** [comment]
Using a proxy or pihole? You can try the beta. OpenAudible.org/beta

**Comment by smashedavocado** [comment]
Thanks,  I tried the beta on it's own, but same issue. I should try a proxy?

**Comment by openaudible** [comment]
No, a poxy is not recommended. Try using a real browser like chrome. If that works, check the console and paste any errors or output.

**Comment by smashedavocado** [comment]
Login on Chrome is fine. Inside OA beta, click 'Connect to Audible' but it is greyed out.

**Comment by smashedavocado** [comment]
Alternatively I can download a book from Amazon website via Chrome then import the .aax file into OA.

**Comment by openaudible** [comment]
If connect to audible is grayed out, maybe already connected? Try “full library sync”

**Comment by smashedavocado** [comment]
A “full library sync” is working - thanks!

**Comment by openaudible** [comment]
Closing issue. Use version 2.4.1.7 or higher.
