### ISSUE TITLE
Convert to mp3 mono instead of stereo

### ISSUE THREAD

**Issue by jbbarnes77** [openaudible/openaudible#584]
I've tested the different quality levels for mp3 output. All produce stereo 22K files, only varying the bitrate.

Not a single book in my large collection needs stereo. Why double the size of the mp3 file unnecessarily? 

I can convert them individually (or in a batch script) to mono using ffmpeg, but why not include an option to make the output mono, thus dramatically reducing the mp3 size? This would be a welcome addition. Thanks.

**Comment by oboe45** [comment]
Sound quality of the AAX  recordings on the Audible site ranges from poor
to acceptable in almost all of my books. Conversion by the OA app produces
a much smaller m4a, m4b or mp3 file and the sound quality, to my ears, is
no worse than the original AAX.  The deciding issue for me is that M4b
conversion is very very fast and mp3 is painfully slow, so, I only use the
m4b conversion option.  I am sure that folks will say that my tolerance to
bad audio is not usual, but frankly, these are book files and the story
does not need to be audiophile quality and it never is!

**Comment by openaudible** [comment]
Trying to keep preference options minimal. If you’re low on disk space, use a lower mp3 quality. But we recommend using m4b whenever possible which incurs no loss of quality. Thank.

**Comment by openaudible** [comment]
There is a hack for creating mono. I haven't tried it.. but.. create a file called ffmpeg_args_mp3.txt in your openaudible settings directory. Put the following two lines in. 


```
-ac
1
```

Re-encode one mp3 and check for mono output.
