### ISSUE TITLE
Problem converting the file

### ISSUE THREAD

**Issue by omrpps** [openaudible/openaudible#585]
With the book loaded in the program's library, the following problem occurs when you try to convert the format. The books are from **audible spain**.

_
![Captura de pantalla (5)](https://user-images.githubusercontent.com/39309527/110602897-b78cf080-8186-11eb-85e7-f7cbc06d561a.png)
_

**Comment by openaudible** [comment]
Delete the aax file or move it and re-download it using OpenAudible. It is probably an axxc file or something downloaded from android or kindle.  

Will fix that UI issue and improve error message.
