### ISSUE TITLE
Access denied but license good

### ISSUE THREAD

**Issue by DKeast** [openaudible/openaudible#586]
![openaudable-error](https://user-images.githubusercontent.com/80432842/110715621-d8733700-81c2-11eb-977b-6cbf85630067.PNG)
_ get an access denied message when I open the program, but my license is valid, how do I fix this?

**Comment by openaudible** [comment]
That is a file that needs read write access by the account running OpenAudible. Maybe check that the file permissions are set right (and not owned by the Admin account instead of your account.) 
You could also try moving that file and have it recreated.

**Comment by DKeast** [comment]
Thanks I will try & figure that out.

**Comment by DKeast** [comment]
So I got a $12 version, it worked for a week, then stopped & said access denied, I did the troubleshooting steps but no luck. I saw that there was a $19 version & thought it might be more current so I uninstalled & installed the new one, still, access denied.  I have spent $31. on this already, not wanting to spend more. Hoping to fix it. I'm perfectly happy to have paid the $$ if I can only get it to work again.

**Comment by openaudible** [comment]
Hi,

I refunded the second order.  You get free updates for a year.  Make sure to use the first license and the second license got deleted automatically on the return. 

I'm not sure what happened. Maybe a firewall or anti-virus program? If you have an anti-virus program, make sure you allow OpenAudible to run. 

Quit OA. Then rename the OpenAudible directory at C:\Users\NAME\OpenAudible. 
Then re-launch OpenAudible. Hope fully it is able to create that directory again and run. If your anti-virus asks, be sure to allow running.

If that works, you can either re-download files.. or move files from the renamed OpenAudible directory..

**Comment by DKeast** [comment]
I will try this & let you know if I have any further issues & copy & send the errors to you.  One last thing, how do I find my first licence # ???
 Other than this issue I love the program, it lets me listen to books on old devices, I'm so happy you created it. 
Thank you so much, I really appreciate you.

**Comment by openaudible** [comment]
Good luck!
Check your email.. or visit:
https://openaudible.org/license

**Comment by openaudible** [comment]
Closing but feel free to re-open. This sounds like a misconfigured system or anti-virus program..
