### ISSUE TITLE
Site security

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#587]
For protection of the converted AAX files, s there a simple way to disable downloads of the m4a, m4b and/or mp3 files on the converted website?  Alternatively, or perhaps as an enhancement, could you include instructions how to password protect the generated site?  I have tried a number of times to incorporate a log in process for the site, but have been unable to make anything work!

**Comment by openaudible** [comment]
That depends on your web server, so you'll need to look up how to do that for Apache or whatever web server you use.
 
Just releasing the final version. Thanks for all your help.
