### ISSUE TITLE
New Version - attempt to update

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#588]
Loaded current beta - which works fine - did not get an update reminder - so I did  "Check for update" got this message on IMAC and on MacBook Pro:

Error checking for latest version. Check your firewall, try again later or check the web site!
	Error message: http error getting: https://openaudible.org/swt_version.json?platform=mac&version=2.4.1.7&mode=beta&bc=1006&mc=0&region=CA&id=1613086958569&uptime=182179&lo=en_US&build=2021-02-27&state=valid reason:Internal Server Error

iMac runs High Sierra 10.13.6 - MacBook runs Big Sur - Latest release.

Rebooted both systems - same result.

**Comment by oboe45** [comment]
I loaded the file anyway without the update reminder - download and install fine.  Ran the Full Library Sync, it found three books which were already in my list of books but I downloaded and converted them anyway - worked fine.  No complaints here - app works well as usual.  Thanks

**Comment by openaudible** [comment]
Fixed. Thank you. !!
