### ISSUE TITLE
Use a free signing certificate

### ISSUE THREAD

**Issue by flashcactus** [openaudible/openaudible#59]
A free code signing cert is better than none, and these are obtainable. Besides the obvious option of self-signing with a self-generated cert and trying to get it signed by someone trusted in the community (which might be tricky), there are options like [CAcert](cacert.org), which provide free community-rated certificates with a community-driven CA.

**Comment by openaudible** [comment]
Known issue. For now, check the MD5 sums for integrity and only download from openaudible.org or github releases.
