### ISSUE TITLE
Download error: No library record found for user.

### ISSUE THREAD

**Issue by NathanRenihan** [openaudible/openaudible#592]
This is my first time on GitHub and I don't know how this works but I just wanted to say that when I try and Download my audiobooks using your application it says download error: No library record found for user even though I'm logged into my account ?

**Comment by openaudible** [comment]
Usually that means the book is not purchased. Perhaps it was free, a podcast, or returned. You can verify by seeing if there is a “download” button next to the book when you view your library in the browser.

**Comment by NathanRenihan** [comment]
There’s isn’t a Download option even though I bought the book. I bought
other books aswell but there’s no download button next to them. On my phone
I can download them but I can’t on my computer ?

**Comment by openaudible** [comment]
The phone lets you download free books, podcasts, and other "all you can consume" items.. but only books that you purchase can be backed up by our app. If you have a book you purchased with a credit or money, you should be able to back it up.  (If it is a purchased book, feel free to send a bug report with the name of the book after doing a "full library sync" making sure you're logged into your account.

**Comment by embebe** [comment]
@NathanRenihan Did you solve this problem?

I have the problem with OpenAudible 3.0.2 for some time now that I can not download some audio books, which I bought, and get the "Download error. No Iibrary record found for user" error message instead...

**Comment by openaudible** [comment]
3.0.2 was released in 7/2021. A low-cost upgrade is recommended. Go to About menu: License... and click on the upgrade link to find out all the details.

**Comment by embebe** [comment]
> 3.0.2 was released in 7/2021. A low-cost upgrade is recommended. Go to About menu: License... and click on the upgrade link to find out all the details.

thank you!
If the paid upgrade solves this issue, I'll happily pay for it.  This was not clear for me so far and I feared that it could be a rare problem, which could also persist with the newer versions...
Thank you for the good work!

**Comment by embebe** [comment]
> 3.0.2 was released in 7/2021. A low-cost upgrade is recommended. Go to About menu: License... and click on the upgrade link to find out all the details.

p. s. the dialog which praises the new version 4.x.x does not say, that it also removes serious problems like this.
Maybe this was the reason, why I was reluctant to buy it...
It only said
>Lots of new features and improvements have been added to latest version.
>including new login method, new M4B tags, improved search, table sorting, 
>import/exporting, more titles can be downloaded. Upgrading is recommended.
>Find out about a free upgrade opportunity!
