### ISSUE TITLE
Merged File Titles and Disc Information

### ISSUE THREAD

**Issue by truckclancy** [openaudible/openaudible#594]
When merging, the output file's title and disc number tag is identical to the first file in that folder.
This often results in merged files having something like "Chapter 1" as the title, and being labeled disc 1 of x.

By default, merged files should strip disc info and have the titles either match the album tag or folder name.

**Comment by openaudible** [comment]
Can you give me a list of the book file names in the folder?

You should be able to rename the joined file after it is created. If the book has been imported into OpenAudible, select the book, Action: Rename Book.

**Comment by truckclancy** [comment]
The merged filename is okay (same as the folder name), but the book's title becomes Immorality Act, 1927 (first chapter's name) and OpenAudible cannot change book titles.

You can replicate this by splitting an Audible book with chapters and merging it back to compare their book title tags.

Born a Crime 01.m4b
Born a Crime 02.m4b
Born a Crime 03.m4b
Born a Crime 04.m4b
Born a Crime 05.m4b
Born a Crime 06.m4b
Born a Crime 07.m4b
Born a Crime 08.m4b
Born a Crime 09.m4b
Born a Crime 10.m4b
Born a Crime 11.m4b
Born a Crime 12.m4b
Born a Crime 13.m4b
Born a Crime 14.m4b
Born a Crime 15.m4b
Born a Crime 16.m4b
Born a Crime 17.m4b
Born a Crime 18.m4b
Born a Crime 19.m4b
Born a Crime 20.m4b
Born a Crime 21.m4b
Born a Crime 22.m4b

**Comment by openaudible** [comment]
Will check on the title tag. Also, will mark as a feature request to add basic tag editing to files. Not sure exactly how else I can make a fix to work in all cases.

**Comment by truckclancy** [comment]
Thank you!

I think the default assumption can be that you're joining all the files(chapters/parts) to make one m4b/mp3 book to import and the unique title and disc information from the first file shouldn't be used.

**Comment by openaudible** [comment]
For now, you may need to use a tag editor to update the tags. We'll try to add a feature that lets you manually change the meta data. We test this by splitting a book and then joining the parts back and at least with our tests it appears to keep everything correct. But with books from other sources, I'm sure there can be issues.

**Comment by RandmTask** [comment]
> Will check on the title tag. Also, will mark as a feature request to add basic tag editing to files. Not sure exactly how else I can make a fix to work in all cases.

That would be great!

**Comment by openaudible** [comment]
Yeah a basic tag editor would be needed. Not a bad idea if we get enough time and energy to make it happen. Marking as a known feature request.
