### ISSUE TITLE
Add Narrator as Composer Tag When Converting

### ISSUE THREAD

**Issue by truckclancy** [openaudible/openaudible#595]
When converting to M4B/MP3, is it possible to add the narrator to the composer tag instead of discarding it?

Since Inaudible has done this for so long, popular audiobook apps like Prologue look for that information: https://www.reddit.com/r/PrologueApp/wiki/index

id=©nrt, fk=**COMPOSER**, value=Dan Harris

**Comment by openaudible** [comment]
Great idea. Done for next release.

**Comment by openaudible** [comment]
OK.. Added to the beta if you wanted to test... https://openaudible.org/beta

**Comment by truckclancy** [comment]
Works great, thanks!

I assume there isn't an easy way to add this to already converted m4b so you'd have to re-convert?

**Comment by openaudible** [comment]
Glad to hear. No.. but converting from aax to m4b is pretty quick. Just delete all the m4b's and re-encode. thanks for the suggestion.
