### ISSUE TITLE
Unable to download books

### ISSUE THREAD

**Issue by Butterfly-Dragon** [openaudible/openaudible#597]
https://www.audible.com/pd/The-Man-in-the-Maze-Audiobook/B01MS1W5J4

https://www.audible.com/pd/Nightwings-Audiobook/B00K55F4YW

I am unable to download these 2 books, they are regularly bought on my account (not "gotten for a period") but on the account i do get a "remove" button where a "download" button should be... for "reasons".

**Comment by openaudible** [comment]
I believe that is a book that has become "included" as part of your subscription. So if you bought it, you needed to convert it to m4b as soon as possible. Now that it is included, it isn't something that can be downloaded. Sorry!

**Comment by Butterfly-Dragon** [comment]
> I believe that is a book that has become "included" as part of your subscription. So if you bought it, you needed to convert it to m4b as soon as possible. Now that it is included, it isn't something that can be downloaded. Sorry!

dammit! i bought it this morning. also: thanks!
