### ISSUE TITLE
heard this was stolen from another git and your charging for it

### ISSUE THREAD

**Issue by Xellerate005** [openaudible/openaudible#598]
bunch of thieves, stealing open source work and making others pay for it, everybody go to this website, its the original
https://github.com/KrumpetPirate/AAXtoMP3

**Comment by openaudible** [comment]
There is a misunderstanding going around.

We included the open source https://github.com/inAudible-NG/RainbowCrack-NG 
This repository had no license file, which makes the open source files "open source". 
We gave attribution and attempted to reach out to the author-- but he chose to remain anonymous.

When we heard he wasn't happy his software was being used commercially, we immediately removed it from our software. We did reach out to the author and cleared things up. But the misunderstanding is still "out there". The code in question was just one part of a larger set of problems OpenAudible attempts to solve. 

For the record, Open source software is routinely used in commercial software-- as long as it doesn't contain a license, such as GPL, that prohibits its use. 



And by all means, use a command line tool to convert your audiobook files.

**Comment by Skeen** [comment]
Could you clearify what you mean by:

'This repository had no license file, which makes the open source files "open source".'

Are you assuming the files were open-source by default, simply because the source code was available? - Having the source code available on github does NOT imply meeting the criteria to be called open-source.

**Comment by openaudible** [comment]
We made it right with the author as soon as we learned he added a license. He politely declined our offer of compensation. We are no longer using his code. I'm pretty sure the issue is resolved and the author is not holding a grudge against us.  The author has my contact info if he would like to reach me.

**Comment by Xellerate005** [comment]
If you check his website/github, the first things it says is that you stole it

**Comment by openaudible** [comment]
Maybe @inAudible-NG can answer for the record whether we are square, or if he wants a more public apology, compensation, or donation to his local animal shelter.

**Comment by JonathanTreffler** [comment]
No license file means closed source. Even if it is on github.

**Comment by openaudible** [comment]
@JonathanTreffler The description of the [github repo](https://github.com/inAudible-NG/RainbowCrack-NG) has always said: **"Free and open-source software to generate and use rainbow tables."** 

I think you mean that when a license isn't specified, commercial use is ambiguous and could lead to problems. A reasonable person could have interpreted their license as "free and open source". Adding a GPL license takes 2 seconds.  

When we learned they didn't like us using their code in a shareware product, we offered to work out a solution and ended up removing their code completely, which gave us better performance, smaller downloads, and a less complex product.

**Comment by JonathanTreffler** [comment]
I mean from a legal perspective. I am quite sure the only way it is legally allowed to use if the exact terms of the license are specified like in a LICENSE.md.

But i am not judging or accusing you, because you definitely didn't use it in bad faith and agreed to remove it
