### ISSUE TITLE
Missing Menu in AppImage & DEB

### ISSUE THREAD

**Issue by DOnTheRiverC** [openaudible/openaudible#599]
PopOS 20.04
AppImage and .deb install for V2..35 and v3.0 show no navigation/function menu for 'File Edit Controls Actions About'. There is simply just the Window Bar show OpenAdubile and then the search box. 
![OpenAudibleMissingFileMenu](https://user-images.githubusercontent.com/4481895/113482333-eae64500-94d0-11eb-8aef-16b631f52f36.png)

**Comment by openaudible** [comment]
What OS are you using? Do the command keys work? (Ctrl-e to open console?) any errors reported in console? We don’t have a good sense of which Linux variants are not compatible but you apparently have something not entirely compatible. Strange.

**Comment by openaudible** [comment]
Seems to be working for me. In fact, looks pretty good in dark mode!  
![pop_os](https://user-images.githubusercontent.com/30847528/114599844-7df94a80-9c48-11eb-9e54-8f2d3cd113b0.jpg)
This is the 3.0 AppImage. I used the latest PopOS on a fresh install.
