### ISSUE TITLE
downloading 3 files only / mapping issue with DE region Product IDs

### ISSUE THREAD

**Issue by drahdiwaberl** [openaudible/openaudible#60]
- windows 10 / openaudible 1.2.6
- connected to Region: DE
- preferences set to automatically convert to mp3

clicking "download all" starts download of 3 files, resulting in 3 aax/art/mp3 files  - all with 'DE' before the extension.

after that it stops with this:
![image](https://user-images.githubusercontent.com/3143680/48968190-f31e4380-efeb-11e8-88d7-b692c1beacf0.png)

the 3 converted got a green dot status icon.

nothing suspicious in console log.

quitting/restarting openaudible gives this:
![image](https://user-images.githubusercontent.com/3143680/48968255-22818000-efed-11e8-8c3b-1776a7f471a2.png)

.. so it still thinks it has to download all 67 files, although already having downloaded and converted 3.

in the list the 3 downloaded and converted show the same 'grey dot' stats icon as the rest now.

clicking one of them shows a product ID **without** the DE in the end (see above - the files i got are named with DE in the end)

**Comment by drahdiwaberl** [comment]
fwiw - this is what i get if i do a 'full sync' again:
![image](https://user-images.githubusercontent.com/3143680/48968615-557a4280-eff2-11e8-90a6-b4265e611e04.png)

(had started a single manual download in the meantime)

**Comment by openaudible** [comment]
Looking into that. Unexpected that the product ID has the DE suffix in some instances but not all... 
I can try to remove the suffix but unknown what that might break..  Will let you know here when a fix has been attempted.

**Comment by Treguard** [comment]
Exactly the same problem, but using UK Audiible. Symptom are exactly the same, and can only download three books. Also have the date sort problem in another thread, using UK style date with day/month/year format.

**Comment by openaudible** [comment]
Not sure why only three books would be downloaded. I think it has to do with the duplicated product ID's that add the region. 

We don't any developers in DE/UK.. Please visit this web page when this happens and submit a bug report:
https://openaudible.org/bugs.html

I think we have a fix for the date sorting and removal duplicate books due to the product id with and without the region code. But don't want to create a new update until I get a little more details.

**Comment by openaudible** [comment]
Posted a new version.. 1.2.7 Need feedback. See above note about how to submit a bug report if needed. 
Thanks!

**Comment by openaudible** [comment]
Posted a new version 1.3.0... Please send a bug report from the help menu if not working and open a new ticket if you're still seeing this.
