### ISSUE TITLE
Files will not convert to MP3 on macOS Catalina v10.15.7

### ISSUE THREAD

**Issue by GreSta64** [openaudible/openaudible#600]
Hi,
I am a new customer with a paid and valid license. Running on a Mac mini with 2.5 GHz processor and 10 GB RAM. 
I changed my library to a 2TB external hard disk so I have enough disk for my books. I have downloaded all of my 169 books and am now trying to convert them to MP3 but nothing is being converted. I can see processes running using Instrument, there are 3 ffmpeg processes using over 88.7% CPU. Nothing else is running on this Mac. 

Regards 
Greg Stahl

**Comment by openaudible** [comment]
Usually you just need to give it some time. You should also see the number of "MP3's" increase in the library status panel. 

To show the status of conversion, click on the "converting" in the status panel to see which files are being converted. Then you can click on any of of the "converting" files and see the status in the book info panel. It should show a progress indication-- in hours and minutes of the book that is being converted. 

In the unlikely event that you have found a bug or other problem, feel free to send a bug report from the help menu referencing this issue number 600. (Send a report after waiting a good 10 minutes of conversion so we have some logs.)

Lastly, check that your external disk path is correct and the drive isn't corrupt. If ffmpeg isn't able to write to the disk (or there is an anti-virus app that prevents writing), that could cause issues.
