### ISSUE TITLE
Failed conversion from AAX to any format

### ISSUE THREAD

**Issue by horaki** [openaudible/openaudible#601]
Hello,

I downloaded an AAX audiobook within Open Audible and tried to convert it, but the conversion fails.  See the console output and screenshot attached.

The audibook is a proper audiobook that I purchased on Audible.

Your help is much appreciated!

Best,
– horaki
![Capture](https://user-images.githubusercontent.com/63412207/113820183-59810800-9748-11eb-8743-e5caaf9622ab.PNG)
[Console.txt](https://github.com/openaudible/openaudible/files/6269399/Console.txt)

**Comment by openaudible** [comment]
This is almost identical to #568 Will PM you.

**Comment by openaudible** [comment]
I think this is an AAXC file that is not currently convertible. The activation bytes are 01000000 which seems to be an indication that this is an unusual file format. I'll do a little more exploring.. but it doesn't look promising at the moment!

**Comment by mkb79** [comment]
You can run ffmpeg -i FILENAME to check encryption format. Aaxc files have a major Brand Label „aaxc“!
Am 8. Apr. 2021, 19:28 +0200 schrieb openaudible ***@***.***>:

**Comment by openaudible** [comment]
Strange that the user has two activation bytes--a valid looking one and this one that resolves to a code consisting of 0's and 1's.

Only the great courses can't be backed up. 

Output from ffmpeg: 

```
.\ffmpeg -i "Economics3rdEdition_ep6.AAX"
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000203f2526580] [aax] file checksum == 009362dc37344ce2a53f0ae410f4441e5cd915b5
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000203f2526580] [aax] activation_bytes option is missing!
[mov,mp4,m4a,3gp,3g2,mj2 @ 00000203f2526580] stream 0, timescale not set
[aac @ 00000203f3dc1640] invalid band type
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from 'Economics3rdEdition_ep6.AAX':
  Metadata:
    major_brand     : aax
    minor_version   : 1
    compatible_brands: aax M4B mp42isom
    creation_time   : 2021-04-07T20:09:24.000000Z
    genre           : Audiobook
    title           : Economics, 3rd Edition
    artist          : Timothy Taylor, The Great Courses
    album_artist    : Timothy Taylor, The Great Courses
    album           : Economics, 3rd Edition
    comment         : These thirty-six lectures will help you think about and discuss economic issues that affect you and the nation every day....
    copyright       : ©2005 The Teaching Company, LLC (P)2005 The Great Courses
```

Then with activation bytes obtained from:  https://audible-tools.github.io/


```
.\ffmpeg -activation_bytes 01000000 -i "Economics3rdEdition_ep6.AAX"

[mov,mp4,m4a,3gp,3g2,mj2 @ 0000024e69046980] [aax] file checksum == 009362dc37344ce2a53f0ae410f4441e5cd915b5
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000024e69046980] [aax] error in drm blob decryption!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0000024e69046980] error reading header
Economics3rdEdition_ep6.AAX: Invalid data found when processing input

    date            : 2013
  Duration: 18:36:44.04, start: 0.000000, bitrate: 64 kb/s
```

Seems like this is a special case AAX file.

**Comment by openaudible** [comment]
Unfortunately need to close as "Unable to fix". I did put a warning note in the log.
