### ISSUE TITLE
Authentication connection error

### ISSUE THREAD

**Issue by kanguru-au** [openaudible/openaudible#602]
Can't connect to the Audible UK site using a legacy audible account (not an Amazon account). I can connect to both Audible.com and Audible.com.au without a problem. OpenAudible fails, popping up an error window in the browser titled "Error Registering Connection" with contents "Unable to register a device." I couldn't find those strings in the source code, so maybe they're coming from Audible.co.uk? (By the way, the label of this field "Description:" in the bug report should be aligned with the top of the text entry box, not the middle).

**Comment by openaudible** [comment]
Can you try the beta 3.0.1 version? I think that has been resolved.
https://openaudible.org/beta

**Comment by kanguru-au** [comment]
Yes indeed, 3.0.1 fixed it. Thank you <3
