### ISSUE TITLE
RPM release seems corrupt.

### ISSUE THREAD

**Issue by jtagcat** [openaudible/openaudible#603]
```
Running transaction check
error: ~/Downloads/OpenAudible_3.0_x86_64.rpm: invalid signature tag Archivesize (1046)
Error: error reading package header: 'OpenAudible_3.0_x86_64.rpm'
```

Fedora 33

**Comment by openaudible** [comment]
The OpenAudible rpm is an unsigned archive. What command are you using to check the integrity of the file?
A basic test is:
```
wget https://openaudible.org/latest/OpenAudible_x86_64.rpm
rpm -qpR OpenAudible_x86_64.rpm
yum -y localinstall OpenAudible_x86_64.rpm
```
With the RPM, a java 12 (or higher) JRE (or JDK) is required.

**Comment by jtagcat** [comment]
The output in the parent comment is for yum/dnf.

```
rpm -qpR ./OpenAudible_3.0_x86_64.rpm
error: ./OpenAudible_3.0_x86_64.rpm: invalid signature tag Archivesize (1046)
error: ./OpenAudible_3.0_x86_64.rpm: not an rpm package (or package manifest)
```

**Comment by openaudible** [comment]
I wasn't able to reproduce this. What OS are you using? Can you reproduce it in Docker?
By the way, my OpenAudible.rpm is 84747233 bytes (ls -l)


Dockerfile
```
FROM centos:latest
WORKDIR /oa
RUN yum -y install wget
RUN wget https://openaudible.org/latest/OpenAudible_x86_64.rpm
RUN rpm -qpR OpenAudible_x86_64.rpm
RUN yum -y localinstall OpenAudible_x86_64.rpm
RUN yum list installed | grep OpenAud
ENTRYPOINT ["/bin/bash"]
```

then build:
```
docker build .
```
Should show a successful installation. (minus the java 12 install.)

**Comment by jtagcat** [comment]
> By the way, my OpenAudible.rpm is 84747233 bytes (ls -l).

The one I downloaded from releases is 8474**4680**, but it matches the md5sum in releases.

> Also, are you able to install the rpm? Maybe re-download it?

No, as I mentioned before. Re-downloaded, cheksummed, etc.

> What OS are you using?

Fedora 33.

Changing CentOS to f33 worked in the Dockerfile. I even copied the file from the container to host, yet still the same problem.

I didn't find anything regarding this problem, I guess I'll have to go to the mailing lists.

**Comment by jtagcat** [comment]
I've replicated the issue on a second computer with Fedora 33. VM install in progress.

**Comment by openaudible** [comment]
Any chance you can reproduce using docker? Should just change the FROM line to a different OS.

**Comment by openaudible** [comment]
Also interested in output from verbose rpm:

rpm -qvvpR ./OpenAudible_3.0_x86_64.rpm

**Comment by openaudible** [comment]
This is either a bug in install4j or rpm. Submitting some bug reports.  Here is the docker file on how to test it:
```
# Simple Dockerfile to demonstrate rpm bug with latest rpm or install4j
# To test, save this as "Dockerfile" and run:
# docker build . -t testrpm
# to Debug, docker run -it testrpm

FROM fedora:latest
WORKDIR /test
RUN yum -y install wget
RUN wget https://download-gcdn.ej-technologies.com/install4j/install4j_linux-x64_9_0_1.rpm
RUN echo "rpm -qvvpR install4j_linux-x64_9_0_1.rpm" > test.sh && chmod +x test.sh
RUN ./test.sh;exit 0
ENTRYPOINT ["/bin/bash"]
```

**Comment by openaudible** [comment]
work-around is 
yum downgrade rpm

**Comment by jtagcat** [comment]
Thanks for the time and effort put in to debugging.

**Comment by openaudible** [comment]
You bet. I also let install4j know so they can follow along. It very well may be a bug in their code.. but a recent change in the rpm code is definitely responsible for breaking the otherwise good archives. 

Did you try running yum downgrade rpm ?

**Comment by jtagcat** [comment]
Yup, I got OAudible running again, and filed yet another issue <3

**Comment by openaudible** [comment]
Install4j has an updated installer that fixes this issue. Tested and fixed in our beta: https://openaudible.org/beta
Fast bug fix.
