### ISSUE TITLE
Can not login using built-in browser

### ISSUE THREAD

**Issue by sebastianschauenburg** [openaudible/openaudible#604]
When I try to login using the built-in browser, it hangs (I have to kill -9 all openaudible processes). Sometimes I can login 1 time, but when I get to the 2nd stage (getting a CAPTCHA), I can't fill in the CAPTCHA response, because it hangs. Currently it already hangs when I try to enter my username and password the first time around.

Edit: tried using the 3.0 release and 3.0.1 beta releases

Error message shown:

> INFO: Connection state changed to Disconnected from Not_Connected
> (OpenAudible:1954391): GLib-GObject-WARNING **: 11:21:03.955: cannot register existing type 'GtkWidget'
> (OpenAudible:1954391): GLib-GObject-CRITICAL **: 11:21:03.955: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
> (OpenAudible:1954391): GLib-GObject-WARNING **: 11:21:03.955: cannot register existing type 'GtkBuildable'
> (OpenAudible:1954391): GLib-GObject-CRITICAL **: 11:21:03.955: g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed
> (OpenAudible:1954391): GLib-CRITICAL **: 11:21:03.955: g_once_init_leave: assertion 'result != 0' failed
> (OpenAudible:1954391): GLib-GObject-CRITICAL **: 11:21:03.955: g_type_add_interface_static: assertion 'G_TYPE_IS_INSTANTIATABLE (instance_type)' failed
> (OpenAudible:1954391): GLib-GObject-CRITICAL **: 11:21:03.955: g_type_register_static: assertion 'parent_type > 0' failed

My system is running Ubuntu 20.10 with [Awesome WM](https://awesomewm.org/).  

Steps to reproduce:

- Connect to Audible
- Select UK 
- Select "Keep me logged in"
- Try to type your username and password

**Comment by openaudible** [comment]
Google: 

swt browser g_type_interface_add_prerequisite: assertion 'G_TYPE_IS_INTERFACE (interface_type)' failed

From https://www.eclipse.org/forums/index.php/t/796060/

Maybe set env SWT_GTK3=0



Or change glib version
https://bbs.archlinux.org/viewtopic.php?id=162320

**Comment by sebastianschauenburg** [comment]
Thanks for the pointers.

Tried setting the SWT variable before (retried it again), but that unfortunately doesn't change anything. I used this commandline to start the application by the way:

> export SWT_GTK3=0 ; jre/bin/java -cp "openaudible-jar-with-dependencies.jar:org.eclipse.swt.gtk.linux.x86_64.jar" -Dfile.encoding=UTF-8 org.openaudible.desktop.Application

The installed version of "libglib2.0-0:amd64" is "2.66.1-2ubuntu0.2", which can't easily be replaced, since it's part of the operating system. Luckily it's way newer than the 2.34 version mentioned in that archlinux thread.

**Comment by openaudible** [comment]
Bummer. The SWT jar with browser support cause a number of unfortunate bugs that are a little bit beyond our control. 

The only thing I can recommend is to upgrade or downgrade the org.eclipse.swt.gtk.linux.x86_64.jar file from:
https://mvnrepository.com/artifact/org.eclipse.platform/org.eclipse.swt.gtk.linux.x86_64

Click on a version, then download the link for the jar. save it as swt.jar 
Then modify the command line to use the new jar:

```jre/bin/java -cp "openaudible-jar-with-dependencies.jar:swt.jar" -Dfile.encoding=UTF-8 org.openaudible.desktop.Application```

repeat for as many as you're willing to try. 

If you find a version that works, let me know.

**Comment by sebastianschauenburg** [comment]
thank you for your reply and information. Tried several jar's, no dice. If I ever find a working solution, I'll let you know. In the meantime, feel free to close this issue.

**Comment by kprestel** [comment]
I'm seeing this same issue. Running on manjaro.

**Comment by openaudible** [comment]
Never heard of manjaro. Maybe see if installing eclipse IDE from eclipse.org will fix or repair any dependencies?
Sorry.. we can only use and include the latest libraries and hope they work with as many OS's as possible.

**Comment by ahokinson** [comment]
I am experiencing this on Ubuntu 20.04. This should probably be re-opened. As much as it doesn't affect other OSes, I'd consider this an ongoing issue with Linux. Is there a workaround for getting a token or something that could help?

**Comment by ahokinson** [comment]
Disregard, this is a working fix:

https://github.com/openaudible/openaudible/issues/757#issuecomment-971133361

**Comment by openaudible** [comment]
@ahokinson Good to hear. We're trying to figure out a way to get a helpful message about installing the missing software if it isn't installed but don't have a great way to do that yet.

Just to reiterate, the fix is: 

```
sudo apt install gstreamer1.0-plugins-bad 
```
