### ISSUE TITLE
Failed to move from download to converting phase

### ISSUE THREAD

**Issue by stephanmax** [openaudible/openaudible#606]
I am having the following behavior for a very recent book (it seems to be a one-off case, other books work fine):

1. I download the book
2. All works fine, I can see the AAX file in the `aax` folder
3. UI tells me that it is "Ready to download", there is no visual indicator that the download has finished successfully (green circle)
4. OpenAudible does not attempt to convert it
5. If I try to re-download, the UI correctly tells me `moveFile error:dst file already exists`

Is that a bug? Is that connected to other issues raised here regarding Audible changing their encoding? Is there an easy workaround to trigger the conversion to m4b differently?

Thanks in advance!

**Comment by openaudible** [comment]
Hmm. If it says ready to download it doesn’t seem to know about the aax file for some reason. Maybe delete or move the aax and try again. Keep an eye on the console and or submit a bug if it doesn’t work the next time.

**Comment by stephanmax** [comment]
Huh! Thanks for mentioning the console, I was not ware of that. I am seeing the following warning:

```
WARNING: product id mismatch for Die Märchen von Beedle dem Bard [BK_POTR_000544DE] and Die Märchen von Beedle dem Bard file [BK_POTR_000544]
```

Does that keep OpenAudible from converting?

**Comment by openaudible** [comment]
Yeah, that's a problem somewhere. Looks like you have two copies of the same book but with different product ID's-- one is the german version (ends with DE.) You may already have the file downloaded and converted and OA is trying to avoid a duplicate. If you want both, you may need to delete one and convert the other.

**Comment by stephanmax** [comment]
Hm, yes, that’s what the warning states, but I don’t. Neither in the file system nor in the OpenAudible UI. Do you have any hints how to debug this?

**Comment by openaudible** [comment]
Try typing the title (or author) into the search bar and see if it lists two books-- one converted and the other not converted. Typically you can "Ignore" one of the books if they're indeed the same. (But if one is German, the other English and you want both, its possible you might have to delete one or the other temporarily. If you need to, you can send a bug report from the about menu, but I don't have much time to dig into this week.

**Comment by stephanmax** [comment]
No worries, there’s no rush at all. Let’s keep this issue closed and I’ll monitor further.
FYI: There is definitely just one book, both in my Audible and OpenAudible library. Weird... Maybe a hiccup with Audible’s pre-order mechanism or something, dunno. Will try to dig deeper myself.
Thanks so much for your help so far, I really appreciate this piece of software 👍

**Comment by MichaelSch** [comment]
Hi there,

I have to add myself to this issue: Same book, same console message.

BR Michael

**Comment by stephanmax** [comment]
Hi @MichaelSch, not sure if this is a feasible workaround for you, but I managed to convert this particular book manually with [AAXtoMP3](https://github.com/KrumpetPirate/AAXtoMP3).

**Comment by MichaelSch** [comment]
Thanks, I managed to convert the book manually as well.

**Comment by bporima** [comment]
Same issue, same audiobook. Will try AAXtoMP3 next. @stephanmax could you pls. post the command you used, much appreciated!

In the end it would be interesting to know what caused this issue on audibles side, so far this is the only audiobook (from around 100 I bought on audible) that causes this problem.

**Comment by stephanmax** [comment]
> Same issue, same audiobook. Will try AAXtoMP3 next. @stephanmax could you pls. post the command you used, much appreciated!

Sure thing, @bporima. I downloaded the repo, went into the directory and called `./AAXtoMP3 -e:m4b -A <your authcode> <path to the aax file>`. The crucial part, really, is the authcode, everything else depends on your preferences/favorite format/potential tagging you do afterwards. For me it was important to get a chaptered m4b file that I then can tag in a post-step. You can obtain your authcode from `<your OpenAudible folder>/keys.json`. It’s the 8-char value of the only key-value pair in there.

You might have to install some software packages (e.g. to make chapter extraction work), but the output of the AACtoMP3 was super helpful. For me on MacOS, installing needed tools via Homebrew’s `brew install` worked like a charm.

> In the end it would be interesting to know what caused this issue on audibles side, so far this is the only audiobook (from around 100 I bought on audible) that causes this problem.

It *would be* interesting to get to the bottom of this... wondering if this is an issue that we will be seeing more in the future.

**Comment by bporima** [comment]
Thanks a lot, @stephanmax, works like charm. I have the same preference like you, chaptered m4b files, and also work on MacOSX. I put those files onto my Plex server (in a "Music" library) and access them via the app "Prologue", and the whole toolchain from OpenAudible to Prologue delivers so satisfying results and works so smoothly, its a dream. Sorry for diverting. :-)

**Comment by stephanmax** [comment]
Don’t worry—I am totally with you. I have the exact same setup and love it 😄
