### ISSUE TITLE
android player not recognizing m4b/a conversion from ep7 format

### ISSUE THREAD

**Issue by Highlander44** [openaudible/openaudible#607]
I've noticed that when openaudible converts an aax file with ending "ep7" to either m4a/m4b format, not all (android) players recognize the play time. Hours zero. The file will play, but will reset to beginning whenever the playback is paused.  No chapter markers recognized.

**Comment by openaudible** [comment]
Unfortunate. That is either a bug in ffmpeg or the m4b player, but probably the player. But ffprobe on the file should show the "duration" in hours,minutes,seconds. 

Any chance you can file a bug with the android player developer and link to it here? Don't even know what the android player would be called.

**Comment by Highlander44** [comment]
Thanks - that was my suspicion. The android players that don't recognize the ep7.aax conversion to m4a/m4b are mAbook / Plaidy / MortPlayer, and a few others. The ones that did recognize the file chapters and time were "Raise" and "Play Books Lite".

Converting an ep6.aax audible file to m4b (or m4a) does not produce a zeroed file. It seems to work properly; so does converting the file to .mp3 format.

**Comment by openaudible** [comment]
I would file a bug with them if you can— I assume these files play fine in VLC or other players.

**Comment by coolaj86** [comment]
Out of curiosity... what does ep6 and ep7 mean in the context of audiobook files?

None of the LLMs seem to know, and search brings me here as a top result.

**Comment by openaudible** [comment]
Not sure. Episode? 
Haven't seen it personally.

**Comment by coolaj86** [comment]
Either `_ep6` or `_ep7` is the part of the filename of every file audiobook that I've ever downloaded from Audible since the first time I used it in 2016.

For example:
```
FREETheFutureofaRadicalPrice_ep6.aax
BabylonsAshesTheExpanseBook6_ep6.aax
```

If I login and download through OpenAudible (which I did just now to see if it were the same), however, it appears to use the title of the book rather than the `Content-Disposition` header's filename.

```
HTTP/2 200
content-type: audio/vnd.audible.aax
content-length: 585865395
server: Server
date: Wed, 23 Jul 2025 04:50:32 GMT
x-amz-rid: 3698GD1ZMMCMQM1KSH2F
content-disposition: attachment; filename=CibolaBurnTheExpanseBook4_ep6.aax <<---------------------------
x-content-type-options: nosniff
vary: Content-Type,Accept-Encoding,User-Agent
strict-transport-security: max-age=47474747; includeSubDomains; preload
x-cache: Miss from cloudfront
via: 1.1 e3489666ede6afb2a043e3d0d3f2825e.cloudfront.net (CloudFront)
x-amz-cf-pop: LAX54-P3
x-amz-cf-id: LYUmkDlIAobIBQqkQ-azSbMclJ6IzYJgZNQqmC_uRrJqktc4IlKRpg==
```

**Comment by openaudible** [comment]
Ah. Not sure then! Maybe someone who knows will see this and reply.

**Comment by coolaj86** [comment]
Digging a little deeper, even though GPT and Grok hallucinated bogus answers, when asked for sources I got to these:

> They are format specifiers. They indicate the general quality level.
> - ep6: 22.05kHz, 63kbps bitrate
> - ep7: 44.1kHz, usually 126kbps bitrate
- https://www.reddit.com/r/audible/comments/1itucf3/ep6aax/

> Audbile still offers rubish quality even now. Its EP6 is equal to FM Radio quality - 22kHz stereo sampling, while the best offered quality (only some books) is EP7 which offers CD quality (44100 stereo sampling)
- https://goodereader.com/blog/electronic-readers/audible-moving-to-enhanced-format-for-audiobooks
