### ISSUE TITLE
Attempting to Store Info for Audible Plus Titles

### ISSUE THREAD

**Issue by 1234shai** [openaudible/openaudible#609]
I have over 200 Audible Plus titles.  I know that I can't download them as they are not purchased.  Is there a way to stop OpenAudible from attempting to search and download them while retaining them and their information in my OpenAudible library?  It'd be like "ignore" for these titles, except that the titles would be retained.

**Comment by openaudible** [comment]
No plans at the moment. But auto- add to ignore list might work. Marking as feature request. A little backlogged.
