### ISSUE TITLE
validation incorrect on license entry field

### ISSUE THREAD

**Issue by lschierer** [openaudible/openaudible#611]
the license code field only accepts 12 characters, but the license code (including dashes) is 14.  It is validating that the code patches the format XXXX-XXXX-XXXX but only has room for the code without the dashes.

**Comment by lschierer** [comment]
Interestingly, if I click on the word "invalid" next to license, it takes me to a different box that has an input field that _does_ take the license key correctly.

**Comment by openaudible** [comment]
Seems strange. Can you take a screenshot? License dialog hasn’t changed in a long time. First report.

**Comment by openaudible** [comment]
Feel free to send screenshot or more details.

**Comment by lschierer** [comment]
Sorry I did not get back sooner, I have been unable to reproduce since restarting openaudible, so this is correctly closed.
