### ISSUE TITLE
Support for multiple audible accounts would be nice

### ISSUE THREAD

**Issue by blurfl** [openaudible/openaudible#612]
A comment a while back touched on this -
["We're also working on other ways to make managing multiple libraries better. But its a big change and we're trying to get it right the first time."](https://github.com/openaudible/openaudible/issues/497#issuecomment-740799627)

The winds of change in the project have settled down, is there hope this feature could be next up? Happy to help test 😁...

**Comment by openaudible** [comment]
Good reminder. It’s top of the list after a few little items.
