### ISSUE TITLE
chapters are repeated on download to mps

### ISSUE THREAD

**Issue by suelyntorg** [openaudible/openaudible#617]
On downloading mp3 to my Creative Zen and also my GoGear Ariaz, chapters/sections are repeated.  This causes the narration to continue past the reported duration of the audible book.  For example, if the reported duration is 10 hours, 5 minutes, the story is only half done at that point.  The narration continues to then end of the story.  however, if you pause or leave the book, it resumes at the reported end duration.   The Audible book plays normally on my computer.  I have deleted and re-loaded books.  This occur on all books I have  checked.

**Comment by openaudible** [comment]
We just take the chapter data from the aax audible book and use ffmpeg to copy it to mp3. 

Can you see if the chapters are correct with VLC? (Maybe it is your player?) 

Can you try with m4b?
