### ISSUE TITLE
Does the database distinguish narrator to differentiate files?

### ISSUE THREAD

**Issue by stormneedle** [openaudible/openaudible#618]
A series I have downloaded has been re-recorded with a new narrator. If I wanted to download the new recordings and keep the old ones, it seems like I would have to back up the current recording, delete the current recording, then do an update to get the new version of the book. Then, if desired, I could add the old version using "import books" from the backup

But I don't know if the narrator is significant to the database, so if I do the above steps, would importing the old version overwrite the new version I'd downloaded?

**Comment by openaudible** [comment]
No, we use the product ID and ASIN for unique identifier. The file name may get changed for the second one by adding a "2" to the end, but you can rename the files from the Action menu.
