### ISSUE TITLE
Audible Plus items in library are not downloading 

### ISSUE THREAD

**Issue by MarkOfColor** [openaudible/openaudible#619]
With the recent addition of audible plus titles several books are now in my library but won't download. I get the error "Download error: No Library Record Found for user" This occurs on several titles using v3.0

**Comment by openaudible** [comment]
Those are currently not supported. You can only back up purchased books. Podcasts and all you can consume books are not allowed. OpenAudible is supposed to hide audible plus books that it won't be able to back up.
