### ISSUE TITLE
Series Links do not work.

### ISSUE THREAD

**Issue by mrjester888** [openaudible/openaudible#620]
The series links do not work.  Everyone I try returns a "Shucks. This product isn't available." e.g. https://www.audible.com/pd/Ready-Player-One-Audiobook/B08CM7ZZ11

**Comment by openaudible** [comment]
Interesting. Looks like audible changed series links from:
https://www.audible.com/pd/Ready-Player-One-Audiobooks/B08CM7ZZ11
to 
https://www.audible.com/series/Ready-Player-One-Audiobooks/B08CM7ZZ11

But the data we collect is still showing /pd/

Will fix in 3.0.1. 
Thanks for finding that!

**Comment by openaudible** [comment]
OK, fixed in version 3.0.1 released today. Let me know if you find anything else!
