### ISSUE TITLE
MP3 Encoder quality selection 

### ISSUE THREAD

**Issue by yhete** [openaudible/openaudible#621]
Hello

Changes to MP3 Encoder levels don't appear to affect the bitrate/size of a file. 4-0 all result in the same file size and bitrate.

**Comment by openaudible** [comment]
Good catch. Will fix in 3.0.1.

For earlier versions, you need to restart OpenAudible after changing the quality setting. 

Thank you for finding that!

**Comment by openaudible** [comment]
OK, fixed in version 3.0.1 released today. Let me know if you find anything else!

**Comment by yhete** [comment]
Just a further question. What do the enocer values equate to? Are they equivalent to the ffmpeg or lame values?

**Comment by openaudible** [comment]
The values are ffmpeg mp3 qscale values (0 through 9) :
https://trac.ffmpeg.org/wiki/Encode/MP3

LAME Bitrate Overview
lame option | Average kbit/s | Bitrate range kbit/s | ffmpeg option
-V 0 | 245 | 220-260 | -q:a 0 (NB this is VBR from 22 to 26 KB/s)
-V 1 | 225 | 190-250 | -q:a 1
-V 2 | 190 | 170-210 | -q:a 2
-V 3 | 175 | 150-195 | -q:a 3
-V 4 | 165 | 140-185 | -q:a 4
-V 5 | 130 | 120-150 | -q:a 5
-V 6 | 115 | 100-130 | -q:a 6
-V 7 | 100 | 80-120 | -q:a 7
-V 8 | 85 | 70-105 | -q:a 8
-V 9 | 65 | 45-85 | -q:a 9

**Comment by ryanpcmcquen** [comment]
@openaudible, can you please add a 'highest' next to 0, and a 'lowest' next to 9. The scale is not obvious. Some people may think 9 is higher quality.

**Comment by openaudible** [comment]
@ryanpcmcquen Added for next version! Also added 4 - Recommended Quality

**Comment by ryanpcmcquen** [comment]
Thank you!

**Comment by openaudible** [comment]
Added feature of showing Max, recommended and minimum quality to latest beta: https://openaudible.org/beta
