### ISSUE TITLE
ALL books got re-converted after upgrade from 2.3.5 to 3.0.1

### ISSUE THREAD

**Issue by wwalker** [openaudible/openaudible#623]
2.3.5 had converted all my books.  These already converted books are in:
```
~/OpenAudible/m4a/*.m4a.
```

I upgraded to 3.0.1 today.  Wondered why my system load is so high...

ALL my books are being converted again... The newly converted books are in:
```
~/OpenAudible/M4A/*.m4a
```

```
@  $ for i in w*/{aax,m4a,M4A}; do du -sm $i; done
287690  working/aax
281914  web/m4a
281914  working/m4a
209179  working/M4A
```

It's not quite finished, but here's what I see right now:
```
@  $ for i in w*/{aax,m4a,M4A}; do echo -ne "$i:\t"; ls $i | wc -l; done
working/aax:    721
web/m4a:        719
working/m4a:    719
working/M4A:    533
```

**Comment by openaudible** [comment]
This is the first report, so I think your M4A directory got renamed to m4a some time in the past... and the linux file system is case sensitive. It is possible we had a buggy version at some point that wrote to a lowercase aax,m4a, etc.. but I didn't think so. 
Sorry for the trouble. 

As an aside, we are recommending switching to M4B, as we think we solved the m4b file size limit.
