### ISSUE TITLE
2 copies of every recording

### ISSUE THREAD

**Issue by wwalker** [openaudible/openaudible#624]
When OA coverts an AAX file (to say M4A), the new file is in `~/OA/working/bookName.m4a`; then it copies the file to `~/OA/web/bookName.m4a` .

Could it either:

* hard link the file instead of copying
OR
* remove the file from `~/OA/working` after the copy is complete?
  * maybe creating a "marker" file in working so that it doesn't recovert the file in the future

**Comment by openaudible** [comment]
Yes. That is super annoying. We are trying to come up with a good solution. I like the idea of just allowing us to save the books to the web directory. Will figure something out.

**Comment by wwalker** [comment]
Thanks!

**Comment by Puddl36lum** [comment]
I don't recall this being an issue in earlier version -- i only noticed this issue when i upgraded to the latest version.

**Comment by openaudible** [comment]
Unfortunately that behavior is present in all versions... We are working on a transition to a "books" directory that will hold the books and allow the web pages to work using that copy.. but didn't get it in the 3.0 release. Its complicated now that there are so many people using the current system we are trying not to break things.

**Comment by openaudible** [comment]
Closing as known feature request.. and duplicate. Will keep working on a fix.
