### ISSUE TITLE
Demo Limitation?

### ISSUE THREAD

**Issue by weswitt** [openaudible/openaudible#625]
Is there a list of disabled feature for the demo license?  I did a library sync with the demo version and it does not seem to sync my entire library.  It seems only sync 60 books.  Is this a demo limitation?

**Comment by openaudible** [comment]
Only books you purchased can be backed up. You may have audible plus or free books that are not being shown.

**Comment by openaudible** [comment]
The full version will only convert or export files it shows in the demo.
