### ISSUE TITLE
Enormous Libraries

### ISSUE THREAD

**Issue by rnbwpnt** [openaudible/openaudible#627]
Is there a way to restrict the size of a library download? For example, to only 5000 books or so. OpenAudible crashes thus:

Error refreshing library. http error getting: https://api.audible.com/1.0/library? <etc indicating it gets to page 100 and dies>

The library in question is over 12,000 titles. It doesn't surprise me that this is an issue; even Audible's clients can't handle a library of this size.

Is there any option in OpenAudible that will help, or could one be added?

**Comment by rnbwpnt** [comment]
I was unable to use the debug script because I got an eclipse crash, so I set OpenAudible.vmoptions to -Xmx16G and I got the same failure at 100 pages. The machine has 32gb physical RAM installed. (Linux Mint 20.1.)

For purposes of this issue, by the way, I am absolutely not concerned about "slow." I'm only concerned about "doesn't crash."

Looking at this, is this just an API error because (again) Amazon is stupid and can't handle customers like me?

![Screenshot from 2021-05-12 00-40-15](https://user-images.githubusercontent.com/5416023/117924295-225bc480-b2bb-11eb-857e-7a65dad737c9.png)

**Comment by openaudible** [comment]
Yeah, that is a bug or limitation of the API. Have you sent a bug report yet after it fails from the About Menu? Maybe @mkb79 knows?

**Comment by openaudible** [comment]
I think the fix would be to allow larger records per page. Will implement a quick fix.

**Comment by rnbwpnt** [comment]
Sent a bug report.

**Comment by openaudible** [comment]
Posted a possible fix. https://openaudible.org/beta
It will fail the first time, but should work the second time. (It will notice it got to page 100, and double the number of books per request.) Let me know if 3.0.1.2 works.

**Comment by rnbwpnt** [comment]
Negative. Still happens both with an immediate retry, and after shutting down and restarting the software.

**Comment by openaudible** [comment]
Check your settings.json file and see if there is something that says:
  "libraryPerPage": 100
and set that to 500 and save it. Then restart the app. 
settings.json file can be found by going to the Settings, and Show Preferences. 

Also, you can check to see how many books it is getting with each request and see if it 500 so..  Also check to see if the error still happens at 100 items. 


-

**Comment by rnbwpnt** [comment]
New bug report sent, so you can look inside.

Negative: This time, with libraryPerPage set to 500, it crashed on page 21, which means again after 10,000 books. So the issue isn't the number of pages (or at least, not at that threshold), it's the number of books.

(BTW, thank you for your help! I know I'm an edge case.)

![Screen Shot 2021-05-12 at 19 41 57](https://user-images.githubusercontent.com/5416023/118061320-59cd7e00-b35a-11eb-8ef2-7b6d47326645.png)

**Comment by openaudible** [comment]
Unfortunate.
Does your library show up in full on iPhone and or Android?

**Comment by rnbwpnt** [comment]
Alas, no. The library is so large that Audible isn't very interested in digging into it. My assumption is that it just runs the RAM out on the phone (even a top of the line S21 has only 8g, and a iPhone 12 Pro Max has only 6g). I have four times the amount of RAM on my Linux desktop, and that's not even counting virtual memory, so I'd hoped that constraint would be eased. My solution to the mobile apps being crashy is to just not go into the library if I can avoid it.

The problems I'm trying to solve are:

- Automating downloads: Downloading hundreds of files via the website makes me want to rip out my eyeballs
- Creating a searchable or browsable directory of titles: There's no effective way to browse titles with a library this large. Unless I know exactly what I want to listen to and that it's already in my library, browsing is a miserable, unworkable mess.
- (less important) Rip to m4b: Obviously this is a core function but I could do it with a competing product if I needed to. That doesn't bother me.

Processing time is not a constraint. My time operating the tool IS a constraint. Thus, my interest in OpenAudible.

**Comment by openaudible** [comment]
I assume the bug is the same. Let support know they haven’t tested their software with libraries exceeding exactly 10000 books. 

I do hope you’re a legitimate user and buyer of books and not a pirate.

**Comment by rnbwpnt** [comment]
The only way to do it from their mobile apps is to search by author or by title. This means that the only way to browse is on the website, a hundred at a time with the attendant slow performance that causes. If I don't already know what I want to listen to, I can't browse and find something that strikes me as interesting. This is the major problem I'm trying to solve.

And to answer your previous question, yes, they're legit. They're frequently bought at 1.99 on sale, or otherwise super cheap. They're not the freebies or the streaming-only stuff. These are AAX downloadable items. I'm a professional driver, and while my collection it very, very large, I also have pretty much endless amounts of time to listen.

**Comment by openaudible** [comment]
Fixed in beta.
