### ISSUE TITLE
No Library Record Found for user

### ISSUE THREAD

**Issue by dnr18lol** [openaudible/openaudible#632]
Hi, 

I just downloaded this to try it before purchase it. I'm a trial user yet. I connected my account and synced my library but when I try to download them a error message displays: "No Library Record Found for user".  I tried to download the android app and it syncs and downloads all the books, so they are in my library. My region is ES (audible.es).

How can I solve this issue? 

Thanks.

**Comment by openaudible** [comment]
You can get that error if the book is "free", a podcast, or if you returned the book. Try a "Quick Library Sync" and see if you get any errors.. and try again. If still not working, send a bug report from the About menu after trying to download the book.

**Comment by dnr18lol** [comment]
After a Quick Sync: "Your library seems up to date!". FYI, in the JSON, the download link looks like this:
`https://cds.audible.es/download?asin=8445010220&cust_id=vhkAb9vwhI54Tl7ejv6WPvpYcGYlkiXOTw1FN0waPGxLhsyQH9ah3MTwAqLCjQ&codec=LC_128_44100_stereo&source=audible_iPhone&type=AUDI`

**Comment by openaudible** [comment]
If you log into audible using the OpenAudible browser and navigate to that book https://www.audible.es/pd/8445010220 , there needs to be a "Download" button next to the title. If there is, click on it and it should be imported into your OA library. It should also say that it is "in your library".

**Comment by dnr18lol** [comment]
That button doesn't seem to exist. Here's a screenshot of the browser:
![image](https://user-images.githubusercontent.com/76540378/119185598-2cc64d00-ba77-11eb-8d6d-7e0804ab6a4b.png)

**Comment by openaudible** [comment]
I'm not sure why.. Some books may not be downloadable. I'm sorry that happened. It looks like that book is only playable in the Audible App and online.

**Comment by timsayshey** [comment]
Same issue here. I can't download any Audible Plus book that I add to my library. Unfortunate. Maybe in the future OpenAudible will add a workaround for these titles. Most of my books are "Plus" titles that I can't download.

**Comment by openaudible** [comment]
Yeah, Audible makes it a lot easier to back up books you've purchased. They don't want you to back up books that you're getting for free or that you're "borrowing." It's unfortunate.. but that's the way it currently is.

**Comment by timsayshey** [comment]
Yeah, right now the only way to download these books would be to come up with some way to capture the data as it streams to the browser and try to convert it to an m4b file. I'll just stick with their painful web interface for now. Cool project though. Thanks

**Comment by dnr18lol** [comment]
FYI: I made an US account and the system is different to the Spanish. In the US version you got credits but not in the Spanish . I could download audiobooks with the US account using the app. I think you must "own" the book to be available in your library records.

**Comment by gdudek** [comment]
Some titles are probably only available in the newer AACX format, notably including the free titles mentioned earlier in this issue thread.  Note that I don't actually use OpenAudible myself, but this error is what I would expect in such cases.

**Comment by AndrewHows** [comment]
I can't comment on this exact case, because I can't read Spanish. But some titles, even full books, are available for free with the subscription. On the English site, they have an "included" badge. You can also purchase them by clicking on the "More Options" button (the grey one, on the bottom of the set of three buttons on right) at which point Open Audible downloads them correctly. I guess buying them guarantees access, even if they're later removed from the free inclusions.
