### ISSUE TITLE
unable to log into audible

### ISSUE THREAD

**Issue by badlydrawnwoman** [openaudible/openaudible#633]
Hello, I'd appreciate some input on my issue please. 

I used OpenAudible for a month (and bought a license) and it's been great! However, after upgrading to 3.0.1 it stopped refreshing. I logged out of audible and tried to re-log in and I get to the login page, I type my email and pass and it just keeps saying that my info is wrong (it's definitely the correct pass)... 

I'm not sure what to do. 

I'm using a macOS Big Sur version 11.3.1 (20E241)

How can I solve this? Or, is there a way I can download the previous version of OpenAudible?

**Comment by openaudible** [comment]
Strange. Maybe reset your password? Make sure the legacy button is not checked if you’re using an email. 

Old releases are available here: https://github.com/openaudible/OpenAudible/releases
