### ISSUE TITLE
AAX Not Being Removed

### ISSUE THREAD

**Issue by rnbwpnt** [openaudible/openaudible#634]
- Download a book
- Convert to M4B
- Create a web page
- Copies of book appear in m4b (expected), web/m4b (expected), AND aax (unexpected)

Can I at least manually delete the cruft in aax, after it's been converted?

**Comment by openaudible** [comment]
Yes, ok to manually delete all aax files after converting.

**Comment by openaudible** [comment]
Now an option to delete the aax automatically. (in latest beta)
