### ISSUE TITLE
No MP3 conversion possible [URGENT]

### ISSUE THREAD

**Issue by PhilippV229** [openaudible/openaudible#635]
Hi,
I just upgraded to the OpenAudible license but am not able to convert _Hard Sell: The Evolution of a Viagra Salesman_ to an MP3 file.

When I downloaded it, it only showed me the option to convert to M4B, which I did.

The attached screenshot shows how the options currently look like. Could you please tell me if there's a way to get the MP3 version as well? **It's urgent**.

PS: I have no coding expertise at all.

Thanks a lot!

Philipp

<img width="503" alt="Screenshot 2021-05-22 at 14 01 21" src="https://user-images.githubusercontent.com/84625328/119225770-33e86c00-bb06-11eb-8057-9977ede1f69a.png">

**Comment by openaudible** [comment]
Yes, it was already converted to m4b. Which should be playable in most things. To get the MP3, switch the preferences to output MP3 in the main preferences (Edit Menu: Preferences)
Then Convert to MP3 will be enabled.
