### ISSUE TITLE
Bandwidth Control

### ISSUE THREAD

**Issue by rnbwpnt** [openaudible/openaudible#636]
Platforms: Mac, Linux
Version: 3.0.1.3b

Is there a method to:
- Limit the number of download threads (currently three), OR
- Limit the total bandwidth take?

I'm on a 30mbit connection, and doing a multi-book download with OA chews up my bandwidth so badly that a) failures are common and b) nothing else on my network can communicate either. Shutting down OA, or downloading one at a time, cures these problems. It looks to me from the console that the issue is DNS failures, which is entirely bandwidth, since I use Google's 8.8.8.8 and 8.8.4.4 and don't have trouble when OA isn't running.

As you're aware,  I I have a huge library. In a recent attempt to download ~1000 books, approximately 350 failed in this way.

If not, feature request: Ability to limit bandwidth use, thread count, or (preferably) both.  Speed is less an issue than reliability and  ability to continue to use my pipe when I'm home.

I've sent a bug report (would prefer not to post console in public) that should contain the log. If you need a full console, please respond and I will email one privately.

Thank you!

**Comment by blurfl** [comment]
I had a similar issue, to combat it I changed "concurrentDownloads" in "settings.json" from the default of 3 to 1. That solved it for me.

**Comment by openaudible** [comment]
3 concurrent should not be a problem, and isn't for most users. Nor should DNS queries fail. Copy and paste the IOException. Does re-trying to download them work? I suspect another problem somewhere. Proxy server? fast.com test? Take a look at network and cpu utilization as well. 

@blurfl is correct. Edit the settings.json file, which you can find in the settings by clicking on the "Show Preferences" then edit (carefully) with a text editor. Restart OA and the concurrent downloads should be changed.
