### ISSUE TITLE
[Feature] Folders for output files

### ISSUE THREAD

**Issue by AndrewHows** [openaudible/openaudible#637]
Is it possible to configure OpenAudio to output its mp3/m4b files in anything but a flat everything-in-one-folder structure? Ideally, something like `/<author>/<series>/book.mp3` would be great.

**Comment by openaudible** [comment]
Its a common feature request. On the feature request list. No time estimate. The problem is some authors are a long list of names, some names contain illegal characters, and its really easy to spend a lot of time building it and it can still break things.
