### ISSUE TITLE
Can't Convert files, option greyed out on Mac OS 11.4

### ISSUE THREAD

**Issue by piratesedge** [openaudible/openaudible#639]
Can't seem to convert books at all in OpenAudible on Mac OS, seems to have grayed out over time with an update, I've tried using the 3.0.1.3beta but still the same result on another machine. 

Please see attached screenshots.

<img width="791" alt="Screen Shot 2021-05-29 at 6 03 08 pm" src="https://user-images.githubusercontent.com/15115163/120063076-c362c180-c0a8-11eb-899c-a0ede98d6a2b.png">

<img width="784" alt="Screen Shot 2021-05-29 at 6 04 47 pm" src="https://user-images.githubusercontent.com/15115163/120063114-ee4d1580-c0a8-11eb-885d-115164604864.png">

Have also tried clicked the Convert All to M4B option under the Control menu above, still won't convert anything.

Please kindly review and advise.

**Comment by openaudible** [comment]
That is an unusual edge case. You have an MP3 version but not the AAX version. So converting to m4b is not currently possible, as it would degrade the audio quality.. so we don't currently have a way to do that. Not sure why the AAX file is missing.. maybe it never had one? 
This is something we could add, but we try to keep things simple and "mp3" is usually compatible with most things... and don't like to lose audio quality.
