### ISSUE TITLE
Download Link - Should Start Download and Does Not

### ISSUE THREAD

**Issue by 1234shai** [openaudible/openaudible#64]
Okay, so I have used the program for awhile but had to reinstall as I got a new computer.  Things have moved around but I think I put it back as it was.  I also refreshed the entire library.

PRoblem is that I open it up to sync my library, and it tells me to check for the audible download manager, and this I did though it thinks there are a lot of files that need to be downloaded that already were downloaded.  It doesn't see the new books I purchased, just the ones that I had from before.  

Second test you've recommended is to open the browser and attempt to download, but as it shouldn't, it brings me to a page about listening to my book rather than downloading.  Something's wrong, clearly.

Your information windows doesn't provide advice on what to do if a download doesn't start.  I can't find other known problems in the list that provide guidance here.  Any ideas?

**Comment by openaudible** [comment]
You may need to copy the aax and mp3 files you already converted into the new location.. Check the prefs. 
If it brings you to the page about downloading books, you need to change your audible settings. 
Audible: -> Account Details -> Update Settings
Toggle the check box that says Software Verification Check for Audible Download Manager
