### ISSUE TITLE
Additional information for series and the number in the series

### ISSUE THREAD

**Issue by BambamSchmidt** [openaudible/openaudible#640]
I suggest to add the series name and the book number into the book meta data.

These information should be filled, when a book is imported.
When a series is specified, the book name for MP3 output shoud be "Series #ofBook - Title [#ofChapter]".

Examples for series:
https://www.audible.co.uk/search?keywords=Jack+Ryan&ref=a_cat_Myste_t1_header_search
or
https://www.audible.co.uk/search?keywords=harry+potter&ref=a_search_t1_header_search

**Comment by openaudible** [comment]
We don't currently collect much series info.. but will look at it more. This also falls into the category of custom file names based on meta data. 

Marking as feature request. Thank you.
