### ISSUE TITLE
Split Books has wrong "Chapters"

### ISSUE THREAD

**Issue by smccandl** [openaudible/openaudible#642]
I have several books that when I "Split Books" the files created do not match the chapters played on Audible. Here is an Example.

https://www.audible.com/pd/The-Beginning-of-the-End-Audiobook/B00A4FRB5S

On Audible there are 87 Chapters...

Opening Credits 00:00:35
Entry 1 00:02:36
Entry 2 00:01:46
Entry 3 00:01:16
Entry 4 00:05:02
Entry 5 00:01:21
Entry 6 00:03:34
Entry 7 00:02:28
Entry 8 00:00:26
Entry 9 00:02:52
Entry 10 00:00:53
..........

When "Split Book" with OpenAudible 3.0.1 I get 34 Chapters...

Chapter 1 00:19:08
Chapter 2 00:18:55
Chapter 3 00:17:22
..........

**Comment by openaudible** [comment]
You can select that book and do a Action menu: Book report to look at the meta data that is included in each audio file (aax and m4b/mp3) and see what it says for chapter data. We just use whatever is encoded in the book-- it can be wrong sometimes. But as far as we know, if the data is correct, the splitting works correctly. If there are 84 chapters shown  in the metadata, there should be 84 "parts".

**Comment by smccandl** [comment]
Thanks for the quick reply. 2 more questions. Where does the "Meta Data" come from. Can it be altered before I run "Split Book" the Meta data is wrong for this book.

**Comment by openaudible** [comment]
Meta data comes from Audible and cannot be changed. You could report it to audible that you think the chapter data is wrong.
Unable to fix.
