### ISSUE TITLE
OpenAudible with Mac M1 processor?

### ISSUE THREAD

**Issue by openaudible** [openaudible/openaudible#643]
Got a report conversion isn't working on M1 processors. Can anyone verify or test this?
If you run into a problem, a bug report would be appreciated.

**Comment by rnbwpnt** [comment]
Not confirmed. Works fine on an M1 Mac Mini.

**Comment by openaudible** [comment]
Thank you very much!

**Comment by openaudible** [comment]
Created a native build for M1 processors in 3.4 and higher, FYI.
