### ISSUE TITLE
Option to convert to MP3 not available

### ISSUE THREAD

**Issue by rosieorosie** [openaudible/openaudible#646]
I need to convert my Audible books to MP3 rather than MP4 but OpenAudible automatically downloaded it t MP4. I deleted the book and downloaded it again, but the same thing happened when I tried to convert it - I was not given any option to choose MP3, it automatically converted it to MP4. I am now unable to play the book on my MP3 device.

**Comment by openaudible** [comment]
Go to Edit Menu: Preferences (ctrl-, or cmd-, if you're on a Mac) and change the output format to MP3. 
We now default to M4B for the fastest and best audio quality. But it is easy to change.
