### ISSUE TITLE
Ubuntu 20.04

### ISSUE THREAD

**Issue by airtac** [openaudible/openaudible#647]
Every time your browser  open to the web it lockup.  I had to open this page with chrome just to add this bug.
I do have a License my email is (a i r t a c@a i r t a c . s i t e)  

You have a great program here please keep up the great work.

**Comment by openaudible** [comment]
OA should be compatible with 20.04. Make sure your system is up to date. Do you see errors in the log window?

I did a quick test using Docker using this method:
https://dev.to/manishfoodtechs/full-desktop-in-docker-5c3n

And I know I have some 20.04 users. So not sure. sudo apt upgrade?

**Comment by airtac** [comment]
OA started working right after I reboot my system.   Something I did not what to do at the time.   

Thanks for the reply
