### ISSUE TITLE
Add CBR MP3 option?

### ISSUE THREAD

**Issue by ryanpcmcquen** [openaudible/openaudible#648]
Some apps have trouble with variable bit rate MP3s, namely Prologue for iOS (which is fantastic for audiobooks). Would you consider adding a constant bit rate option?

**Comment by openaudible** [comment]
I can look at it.. but it isn't a priority. We're encouraging everyone to use M4B for the best audio quality. Marking as feature request.

**Comment by ryanpcmcquen** [comment]
Thanks! I wish Plex supported M4B.

**Comment by openaudible** [comment]
This has been addressed in the latest beta:
https://openaudible.org/beta
(Under prefs, you'll need to check "CBR", and re-encode)

**Comment by ryanpcmcquen** [comment]
Thank you so much!

**Comment by openaudible** [comment]
You bet! Let me know if it helps.
