### ISSUE TITLE
OpenAudible Modified to support Premium features

### ISSUE THREAD

**Issue by Ashesh3** [openaudible/openaudible#649]
Hello, as the license permits me to modify the software and create derivatives.

I am uploading a patched version of OpenAudible which has all the paid / premium features unlocked. 
It supports conversion and does not need a license, say, kind of similar to a crack but in this case just a modification.

- Removed need for a license
- Allows conversion with chapters
- Works offline (does not contact openaudible servers at all)
- Totally Free!

Version Modded : 3.0.1 (Windows Only)

Thank you for making this amazing software! But shifting from OSS to Paywall with extreme restrictions forced me to create this for others who might need this.

I encourage everyone to support the developers for working on this but at the same time I ask the developers to at least allow the software to be usable in demo mode, like allow 1-2 conversions instead of having zero functionality in demo.

Links :
- https://anonfiles.com/b6M6Pfzdue/TotallyOpenAudible_zip
- https://www104.zippyshare.com/v/30lpS4A9/file.html
- https://t.me/ashsec_files/2

**Comment by PwrSrg** [comment]
@Ashesh3 - You **ROCK**!  **THANK YOU** for this.

I was thinking the exact same thing when I found this software, and was very confused, especially with the name **OPEN**audible.  WHY was it called **OPEN**audible when there was **nothing** "**_open_**" about it?!?

So thank you again for your amazing contribution!

**Comment by kouki31** [comment]
Thanks for your work.
PS i have installe pay version and log in amazon, i see i need to pay...
and i found yours, i download and i run it, i don't need to relog in amazon ^^
againe very good work a all peapole work on this.

**Comment by jdbancal** [comment]
Awesome, thanks a lot @Ashesh3 for looking into this!
May I ask whether you would be kind enough to share openly the corresponding code in the form of a fork? This way, people on other operating systems like me can also enjoy this open feature?

**Comment by openaudible** [comment]
anonfiles.com and www.verified-apps.com are malware sites. 

It is highly doubtful you'll get a working copy using this method and you may end up with who knows what virus. 

Open means we let you Open your audible files. We were open source, but spent too much time and effort and got almost no donations.

**Comment by TheHiddenCats** [comment]
> anonfiles.com and [www.verified-apps.com](http://www.verified-apps.com) are malware sites.
> 
> It is highly doubtful you'll get a working copy using this method and you may end up with who knows what virus.
> 
> Open means we let you Open your audible files. We were open source, but spent too much time and effort and got almost no donations.

Anonfiles allows users to upload files just like Mega, Google Drive ,Mediafire, etc. One cool thing about this is that it allows users to upload files anonymously. It's real. No phone number and no email required. Just only user name and password required 

This website is totally safe. But i dont know about the file you are trying to download. If you trust the uploader, then you can download it and scan it offline.

verified-apps.com is not even mentioned in the OP

**Comment by openaudible** [comment]
I tried to download his file. 2 of 3 links were dead. One wanted me to register. Another downloaded a file that redirected to the verified-apps.com, which people wrote about having to uninstall their adware. 
If anyone has a copy they want to send me or knows if this crack works, let me know. But download and install at your own risk.
