### ISSUE TITLE
Audiobooks are stored multiple times (4x)

### ISSUE THREAD

**Issue by kbabioch** [openaudible/openaudible#651]
I have ~ 280 or so books in my library. I'm using OpenAudible to download and convert them into M4A, as it seems to be the most feature-rich file format (chapters, artwork, etc.).

After downloading and converting my books, it seems that I have no up to four copies of them. Instead of storing ~75 GB of data, I need to store 300 GB. I can understand that it might make sense to keep the original data (+ the converted ones), but why is it stored in addition to that also in `books` and `web`?

```
14M     ./tmp
75G     ./web
76G     ./aax
13M     ./art
0       ./mp3
75G     ./books
75G     ./M4A
300G    .
```

My suggestion:

- Add option to remove original file format (AAX) when converting is done (i.e. `Keep original file format after conversion`)
- Only keep data once (+ original data, if configured).

**Comment by rnbwpnt** [comment]
aax can be removed once you've converted, and they're put in books.

**Comment by kbabioch** [comment]
Then this should happen automatically. I don't want to delete files, which are managed by an application. Even with those files deleted, I still have some more copies around (`web`, etc.).

**Comment by openaudible** [comment]
We're in the process of getting rid of mp3,m4b,m4a and web directories. All will be moved to a "books" directory that you can define for your library. We're also working on the naming convention, so you can store files in directories like "author" or genre or file type. But it has been a slow transition and we want to try to not break things for existing users. 

aax files will remain, but will probably create a way to delete them automatically.. but sometimes we want to allow users to re-encode the aax file if we or the user decides to change something.

**Comment by RandmTask** [comment]
> aax files will remain, but will probably create a way to delete them automatically.. but sometimes we want to allow users to re-encode the aax file if we or the user decides to change something.

This would probably be an edge case if they want to reencode and most users would prefer the extra space. They still have the opportunity to redownload the file or disable an auto-delete feature in Preferences.

+1 for deleting AAX automatically!
