### ISSUE TITLE
Add Chapter Number to tag and file name when a audio file is split

### ISSUE THREAD

**Issue by archdeac0n** [openaudible/openaudible#652]
Please could you change the tag title of the split audio files to include the chapter number. This means then when it is being played in Plex it is possible to remember which chapter you have got to.

**Comment by openaudible** [comment]
Good suggestion. I don't see why not.

**Comment by openaudible** [comment]
I looked into this.. It isn't an easy fix. We allow splitting of random files, and we don't always have access to the title that is used in the meta data. We're going to pass on this for the moment.. Track number should be unique and say what the chapter number is.
