### ISSUE TITLE
Add Series data to file "Part of set" property

### ISSUE THREAD

**Issue by xoozoo** [openaudible/openaudible#653]
On the downloaded files a lot of the file property details are populated already.

Would it be possible to also populate "Part of set" property with the "BOOK_ELEM_SERIES_NAME"

**Comment by openaudible** [comment]
This is already done.
We have a field called "series_name" and series_link in the json and it is displayed in the GUI under "Audio Book Info".

**Comment by xoozoo** [comment]
Sorry, I wasn't clear - I mean in the file meta data in this field:
![image](https://user-images.githubusercontent.com/8396743/123707277-5d14be80-d861-11eb-9bee-479b61747045.png)

**Comment by openaudible** [comment]
Ohh. Great idea. Let me see if i can.

**Comment by openaudible** [comment]
As far as I can determine, this isn't something that can be set. If you can find an M4B tag editor that changes this field, please let me know and I'll try to get a sample file and look at what meta data is being set.
For now, I'm closing as "unable to implement".
