### ISSUE TITLE
Audible Plus Titles can not be downloaded

### ISSUE THREAD

**Issue by krypterro** [openaudible/openaudible#655]
Using Linux Mint 20 the application runs fine, and I can sync and download Audible titles, however, for some reason I can sync Audible Plus titles, but I can not download the actual audio files. I get the error below, Kill Baxter is the title in this case.

Download error: No Library Record Found for user. for Kill Baxter

Jun 14, 2021 1:07:09 PM org.openaudible.Audible jobCompleted
INFO: DownloadQueue completed:Kill Baxter Working.... 1 remain
Jun 14, 2021 1:07:09 PM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error downloading Kill Baxter: Download error:No Library Record Found for user. for Kill Baxter
Jun 14, 2021 1:07:09 PM org.openaudible.desktop.swt.manager.AudibleGUI getTaskString
WARNING: error downloading Kill Baxter: Download error:No Library Record Found for user. for Kill Baxter
Jun 14, 2021 1:11:52 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Diagnostics
Jun 14, 2021 1:11:52 PM org.openaudible.desktop.swt.manager.browser.AudibleBrowser setUrl
INFO: AudibleBrowser setURL: file:/home/krypterro/OpenAudible/tmp/diagnostics.html
Jun 14, 2021 1:12:39 PM org.openaudible.desktop.swt.manager.browser.AudibleBrowser setUrl
INFO: AudibleBrowser setURL: about:blank
Jun 14, 2021 1:12:43 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by openaudible** [comment]
Yes, we only can back up audiobooks that you purchase. Free books, podcasts, audible plus, romance series, etc, are not purchased and can't be backed up.

**Comment by openaudible** [comment]
This has been added to version 3.6.
