### ISSUE TITLE
License on multiple computers

### ISSUE THREAD

**Issue by ScotchNip** [openaudible/openaudible#656]
Hi,

I have searched but couldn't find an answer to this issue. I just bought a license for OpenAudible but I am wondering if I can use it on more than one computer. 

I just installed on my work computer (I work away from home) but when I get home I would like to use it on my personal computer. Is that possible with one license, or should I wait til I get home to activate?

Thanks to anyone who can answer.

**Comment by openaudible** [comment]
Yes no problem to use one license on multiple computers of any platform in a family. 

One license for up to 5 audible accounts. 

Please don’t share licenses outside a family. 

Thanks for your support.
