### ISSUE TITLE
Sync doesn't work, even though the Check for Audible Download Manager is checked

### ISSUE THREAD

**Issue by melenai** [openaudible/openaudible#66]
I used Openaudible on a different PC and it was working fine. Now I installed it on a new PC, connected it with my Audible account, which had the "Check for Audible Download Manager" already checked.
Any attempts to sync a library fail with the Audible account fail with the notification, that I must check the checkbox that's already checked.
I tried to un-check and re-check it. Tried to log out, and log back in. I even restarted the PC. Every time I have the same message.
Screens and a log file are in attachments.
![1](https://user-images.githubusercontent.com/45478380/49271482-23436780-f46e-11e8-82be-b28782f24a58.png)
[2.txt](https://github.com/openaudible/openaudible/files/2632236/2.txt)
![3](https://user-images.githubusercontent.com/45478380/49271483-23dbfe00-f46e-11e8-9c89-3e62d7274bde.png)

**Comment by melenai** [comment]
Update
After **unchecking** the checkbox and syncing again it started it synced fine.

**Comment by openaudible** [comment]
Thank you for the report! 
I think Audible changed the wording of the preferences... Now unchecked is required. 
I will update the dialog and try to add a help page.
