### ISSUE TITLE
Window & Column Size and Position

### ISSUE THREAD

**Issue by terabyte2007** [openaudible/openaudible#660]
Will not save window size and other parameters such as book title columns and etc. Would be nice if each time the program was loaded we would have to resize the window and resize all the columns which is a bit annoying. I don't know if this falls under the catagory as a bug but it would make the experience much better.

**Comment by openaudible** [comment]
Feature request. Thank you.

**Comment by openaudible** [comment]
Added for next release. May need to test on multiple monitors. ETA sometime in July.
