### ISSUE TITLE
Editing Fields

### ISSUE THREAD

**Issue by rnbwpnt** [openaudible/openaudible#661]
Is it possible to edit a single field, such as author? I apparently imported some stuff with the author and narrator reversed; to fix this I'll have to go dig out the original files I imported, re-process them and re-import them, after deleting the errors.

Would editing the json (sub-optimal but I could figure it out) be the best approach right now?

**Comment by openaudible** [comment]
Tag editing is a feature request. Editing the json is not recommended—but could work temporarily. Delete book, use 3rd party tag editor, Re-import the book.
