### ISSUE TITLE
Login Window Locking Up

### ISSUE THREAD

**Issue by rnbwpnt** [openaudible/openaudible#662]
- Controls -> Connect to Audible
- Select region
- Browser pops
- Email -> Begin entering email
- Browser window locks up
- If resized, window goes blank
- Refresh works, but lather, rince, repeat

Video attached.

https://user-images.githubusercontent.com/5416023/123125751-6a1f5100-d40e-11eb-8e42-86892a719d41.mp4

**Comment by openaudible** [comment]
Is this linux? Are errors showing in the console (CTRL-E) OA is not compatible with all linux flavors.. maybe try a different linux install or make sure your OS is up to date.

**Comment by rnbwpnt** [comment]
This may in fact have been a Linux issue, and at this time I'm unable to pull a console report (will do when I can get the machine sorted out). However, for the record of the ticket, I'm using Linux Mint 20.1, a Ubuntu derivative, with the 64-bit deb.
