### ISSUE TITLE
Dealing With Dupes In Web Directory

### ISSUE THREAD

**Issue by rnbwpnt** [openaudible/openaudible#663]
I know duplicated files in the web directory is a known issue that will be solved at some point.

Question on an interim fix on Linux:

Could I link the data directories in web to /dev/null so when the copy is made, the duplicated data files get dumped?

If I need to create a fully-functional webpage complete with downloads, I understand I'd need to undo this and recreate the webpage.

But would this work as an interim space-saving measure, for the technically-inclined?

**Comment by openaudible** [comment]
I doubt it.. I'm pretty sure we check to make sure everything is a writeable directory before starting.. But not sure.. Can't hurt to try.

**Comment by rnbwpnt** [comment]
How amusing. This configuration seems to work. When cover is linked to /dev/null OA complains; when m4b is linked, it doesn't. Since m4b is the big space hog, I'm happy for the moment. Thus:

```
rnbwpnt@hood:~/raid0/openaudible-web$ ls -la
total 940
drwxrwxr-x  3 rnbwpnt rnbwpnt   4096 Jul  6 23:08 .
drwxr-xr-x 10 rnbwpnt rnbwpnt   4096 Jul  5 21:08 ..
lrwxrwxrwx  1 rnbwpnt rnbwpnt      9 Jul  5 21:09 books -> /dev/null
-rw-rw-r--  1 rnbwpnt rnbwpnt 438272 Jul  6 20:58 books.json
drwxrwxr-x  2 rnbwpnt rnbwpnt 516096 Jul  6 23:33 cover
lrwxrwxrwx  1 rnbwpnt rnbwpnt      9 Jul  6 22:33 m4a -> /dev/null
lrwxrwxrwx  1 rnbwpnt rnbwpnt      9 Jul  6 22:32 m4b -> /dev/null
lrwxrwxrwx  1 rnbwpnt rnbwpnt      9 Jul  5 21:09 mp3 -> /dev/null
lrwxrwxrwx  1 rnbwpnt rnbwpnt      9 Jul  6 22:33 thumb -> /dev/null
rnbwpnt@hood:~/raid0/openaudible-web$ 
```

**Comment by openaudible** [comment]
Oh shoot, I just remembered there is a hidden feature that disables writing the audio files to the web directory:
Go to Preferences, show "Settings directory"
Open settings.json
change   "webPageIncludeMP3": true,  to   "webPageIncludeMP3": false,
And restart app and export web page.

**Comment by rnbwpnt** [comment]
Does that verb work for all formats, or only mp3? It's certainly more elegant than my solution, even if my solution is somewhat more ... inventive. :-)

**Comment by openaudible** [comment]
Yes. That feature was added when the only output format was mp3.
