### ISSUE TITLE
Ignoring Environment Variable

### ISSUE THREAD

**Issue by aloisgruber** [openaudible/openaudible#664]
OpenAudible ignores the environment Variable OPENAUDIBLE_HOME, still uses the default directory

**Comment by openaudible** [comment]
What OS?

**Comment by aloisgruber** [comment]
Windows 10 Pro Version 2004, Openaudible 3.0.1

**Comment by aloisgruber** [comment]
tried both with and without trailing \

**Comment by aloisgruber** [comment]
"run as administrator" is the same result

**Comment by aloisgruber** [comment]
no difference between system env var and user env var

**Comment by openaudible** [comment]
On Windows, rebooting is necessary. (Or maybe logging out and back in.)
1. Click PC
2. Right-click, select Properties
3. Click Advanced settings
4. Click Environment Variables...
5. Click New... (under user or system, depending on what you prefer.)
6. Select Directory (Will not include trailing slash \
7. Reboot
8. Launch OpenAudible and it should pick up the new directory.

Tested on Windows 10

**Comment by aloisgruber** [comment]
Did it exact this way, even including reboot, it is still ignored

**Comment by aloisgruber** [comment]
![image](https://user-images.githubusercontent.com/7318366/124556943-3514f480-de39-11eb-86ae-d080687ac111.png)

**Comment by openaudible** [comment]
Make sure the D:\FileStore\OpenAudible is read/writable.
When it starts up, the log window (CTRL-D) should say something like: (but mine will say openaudible\test_home and yours will say FileStore\OpenAudible )

```
Jul 06, 2021 2:28:07 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 3.0.1.4 for win32 swt 4940 jvm 14.0.2 file.encoding UTF-8
Jul 06, 2021 2:28:07 PM org.openaudible.Directories getOrCreateWorkingDir
INFO: Using variable OPENAUDIBLE_HOME=D:\openaudible\test_home
Jul 06, 2021 2:28:07 PM org.openaudible.Directories isValid
SEVERE: Not found:D:\openaudible\test_home\mp3
Jul 06, 2021 2:28:07 PM org.openaudible.Directories isValid
SEVERE: Not found:D:\openaudible\test_home\m4a
Jul 06, 2021 2:28:07 PM org.openaudible.Directories isValid
SEVERE: Not found:D:\openaudible\test_home\m4b
Jul 06, 2021 2:28:07 PM org.openaudible.Directories isValid
SEVERE: Not found:D:\openaudible\test_home\pdf
Jul 06, 2021 2:28:08 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 3.0.1.4
Jul 06, 2021 2:28:08 PM org.openaudible.Directories getPrefs
INFO: Loading D:\openaudible\test_home\settings.json exists=true size=482
```


You can leave a bug report from the About menu if you want.

**Comment by aloisgruber** [comment]
I tried the debug_win.bat and got this on my screen. It is reading the env var but somehow , Users have full access on directory 

C:\Program Files\OpenAudible>.\jre\bin\java -ea -Xmx2048m "-Dfile.encoding=UTF8" -classpath "openaudible-jar-with-dependencies.jar;org.eclipse.swt.win32.win32.x86_64.jar" org.openaudible.desktop.Application
Juli 07, 2021 11:57:10 VORM. org.openaudible.desktop.swt.gui.GUI <init>
INFORMATION: Starting OpenAudible build 3.0.1 for win32 swt 4940 jvm 12 file.encoding UTF8
Juli 07, 2021 11:57:10 VORM. org.openaudible.Directories getOrCreateWorkingDir
INFORMATION: Using variable OPENAUDIBLE_HOME=D:\FileStore\OpenAudible
Juli 07, 2021 11:57:10 VORM. org.openaudible.Directories isValid
SCHWERWIEGEND: Not found:C:\Users\alois\OpenAudible\tmp
Juli 07, 2021 11:57:10 VORM. org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFORMATION: audible desktop 3.0.1
Juli 07, 2021 11:57:10 VORM. org.openaudible.Directories getPrefs
INFORMATION: Loading C:\Users\alois\OpenAudible\settings.json exists=true size=462
Juli 07, 2021 11:57:10 VORM. org.openaudible.Directories getPrefs
INFORMATION: loaded settings 1625494874663
Juli 07, 2021 11:57:11 VORM. org.openaudible.Directories getPrefs
INFORMATION: Loading C:\Users\alois\OpenAudible\settings.json exists=true size=462
Juli 07, 2021 11:57:11 VORM. org.openaudible.Directories getPrefs
INFORMATION: loaded settings 1625494874663
Juli 07, 2021 11:57:11 VORM. org.openaudible.audible.AudibleConnectionState setRegion
INFORMATION: Setting audible region to US
Juli 07, 2021 11:57:11 VORM. org.openaudible.Audible load
INFORMATION: Loading C:\Users\alois\OpenAudible\books.json
Juli 07, 2021 11:57:11 VORM. org.openaudible.Audible checkLibrary
INFORMATION: loaded 21 books.
Juli 07, 2021 11:57:12 VORM. org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFORMATION: applicationStarted took 565 ms. to complete.
Juli 07, 2021 11:57:15 VORM. org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFORMATION: versionCheck: https://openaudible.org/swt_version.json

**Comment by aloisgruber** [comment]
I think I found it, it is required to remove to default directory, then it uses the env var correctly

**Comment by openaudible** [comment]
Strange. I'm not sure. I didn't do that when I tested it.. but something must have changed. Glad it's working now.

**Comment by sr-behanafnq** [comment]
I tried adding both personal and system environment variables and changing the first two preferences to a location on Dropbox. When I restarted, the preferences had changed back to the original C drive location. Once I deleted the environment variables and restarted, the first 2 preferences had changed to the Dropbox location! In case I was going nuts, I repeated the whole process this morning with the same result, so I wasn't seeing things. I downloaded and converted a book this morning. The AAX, art and books folders in Dropbox were updated with the new book. However the tmp folder and various json files (excl license.json) were updated on my C drive. OA seems to be working in a strange, hybrid way. At least I've managed to clear a significant amount of space on my C drive.

**Comment by openaudible** [comment]
Look at the console window once OA starts. See above for a sample of what to see-- you should see what it "wants" to use for directories and what it ends up using.

**Comment by taconomix** [comment]
I know this is closed, just wanted to chime and say I had the same issue using ArchLinux, and the same solution (removing the OpenAudible directory in my home directory) fixed the issue.

**Comment by DreamSworK** [comment]
> I think I found it, it is required to remove to default directory, then it uses the env var correctly

Yes, I had the same issue. Deleting the old directory helped me. Windows 10.
