### ISSUE TITLE
OpenAudible Not able to do quick/full library sync

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#666]
seen on Mac with Open audible 3.1

tried on windows without error ver 3.1

Error refreshing library.

Jul 11, 2021 7:34:53 PM org.openaudible.desktop.swt.manager.AudibleGUI run
SEVERE: Error refreshing library
java.io.IOException: http error getting: https://api.audible.com/1.0/library?response_groups=product_attrs%2C+contributors%2C+relationships%2C+media%2C+product_desc%2C+product_extended_attrs%2C+pdf_url%2C+series%2C+category_ladders%2C+rating%2C+sku&num_results=100&page=1&purchased_after=2021-05-23T16%3A06%3A35%2B10%3A00 reason:Forbidden
at org.openaudible.audible.api.Client.requestBytes(Client.java:181)
at org.openaudible.audible.api.Client.request(Client.java:69)
at org.openaudible.audible.api.Client.get(Client.java:245)
at org.openaudible.audible.api.API.getBooks(API.java:164)
at org.openaudible.audible.api.API.getBooks(API.java:148)
at org.openaudible.audible.APIManager.library(APIManager.java:858)
at org.openaudible.desktop.swt.manager.AudibleGUI$1.run(AudibleGUI.java:358)

also seen on mac with version 2.xxx (one of the latest versions) i upgraded to 3.1 to see if the issue was fixed without luck
I have been using open audible since version 1.x without issue on my mac before this

{
 "date": "Sun Jul 11 19:27:38 AEST 2021",
 "uid": "1578526615445",
 "memory": "Memory: Using 26.080M of 8192M (0%) Min 26.080M Max 26.080M",
 "directories": [
  {
   "path": "/Users/Lee/Library/OpenAudible",
   "kind": "BASE",
   "exists": true
  },
  {
   "path": "/Users/Lee/Library/OpenAudible/web",
   "kind": "WEB",
   "exists": true
  },
  {
   "path": "/Users/Lee/Library/OpenAudible",
   "kind": "META",
   "exists": true
  },
  {
   "path": "/Users/Lee/Library/OpenAudible/aax",
   "kind": "AAX",
   "exists": true
  },
  {
   "path": "/Users/Lee/Library/OpenAudible/art",
   "kind": "ART",
   "exists": true
  },
  {
   "path": "/Users/Lee/Library/OpenAudible/books",
   "kind": "MP3",
   "count": 0,
   "exists": true,
   "sample": "/Users/Lee/Library/OpenAudible/books/sample.mp3"
  },
  {
   "path": "/Users/Lee/Library/OpenAudible/tmp",
   "kind": "TMP",
   "exists": true
  },
  {
   "path": "/Applications/OpenAudible.app/Contents/Resources/app",
   "kind": "APP",
   "exists": true
  },
  {
   "path": "/Users/Lee/Library/OpenAudible/books",
   "kind": "M4A",
   "count": 0,
   "exists": true,
   "sample": "/Users/Lee/Library/OpenAudible/books/sample.m4a"
  },
  {
   "path": "/Users/Lee/Library/OpenAudible/books",
   "kind": "M4B",
   "count": 1,
   "exists": true,
   "sample": "/Users/Lee/Library/OpenAudible/books/sample.m4b"
  },
  {
   "path": "/Users/Lee/Library/OpenAudible/books",
   "kind": "BOOKS",
   "exists": true
  }
 ],
 "region": "US",
 "version": "3.0.1",
 "demo": false,
 "platform": "mac",
 "prefs": {
  "disableVersionCheck": false,
  "lastVersion": "3.0.1",
  "playFileCmd": "",
  "webPageIncludeMP3": true,
  "format": "M4B",
  "autoConvert": false,
  "mp3Qscale": 4,
  "autoDownload": true,
  "language": "en",
  "autoWebPage": false,
  "autoConnect": false,
  "uid": "1578526615445",
  "concurrentConversions": 3,
  "browseFileCmd": "",
  "autoLink": false,
  "concurrentDownloads": 3,
  "html": false,
  "theme": "dark",
  "migrated": true,
  "region": "US"
 }
}

**Comment by feldegast** [comment]
here is the error

Jul 11, 2021 7:34:53 PM org.openaudible.desktop.swt.manager.AudibleGUI run
SEVERE: Error refreshing library
java.io.IOException: http error getting: https://api.audible.com/1.0/library?response_groups=product_attrs%2C+contributors%2C+relationships%2C+media%2C+product_desc%2C+product_extended_attrs%2C+pdf_url%2C+series%2C+category_ladders%2C+rating%2C+sku&num_results=100&page=1&purchased_after=2021-05-23T16%3A06%3A35%2B10%3A00 reason:Forbidden
	at org.openaudible.audible.api.Client.requestBytes(Client.java:181)
	at org.openaudible.audible.api.Client.request(Client.java:69)
	at org.openaudible.audible.api.Client.get(Client.java:245)
	at org.openaudible.audible.api.API.getBooks(API.java:164)
	at org.openaudible.audible.api.API.getBooks(API.java:148)
	at org.openaudible.audible.APIManager.library(APIManager.java:858)
	at org.openaudible.desktop.swt.manager.AudibleGUI$1.run(AudibleGUI.java:358)

**Comment by openaudible** [comment]
Try logging out and back in.

**Comment by feldegast** [comment]
that worked, maybe add that into the error message as a solution to resolve the issue or force the log out and prompt to log back in?

**Comment by openaudible** [comment]
Good idea. Will add some code.
