### ISSUE TITLE
co.uk won't download any boooks

### ISSUE THREAD

**Issue by gavor00a** [openaudible/openaudible#67]

**Comment by gavor00a** [comment]
Downloading from audible.co.uk doesn't work - it's still trying to donwload from US shop apparently.

Dec 02, 2018 12:00:56 PM org.openaudible.util.queues.ThreadedQueue$JobThread run
INFO: Starting job Download A Walk in the Woods In progress:1 queue: 0
Dec 02, 2018 12:00:56 PM org.openaudible.Audible jobStarted
INFO: DownloadQueue started:A Walk in the Woods size:0
Dec 02, 2018 12:00:56 PM org.openaudible.download.DownloadJob download
**INFO: Download book: A Walk in the Woods url=http://cds.audible.com**/download?user_id=wc64mOu3myVsj27fWZzfJlzbjK4DHPj1SRMXGI1eNzvkU7_zl-ucusHqB8fmzA&product_id=BK_BBCW_000853&codec=LC_64_22050_Stereo&awtype=AAX&cust_id=wc64mOu3myVsj27fWZzfJlzbjK4DHPj1SRMXGI1eNzvkU7_zl-ucusHqB8fmzA
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 26/02/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 29/06/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 26/02/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 01/12/2017
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 26/02/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 26/02/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 07/08/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 01/12/2017
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 01/02/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 26/02/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 26/07/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 23/11/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 26/02/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 24/04/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 18/07/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 15/11/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 18/07/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 24/11/2017
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 26/02/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 15/11/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 29/04/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 24/06/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 29/06/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 29/06/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 19/11/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 13/11/2017
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 16/10/2017
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 04/06/2018
Dec 02, 2018 12:00:56 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 15/02/2018
Dec 02, 2018 12:00:57 PM org.openaudible.Audible jobCompleted
INFO: DownloadQueue completed:A Walk in the Woods remaining queue size:0
Dec 02, 2018 12:00:57 PM org.openaudible.util.queues.ThreadedQueue$JobThread run
INFO: Starting job convert A Walk in the Woods In progress:1 queue: 0
Dec 02, 2018 12:00:57 PM org.openaudible.Audible jobStarted
INFO: ConvertQueue started:A Walk in the Woods size:0
Dec 02, 2018 12:00:57 PM org.openaudible.util.AudibleDateUtil toSortableDate
WARNING: Unable to parse audible date: 26/02/2018
Dec 02, 2018 12:00:57 PM org.openaudible.convert.ConvertJob convert
SEVERE: Error converting book to MP3:A Walk in the Woods
java.io.IOException: file not found:C:\Users\Jakub\OpenAudible\aax\BK_BBCW_000853.AAX
	at org.openaudible.convert.LookupKey.getKeyFromAAX(LookupKey.java:93)
	at org.openaudible.convert.ConvertJob.getActivationBytes(ConvertJob.java:243)
	at org.openaudible.convert.ConvertJob.createMP3(ConvertJob.java:122)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:271)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:315)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:261)

**Comment by openaudible** [comment]
Click on that book, and use Action Menu, Show AAX. Where is that aax file and what is the full title? 
We expected: :C:\Users\xx\OpenAudible\aax\BK_BBCW_000853.AAX
and its posssible it is at: :C:\Users\xx\OpenAudible\aax\BK_BBCW_000853UK.AAX

Maybe delete all .aax files that end in UK? and re-download them and see if they are named without the UK suffix?

**Comment by openaudible** [comment]
OK.. I posted a new version 1.2.8... You may need to delete your books.json file and re-import your books...  If you get duplicate books, or see other problems getting your books..please send in a bug report from the Help menu within OpenAudible.

**Comment by Andee75** [comment]
I am having the same issue..... I can connect to audible but I can't seem to figure out how to download any of my book.

**Comment by openaudible** [comment]
Try the following:
Restart OA.
Connect to audible
Go to your Library
Click on a "download" button. (If you see a message about "how to listen" in the browser or an alert in the application,  change your audible settings (see help.. need to get a specific help page.)
You should see the file start downloading in OA.
Next, try a "library sync". 
If your books don't show up:
Help Menu -> Send Bug report. Reference Issue #67. We will get a copy of the console and html and can take a look.

**Comment by Andee75** [comment]
Thanks for that.  I tried those things.  When I do a library sync it says that my library is up to date and I need to buy more books…. But I have no books in openaudible.  I have tried to click download next to a book in the browser that I sign in with.  Nothing happens.  I am not given the option to click on download all book from the menu.  It is light grey and I can’t click on it.  I have sent bug report.

 

LaWanda

**Comment by openaudible** [comment]
OK.. I got a bug report from someone in the UK. In the OA console, you'll see OA trying to download the aax using a url that starts with https://cds.amazon.com/xxxxx

That URL is not working and the book isn't downloading.. We need to determine the correct URL to use. You could try downloading the book from a web browser (not the OA internal browser) to get the audible download manager link file, which is a small text file with details.. Post the contents of that file (obfuscating your IDs) and we can see if the URL can be determined. maybe it is as simple as cds.amazon.uk.co, but we don't know as we don't have any UK accounts to test with.

**Comment by openaudible** [comment]
Made a significant fix.. please upgrade to 1.3.0 and let me know.

**Comment by IOI-655321** [comment]
This is working loads better now great thanks.  Only occasional error I have is after doing a full Library Sync it sometimes resets the browser library window to show an empty library so not sure if it tries to send it to a non UK url after that process?

**Comment by openaudible** [comment]
Glad to hear. Not sure why a blank library would come up.. Might be a bug with audible. Haha. 
Feel free to open a new ticket for that-- would need some screenshots and a bug report.
