### ISSUE TITLE
Conversion of non-audible.com files?

### ISSUE THREAD

**Issue by ejtasker** [openaudible/openaudible#670]
I have an audio book I ripped from a CD some time ago as an mp3. I'd like to merge the track files and convert to .m4b. But those options are greyed out on the files I imported. Is it not possible for files not purchased from audible.com?

**Comment by openaudible** [comment]
Converting to m4b from mp3 is not currently supported.  You would lose audio quality. I think you can join the mp3 chapters into a single mp3. There are other tools to convert mp3 to m4b but we want to keep things simple.
