### ISSUE TITLE
buying openaudible

### ISSUE THREAD

**Issue by ives31** [openaudible/openaudible#672]
Before I buy Openaudible, is there any recourse to compensation if, by chance the program does not work on my pc/laptop etc?
I'm asking becasuse Ive been stung before buying software that in the end does not work.
Thanks
Ives

**Comment by openaudible** [comment]
Sure, just ask for a refund. Our return rate is well under 0.5%. 

Once you've successfully converted your books, we would appreciate you not asking for a refund, instead, let us know if you have any feedback.

**Comment by ives31** [comment]
thats great.
I paid for a licence today and the program works perfectly. thanks.
