### ISSUE TITLE
License Issue - I thought I had a perpetual license but now it seems 1 year. Am I being scammed?

### ISSUE THREAD

**Issue by riwide** [openaudible/openaudible#677]
Approx one year after purchasing a license, I am told that version 3.02 requires me to get a new license. I did not know the license was restricted to one year. The open audible web site should make this clear. It does not indicate any limitation.

Please issue my perpetual license and update web site to inform new licensees of any restrictions.

**Comment by openaudible** [comment]
You can use your license forever.. but free upgrades are for 1 year. 

So after a year, you can either upgrade ($12) another year of upgrades. or keep using the last version that is within the one year period. Older versions can be downloaded from https://github.com/openaudible/openaudible/releases

We have been extending people's licenses automatically when they log in with a newer version (3.0.1 or 3.0.2), so you can check to see when you bought your license and when it expires in the "License" dialog under the About menu. So currently I don't think you need to buy an upgrade-- but it is something on the horizon. It is possible our alert message is wrong about needing to upgrade-- but I'm not positive. 

Upgrades help fund development of new features, support, and upkeep.

**Comment by riwide** [comment]
Thank you for the clarification. Please make it clearer on the website.
I do find the program useful as I have a lot of audio books,  it allows me
to do a backup and manage my catalog.

I will probably buy another year of updates.

Richard

**Comment by openaudible** [comment]
Will update the web page to make it more clear that the license is good for 1 year of free updates. Thanks.
