### ISSUE TITLE
License

### ISSUE THREAD

**Issue by fruttivendolo** [openaudible/openaudible#678]
Ciao,
Before purchasing a license for OpenAudible I would appreciate a response to some issues that I have not been able to find an answer to.

Firstly, is an OpenAudible license, for Linux, for a limited period of time and if so for how long. Secondly, if Audible make some changes to the format of their audio book files are all current license holders entitled to an updated version of OpenAudible?

Best regards

**Comment by openaudible** [comment]
It can be a little confusing. 

From https://openaudible.org/license : 

OpenAudible requires a valid license to use the latest version of the software. A license is valid forever. Free updates are available for one year. If your license is more than a year old, you can keep using your current version indefinitely. However upgrading to a version created after your 1 year license may require a low-cost upgrade.

If Audible makes a change that breaks our software, we will attempt to fix it-- however if our release is made after your 1 year of free updates, an upgrade charge (currently $12) _may_ be required. If its a small fix, we could make it available to all users. We're trying to strike a balance between a subscription model and allowing users to get a great product for a one time fee.

**Comment by fruttivendolo** [comment]
Ciao,
Thank you for your response and explanation of the license terms.

I have purchased and installed a copy of the software, under Linux Mint, and downloaded a book, V2 by Robert Harris, as an mp3 file without encountering any problems. I then used the software to split the downloaded book into chapters but found the following anomaly.

On the laptop each file has an individual name, V2 01.mp3, V2 02.mp3, V2 03.mp3 etc, but on my music player, a Zen X-Fi3, all of the chapter files are shown as having the same name, in this case V2. The result that it is not possible to distinguish between files when playing them on the music player. Also, I have noticed that the metadata for each chapter file is the same, ie V2.

As this is the first time that I have used the software it may be that I am doing something incorrectly. Any comments or suggestions appreciated.

**Comment by openaudible** [comment]
Check out our beta version.. we just added chapter names and new splitting logic.
You'll need to: delete any m4b/mp3 files
Do a full library rescan
Encode your books.
Then split them.
https://openaudible.org/beta

**Comment by fruttivendolo** [comment]
Ciao,
Thank you for your response and beta version which now includes chapter numbers in the metadata.

The remaining minor problem that I have is that the first nine chapters do not appear on my music player in the correct sequence. For a book with 18 chapters, chapter 1 is followed by chapter 10 with chapters 2 to 9 following after chapter 18. It seems to me that this could be due to chapters 1 to 9 being named in the metadata as "Chapter 1", "Chapter 2" etc rather than  "Chapter 01", "Chapter 02" etc. Could this change be incorporated into the naming format in your next version?

**Comment by openaudible** [comment]
The title of the chapter could be anything -- Introduction, Chapter 1, Godzilla Attacks, etc. 
Not sure why your book player would try to sort the chapters alphabetically. Can you send a bug report to them? The files we generate when we split the book are always sorted alphabetically.

**Comment by fruttivendolo** [comment]
Ciao,
Thank you for your patience and your further response. I am not sure if the way my music player indexes its files is a bug or a feature! 

After originally splitting the large mp3 file with OpenAudible the chapters are displayed as shown in "numbering 1.png" but when I manually edit the metadata of chapters 1 to 9, changing "chapter 1" to "chapter 01" the chapters are displayed as shown in "numbering 01.png", see attached files.

As this problem only seems to apply to the first nine chapters doing the above manual editing only takes a few minutes and is not really a problem.

numbering 1:
![numering 1](https://user-images.githubusercontent.com/88164356/129458179-6cd26122-abde-4125-a192-0429e1c55bc7.png)

numbering 01:
![numering 01](https://user-images.githubusercontent.com/88164356/129458180-59c39ffd-08ec-4588-89e3-f50a4057b733.png)

**Comment by openaudible** [comment]
We really don't recommend splitting books into multiple chapters. A single MP3 or M4B can contain a whole book and include meta data for chapters. Modern audio players (every android or Apple product) should support large audio files without issue. ZEN players have all been discontinued. I'm sorry I'm out of bandwidth for players built in built before 2008.

**Comment by fruttivendolo** [comment]
Ok and thank you for your response.

This particular Zen has been around for quite some time, its first Audible book was in December 2011. It can play the large mp3 files but moving backwards and forwards is much easier when the large file is split, as with OpenAudible, into chapters.

Best regards and thanks again for your help.
