### ISSUE TITLE
Auto-update

### ISSUE THREAD

**Issue by edpowell** [openaudible/openaudible#679]
Please add auto-update capability on macOS.

Manual updates are fine for software packages that are rarely updated, but for a software package updated weekly or even more often, the bouncing icons and alerts and downloads are all too much.  Auto-update would solve this problem.

**Comment by openaudible** [comment]
We try not to make too many updates.. but I get your point. 

I think there is support for that in install4j, our installer app... but haven't tested it. Marking as a suggestion.
