### ISSUE TITLE
conversion from .aax to .mp3 failing on books over a certain size/length

### ISSUE THREAD

**Issue by Crimmy5** [openaudible/openaudible#68]
Hello,

I am trying to convert a few books from my library, however, they always seem to fail. The only trend I can see is that with the exception of one, all books over 20:35 in length are failing to convert. There doesn't seem to be a correlation with file size; there are numerous files that will not convert that are smaller than some that have converted. I have also tracked OpenAudibles RAM usage while converting, and it successfully cleared 2GB, and crashed a little ways past that.

![image](https://user-images.githubusercontent.com/45559049/49367958-7115d500-f6e5-11e8-87d8-47e0ccd281e8.png)

I would love some help with this, and I want to thank you wonderful people for creating such a useful tool! If there is anything else I can do to help solve this issue then please let me know.

**Comment by openaudible** [comment]
We've tested with many larger files.

Try converting again with the console log open. Copy and paste the results here.. Make sure the working directory and application dirs have plenty of space. My guess is the temp dir being used is running out of space. 

Just reopen this ticket by pasting console data.

**Comment by Crimmy5** [comment]
Ok, I have tried that. Unfortunately, when the conversion fails, it also closes OpenAudible, including the log - This is what it looked like before crashing through: 

Dec 04, 2018 11:56:43 AM org.openaudible.desktop.swt.manager.AppLoader <init>
INFO: Starting OpenAudible build 1.2.7 for win32 swt 4623 jvm 1.8.0_141
Dec 04, 2018 11:56:43 AM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 1.2.7
Dec 04, 2018 11:56:44 AM org.openaudible.Audible checkLibrary
INFO: bl=104, gl=0
Dec 04, 2018 11:56:44 AM org.openaudible.util.SimpleProcess <init>
INFO: Running: "C:\Program Files\OpenAudible\bin\win\ffmpeg" -version 
Dec 04, 2018 11:56:44 AM org.openaudible.desktop.swt.manager.AudibleGUI checkFFMPEG
INFO: using ffmpeg version N-76456-g6df2c94 Copyright (c) 2000-2015 the FFmpeg developer
Dec 04, 2018 11:56:49 AM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Dec 04, 2018 12:01:14 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Convert
Dec 04, 2018 12:01:14 PM org.openaudible.util.queues.ThreadedQueue$JobThread run
INFO: Starting job convert Harry Potter and the Half-Blood  In progress:1 queue: 0
Dec 04, 2018 12:01:14 PM org.openaudible.Audible jobStarted
INFO: ConvertQueue started:Harry Potter and the Half-Blood  size:0
Dec 04, 2018 12:01:14 PM org.openaudible.util.SimpleProcess <init>
INFO: Running: "C:\Program Files\OpenAudible\bin\win\ffmpeg" -i C:\Users\User1\OpenAudible\aax\BK_POTR_000013.AAX 
Dec 04, 2018 12:01:14 PM org.openaudible.convert.ConvertJob createMP3
INFO: creating mp3: Harry Potter and the Half-Blood  to temp file: C:\Users\User1\OpenAudible\tmp\BK_POTR_000013_temp.mp3
Dec 04, 2018 12:01:14 PM org.openaudible.convert.ConvertJob createMP3
INFO: "C:\Program Files\OpenAudible\bin\win\ffmpeg" -activation_bytes 0de38901 -i C:\Users\User1\OpenAudible\aax\BK_POTR_000013.AAX -map_metadata 0 -metadata:s:v "title=Album cover" -metadata:s:v "comment=Cover (front)" -codec:a libmp3lame -qscale:a 4 -id3v2_version 3 -metadata product_id=BK_POTR_000013 -metadata asin=B017WOTWVO -metadata "narratedBy=Stephen Fry" -metadata book_genre= -metadata major_brand= -metadata minor_version= -metadata compatible_brands= C:\Users\User1\OpenAudible\tmp\BK_POTR_000013_temp.mp3 
Dec 04, 2018 12:05:01 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console


I noticed something else and realised I have been misdescribing the problem. OpenAudible seems to close itself down automatically after exactly 10 minutes, regardless of what's going on - whether it's idling or converting. I think the remaining audiobooks are the ones that can't be converted in that 10-minute window. Is this intended? And if not, how can I fix it? 

Thanks!

**Comment by Crimmy5** [comment]
> 
> 
> We've tested with many larger files.
> 
> Try converting again with the console log open. Copy and paste the results here.. Make sure the working directory and application dirs have plenty of space. My guess is the temp dir being used is running out of space.
> 
> Just reopen this ticket by pasting console data.

Hello,

I have done so, and also (I think) diagnosed the problem - however, the case wasn't reopened upon replying. 

The more likely problem: OpenAudible seems to close itself down automatically after exactly 10 minutes, regardless of what's going on - whether it's idling or converting. I think the remaining audiobooks are the ones that can't be converted in that 10-minute window. Is this intended? And if not, how can I fix it?

Thanks!
