### ISSUE TITLE
Deleting files from Finder

### ISSUE THREAD

**Issue by RandmTask** [openaudible/openaudible#680]
At the moment, after I rename the file I move it to my Audiobooks directory

Once I do that, OpenAudible starts converting the AAX file again to M4B, and everytime I delete that file in Finder, it keeps recreating the file

I worked out that I need to delete the AAX file also which stops the behaviour (However the icon is still green in OpenAudible)

Suggestion:
1. When the file is converted from AAX -> M4B/M4A/MP3 have an option in preferences to always delete the AAX as it takes up twice as much space
2. When the M4B **in Finder** is moved out of the "OpenAudible\books" directory, don't start converting again or download. Instead change the icon in OpenAudible from green to grey.
3. When you delete the book **in OpenAudible** don't delete it from OpenAudible, just delete the underlying files and change the icon from green to grey

Thanks

**Comment by openaudible** [comment]
I have a partial solution..

1. If book has converted file (either m4b or mp3 in our standard location), we won't allow you to re-download the file. (You'd have to move or delete the m4b.) That way you can delete or move the aax files to save space.

2. This one is more messy. With Auto-convert on, moving the m4b will make it want to re-encode the book. Kind of an edge case to want to not convert your files.

3. I assume if you delete the whole book as it is now, when you rescan your library, it will be re-added. 

Trying to keep the complexity down and usability up. Will close but open to suggestions like these to make the product more usable.

**Comment by openaudible** [comment]
Option to delete the aax has been added to the latest beta.
