### ISSUE TITLE
No chapter information

### ISSUE THREAD

**Issue by RandmTask** [openaudible/openaudible#681]
All of my Audible books have no chapter information (Checked through Subler, Audiobook Builder and PLEX via Prologue). 

Checked about 20 books and they only are listed as Chapter 1, Chapter 2 etc.

The chapter names are available in the Cloud Player however.

Is there something I am doing wrong?

**Comment by openaudible** [comment]
Chapter names is a known feature request. Have a prototype in progress. Will be added as a feature soon.

**Comment by openaudible** [comment]
OK.. Posted a beta that supports chapter names. 
https://openaudible.org/beta
Not all audible titles have chapters names.

**Comment by RandmTask** [comment]
Brilliant!

Tested about 20 titles and only about half of them worked. After a lot of trial and error I realised it was because my audiobooks are from different regions.

When I was logged in to the AU store:
**All** AU books worked with chapter names
**Some** books in the US worked with chapter names others had **no chapters at all**
**Some** books in the IN worked with chapter names others had **no chapters at all**

When I logged into the IN store: 
**All** IN books worked with chapter names

Suggestions:
-If possible allow OpenAudible to download chapter names from stores that it is not logged in to.
-Be able to log in (be connected) to more than one Store at a time
-Introduce another column in OpenAudible that says the store and account eg "AU / myemail@gmail.com"

Hope that helps, and thanks for your hard work in bringing this feature!

See below for two different copies of Tales of Beedle the Bard (US and IN) downloaded while connecting to the AU store

![Screen Shot 2021-08-07 at 1 00 40 pm](https://user-images.githubusercontent.com/7912017/128596815-45439272-dbb4-4ba0-89c9-7f6c161f6187.png)

**Comment by openaudible** [comment]
Thanks for the feedback! Yeah multiple accounts isn’t supported well yet. Will work on some solutions. Trying to keep things reasonable.

**Comment by openaudible** [comment]
Have a fix in mind that you’ll need to delete all m4b, do full rescan on all accounts… then encode. Will be in next beta 4. But still working on a few glitches.

**Comment by openaudible** [comment]
OK. Posted a new beta 4.  Full rescan all libraries before re-encoding files.

**Comment by openaudible** [comment]
Chapter names added to 3.1 released today.
