### ISSUE TITLE
Images not attaching to files

### ISSUE THREAD

**Issue by Flyingmatthew** [openaudible/openaudible#682]
Book images are not being automatically being added to m4b files in the newest verison. Also m4b files are a lot bigger than the before updating to the newest verison.

**Comment by openaudible** [comment]
Beta or regular version? What OS? What app doesn’t show images? They show in iTunes windows and Plex. Maybe a screenshot?

**Comment by Flyingmatthew** [comment]
I believe that it is the regular version. The app is "Smart AudioBook Player" for Android. 
Attached are two screen shots of the cover art selection within the app. The first "The Core" was a older conversion and shows an embedded cover.  The second "The Desert Prince" I converted a couple days ago and had to manually transfer the cover art to the same folder for the app to read it.
Thanks Matthew 





Sent from Yahoo Mail on Android 
 
  On Sun, Aug 8, 2021 at 5:46 AM, ***@***.***> wrote:   


Beta or regular version? What OS? What app doesn’t show images? They show in iTunes windows and Plex. Maybe a screenshot?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by openaudible** [comment]
Hmm. Will look at the code to see what changed. There are a few ways to attach an image. When it shows up in windows explorer, we usually call it a day. But definitely played with different image attaching methods. 

You could take a look at the beta, we changed a few things for chapter names in that and are encoding m4b files in a new style. https://openaudible.org/beta and will be able to try new changes with the beta if you have more feedback.

**Comment by Flyingmatthew** [comment]
Thanks 😀

Sent from Yahoo Mail on Android 
 
  On Sun, Aug 8, 2021 at 8:43 AM, ***@***.***> wrote:   


Hmm. Will look at the code to see what changed. There are a few ways to attach an image. When it shows up in windows explorer, we usually call it a day. But definitely played with different image attaching methods.

You could take a look at the beta, we changed a few things for chapter names in that and are encoding m4b files in a new style. https://openaudible.org/beta and will be able to try new changes with the beta if you have more feedback.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by openaudible** [comment]
OK, found some code that was "optimized" and looks like it caused the problem you're seeing. 
Fixed in beta 3: https://openaudible.org/beta
Please let me know if that fixes the issue.

**Comment by Flyingmatthew** [comment]
It will be later tonight or tomorrow before I can test it. Will let you know when I do 😀
Matthew 

Sent from Yahoo Mail on Android 
 
  On Sun, Aug 8, 2021 at 2:06 PM, ***@***.***> wrote:   


OK, found some code that was "optimized" and looks like it caused the problem you're seeing.
Fixed in beta 3: https://openaudible.org/beta
Please let me know if that fixes the issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Flyingmatthew** [comment]
Yes that seems to have fixed the problem 👍Thank you 

Sent from Yahoo Mail on Android 
 
  On Sun, Aug 8, 2021 at 2:06 PM, ***@***.***> wrote:   


OK, found some code that was "optimized" and looks like it caused the problem you're seeing.
Fixed in beta 3: https://openaudible.org/beta
Please let me know if that fixes the issue.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by openaudible** [comment]
Hmm. That introduced a new bug where the tags (author, description, etc.) were not added. Might need to send a bug report to your audiobook player people.. The image shows up in most audio players.. May try to debug some more, but no promises.

**Comment by Flyingmatthew** [comment]
Ok, keep me posted if you can. 😀

Sent from Yahoo Mail on Android 
 
  On Tue, Aug 10, 2021 at 8:21 PM, ***@***.***> wrote:   


Hmm. That introduced a new bug where the tags (author, description, etc.) were not added. Might need to send a bug report to your audiobook player people.. The image shows up in most audio players.. May try to debug some more, but no promises.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
