### ISSUE TITLE
Unable to log in

### ISSUE THREAD

**Issue by nogorilla** [openaudible/openaudible#683]
macOS 11.5.1
OpenAudible 3.0.2

When attempting to connect to my Audible account, after entering username and password for Amazon, an error popup appears with the title: "Error registering virtual device" and the message body: `REGISTER_ERROR_BODY`

**Comment by nogorilla** [comment]
<img width="596" alt="Screen Shot 2021-08-09 at 10 12 18 AM" src="https://user-images.githubusercontent.com/1786677/128720534-2b15edf3-afdd-4307-905e-c786d54d5993.png">

**Comment by openaudible** [comment]
Error message isn’t too good. I think you have too many devices registered. You’ll need to delete some from your Amazon devices list. 

https://help.audible.com/s/article/how-can-i-deactivate-devices-that-are-using-the-audible-app?language=en_US

**Comment by openaudible** [comment]
By the way, I fixed that error message for the next version. Let me know if that fixes your issue.
