### ISSUE TITLE
Joining M4A files with an apostrophe in the filename

### ISSUE THREAD

**Issue by wosson** [openaudible/openaudible#686]
Joining M4A files with an apostrophe in the filename breaks created file. In VLC file length reported correctly but file size suspiciously small. Jumping to later chapters causes book to crash. Observing file length (time) in MP3tag shows that actual file length is truncated. Removing apostrophe (') in component file fixes!

**Comment by openaudible** [comment]
Thank you for the report! Fixed in beta 5, https://openaudible.org/beta
