### ISSUE TITLE
[Question/FR] Join via Command Line

### ISSUE THREAD

**Issue by LanceMcCarthy** [openaudible/openaudible#687]
I have a bunch of titles that I'd love to automate the joining of them into a single mp3. Doing this manually will literally take 8 hours a day for a week. 

Is there a way I can call openaudible.exe in the CLI and pass in the folder to join the files?

for example, I could use cmd with the `copy` command, 

`copy/b Chapter1.mp3 + Chapter12.mp3 + Chapter13.mp3 Complete.mp3`

but it looks like OpenAudible handles this more elegantly and sets the mp3tags as well.

**Comment by openaudible** [comment]
Marked as FR. 

Maybe instead of command line, drag and drop a directory would join and add the joined file automatically? Would that work?

**Comment by LanceMcCarthy** [comment]
Drag and Drop would work just as well (ala dropping a set of files onto a bat file)

**Comment by openaudible** [comment]
I posted a new beta 3.0.2.6 https://openaudible.org/beta that lets you drag and drop one or more directories to be joined. It automatically creates a output mp3 or m4b. It can also import zip files that contain a split book. Check the tagging to make sure the title, album (also title), and artist (author) are correct.. as well as the chapter names and times. Test a few book directories and make sure you know where things are being created. Book directories need at least two parts to be joined.. other assumptions are made. Any feedback appreciated.

**Comment by LanceMcCarthy** [comment]
Thank you, I'll try it out over the next couple weeks and let you know of any undesired behavior.

No, this isn't for any commercial operations. I have a large, old, library of books that are in Plex but are split up by chapter. I also prefer to have the media as one mp3 file and let Plex handle the position tracking. Thus, I am manually going through the library and joining them all. However, there are thousands of books, so any tiny bit of optimization adds up to saving a lot of time.

Speaking of Plex. I noticed that the release notes for 3.0.2 mention Plex support. what exactly does that mean? I installed the update and extended my license for another year. I went through some of the GUI but didn't see any setting/mention of Plex interop.

**Comment by openaudible** [comment]
We just optimized our tags (summary, narratory, etc.) to work with the new plex beta. So the idea is you create a "audiobooks" library in plex and point it to the OA books directory and it works pretty well. 
Good luck and closing this ticket.

**Comment by LanceMcCarthy** [comment]
works great!

**Comment by LanceMcCarthy** [comment]
Wait, sorry for the double reply. I just discovered an issue, it seems it works gfreat for the 1st drop. However the 2nd drop loses context and never finished writing to the joined file.

Take the following steps to repro:

1. Drag in one folder, let it work to completion and observe the final dialog for import.
2. Drag in a 2nd folder, let it work to completion
  => Observe issue: The operation completes and the progress dialog closes, however there is no final joined files saved, nor is there a import dialog.

It seems I can reset this if I manually select a folder, then do a subsequent drag and drop. so I suspect this is a simple state management problem for subsequent folder drops.

**Comment by LanceMcCarthy** [comment]
I think I figured what is going wrong. The joined file being generated in the /temp/ folder is never copied into the original folder.

This is anecdotally confirmed by dragging the same folder back into OpenAudible, because it immediately completes the operation (though with out the desired end result because the cached joined-file is still in the temp folder).

**Comment by openaudible** [comment]
There are no prompts when you drag and drop a folder onto OA. It automatically does the join and adds the book. Adding a dialog would slow the process down and not be very clear what is going on.

The folder should have a good book title in case the title can't be determined from the tags. You should be able to edit the tags before you do the join.. but that's up to you.


We will probably add a tag editor to a later version of OA. Seems like if you are managing a lot of book files, that is a feature that will be important.

**Comment by LanceMcCarthy** [comment]
Agreed  that the dialog is counter productive in this d&d import operation. I misphrased what I mean by 'keeping the same behavior as ctl+j' . 

I was ultimately expecting was the joined mp3 to present in the source folder after the join.

Could you leave a copy of it in the folder, before performing the final  import step?

**Comment by openaudible** [comment]
I think its better to keep the import action "read only". If you were to drag it in a second time, the newly created joined file would be appended to the book.. not what the user would want. We do create a reasonable json file that can be read and parsed so a script could be used to do additional copies or steps.

**Comment by LanceMcCarthy** [comment]
The json results file would indeed be a perfect way to do post-import actions. Where is it saved, and does it use a predictable naming scheme (ie My Book-Import.json)?

**Comment by openaudible** [comment]
We already create a books.json file that is updated with each imported book. Its in the application prefs, which you can find in the preferences dialog. 

Just scan the json file for new books and do what you need to do. You might also parse the tmp/logs.txt log file that might have some information about recently joined books.
