### ISSUE TITLE
Random Chapter Number/Title Appearing in Apple Books App

### ISSUE THREAD

**Issue by palomban** [openaudible/openaudible#688]
See screenshots. I did not split by chapter. Not sure where the "Chapter 8" text is coming from.

![IMG_7101](https://user-images.githubusercontent.com/74151076/129380611-94764ca2-4f61-4696-8983-09aa63b7e91d.PNG)

![IMG_7099](https://user-images.githubusercontent.com/74151076/129380809-778e197e-e7e2-44e9-8a50-9594cab67902.jpg)

![image](https://user-images.githubusercontent.com/74151076/129381025-4a89d6c1-5416-4bd4-903f-7edeec69e8dd.png)

**Comment by openaudible** [comment]
Are you using the beta? https://openaudible.org/beta 
We started adding the chapter names that Audible has to books. 
With the current version (302) chapter data is pulled from the aax file and may be interpreted by the book player app.
You can select a book in OA and Action: Book Report to get a bunch of data about the book and each of the media files (AAX, M4B, etc.) Maybe scan through that and look for a "Chapter 8" -- it seems unlikely that 10 minutes into the book you'd be on chapter 8, but not sure.

**Comment by palomban** [comment]
I'm using Version 3.0.2. Here is the book report. I don't see any reference to a Chapter 8. Also, the player is showing this text throughout the entire duration of the book.

`{
 "copyright": "©2021 Mark Spitznagel (P)2021 Audible, Inc.",
 "author": "Mark Spitznagel",
 "description": "What is a safe haven? What role should they play in an investment portfolio? Do we use them only to seek shelter until the passing of financial storms? Or are they something more? Contrary to everything we know from modern financial theory, can higher returns actually come as a result of lowering risk? In Safe Haven, hedge fund manager Mark Spitznagel - one of the top practitioners of safe haven investing and portfolio risk mitigation in the world - answers these questions and more. ",
 "title": "Safe Haven: Investing for Financial Storms",
 "title_short": "Safe Haven: Investing for Financial Storms",
 "duration": "06:42:18",
 "report_by": "OpenAudible 3.0.2",
 "filename": "SafeHavenInvestingforFinancialStorms_ep7",
 "narrated_by": "Fred Berman",
 "release_date": "03-AUG-2021",
 "product_id": "BK_ADBL_033682",
 "genre": "Audiobook",
 "publisher": "Audible Studios",
 "files": [{
  "file": "C:\\Users\\Nicholas Palomba\\OpenAudible\\art\\SafeHavenInvestingforFinancialStorms_ep7.jpg",
  "size": 29776,
  "chapters": [],
  "meta": [
   ";FFMETADATA1",
   "encoder=Lavf58.44.100"
  ],
  "streams": [{
   "color_range": "pc",
   "pix_fmt": "yuvj420p",
   "r_frame_rate": "25/1",
   "start_pts": 0,
   "duration_ts": 1,
   "duration": "0.040000",
   "sample_aspect_ratio": "1:1",
   "codec_tag_string": "[0][0][0][0]",
   "avg_frame_rate": "0/0",
   "closed_captions": 0,
   "color_space": "bt470bg",
   "codec_long_name": "Motion JPEG",
   "height": 500,
   "chroma_location": "center",
   "time_base": "1/25",
   "coded_height": 500,
   "level": -99,
   "profile": "Baseline",
   "bits_per_raw_sample": "8",
   "index": 0,
   "codec_name": "mjpeg",
   "start_time": "0.000000",
   "disposition": {
    "dub": 0,
    "karaoke": 0,
    "default": 0,
    "original": 0,
    "visual_impaired": 0,
    "forced": 0,
    "attached_pic": 0,
    "timed_thumbnails": 0,
    "comment": 0,
    "hearing_impaired": 0,
    "lyrics": 0,
    "clean_effects": 0
   },
   "codec_tag": "0x0000",
   "has_b_frames": 0,
   "refs": 1,
   "codec_time_base": "0/1",
   "width": 500,
   "display_aspect_ratio": "1:1",
   "coded_width": 500,
   "codec_type": "video"
  }],
  "format": {
   "duration": "0.040000",
   "start_time": "0.000000",
   "bit_rate": "5955200",
   "filename": "C:\\Users\\Nicholas Palomba\\OpenAudible\\art\\SafeHavenInvestingforFinancialStorms_ep7.jpg",
   "size": "29776",
   "probe_score": 50,
   "nb_programs": 0,
   "format_long_name": "image2 sequence",
   "nb_streams": 1,
   "format_name": "image2"
  }
 }],
 "asin": "B09BD8PCF8",
 "purchase_date": "2021-08-04"
}
`

**Comment by openaudible** [comment]
Where did you get the file from? I didn’t see an aax file attached. Didn’t see any chapters embedded in the file. Also file name says ep7, which looks like a podcast name.
