### ISSUE TITLE
[BR] Join - Missing Mp3 Tag Causes NRE

### ISSUE THREAD

**Issue by LanceMcCarthy** [openaudible/openaudible#689]
I noticed that I was consistent getting a Java Null Reference Exception when trying to join a particular set of audio files. One thing I noticed is that none of them had an mp3 tag set.

So, to debug, I manually set all the files to have an mp3tag (using Mp3Tag) and the join was successful.

This leads me to think there is some sort of variable being used inside the file join loop that grabs the first instance of any tags. Then, outside of the loop, it uses that tag to set the final tag's mp3 tags.

Here's a  pseudo-code example to explain what I mean

```java
var tagToUse = null;

foreach(var file in files)
{
    if(file.tag != null && tagToUse == null)
    {
        tagToUse = file.tag;
    }
}

// THIS CAUSE THE EXCEPTION (because the inner loop never met conditions and tagToUse is still null)
finalFile.Tag = tagToUse;

```

**Comment by openaudible** [comment]
Can you use the beta and copy and paste the NPE report from the console window?

**Comment by LanceMcCarthy** [comment]
Unfortunately, I didn't grab the stacktrace or error message before I applied the workaround. Is there a log I can pull up?

**Comment by openaudible** [comment]
No.. Hopefully fixed in the beta already.. we did a lot of join code. If it happens again, the stack trace or a bug report from the app is always helpful. Thanks for the report.
