### ISSUE TITLE
OpenAudible closes automatically after 10 minutes

### ISSUE THREAD

**Issue by Crimmy5** [openaudible/openaudible#69]
Hi,

I opened an issue previously about OpenAudible not converting larger files - I think I have narrowed down the issue a bit more. It wasn't the size of the files that was the issue, or the size of the drive they're being saved on - I believe it is the fact that OpenAudible closes after 10 minutes automatically, regardless of what is going on. All the other books I was able to successfully convert were done in that 10 minutes, whereas the longer ones I'm now having trouble converting aren't able to be converted in that timeframe. Any idea why OpenAudible is doing this, and how to stop it closing to Desktop after 10 minutes? I tried to check the console log for anything happening around the time it closed down, but I didn't see anything, and when the program closed the console closed with it. Nevertheless, in case its useful, I have pasted the Console log (as close as I can get it to when it closes) below:

Dec 04, 2018 11:56:43 AM org.openaudible.desktop.swt.manager.AppLoader
INFO: Starting OpenAudible build 1.2.7 for win32 swt 4623 jvm 1.8.0_141
Dec 04, 2018 11:56:43 AM org.openaudible.desktop.swt.manager.AudibleGUI
INFO: audible desktop 1.2.7
Dec 04, 2018 11:56:44 AM org.openaudible.Audible checkLibrary
INFO: bl=104, gl=0
Dec 04, 2018 11:56:44 AM org.openaudible.util.SimpleProcess
INFO: Running: "C:\Program Files\OpenAudible\bin\win\ffmpeg" -version
Dec 04, 2018 11:56:44 AM org.openaudible.desktop.swt.manager.AudibleGUI checkFFMPEG
INFO: using ffmpeg version N-76456-g6df2c94 Copyright (c) 2000-2015 the FFmpeg developer
Dec 04, 2018 11:56:49 AM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
Dec 04, 2018 12:01:14 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Convert
Dec 04, 2018 12:01:14 PM org.openaudible.util.queues.ThreadedQueue$JobThread run
INFO: Starting job convert Harry Potter and the Half-Blood In progress:1 queue: 0
Dec 04, 2018 12:01:14 PM org.openaudible.Audible jobStarted
INFO: ConvertQueue started:Harry Potter and the Half-Blood size:0
Dec 04, 2018 12:01:14 PM org.openaudible.util.SimpleProcess
INFO: Running: "C:\Program Files\OpenAudible\bin\win\ffmpeg" -i C:\Users\User1\OpenAudible\aax\BK_POTR_000013.AAX
Dec 04, 2018 12:01:14 PM org.openaudible.convert.ConvertJob createMP3
INFO: creating mp3: Harry Potter and the Half-Blood to temp file: C:\Users\User1\OpenAudible\tmp\BK_POTR_000013_temp.mp3
Dec 04, 2018 12:01:14 PM org.openaudible.convert.ConvertJob createMP3
INFO: "C:\Program Files\OpenAudible\bin\win\ffmpeg" -activation_bytes 0de38901 -i C:\Users\User1\OpenAudible\aax\BK_POTR_000013.AAX -map_metadata 0 -metadata:s:v "title=Album cover" -metadata:s:v "comment=Cover (front)" -codec:a libmp3lame -qscale:a 4 -id3v2_version 3 -metadata product_id=BK_POTR_000013 -metadata asin=B017WOTWVO -metadata "narratedBy=Stephen Fry" -metadata book_genre= -metadata major_brand= -metadata minor_version= -metadata compatible_brands= C:\Users\User1\OpenAudible\tmp\BK_POTR_000013_temp.mp3
Dec 04, 2018 12:05:01 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by openaudible** [comment]
The app shouldn't close automatically.. 
It may be crashing and not sending an error, but that is unusual.  Your log doesn't show anything unusual-- so need the part after it crashes. 

A few things: Always use the latest version.. latest is 1.2.9. 

Find the Program Files/OpenAudible directory. Look for any crash logs-- that are named hs_err.... If you see one, post here or on a pastebin. 

Go to the OA working directory. (From prefs, click "Show") Open the tmp directory. 
you'll see a log file called log.txt... It is the full log, and gets created each time the app is started. If it already crashed, open it and paste the last few pages... Maybe there is a reason why it is crashing.  If the app quit normally, relaunch, reproduce, and check the log.

Last question, sort your books by release date. Any in the future (year >2018) ?

**Comment by Crimmy5** [comment]
> Sort your books by release date. Any in the future (year >2018) ? Strangely, that looks like it could cause the problem you're seeing.
> 
> Can you do a Send Bug Report from the Help menu?

Will do so ASAP after the weekend, I'm away from the computer until then I'm afraid.

**Comment by openaudible** [comment]
Found the bug, I think.. Please upgrade to 1.3.0 and let me know. Re-open if not fixed.
