### ISSUE TITLE
Broken JSON files deleted

### ISSUE THREAD

**Issue by rnbwpnt** [openaudible/openaudible#690]
I've been manually cleaning up books.json, and I noticed that when I open OA with an error in books.json (typically a missing }, or something), OA tells me what line number the error is on (yay!), but then it ALSO flattens books.json and I'm left with a file consisting of only {}.

In my case this isn't a huge deal in my case because copious backups, but I suspect this isn't the behavior that's desired.

The actual clobber is done when OA is closed after the error.
 
Observed in 3.0.2.6 on Linux.

**Comment by openaudible** [comment]
Most of the stuff in the books.json file should be considered "read only" and can be written over at any time without notice. 

I suspect the correct thing to do is ask if the user wants to quit or reset their library. Will look into it.

**Comment by openaudible** [comment]
Fixed in 3.1.
