### ISSUE TITLE
One of my books cannot be converted

### ISSUE THREAD

**Issue by robster7674** [openaudible/openaudible#695]
One of my aax files cannot be converted. State is set to "No audio file or download link", yet the book is in the same place as all other books that convert fine. Also, meta information of the book is available, and the Report Book function works fine too.

**Comment by openaudible** [comment]
Unfortunately not all books are downloadable from your Audible account. Podcasts, free, romance series, and some other books are not something you can back up. Generally purchases are, but sometimes Audible will make a book you purchased "free to listen".

Load your library in the browser and look for "Download" buttons next to each book. If there is one next to the "missing" book, click the download button and it should download and be convertible. If there isn't a download button, it isn't something we can download.

**Comment by robster7674** [comment]
The book is this one: https://www.audible.co.uk/pd/The-Theory-of-Money-and-Credit-Audiobook/B078KFWGMD. I could download it fine, so I don't really understand the comment about not being able to back it up.

![image](https://user-images.githubusercontent.com/70331923/130184257-3f3d6280-653e-4425-9850-8cf8d5d1cf17.png)

You mention it "should" be convertible. Well, it isn't, while it downloaded fine. What else could be the cause? Any debug logs I can get?

**Comment by openaudible** [comment]
Strange. Is that screenshot from the OpenAudible browser (CTRL-B)? Either way, go to that page from the OpenAudible browser and click the Download Full link and your book should download and be imported into your library. From there it should be convertible.  Or if you already downloaded the aax file, you can drag and drop it into OpenAudible. 

From there it should be convertible! If not, please send an update and/or send a bug report from the About menu.

**Comment by robster7674** [comment]
Screenshot was from Audible.

"Or if you already downloaded the aax file, you can drag and drop it into OpenAudible." - that's exactly the point: I already downloaded the aax file, and it is visible in OpenAudible browser:

![image](https://user-images.githubusercontent.com/70331923/130254986-694c7f8e-932b-412e-8e95-49e4f9106c4a.png)

The issue is that when I right-click it, both the "Download" and "Convert to MP3" option are greyed out:

![image](https://user-images.githubusercontent.com/70331923/130255074-fa7e07d8-8e34-45b3-b776-b90d5cf06159.png)

I'll submit a bug report from the app.

**Comment by openaudible** [comment]
Ah- Says you are not connected in Library Status. 

1. Controls: Connect to audible (use account that owns the book theory of money).
2. Full Library Rescan
3. See if links populate and the download/convert buttons start working

**Comment by robster7674** [comment]
That worked, thanks for your help!
