### ISSUE TITLE
BrowserNotCreated

### ISSUE THREAD

**Issue by trhr** [openaudible/openaudible#7]
When trying to hit /access, erroring with BrowserNotCreated. Installed from the .sh installer

**Comment by openaudible** [comment]
Thanks for finding that. A weird GTK 3.0 /SWT Browser bug. I am switching all linux users to the WebKit browser engine. Not sure why SWT didn't auto-negotiate a working browser.. If able, pull changes and re-run from terminal.. otherwise, will push a new update 1.11 out soon.
