### ISSUE TITLE
Key for Icons

### ISSUE THREAD

**Issue by ph0rd** [openaudible/openaudible#702]
### Discussed in https://github.com/openaudible/openaudible/discussions/701

<div type='discussions-op-text'>

<sup>Originally posted by **ph0rd** August 28, 2021</sup>
File list has nice icons -- (Audible logo, red dot, green dot, white dot, maybe more).
Where can I find what each icon means? 
Because as you can see in the screen capture, it is confusing and messy (multiple entries with different icons) ![Screenshot 2021-08-28 193114](https://user-images.githubusercontent.com/2100410/131236302-5de4ba3a-4e40-48d5-b73c-582cc4ab24f4.jpg)
I searched discussions, issues, openaudible.org - nothing.
Thanks in advance.</div>

**Comment by openaudible** [comment]
Thanks for the suggestion. Added to the documentation.
