### ISSUE TITLE
Book download and conversion - author's name neither in filename nor in separate folder

### ISSUE THREAD

**Issue by francwalter** [openaudible/openaudible#703]
Hello

I just started to use OpenAudbile 3.0.2 on Windows 10 some days ago and I copied the files of my autiobooks to my backup disk.
OA is creating the files with just the title as filename, e.g. a book from author Albert Bookwriter with the title MyBook would be saved as:

`c:\Users\f\OpenAudible\aax\MyBook.aax `

and if converted to mp3 as well in:

`c:\Users\f\OpenAudible\mp3\MyBook.mp3`

I have many books and I dont recognize them easily by title, I need the author's name too!
I would much prefer that OA creates a folder for each author and save the files there, e.g.:

`c:\Users\f\OpenAudible\mp3\Albert Bookwriter\MyBook.mp3`

or, if this is too hard to program add at least the author in the filename, e.g.:

`c:\Users\f\OpenAudible\mp3\Albert Bookwriter - MyBook.mp3`

At the moment I have to look up each author and add it manually to the file. Yes I can use mp3Tag for it, but this also is some work, which could be avoided.
So could you please add at least an option (in preferences) to add the author's name in filename, so the sorting is easier?
Thanks.

frank

**Comment by ed1023** [comment]
I would 2nd this request.
Ideally I would like to configure both a folder and name in my case I am using mb4.
EG:
base_folder\Author\Series\Author-Series-Series#-Book_Title.mb4

If it helps I am will to through some money into the pot to help get this feature added.

Thanks
Joel

**Comment by openaudible** [comment]
We're working on that commonly requested feature request. Code is in progress and will drop into a beta first and then into the full version.. hopefully by early 2022. 
You will be able to create the folder structure the way you want -- author, genre, series name, title, etc. 
Also working on a tag editor to update meta data in books... and adding chapter names to the meta data.

**Comment by openaudible** [comment]
Closing as a known feature request. Its near the top of the stack.

**Comment by francwalter** [comment]
> Closing as a known feature request. Its near the top of the stack.

Closing the issue when the issue is not solved? Strange. The stack of Feature Requests is not public anyway, so no need to close that issue.
I would expect that the issue would be closed only when really implemented, even only in a beta, but it is now official 3.3 and we are fare away from having any setting in the file saving as it seems to me.

Will this feature be available than only for another payment?
E.g. version 4.0 with some new features and no free upgrade?
This is what I suppose...

**Comment by openaudible** [comment]
You get a year of updates with each license. If we don't have it added in a year from the date of your purchase, a small upgrade fee would be needed to get the latest features. That's how it works. Closing because it isn't a bug report, its a suggestion.

**Comment by francwalter** [comment]
> Closing as a known feature request. Its near the top of the stack.

Now there is 3.4.1 and still that FR didnt make it to the top of the stack? 
On which position is it then?
Is that "stack" somewhere visible to public? At least to the users who payed the license?
Thanks.

**Comment by openaudible** [comment]
We released 3.4.x to address a crashing bug for linux users and to add native Apple silicon support. That caused our schedule to slip a bit. Might be longer now. 
Thanks.

**Comment by francwalter** [comment]
On which position is that FR now in the stack, now with 3.5 released and that FR not yet implemented?
