### ISSUE TITLE
Error importing aax file (mac)

### ISSUE THREAD

**Issue by Macrisu** [openaudible/openaudible#706]
Hello

Big Sur, java - latest versions
I try to import an aax file and I get this error

![error](https://user-images.githubusercontent.com/16325429/132084157-1da4b3ab-f5fb-43da-9ca2-d6a8b1763095.jpg)

**Comment by openaudible** [comment]
Nice find. Will try to find and fix and get into our next beta. If I need a more detailed message from the console window I’ll let you know. Thanks

**Comment by openaudible** [comment]
Fixed in beta. https://openaudible.org/beta
Thanks!
