### ISSUE TITLE
error importing on 3.1.1

### ISSUE THREAD

**Issue by crush123** [openaudible/openaudible#707]
I just updated to 3.1.1 from 2.3.4 (paid again, even though update was apparently free).

I now get an error on import

java.lang.Exception: Expected allowed file format: {filename}

is there a fix or is there a way to go back to old version ?

**Comment by openaudible** [comment]
Fixed in beta. Will be fixed in full version shortly. openaudible.org/beta

**Comment by openaudible** [comment]
Fixed in 3.1.2.. Posted today. Thanks for the report!
