### ISSUE TITLE
Included Titles Unable to Download

### ISSUE THREAD

**Issue by PacManSNT** [openaudible/openaudible#708]
I am currently unable to download certain titles, I believe it is because they are now included free with Audible subscriptions.
For example when trying to download Age of Heroes - The Pantheon Saga Book 1 I get this error message:

Download error:No Library Found for user. for Age of Heroes

Am I doing something wrong, or is there a fix?

**Comment by openaudible** [comment]
Correct. We only can backup books you have purchased, not free titles included with your subscription. It is a limitation we try to state clearly on the home page and documentation. The technology is different for the “free” items.
