### ISSUE TITLE
AppImage for 3.1.2 same as 3.1.1

### ISSUE THREAD

**Issue by antonc42** [openaudible/openaudible#710]
The appimage for 3.1.2 is the exact same as for 3.1.1. The hashes match:

86aa089164273adb9d90396e4a9b6f9a  OpenAudible_3.1.1_x86_64.AppImage
86aa089164273adb9d90396e4a9b6f9a  OpenAudible_3.1.2_x86_64.AppImage

**Comment by openaudible** [comment]
Thank you for finding that. We use a script for building the app image off site and it clearly didn't run correctly. Fixed and appreciated! Glad to see there are some linux users out there!

**Comment by antonc42** [comment]
Looks good now, thanks!

I just found OpenAudible the other day and I was so glad to find that it supported Linux that I immediately bought it. Keep up the great work and thank you for supporting Linux!
