### ISSUE TITLE
Error Starting Application

### ISSUE THREAD

**Issue by davidfhyde** [openaudible/openaudible#711]
Hi! after installing 3.1.2 i am getting this: "error starting application A JOSONObject text must begin with '{" at 1 [character 2 line 1]

**Comment by openaudible** [comment]
Looks like a json preference file is empty or damaged. Any better log from console? Try moving or deleting user/OpenAudible prefs.

**Comment by davidfhyde** [comment]
Thanks!   Deleting some stray Json files fixed the issue. Love the app.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
