### ISSUE TITLE
Download error:No Library Record Found for user. for All Hell Let Loose

### ISSUE THREAD

**Issue by littleblackdog77** [openaudible/openaudible#712]
Audible Australia has added audible plus. This title All Hell Let Loose is one of them. I have added it to my library in the Audible client and downloaded it successfully but Open Audible throws this error (Download error:No Library Record Found for user. for All Hell Let Loose) when trying to download.

Version 3.1.2

**Comment by openaudible** [comment]
Duplicate: https://github.com/openaudible/openaudible/issues?q=No+Library+Record+Found
