### ISSUE TITLE
Cannot convert to MP3

### ISSUE THREAD

**Issue by kleese13** [openaudible/openaudible#718]
My library loads from Audible.  I have a choice on pull down to convert to M4B.  MP3 ghosted.  I selected books I want to convert for MP3 player and app converted to M4B. What next?

**Comment by openaudible** [comment]
Change output preference to MP3 under preferences. We prefer M4B for the best quality and fastest conversion.. but MP3 is also supported.  https://openaudible.org/documentation#Preferences

**Comment by kleese13** [comment]
Thanks for direction.  Works fine now.  Closed
