### ISSUE TITLE
Convert from MP3/others to AAX

### ISSUE THREAD

**Issue by C0rn3j** [openaudible/openaudible#72]
Hey there, looks like this software was made to do the opposite of what I want, but I was wondering if it'd be within scope to also convert normal audio files (MP3, FLAC,..) into AAX?

Looking for ways to listen to music on my Kindle Paperwhite 4, and it looks like the 'easy' way could be to just use the Audible app.

**Comment by openaudible** [comment]
Out of scope. Maybe ffmpeg can convert from mp3 to aa.

**Comment by C0rn3j** [comment]
ffmpeg seems to only support converting FROM aax sadly.

Issue for ffmpeg supporting converting TO aax here: https://trac.ffmpeg.org/ticket/7615#ticket

Kindle-specific thread here: https://www.mobileread.com/forums/showthread.php?t=313397

Maybe by the time someone interested reads this issue someone have developed a workaround other than messing with AAX.
