### ISSUE TITLE
Sync is downloading whole library... Again

### ISSUE THREAD

**Issue by wdpcpa** [openaudible/openaudible#721]
I bought the new version.  But instead of syncing, it is downloading the whole library.  There is no way to pause and change the library destination - at least that I can find.  I guess uninstall and try again?

**Comment by openaudible** [comment]
You can select all and cancel jobs if you want to stop auto download or convert.
Uninstall shouldn't help unless you want to revert to an older version. But we have very few complaints.. make sure your destination directory is online and read/writable.

**Comment by wdpcpa** [comment]
Alright.  I see where it wants to download.  I thought it could read sub files when it would sync but it can't.  It downloads everything to the folder books.  I copied all the MP3 to the subfolder books.  Ran Quick Sync.  Of 316 MP3 files it says it has to download 162.  That isn't correct.  Should be 3 or 4.  Files that it thinks it needs to download are already there.  What do I do.  I just want it to sync files I don't have downloaded.

**Comment by wdpcpa** [comment]
Followup - now show 159 books left to download and then convert.  Most of those are in the library.  What seems to work is to remove them from the "books" subfolder to another folder.  The use the import function to bring them back.  Then they show to no longer need to be downloaded.  And the number of books that need to be downloaded goes down by one.  Not an elegant solution but would work.  Your thoughts?

**Comment by openaudible** [comment]
I was going to suggest that. You can drag and drop all the books from another folder to speed things up.

**Comment by wdpcpa** [comment]
That works.  Probably did it the hard way by moving only the ones showing needing downloading.  Probably could have moved all and imported all.  Been done way faster.  Thanks.
