### ISSUE TITLE
Nested Folder Error Fix

### ISSUE THREAD

**Issue by rnbwpnt** [openaudible/openaudible#722]
When OpenAudible throws an error that it can't do nested folders, it doesn't indicate which top-level folder it failed on. This presents a problem trying to find it when you're importing a large number of folders.

Suggested fix: Print the name of the top-level folder with the failure, so the user can find and fix the issue.

**Comment by openaudible** [comment]
Can you tell me what you did to get the error and provide a copy and paste from the log?

**Comment by rnbwpnt** [comment]
**To reproduce:** Drag and drop a folder containing mp3s (a single book) onto the OA main window, to trigger the automatic join and import function. Inside the folder, include another folder of MP3s (the nested folder).

The error message on the screen produced is:

java.lang.Exception: Importing directory with subdirectories is currently unsupported.

Click OK to dismiss. Import fails.

The error message clearly indicates the problem and I don't have an issue with it, except that it doesn't contain enough information for the user to track the issue down.

**Misbehavior:** The error message does not indicate which folder was being imported when the process failed. Thus, the user must figure it out. In a situation where the user is dumping many folders into OA at once for batch processing, the user doesn't know where to begin again or where to correct the error, and must check every folder manually to see which might be the problem. As a point of reference, I was importing perhaps 200 folders at once, and everything has worked flawlessly except for this one issue.

**Suggested behavior:** Print the name/path of the folder being imported that is throwing the error, to assist the user in more quickly finding and correcting the issue.


Sep 22, 2021 12:15:30 AM org.openaudible.desktop.swt.manager.views.FileDropTarget drop
INFO: drop:DropTargetEvent{DropTarget {} time=274405906 data=[Ljava.lang.String;@3af5f19a x=3208 y=913 item=null operations=1 operation=1 feedback=1 dataTypes={ 144 } currentDataType=144} data=[Ljava.lang.String;@3af5f19a
Sep 22, 2021 12:15:30 AM org.openaudible.desktop.swt.manager.views.FileDropTarget drop
INFO: drop file:/home/rnbwpnt/raid0/Ready For Import/Unspeakable exists=true
Sep 22, 2021 12:15:30 AM org.openaudible.desktop.swt.manager.ImportExport importFiles
SEVERE: java.lang.Exception: Importing directory with subdirectories is currently unsupported.
Sep 22, 2021 12:15:30 AM org.openaudible.desktop.swt.gui.MessageBoxFactory showError
SEVERE: showError
java.lang.Exception: Importing directory with subdirectories is currently unsupported.
	at org.openaudible.desktop.swt.manager.ImportExport.importDirectory(ImportExport.java:466)
	at org.openaudible.desktop.swt.manager.ImportExport._importFile(ImportExport.java:311)
	at org.openaudible.desktop.swt.manager.ImportExport.importFiles(ImportExport.java:135)
	at org.openaudible.desktop.swt.manager.ImportExport$1.run(ImportExport.java:1155)

Sep 22, 2021 12:15:30 AM org.openaudible.desktop.swt.gui.MessageBoxFactory task
SEVERE: showError: Error
java.lang.Exception: Importing directory with subdirectories is currently unsupported.

**Comment by openaudible** [comment]
OK, adding full path to the error message:

                throw new Exception("Importing directory with subdirectories is currently unsupported: "+f.getAbsolutePath());

Thanks for the suggestion. Will be in next beta and next release.. No ETA at the moment.

**Comment by openaudible** [comment]
It's in the current beta and all future releases.
