### ISSUE TITLE
Re-sampling feature request

### ISSUE THREAD

**Issue by stevenleadbeater** [openaudible/openaudible#725]
Hi, it seems as though garmin has a load of issues related to their audio player on watches. If the audio is not 44.1Khz seeking / skipping causes the book player to report the wrong place in the book, often you'll overflow the end of the book and get sent back to the beginning by skipping forward to the midway point. Would it be possible to add a re-sampling feature to the software? The problems are caused by 22Khz files which seem to be highly prevalent on audible as they are mono sources. I've had a look at the open source code. I can get it to run but it looks quite badly out of date and has a few broken bits in it.

**Comment by stevenleadbeater** [comment]
I'd happily help with the fixes if you want, I'm a commercial Java developer with over a decade of experience :)

**Comment by openaudible** [comment]
Happens with both m4b and mp3? 

We probably won’t touch the m4b, but mp3 is re-encoded so maybe an argument change could be added. 

We echo the ffmpeg convert command we use. If you change it and it works, let me know the before and after commands. 

Doubling the frequency seems like it would double the amount of data. You should also try 22.05khz or search around to see what else works or doesn’t. 

Of course let garmin know.

**Comment by stevenleadbeater** [comment]
I've only had the issue with mp3, I can try m4b and see if the issue is reproducible. 

I have converted the files to 44.1khz and the issue goes away, only I've been using audacity to do it which drops a load of the ID3 tag data that you guys are so kindly applying to the files, this causes another issue on garmins in that they don't tell me the progress through the book on the audio playing app if the album art is missing (it's a buggy mess!!!)

It does double the file size when I resample. I was looking at putting something in the settings so users could either:

1/ maintain sample rate of source file (default)
2/ resample to <enter sample rate here>

There is a potential issue around treble clipping and high frequency cut offs when resampling if the source file is encoded higher than the re-sample rate specified. 

Re: letting Garmin know, their forums are riddled with complaints about this and other problems with the book player. They go unanswered and ignored. At this point, even if they do bring out an official app, i'll still pay your licence and use MP3s instead. I like you guys and the work you do too much to leave now :)

**Comment by openaudible** [comment]
Looks like adding an -ar 44100 to the ffmpeg command would work.. but doubling the file size is a terrible idea. You might try -ar 22050 and see if that helps the playback. Unfortunately, we create a metadata file during the conversion which we delete after the command completes, so it may be difficult to re-run the ffmpeg command.. I believe the beta does not delete the metadata file until the app closes. https://openaudible.org/beta

We would strongly suggest buying a playback device that supports m4b, as that is the best codec for quality and conversion speed. 

FYI, we are adding a tag editor to allow you to add album artwork and update tags.. but still "in progress".. which might help with broken playback.. but trying to avoid too many additional features or GUI options to confuse users and induce tech support questions.

**Comment by stevenleadbeater** [comment]
I can probably work around this actually. I can appreciate the position on file sizes and formats. I don't really want to change device though as this is primarily a fitness platform that also "plays audio" I deliberately got it to avoid having to carry extra devices when running. I really do appreciate this isn't an issue you cause :) it's absolutely Garmin's fault and their terrible support is makes it worse. You may have something of a market here though given the lack of audible support and the poor player implementation. For me I can overwrite the ffmpeg binary with a soft link to a script with the extra argument and put the binary elsewhere. For the UI options, maybe a checkbox with "Force Garmin comparability (warning, doubles file sizes)"? It's still papering over the real issue with the audio player  but you guys are much more responsive than Garmin!!!

**Comment by openaudible** [comment]
I added a hack/fix for you.

Create a file called ffmpeg_args_mp3.txt saved to your openaudible prefs directory. (Users/name/OpenAudible/, which should have license.json, etc.)

The contents of the file are any extra arguments used for mp3 conversion, in your case:
```
-ar
44100
```
Only works in the beta for now, but if it works, will keep it in the next release. (link above)

Again, try 22050 if you want to avoid doubling the size.

**Comment by openaudible** [comment]
Let me know how it works.. and closing for now.

**Comment by stevenleadbeater** [comment]
That has literally solved everything, I love you guys and this project, you're awesome :)

**Comment by openaudible** [comment]
Great to hear! Feel free to let the Garmin community know!
