### ISSUE TITLE
Plus Catalogue books block downloading of purchased books

### ISSUE THREAD

**Issue by isr-play** [openaudible/openaudible#726]
Recently added a number of free plus catalogue books to my library.  I also purchased a few books.  

Open Audible fails to download the Plus Catalogue (free) books in library, though it does list them, the State says there is No Library Record found for user.

This blocks purchased books from downloading, ones that are further down the list.

It appears to be an issue for the Audible for windows App which cant play them either.

**Comment by rnbwpnt** [comment]
This has not been my experience. While Plus catalog books can't be downloaded, a mass download of a mix of Plus and purchased books doesn't cause the purchase book downloads to fail.

**Comment by isr-play** [comment]
I purchased 4 and loaded about 80 of the free books to my library, 3 of the purchased books came down and were converted and the 4th I had to select and manually request the download which then worked.

I'm on 3.1.2 and busily removing the Plus Catalogue books from my library to try and free up the clutter.

**Comment by openaudible** [comment]
So yeah, it can get a little tricky if you have a purchase that becomes free. Unfortunately no support for items that are "free".
