### ISSUE TITLE
Audible podcasts not downloaded with podcast title and not grouped together

### ISSUE THREAD

**Issue by isr-play** [openaudible/openaudible#727]
A number of the Audible podcasts only have chapter numbers for each episode and so once processed by OpenAudible are impossible to work out which file goes with which book.

Could the name include the Podcast name or be stored in a sub folder named with the podcast name?

**Comment by openaudible** [comment]
We don't support any podcasts or free books. Only books you purchased. See documentation on Unsupported Books.
https://openaudible.org/docs
