### ISSUE TITLE
Purchased date is not correct in the book list

### ISSUE THREAD

**Issue by CrustyApplesniffer** [openaudible/openaudible#73]
Hello, I've purchased 2 books:
The first one was bought the 27/11/2018 and the second one the 27/05/2018.
In the pruchased column I can see : 2018-11-27 and 2018-27-05.
The date format should not be different from a row to another.
Then, if I sort according to this date, the sort will be correct.
![image](https://user-images.githubusercontent.com/37656975/50009380-26367000-ffb7-11e8-8167-a93db208e0b6.png)

**Comment by openaudible** [comment]
Unfortunately dates are displayed differently depending on the region which makes getting them correctly from the web pages difficult-- as we don't have foreign audible accounts to test. Feel free to submit a bug report from the app that will include your log messages and some html files from audible.fr.

**Comment by CrustyApplesniffer** [comment]
I think I understand what happened.
When Open-audible was connecting to the audible website I've got a message that said : "According to your location, you've been redirected to audible.fr. Do you want to go to audible.com" (in french)
I think I've chosen one time to go to audible.com and at an other time, to stay on the french site. That why I've different date format.
So,... PEBKAC :(
I close the issue.

**Comment by openaudible** [comment]
OK. If anyone starts to see dates with an * before it, it means the app didn't parse the date properly and is probably a bug that could be reported from the Help menu. 

Had to look up PEBKAC. Hah.

**Comment by kai-uwe-rommel** [comment]
But it is definitely wrong. I just came across OpenAudible and like it. I installed it and did a full sync to get the complete list of my audio books. I am in Germany and was connected to the german site. In the audio book info of all books the date is shown as dd.mm.yy but in the view column for some this gets converted into yyyy-mm-dd and for some to yyy-dd-mm.
For example I have one book I bought on January 8th and one I bought today, June 29th. One is shown as 2019-08-01 (in the future ...) and the other as 2019-06-29 (correctly).

**Comment by 85pando** [comment]
Have just seen this same issue.
Audible store is Germany
![OpenAudible](https://user-images.githubusercontent.com/1187085/61182618-4e15b100-a636-11e9-9c4f-ada09439fdfe.png)
Red square shows the date in the format: YYYY-DD-MM
Blue square shows the date in the format: YYYY-MM-DD (which is the correct one in my opinion, and also going from the column sorting)

The corresponding Audiobook information shows the correct dates in the format: DD.MM.YYYY
![OpenAudibleChildrenOfTime](https://user-images.githubusercontent.com/1187085/61182664-d5fbbb00-a636-11e9-8933-b31b97215d67.png)
![OpenAudibleDeathByBlackHole](https://user-images.githubusercontent.com/1187085/61182666-d8f6ab80-a636-11e9-8a4a-015fab21ee1f.png)
![OpenAudibleStrangeDogs](https://user-images.githubusercontent.com/1187085/61182667-dac06f00-a636-11e9-9be8-163281c53a6f.png)

I think the difference here is that "Death by black hole" was purchased on day 14, which can not be converted into a correct month, so it is assumed to be a day.

Damn date format inconsistencies )-:
