### ISSUE TITLE
Could I have a refund?

### ISSUE THREAD

**Issue by tofutiger24** [openaudible/openaudible#731]
Hello! 
I purchased this software so that I could convert my audible books into a format that could be read by my mp3 player. Unfortunately, I have only been able to convert things into mb4 (and it doesn't give me the option of converting to mp3). My mp3 player doesn't play mb4, so the software hasn't been of any use to me. 
My name is kristian cantens and email is kjcantens@tamu.edu
Thanks,
Kristian

**Comment by openaudible** [comment]
The option to convert to MP3 is under preferences, CTRL-, under the Edit Menu. 
Sorry for the confusion.
