### ISSUE TITLE
No checksum for App Image file

### ISSUE THREAD

**Issue by Sleuth56** [openaudible/openaudible#732]
The MD5 sum file doesn't have a check sum for the App Image file.

**Comment by openaudible** [comment]
Can you say where and what the error you're seeing is?

Here is the link for checksums:
https://openaudible.org/downloads/swt_version.json
  "AppImage": {
   "file": "OpenAudible_3.1.2_x86_64.AppImage",
   "size": 138564800,
   "mb": "132.14Mb",
   "version": "3.1.2",
   "platform": "Linux GTK",
   "md5": "0612bc841a273496788e0b996f7f9af7"
  },

Its possible we changed the file but didn't get the checksum updated.

**Comment by Sleuth56** [comment]
No error. I was going to manually check the checksum file in the downloads page on github but it doesn't have a sum for the appimage.

**Comment by openaudible** [comment]
Oh. Usually that is automatically set. I'm sure the app is fine. Thanks for the heads up.
