### ISSUE TITLE
How to Login to Multiple Accounts?

### ISSUE THREAD

**Issue by jasonpatel** [openaudible/openaudible#737]
I bought the paid version as it said you can connect up to 5 Audible accounts.  I cannot figure out how to do that, once logged into your main account the only option I can see related to account is to logout, I simply want to add +1 more account to sync both.

Can you please explain how you do this as cannot see in the documentation.

**Comment by openaudible** [comment]
For now, just log out, then log in as a new user. (Up to 5 is allowed.). We don’t yet have a way to manage multiple accounts or save files in different locations easily. But it is a request.
