### ISSUE TITLE
Library Sync not getting new books

### ISSUE THREAD

**Issue by stefwill** [openaudible/openaudible#740]
Running either quick or full library sync returns the following message:

> "Your library appears up to date! Go buy more Audible books!
> (If new books weren't found, check the console.)"

I have a feeling that the region is the problem.
Looks like the region is switching from AU to US.
```
Oct. 12, 2021 5:35:13 PM org.openaudible.audible.AudibleConnectionState setRegion
INFO: Setting audible region to AU
Oct. 12, 2021 5:35:13 PM org.openaudible.Audible load
INFO: Loading C:\Users\svonw\OpenAudible\books.json
Oct. 12, 2021 5:35:13 PM org.openaudible.Audible checkLibrary
INFO: loaded 123 books.
Oct. 12, 2021 5:35:13 PM org.openaudible.audible.AudibleConnectionState setRegion
INFO: Setting audible region to US
```

**Comment by openaudible** [comment]
Hmm. The audible region is stored (twice) in your OpenAudible credentials.json file. (region and audible_region.) 
So you can inspect that... But I haven't heard of this issue before, so it may just need a log-off and log back on from the OA control menu. (Do you have two accounts?)

Feel free to send a bug from the About menu report if it keeps happening.

**Comment by stefwill** [comment]
Yeah, logout/login seems to have fixed it.
I do have two accounts one in the US and one in AU. Though I don't use the US one at all.
