### ISSUE TITLE
How to log in to Multiple Audible Accounts?

### ISSUE THREAD

**Issue by pakiyabhai** [openaudible/openaudible#741]
Hi,
just bought Open Audible on OSX 

- how do I login to multiple accounts ? 
- Is there a way to all the books across multiple account ?

**Comment by openaudible** [comment]
We do have a feature in progress to manage multiple accounts... but it is not yet in the current version. It is a common request. 
Correct, you can log out of one account and into another account. Hang tight and we'll have an updated version that has better support for switching between accounts. 

Once you've converted your audiobooks, we don't typically offer refunds.
