### ISSUE TITLE
Full Sync download issue

### ISSUE THREAD

**Issue by danieleturcato** [openaudible/openaudible#752]
sync downloads fewer books than I have in my library.
Downloaded 262, in the library about 600.

How can I fix this?

Best Regards

**Comment by danieleturcato** [comment]
Hello, there are no podcast, and and what does free mean? I can only listen
to them with a subscription.

**Comment by openaudible** [comment]
We only allow you to back up your audible purchases. Things that are included "free" with your paid subscription are not something we can back up... Sorry. We try to make this very clear, but it is easy to miss.
