### ISSUE TITLE
Suppress download links

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#756]
I am looking for a simple way to modify the generated web file(s) to:
1. Disallow book downloads perhaps by simply not including the links on any of the web page displays and
2. By default, on the generated file include the book covers, rather than having them optional.

This would let me generate a useable and searchable table of books accessible by web but without fear of web exposure. I have tried unsuccessfully to just protect the generated page with passwords, but am having difficulty doing this on my NAS web server.  

It would be even better if these were options when the app generates the web files!

Great program, works perfectly!

Thanks

**Comment by openaudible** [comment]
The idea is that once we write the index.html file, if you modify it, we won't overwrite it. So the best thing to do is create an index2.html file, edit the html as you want, then copy index2.html -> index.html ... and do that as needed after building the web page. We are not html experts, so we tried to make a simple page.. You can create a small job on fiverr.com and I'm sure someone will offer to make changes for under $20. 

That said, our system isn't perfect. Files may get overwritten.. so keep backups.. and maybe a script to just copy the .json file to your web directory is best.

**Comment by openaudible** [comment]
To disable exporting the files, try editing the OA settings.json file and change webPageIncludeMP3 to false
