### ISSUE TITLE
Australia not working

### ISSUE THREAD

**Issue by openaudible** [openaudible/openaudible#76]
Australia audible does not include the product_id in the html, so OA doesn't load the books. Working on a fix to use ASIN.

**Comment by Knight1** [comment]
Germany too.

If you push a new version please also update the version inside the pom.xml

:)

**Comment by openaudible** [comment]
Thanks Tom,

Your fix is the first real java fix anyone has attempted to submit. I will take a look at the code, but, things have changed significantly to use the browser method.. I can get you access to the current build if needed. 

I took some time off for the holidays and will go through bug reports which is one of the best ways to let me know what is not working. And hoping to get the new version out in the next week or so.

**Comment by openaudible** [comment]
Posted 1.4. Please give a try. Let us know.

**Comment by Knight1** [comment]
```
INFORMATION: Unable to get ASIN: asin=B0777RKWXT,fullTitle=Ein Satz für Zwei (Original Podcast) Alle Folgen zeigen Neuste Folgen anzeigen Neuste Folgen verbergen,author=Ein Satz für Zwei,duration=20 Min.,purchase_date=29.12.18,author_link=https://www.audible.de/search,
```

**Comment by rawdamedia** [comment]
Still not working for Australia.

**Comment by openaudible** [comment]
Someone posted a bug report from AU and was able to reproduce and possibly fix for 1.4.1. which was posted. Please confirm and close if its working.

**Comment by openaudible** [comment]
Closing this... Feel free to re-open if still seeing problems in AU. Submit a bug report from the tools menu and mention AU if any issues.

**Comment by Knight1** [comment]
It is mentioning something. But every audible original (Original podcast) is only the main page and not the download page itself. 

```
Jan 27, 2019 8:34:53 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFORMATION: Empty Product ID:
asin=B078NSXLZY
fullTitle=Die Kolumnisten - Bettina Rust (Original Podcast) Alle Folgen zeigen Neuste Folgen anzeigen Neuste Folgen verbergen
author=Bettina Rust
duration=10 Min.
purchase_date=29.12.18
author_link=https://www.audible.de/search
```

It mentions in German to see all episodes :)

```
INFORMATION: invalid author link on Die Kolumnisten - Bettina Rust (
Jan 27, 2019 8:42:03 PM org.openaudible.Audible ok
```

Also for example I can not download "Star Trek Titan 1: Eine neue Ära" because it is not on the page I guess due to the German ä.
