### ISSUE TITLE
Converting AAX Files Already Downloaded

### ISSUE THREAD

**Issue by staylor105** [openaudible/openaudible#761]
Issue #730. How does deleting the MP3 files answer my question?

I want to convert the aax files I have already downloaded into  mp3 format.

**Comment by staylor105** [comment]
Correction. Issue #760.

**Comment by staylor105** [comment]
Convert to MP3 is greyed out. It won't let me convert books I have already
downloaded.

-- Scott Taylor
-- DSP Systems Inc.
-- 3338 Bryan Ave.
-- Simi Valley, CA 93063
-- 805-582-1954

**Comment by openaudible** [comment]
Is convert to m4b enabled?

**Comment by staylor105** [comment]
It doesn't seem like you are addressing my question.

I set it to AAX Files. It shows the files I have on my local drive.

Under Actions, Convert to MP3 is greyed out.

How do I convert AAX files already downloaded to MP3?


-- Scott Taylor
-- DSP Systems Inc.
-- 3338 Bryan Ave.
-- Simi Valley, CA 93063
-- 805-582-1954

**Comment by openaudible** [comment]
You didn't answer whether you set the output format to MP3 under the preferences (CTRL-,).
That should make Convert to M4B disabled and MP3 enabled. Send a bug report from the help menu if you're still stuck.

**Comment by staylor105** [comment]
M4B is disabled. It is set to MP3.

-- Scott Taylor
-- DSP Systems Inc.
-- 3338 Bryan Ave.
-- Simi Valley, CA 93063
-- 805-582-1954
-- 9:10:55 AM 11/5/2021

 You didn't answer whether you set the output format to MP3 under the preferences (CTRL-,).
 That should make Convert to M4B disabled and MP3 enabled. Send a bug report from the help menu if you're still stuck.

 —

**Comment by openaudible** [comment]
Then I'm not sure why. I can't see your screen so it is impossible to know what you are doing.

You select an AAX file you're trying to convert to MP3 from the OA book table.. what does it AudioBook Info State: line?

Is "Show MP3" an option?
