### ISSUE TITLE
Sticky header line on web page output

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#763]
Prior to v 3.2 (MAC),  the Page header titles on the web page output were sticky, now they move upscreen when the page is scrolled, so, sorting on a column is only possible when at the top of page - awkward if the page is a thousand lines long.  

Either make them sticky, or put some mechanism on page to be able to quickly return to the top of page

**Comment by openaudible** [comment]
I'm looking at the history of file changes and there haven't been a lot of changes in 2021. I'm not sure what happened.
A good sticky header would be nice.. But they aren't easy with the table. I know its been discussed in other issues.
Open to suggestions on better headers and web layout. Thinking maybe a contest where people can submit their html and we can include several different variants people can choose from.

**Comment by openaudible** [comment]
This might be the bug we found where your HTML files were getting pulled out of whatever version of Openaudible was in your Applications directory. 
In any case, to keep my open issues to a minimum, will mark this as a feature request. 
Thanks!
