### ISSUE TITLE
Any Betas to test for Multiple Account?

### ISSUE THREAD

**Issue by pakiyabhai** [openaudible/openaudible#766]
Hi,
I constantly have to juggle between multiple accounts , worst I keep getting logged out from each account & then 2FA verification for each account has to be done. Can at least "logged in" state be preserved ? 

Can I help out with any betas to test?

**Comment by openaudible** [comment]
Thank you for the reminder. Looking into it now..

**Comment by openaudible** [comment]
I'm going to mark as a "feature request". It isn't an easy addition. But we've started on the UI as well as have support in the credentials.json file for multiple accounts.. but it needs a lot of work to dial it in so errors don't pop up.

**Comment by pakiyabhai** [comment]
Thanks a lot

**Comment by openaudible** [comment]
There is now! https://openaudible.org/beta !
