### ISSUE TITLE
Don't update library

### ISSUE THREAD

**Issue by fpusersuggest** [openaudible/openaudible#767]
Version 3.2
website: audible.IT

Hello, I have version 3.2 downloaded yesterday.
yesterday I added some books to my library under audible.it but openaudible seems not to synchronize the list with the last books added. I thoguht the problems was that the demo version has limit of 300 books but after removed some untill to have 274 books the problem persist.

**Comment by openaudible** [comment]
We just made a change for Italy and Japan Audible.. can you try https://openaudible.org/beta

**Comment by fpusersuggest** [comment]
Yep, thanks, it works very well.

**Comment by fpusersuggest** [comment]
if you are interested I can translate your app into italian.

**Comment by openaudible** [comment]
Oh, just noticed we didn't include Italian in our translations. What a nice offer. I am letting Google Translate do the translations. Check out v 3.2.1 production for an update with Italy translations. 

Thank you for the reports!
