### ISSUE TITLE
Mac Beta 3.2.0.2  still not showing Book Covers in 's files

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#769]
Loaded 88 books from Audible site, converted to m4b - I made sure my local library and the web library were empty before starting.

All downloaded and converted and in every case, the files at all stages show an image in the metadata, but generated web page still shows no image if the filename contains 's. !!!!

Can you fix this and test it before publishing?  88 books took over an hour to test, I have over a 1000 books on the Audible site and would really like this to work properly as it used to work before version 3.2!!

**Comment by openaudible** [comment]
You found an obscure mac bug. It was pulling the web template files from an older application by mistake. Fixed.
Don't test on Mac much. 
https://openaudible.org/beta
I think you can just delete the web "assets" directory and rebuild the web page. No need to encode,download,etc. Was just a display issue where the web javascript file didn't get the fix.

**Comment by oboe45** [comment]
Yes, it worked, going to load the next batch of files to be sure it works!
With luck should be completely reloaded by end of day Saturday!  Thanks

**Comment by openaudible** [comment]
Cool. Thank you for the reports. Can you close any issues that are "resolved"?
Posting 3.2.1 final.
