### ISSUE TITLE
[UK] OpenAudible keeps getting US books

### ISSUE THREAD

**Issue by IOI-655321** [openaudible/openaudible#77]
I'm on the latest version 1.3.0.

When doing a quick/full library sync my book list is often populated by non UK versions (no UK suffix on product ID) sometimes these are duplicated, sometimes no UK versions are shown.

Other times it doesn't read from my AAX files correctly and doesn't show all currently downloaded books and therefore cant convert some that are already downloaded.

If I import aax files manually it still seems to show these as the non UK versions in the list despite the files having the UK suffix.  It also sometimes duplicates these even though I only imported once.

**Comment by IOI-655321** [comment]
Ok I reinstalled the program completely but did copy over my aax files.  All aax files are showing the UK suffix however.

Will await and feedback on new version.

Keep up the great work.

**Comment by openaudible** [comment]
1.4 has been posted. I am preventing duplicates if the ASIN is the same and keeping the foreign (UK) version.. fingers crossed.. let me know.

**Comment by openaudible** [comment]
Reopen this ticket if you're still seeing it in version >= 1.4
