### ISSUE TITLE
Images incorrect - Mac Version 3.2.1

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#770]
1.  All of the blank cover pages ('s) have been resolved in this version.
2. A minor issue, but an error,  there are several pairs of books in my library, for example, with titles like "Silent Scream - An Anna Travis Mystery". and "Silent Scream - Detective Kim Stone Crime Thriller, Book 1" which show up on the web page with the same image even though they are different books and have different images in their metadata.  Both books exist on the Audible site, I own both and both download separately for playback, but the title gets cobbled by whatever algorithm is used to mess around with the title, so they show up correctly as separate books on the web page generated by OpenAudible but with a common image cover.  I have 5 examples of books like this from my Audible library.

Not a big deal, but if you ever look at the method of changing the title, it would be nice to fix the issue.

Other than that, the download and reconversion worked like a charm, albeit a very slow charm!

Thanks

**Comment by openaudible** [comment]
Ok. That will probably get resolved in next beta but might mean duplicates in the web dir… lol. Thanks for the good report.

**Comment by openaudible** [comment]
Posted a beta that should fix that item.. but you may get some file name conflicts if you don't wipe the web dir fully. 
https://openaudible.org/beta
