### ISSUE TITLE
windows 11 - can't join audio files

### ISSUE THREAD

**Issue by darksidemilk** [openaudible/openaudible#771]
Whenever I try to do a join audio files of a folder of mp3's, it inspects them all, then just gives a java pointer exception:
![image](https://user-images.githubusercontent.com/7743340/140624176-7c4d6285-fab2-4893-a17a-a7adc5508aa1.png)

I also tried some of the audio files I know worked for joining with openaudible before I upgraded to win 11 with the same result.
I also tried a few different versions of open audible 3.2.1, .3.1.2 and also tried going to pre-3 at 2.3.5 all with the same result.
Also tried windows compatibility mode, different mp3 quality level settings, and running as admin.

Perhaps microsoft changed something in win 11 that breaks the conversion method? Or maybe I'm missing something else.

**Comment by openaudible** [comment]
Not sure what changed.

Can you copy and paste the full error about NullPointerException from the console log window (CTRL-E).. and or send a bug report from the help menu after trying again? 

Is it a stripped down version of windows 11?

**Comment by Kuroo2021** [comment]
Try to upgrade your java to the latest version.

**Comment by openaudible** [comment]
A java jre is included with the windows installation. Would be hard for a user to change.. 
I was able to download and install windows 11. All seems to work.
Looks like your bug is due to missing mp3 tags in the original audio files. Which is still a bug. Will have a beta fix soon.

**Comment by openaudible** [comment]
Posted a beta that may/hopefully fix your bug. Any feedback appreciated:
https://openaudible.org/beta

**Comment by openaudible** [comment]
Please re-open if that doesn't solve the problem.

**Comment by darksidemilk** [comment]
Wow, thank you for the prompt replies. I only just saw this. I will give this a try when I get home tonight.

**Comment by darksidemilk** [comment]
Sadly it did not fix the issue. I sent a bug report from the program.

**Comment by darksidemilk** [comment]
I upgraded to 3.2.2 and was then able to join audio files that worked previously (wasn't working before in windows 11, worked in 10). But the ones that I found the problem still wouldn't join. I added some basic album artist and album id3 tags (I'm not actually sure how they lost their tags) and tried again and then it worked as expected.
So there is still a bug that it fails if id3 tags are missing, but it does work in windows 11 other than that.

**Comment by openaudible** [comment]
Ok. Wasn’t sure. 

Can you just recreate the problem in the latest release version and send bug report from the about/help menu? 

Thank you!

**Comment by darksidemilk** [comment]
bug request sent

**Comment by openaudible** [comment]
Great reports. Thank you. Should be fixed in the latest beta. 
https://openaudible.org/beta

**Comment by openaudible** [comment]
Please comment or re-open if this issue isn't solved in the beta.
