### ISSUE TITLE
Error Converting Failed To Convert

### ISSUE THREAD

**Issue by Kuroo2021** [openaudible/openaudible#773]
I have 7 files that I downloaded from the main place and left my system to convert all my books. Upon coming back I saw that they won't convert. I reboot the system clear out my temp folder and check. Ran OpenAudio as admin. But all my other books but these 7 just won't convert Attach the log file from OA. and a bug report as well from the software.
[Logs.txt](https://github.com/openaudible/openaudible/files/7491548/Logs.txt)
.

**Comment by openaudible** [comment]
The error is in ffmpeg, which is summarized as vbrsf[sfb] >= vbrsfmin[sfb], file vbrquantize.c, 
Googling, I see a few unresolved errors.
Can you change the convert format to M4B in the prefs and see if the files convert properly?

**Comment by Kuroo2021** [comment]
I'm able to convert it was the M4B files, but the player I used only played mp3 and mp4 files.

**Comment by Kuroo2021** [comment]
I upgraded to the beta 3.2.1.1 beta did the test again and with M4B it did them all but in the MP3 test, the same 7 didn't convert. I download a fresh new file from Audible to make sure maybe the file is not having issues. It's weird the same 7 are having issues from a fresh download and upgrade of the software. I uploaded the bug report and mark it with this ticket number.

**Comment by openaudible** [comment]
Hmm. Can you send an aax file via https://openaudible.org/check.html and I’ll get an ffprobe report. Seems like a possible bug in the ffmpeg mp3 encoder. Which could be a bummer. But might be able to figure it out.

**Comment by Kuroo2021** [comment]
> Hmm. Can you send an aax file via https://openaudible.org/check.html and I’ll get an ffprobe report. Seems like a possible bug in the ffmpeg mp3 encoder. Which could be a bummer. But might be able to figure it out.

I went ahead and upload what I could of the 7 for samples you can play with.

**Comment by openaudible** [comment]
Thank you for the bug report!  

OK.. looks like an ffmpeg with an out of date mp3 encoder library. Maybe set quality to 4 and that might help. Will take a few days to get a fix figured out.

**Comment by Kuroo2021** [comment]
Ya I try quality level 4 and still failed. No problem hopefully help fix a bug, just so weird only the same 7 are the ones that are affected out of the 172 books I have, so weird.

**Comment by openaudible** [comment]
It was a rare bug that has surfaced in the past. 
Was able to recompile a new version tonight (usually takes longer!) and got a beta out. 
https://openaudible.org/beta
That should do it.  Please re-open if it doesn't.
