### ISSUE TITLE
Unable to update Docker image

### ISSUE THREAD

**Issue by WKirchner** [openaudible/openaudible#774]
I am running Openaudible in docker. The current version is 3.0.1. I get the message of a new version is available. I have a valid license. But I have been unable to get the image to update. Even if I manually attempt to get the new image it keeps giving me the same version. 

Am I missing something?

Linuxserver.io version:- f488be66-ls10 Build-date:- 2021-06-26T00:26:10-04:00

**Comment by openaudible** [comment]
Try rebuilding the docker image. (Should keep your volumes, but make a backup!)


docker stop openaudible
docker rm openaudible
Then docker pull and run.

**Comment by WKirchner** [comment]
I just tried that. I am not worried about the data so I removed everything and the image. It downloaded the same version again. I am using docker-compose. Below is what I am using. 

### OpenAudible - Audible Converter
  openaudible:
    image: openaudible/openaudible:latest
    container_name: openaudible
    restart: unless-stopped
    networks:
      t2_proxy:
        ipv4_address: 172.19.0.100
#    networks:
#      - t2_proxy
    security_opt:
      - no-new-privileges:true
    ports:
      - "$OPENAUDIBLE_PORT:3001"
    volumes:
      - $DOCKERDIR/openaudible:/config
      - /openaudible:/openaudible
    environment:
      PUID: $PUID
      PGID: $PGID
      TZ: $TZ

**Comment by WKirchner** [comment]
ubuntu:~/docker$ sudo docker pull openaudible/openaudible:latest
latest: Pulling from openaudible/openaudible
Digest: sha256:efadb5788688332b4438769d01043d9f60e40ab44e1e7b0b4efbc30d56e26112
Status: Image is up to date for openaudible/openaudible:latest
docker.io/openaudible/openaudible:latest

**Comment by openaudible** [comment]
Oh, looks like Docker doesn't automatically update unless you build from the source Dockerfile.

I updated the docker hub version. That should fix it.

**Comment by openaudible** [comment]
Confirmed downloading the update using the built-in web browser doesn't work.  No idea why not. 
From terminal, you can upgrade... First open the terminal by right-clicking the desktop and selecting "Terminal" 

```
cd /tmp
wget https://openaudible.org/latest/OpenAudible_x86_64.sh -O OpenAudible.sh
sudo sh OpenAudible.sh -q -overwrite -dir /usr/local/OpenAudible
rm OpenAudible.sh
```

I looked into installing the latest when the program starts.. but got a little bit stuck... For now will update the latest version after a new release.

**Comment by WKirchner** [comment]
I was able to get it updated to 3.2.1. I see that a new update 3.2.2 is available. I will wait and see if my image updates automatically.
