### ISSUE TITLE
Replace MP4 File Extension with aax?

### ISSUE THREAD

**Issue by EricBergerud** [openaudible/openaudible#775]
I've got tweny five books in audible. Since a couple of weeks ago, downloads have all been in mp4 format - not aax. This is true even for books purchased years ago. 

OpenAud will not import an MP4 file. Someone on Reddit said the MP4 and AAX are very close and if you simply changed the file extension it would load into Open Audible. And that does work. 

Is this a solution for problem that I have (at least in the SF Bay Area in California) of Audible downloading MP4 and not AAX? (Might add - Audible shows the file name before download, so this has nothing to do with OpenAudible.

I haven't tried direct download - would OpenAudible accept the format used by Audible regardless?

Would like any insight. Thanks.

**Comment by openaudible** [comment]
You can drag and drop mp4 files onto OpenAudible and they should convert. 

What are you using to download them?

openaudible has an automatic download system that is the recommended way to download and convert your purchased books.
