### ISSUE TITLE
An error occurred opening an internal web browser. 

### ISSUE THREAD

**Issue by blurfl** [openaudible/openaudible#776]
beta 3.2.1.1 posts "An error occurred opening an internal web browser. " when trying to log into US-audible.com, shows 'Error code: null".  The result is same for either email uname or legacy Audible uname. OS is macos 11.6.1 beta2
Note that releae 3.2.1 works correctly.

**Comment by openaudible** [comment]
Maybe fixed in latest beta: 3.2.1.2 https://openaudible.org/beta

**Comment by blurfl** [comment]
beta: 3.2.1.2 works as expected. That was fast!

**Comment by openaudible** [comment]
Great! Good report made it easy to find the newly untested lines of code. :)
