### ISSUE TITLE
error with depenencies

### ISSUE THREAD

**Issue by x0rld** [openaudible/openaudible#778]
![image](https://user-images.githubusercontent.com/45242856/141101359-014704f2-3e15-4efe-b7ff-634c17eeb818.png)
I just run intellij and there is an error while downloading dependencies

**Comment by openaudible** [comment]
I assume that is the audio tagged. Seems to have gone down. Just download the jar and use that. Or add the source code and remove the dependency. The 1.x version is legacy and not recommended except as an example what we started out doing. The latest full version is closed source.
