### ISSUE TITLE
View As Webpage Doesn't Include Imported Books

### ISSUE THREAD

**Issue by Puddl36lum** [openaudible/openaudible#783]
I have a ton of audiobooks from Downpour (DRM free) that I imported into Open Audible but when try generating a webpage, it doesn't add the imported books.  Anyone else run into this issue?

I don't know exactly how the webpage is generated so it might be operator error.

TIA

**Comment by openaudible** [comment]
I can't recreate the problem-- I have a test library with imported books and they all get exported to the web page.

It should export them if there is a mp3 or m4b file associated with the book. 
Anything in the error log when you export to web page? (CTRL-E)
Anything errors shown in the browser console window?  (F12)
How many books are shown in the Library Status panel (Books:) and about  how many show in the web page?

**Comment by openaudible** [comment]
Closing as unconfirmed and no response. 

Feel free to attempt again and do a bug report from the Help menu.
