### ISSUE TITLE
Error Converting Books

### ISSUE THREAD

**Issue by kjb11** [openaudible/openaudible#785]
I just downloaded the software today and successfully converted several books, but I keep getting an error when trying to convert five different books. The error I get is as follows:

Error converting: Invalid key for hash=000000002c0a9de07266fa3cc4456e91b5be7ed9 key= mode=remote_only

Any help greatly appreciated!

**Comment by openaudible** [comment]
That is an aaxc file that is not compatible. Either it not downloaded by 3.2.2 or it recently became a "free" book and is no longer considered a "purchase" that can be backed up. Then delete the book by right-clicking, delete book.. then do a full library rescan and see if you can re-download it.

**Comment by kjb11** [comment]
I just purchased this program and the books yesterday so I wouldn’t think
there would be compatibility issues. I’m using version 3.2.2 and I just
tried redownloading the books and it is giving me the same error.

One thing I’ve noticed is that before showing me the error message, a box
pops up with a Personal Use Notice (0 of 10) and says “OpenAudible is meant
for personal use to back up content you have purchased. Your OpenAudible
license is for ‘family use’ and can be used to convert audiobooks on up to
5 Audible accounts.” Not sure what this has to do with the error, as I only
have one Audible account linked.

**Comment by openaudible** [comment]
Ok. When you view the book in your list of books in the Audible web page under "Library", there needs to be a "Download" link next to the book for it to be downloadable. If its missing, it may be a free book, podcast, or something else not considered "purchased".

That message you can ignore. In fact it shouldn't be shown until you've linked a couple of accounts.

**Comment by kjb11** [comment]
I actually downloaded the five books directly to my computer from the
Audible website before linking my Audible account, so they are all
considered downloadable. I imported the file into OpenAudible both ways and
I get the same error message either way.

**Comment by openaudible** [comment]
You need to download them from the OA app. 
I have a feeling they are Aaxc files, which are not easily convertible. They have to be books you’ve purchased, not books that are free with your membership.

**Comment by kjb11** [comment]
They are definitely books I purchased, and I just checked their properties
and they are all .aax files, not .aaxc.

**Comment by openaudible** [comment]
Can you upload one of them to https://openaudible.org/check.html ? We'll get a report that can give us a better clue as to what is happening.

**Comment by Nebumix** [comment]
I have the same issue. 
When I try to convert books I downloaded I have this error.

 },
 "error": {
  "result": 1,
  "cmd": "/Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffmpeg -audible_iv fbd0a05d64978d53c11b10828b7946e4 -audible_key 2d413c723a5778265e0d3c77daadc47c -i \"/Users/m/Library/OpenAudible/aax/Su Nettuno piovono diamanti.AAX\" -i \"/Users/m/Library/OpenAudible/tmp/Su Nettuno piovono diamanti.AAX.txt\" -map_metadata 1 -map_chapters 1 -map_metadata 0 -metadata:s:v \"title=Album cover\" -metadata:s:v \"comment=Cover (front)\" -codec:a libmp3lame -qscale:a 4 -id3v2_version 3 /Users/m/Library/OpenAudible/tmp/BK_MDOR_000817IT_temp.mp3 ",
  "stderr": ["ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers,   built with Apple clang version 11.0.0 (clang-1100.0.33.8),   configuration: --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libaom --enable-libgsm --enable-librav1e --enable-appkit --enable-avfoundation --enable-coreimage --enable-audiotoolbox,   libavutil      56. 51.100 / 56. 51.100,   libavcodec     58. 91.100 / 58. 91.100,   libavformat    58. 45.100 / 58. 45.100,   libavdevice    58. 10.100 / 58. 10.100,   libavfilter     7. 85.100 /  7. 85.100,   libswscale      5.  7.100 /  5.  7.100,   libswresample   3.  7.100 /  3.  7.100, Unrecognized option 'audible_iv'., Error splitting the argument list: Option not found"]
 }
}
nov 26, 2021 11:33:51 AM org.openaudible.util.queues.ThreadedQueue jobError
INFORMAZIONI: ConvertQueue error processing convert Su Nettuno piovono diamanti item Su Nettuno piovono diamanti
java.io.IOException: Failed to convert /Users/m/Library/OpenAudible/aax/Su Nettuno piovono diamanti.AAX. Check console for details.
	at org.openaudible.convert.ConvertJob.convertFile(ConvertJob.java:452)
	at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:635)
	at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:711)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:484)

**Comment by openaudible** [comment]
We posted a fix at https://openaudible.org/beta
Can you give it a try and let me know if that fixes it?

**Comment by Nebumix** [comment]
For me it works fine.

Is it normal it cannot download podcast series?

**Comment by openaudible** [comment]
Great to hear! 
Podcasts are not allowed
Thank you very much.

**Comment by Nebumix** [comment]
thanks

**Comment by openaudible** [comment]
If you’re on a Mac in Italy or Japan region a bug fix has been posted to https://openaudible.org/beta

**Comment by openaudible** [comment]
We did find one or two bugs. Fixed in 3.3 release. Hopefully fixed!
