### ISSUE TITLE
I bought the licenze but i can't converte te AAX

### ISSUE THREAD

**Issue by SergioDeSimone** [openaudible/openaudible#786]
Please i just bought the licenze, i received the licence code and intent it. but i still have the error "ERROR DURING CONVERSIONE: FAILED TO CONVERT /Users/..... "
Please can you help me?

**Comment by Nebumix** [comment]
I have the same problem, I also bought the license and I cannot convert aax files.
I have this error


},
"error": {
"result": 1,
"cmd": "/Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffmpeg -audible_iv fbd0a05d64978d53c11b10828b7946e4 -audible_key 2d413c723a5778265e0d3c77daadc47c -i "/Users/m/Library/OpenAudible/aax/Su Nettuno piovono diamanti.AAX" -i "/Users/m/Library/OpenAudible/tmp/Su Nettuno piovono diamanti.AAX.txt" -map_metadata 1 -map_chapters 1 -map_metadata 0 -metadata:s:v "title=Album cover" -metadata:s:v "comment=Cover (front)" -codec:a libmp3lame -qscale:a 4 -id3v2_version 3 /Users/m/Library/OpenAudible/tmp/BK_MDOR_000817IT_temp.mp3 ",
"stderr": ["ffmpeg version 4.3.1 Copyright (c) 2000-2020 the FFmpeg developers, built with Apple clang version 11.0.0 (clang-1100.0.33.8), configuration: --enable-version3 --enable-sdl2 --enable-fontconfig --enable-gnutls --enable-iconv --enable-libass --enable-libdav1d --enable-libbluray --enable-libfreetype --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopenjpeg --enable-libopus --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libsrt --enable-libtheora --enable-libtwolame --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libxml2 --enable-libzimg --enable-lzma --enable-zlib --enable-gmp --enable-libvmaf --enable-libvorbis --enable-libvo-amrwbenc --enable-libmysofa --enable-libspeex --enable-libaom --enable-libgsm --enable-librav1e --enable-appkit --enable-avfoundation --enable-coreimage --enable-audiotoolbox, libavutil 56. 51.100 / 56. 51.100, libavcodec 58. 91.100 / 58. 91.100, libavformat 58. 45.100 / 58. 45.100, libavdevice 58. 10.100 / 58. 10.100, libavfilter 7. 85.100 / 7. 85.100, libswscale 5. 7.100 / 5. 7.100, libswresample 3. 7.100 / 3. 7.100, Unrecognized option 'audible_iv'., Error splitting the argument list: Option not found"]
}
}
nov 26, 2021 11:33:51 AM org.openaudible.util.queues.ThreadedQueue jobError
INFORMAZIONI: ConvertQueue error processing convert Su Nettuno piovono diamanti item Su Nettuno piovono diamanti
java.io.IOException: Failed to convert /Users/m/Library/OpenAudible/aax/Su Nettuno piovono diamanti.AAX. Check console for details.
at org.openaudible.convert.ConvertJob.convertFile(ConvertJob.java:452)
at org.openaudible.convert.ConvertJob.convert(ConvertJob.java:635)
at org.openaudible.convert.ConvertJob.processJob(ConvertJob.java:711)
at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:484)

**Comment by openaudible** [comment]
I think this only affects Mac users in Japan and Italy. Will have a fix soon. If you have a pc, try that.

**Comment by openaudible** [comment]
A new beta fixes it. https://openaudible.org/beta

**Comment by openaudible** [comment]
Should be fixed in 3.3 release.
