### ISSUE TITLE
Unable To Connect To audible.com

### ISSUE THREAD

**Issue by goldharv** [openaudible/openaudible#787]
I have been usiing Open Audible for several years on my OSx machine. I just downloaded and installed Open Audible on my Ubuntu 20.04 machine. I purchased a new license. However, I am unable to log into audible.com through the application on Ubuntu. When I attempt to the login screen doesn't indicate anything and the Connected: status in the main window stays at "No".

I have of course logged into audible.com with my user email address and password using your built in browser (ctl+b) and brave browser. From the Ctl-b browser, I have selected "Account Details" on audible and entered my email and password to get to my account details page.

The "Software Verification" check box no longer appears to be on the account details page.

**Comment by openaudible** [comment]
Try
```
sudo apt install gstreamer1.0-plugins-bad
```

**Comment by goldharv** [comment]
Thanks. That fixed it.

**Comment by gottifire** [comment]
> Try
> 
> ```
> sudo apt install gstreamer1.0-plugins-bad
> ```

Can you explain this? I think I might be having the same issue

**Comment by openaudible** [comment]
We just got a good report of a similar bug affecting windows users.
If you're on Windows, please try the beta version:
https://openaudible.org/beta 
And we'll have a final fix in 3.5.5 when it is released shortly.

**Comment by gottifire** [comment]
> We just got a good report of a similar bug affecting windows users. If you're on Windows, please try the beta version: https://openaudible.org/beta And we'll have a final fix in 3.5.5 when it is released shortly.

Thank you for commenting. 

Happens with the newest beta as well

**Comment by openaudible** [comment]
Shoot.
Can you do us a favor.. it's really hard to reproduce on our end.. but if you can restart the app, try to connect, and copy and paste the last part of the console window (CTRL-E) to us.. it should say something about opening an EDGE browser. and perhaps some kind of error.


Another solution is to define a windows environment variable:
SWT_BROWSER=0


The alternative is to install webview2 from microsoft..
https://developer.microsoft.com/en-us/microsoft-edge/webview2/

**Comment by gottifire** [comment]
> Shoot. Can you do us a favor.. it's really hard to reproduce on our end.. but if you can restart the app, try to connect, and copy and paste the last part of the console window (CTRL-E) to us.. it should say something about opening an EDGE browser. and perhaps some kind of error.
> 
> Another solution is to define a windows environment variable: SWT_BROWSER=0
> 
> The alternative is to install webview2 from microsoft.. https://developer.microsoft.com/en-us/microsoft-edge/webview2/

I'm not sure I'm following you on what you're asking about the console window. I don't see anything that says anything about an error or the EDGE browser

**Comment by gottifire** [comment]
Not following what you mean by "beta 2..." but I just installed the latest beta that looks like it was uploaded today 3.5.4.2

This version is the first one showing an error. Can't copy any of the text so I'm including a screenshot or the error text. Looks like there is more at the bottom but I'm unable to scroll down to it or select any of it. 

I'm assuming this is what you mean by "last line of text". Or are you talking about the text in the "Summary" area? Or maybe the diagnostics
![screenshot](https://user-images.githubusercontent.com/57510636/169100549-5a568ce9-9ae7-48ec-8ce8-13a6c6d77393.png)
?

**Comment by gottifire** [comment]
> Thank you for the screenshot. That helps. I think you can hit "escape" to close that dialog. (We'll fix it.)
> 
> I meant copy and paste from the OpenAudible Console, which is accessible from the File Menu (Console CTRL-E). You can send here or email to openaudible at email dot tg.
> 
> With beta 2 (3.5.4.2), we added a "test" to see if WebView2 was available on your system and it failed to detect that your system didn't have it installed.. so we will make another attempt to do a beta 3 today, which will be 3.5.4.3 on the beta page.
> 
> The dilemma is we would prefer to use the Edge widget for most Windows users.. but on some systems (yours) we can't know in advance if it is not available. So we need to fall back to using IE gracefully.

Okay I see my bad. I do have Edge on my computer. I'm installing the webview2 program now. 

Here's all the text from the console:

May 18, 2022 12:31:59 PM org.openaudible.desktop.swt.gui.GUI <init>
INFO: Starting OpenAudible build 3.5.4.2 for win32 swt 4944 jvm 17.0.1
May 18, 2022 12:32:00 PM org.openaudible.Directories load
INFO: Directories:{
 "META": "C:\\Users\\John\\OpenAudible",
 "APP": "C:\\Program Files\\OpenAudible",
 "WEB": "C:\\Users\\John\\OpenAudible\\web",
 "TMP": "C:\\Users\\John\\OpenAudible\\tmp",
 "BASE": "C:\\Users\\John\\OpenAudible"
}
->{
 "META": "C:\\Users\\John\\OpenAudible",
 "APP": "C:\\Program Files\\OpenAudible",
 "MP3": "",
 "ART": "",
 "PDF": "",
 "WEB": "C:\\Users\\John\\OpenAudible\\web",
 "TMP": "C:\\Users\\John\\OpenAudible\\tmp",
 "AAX": "",
 "M4B": "",
 "M4A": "",
 "BOOKS": "",
 "BASE": "C:\\Users\\John\\OpenAudible"
}
May 18, 2022 12:32:00 PM org.openaudible.Directories isValid
INFO: Not found:C:\Users\John\OpenAudible\mp3
May 18, 2022 12:32:00 PM org.openaudible.Directories isValid
INFO: Not found:C:\Users\John\OpenAudible\m4a
May 18, 2022 12:32:00 PM org.openaudible.Directories isValid
INFO: Not found:C:\Users\John\OpenAudible\m4b
May 18, 2022 12:32:00 PM org.openaudible.Directories isValid
INFO: Not found:C:\Users\John\OpenAudible\pdf
May 18, 2022 12:32:00 PM org.openaudible.Directories getPrefs
INFO: Loading C:\Users\John\OpenAudible\settings.json exists=true size=548
May 18, 2022 12:32:00 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1652808245565
May 18, 2022 12:32:00 PM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 3.5.4.2 win
May 18, 2022 12:32:00 PM org.openaudible.desktop.swt.util.shop.PaintShop prefer2x
INFO: useHighDPI=false
May 18, 2022 12:32:01 PM org.openaudible.desktop.swt.manager.views.SummaryPanel <init>
SEVERE: Created swt summary panel.
May 18, 2022 12:32:02 PM org.openaudible.Directories getPrefs
INFO: Loading C:\Users\John\OpenAudible\settings.json exists=true size=548
May 18, 2022 12:32:02 PM org.openaudible.Directories getPrefs
INFO: loaded settings 1652808245565
May 18, 2022 12:32:02 PM org.openaudible.audible.AudibleConnectionState setRegion
INFO: Setting audible region to US
May 18, 2022 12:32:02 PM org.openaudible.Audible load
INFO: Loading C:\Users\John\OpenAudible\books.json
May 18, 2022 12:32:02 PM org.openaudible.Audible checkLibrary
INFO: loaded 0 books.
May 18, 2022 12:32:02 PM org.openaudible.desktop.swt.manager.AudibleGUI applicationStarted
INFO: applicationStarted took 303 ms. to complete.
May 18, 2022 12:32:05 PM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: https://openaudible.org/swt_version.json
May 18, 2022 12:32:07 PM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Command: Console

**Comment by gottifire** [comment]
Latest Beta now working with webview2

**Comment by openaudible** [comment]
Are you on Windows N?

Installing webview2 is a decent fix. 

I just posted a beta 3 that _should_ fallback to explorer if you don't have webview2 for whatever reason.

https://openaudible.org/beta

**Comment by gottifire** [comment]
> Are you on Windows N?
> 
> Installing webview2 is a decent fix.
> 
> I just posted a beta 3 that _should_ fallback to explorer if you don't have webview2 for whatever reason.
> 
> https://openaudible.org/beta

I'm using windows 10

I'll try beta 3, thank you
