### ISSUE TITLE
Splitting not aligned anymore

### ISSUE THREAD

**Issue by stephanmax** [openaudible/openaudible#788]
Hi there,
I noticed an issue with the German book “Spektrum” by Sergej Lukianenko: When clicking though the m4b chapters, I realize they get less and less aligned with the narrator announcing the actual chapters in the book the further I get into it.

I am attaching the book info from OpenAudible and the info from ffmpeg/ffprobe of the converted m4b file. The chapter marks seem to be the same. Can you think of any other reason the chapter marks get out of sync? (When clicking through the chapters in the Audible app they are perfectly aligned, so I don’t think they are wrong initially.)

Happy to provide anything else to get to the bottom of this. Thanks for this amazing piece of software!

[ffmpeg_info.txt](https://github.com/openaudible/openaudible/files/7642742/ffmpeg_info.txt)
[book_report.txt](https://github.com/openaudible/openaudible/files/7642748/book_report.txt)

**Comment by openaudible** [comment]
Are the chapters good or bad when you navigate by chapter on the whole Spektrum.m4b book in VLC (or other chapter enabled book player)?

**Comment by openaudible** [comment]
Its probable its just bad data from audible. Maybe re-downloading and re-converting the book would help.. but probably not unless the book has been updated. 

As always, we recommend not splitting the book and just get an audiobook player that supports chapters, large files, and bookmarking your last heard position.
