### ISSUE TITLE
Choice of Browser

### ISSUE THREAD

**Issue by 1234shai** [openaudible/openaudible#79]
When I want to get to the github page, I press the link to go to it but it uses the Internet Explorer browser instead of the browser I usually use, Chrome.  Github then warns me that it is no longer compatible with Internet Explorer.  Since I never use Internet Explorer, I'm not sure why the program uses it - but is there a way that I can force it to open up in a different browser so that the warning doesn't appear when I get to the Github page?

**Comment by openaudible** [comment]
The browser is the default one provided by our dev environment, eclipse.org/swt/ 
It is only used to parse Audible pages.
