### ISSUE TITLE
conversion not working

### ISSUE THREAD

**Issue by sgp000** [openaudible/openaudible#795]
I can't seem to convert to mp3 books I just downloaded from Audible.  I did import them*, and they show are "audiobook" (as opposed to actual genre), and I selected "convert to MP3", but I see no conversions.

* Downloading them from within OpenAudible was not working as expected, so I downloaded them manually from Audinble and put the .aax files in to OpenAudible/web directory.  Once there I was able to "import" them, which put me at the place I noted above- visible as "Audiobook" and selectable as such, but not converting to .mp3

**Comment by openaudible** [comment]
You have to download from desktop web browser. Not android. 

If you select one and Action menu convert to mp3 look in the console log for an error.
