### ISSUE TITLE
Openaudible does not fetch all download_link

### ISSUE THREAD

**Issue by perrinal** [openaudible/openaudible#796]
Hi,
When doing a refresh of the library openaudible is not able to fetch all the download_link of my audiobooks.
The logs show this info available for only for 8/60 and most book end up in the missing link category.
I can go in my Audible library, find the download URL and download the book manually but defeats the automated aspect of open audible. I get the books from audible.co.uk
How is openaudible fetching this information? What can I do to help to troubleshoot the issue.
```
"os": "ProductName:\tMac OS X\nProductVersion:\t10.13.6\nBuildVersion:\t17G14042\n",
 "java.version": "12",
 "version": "3.3",
```

**Comment by openaudible** [comment]
Hmm. Are these books purchased or free/included with your membership? Might need to get a bug report from you after doing a full rescan (from about menu)

**Comment by Zea-mai** [comment]
I am also experiencing this issue with a few of my newly purchased titles. I have attempted a full rescan

**Comment by perrinal** [comment]
After re-sync again, it works.
