### ISSUE TITLE
1.1.1 seems broken

### ISSUE THREAD

**Issue by rsrsps** [openaudible/openaudible#8]
the new version, 1.1.1 seems to be broken.  When one does a "full library sync" it opens a web browser to https://www.audible.com/account/access and very, very slowly loads it but then does nothing.

**Comment by rsrsps** [comment]
(I should note that the browser window is from within the UI as a separate window on the application, not the system default browser or safari)

**Comment by rsrsps** [comment]
Actually, I think this might be a 1.0 to > 1.0 issue.  I did a complete purge (including ~/Library/OpenAudible and it's still broken for 1.1 and 1.1.1.  Here's what it does:

![openaudible_browser](https://user-images.githubusercontent.com/5316857/41194063-af7f9a5c-6bca-11e8-8748-ef477d300a28.gif)

**Comment by kylemhall** [comment]
Same for me.

**Comment by adik0861** [comment]
I was having the same problem and I found a really strange workaround.  The exact steps are as follow: 

1. Download a single audiobook (i.e. an AAX file) directly from audible.com 
2. Import the downloaded AAX file into the program (_OpenAudible > File > Import AAX Files_)
3. Convert single file to mp3 ( _OpenAudible > Controls > Convert All to MP3_ )
4. Finally Connect to Audible followed by Full Library Sync

This is far from a programmatic solution, though it seemed to have solved the error I was receiving previously (same error as yours)

**Comment by rsrsps** [comment]
thanks for the suggestion.  FWIW this did not work for me; it still presents the browser for "full library sync."

**Comment by openaudible** [comment]
Make sure your user name and password are set in the Preferences. 
Make sure region is set to US. (All other regions untested.) 
Open the internal Browser: Controls: Browser (CMD-B).
Make sure you can log into audible and see your library 
Then try Controls:  "connect to Audible." 
If connected.. 
Controls: Full Library Sync

Thank you for the user reports. Not sure if it is just Mac users.. but we don't have many for testing, but we have at least one that works...

**Comment by rsrsps** [comment]
In 1.1.3, "Connect to audible" opens the browser to /access and dies.  Image and log below.

![image](https://user-images.githubusercontent.com/5316857/42128099-d5ab2068-7c58-11e8-82fd-d8b7b6d85fb6.png)
Jun 30, 2018 11:22:21 AM org.openaudible.desktop.swt.manager.AppLoader <init>
INFO: Starting OpenAudible build 1.1.3 for cocoa swt 4623 jvm 1.8.0_144
Jun 30, 2018 11:22:23 AM org.openaudible.desktop.swt.manager.AudibleGUI <init>
INFO: audible desktop 1.1.3
Jun 30, 2018 11:22:24 AM org.openaudible.util.SimpleProcess <init>
INFO: Running: /Applications/OpenAudible.app/Contents/java/app/bin/mac_ffmpeg -version 
Jun 30, 2018 11:22:24 AM org.openaudible.desktop.swt.manager.AudibleGUI checkFFMPEG
INFO: using ffmpeg version N-89585-g5533cbf-tessus Copyright (c) 2000-2017 the FFmpeg developers
built with Apple LLVM version 8.0.0 (clang-800.0.42.1)
configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-avisynth --enable-fontconfig --enable-gpl --enable-libass --enable-libbluray --enable-libfreetype --enable-libgsm --enable-libmodplug --enable-libmp3lame --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libopus --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libtheora --enable-libvidstab --enable-libvo-amrwbenc --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libx264 --enable-libx265 --enable-libxavs --enable-libxvid --enable-libzmq --enable-libzvbi --enable-version3 --pkg-config-flags=--static --disable-ffplay
libavutil      56.  6.100 / 56.  6.100
libavcodec     58.  8.100 / 58.  8.100
libavformat    58.  3.100 / 58.  3.100
libavdevice    58.  0.100 / 58.  0.100
libavfilter     7.  7.100 /  7.  7.100
libswscale      5.  0.101 /  5.  0.101
libswresample   3.  0.101 /  3.  0.101
libpostproc    55.  0.100 / 55.  0.100

Jun 30, 2018 11:22:29 AM org.openaudible.desktop.swt.manager.VersionCheck getVersion
INFO: versionCheck: http://openaudible.org/swt_version.json?platform=mac&version=1.1.3
Jun 30, 2018 11:22:31 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Execute: Rescan_Library
Jun 30, 2018 11:22:32 AM org.openaudible.audible.AudibleScraper setURL
INFO: setURL:/access
Jun 30, 2018 11:22:34 AM org.openaudible.audible.AudibleScraper setPage
INFO: pageLoaded:https://www.audible.com/account/access Download Audiobooks with Audible.com
Jun 30, 2018 11:22:34 AM org.openaudible.util.HTMLUtil debugNode
INFO: Debug: /Users/myname/Downloads/Video/openaudible/tmp/checkLoggedIn.html
Jun 30, 2018 11:22:34 AM org.openaudible.util.HTMLUtil debugNode
INFO: Debug: /Users/myname/Downloads/Video/openaudible/tmp/checkLoggedIn.html
Jun 30, 2018 11:22:34 AM org.openaudible.desktop.swt.manager.AudibleGUI connect
SEVERE: unable to connect
org.openaudible.audible.AudibleLoginError
	at org.openaudible.audible.AudibleScraper.home(AudibleScraper.java:317)
	at org.openaudible.desktop.swt.manager.AudibleGUI.connect(AudibleGUI.java:397)
	at org.openaudible.desktop.swt.manager.AudibleGUI.access$000(AudibleGUI.java:49)
	at org.openaudible.desktop.swt.manager.AudibleGUI$3.run(AudibleGUI.java:328)

Jun 30, 2018 11:22:46 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Execute: About
Jun 30, 2018 11:23:22 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Execute: About
Jun 30, 2018 11:24:04 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Execute: Preferences
Jun 30, 2018 11:24:16 AM org.openaudible.desktop.swt.manager.views.Preferences okPressed
INFO: okPressed
Jun 30, 2018 11:24:21 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Execute: Rescan_Library
Jun 30, 2018 11:24:21 AM org.openaudible.desktop.swt.manager.AudibleGUI connect
INFO: Setting cookies 1
Jun 30, 2018 11:24:21 AM org.openaudible.desktop.swt.manager.AudibleGUI$4 task
INFO: Done Setting cookies 2
Jun 30, 2018 11:24:21 AM org.openaudible.desktop.swt.manager.AudibleGUI$4 task
INFO: Done Setting cookies 3
Jun 30, 2018 11:24:21 AM org.openaudible.desktop.swt.manager.AudibleGUI connect
INFO: Done Setting cookies 4
Jun 30, 2018 11:24:21 AM org.openaudible.audible.AudibleScraper setURL
INFO: setURL:/access
Jun 30, 2018 11:24:21 AM org.openaudible.audible.AudibleScraper setPage
INFO: pageLoaded:https://www.audible.com/account/access Download Audiobooks with Audible.com
Jun 30, 2018 11:24:21 AM org.openaudible.util.HTMLUtil debugNode
INFO: Debug: /Users/myname/Downloads/Video/openaudible/tmp/checkLoggedIn.html
Jun 30, 2018 11:24:21 AM org.openaudible.util.HTMLUtil debugNode
INFO: Debug: /Users/myname/Downloads/Video/openaudible/tmp/checkLoggedIn.html
Jun 30, 2018 11:24:21 AM org.openaudible.desktop.swt.manager.AudibleGUI connect
SEVERE: unable to connect
org.openaudible.audible.AudibleLoginError
	at org.openaudible.audible.AudibleScraper.home(AudibleScraper.java:317)
	at org.openaudible.desktop.swt.manager.AudibleGUI.connect(AudibleGUI.java:397)
	at org.openaudible.desktop.swt.manager.AudibleGUI.access$000(AudibleGUI.java:49)
	at org.openaudible.desktop.swt.manager.AudibleGUI$3.run(AudibleGUI.java:328)

Jun 30, 2018 11:25:09 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Execute: Rescan_Library
Jun 30, 2018 11:25:09 AM org.openaudible.desktop.swt.manager.AudibleGUI connect
INFO: Setting cookies 1
Jun 30, 2018 11:25:09 AM org.openaudible.desktop.swt.manager.AudibleGUI$4 task
INFO: Done Setting cookies 2
Jun 30, 2018 11:25:09 AM org.openaudible.desktop.swt.manager.AudibleGUI$4 task
INFO: Done Setting cookies 3
Jun 30, 2018 11:25:09 AM org.openaudible.desktop.swt.manager.AudibleGUI connect
INFO: Done Setting cookies 4
Jun 30, 2018 11:25:09 AM org.openaudible.audible.AudibleScraper setURL
INFO: setURL:/access
Jun 30, 2018 11:25:09 AM org.openaudible.audible.AudibleScraper setPage
INFO: pageLoaded:https://www.audible.com/account/access Download Audiobooks with Audible.com
Jun 30, 2018 11:25:09 AM org.openaudible.util.HTMLUtil debugNode
INFO: Debug: /Users/myname/Downloads/Video/openaudible/tmp/checkLoggedIn.html
Jun 30, 2018 11:25:09 AM org.openaudible.util.HTMLUtil debugNode
INFO: Debug: /Users/myname/Downloads/Video/openaudible/tmp/checkLoggedIn.html
Jun 30, 2018 11:25:09 AM org.openaudible.desktop.swt.manager.AudibleGUI connect
SEVERE: unable to connect
org.openaudible.audible.AudibleLoginError
	at org.openaudible.audible.AudibleScraper.home(AudibleScraper.java:317)
	at org.openaudible.desktop.swt.manager.AudibleGUI.connect(AudibleGUI.java:397)
	at org.openaudible.desktop.swt.manager.AudibleGUI.access$000(AudibleGUI.java:49)
	at org.openaudible.desktop.swt.manager.AudibleGUI$3.run(AudibleGUI.java:328)

Jun 30, 2018 11:27:23 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Execute: Quick_Refresh
Jun 30, 2018 11:27:23 AM org.openaudible.desktop.swt.manager.AudibleGUI connect
INFO: Setting cookies 1
Jun 30, 2018 11:27:23 AM org.openaudible.desktop.swt.manager.AudibleGUI$4 task
INFO: Done Setting cookies 2
Jun 30, 2018 11:27:23 AM org.openaudible.desktop.swt.manager.AudibleGUI$4 task
INFO: Done Setting cookies 3
Jun 30, 2018 11:27:23 AM org.openaudible.desktop.swt.manager.AudibleGUI connect
INFO: Done Setting cookies 4
Jun 30, 2018 11:27:23 AM org.openaudible.audible.AudibleScraper setURL
INFO: setURL:/access
Jun 30, 2018 11:27:23 AM org.openaudible.audible.AudibleScraper setPage
INFO: pageLoaded:https://www.audible.com/account/access Download Audiobooks with Audible.com
Jun 30, 2018 11:27:23 AM org.openaudible.util.HTMLUtil debugNode
INFO: Debug: /Users/myname/Downloads/Video/openaudible/tmp/checkLoggedIn.html
Jun 30, 2018 11:27:23 AM org.openaudible.util.HTMLUtil debugNode
INFO: Debug: /Users/myname/Downloads/Video/openaudible/tmp/checkLoggedIn.html
Jun 30, 2018 11:27:23 AM org.openaudible.desktop.swt.manager.AudibleGUI connect
SEVERE: unable to connect
org.openaudible.audible.AudibleLoginError
	at org.openaudible.audible.AudibleScraper.home(AudibleScraper.java:317)
	at org.openaudible.desktop.swt.manager.AudibleGUI.connect(AudibleGUI.java:397)
	at org.openaudible.desktop.swt.manager.AudibleGUI.access$000(AudibleGUI.java:49)
	at org.openaudible.desktop.swt.manager.AudibleGUI$3.run(AudibleGUI.java:328)

Jun 30, 2018 11:29:07 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Execute: Connect
Jun 30, 2018 11:29:07 AM org.openaudible.desktop.swt.manager.AudibleGUI connect
INFO: Setting cookies 1
Jun 30, 2018 11:29:07 AM org.openaudible.desktop.swt.manager.AudibleGUI$4 task
INFO: Done Setting cookies 2
Jun 30, 2018 11:29:07 AM org.openaudible.desktop.swt.manager.AudibleGUI$4 task
INFO: Done Setting cookies 3
Jun 30, 2018 11:29:07 AM org.openaudible.desktop.swt.manager.AudibleGUI connect
INFO: Done Setting cookies 4
Jun 30, 2018 11:29:07 AM org.openaudible.audible.AudibleScraper setURL
INFO: setURL:/access
Jun 30, 2018 11:29:08 AM org.openaudible.audible.AudibleScraper setPage
INFO: pageLoaded:https://www.audible.com/account/access Download Audiobooks with Audible.com
Jun 30, 2018 11:29:08 AM org.openaudible.util.HTMLUtil debugNode
INFO: Debug: /Users/myname/Downloads/Video/openaudible/tmp/checkLoggedIn.html
Jun 30, 2018 11:29:08 AM org.openaudible.util.HTMLUtil debugNode
INFO: Debug: /Users/myname/Downloads/Video/openaudible/tmp/checkLoggedIn.html
Jun 30, 2018 11:29:08 AM org.openaudible.desktop.swt.manager.AudibleGUI connect
SEVERE: unable to connect
org.openaudible.audible.AudibleLoginError
	at org.openaudible.audible.AudibleScraper.home(AudibleScraper.java:317)
	at org.openaudible.desktop.swt.manager.AudibleGUI.connect(AudibleGUI.java:397)
	at org.openaudible.desktop.swt.manager.AudibleGUI.access$000(AudibleGUI.java:49)
	at org.openaudible.desktop.swt.manager.AudibleGUI$2.run(AudibleGUI.java:274)

Jun 30, 2018 11:29:35 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFO: Execute: Console

**Comment by rsrsps** [comment]
Ok, weird.  I manually opened the browser as directed, logged _out_, then logged in again in the browser.  Then I got a few errors (not captured) and now it is fixed. 

Suggestion: add an option to purge (to a .bak file) all cached information.  Closing the other issue.
