### ISSUE TITLE
Getting Error Message

### ISSUE THREAD

**Issue by themorley** [openaudible/openaudible#80]
Error importing
pathname\filename:Unable to find next atom because identifier is invalid

If I delete my book and then download it again from audible it works

**Comment by themorley** [comment]
also it is unable to import more than one audio book that is of multiple volumes, for example, Parallel Lives and the Decline and Fall of the Roman Empire can't both be imported because they are of multiple volumes

**Comment by openaudible** [comment]
Posted new version. Feel free to try again. Connect, scan library. Go to the page with one of the multi-volume books and send a bug report after trying to get.. 
Regarding the find next atom error name.. sounds like it is trying to parse an .aax file... no idea... those books look really big, so they may be exceeding the ability of the generic aax file parser i'm using.

**Comment by themorley** [comment]
Yes, the volumes it had the atom trouble with were monstrously large volumes (library is mostly non fiction).

Really impressed at the swift response, will update and report back soon :)

**Comment by openaudible** [comment]
The latest release ignores any problems parsing the aax file--except it will give a warning. Should work fine otherwise. Might want to do "Refresh Info" for the book to grab the extra meta data before converting to mp3. Feel free to report back.
