### ISSUE TITLE
[Feature Request] Periodically refresh audible library

### ISSUE THREAD

**Issue by Weldawadyathink** [openaudible/openaudible#805]
I run the relatively recent OpenAudible docker on my server. This setup (almost) automatically will export my Audible library into my plex library. Every step of this process is automated except the initial sync. Whenever I buy a book, I have to remote in and quick sync the library. It would be great if the program could be set to refresh automatically with a user-set frequency.

**Comment by Weldawadyathink** [comment]
Ideally it would be able to get push updates from the server. I am guessing it is not possible since Amazon doesn’t make an api for this (hence why OpenAudible exists in the first place). 

Maybe it is best to leave it up to the user? Personally, I would like it in the 5-15 minute range, but even hourly updates would be fine. I often buy books before I finish the previous book, so a bit of lag time isn’t the end of the world.

**Comment by openaudible** [comment]
Definitely no API push options. Will try to make it a hidden feature to start with where you can set the minute interval in the prefs.

**Comment by openaudible** [comment]
Added to most recent beta: https://openaudible.org/beta
Probably keep it a hidden feature for the time.
You'll need to edit the preferences and add or edit autoRefreshMinutes and set it to 5 or whatever value.
