### ISSUE TITLE
File export to csv not working

### ISSUE THREAD

**Issue by dckhome** [openaudible/openaudible#808]
File export to csv not working, Export to web page does work

latest version 3.3, licenced, Windows 10, Dell inspiron I7, Kaspersky security

**Comment by openaudible** [comment]
Check error log? What does it output?

**Comment by dckhome** [comment]
Hi
I should have stated it creates a csv file but there is nothing in it

below diagnostics report
is that what you equire?

{
 "date": "Fri Dec 17 16:58:58 GMT 2021",
 "memory": "Memory: Using 23.854Mb of 2022Mb (1%) Min 23.854Mb Max 27.288Mb",
 "os": "",
 "java.version": "12",
 "version": "3.3",
 "demo": false,
 "platform": "win",
 "prefs": {
  "disableVersionCheck": false,
  "lastVersion": "3.3",
  "playFileCmd": "",
  "webPageIncludeMP3": true,
  "format": "M4B",
  "autoConvert": true,
  "mp3Qscale": 4,
  "autoDownload": false,
  "language": "en",
  "autoWebPage": false,
  "autoConnect": false,
  "uid": "1624977180453",
  "concurrentConversions": 3,
  "browseFileCmd": "",
  "autoLink": false,
  "concurrentDownloads": 3,
  "html": false,
  "theme": "",
  "autoPDF": true,
  "migrated": true,
  "region": "UK"
 },
 "uid": "1624977180453",
 "swt": 4946,
 "books.json": "C:\\Users\\dckin\\OpenAudible\\books.json",
 "file.encoding": "UTF-8",
 "directories": [
  {
   "path": "C:\\Users\\dckin\\OpenAudible",
   "kind": "BASE",
   "exists": true
  },
  {
   "path": "C:\\Users\\dckin\\OpenAudible\\books",
   "kind": "BOOKS",
   "exists": true
  },
  {
   "path": "C:\\Users\\dckin\\OpenAudible\\web",
   "kind": "WEB",
   "exists": true
  },
  {
   "path": "C:\\Users\\dckin\\OpenAudible",
   "kind": "META",
   "exists": true
  },
  {
   "path": "C:\\Users\\dckin\\OpenAudible\\aax",
   "kind": "AAX",
   "exists": true
  },
  {
   "path": "C:\\Users\\dckin\\OpenAudible\\art",
   "kind": "ART",
   "exists": true
  },
  {
   "path": "C:\\Users\\dckin\\OpenAudible\\books",
   "kind": "MP3",
   "count": 0,
   "exists": true,
   "sample": "C:\\Users\\dckin\\OpenAudible\\books\\sample.mp3"
  },
  {
   "path": "C:\\Users\\dckin\\OpenAudible\\tmp",
   "kind": "TMP",
   "exists": true
  },
  {
   "path": "C:\\Program Files\\OpenAudible",
   "kind": "APP",
   "exists": true
  },
  {
   "path": "C:\\Users\\dckin\\OpenAudible\\books",
   "kind": "M4A",
   "count": 0,
   "exists": true,
   "sample": "C:\\Users\\dckin\\OpenAudible\\books\\sample.m4a"
  },
  {
   "path": "C:\\Users\\dckin\\OpenAudible\\books",
   "kind": "M4B",
   "count": 0,
   "exists": true,
   "sample": "C:\\Users\\dckin\\OpenAudible\\books\\sample.m4b"
  },
  {
   "path": "C:\\Users\\dckin\\OpenAudible\\books",
   "kind": "PDF",
   "exists": true
  }
 ],
 "region": "UK"
}

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by openaudible** [comment]
Oh! Found the bug. Thank you for the report.

When the dialog asks for a file name, instead of "books", change it to "books.csv".  

(The code was getting the file name "books" which wasn't a valid csv file name.)

That will fix it for the next release.

**Comment by dckhome** [comment]
Thankyou
Exported ok

Ta
Dave

Sent with [ProtonMail](https://protonmail.com/) Secure Email.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by openaudible** [comment]
Fixed in latest beta
https://openaudible.org/beta
Will be a new release soon.
