### ISSUE TITLE
Internal web browser not working on Arch

### ISSUE THREAD

**Issue by pikim** [openaudible/openaudible#81]
I installed OpenAudible on Arch Linux and the application itself opens, but when I try to open the internal web browser only the following dialogue is shown:
![oae](https://user-images.githubusercontent.com/11775849/51071240-fb8b1600-164d-11e9-9fbe-8dab61fe5bde.png)

**Comment by openaudible** [comment]
You'll need to google the full error reported from the console..  The internal Eclipse SWT browser is not compatible all unix flavors. 
Usually means you need to upgrade or downgrade something.

**Comment by EliyahuFisherman** [comment]
I'm getting the same error on ubuntu 18.10

**Comment by openaudible** [comment]
From OpenAudible, open the console: Control-L
Then open the browser: Control-B

Copy and paste the error you see into a reply. 
Optionally, google the error message, with something like "SWT Browser xxxx error" where xxxx is main error returned.

Often you'll see a number of suggestions and tips for getting browser support to work.. installing webkit, xurlrunner, etc.. 

I just ran a test by installing a brand new Ubuntu 18.0.4.1 (AMD64) desktop image on VMWare. 

Only one pre-requisite: Java 8.

sudo apt install openjdk-8-jre

Run .deb installer (or .sh installer)
Launch /opt/OpenAudible

Browser comes up fine.

You sure you're on AMD64? Some other software may be causing the problem.. Linux is not my day to day OS, so hard to tell what's wrong.

**Comment by openaudible** [comment]
Only thing I found when googling "swt browser no more handles" is that "Firefox must be dynamically linked".  So make sure FireFox is installed using the ubuntu package manager.. Or just reinstall your Ubuntu. :)

**Comment by pikim** [comment]
On my main PC I'm running Arch with Firefox installed and working and there I have the problem.

**Comment by gnuanu** [comment]
@pikim @openaudible 
Install webkit2gtk package using pacman. That solved the issue for me.

`sudo pacman -S webkit2gtk`

A bit late but might help others who reach here.

**Comment by realolephart** [comment]
> Install webkit2gtk package using pacman. That solved the issue for me.
> ...
> A bit late but might help others who reach here.

That did the trick! 

Thanks gnuanu
