### ISSUE TITLE
Move to a New Machine

### ISSUE THREAD

**Issue by rnbwpnt** [openaudible/openaudible#810]
Is there a good/semi-reliable procedure for moving a library and associated settings to a new computer, cross-platform? I'm looking at retiring a Linux box that isn't used for anything except OA, and moving it to my daily driver Mac. When I've attempted the move, my books.json got flattened and I've had trouble getting the library installed correctly. The library is well over 10k books, so just re-importing everything would ... work, I guess? ... but be non-trivial.

**Comment by openaudible** [comment]
You could try with an empty library on the new machine, then quit, and copy files over, replacing the existing ones, except for directories.json (which are not compatible between mac and pc.) 
When you start, hopefully all will be ok.. but feel free to post an error message from the console (ctrl-E).

**Comment by rnbwpnt** [comment]
I'll give it a spin and report back. The library weighs in at 4.3tb, so copying it over will take ... a bit of time.

**Comment by openaudible** [comment]
Time to upgrade to 10G ethernet.
