### ISSUE TITLE
Convert AAX to M4B

### ISSUE THREAD

**Issue by swtharp** [openaudible/openaudible#811]
Trying to convert AX files to M4B and 115 files fail with ffprobe error. I have tried to restart and to clear temp files and restart same issue continues. 

Here is the diag

{
 "date": "Mon Dec 20 11:22:50 EST 2021",
 "memory": "Memory: Using 23.375Mb of 8182Mb (0%) Min 23.375Mb Max 23.375Mb",
 "os": "",
 "java.version": "12",
 "version": "3.3",
 "demo": false,
 "platform": "win",
 "prefs": {
  "disableVersionCheck": false,
  "lastVersion": "3.3",
  "playFileCmd": "",
  "webPageIncludeMP3": true,
  "format": "M4B",
  "autoConvert": true,
  "mp3Qscale": 4,
  "autoDownload": false,
  "language": "en",
  "autoWebPage": false,
  "autoConnect": false,
  "uid": "1639947192357",
  "concurrentConversions": 3,
  "browseFileCmd": "",
  "autoLink": false,
  "concurrentDownloads": 3,
  "html": false,
  "theme": "",
  "autoPDF": true,
  "migrated": true,
  "region": "US"
 },
 "uid": "1639947192357",
 "swt": 4946,
 "books.json": "C:\\Users\\Steven\\OpenAudible\\books.json",
 "file.encoding": "UTF-8",
 "directories": [
  {
   "path": "C:\\Users\\Steven\\OpenAudible",
   "kind": "BASE",
   "exists": true
  },
  {
   "path": "C:\\Users\\Steven\\OpenAudible\\books",
   "kind": "BOOKS",
   "exists": true
  },
  {
   "path": "C:\\Users\\Steven\\OpenAudible\\web",
   "kind": "WEB",
   "exists": true
  },
  {
   "path": "C:\\Users\\Steven\\OpenAudible",
   "kind": "META",
   "exists": true
  },
  {
   "path": "C:\\Users\\Steven\\OpenAudible\\aax",
   "kind": "AAX",
   "exists": true
  },
  {
   "path": "C:\\Users\\Steven\\OpenAudible\\art",
   "kind": "ART",
   "exists": true
  },
  {
   "path": "C:\\Users\\Steven\\OpenAudible\\books",
   "kind": "MP3",
   "count": 3,
   "exists": true,
   "sample": "C:\\Users\\Steven\\OpenAudible\\books\\sample.mp3"
  },
  {
   "path": "C:\\Users\\Steven\\OpenAudible\\tmp",
   "kind": "TMP",
   "exists": true
  },
  {
   "path": "C:\\Program Files\\OpenAudible",
   "kind": "APP",
   "exists": true
  },
  {
   "path": "C:\\Users\\Steven\\OpenAudible\\books",
   "kind": "M4A",
   "count": 10,
   "exists": true,
   "sample": "C:\\Users\\Steven\\OpenAudible\\books\\sample.m4a"
  },
  {
   "path": "C:\\Users\\Steven\\OpenAudible\\books",
   "kind": "M4B",
   "count": 110,
   "exists": true,
   "sample": "C:\\Users\\Steven\\OpenAudible\\books\\sample.m4b"
  },
  {
   "path": "C:\\Users\\Steven\\OpenAudible\\books",
   "kind": "PDF",
   "exists": true
  }
 ],
 "region": "US"
}

**Comment by openaudible** [comment]
Did you download them using OpenAudible? 
Are they purchased books, or "included for free with your subscription"?

**Comment by swtharp** [comment]
I did copy some aax files from a previous install I removed all books and restarted and appears all is well.
