### ISSUE TITLE
Cannot connect to audible - browser bug

### ISSUE THREAD

**Issue by b0rez** [openaudible/openaudible#813]
I cannot connect to audible.co.uk or audible.com. After entering credentials in the OpenAudible browser the page just hangs.

Sometimes (as in "randomly" and "unpredictably") after entering credentials and clicking Continue, the captcha page partially loads (the captcha puzzle itself does NOT load) but the page is FROZEN and does not respond to keyboard or mouse input. (see attached screenshot...)

From [OpenAudible | Controls | Connect to Audible] the browser DOES open successfully. And I can even use it to put in the URL https://www.audible.co.uk and successfully log into my Audible account.

It *feels* like there's a bug in the OpenAudible connection string - OR - in the OpenAudible's browser ability to handle captcha traffic.

OS is Ubuntu 20.04.3 LTS
Installed browsers: Mozilla Firefox and Google Chrome
![OpenAudible bug screenshot](https://user-images.githubusercontent.com/96565409/147214755-10c357bd-3a5a-4e2a-b99c-692bfa37747d.jpg)

**Comment by Bhlowe** [comment]
Try : 
``` 
sudo apt install gstreamer1.0-plugins-bad
```

**Comment by b0rez** [comment]
> Try :
> 
> ```
> sudo apt install gstreamer1.0-plugins-bad
> ```

My new-found, BFF (Best Friend Forever)... YOU ROCK!!!

Yes, you nailed the solution. Any comment or background you might want to share?

A thousand thanks!

**Comment by openaudible** [comment]
Known bug.

**Comment by b0rez** [comment]
RESOLVED.
