### ISSUE TITLE
nag popups

### ISSUE THREAD

**Issue by Butterfly-Dragon** [openaudible/openaudible#814]
I disabled automatic conversion to MP3 in the settings due to it taking too much space on the hard drive of the PC i have that i use for downloads. It still tries to autoconvert MP3s via nag popups.

![image](https://user-images.githubusercontent.com/33538906/147851869-5e2cead6-0dd0-4ed4-b212-c7ee33df7c13.png)

Also as usual hotkeys still do not work after years of the first version for some reasons, so if it starts to autoconvert i have to do everything with the mouse.

**Comment by openaudible** [comment]
What are hot keys? Yes is highlighted so "Enter" should select it. Use tab to highlight the "No".
Are you asking for the Y and N in yes/no to be underlined?
I can enable that for some dialogs.. haven't really bothered to do that because it makes things kind of ugly on the more complicated dialogs (like prefs.)

**Comment by Butterfly-Dragon** [comment]
?!?!?

uh... what are you talking about?! i meant canceling a job does not work... normally i would `[CTRL]`+`[A]` to select everything then there used to be a key to cancel the job.

Now not only i get presented that "start tasks" even though i had explicitly said in the settings to not start any conversion "magically"

BUT in addition to that 

i can't even quickly cancel a conversion job.

In fact most of the times even when there is an hotkey assigned to an action like `[CTRL]`+`[D]` to download a book... the hotkey does nothing at all.

**Comment by openaudible** [comment]
You said hotkeys and showed the yes/no dialog. I wasn't sure. There is a weird way to assign a mnemonic letter to a button.

I can add a hotkey to cancel all  jobs, how about CTRL- . (period)

I hadn't noticed, but it does seem like sometimes the hotkeys aren't work. Ugh! You keep finding bugs. !! (thanks!)

**Comment by Butterfly-Dragon** [comment]
fair enough and yes... hotkeys are a bit of an hit and miss... sometimes the work and sometimes they do not.

**Comment by openaudible** [comment]
Found the menu item bug. Added the command to cancel jobs. Removed nag dialog. Will post beta soonish.

**Comment by Butterfly-Dragon** [comment]
ok, thanks!

**Comment by openaudible** [comment]
I think fixed in latest beta:
https://openaudible.org/beta

**Comment by Butterfly-Dragon** [comment]
thanks!
