### ISSUE TITLE
[feature request] convert more than 3 books at once

### ISSUE THREAD

**Issue by Butterfly-Dragon** [openaudible/openaudible#815]
On the PC i use to do all the "heavy lift works" (which is different from the on i use to download things) i cannot seem to be able to convert more than 3 books at once. Ideally Openaudible should check how many cores the PC has and start nearly as many FFMPEG processes leaving only 1, 2 or 4 cores free (depending on the number of cores, for single core PCs, if they still exist, still running a single instance is okay) and/or let the user decide how much they want to cook their own PC with its own heat.

i have... uh... a lot of conversions to do and i would like to start backups before the heath death of the universe.

![image](https://user-images.githubusercontent.com/33538906/147851764-cf9ceb5e-3848-442f-9079-562472010da0.png)

**Comment by openaudible** [comment]
You can manually edit the settings.json and set the max conversion or downloads to 10.

**Comment by Butterfly-Dragon** [comment]
uhm... an option in the settings would be better than to manually edit the settings. 😅

**Comment by Butterfly-Dragon** [comment]
but okay i guess.

**Comment by openaudible** [comment]
Trying to keep the UI simple.
