### ISSUE TITLE
[feature request] naming conventions for files and books.

### ISSUE THREAD

**Issue by Butterfly-Dragon** [openaudible/openaudible#817]
Correct me if i am wrong but i only see books named as:

[title].[extension] or [title]/[track].[chapter title].[extension]

I cannot seem to find a way to do things like:

[last name of author], [first name of author] - [year] - {[book series] [index] - }[title]/[track] - [chapter title].[extension]

Which is my current naming convention and where [ ] are book tags and { } denotes an optional element which might be missing

**Comment by openaudible** [comment]
Marked as feature request. No ETA on implementation... but hopefully 2022!
