### ISSUE TITLE
[feature request] connect to databases

### ISSUE THREAD

**Issue by Butterfly-Dragon** [openaudible/openaudible#818]
A nagging problem i have with Audible is that it does not write down the original publication date of a book.

So according to audible a book which came out in 1953 was "written" in the 2010s or something (see all the Lem Stanislav books).

Also audible is extremely lax on author naming. Aside from many mistakes in author naming (which result in me having seen several books i bought getting "de-listed" from a series because according to some random bot it was not the same author) it does not discern from the same author using known pen names.

Is there any way to connect openaudible to public archives (i only know of ISFDB since it's the one i use the most, but goodreads could be a good bet too) so that the correct name of the author can be listed?

It might also fix series assignment on audible which is glitchy at the best of times with books popping in and out of a series completely at random.

**Comment by openaudible** [comment]
Way beyond scope. That would be a feature request for audible. Thanks tho and HNY.

**Comment by Butterfly-Dragon** [comment]
fair enough ¯\_(ツ)_/¯ thanks anyway.
