### ISSUE TITLE
Error converting, access denied

### ISSUE THREAD

**Issue by JoArtyJo** [openaudible/openaudible#820]
Hi, I have just purchased OpenAudible today and synced my first 2 Audible books.
However they both say “error converting” and then “access denied”. I can’t convert them to mp3 as the option doesn’t come up.
Can you let me know where I’m going wrong please? Thanks.

**Comment by openaudible** [comment]
Not sure about access denied. Mp3 requires a change in prefs under output format. Click on one book and look at status in book info panel.

**Comment by JoArtyJo** [comment]
I changed the preferences so the option to convert to mp3 does come up now.
But if I click on either book (I only have 2 at the moment) then next to “state” it still says “error converting” then the long file name, followed by “access denied”?

**Comment by JoArtyJo** [comment]
Sorry for the picture quality!
![Uploading B71D1FC2-28AC-4422-9EA0-92452FB139DE.jpeg…]()

**Comment by JoArtyJo** [comment]
![333B9D21-212F-44E4-AE90-F741568206D9](https://user-images.githubusercontent.com/97190971/148300698-1c9fbffc-199a-466a-a1a5-d858ae7e1cd5.jpeg)

**Comment by JdVarney** [comment]
This is the error msg I'm receiving...

Jan 05, 2022 8:27:38 PM org.openaudible.download.DownloadJob download
INFO: Downloading book: Pandora's Star url=https://cds.audible.com/download?asin=B002V5BDXK&cust_id=EF_4DkGAg7eH9AOocZFnbF79Avfy96vXkERiOG1PxcRArBb4i3WFAJHilouoSw&codec=LC_64_22050_stereo&source=audible_iPhone&type=AUDI attempt3
Jan 05, 2022 8:27:39 PM org.openaudible.download.DownloadAAXJob helperBodyToURL
SEVERE: helperToURL: This audio format is not supported for the title. Please download in another audio format.
Jan 05, 2022 8:27:39 PM org.openaudible.download.DownloadAAXJob handleError
SEVERE: Error downloading book:Pandora's Star
url=https://cds.audible.com/download?asin=B002V5BDXK&cust_id=EF_4DkGAg7eH9AOocZFnbF79Avfy96vXkERiOG1PxcRArBb4i3WFAJHilouoSw&codec=LC_64_22050_stereo&source=audible_iPhone&type=AUDI
dl=https://cds.audible.com/download?asin=B002V5BDXK&cust_id=EF_4DkGAg7eH9AOocZFnbF79Avfy96vXkERiOG1PxcRArBb4i3WFAJHilouoSw&codec=LC_64_22050_stereo&source=audible_iPhone&type=AUDI
err=Download error:This audio format is not supported for the title. Please download in another audio format. for Pandora's Star
region=US
dl_body=This audio format is not supported for the title. Please download in another audio format.
dl_body error:java.io.IOException: Expected assemble_url
Jan 05, 2022 8:27:39 PM org.openaudible.download.DownloadJob download
INFO: Download failed:/Users/johnvarney/Library/Mobile Documents/com~apple~CloudDocs/Books/aax/Pandora's Star.AAX Pandora's Star progress: null
Jan 05, 2022 8:27:39 PM org.openaudible.download.DownloadAAXJob processJob
WARNING: Error downloading https://cds.audible.com/download?asin=B002V5BDXK&cust_id=EF_4DkGAg7eH9AOocZFnbF79Avfy96vXkERiOG1PxcRArBb4i3WFAJHilouoSw&codec=LC_64_22050_stereo&source=audible_iPhone&type=AUDI attempt 3
java.lang.Exception: Download error:This audio format is not supported for the title. Please download in another audio format. for Pandora's Star
	at org.openaudible.download.DownloadAAXJob.handleError(DownloadAAXJob.java:70)
	at org.openaudible.download.DownloadAAXJob.checkEntity(DownloadAAXJob.java:45)
	at org.openaudible.download.DownloadJob.download(DownloadJob.java:92)
	at org.openaudible.download.DownloadAAXJob.processJob(DownloadAAXJob.java:205)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:484)

Jan 05, 2022 8:27:39 PM org.openaudible.util.queues.ThreadedQueue jobError
INFO: DownloadQueue error processing Download Pandora's Star item Pandora's Star
java.lang.Exception: Download error:This audio format is not supported for the title. Please download in another audio format. for Pandora's Star
	at org.openaudible.download.DownloadAAXJob.handleError(DownloadAAXJob.java:70)
	at org.openaudible.download.DownloadAAXJob.checkEntity(DownloadAAXJob.java:45)
	at org.openaudible.download.DownloadJob.download(DownloadJob.java:92)
	at org.openaudible.download.DownloadAAXJob.processJob(DownloadAAXJob.java:205)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:484)


I've been able to download books from the same publisher without any problem.

Thanks

**Comment by trueAl** [comment]
> 



> This is the error msg I'm receiving...
> 
> Jan 05, 2022 8:27:38 PM org.openaudible.download.DownloadJob download INFO: Downloading book: Pandora's Star url=https://cds.audible.com/download?asin=B002V5BDXK&cust_id=EF_4DkGAg7eH9AOocZFnbF79Avfy96vXkERiOG1PxcRArBb4i3WFAJHilouoSw&codec=LC_64_22050_stereo&source=audible_iPhone&type=AUDI attempt3 Jan 05, 2022 8:27:39 PM org.openaudible.download.DownloadAAXJob helperBodyToURL SEVERE: helperToURL: This audio format is not supported for the title. Please download in another audio format. Jan 05, 2022 8:27:39 PM org.openaudible.download.DownloadAAXJob handleError SEVERE: Error downloading book:Pandora's Star url=https://cds.audible.com/download?asin=B002V5BDXK&cust_id=EF_4DkGAg7eH9AOocZFnbF79Avfy96vXkERiOG1PxcRArBb4i3WFAJHilouoSw&codec=LC_64_22050_stereo&source=audible_iPhone&type=AUDI dl=https://cds.audible.com/download?asin=B002V5BDXK&cust_id=EF_4DkGAg7eH9AOocZFnbF79Avfy96vXkERiOG1PxcRArBb4i3WFAJHilouoSw&codec=LC_64_22050_stereo&source=audible_iPhone&type=AUDI err=Download error:This audio format is not supported for the title. Please download in another audio format. for Pandora's Star region=US dl_body=This audio format is not supported for the title. Please download in another audio format. dl_body error:java.io.IOException: Expected assemble_url Jan 05, 2022 8:27:39 PM org.openaudible.download.DownloadJob download INFO: Download failed:/Users/johnvarney/Library/Mobile Documents/com~apple~CloudDocs/Books/aax/Pandora's Star.AAX Pandora's Star progress: null Jan 05, 2022 8:27:39 PM org.openaudible.download.DownloadAAXJob processJob WARNING: Error downloading https://cds.audible.com/download?asin=B002V5BDXK&cust_id=EF_4DkGAg7eH9AOocZFnbF79Avfy96vXkERiOG1PxcRArBb4i3WFAJHilouoSw&codec=LC_64_22050_stereo&source=audible_iPhone&type=AUDI attempt 3 java.lang.Exception: Download error:This audio format is not supported for the title. Please download in another audio format. for Pandora's Star at org.openaudible.download.DownloadAAXJob.handleError(DownloadAAXJob.java:70) at org.openaudible.download.DownloadAAXJob.checkEntity(DownloadAAXJob.java:45) at org.openaudible.download.DownloadJob.download(DownloadJob.java:92) at org.openaudible.download.DownloadAAXJob.processJob(DownloadAAXJob.java:205) at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:484)
> 
> Jan 05, 2022 8:27:39 PM org.openaudible.util.queues.ThreadedQueue jobError INFO: DownloadQueue error processing Download Pandora's Star item Pandora's Star java.lang.Exception: Download error:This audio format is not supported for the title. Please download in another audio format. for Pandora's Star at org.openaudible.download.DownloadAAXJob.handleError(DownloadAAXJob.java:70) at org.openaudible.download.DownloadAAXJob.checkEntity(DownloadAAXJob.java:45) at org.openaudible.download.DownloadJob.download(DownloadJob.java:92) at org.openaudible.download.DownloadAAXJob.processJob(DownloadAAXJob.java:205) at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:484)
> 
> I've been able to download books from the same publisher without any problem.
> 
> Thanks

To me it looks like a different problem, I created a new issue for that

**Comment by openaudible** [comment]
I think you're right.. this two different bugs.  @JoArtyJo I might need a little more of the error message. Can you open the Console (File Menu, Console) and try to convert a file again. 

@trueAl and @JdVarney I'm looking at your bug in #825 ... and removing the comments above to keep things clear. (Thanks!)

**Comment by openaudible** [comment]
Feel free to post the log if this is still happening. Also, check your firewall/antivirus. No other reports of access denied so may be that.
