### ISSUE TITLE
Download Error: This audio format is not supported for the title.

### ISSUE THREAD

**Issue by benhall847** [openaudible/openaudible#823]
Book was released a few weeks ago.
I'm successfully able to visit the page on audibles website via the link provided by openaudible.

But Audible is unable to download the book.
Full error message -

'Error downloading: Download error: This audio format is not supported for the title. Please download in another audio format.'

Any suggestions?

URL from openaudible -
https://www.audible.com/pd/B09MZRGMY9

**Comment by Naburu011** [comment]
I am getting this as well with multiple titles, I have even tried to download from the Audible website and it opens a page with that text. It may not be an OpenAudible issue, but a general Audible issue.

**Comment by Stanmore1903** [comment]
Error shown on Audible.com site:
This audio format is not supported for the title. Please download in another audio format.

Confirmed same behaviour whether download is attempted via Audible.com site or OpenAudible;
1) books offered by the Audible site ONLY as single files can be downloaded;
2) books offered by the Audible site as a single file OR in parts can only be downloaded as parts.

Problem is to do with Audible.com's presentation of large files broken into parts, not OpenAudible. The Audible.com site;
- fails to serve the single large files for download;
- serves the part files for download, but does not present them to OpenAudible via the Audible.com API.

Testing procedure follows.

Downloaded test file to local disk Downloads folder via Audible.com in 2 parts of 483.7MB & 411.6MB. (Note: do not download into OpenAudible's AAX folder & import from there. Even though the import progress dialog reports success, OpenAudible will not play or convert to M4B).

Imported both parts of test file into OpenAudible AAX folder from local disk Downloads folder. Import dialog reported no errors. After import, OpenAudible showed 2 parts correctly labelled, played them & converted them to M4B. 

However, OpenAudible reported no change in number of files remaining to download. It does not recognise that it has the whole book as 2 parts.

Did a full library sync. 

1) OpenAudible did not detect that the test file was on the local disk as 2 parts.

2) OpenAudible offered to donwload all unsynced files but failed as before.

**Comment by Weldawadyathink** [comment]
I am having the same issue. @Stanmore1903 your list of symptoms matches mine perfectly. It seems like amazon has some issues with downloading single part files. I also tested downloads in the iOS audible app, with high quality and single part settings set (equivalent to what OpenAudible should be downloading). These downloads worked perfectly, so whatever internal API the apps use is unaffected. 

I also contacted audible live chat support. After trudging through the usual support nonsense, the tech finally seemed to understand that it was an audible issue and not an issue with my computer. They escalated it to their technical team. I guess time will tell if they actually fix this. I hope this is quick. I just bought a book I want to read, and I really don't want to have to use the terrible audible app.

**Comment by Stanmore1903** [comment]
Good work making yourself audible.


------

David Morrell

**Comment by benhall847** [comment]
I see,

I confirmed this is an issue with Amazon/Audible.

I see the same message on Audibles website when trying to download the book from there.

As mentioned above - you can download the book in 'parts'.

Closing this ticket due to not being an openAudible issue.

**Comment by Weldawadyathink** [comment]
This issue, both downloading through the audible website and through open audible appears to be resolved. I can download my books again!
