### ISSUE TITLE
Download format wrong

### ISSUE THREAD

**Issue by trueAl** [openaudible/openaudible#825]
This is the error msg I'm receiving...

Jan 05, 2022 8:27:38 PM org.openaudible.download.DownloadJob download
INFO: Downloading book: Pa

Jan 05, 2022 8:27:39 PM org.openaudible.util.queues.ThreadedQueue jobError
INFO: DownloadQueue error processing Download Pandora's Star item Pandora's Star
java.lang.Exception: Download error:This audio format is not supported for the title. Please download in another audio format. for Pandora's Star
	at org.openaudible.download.DownloadAAXJob.handleError(DownloadAAXJob.java:70)
	at org.openaudible.download.DownloadAAXJob.checkEntity(DownloadAAXJob.java:45)
	at org.openaudible.download.DownloadJob.download(DownloadJob.java:92)
	at org.openaudible.download.DownloadAAXJob.processJob(DownloadAAXJob.java:205)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:484)

I've been able to download books from the same publisher without any problem.

Thanks

_Originally posted by @JdVarney in https://github.com/openaudible/openaudible/issues/820#issuecomment-1006213025_

**Comment by trueAl** [comment]
I can confirm this behaviour with the 3.3 version of openAudible on both mac and windows platforms.
Does not affect all audiobooks, just some. In my case 38/98 books could be downloaded, 60 don't work.
I know it worked earlier.

Happy to assist with testing

**Comment by SRawrKnight** [comment]
I was having this same problem and determined that it was an Audible issue, not a problem with this application. I could not download the single-part files directly from Audible on my browser either. I got the same error. After chatting for a ridiculous amount of time with their support I got this answer: "I have got it check from our resources and this issue is already escalated. It may take up to 3-5 business days for the issue to be fixed."

**Comment by kamituel** [comment]
A (possibly obvious) workaround that works for me:

After opening my Audible library in the browser, I wasn't able to download a book using the "Download -> Full" menu option. However, I was able to download "Part 1" and "Part 2" separately. This left me with two .mp4 files in my Downloads folder. I then dragged and dropped both files into my OpenAudible window.

By the way, I just purchased OpenAudible and I got this error as soon as I tried to convert the first book. Ouch ;)

**Comment by OlafVal** [comment]
Thanks for the workaround, that one helped me a lot.  By the way, regarding the "Ouch", I feel the same way and would be truly grateful for an update.

**Comment by openaudible** [comment]
We are attempting to re-create the issue on our end. So far none of our libraries contain books that can't be downloaded, but still checking. You can try again to see if it resolves.. And we will look at some possible solutions on our end. Hopefully just a temporary issue on Audible's side of things...

**Comment by SRawrKnight** [comment]
For my part it seems to have resolved. I am currently downloading several of the titles that failed earlier in the day.

**Comment by openaudible** [comment]
I’m seeing the same thing. Looks resolved!
