### ISSUE TITLE
 31 hour-long file - only first 10 hours in converted file 

### ISSUE THREAD

**Issue by wildcatherder** [openaudible/openaudible#828]
Very long Audible file after conversion - file is only about 1/3rd as long as the original.

**Comment by openaudible** [comment]
Did you download the file using OA? You may have gotten just "part one" of a multi-part book if you downloaded it some other way.

You can do a "Book Info" and go to the book report tab and look at all the details about the book -- size and duration of AAX file, size and duration of mp3 or m4b file. 

If needed, you can delete the book, do a full library scan, and re-download and re-covert the book. There are no known issues with long books.

**Comment by wildcatherder** [comment]
Apparently, it was truncated during download.  I downloaded it again and
everything is fine.

Thank you for responding so promptly.

Boyd Crow

**Comment by openaudible** [comment]
Great to hear.
