### ISSUE TITLE
Downloading art

### ISSUE THREAD

**Issue by Blimby** [openaudible/openaudible#83]
Any chance of a switch to download art with an info refresh? Currently it looks as though you have to download the whole book to capture the art.

**Comment by openaudible** [comment]
The art is in the aax file, so getting it from the web site shouldn't be needed if you download the book.. but yes, could do that..

**Comment by Blimby** [comment]
That'd be great. I don't really want to download the books as I can download on-demand, but I think the app is already the best way of cataloguing an Audible collection and having the artwork would be the icing on the cake!

**Comment by openaudible** [comment]
Good point. Will take a look. Re-open if not in the next release >= 1.4.2.
