### ISSUE TITLE
Can# sync my imported books

### ISSUE THREAD

**Issue by HerbJul** [openaudible/openaudible#830]
Imported books cannot be synchronized, even if the books have already been purchased from audible and downloaded via Safari.

**Comment by openaudible** [comment]
Generally if the books have the same product id or ain number they should sync up. But importing is a bit hit and miss— we typically recommend only downloading using our app. 

So click on one book and look at the IDs and compare them to the other similar book. If they don’t match, they could be two different versions of the same book— which we wouldn’t want to merge. People often want to have two copies of the same book with slight differences.

**Comment by HerbJul** [comment]
Could you still implement the function, which you could at least also deactivate again when it is not needed?

**Comment by openaudible** [comment]
I don’t know what you mean. If you have a duplicated book, delete the one not automatically imported by OpenAudible. If you provide a full description of the problem with book ID’s and what is currently unsolvable we might be able to assist. But doesn’t sound like a common problem so unlikely to add more complexity to deal with it.
