### ISSUE TITLE
Contribute translation? (DE)

### ISSUE THREAD

**Issue by Plaenkler** [openaudible/openaudible#832]
I would like to support the project with translations. Is there official information for contributors? I couldn't find any.

**Comment by openaudible** [comment]
Great idea and thank you for the offer!

I created a repo and sent you an invite. If you have any questions about submitting your changes (usually through a Pull Request), just let me know. 

If anyone is interested in helping with translations, let me know and I'll send you an invite. Keeping the i18n repo private for the time being.

Thanks!

**Comment by openaudible** [comment]
Thank you. Merging your edits into next beta and release. !!!
