### ISSUE TITLE
Automatic relocation of the library

### ISSUE THREAD

**Issue by Plaenkler** [openaudible/openaudible#833]
A suggestion: If the **Library** path is adjusted under **Edit -> Settings -> Directories**, the content should be automatically moved to the new environment.

**Comment by openaudible** [comment]
That can get tricky-- if one file is open and can't be moved, the library can be broken. 
But we do need to add better support for multiple libraries. 
Closing as "feature request" and the multiple library manager is a thing we have been working on in the dev builds.
