### ISSUE TITLE
Delete Book Dialog deletes book on escape

### ISSUE THREAD

**Issue by Plaenkler** [openaudible/openaudible#834]
If the button to close the dialog is pressed, the book will disappear anyway. The expected reaction would be that the book stays in the library.

![Dialog](https://user-images.githubusercontent.com/60503970/149677997-500d084a-9caf-492a-a5b2-24c2fee14ff4.PNG)

**Comment by openaudible** [comment]
Thank you. Fixing and working on new releases.

**Comment by openaudible** [comment]
Fixed in beta. Please re-open if you see anything.
https://openaudible.org/beta
