### ISSUE TITLE
Link to always download latest beta version

### ISSUE THREAD

**Issue by Weldawadyathink** [openaudible/openaudible#835]
Is there a url that will always download the latest beta version of the software?

For example, you can always download the latest release version (for linux sh) at https://openaudible.org/latest/OpenAudible_x86_64.sh

Is there a similar way to download the latest beta version?

**Comment by openaudible** [comment]
Not yet. But could add one. Why do you want it? (Btw, latest link will change for Mac users with addition of M1 processor builds).

**Comment by Weldawadyathink** [comment]
I am trying to setup an automated docker build that pulls the latest beta version. The current dockerfile pulls from the link above to always get the latest version. In order to build a beta docker container, I currently need to modify the dockerfile to target a specific version url.

I would imagine this would also be useful for linux repository maintainers if they want to include a beta version of the package.

**Comment by openaudible** [comment]
When we release a new release version the beta goes away. Often there is only a beta 10% of the time. 

but the beta really is not for public use. Not tested and may have significant flaws. 

Would prefer it isn’t widely distributed… but.

You could use jq to pull it from https://openaudible.org/beta/swt_version.json
And know that link may 404.
