### ISSUE TITLE
Preferences cannot be saved - Kubuntu 20.04

### ISSUE THREAD

**Issue by AvengingSpirit** [openaudible/openaudible#836]
Hello!
I found that OpenAudible under a KDE-Ubuntu 20.04 will not save it's changed preferences if you do so. The OK button is marked blue, but you cannot access it neither with a mouse nor the keyboard. That may be a problem with the access rights, but it lokks like nothing happens at all. Version of OpenAudible is 3.3.

**Comment by openaudible** [comment]
Confirmed. It does look like the ok button is getting called, but it doesn't close the dialog box as expected.
But the internal browser is also not working for me-- try going to About: Diagnostics.. and I get an error. Not sure if either can be fixed. Will try when I get some time.

**Comment by openaudible** [comment]
Fixed in the next beta and release.
For now, you can try:

```
sudo apt install libwebkit2gtk-4.0.37
sudo apt install gstreamer1.0-plugins-bad
```

Thanks for the report!
