### ISSUE TITLE
Update to Docker Container

### ISSUE THREAD

**Issue by pusta** [openaudible/openaudible#838]
The latest docker container is running 3.2.2, and it appears 3.3 is the latest version.  Are there plans to update the docker image to 3.3?  Thanks!

**Comment by openaudible** [comment]
Looks like it is out of date. Try building it yourself using git clone and build with --no-cache option. 

Or open the terminal from within the app and download the latest run the installer. 

But we have one outstanding issue with the built-in webkit browser we are still trying to solve. A little backlogged on linux builds. Please open issues on the https://github.com/openaudible/openaudible_docker repo if it has to do with docker. 

Thanks.
