### ISSUE TITLE
Manually Adding Cover Image Doesn't Save

### ISSUE THREAD

**Issue by shelaffs** [openaudible/openaudible#840]
Hello! 

I'm using version 3.3 of Open Audible, licensed for Mac. 
I finished downloading and converting all of my Audible purchases and the software works great, thanks so much! 

I decided to add my purchases from Libro.fm to my library so I used Open Audible to combine the individual MP3 files for those into a single long one, and add it to my library with my Audible purchases. However, the cover artwork from the files didn't carry through the merge. I tried to manually add the cover artwork by selecting "Get Info" for the book in OpenAudible, navigating to the Image tab and adding the cover artwork there. But when I select "save changes" it goes through the Update Book process, and the artwork does not appear. If I select "Get Info" again, the selected artwork is not in the image tab as I would expect. 

Using an M1 Mac, OSX 12.0.1 Monterey. Thank you!

**Comment by openaudible** [comment]
Thank you for finding that. Fixed and will be in the next beta 5. https://openaudible.org/beta 
Feel free to try the new M1 version.

**Comment by openaudible** [comment]
Fixed in latest beta. Feedback welcome.

**Comment by shelaffs** [comment]
Can verify the fix worked! Added some other issues I found with the beta release to the beta 7 thread. Thanks for the great work!
