### ISSUE TITLE
3.3.04. beta M1 issues

### ISSUE THREAD

**Issue by the1gofer** [openaudible/openaudible#841]
I've noticed a couple of issues so far.
1.  the settings don't save between updates.  Specifically the folder download folder location.
2.  edit buttons for the preferences don't do anything. 
<img width="550" alt="Screen Shot 2022-01-21 at 9 20 28 PM" src="https://user-images.githubusercontent.com/2140724/150624460-57b308ad-fcbb-4e4b-b7e4-93d90f795021.png">

unfortunately, I can't do much testing, because I don't want it to fill up my hard drive with things I've already downloaded.

**Comment by openaudible** [comment]
That was annoying. We weren't getting mouse up events on the m1. Thank you for finding that. 

Fixed in beta 6...
