### ISSUE TITLE
final chapter truncated before end when splitting into chapters

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#843]
I have one audiobook where the final chapter ends before the end of the book meaning if I play the single file audiobook it is fine but if I split the audiobook into chapters I miss about the last 30sec of the last chapter, I think it is due to the aax file itself having incorrect chapter breaks....I have no idea how I would get audible to resolve that.. is there a way to create a final chapter for any audio after the end of the final chapter mark?

**Comment by openaudible** [comment]
Definitely can check to see if there is any time remaining after last chapter. But usually is bad chapter data. Can you drop and submit the aax file to https://openaudible.org/check.html and we’ll take a look at the meta data. (Or select book, get info, and select details and copy and paste the json and email to openaudible at email dot tg.

**Comment by openaudible** [comment]
I went ahead and changed the logic to just go thru the end of the book on the last chapter. Should be a rare event but it can’t hurt and should help in your case. Expect 3.4 to drop in a few days.

**Comment by feldegast** [comment]
Thanks, i have over 200 audiobooks and this is the only one with this issue, I sent the data to the email address above

**Comment by feldegast** [comment]
i would like to confirm that with version 3.4.1 this issue is fixed, the final split m4b file is not truncated :)
