### ISSUE TITLE
status icons (in queue and downloading) hard to tell apart

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#844]
in ver 2.2 when looking at items in the downloading queue it is hard to tell which is downloading or just waiting to download as the only difference is the tiny download icon is light green vs light grey.

instead of using light green maybe a dark green or another dark colour to make the contrast easy to spot

tip: take a screenshot, convert to grayscale, see how hard it is to see the difference
I use this when designing UIs to ensure there is sufficient contrast between components so they are easy to identify

**Comment by openaudible** [comment]
Thanks for the heads up. 

Send any large square transparent png to openaudible at email dot tg and I’m happy to use them. But will fix regardless.

**Comment by openaudible** [comment]
Ok. Fixed in the latest (hopefully last) beta:
https://openaudible.org/beta
Icons are still a little hard to see, but the colors are now distinct and no longer grayscale. 
Might make them a little bigger. (currently 20x20 for high DPI monitors and 10x10 for 72dpi.)
