### ISSUE TITLE
Output filenames when splitting chapters

### ISSUE THREAD

**Issue by Logen9Fingers** [openaudible/openaudible#845]
I previously had OpenAudible installed on another computer, and when splitting chapters, the output filename always (I thk) had a zero before the the first 9 chapters, ie...01, 02, 03, etc..., which was important when using filing systems on certain devices (more specifically, the Victor Reader Stream (accessible mp3 player for blind people). I have recently installed OpenAudible on another computer, and now the output filenames say 'Chapter 1', 'Chapter 2', 'Chapter 3', etc. This not helpful as, without the zero, the file order puts 'Chapter 20', after Chapter 1'. Why is this happening? Is it taking the output filename from metadata provided by the Audible aax file, or is the output filename definable somewhere in the software? I really hope this isn't a change to the later versions of OpenAudible, as this causes problems in that I have to manually add a 0 to the fist nine chapters, or, even worse, add zeros to the fist 99 chapters, if there are over 100 chapters...a real pain.

Any help you can give will be much appreciated!

**Comment by openaudible** [comment]
This is fixed in the latest beta and will be in the final 3.4 release coming later today.
