### ISSUE TITLE
Error downloading: Unable to download aaxc files

### ISSUE THREAD

**Issue by bporima** [openaudible/openaudible#847]
3.3.0.7-beta for Apple Silicon, license is valid

Connection to Audible (DE) works, I see my book list. Trying to download results in this error message.

I checked permissions on folders, but they seem ok

Thanks for checking!

**Comment by bporima** [comment]
Same with 3.3.0.8-beta

**Comment by openaudible** [comment]
I don't see the error message in your post. You can email me a section of the log file from the console window (File menu)

**Comment by openaudible** [comment]
I made a fix to correct bad error message.. but not sure exactly what is going on. Probably a book is now free and can't be downloaded using the old download URL audible gave you.

https://openaudible.org/beta
Closing, but feel free to send an error report from the application after attempting a full rescan and download of the problem book. Include the name of the book so its easy to find in the logs.

**Comment by bporima** [comment]
Hi, sorry for the delay! An uninstall/reinstall and reconnection to Audible fixed the problem for me. Before that, when the problem still existed, I tried several books, all resulting in the error message in the subject. After reinstall all works flawlessly, same books now download and transcode perfectly.

**Comment by openaudible** [comment]
Glad to hear! Thanks for the feedback!
