### ISSUE TITLE
Overwrite local metadata of m4b with metadata from audible?

### ISSUE THREAD

**Issue by ChadTaljaardt** [openaudible/openaudible#848]
Hello, 

I have several books that have incomplete or incorrect metadata. I am wondering if there is a way to overwrite this metadata with the data from audible. 

I thought that doing `file->import url` and then using the following would work, but i get a error: 

```
https://www.audible.co.uk/pd/Harry-Potter-and-the-Philosophers-Stone-Book-1-Audiobook/B017V568SY
```

![TnVHdGs](https://user-images.githubusercontent.com/13891249/151642663-fdf0afb5-6f81-407d-aec7-72117dbf9b97.png)

Does your software support this?

Thanks!

**Comment by openaudible** [comment]
Import URL is for links to a download of a book. 
You need to download your books using our app and the tags should all be correct.
If you have a book but you didn't buy it from audible, there isn't a way to auto-populate a book's meta data
There is a meta data tag editor included in OpenAudible, under Get Info. 
Good luck!

**Comment by ChadTaljaardt** [comment]
> Import URL is for links to a download of a book. You need to download your books using our app and the tags should all be correct. If you have a book but you didn't buy it from audible, there isn't a way to auto-populate a book's meta data There is a meta data tag editor included in OpenAudible, under Get Info. Good luck!

I tried to edit the information, but once i saved it and then went to re-edit it, it had reverted back to the original.
