### ISSUE TITLE
Cannot split some books

### ISSUE THREAD

**Issue by iceisfun** [openaudible/openaudible#856]
Can't split some books, ex Wheel of Time book 1

Error The Eye of the World Chapter less than 1000 ms: 02 Maps 1108244/420

**Comment by openaudible** [comment]
Hmm. That sounds like a bug somewhere.  Why is there a chapter less than 1 second in length?

**Comment by iceisfun** [comment]
Looks to me like chapter "02 Maps" is 420ms

**Comment by openaudible** [comment]
Thank you. Fixed in latest beta. Also added a speed improvement for splitting books-- you should see 5-8x faster times.
https://openaudible.org/beta

**Comment by iceisfun** [comment]
splits much faster and works with small chapters.

Thanks!

Split The Eye of the World to /home/iceisfun/OpenAudible/books/The Eye of the World in 86.95

Good:1, Errors:0 Skipped:0
