### ISSUE TITLE
setting cancel job for item in download queue sets incorrect status

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#857]
Version 3.4.1 Mac Intel
I am downloading my whole collection and want to prioritise some books so I select 'cancel job' for the audiobooks I want to download later but instead of stopping their download their status is changed to downloading and then the audiobook is put back into the queue

**Comment by openaudible** [comment]
Thank you, fixed in latest beta,
https://openaudible.org/beta

**Comment by openaudible** [comment]
Great. Fixed in 3.4.2, released today.
