### ISSUE TITLE
Controls -> Full Library Sync loads 1st page over and over forever.

### ISSUE THREAD

**Issue by aljex** [openaudible/openaudible#86]
I have been able to download and convert most of my books ok. I'm past the usual points of just logging in correctly and getting the browser cookie, un-selected the checkbox in the account preferences to check for audible manager, etc. For most books I can manually click the download button and it works. The aax is downloaded, the book info is added to the list in OpenAudible, the aax is converted to mp3.

The issue I have (one of them) is when I try to use Controls -> Full Library Sync.
It loops forever loading the same page of the 1st 20 books over and over.

I've only used 1.4.0 and 1.4.1 so far. I just discovered OpenAudible a couple days ago.
I'm on Lubuntu and using the 1.4.1.deb currently.

This is the tail end of the console log after letting it loop for a while. It says it's loading page 206 etc, but it's the same first page every time.

Possible quirk affecting this?
* The first 3 books listed in this library page:
BK_DOVE_000351: 	new:Crisis on Doona and Treaty at Do
BK_DOVE_001115: 	new:City of Darkness
BK_GALA_000025: 	new:If I Were You
... are ones that I purchased years ago, but which Audible has removed from the site, and so although they are listed in my library, they can not be downloaded. Also, the purchase date has somehow been changed to Jan 18 2019 but that is wrong. That's the day I called support to find out why I can't download them, so they must have done something that updated the date while they were poking around in my account.

It doesn't really look like that issue is the cause of this issue.
It looks like OA is just trying to use the "next" button, and the Audible site is not actually sending the next page.

---snip---

Jan 20, 2019 7:56:33 PM org.openaudible.audible.AudibleScraper _fetchLibrary
INFO: ******************* LIBRARY PAGE 206
Jan 20, 2019 7:56:33 PM org.openaudible.audible.AudibleScraper setURL
INFO: setURL:https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=206
Jan 20, 2019 7:56:33 PM org.openaudible.desktop.swt.manager.browser.GetPageTask getPage
INFO:  getPage:https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=206 js=true
Jan 20, 2019 7:56:34 PM org.openaudible.desktop.swt.manager.browser.GetPageTask task
INFO: 0:getPage:https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=206 completed 617 ms
07:56:33.845	07:00:00.004	waitForPageLoad:start
07:56:33.846	07:00:00.005	event:ProgComplete -> ProgressEvent{Browser {} time=0 data=null current=100 total=100}
07:56:34.348	07:00:00.507	browser state unknown -> complete
07:56:34.348	07:00:00.507	needQuery: last=0 new=1
07:56:34.458	07:00:00.617	query start: end:h_len=918692 hash=AB3CAA7D eq=false Last Query:110;ProgChanged:0ProgComplete:1LocChanging:0LocChanged:0;same=0;diff=0;url=https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=206
07:56:34.458	07:00:00.617	waitForPageLoad exit:613 result=h_len=918692 hash=AB3CAA7D inspect=Last Query:110;ProgChanged:0ProgComplete:1LocChanging:0LocChanged:0;same=0;diff=1;url=https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=206
Jan 20, 2019 7:56:34 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 1040 to disk:/home/bkw/OpenAudible/tmp/0.txt
Jan 20, 2019 7:56:34 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFO: Empty Product ID:
asin=B002V9ZD4G
fullTitle=The New York Times Audio Digest View all episodes View latest episodes Hide latest episodes
author=The New York Times
purchase_date=09-27-18
author_link=https://www.audible.com/search

Jan 20, 2019 7:56:34 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFO: Library page contains: 20 book(s)
Jan 20, 2019 7:56:34 PM org.openaudible.Audible ok
INFO: invalid author link on The New York Times Audio Digest 
Jan 20, 2019 7:56:34 PM org.openaudible.audible.AudibleScraper _fetchLibrary
INFO: pageNum=206 total=20 new=20 partial=0
Parsed:20 books
BK_DOVE_000351: 	new:Crisis on Doona and Treaty at Do
BK_DOVE_001115: 	new:City of Darkness
BK_GALA_000025: 	new:If I Were You
BK_BIMO_000921: 	new:Sten: Court of a Thousand Suns: 
BK_ADBL_033907: 	new:Storm World: Undying Mercenaries
BK_ADBL_016178: 	new:Imago
BK_ADBL_016177: 	new:Adulthood Rites: Xenogenesis, Bo
BK_ADBL_016176: 	new:Dawn: Xenogenesis, Book 1
BK_ADBL_023528: 	new:Will Save the Galaxy for Food
BK_HOWE_003509: 	new:The Algebraist
BK_ACX0_117242: 	new:The Lost Artifact
BK_ADBL_025667: 	new:The Consuming Fire: The Interdep
BK_ADBL_034199: 	new:Uncompromising Honor: Honor Harr
BK_ACX0_096726: 	new:The Lost Earth
BK_ACX0_083933: 	new:The Lost Planet: Lost Starship, 
: 	new:The New York Times Audio Digest 
BK_ACX0_074114: 	new:The Lost Patrol: Lost Starship S
BK_ACX0_059708: 	new:The Lost Colony: Lost Starship S
BK_PODM_001103: 	new:Galaxy's Edge
BK_ACX0_043484: 	new:The Lost Destroyer: Lost Starshi

Jan 20, 2019 7:56:34 PM org.openaudible.audible.AudibleScraper _fetchLibrary
INFO: ******************* LIBRARY PAGE 207
Jan 20, 2019 7:56:34 PM org.openaudible.audible.AudibleScraper setURL
INFO: setURL:https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=207
Jan 20, 2019 7:56:34 PM org.openaudible.desktop.swt.manager.browser.GetPageTask getPage
INFO:  getPage:https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=207 js=true
Jan 20, 2019 7:56:35 PM org.openaudible.desktop.swt.manager.browser.GetPageTask task
INFO: 0:getPage:https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=207 completed 623 ms
07:56:34.500	07:00:00.009	waitForPageLoad:start
07:56:34.501	07:00:00.010	event:ProgComplete -> ProgressEvent{Browser {} time=0 data=null current=100 total=100}
07:56:35.006	07:00:00.515	browser state unknown -> complete
07:56:35.006	07:00:00.515	needQuery: last=0 new=1
07:56:35.114	07:00:00.623	query start: end:h_len=918692 hash=AB3CAA7D eq=false Last Query:108;ProgChanged:0ProgComplete:1LocChanging:0LocChanged:0;same=0;diff=0;url=https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=207
07:56:35.114	07:00:00.623	waitForPageLoad exit:614 result=h_len=918692 hash=AB3CAA7D inspect=Last Query:108;ProgChanged:0ProgComplete:1LocChanging:0LocChanged:0;same=0;diff=1;url=https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=207
Jan 20, 2019 7:56:35 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 1040 to disk:/home/bkw/OpenAudible/tmp/0.txt
Jan 20, 2019 7:56:35 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFO: Empty Product ID:
asin=B002V9ZD4G
fullTitle=The New York Times Audio Digest View all episodes View latest episodes Hide latest episodes
author=The New York Times
purchase_date=09-27-18
author_link=https://www.audible.com/search

Jan 20, 2019 7:56:35 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFO: Library page contains: 20 book(s)
Jan 20, 2019 7:56:35 PM org.openaudible.Audible ok
INFO: invalid author link on The New York Times Audio Digest 
Jan 20, 2019 7:56:35 PM org.openaudible.audible.AudibleScraper _fetchLibrary
INFO: pageNum=207 total=20 new=20 partial=0
Parsed:20 books
BK_DOVE_000351: 	new:Crisis on Doona and Treaty at Do
BK_DOVE_001115: 	new:City of Darkness
BK_GALA_000025: 	new:If I Were You
BK_BIMO_000921: 	new:Sten: Court of a Thousand Suns: 
BK_ADBL_033907: 	new:Storm World: Undying Mercenaries
BK_ADBL_016178: 	new:Imago
BK_ADBL_016177: 	new:Adulthood Rites: Xenogenesis, Bo
BK_ADBL_016176: 	new:Dawn: Xenogenesis, Book 1
BK_ADBL_023528: 	new:Will Save the Galaxy for Food
BK_HOWE_003509: 	new:The Algebraist
BK_ACX0_117242: 	new:The Lost Artifact
BK_ADBL_025667: 	new:The Consuming Fire: The Interdep
BK_ADBL_034199: 	new:Uncompromising Honor: Honor Harr
BK_ACX0_096726: 	new:The Lost Earth
BK_ACX0_083933: 	new:The Lost Planet: Lost Starship, 
: 	new:The New York Times Audio Digest 
BK_ACX0_074114: 	new:The Lost Patrol: Lost Starship S
BK_ACX0_059708: 	new:The Lost Colony: Lost Starship S
BK_PODM_001103: 	new:Galaxy's Edge
BK_ACX0_043484: 	new:The Lost Destroyer: Lost Starshi

Jan 20, 2019 7:56:35 PM org.openaudible.audible.AudibleScraper _fetchLibrary
INFO: ******************* LIBRARY PAGE 208
Jan 20, 2019 7:56:35 PM org.openaudible.audible.AudibleScraper setURL
INFO: setURL:https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=208
Jan 20, 2019 7:56:35 PM org.openaudible.desktop.swt.manager.browser.GetPageTask getPage
INFO:  getPage:https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=208 js=true
Jan 20, 2019 7:56:35 PM org.openaudible.desktop.swt.manager.browser.GetPageTask task
INFO: 0:getPage:https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=208 completed 635 ms
07:56:35.156	07:00:00.008	waitForPageLoad:start
07:56:35.156	07:00:00.008	event:ProgComplete -> ProgressEvent{Browser {} time=0 data=null current=100 total=100}
07:56:35.663	07:00:00.515	browser state unknown -> complete
07:56:35.663	07:00:00.515	needQuery: last=0 new=1
07:56:35.783	07:00:00.635	query start: end:h_len=918692 hash=AB3CAA7D eq=false Last Query:120;ProgChanged:0ProgComplete:1LocChanging:0LocChanged:0;same=0;diff=0;url=https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=208
07:56:35.783	07:00:00.635	waitForPageLoad exit:627 result=h_len=918692 hash=AB3CAA7D inspect=Last Query:120;ProgChanged:0ProgComplete:1LocChanging:0LocChanged:0;same=0;diff=1;url=https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=208
Jan 20, 2019 7:56:35 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 1040 to disk:/home/bkw/OpenAudible/tmp/0.txt
Jan 20, 2019 7:56:35 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFO: Empty Product ID:
asin=B002V9ZD4G
fullTitle=The New York Times Audio Digest View all episodes View latest episodes Hide latest episodes
author=The New York Times
purchase_date=09-27-18
author_link=https://www.audible.com/search

Jan 20, 2019 7:56:35 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFO: Library page contains: 20 book(s)
Jan 20, 2019 7:56:35 PM org.openaudible.Audible ok
INFO: invalid author link on The New York Times Audio Digest 
Jan 20, 2019 7:56:35 PM org.openaudible.audible.AudibleScraper _fetchLibrary
INFO: pageNum=208 total=20 new=20 partial=0
Parsed:20 books
BK_DOVE_000351: 	new:Crisis on Doona and Treaty at Do
BK_DOVE_001115: 	new:City of Darkness
BK_GALA_000025: 	new:If I Were You
BK_BIMO_000921: 	new:Sten: Court of a Thousand Suns: 
BK_ADBL_033907: 	new:Storm World: Undying Mercenaries
BK_ADBL_016178: 	new:Imago
BK_ADBL_016177: 	new:Adulthood Rites: Xenogenesis, Bo
BK_ADBL_016176: 	new:Dawn: Xenogenesis, Book 1
BK_ADBL_023528: 	new:Will Save the Galaxy for Food
BK_HOWE_003509: 	new:The Algebraist
BK_ACX0_117242: 	new:The Lost Artifact
BK_ADBL_025667: 	new:The Consuming Fire: The Interdep
BK_ADBL_034199: 	new:Uncompromising Honor: Honor Harr
BK_ACX0_096726: 	new:The Lost Earth
BK_ACX0_083933: 	new:The Lost Planet: Lost Starship, 
: 	new:The New York Times Audio Digest 
BK_ACX0_074114: 	new:The Lost Patrol: Lost Starship S
BK_ACX0_059708: 	new:The Lost Colony: Lost Starship S
BK_PODM_001103: 	new:Galaxy's Edge
BK_ACX0_043484: 	new:The Lost Destroyer: Lost Starshi

Jan 20, 2019 7:56:35 PM org.openaudible.audible.AudibleScraper _fetchLibrary
INFO: ******************* LIBRARY PAGE 209
Jan 20, 2019 7:56:35 PM org.openaudible.audible.AudibleScraper setURL
INFO: setURL:https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=209
Jan 20, 2019 7:56:35 PM org.openaudible.desktop.swt.manager.browser.GetPageTask getPage
INFO:  getPage:https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=209 js=true
Jan 20, 2019 7:56:36 PM org.openaudible.desktop.swt.manager.browser.GetPageTask task
INFO: 0:getPage:https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=209 completed 649 ms
07:56:35.821	07:00:00.005	waitForPageLoad:start
07:56:35.822	07:00:00.006	event:ProgComplete -> ProgressEvent{Browser {} time=0 data=null current=100 total=100}
07:56:36.340	07:00:00.524	browser state unknown -> complete
07:56:36.340	07:00:00.524	needQuery: last=0 new=1
07:56:36.465	07:00:00.649	query start: end:h_len=918692 hash=AB3CAA7D eq=false Last Query:125;ProgChanged:0ProgComplete:1LocChanging:0LocChanged:0;same=0;diff=0;url=https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=209
07:56:36.465	07:00:00.649	waitForPageLoad exit:644 result=h_len=918692 hash=AB3CAA7D inspect=Last Query:125;ProgChanged:0ProgComplete:1LocChanging:0LocChanged:0;same=0;diff=1;url=https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=209
Jan 20, 2019 7:56:36 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 1040 to disk:/home/bkw/OpenAudible/tmp/0.txt
Jan 20, 2019 7:56:36 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFO: Empty Product ID:
asin=B002V9ZD4G
fullTitle=The New York Times Audio Digest View all episodes View latest episodes Hide latest episodes
author=The New York Times
purchase_date=09-27-18
author_link=https://www.audible.com/search

Jan 20, 2019 7:56:36 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFO: Library page contains: 20 book(s)
Jan 20, 2019 7:56:36 PM org.openaudible.Audible ok
INFO: invalid author link on The New York Times Audio Digest 
Jan 20, 2019 7:56:36 PM org.openaudible.audible.AudibleScraper _fetchLibrary
INFO: pageNum=209 total=20 new=20 partial=0
Parsed:20 books
BK_DOVE_000351: 	new:Crisis on Doona and Treaty at Do
BK_DOVE_001115: 	new:City of Darkness
BK_GALA_000025: 	new:If I Were You
BK_BIMO_000921: 	new:Sten: Court of a Thousand Suns: 
BK_ADBL_033907: 	new:Storm World: Undying Mercenaries
BK_ADBL_016178: 	new:Imago
BK_ADBL_016177: 	new:Adulthood Rites: Xenogenesis, Bo
BK_ADBL_016176: 	new:Dawn: Xenogenesis, Book 1
BK_ADBL_023528: 	new:Will Save the Galaxy for Food
BK_HOWE_003509: 	new:The Algebraist
BK_ACX0_117242: 	new:The Lost Artifact
BK_ADBL_025667: 	new:The Consuming Fire: The Interdep
BK_ADBL_034199: 	new:Uncompromising Honor: Honor Harr
BK_ACX0_096726: 	new:The Lost Earth
BK_ACX0_083933: 	new:The Lost Planet: Lost Starship, 
: 	new:The New York Times Audio Digest 
BK_ACX0_074114: 	new:The Lost Patrol: Lost Starship S
BK_ACX0_059708: 	new:The Lost Colony: Lost Starship S
BK_PODM_001103: 	new:Galaxy's Edge
BK_ACX0_043484: 	new:The Lost Destroyer: Lost Starshi

Jan 20, 2019 7:56:36 PM org.openaudible.audible.AudibleScraper _fetchLibrary
INFO: ******************* LIBRARY PAGE 210
Jan 20, 2019 7:56:36 PM org.openaudible.audible.AudibleScraper setURL
INFO: setURL:https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=210
Jan 20, 2019 7:56:36 PM org.openaudible.desktop.swt.manager.browser.GetPageTask getPage
INFO:  getPage:https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=210 js=true
Jan 20, 2019 7:56:37 PM org.openaudible.desktop.swt.manager.browser.GetPageTask task
INFO: 0:getPage:https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=210 completed 635 ms
07:56:36.505	07:00:00.006	waitForPageLoad:start
07:56:36.506	07:00:00.007	event:ProgComplete -> ProgressEvent{Browser {} time=0 data=null current=100 total=100}
07:56:37.010	07:00:00.511	browser state unknown -> complete
07:56:37.010	07:00:00.511	needQuery: last=0 new=1
07:56:37.134	07:00:00.635	query start: end:h_len=918692 hash=AB3CAA7D eq=false Last Query:124;ProgChanged:0ProgComplete:1LocChanging:0LocChanged:0;same=0;diff=0;url=https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=210
07:56:37.134	07:00:00.635	waitForPageLoad exit:629 result=h_len=918692 hash=AB3CAA7D inspect=Last Query:124;ProgChanged:0ProgComplete:1LocChanging:0LocChanged:0;same=0;diff=1;url=https://www.audible.com/lib?ref=a_lib_c5_pageNext&pf_rd_p=f7f7772a-0d4c-4af2-affd-126e1009604a&pf_rd_r=6XGSZFMRQVDK94MWSDH2&page=210
Jan 20, 2019 7:56:37 PM org.openaudible.util.HTMLUtil writeFile
INFO: wrote 1040 to disk:/home/bkw/OpenAudible/tmp/0.txt
Jan 20, 2019 7:56:37 PM org.openaudible.desktop.swt.manager.AudibleGUI run
SEVERE: Error refreshing library
java.lang.Exception: Operation canceled
	at org.openaudible.progress.IProgressTask.throwCanceled(IProgressTask.java:21)
	at org.openaudible.audible.AudibleScraper._fetchLibrary(AudibleScraper.java:308)
	at org.openaudible.audible.AudibleScraper.fetchLibrary(AudibleScraper.java:410)
	at org.openaudible.Audible.updateLibrary(Audible.java:692)
	at org.openaudible.desktop.swt.manager.AudibleGUI$1.run(AudibleGUI.java:238)

Jan 20, 2019 7:56:37 PM org.openaudible.desktop.swt.gui.progress.ProgressDialog runTask
SEVERE: java.lang.InterruptedException: The operation was cancelled
Jan 20, 2019 7:56:38 PM org.openaudible.desktop.swt.manager.browser.BrowserWebClient debug
INFO: web event orphan ProgressEventCompleted:ProgressEvent{Browser {} time=0 data=null current=100 total=100}
Jan 20, 2019 7:56:38 PM org.openaudible.audible.parser.LibraryParser parseLibraryFragment
INFO: Skipping table with:0 cols
Jan 20, 2019 7:56:38 PM org.openaudible.desktop.swt.manager.AudibleGUI checkForLibraryPage
INFO: Added 0 books from library took 2 ms. to complete.
---snip---

**Comment by openaudible** [comment]
I wasn't able to figure out a full fix from your message above. I added a few lines of console messages when discarding books.. so feel free to try again with the 1.4.2 and post the same style console log.

**Comment by aljex** [comment]
Will do, thanks!

**Comment by aljex** [comment]
I can't use the browser window to even manually download the books. Whenever page 1 of the library is loaded by any means, it starts scanning the entire library all by itself and then ends with the "your library is empty" page. I basically can not even look at page 1.

If I reload the library, and hit cancel in the scanning library popup before it finishes, then the scan will abort, and the browser is left on page 4 or 5 which is how far it gets before I can abort it.

At that point, I can navigate to other pages by clicking on the page numbers or by using the prev/next links, and what will happen is when I load that other page, the scanning library popup will happen, but only scan that one page, and it doesn't break the browser. After it scans that one page, the browser window still shows that library page instead of "your library is empty", and I can manually click the download links on that page.

EXCEPT, not for page 1. I can go prev, prev, prev through the other pages one at a time and each page will load, scan itself, and be ok after the scan popup goes away, but if I "prev" to page 1, then it scans all pages again not just page 1. And I'm left with a "your library is empty" page again.

I can view the same page 1 of my library in firefox, and download the aax files from there, and manually save them in the openaudible aax folder, and openaudible can then import and convert them, and that all seems to be fine, and the only difference is it loses a little bit of metadata that way since it wasn't scraped from the web page. For instance the purchase date. I don't care too much about that, just reporting what I'm seeing.

**Comment by aljex** [comment]
I had "Automatically Update Web Page" selected. I unselected that, closed & reopened openaudible, still does the same thing, trying to scan the entire library any time page 1 is loaded.

**Comment by aljex** [comment]
Just trying again today, verified, all 3 automation checkboxes are un-checked, yet it starts doing that full library scan automatically any time you try to go to page 1 of the library. Page 1 and all the most recent books are simply inaccessible because you can't abort fast enough to catch it while it's still in page 1, and if you try to go back to page 1 after aborting the scan, it just starts another scan,, and if you don't abort, then the browser ends up on a broken page that says no books in library.

But one new thing I can add now is a work-around (other than using a regular browser and giving up the scraping):

After aborting the scan in the middle, if I press the link to reverse the sorting on the "date added" column in the browser, then I can get my most recent books because now they are on the last page instead of page 1. But also, even page 1 works now. After reversing the sort, all pages work normally including page 1.

This is all in the embedded browser not firefox etc just to be clear.

**Comment by aljex** [comment]
...spoke too soon I guess...

After reversing the sort order, I can jump to the last page (page 26 in my case, with the default initial setting of 20 books per page), and page 26 works fine. But in my case my last page happens to only have 3 books, and some of my most recent books are on page 25.

When I click on page 25, the page appears to load and populate fine at first, but the blue loading progress bar on the bottom-right sticks at about 90%. After several seconds, the full library scan starts! 

When I abort this scan as fast as I can, the browser is left on page 4 or 5, and the sort order is back to the default ("Date Added" column header has a down-arrow).

This processes is repeatable and consistent.

I can toggle the date added sort order again, jump to page 26 (last page) again. That page loads fine. The blue loading progress bar sticks at 90% or so for several seconds, and then a small window pop-up appears and disappears too fast to read what it was, and then the browser is left on page 26 with no more loading bar, and the contents of the page work. I can download those books. The library scan does not launch by itself no matter how long I let it sit there. Perhaps that brief pop-up was the library scan trying to run and then aborting itself out immediately for some reason.

After that, if I jump to page 25, (there are no other pages I can jump directly to from the last page other than the 1st page, and the 2nd to last page), it does as I described above. After several seconds it starts a libary scan and I can either abort the scan somewhere in the middle, or if I let it run, then I'm left on a broken page that says your library is empty.

This unwanted automatic library scan, and the bogus empty library page at the end should probably be submitted as their own separate issue, it's just coming up as part of documenting this issue about loading the books from page 1 over and over instead of the books from each page after 1.

**Comment by aljex** [comment]
Update, it's weirder than that. It's not the page numbers, it's something to do with the contents of the pages. I just went through all pages of my library in both forward and reverse  sort order.

With the default pagination (20 books / page), I have 26 pages total.

In the DEFAULT sort (date added, newest first), pages 1, 2, and 24 trigger an un-wanted full library scan.

In REVERSE sort, it's pages 2, 3, 24, & 25.

I am checking in a regular browser what titles are on those pages, where they overlap in both the forward & reverse sorts. Example, For page 1 in the normal sort, we can eliminate the first 3 titles, because page 26 in reverse sort is ok, and that's the same 3 titles. So there is something in the subset of titles in the overlap, that appear both on page 1 in normal sort, and page 25 in reverse sort.

I think page 2 in forward sort used to be ok. I have added 4 new books after Feb 3 when I described that problem originally, so it ooks like as I purchased new books, one or more of the last 4 items on page 1 was somehow a problem, got shifted down to page 2, and so now page 2 triggers a library scan also. Page 1 still triggers a scan, and so does page 24 (in default oldest-first sort), so whatever it is, there is more than one title that can cause it. This also means I guess I can just look very closely at the first 4 items on my current page 2 (before I add anything else and everything shifts down some more).
If page 2 used to be ok, and now it's not, that's what changed is the first 4 items moved from page 1 to page 2.

Unfortunately, those 4 items don't seem to be remarkable in any way. They are just ordinary books. Not periodicals etc. However page 2 does include the new york times periodical right now.

I just switched the filter at the top from "All Program Types" to "Audiobook", and now page 2 (in default sort) does NOT trigger a library scan.

Page 1 still DOES trigger a library scan even when set to "Audiobook".

And, once that library scan got triggered, the filter went back to "All Program Types".

Also, many many times, when loading any library page, it will just hang on 60% or 90% forever. When that happens, usually I can click on the previous or next page and the new page will load. The new page has at least a 50% chance of hanging also, but I can just click the previous page again and it may load to completion just fine the next time, or after 3 or 4 tries of loading the same page by flipping back & forth from, say 3 to 4, back to 3, back to 4, etc. both pages 3 and 4 might hang like that 3 or 4 times and then finally page 3 will load all the way one time, and then 4 will work too, then maybe 5 will hang or maybe 5 will work the first time etc.. All the pages where I said it loads ok without triggering a library sync, frequently it took many tries to get the page to actually load completely and have the blue progress bar on the bottom-right go away.

**Comment by aljex** [comment]
All these same pages load fine in firefox. They don't hang at 60 or 90%.

With the filter set to "Audiobook", I only have 23 pages total, and in the normal default sort order, pages 1 and 23 cause a library scan, no others.
The same two pages do it in reverse order too.

pages 1 & 23 in default order, and pages 1 & 23 in reverse order, are not the exact same two sets of books. In forward order, page 1 is my 20 most-recent books. In reverse order, page 23 is only my 15 most recent books for example.

I am struggling to find the patterm here but I'll keep poking. If I can identify any particular single example book where the presence of the item on the page causes the library scan, I'll offer to buy you that book so you can add it to your own library.

**Comment by openaudible** [comment]
Set the search order to recent purchases first. Click the column "Date Ordered" with the arrow pointing down. That way it should find new books on the first or second page. The quick scan only scans until no new books are found. A full scan is supposed to go through all pages, but I haven't spent the time to look at your logs to see where it is getting lost/confused. I also haven't experimented with different sort orders either.

**Comment by aljex** [comment]
Yes I've done that.
Along the way I noticed another clue, where I don't think the pattern is actually "the first page over and over", but "whatever happened to be displayed in the browser at the start of the scan"

That would *normally* be page 1 of your library in the default sorting etc..

But in all these different ways I was having the full scan start up from other pages, I noticed that, for instance one time I had only 3 books on the page because of the the combination of date filter, content type filter, and sort. When the library was scanning saying "scanning page 2, page 3, page 4 etc... *that time* it always said "found 3 books". Presumably because when the scan kicked off, there were only 3 books in the browser, even though the subsequent pages had 20 books each.

Or maybe that was just because only those 3 books were new and not yet imported into OpenAudible at the time. I think there were actually 4 new books at that time but because of the reverse sort order only 3 of them happened to land on the last page.

I don't know. I have not yet figured out any real pattern for certain. Sorry.

**Comment by openaudible** [comment]
I updated the version to 1.4.3. I added new code to save each library page in the tmp directory for each session.. So you can go through the actual .html and see what the "next" link is going to.. but it usually is the same URL with a page=xx.. you can also create a bug report after failure and it will send your tmp directory to us and I can take a look.. reference #86. 

The other thing to do is make sure you watch the browser page by moving it to the side of the main window.. so you can see what is going on-- you should see new books with each "next".

So far I haven't gotten any other reports like yours -- so I don't think it is widespread. You could try to reproduce by bringing up /lib, then comparing the URL you get with "next" to what we use.. and the behavior. 

I have noticed bugs in audible where I try to sort by author, and it reports "no books"--so audible itself can be flaky.
