### ISSUE TITLE
Unmatched existing aax files causing duplicates when re-downloading audiobooks

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#860]
When you download some audiobooks and then for whatever reason the Openaudible library data is lost/corrupted a resync happens and the data is downloaded again but often (had to resync twice and it has happened both times) the old existing AAX files are not matched to the new sync data and are given a genre of Audiobook rather than their genre from audible and so you end up with multiple copies of the same audiobook data, one is unmatched with the genre Aidiobook the other is the newly downloaded copy from Audible.
Would it be possible to improve the matching system of the already existing AAX files to match them to the list of audiobooks from amazon so they don't need to be re-downloaded or cause duplicates, maybe matching their ASIN/SKUs? or allowing the merging of records so the already downloaded AAX file can be manually merged with the amazon data?

**Comment by openaudible** [comment]
We key off of product id and ASIN. Shown in the book info panel. If both match (or one if the other is blank) the books should “merge”. 

So you need to look at the keys. Maybe the book was assigned a new product id or asin? 

The only duplicates I find are from imported m4b/mp3 without proper tags to identify the IDs. 

Also, if you just manually copy aax files to the library rather than import them, you can get duplicates. Better to drag and drop from an outside folder.

**Comment by feldegast** [comment]
ok thank you i think the issue is the aax files remained in their original directory (from when they were originally downloaded) when the resync happened they are not auto imported maybe when the library is empty and the rsync happens maybe a warning that the audiobooks might get imported as duplicates, I didn't copy them in I didn't move them and so the result is the same

**Comment by feldegast** [comment]
also the import process, does it do a move or a copy? from what I can see it is not clear....

**Comment by openaudible** [comment]
Imports make a copy. 

We do have some basic support for a Controls: "Refresh Files" and if we find books that we don't know about (say, you copied them directly to the books directory) OA is supposed to attempt to add them.. 

But for now, recommend deleting orphaned books that don't have an ID and are (therefore) not associated with a library.

**Comment by feldegast** [comment]
so in the event the OA list of audiobooks is corrupted and the list needs to be rebuilt I need to move the audiobooks out of the AAX directory and then do re-import and delete the old AAX files??
