### ISSUE TITLE
audiobooks auto download even if they have been canceled

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#863]
in ver 3.4.2 
when you select cancel job to stop audiobooks from downloading (say you want to only download one audiobook at a time to maximise bandwidth) 
downloads are removed from the download queue
and then if change your view between Downloading and All the following happens:
The cancelled downloads are automatically re-added to the download queue even though they had just been cancelled and begin downloading again
sometimes I have seen the downloads be re-added without having to change view

**Comment by openaudible** [comment]
Do you have automatically download books enabled in preferences? 
I'm not sure the expected behavior-- but if that is checked, they can all start downloading at any time...

**Comment by feldegast** [comment]
yes auto-download was enabled I thought it might notify/ask to disable this

**Comment by openaudible** [comment]
Yeah, that is normal.. Only check those if you want to always keep your books downloaded/converted.
