### ISSUE TITLE
Split selected books 1st file has different album artwork

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#864]
Ver 3.4.2 Mac
when I select to split selected audiobooks, the 1st file/chapter's artwork is different to the other files, it looks the same but in other meta data apps it reports that the 1st file's artwork is different for some reason

**Comment by openaudible** [comment]
The first chapter already contains the cover art from the book. The rest of the chapters don't get cover art unless we add it as a second step. (Couldn't figure out a way to do it in one step with ffmpeg and keep it in a format that shows up in windows, plex, etc.) So for that art, we may use the art from audible, and not from the aax file.. we could "fix" (adding a little performance hit) this but its the first time anyone has mentioned it..

**Comment by feldegast** [comment]
when i select split selected books each resulting file has cover art it;s
just that the 1st chapter's cover are is different (my metadata editor app
tells me it is different but just for the 1st chapter, chapters
2,3.4....all have identical artwork
they all look the same so it is probably some meta data that is being
flagged as different

**Comment by openaudible** [comment]
I'll switch it so that all chapters use the exact same image. Will be in the next beta.
