### ISSUE TITLE
Split selected books sometimes writes incorrect metadata

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#865]
Ver 3.4.2 Mac
Wen splitting audiobooks the metadata for some files is written incorrectly
the file name is correct from what I can see but

if you split a book with multiple chapters, sometimes 
the title and track numbers are written incorrectly
I see that it happens mostly on even tracks but also on the occasional odd-numbered track
the incorrect data is incorrectly duplicated from other tracks, rather than having their correct track numbers and titles causing duplicated track numbers and titles
I have tested this with multiple aax files that were split correctly in earlier versions of open audible....and they all now have this issue

**Comment by feldegast** [comment]
here is the book report data for one of the audiobooks I split that has this issue, every audiobook with more than 2 chapters I have seen this issue on though

{
 "copyright": "©2016 Dragonsteel Entertainment LLC (P)2016 Macmillan Audio",
 "chapters": [
  {
   "start_offset_ms": 0,
   "length_ms": 2762292,
   "title": "Chapter 1"
  },
  {
   "start_offset_ms": 2762292,
   "length_ms": 1399095,
   "title": "Chapter 2"
  },
  {
   "start_offset_ms": 4161387,
   "length_ms": 1073180,
   "title": "Chapter 3"
  },
  {
   "start_offset_ms": 5234567,
   "length_ms": 2310896,
   "title": "Chapter 4"
  },
  {
   "start_offset_ms": 7545464,
   "length_ms": 2211933,
   "title": "Chapter 5"
  },
  {
   "start_offset_ms": 9757396,
   "length_ms": 1748973,
   "title": "Chapter 6"
  },
  {
   "start_offset_ms": 11506370,
   "length_ms": 1088969,
   "title": "Chapter 7"
  },
  {
   "start_offset_ms": 12595339,
   "length_ms": 1894005,
   "title": "Chapter 8"
  },
  {
   "start_offset_ms": 14489345,
   "length_ms": 853240,
   "title": "Chapter 9"
  },
  {
   "start_offset_ms": 15342585,
   "length_ms": 1392779,
   "title": "Chapter 10"
  },
  {
   "start_offset_ms": 16735364,
   "length_ms": 1601295,
   "title": "Chapter 11"
  },
  {
   "start_offset_ms": 18336659,
   "length_ms": 1423662,
   "title": "Chapter 12"
  },
  {
   "start_offset_ms": 19760321,
   "length_ms": 2629056,
   "title": "Chapter 13"
  },
  {
   "start_offset_ms": 22389377,
   "length_ms": 1305147,
   "title": "Chapter 14"
  },
  {
   "start_offset_ms": 23694524,
   "length_ms": 1457284,
   "title": "Chapter 15"
  },
  {
   "start_offset_ms": 25151808,
   "length_ms": 1108846,
   "title": "Chapter 16"
  },
  {
   "start_offset_ms": 26260654,
   "length_ms": 1590010,
   "title": "Chapter 17"
  },
  {
   "start_offset_ms": 27850664,
   "length_ms": 2799258,
   "title": "Chapter 18"
  },
  {
   "start_offset_ms": 30649922,
   "length_ms": 1531124,
   "title": "Chapter 19"
  },
  {
   "start_offset_ms": 32181046,
   "length_ms": 1741311,
   "title": "Chapter 20"
  },
  {
   "start_offset_ms": 33922357,
   "length_ms": 2224565,
   "title": "Chapter 21"
  },
  {
   "start_offset_ms": 36146921,
   "length_ms": 2243605,
   "title": "Chapter 22"
  },
  {
   "start_offset_ms": 38390526,
   "length_ms": 1144326,
   "title": "Chapter 23"
  },
  {
   "start_offset_ms": 39534852,
   "length_ms": 1700212,
   "title": "Chapter 24"
  },
  {
   "start_offset_ms": 41235064,
   "length_ms": 1336494,
   "title": "Chapter 25"
  },
  {
   "start_offset_ms": 42571558,
   "length_ms": 1013133,
   "title": "Chapter 26"
  },
  {
   "start_offset_ms": 43584691,
   "length_ms": 751723,
   "title": "Chapter 27"
  },
  {
   "start_offset_ms": 44336414,
   "length_ms": 1347129,
   "title": "Chapter 28"
  },
  {
   "start_offset_ms": 45683542,
   "length_ms": 1374621,
   "title": "Chapter 29"
  },
  {
   "start_offset_ms": 47058164,
   "length_ms": 1728075,
   "title": "Chapter 30"
  },
  {
   "start_offset_ms": 48786239,
   "length_ms": 1001662,
   "title": "Chapter 31"
  },
  {
   "start_offset_ms": 49787902,
   "length_ms": 1310256,
   "title": "Chapter 32"
  },
  {
   "start_offset_ms": 51098157,
   "length_ms": 759571,
   "title": "Chapter 33"
  },
  {
   "start_offset_ms": 51857728,
   "length_ms": 50573,
   "title": "Chapter 34"
  },
  {
   "start_offset_ms": 51908301,
   "length_ms": 634276,
   "title": "Chapter 35"
  },
  {
   "start_offset_ms": 52542578,
   "length_ms": 246224,
   "title": "Chapter 36"
  },
  {
   "start_offset_ms": 52788802,
   "length_ms": 105279,
   "title": "Chapter 37"
  },
  {
   "start_offset_ms": 52894081,
   "length_ms": 1181162,
   "title": "Chapter 38"
  }
 ],
 "author": "Brandon Sanderson",
 "description": "Chapter 38",
 "abridged": "false",
 "title": "The Bands of Mourning - A Mistborn Novel",
 "title_short": "The Bands of Mourning: A Mistborn Novel",
 "duration": "15:01:15",
 "seconds": 54075,
 "report_by": "OpenAudible 3.4.2",
 "filename": "The Bands of Mourning.1",
 "release_date": "2016-01-01",
 "genre": "Audiobook",
 "files": [
  {
   "file": "/Volumes/Media/Plex Extra/OpenAudibleFiles/aax/The Bands of Mourning.1.AAX",
   "size": 437213571,
   "chapters": [
    {
     "start_time": "0.000000",
     "time_base": "1/22050",
     "start": 0,
     "end_time": "2762.292245",
     "end": 60908544,
     "id": 0,
     "tags": {"title": "Chapter 1"}
    },
    {
     "start_time": "2762.292245",
     "time_base": "1/22050",
     "start": 60908544,
     "end_time": "4161.387392",
     "end": 91758592,
     "id": 1,
     "tags": {"title": "Chapter 2"}
    },
    {
     "start_time": "4161.387392",
     "time_base": "1/22050",
     "start": 91758592,
     "end_time": "5234.567256",
     "end": 115422208,
     "id": 2,
     "tags": {"title": "Chapter 3"}
    },
    {
     "start_time": "5234.567256",
     "time_base": "1/22050",
     "start": 115422208,
     "end_time": "7545.463583",
     "end": 166377472,
     "id": 3,
     "tags": {"title": "Chapter 4"}
    },
    {
     "start_time": "7545.463583",
     "time_base": "1/22050",
     "start": 166377472,
     "end_time": "9757.396463",
     "end": 215150592,
     "id": 4,
     "tags": {"title": "Chapter 5"}
    },
    {
     "start_time": "9757.396463",
     "time_base": "1/22050",
     "start": 215150592,
     "end_time": "11506.369887",
     "end": 253715456,
     "id": 5,
     "tags": {"title": "Chapter 6"}
    },
    {
     "start_time": "11506.369887",
     "time_base": "1/22050",
     "start": 253715456,
     "end_time": "12595.339320",
     "end": 277727232,
     "id": 6,
     "tags": {"title": "Chapter 7"}
    },
    {
     "start_time": "12595.339320",
     "time_base": "1/22050",
     "start": 277727232,
     "end_time": "14489.344580",
     "end": 319490048,
     "id": 7,
     "tags": {"title": "Chapter 8"}
    },
    {
     "start_time": "14489.344580",
     "time_base": "1/22050",
     "start": 319490048,
     "end_time": "15342.585034",
     "end": 338304000,
     "id": 8,
     "tags": {"title": "Chapter 9"}
    },
    {
     "start_time": "15342.585034",
     "time_base": "1/22050",
     "start": 338304000,
     "end_time": "16735.364354",
     "end": 369014784,
     "id": 9,
     "tags": {"title": "Chapter 10"}
    },
    {
     "start_time": "16735.364354",
     "time_base": "1/22050",
     "start": 369014784,
     "end_time": "18336.658866",
     "end": 404323328,
     "id": 10,
     "tags": {"title": "Chapter 11"}
    },
    {
     "start_time": "18336.658866",
     "time_base": "1/22050",
     "start": 404323328,
     "end_time": "19760.320726",
     "end": 435715072,
     "id": 11,
     "tags": {"title": "Chapter 12"}
    },
    {
     "start_time": "19760.320726",
     "time_base": "1/22050",
     "start": 435715072,
     "end_time": "22389.376871",
     "end": 493685760,
     "id": 12,
     "tags": {"title": "Chapter 13"}
    },
    {
     "start_time": "22389.376871",
     "time_base": "1/22050",
     "start": 493685760,
     "end_time": "23694.524082",
     "end": 522464256,
     "id": 13,
     "tags": {"title": "Chapter 14"}
    },
    {
     "start_time": "23694.524082",
     "time_base": "1/22050",
     "start": 522464256,
     "end_time": "25151.808435",
     "end": 554597376,
     "id": 14,
     "tags": {"title": "Chapter 15"}
    },
    {
     "start_time": "25151.808435",
     "time_base": "1/22050",
     "start": 554597376,
     "end_time": "26260.654150",
     "end": 579047424,
     "id": 15,
     "tags": {"title": "Chapter 16"}
    },
    {
     "start_time": "26260.654150",
     "time_base": "1/22050",
     "start": 579047424,
     "end_time": "27850.663764",
     "end": 614107136,
     "id": 16,
     "tags": {"title": "Chapter 17"}
    },
    {
     "start_time": "27850.663764",
     "time_base": "1/22050",
     "start": 614107136,
     "end_time": "30649.922177",
     "end": 675830784,
     "id": 17,
     "tags": {"title": "Chapter 18"}
    },
    {
     "start_time": "30649.922177",
     "time_base": "1/22050",
     "start": 675830784,
     "end_time": "32181.045986",
     "end": 709592064,
     "id": 18,
     "tags": {"title": "Chapter 19"}
    },
    {
     "start_time": "32181.045986",
     "time_base": "1/22050",
     "start": 709592064,
     "end_time": "33922.356825",
     "end": 747987968,
     "id": 19,
     "tags": {"title": "Chapter 20"}
    },
    {
     "start_time": "33922.356825",
     "time_base": "1/22050",
     "start": 747987968,
     "end_time": "36146.921361",
     "end": 797039616,
     "id": 20,
     "tags": {"title": "Chapter 21"}
    },
    {
     "start_time": "36146.921361",
     "time_base": "1/22050",
     "start": 797039616,
     "end_time": "38390.526259",
     "end": 846511104,
     "id": 21,
     "tags": {"title": "Chapter 22"}
    },
    {
     "start_time": "38390.526259",
     "time_base": "1/22050",
     "start": 846511104,
     "end_time": "39534.852063",
     "end": 871743488,
     "id": 22,
     "tags": {"title": "Chapter 23"}
    },
    {
     "start_time": "39534.852063",
     "time_base": "1/22050",
     "start": 871743488,
     "end_time": "41235.063583",
     "end": 909233152,
     "id": 23,
     "tags": {"title": "Chapter 24"}
    },
    {
     "start_time": "41235.063583",
     "time_base": "1/22050",
     "start": 909233152,
     "end_time": "42571.557732",
     "end": 938702848,
     "id": 24,
     "tags": {"title": "Chapter 25"}
    },
    {
     "start_time": "42571.557732",
     "time_base": "1/22050",
     "start": 938702848,
     "end_time": "43584.690794",
     "end": 961042432,
     "id": 25,
     "tags": {"title": "Chapter 26"}
    },
    {
     "start_time": "43584.690794",
     "time_base": "1/22050",
     "start": 961042432,
     "end_time": "44336.413605",
     "end": 977617920,
     "id": 26,
     "tags": {"title": "Chapter 27"}
    },
    {
     "start_time": "44336.413605",
     "time_base": "1/22050",
     "start": 977617920,
     "end_time": "45683.542494",
     "end": 1007322112,
     "id": 27,
     "tags": {"title": "Chapter 28"}
    },
    {
     "start_time": "45683.542494",
     "time_base": "1/22050",
     "start": 1007322112,
     "end_time": "47058.163810",
     "end": 1037632512,
     "id": 28,
     "tags": {"title": "Chapter 29"}
    },
    {
     "start_time": "47058.163810",
     "time_base": "1/22050",
     "start": 1037632512,
     "end_time": "48786.239274",
     "end": 1075736576,
     "id": 29,
     "tags": {"title": "Chapter 30"}
    },
    {
     "start_time": "48786.239274",
     "time_base": "1/22050",
     "start": 1075736576,
     "end_time": "49787.901678",
     "end": 1097823232,
     "id": 30,
     "tags": {"title": "Chapter 31"}
    },
    {
     "start_time": "49787.901678",
     "time_base": "1/22050",
     "start": 1097823232,
     "end_time": "51098.157279",
     "end": 1126714368,
     "id": 31,
     "tags": {"title": "Chapter 32"}
    },
    {
     "start_time": "51098.157279",
     "time_base": "1/22050",
     "start": 1126714368,
     "end_time": "51857.728435",
     "end": 1143462912,
     "id": 32,
     "tags": {"title": "Chapter 33"}
    },
    {
     "start_time": "51857.728435",
     "time_base": "1/22050",
     "start": 1143462912,
     "end_time": "51908.301497",
     "end": 1144578048,
     "id": 33,
     "tags": {"title": "Chapter 34"}
    },
    {
     "start_time": "51908.301497",
     "time_base": "1/22050",
     "start": 1144578048,
     "end_time": "52542.577778",
     "end": 1158563840,
     "id": 34,
     "tags": {"title": "Chapter 35"}
    },
    {
     "start_time": "52542.577778",
     "time_base": "1/22050",
     "start": 1158563840,
     "end_time": "52788.802177",
     "end": 1163993088,
     "id": 35,
     "tags": {"title": "Chapter 36"}
    },
    {
     "start_time": "52788.802177",
     "time_base": "1/22050",
     "start": 1163993088,
     "end_time": "52894.081451",
     "end": 1166314496,
     "id": 36,
     "tags": {"title": "Chapter 37"}
    },
    {
     "start_time": "52894.081451",
     "time_base": "1/22050",
     "start": 1166314496,
     "end_time": "54075.243356",
     "end": 1192359116,
     "id": 37,
     "tags": {"title": "Chapter 38"}
    }
   ],
   "streams": [
    {
     "r_frame_rate": "0/0",
     "start_pts": 0,
     "channel_layout": "stereo",
     "duration_ts": 1192359116,
     "duration": "54075.243356",
     "bit_rate": "62794",
     "codec_tag_string": "aavd",
     "avg_frame_rate": "0/0",
     "nb_frames": "1164414",
     "codec_long_name": "AAC (Advanced Audio Coding)",
     "time_base": "1/22050",
     "profile": "LC",
     "index": 0,
     "max_bit_rate": "64004",
     "codec_name": "aac",
     "tags": {
      "creation_time": "2022-02-03T14:08:47.000000Z",
      "handler_name": "\u0019Apple Sound Media Handler",
      "language": "eng"
     },
     "start_time": "0.000000",
     "disposition": {
      "dub": 0,
      "karaoke": 0,
      "default": 1,
      "original": 0,
      "visual_impaired": 0,
      "forced": 0,
      "attached_pic": 0,
      "timed_thumbnails": 0,
      "comment": 0,
      "hearing_impaired": 0,
      "lyrics": 0,
      "clean_effects": 0
     },
     "codec_tag": "0x64766161",
     "sample_rate": "22050",
     "channels": 2,
     "sample_fmt": "fltp",
     "codec_time_base": "1/22050",
     "bits_per_sample": 0,
     "codec_type": "audio"
    },
    {
     "time_base": "1/22050",
     "r_frame_rate": "0/0",
     "start_pts": 0,
     "index": 1,
     "duration_ts": 1192359116,
     "codec_name": "bin_data",
     "tags": {
      "creation_time": "2022-02-03T14:11:19.000000Z",
      "handler_name": "\u0018Apple Text Media Handler",
      "language": "eng"
     },
     "duration": "54075.243356",
     "start_time": "0.000000",
     "disposition": {
      "dub": 0,
      "karaoke": 0,
      "default": 1,
      "original": 0,
      "visual_impaired": 0,
      "forced": 0,
      "attached_pic": 0,
      "timed_thumbnails": 0,
      "comment": 0,
      "hearing_impaired": 0,
      "lyrics": 0,
      "clean_effects": 0
     },
     "codec_tag": "0x74786574",
     "codec_tag_string": "text",
     "avg_frame_rate": "0/0",
     "nb_frames": "38",
     "codec_type": "data",
     "codec_long_name": "binary data"
    },
    {
     "color_range": "pc",
     "pix_fmt": "yuvj420p",
     "r_frame_rate": "90000/1",
     "start_pts": 0,
     "duration_ts": 4866771900,
     "duration": "54075.243333",
     "sample_aspect_ratio": "1:1",
     "codec_tag_string": "[0][0][0][0]",
     "avg_frame_rate": "0/0",
     "closed_captions": 0,
     "color_space": "bt470bg",
     "codec_long_name": "Motion JPEG",
     "height": 500,
     "chroma_location": "center",
     "time_base": "1/90000",
     "coded_height": 500,
     "level": -99,
     "profile": "Baseline",
     "bits_per_raw_sample": "8",
     "index": 2,
     "codec_name": "mjpeg",
     "start_time": "0.000000",
     "disposition": {
      "dub": 0,
      "karaoke": 0,
      "default": 0,
      "original": 0,
      "visual_impaired": 0,
      "forced": 0,
      "attached_pic": 1,
      "timed_thumbnails": 0,
      "comment": 0,
      "hearing_impaired": 0,
      "lyrics": 0,
      "clean_effects": 0
     },
     "codec_tag": "0x0000",
     "has_b_frames": 0,
     "refs": 1,
     "codec_time_base": "0/1",
     "width": 500,
     "display_aspect_ratio": "1:1",
     "coded_width": 500,
     "codec_type": "video"
    }
   ],
   "format": {
    "duration": "54075.243333",
    "start_time": "0.000000",
    "bit_rate": "64682",
    "filename": "/Volumes/Media/Plex Extra/OpenAudibleFiles/aax/The Bands of Mourning.1.AAX",
    "size": "437213571",
    "probe_score": 100,
    "nb_programs": 0,
    "format_long_name": "QuickTime / MOV",
    "nb_streams": 3,
    "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
    "tags": {
     "creation_time": "2022-02-03T14:08:47.000000Z",
     "date": "2016",
     "copyright": "©2016 Dragonsteel Entertainment LLC (P)2016 Macmillan Audio",
     "artist": "Brandon Sanderson",
     "album_artist": "Brandon Sanderson",
     "album": "The Bands of Mourning: A Mistborn Novel",
     "major_brand": "aax ",
     "genre": "Audiobook",
     "comment": "Chapter 38",
     "title": "The Bands of Mourning: A Mistborn Novel",
     "minor_version": "1",
     "compatible_brands": "aax M4B mp42isom"
    }
   }
  },
  {
   "file": "/Volumes/Media/Plex Extra/OpenAudibleFiles/art/The Bands of Mourning.1.jpg",
   "size": 38035,
   "chapters": [],
   "streams": [{
    "color_range": "pc",
    "pix_fmt": "yuvj420p",
    "r_frame_rate": "25/1",
    "start_pts": 0,
    "duration_ts": 1,
    "duration": "0.040000",
    "sample_aspect_ratio": "1:1",
    "codec_tag_string": "[0][0][0][0]",
    "avg_frame_rate": "0/0",
    "closed_captions": 0,
    "color_space": "bt470bg",
    "codec_long_name": "Motion JPEG",
    "height": 500,
    "chroma_location": "center",
    "time_base": "1/25",
    "coded_height": 500,
    "level": -99,
    "profile": "Baseline",
    "bits_per_raw_sample": "8",
    "index": 0,
    "codec_name": "mjpeg",
    "start_time": "0.000000",
    "disposition": {
     "dub": 0,
     "karaoke": 0,
     "default": 0,
     "original": 0,
     "visual_impaired": 0,
     "forced": 0,
     "attached_pic": 0,
     "timed_thumbnails": 0,
     "comment": 0,
     "hearing_impaired": 0,
     "lyrics": 0,
     "clean_effects": 0
    },
    "codec_tag": "0x0000",
    "has_b_frames": 0,
    "refs": 1,
    "codec_time_base": "0/1",
    "width": 500,
    "display_aspect_ratio": "1:1",
    "coded_width": 500,
    "codec_type": "video"
   }],
   "format": {
    "duration": "0.040000",
    "start_time": "0.000000",
    "bit_rate": "7607000",
    "filename": "/Volumes/Media/Plex Extra/OpenAudibleFiles/art/The Bands of Mourning.1.jpg",
    "size": "38035",
    "probe_score": 50,
    "nb_programs": 0,
    "format_long_name": "image2 sequence",
    "nb_streams": 1,
    "format_name": "image2"
   }
  },
  {
   "file": "/Volumes/Media/Plex Extra/OpenAudibleFiles/books/The Bands of Mourning.1.m4b",
   "size": 429155746,
   "chapters": [
    {
     "start_time": "0.000000",
     "time_base": "1/1000",
     "start": 0,
     "end_time": "2762.292000",
     "end": 2762292,
     "id": 0,
     "tags": {"title": "Chapter 1"}
    },
    {
     "start_time": "2762.292000",
     "time_base": "1/1000",
     "start": 2762292,
     "end_time": "4161.387000",
     "end": 4161387,
     "id": 1,
     "tags": {"title": "Chapter 2"}
    },
    {
     "start_time": "4161.387000",
     "time_base": "1/1000",
     "start": 4161387,
     "end_time": "5234.567000",
     "end": 5234567,
     "id": 2,
     "tags": {"title": "Chapter 3"}
    },
    {
     "start_time": "5234.567000",
     "time_base": "1/1000",
     "start": 5234567,
     "end_time": "7545.464000",
     "end": 7545464,
     "id": 3,
     "tags": {"title": "Chapter 4"}
    },
    {
     "start_time": "7545.464000",
     "time_base": "1/1000",
     "start": 7545464,
     "end_time": "9757.396000",
     "end": 9757396,
     "id": 4,
     "tags": {"title": "Chapter 5"}
    },
    {
     "start_time": "9757.396000",
     "time_base": "1/1000",
     "start": 9757396,
     "end_time": "11506.370000",
     "end": 11506370,
     "id": 5,
     "tags": {"title": "Chapter 6"}
    },
    {
     "start_time": "11506.370000",
     "time_base": "1/1000",
     "start": 11506370,
     "end_time": "12595.339000",
     "end": 12595339,
     "id": 6,
     "tags": {"title": "Chapter 7"}
    },
    {
     "start_time": "12595.339000",
     "time_base": "1/1000",
     "start": 12595339,
     "end_time": "14489.345000",
     "end": 14489345,
     "id": 7,
     "tags": {"title": "Chapter 8"}
    },
    {
     "start_time": "14489.345000",
     "time_base": "1/1000",
     "start": 14489345,
     "end_time": "15342.585000",
     "end": 15342585,
     "id": 8,
     "tags": {"title": "Chapter 9"}
    },
    {
     "start_time": "15342.585000",
     "time_base": "1/1000",
     "start": 15342585,
     "end_time": "16735.364000",
     "end": 16735364,
     "id": 9,
     "tags": {"title": "Chapter 10"}
    },
    {
     "start_time": "16735.364000",
     "time_base": "1/1000",
     "start": 16735364,
     "end_time": "18336.659000",
     "end": 18336659,
     "id": 10,
     "tags": {"title": "Chapter 11"}
    },
    {
     "start_time": "18336.659000",
     "time_base": "1/1000",
     "start": 18336659,
     "end_time": "19760.321000",
     "end": 19760321,
     "id": 11,
     "tags": {"title": "Chapter 12"}
    },
    {
     "start_time": "19760.321000",
     "time_base": "1/1000",
     "start": 19760321,
     "end_time": "22389.377000",
     "end": 22389377,
     "id": 12,
     "tags": {"title": "Chapter 13"}
    },
    {
     "start_time": "22389.377000",
     "time_base": "1/1000",
     "start": 22389377,
     "end_time": "23694.524000",
     "end": 23694524,
     "id": 13,
     "tags": {"title": "Chapter 14"}
    },
    {
     "start_time": "23694.524000",
     "time_base": "1/1000",
     "start": 23694524,
     "end_time": "25151.808000",
     "end": 25151808,
     "id": 14,
     "tags": {"title": "Chapter 15"}
    },
    {
     "start_time": "25151.808000",
     "time_base": "1/1000",
     "start": 25151808,
     "end_time": "26260.654000",
     "end": 26260654,
     "id": 15,
     "tags": {"title": "Chapter 16"}
    },
    {
     "start_time": "26260.654000",
     "time_base": "1/1000",
     "start": 26260654,
     "end_time": "27850.664000",
     "end": 27850664,
     "id": 16,
     "tags": {"title": "Chapter 17"}
    },
    {
     "start_time": "27850.664000",
     "time_base": "1/1000",
     "start": 27850664,
     "end_time": "30649.922000",
     "end": 30649922,
     "id": 17,
     "tags": {"title": "Chapter 18"}
    },
    {
     "start_time": "30649.922000",
     "time_base": "1/1000",
     "start": 30649922,
     "end_time": "32181.046000",
     "end": 32181046,
     "id": 18,
     "tags": {"title": "Chapter 19"}
    },
    {
     "start_time": "32181.046000",
     "time_base": "1/1000",
     "start": 32181046,
     "end_time": "33922.357000",
     "end": 33922357,
     "id": 19,
     "tags": {"title": "Chapter 20"}
    },
    {
     "start_time": "33922.357000",
     "time_base": "1/1000",
     "start": 33922357,
     "end_time": "36146.921000",
     "end": 36146921,
     "id": 20,
     "tags": {"title": "Chapter 21"}
    },
    {
     "start_time": "36146.921000",
     "time_base": "1/1000",
     "start": 36146921,
     "end_time": "38390.526000",
     "end": 38390526,
     "id": 21,
     "tags": {"title": "Chapter 22"}
    },
    {
     "start_time": "38390.526000",
     "time_base": "1/1000",
     "start": 38390526,
     "end_time": "39534.852000",
     "end": 39534852,
     "id": 22,
     "tags": {"title": "Chapter 23"}
    },
    {
     "start_time": "39534.852000",
     "time_base": "1/1000",
     "start": 39534852,
     "end_time": "41235.064000",
     "end": 41235064,
     "id": 23,
     "tags": {"title": "Chapter 24"}
    },
    {
     "start_time": "41235.064000",
     "time_base": "1/1000",
     "start": 41235064,
     "end_time": "42571.558000",
     "end": 42571558,
     "id": 24,
     "tags": {"title": "Chapter 25"}
    },
    {
     "start_time": "42571.558000",
     "time_base": "1/1000",
     "start": 42571558,
     "end_time": "43584.691000",
     "end": 43584691,
     "id": 25,
     "tags": {"title": "Chapter 26"}
    },
    {
     "start_time": "43584.691000",
     "time_base": "1/1000",
     "start": 43584691,
     "end_time": "44336.414000",
     "end": 44336414,
     "id": 26,
     "tags": {"title": "Chapter 27"}
    },
    {
     "start_time": "44336.414000",
     "time_base": "1/1000",
     "start": 44336414,
     "end_time": "45683.542000",
     "end": 45683542,
     "id": 27,
     "tags": {"title": "Chapter 28"}
    },
    {
     "start_time": "45683.542000",
     "time_base": "1/1000",
     "start": 45683542,
     "end_time": "47058.164000",
     "end": 47058164,
     "id": 28,
     "tags": {"title": "Chapter 29"}
    },
    {
     "start_time": "47058.164000",
     "time_base": "1/1000",
     "start": 47058164,
     "end_time": "48786.239000",
     "end": 48786239,
     "id": 29,
     "tags": {"title": "Chapter 30"}
    },
    {
     "start_time": "48786.239000",
     "time_base": "1/1000",
     "start": 48786239,
     "end_time": "49787.902000",
     "end": 49787902,
     "id": 30,
     "tags": {"title": "Chapter 31"}
    },
    {
     "start_time": "49787.902000",
     "time_base": "1/1000",
     "start": 49787902,
     "end_time": "51098.157000",
     "end": 51098157,
     "id": 31,
     "tags": {"title": "Chapter 32"}
    },
    {
     "start_time": "51098.157000",
     "time_base": "1/1000",
     "start": 51098157,
     "end_time": "51857.728000",
     "end": 51857728,
     "id": 32,
     "tags": {"title": "Chapter 33"}
    },
    {
     "start_time": "51857.728000",
     "time_base": "1/1000",
     "start": 51857728,
     "end_time": "51908.301000",
     "end": 51908301,
     "id": 33,
     "tags": {"title": "Chapter 34"}
    },
    {
     "start_time": "51908.301000",
     "time_base": "1/1000",
     "start": 51908301,
     "end_time": "52542.578000",
     "end": 52542578,
     "id": 34,
     "tags": {"title": "Chapter 35"}
    },
    {
     "start_time": "52542.578000",
     "time_base": "1/1000",
     "start": 52542578,
     "end_time": "52788.802000",
     "end": 52788802,
     "id": 35,
     "tags": {"title": "Chapter 36"}
    },
    {
     "start_time": "52788.802000",
     "time_base": "1/1000",
     "start": 52788802,
     "end_time": "52894.081000",
     "end": 52894081,
     "id": 36,
     "tags": {"title": "Chapter 37"}
    },
    {
     "start_time": "52894.081000",
     "time_base": "1/1000",
     "start": 52894081,
     "end_time": "54075.243000",
     "end": 54075243,
     "id": 37,
     "tags": {"title": "Chapter 38"}
    }
   ],
   "streams": [
    {
     "r_frame_rate": "0/0",
     "start_pts": 0,
     "channel_layout": "stereo",
     "duration_ts": 1192359116,
     "duration": "54075.243356",
     "bit_rate": "62794",
     "codec_tag_string": "mp4a",
     "avg_frame_rate": "0/0",
     "nb_frames": "1164414",
     "codec_long_name": "AAC (Advanced Audio Coding)",
     "time_base": "1/22050",
     "profile": "LC",
     "index": 0,
     "max_bit_rate": "62794",
     "codec_name": "aac",
     "tags": {
      "creation_time": "2022-02-03T14:08:47.000000Z",
      "handler_name": "\u0019Apple Sound Media Handler",
      "language": "eng"
     },
     "start_time": "0.000000",
     "disposition": {
      "dub": 0,
      "karaoke": 0,
      "default": 1,
      "original": 0,
      "visual_impaired": 0,
      "forced": 0,
      "attached_pic": 0,
      "timed_thumbnails": 0,
      "comment": 0,
      "hearing_impaired": 0,
      "lyrics": 0,
      "clean_effects": 0
     },
     "codec_tag": "0x6134706d",
     "sample_rate": "22050",
     "channels": 2,
     "sample_fmt": "fltp",
     "codec_time_base": "1/22050",
     "bits_per_sample": 0,
     "codec_type": "audio"
    },
    {
     "time_base": "1/1000",
     "r_frame_rate": "0/0",
     "start_pts": 0,
     "index": 1,
     "duration_ts": 54075243,
     "codec_name": "bin_data",
     "tags": {
      "creation_time": "2022-02-03T14:08:47.000000Z",
      "handler_name": "SubtitleHandler",
      "language": "eng"
     },
     "duration": "54075.243000",
     "start_time": "0.000000",
     "disposition": {
      "dub": 0,
      "karaoke": 0,
      "default": 0,
      "original": 0,
      "visual_impaired": 0,
      "forced": 0,
      "attached_pic": 0,
      "timed_thumbnails": 0,
      "comment": 0,
      "hearing_impaired": 0,
      "lyrics": 0,
      "clean_effects": 0
     },
     "codec_tag": "0x74786574",
     "codec_tag_string": "text",
     "avg_frame_rate": "0/0",
     "nb_frames": "38",
     "codec_type": "data",
     "codec_long_name": "binary data"
    },
    {
     "color_range": "pc",
     "pix_fmt": "yuvj420p",
     "r_frame_rate": "90000/1",
     "start_pts": 0,
     "duration_ts": 4866771960,
     "duration": "54075.244000",
     "sample_aspect_ratio": "1:1",
     "codec_tag_string": "[0][0][0][0]",
     "avg_frame_rate": "0/0",
     "closed_captions": 0,
     "color_space": "bt470bg",
     "codec_long_name": "Motion JPEG",
     "height": 500,
     "chroma_location": "center",
     "time_base": "1/90000",
     "coded_height": 500,
     "level": -99,
     "profile": "Baseline",
     "bits_per_raw_sample": "8",
     "index": 2,
     "codec_name": "mjpeg",
     "start_time": "0.000000",
     "disposition": {
      "dub": 0,
      "karaoke": 0,
      "default": 0,
      "original": 0,
      "visual_impaired": 0,
      "forced": 0,
      "attached_pic": 1,
      "timed_thumbnails": 0,
      "comment": 0,
      "hearing_impaired": 0,
      "lyrics": 0,
      "clean_effects": 0
     },
     "codec_tag": "0x0000",
     "has_b_frames": 0,
     "refs": 1,
     "codec_time_base": "0/1",
     "width": 500,
     "display_aspect_ratio": "1:1",
     "coded_width": 500,
     "codec_type": "video"
    }
   ],
   "format": {
    "duration": "54075.244000",
    "start_time": "0.000000",
    "bit_rate": "63490",
    "filename": "/Volumes/Media/Plex Extra/OpenAudibleFiles/books/The Bands of Mourning.1.m4b",
    "size": "429155746",
    "probe_score": 100,
    "nb_programs": 0,
    "format_long_name": "QuickTime / MOV",
    "nb_streams": 3,
    "format_name": "mov,mp4,m4a,3gp,3g2,mj2",
    "tags": {
     "creation_time": "2022-02-03T14:08:47.000000Z",
     "date": "2016",
     "copyright": "©2016 Dragonsteel Entertainment LLC (P)2016 Macmillan Audio",
     "artist": "Brandon Sanderson",
     "album": "The Bands of Mourning: A Mistborn Novel",
     "major_brand": "M4A ",
     "title": "The Bands of Mourning: A Mistborn Novel",
     "minor_version": "512",
     "album_artist": "Brandon Sanderson",
     "genre": "Audiobook",
     "comment": "Chapter 38",
     "track": "1",
     "compatible_brands": "M4A isomiso2"
    }
   }
  }
 ],
 "purchase_date": "2022-02-04"
}

**Comment by openaudible** [comment]
I need more details. In the example above, which chapter is wrong, what is it supposed to be, and what is it in the split file?
In the original book, there are two sources of chapter data-- inside the aax, and from audible. The data from audible is what we usually use, since it contains chapter names. It may be different than the aax meta data.

For splitting, we usually disregard the chapter data-- as we are only getting one chapter of info. The only thing we care about is the title (which we sometimes modify to make alphabetical) and the start time and duration.

**Comment by feldegast** [comment]
in the above example chapters 2,3,4,6,7,9,11,12,14,15,18,19,20,22,23,25,26,28,29,,30,32,34,35 and 37 are incorrect out of 38 chapters all these have incorrect title and track number data

**Comment by openaudible** [comment]
Dah!
Thank you. In process of fixing. Will post update ASAP.

**Comment by feldegast** [comment]
all good :) 
looking at the above data, the data written is always from a chapter greater than what it should be, if that helps
I'm not in a hurry I'm about to sleep :)

**Comment by openaudible** [comment]
Fixed in 3.4.3
Thanks for your help!
