### ISSUE TITLE
[Request] Automatically update OpenAudible version

### ISSUE THREAD

**Issue by Weldawadyathink** [openaudible/openaudible#867]
Would it be possible to implement auto-updating OpenAudible version? This would be extremely helpful for a hands-off installation made possible by [auto refresh audiobooks.](https://github.com/openaudible/openaudible/issues/805)

Thank you in advance.

**Comment by openaudible** [comment]
Do you mean automatically upgrade openaudible to the latest version? That isn't really easy-- but we do check periodically for a new version. And you can "watch" this to be notified of new releases by email.

You could write a script to do this, although it isn't trivial. The idea is you query the version from https://openaudible.org/downloads/swt_version.json (using jq to parse the json) and if you detect a new version, download the installer, quit the old version, and run the installer in quiet & overwrite mode: -q -overwrite  then relaunch the app.

We won't add this as a feature as after a year of updates, the license needs to be updated and we want to give lots of heads up via the new version available message.

Thanks for the idea.
