### ISSUE TITLE
java download resume support should be possible

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#868]
resuming downloads is an important feature needed especially for areas with unreliable and slow internet connections

I am able to use wget -c to resume the downloads from amazon so I know the server supports file resuming

here is example code that should allow a file download to resume in java...

https://coderanch.com/t/530480/java/Download-files-resume-support
I know you have said previously that you can't do this but I am unsure as to why this is the case given java and amazon servers both allow it.....

**Comment by feldegast** [comment]
if you want someone to test some practice code I can do it if it works on an intel mac, compiled, as I removed my code due to low space :-/

**Comment by openaudible** [comment]
Its usually a testing thing and making sure there aren't unintended consequences. 
Made a beta that attempts to retry and resume downloading. If you cancel 50% through, the partial book will stay in the temp directory for 24 hours.. then be deleted. Re-downloading before then should start where it left off.

**Comment by feldegast** [comment]
trying it now

**Comment by openaudible** [comment]
I’ll need to see the logs. You can also review them as I added extra logging for errors and retry. It may not be clear that a resume is being done from the regular gui as I don’t jump to 50% but just report the remaining bytes from 0 to 100 percent complete. (But will fix that.

One thing to do is recreate both bugs. delete an aax book, restart OA to clear logs, then recreate aax bug and download Resume issue. Then send a bug report from help menu. 

Or email download logs to me by copy and paste. Don’t post them here or your books might get downloaded. 

Lastly if you get more than 5 errors, you should still see that book download as a .part file in the tmp directory and manually Re downloading that book should resume from there. 

Will add more logging and improve ui on next iteration.

**Comment by feldegast** [comment]
which logs would you like? everything in the tmp directory??

**Comment by feldegast** [comment]
ok yeah in the GUI it looks like you just restart (go back to 0%) but I can see the .part file gets bigger and doesn't restart so it might be all good there, the importing of AAX files issue is still an issue I will send logs

**Comment by openaudible** [comment]
Fixed the GUI in the latest beta. I think will close as having been solved.
