### ISSUE TITLE
Issue with downloading files with umlauten

### ISSUE THREAD

**Issue by masterdot** [openaudible/openaudible#870]
I have some audiobooks unable to download. 
They all contain Umlaute, Screenshots are attached.

![Screenshot 2022-02-13 20 56 35](https://user-images.githubusercontent.com/493105/153772486-7356e820-1b43-496f-b4c7-3a4e33e6975a.png)
![Screenshot 2022-02-13 20 56 29](https://user-images.githubusercontent.com/493105/153772487-3209a4f3-b548-4f3e-b165-6befd04ac09f.png)
![Screenshot 2022-02-13 20 56 20](https://user-images.githubusercontent.com/493105/153772488-fc6ca732-8194-48b3-b5b9-0ae15cb9c8ed.png)

**Comment by openaudible** [comment]
Can you quit and restart OpenAudible, download one file, and when you get the error, send a bug report from the About menu and reference issue #870.  I'll be able to see the full error log and should be able to get a quick fix to you.

**Comment by masterdot** [comment]
Did that, thanks for your assistance!

**Comment by masterdot** [comment]
... you did then forget it in your docker image :) 

But that did explain why I didnt have the problem before :) 

![Screenshot 2022-02-13 22 40 17](https://user-images.githubusercontent.com/493105/153776269-7271871c-d957-4691-a78e-303ec560a6e6.png)

**Comment by openaudible** [comment]
Ok. I got the line of code it fails on, which is renaming a file from the downloaded .part file to the full name. Its possible I can just trap on that error and manually copy the file and delete the old one.. which we do on some errors but not your error. So will have a beta to try shortly. But real solution may still be to set the LANG properly. 


So you're saying the docker image is not set correctly? Are you able to set the locale?

**Comment by masterdot** [comment]
Hmm... I did set the locale now, but it still doesnt work..
As I said, Im using the docker... Thanks for your time :)

**Comment by openaudible** [comment]
Was able to reproduce and fix. You'll need to stop, remove, and pull the new version.
https://github.com/openaudible/openaudible_docker
Pushing to dockerhub now.

**Comment by masterdot** [comment]
It does work now, Thanks for your time!
