### ISSUE TITLE
Library status window values are not always updated correctly

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#871]
ver: 3.4.3.1beta
Library status window values for To Download and Downloading are not always updated when a book changes status from downloading to error (red) or from error (red) to in the download queue
selecting books in the download queue and canceling job on them also doesn't move them from Downloading to To download in the library status window
might be with checking To Convert and the other values.....

I know i's not critical but noticed it while testing

**Comment by openaudible** [comment]
I’ll look at that a little. Thanks.

**Comment by openaudible** [comment]
Feel free to try the beta! Made some updates for the redraw caching.
https://openaudible.org/beta

:)

**Comment by openaudible** [comment]
Made a change in beta 3 https://openaudible.org/beta
Please reopen if not fixed.
