### ISSUE TITLE
'Automatically download books' should auto retry failed downloads

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#872]
if 'Automatically download books' is enabled, in the event a download fails (gets a red circle) the failed download should automatically be re-added to the download queue, and its status should also be changed to 'in download queue'

**Comment by openaudible** [comment]
Most often when a download error occurs it is because the link is no longer valid. Retrying repeatedly is not a great strategy.
I'd like to keep some human interaction going. Quitting and restarting the app, or select all and download should suffice.

But appreciate the suggestion.

**Comment by feldegast** [comment]
i was thinking for poor connections but I get your point

**Comment by openaudible** [comment]
There is a hidden field in settings.json that lets you download books 1 at a time.. versus the 3 at a time default. Something like: concurrent_file_downloads.
