### ISSUE TITLE
Crashes during conversion to MP3 files

### ISSUE THREAD

**Issue by ttffm** [openaudible/openaudible#873]
When converting long audio books to MP3 my PC becomes very slow and eventually crashes. It always happens with audio books over 38 hours long. It looks like the program is uses up all the available memory. Please fix this issue, or allow Open Audible to divide up books into large chunks to save on resources.

**Comment by openaudible** [comment]
Oh, shoot. OK. For now, edit settings.json file and set concurrentConversionsto a lower number:
Go to preferences, click on folder icon next to preferences directory:
Find settings.properties and open with text editor. Change concurrentConversions from 6 or whatever it is to 3 (or 2)
Save and restart OpenAudible and that should fix it.

**Comment by ttffm** [comment]
It was already set to 3 but I changed it to 1. The book is over 52 hours. During conversion it slows at about 38 hour point and crashes at about 46 hours. My system memory can't hold more than that.

**Comment by openaudible** [comment]
CAn you copy and paste the error from the console window? The app does the conversion with a program called ffmpeg. Is that what crashes or is it the app itself? How much ram do you have? Assume windows?

**Comment by ttffm** [comment]
I'm running a Debian based OS on my laptop with 4Gb of memory. I have had this same issue with both Linux and Windows on the same hardware. Unfortunately I can't show an error. The machine just freezes and nothing else happens.

**Comment by openaudible** [comment]
I might be able to reproduce with virtualbox/vmware. Is there an ISO for your linux you can point to?

OA prints the command line which you might be able to run from the terminal to see if it is ffmpeg or OA. 

You might also try converting to m4b... which should be a lot easier on CPU/memory.. That might narrow it down as well.

**Comment by ttffm** [comment]
I'm currently running Xubuntu 20.04.1 but I had also have Windows 10 on another machine as well. I'll check into M4b to see if that does anything. Thank you.

**Comment by openaudible** [comment]
I try not to get too bogged down on all the different flavors of linux and system attributes. Can't support everything. But will attempt to reproduce.

A few things to consider: 
- monitor cpu and memory using `top` when converting
- add a swap file

**Comment by ttffm** [comment]
I'll give that a try as well.

**Comment by openaudible** [comment]
I wasn't able to install xubuntu. Unable to reproduce. Feel free to run with the console open and if anything gets printed before it crashes, that might be helpful as well.

**Comment by openaudible** [comment]
Unable to reproduce. Was able to convert multiple 50+ hour an books simultaneously on a Ubuntu with 2GB RAM. Keep an eye on your available memory (using top).. Might be a system problem (bad ram, etc.).

Feel free to re-open this if you get a usable error message.
