### ISSUE TITLE
state: Downloading XXX.XXMb XX.X% @ XXKb/sec the kb/sec value sometimes has very long decimals

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#876]
Ver 3.4.3.2 beta
XXKb/sec can sometimes have a vert long decimal fraction, might be a good idea to round to 2 decimals or something similar, I notice this when 1st switching to a download from another more than just staying on one download

this style download status looks good other than this small issue :)

**Comment by openaudible** [comment]
Thanks.

**Comment by openaudible** [comment]
The rate should be limited to a 6 digit number 1.3456Mb or 1234.6 for some numbers.  
If you see something like 1.333333333 that would be a bug, but I didn't find how that can happen.

**Comment by feldegast** [comment]
it was for the download rate, i was thinking it was due to the division not being rounded properly and it was only for 1sec or so before it was auto-updated when 1st switching to a downloading book
