### ISSUE TITLE
quickly clicking on downloading books and the clicking on a book that is not downloading can result in old data still showing

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#878]
ver 3.4.3.3beta
clicking on downloading books say 3 of them one after the other quickly and then clicking on a book that is not downloading can result in old data still showing for the state: field, it keeps the "downloading........" text from the previously selected book instead of changing to "in download queue" etc

**Comment by feldegast** [comment]
using down arrow keys (probably works with up arrow key too) to change the selected book is the easiest way to get the bug to show but it only happens sometimes
moving down past 2 downloading books to a book that is not downloading shows the issues sometimes for me
not updating when a book is selected and showing old data instead

**Comment by openaudible** [comment]
Feel free to try the beta! Made some updates for the redraw caching.
https://openaudible.org/beta

**Comment by openaudible** [comment]
Made a change in beta 3 https://openaudible.org/beta
Please reopen if not fixed.
