### ISSUE TITLE
adding books to the download queue doesn't always update the To Download stat

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#879]
Ver 3.5
again not a critical bug just a display/clarification issue

When adding books to the download queue the To download stat doesn't always update (reduce by 1)

I often have OA set to show Downloading books, to show items that are in my download queue

When a book stops downloading due to a connection issue or other issue the count of "To download" is incremented, the book's entry in Downloading changes to red but the book remains in Downloading list (this is fine though a little inaccurate)

if I then select that book and re-add it to the download queue (without changing the view of shown audiobooks) the book is re-added to the download queue but the To download value is not updated

if I change my view to show all books in To Download list at this point, the book is in still in the To download list but has a Downloading icon indicating it is in the download queue rather than in To Download books

**Comment by openaudible** [comment]
We're trying to limit how frequently we go through the full list of books to update stats, as it can be a little bit expensive CPU wise, especially when checking whether files are on the disk. I've added a little code to update the stats a little more frequently. Will be in the next beta. No ETA..

**Comment by feldegast** [comment]
all good, it was unclear it was a known issue :)

**Comment by openaudible** [comment]
Feel free to try the beta! Made some updates for the redraw caching.
https://openaudible.org/beta

**Comment by openaudible** [comment]
Made a change in beta 3 https://openaudible.org/beta
Please reopen if not fixed.
