### ISSUE TITLE
Can not download books from https://www.audible.co.jp/ #880

### ISSUE THREAD

**Issue by HiroshiTsu** [openaudible/openaudible#881]
Can not download books from https://www.audible.co.jp/ #880

**Comment by feldegast** [comment]
you need to send a bug report so they can check logs etc, while running app goto the menu option 'Send bug report' it's in my About menu but it might be elsewhere on windows...

**Comment by openaudible** [comment]
Yes. Send report after trying to download. Will report back on #880
