### ISSUE TITLE
Tab text hard to read on edit book window in dark mode

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#883]
UI color issue for tabs on edit book window

when using dark mode the tabs on the edit book window has hard to read tab text

it looks like it uses white text on a light grey background for all tabs other than the current one
the currently visible tab uses white text with a slightly darker gray background when the window is not active, if the window is active the background of the tab is blue which is fine

the colors in light mode looks good

**Comment by openaudible** [comment]
For some reason the tabs don’t change color on windows. A windows bug. ?!

https://bugs.eclipse.org/bugs/show_bug.cgi?id=162855
