### ISSUE TITLE
tab background colour on osx bug 883

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#884]
this is on Mac with dark mode, not windows.....
it's probably an issue with the control itself?
if I knew the control name I might be able to troubleshoot....
I'm not a java developer...

**Comment by openaudible** [comment]
Eclipse swt tabitem. There is no setForeground/setBackround color calls. Not sure why. 
You can reopen an issue or respond on the previous topic.

**Comment by openaudible** [comment]
Made a change in beta 3 https://openaudible.org/beta
Please reopen if not fixed.
