### ISSUE TITLE
Window not using dark mode on Mac OS : Audible Library Scan

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#885]
OA version 3.5.0.1Beta 
Colour scheme selected : dark
Installed OS : Mac OS Catalina 10.15.7 (dark mode selected)

Audible Library Scan window/dialogue uses the light color scheme when the dark color scheme is selected in the app's preferences
so does the canceled dialogue if you cancel the scan and the loading dialogue when you start OA

**Comment by openaudible** [comment]
I assume that is the progress dialog throughout the app. Can fix.

**Comment by feldegast** [comment]
here is an article on setting dark mode in an app for java, is it relevant? as there are a number of other controls that don't use dark mode styling....the main list control (the one listing the books) title/headding and scroll bars......
https://stackoverflow.com/questions/55217540/how-to-get-macos-mojave-style-dark-mode-in-java-in-a-swing-application

**Comment by openaudible** [comment]
There are 3 gui options for Java- swing, eclipse swt and javafx. We use swt. Anything with swing or javafx (or also electron) do not apply. 

Just looked and there may be a solution by using a similar thing. Will give it another look. 

https://help.eclipse.org/latest/index.jsp?topic=/org.eclipse.platform.doc.isv/reference/api/org/eclipse/swt/custom/CTabFolder.html

**Comment by feldegast** [comment]
the only java app i use a lot is BiglyBT it has a dark mode option (at least on MacOS) wish could be more help

**Comment by openaudible** [comment]
No problem. Found a fix. Will post a new beta soon. WW3 starting tho.

**Comment by openaudible** [comment]
Made a change in beta 3 https://openaudible.org/beta
Please reopen if not fixed.
