### ISSUE TITLE
Periodic refresh feature blocks itself from refreshing.

### ISSUE THREAD

**Issue by Weldawadyathink** [openaudible/openaudible#886]
Thanks again for adding the auto refresh feature to OpenAudible. 

There appears to be an issue with this feature as implemented. When the library is refreshed, OpenAudible creates an alert dialog "Your library is up to date!". This prevents OpenAudible from refreshing the library again until this dialog is dismissed. Therefore, when I purchase a new book on audible, I have to remote into my server and dismiss the dialog for OpenAudible to download the new book. This (almost) negates the point of the feature. 

I propose 2 options to address this. Add a config option to disable this popup box entirely on all library refreshes (The same info appears in the Summary section anyway). Or make it so that refreshes created by the timer skip the dialog box.

Thanks in advance, and thanks for creating such a wonderful and easy to use program!

**Comment by openaudible** [comment]
Oh good catch. Never tested that feature. Will remove alert.

**Comment by openaudible** [comment]
Made a change in beta 3 https://openaudible.org/beta
Please reopen if not fixed.

**Comment by Weldawadyathink** [comment]
Pop up is gone in the beta! It appears to refresh as requested. I will assume it is fixed for now, but I’ll check again next time I buy a book. Thanks!
