### ISSUE TITLE
Apply dark mode to whole application

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#887]
OA 3.5.0.3beta
MacOS Catalina

i notice that the application window, the list control and a few other items are not using dark mode
maybe it needs https://stackoverflow.com/questions/55217540/how-to-get-macos-mojave-style-dark-mode-in-java-in-a-swing-application ?
just a thought
the top of the application window is still light mode (on windows this would not be visible but it is clear on OSX) see screenshot
the title bar of the control showing the list of audiobooks is also light mode
![Screenshot 2022-02-23 at 09 19 52](https://user-images.githubusercontent.com/1029921/155236490-7d88abb3-bf02-4b92-bede-b4cf3dc9b3b7.jpg)

**Comment by openaudible** [comment]
Inside the OpenAudible.app directory there should be a debug_mac.sh file that you should be able to examine to show how to call the java application with additional command line arguments. You'd do this from the terminal.

```
cd to /Applications/OpenAudible.app/Contents/Resources/app
cat debug_mac.sh
```
Looks like adding -Dorg.eclipse.swt.display.useSytemTheme=true to the command might make the "system" theme work.

Will try in next release.

**Comment by feldegast** [comment]
yeah...having the dark theme controlled through the system wide setting instead of an option in the app may be better on Mac OS
that being said the mac dark theme can change while the app is running so it may also need to switch dynamically....

**Comment by feldegast** [comment]
adding -Dorg.eclipse.swt.display.useSytemTheme=true to the command disabled
the "system" theme (set it to light theme)
except for the Summery box which was black
the command I used.....

OpenAudible.app/Contents/MacOS/JavaApplicationStub
-Dorg.eclipse.swt.display.useSytemTheme=False

**Comment by openaudible** [comment]
Looks like you got it right.
From there, set OA to use "System" theme, and set your Mac to Use Dark. OA should be dark as well. 
Restarting OA may be needed after going from "dark" to system.

**Comment by feldegast** [comment]
my mac has been in dark mode theme for months, only allowing system theme on mac I think is what most apps do rather than letting users select it
setting the following doesn't use dark theme, it looks like it overrides the app setting of dark and uses the light theme
OpenAudible.app/Contents/MacOS/JavaApplicationStub -Dorg.eclipse.swt.display.useSytemTheme=True

**Comment by openaudible** [comment]
Ok. We don't use swing, so any java swing dark theme does not apply. Hope to have a beta tomorrow. Working on snapcraft installer as well, so keeping busy.

**Comment by feldegast** [comment]
that link was just to get you the system variable for mac dark mode...

**Comment by openaudible** [comment]
The book summary panel is the only thing we really need to check the status of dark mode for if using the system. 
Its HTML and if we're in dark mode, we change the css to show white text on black.
Did a quick test on the latest beta and it seems OK. I do see an annoying white flash when it re-draws the summary.
Checking a little more...

**Comment by feldegast** [comment]
i had net issues so was offline for almost a day, will check latest beta

**Comment by feldegast** [comment]
i couldn't duplicate on intel mac....system had no effect for me, it kist set it to light even though my system is set to dark mode

**Comment by feldegast** [comment]
Ah, i have an intel mac running Catalina

**Comment by openaudible** [comment]
The system dark should be working. I tested on the mac from the debugger, but the fix didn't get into the installer correctly. 

Should be fixed in the beta 5, https://openaudible.org/beta  (flashing summary text and pure black background is a known issue.) 

This beta removes the internal web browser... which has been a huge pain to maintain on all platforms. Please re-open or comment if you want..)

**Comment by feldegast** [comment]
3.5.0.5beta
setting the theme to 'system' does not detect dark mode on MacOS Catalina, it just always uses the light theme
setting the theme to 'dark' doesn't change the application title bars to dark
as a side note, I never needed the browser so it's removal actually makes the app look nicer
the only need for the drowser for me was to log in.....
