### ISSUE TITLE
I can not download.

### ISSUE THREAD

**Issue by hidetok0520** [openaudible/openaudible#889]
State:Error Downloading "All you can consume books can't be downloaded at this time"
The display will appear.
It will not be available for download from mid-February.
It is a Japanese audible.

**Comment by openaudible** [comment]
Japan version has a bug, please use the beta. 
https://openaudible.org/beta

**Comment by hidetok0520** [comment]
I was able to download it.
Thank you very much for your prompt response.

**Comment by openaudible** [comment]
3.5.1 should fix this permanently.
