### ISSUE TITLE
Peridicals titles not scraped correctly

### ISSUE THREAD

**Issue by aljex** [openaudible/openaudible#89]
The first 9 lines of thisdisplay are all periodicals:
![openaudible_periodical_scrape](https://user-images.githubusercontent.com/455568/52174333-0eca6680-2760-11e9-91e0-cc93821fed48.png)

All 4 of the Story Pod periodicals displayed in library, collapsed:
![periodical-collapsed](https://user-images.githubusercontent.com/455568/52174466-feb38680-2761-11e9-8673-236938ed2498.png)

Story Pod 2.0 - expanded:
![periodical-expanded](https://user-images.githubusercontent.com/455568/52174469-0ffc9300-2762-11e9-8ab1-77cd167f4e8a.png)

**Comment by aljex** [comment]
When I manually expand the periodical and download each item, they download, import, and convert fine. The individual issues (at least whichever ones I manually downloaded) are listed correctly in OpenAudible as well as the bogus entry for the whole periodical.

I can right-click and "ignore book" on the bogus periodical titles, and it works. The individual downloads remain, the periodical name entry goes away.

**Comment by aljex** [comment]
I had "Automatically Update Web Page" selected. I unselected that, closed & reopened openaudible, still does the same thing.

**Comment by openaudible** [comment]
Unusual case.. Never seen a buy one get 12 books.. Will look at it.

**Comment by milegrin** [comment]
I have found the same with the Harvard Business School books and periodicals.  As a work-around, manually clicking the download starts the download as stated above.  Not a major problem once I figured out to get it working.

**Comment by openaudible** [comment]
Good to hear the manual download works. Closing for now.
