### ISSUE TITLE
I cannot Download, message: ""Error downloading: All you can consume books can't be downloaded at this time"

### ISSUE THREAD

**Issue by GBGHub** [openaudible/openaudible#890]
Version 3.5, from the console:
====================================================
mar 01, 2022 11:27:48 AM org.openaudible.desktop.swt.manager.menu.CommandCenter execute
INFORMAZIONI: Command: Download
mar 01, 2022 11:27:48 AM org.openaudible.desktop.swt.manager.AudibleGUI downloadAAX
INFORMAZIONI: Added 1 of 1
mar 01, 2022 11:27:48 AM org.openaudible.util.queues.ThreadedQueue run
INFORMAZIONI: Starting job Download Cibola Burn - La cura DownloadQueue size:1 remain:0 success:0 fail:65 threads:1
mar 01, 2022 11:27:48 AM org.openaudible.Audible jobStarted
INFORMAZIONI: DownloadQueue started:Cibola Burn - La cura DownloadQueue size:1 remain:0 success:0 fail:65 threads:1
mar 01, 2022 11:27:48 AM org.openaudible.util.queues.ThreadedQueue jobError
INFORMAZIONI: DownloadQueue error processing Download Cibola Burn - La cura item Cibola Burn - La cura
java.lang.Exception: All you can consume books can't be downloaded at this time.
	at org.openaudible.download.DownloadAAXJob.downloadAlt(DownloadAAXJob.java:196)
	at org.openaudible.download.DownloadAAXJob.processJob(DownloadAAXJob.java:207)
	at org.openaudible.util.queues.ThreadedQueue$JobThread.run(ThreadedQueue.java:507)

mar 01, 2022 11:27:48 AM org.openaudible.Audible jobCompleted
INFORMAZIONI: DownloadQueue completed:Cibola Burn - La cura DownloadQueue size:0 remain:0 success:0 fail:66 threads:1

**Comment by openaudible** [comment]
Please use beta. #889

**Comment by openaudible** [comment]
3.5.1 should fix this permanently.
