### ISSUE TITLE
issue with small screens

### ISSUE THREAD

**Issue by Butterfly-Dragon** [openaudible/openaudible#891]
i have an affectionally named "potato pc" which is little more than a NAS of several terabytes with a 5" screen and gamepad-sized keyboard+mouse (think like a ps4 controller, but with keys instead of empty space)

due to the tiny and odd (vertical) screen resolution of 480×800 the interface looks like this:
![openaudible](https://user-images.githubusercontent.com/33538906/156205947-9a599906-7ce9-4777-b860-b0129ac6151a.png)

Is there any way to move the image of the book elsewhere or ask the program for it to not be shown?

As is it shown here, it hides information and with such a small screen i prefer information over visuals.

**Comment by openaudible** [comment]
You're killing me. 480 horizontal resolution?  Not a chance. 
Just kidding. Fixed it for the next release. You owe me!!

**Comment by Butterfly-Dragon** [comment]
🤣 well my license will renew in ... what... 1 month? so... yeah. i owe you. 😉👍💖

**Comment by openaudible** [comment]
Posted beta.

**Comment by Butterfly-Dragon** [comment]
😂 i guess the image is gone... sooo... 50% success?
![image](https://user-images.githubusercontent.com/33538906/156511634-a82b102e-6971-4ed9-9ac7-910757a04411.png)
(sorry i was not at home so i am using teamviewer to check this quickly)

**Comment by openaudible** [comment]
Hmm. Don’t have a 480px monitor to test.  Try adjusting the window size a little after a book is selected. Or restart OA? Will take another stab.

**Comment by Butterfly-Dragon** [comment]
tried that, still works like before.

**Comment by openaudible** [comment]
Made a little change right before 3.5.1.
