### ISSUE TITLE
Apply dark mode to whole application #887 - still an issue

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#892]
in 3.5.0.5beta
Setting the theme to 'system' does not detect dark mode on MacOS Catalina, it just always uses the light theme

setting the theme to 'dark' doesn't change the application title bars to dark

as a side note, I never needed the browser so it's removal actually makes the app look nicer
the only need for the browser for me was to log in.....

**Comment by openaudible** [comment]
OK. Confirmed working on M1 silicon macs, not on intel mac. Strangely, it works from the command line (debug.sh) but not when double clicking the app (which uses an installer binary, called JavaApplicationStub to launch the app. 
So.. you could run from the "debug.sh" command line to get slightly better dark mode.
Posting one last beta today.

**Comment by feldegast** [comment]
BiglyBt is a similar java app i think?it detects the sytem's theme
just a thought

**Comment by openaudible** [comment]
Yes that is a good example.

**Comment by openaudible** [comment]
Had to leave it as unsolved. Sorry I couldn’t figure it out. Running from command line (debug_mac.sh) is the only work around.

**Comment by feldegast** [comment]
all good :)

ty for trying
