### ISSUE TITLE
Copyright text

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#895]
something I have noticed recently is the copyright text includes the following ascii & # 169 ; (without spaces) rather than the copyright symbol Ⓒ it is not for all books so I think it is an issue with the Audible source data rather than an issue in the app....

from book report:
 "copyright": "&#169;2002 L.E. Modesitt ;(P)2014 Tantor",
github converts the above copyright line to show the copyright symbol rather than the ascii code.....

again & # 169 ; without spaces
this should be easy to handle I think?

**Comment by openaudible** [comment]
Yes. I think we display it correctly but don’t modify it since it isn’t our data. How do you think this issue should be fixed?

**Comment by feldegast** [comment]
yes you show the original data
i was thinking ascii encoding of characters might be convertable by the app
either automatically or with a option
so the character is used rather than the code
for those who have small collections it is not much of an issue, they can
either convert it by hand or delete the data completly
if you have a large collection (i have >200) doing this by hand is
tedious.....

**Comment by openaudible** [comment]
We could definitely convert it... Do you want it changed in the tag meta data for the converted books?

**Comment by feldegast** [comment]
That's what i was thinking yes.....

**Comment by openaudible** [comment]
fixed
