### ISSUE TITLE
A new book splitting need

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#896]
Audible.ca has a few books (Agatha Christie books for example) which include two books with their own chapter numbers in the downloaded file. Using Alexa, its hard to skip backwards and forwards to the start of each book for playback.  I want to just split the two books into separate M4b files and playback separately.  I could do this by splitting the complete file into chapters and then rejoining back into two books. Is there a better way to do this in OpenAudible.  Is there a potential feature that is of interest (and value). Thanks.  As always the latest version of the app is stable and superb.

**Comment by openaudible** [comment]
No. Too much of an edge case. Other code needs to be written. 
Glad everything else is going ok. 
Cheers,
