### ISSUE TITLE
Reveal File in Explorer broken on Windows

### ISSUE THREAD

**Issue by mtubbe** [openaudible/openaudible#899]
I'm using Windows 10 64-bit and OpenAudible 3.5.2

When I use the Show PDF option for a downloaded title (the PDF was also downloaded successfully using Get PDF), the following error shows:
View File in System Explorer Error
Unable to show file in system explorer.
See Console WIndow for more details.

The console windows shows the following command:
"Explorer " /select, "E:\Users\xxxxxx\OpenAudible\books\Loving the City.pdf" 

When I run this from the command line, it gives this error:
'"Explorer "' is not recognized as an internal or external command, operable program or batch file.
I changed the command to remove the space after the word Explorer and it worked from the command line. i.e. 
"Explorer" /select, "E:\Users\mtubb\OpenAudible\books\Loving the City.pdf"

Thanks for any help resolving this.

Mike

**Comment by openaudible** [comment]
Good catch. We made some changes to the reveal file code..  Will fix soon.

**Comment by openaudible** [comment]
This has been fixed in 3.5.3.
