### ISSUE TITLE
Syncing not download full list of books

### ISSUE THREAD

**Issue by adik0861** [openaudible/openaudible#9]
Both syncs (Quick and Full) are stopping at the 4th page of my library, so I'm only seeing 45 books.

![image](https://user-images.githubusercontent.com/19669599/41378478-05047668-6f14-11e8-916c-f75a11500a54.png)

**Comment by openaudible** [comment]
Have not been able to reproduce this. You can try the following:
Open the Audible Browser. It should take you to your library.
At the top of the page are two filters: Set to "All Time", and "All Program Types".
Close the browser, and try to do a full rescan of your library.

The code that is supposed to do that in AudibleScraper.java is a little bit of a hack-- around line 515.

**Comment by openaudible** [comment]
This should be fixed in 1.1.2, available now.

**Comment by cyotee** [comment]
I am having a similar problem. A full library sync only checks the first 2 pages of my library. It won't continue to the rest of my library.
