### ISSUE TITLE
View File In System Explorer Error

### ISSUE THREAD

**Issue by Plaenkler** [openaudible/openaudible#903]
## A picture of the error

![Error Message](https://user-images.githubusercontent.com/60503970/158073134-a4f2b48e-a95f-479c-a832-fdf63ce2d76b.PNG)

## Test Environment

Windows 10 Pro 64 Bit
AMD Ryzen 5600
32 GB RAM

## Behavior

When trying to display a M4B in the Explorer, this error occurs. The Windows File Explorer opens anyway and the desired file is displayed. The option in the configuration file contains an empty string. I have attached the log.

[Console_Output.txt](https://github.com/openaudible/openaudible/files/8240342/Console_Output.txt)

**Comment by openaudible** [comment]
Thank you for the report. This is same as #899 which I should rename.  There is a fix, and there will be a new version posted shortly.
