### ISSUE TITLE
Licence will not work with older versions as promised

### ISSUE THREAD

**Issue by conorjd** [openaudible/openaudible#904]
Licence stopped working after recent update. I installed an older version and got error "This version of OpenAudible has is expired. Please download a new version from openaudible.org" despite your website saying a licence is free forever and a license that is over 1 year old will continue to work indefinitely with any version of the software created before the expiration date.

**Comment by openaudible** [comment]
There are a few old versions don’t work well with out of date licenses when they should. Send a message to us from openaudible.org/license and we’ll make it right.

**Comment by conorjd** [comment]
I cannot see how to send a message from there but I have found a version that works with my licence, thanks.
