### ISSUE TITLE
update dialogue uses light mode when dark mode is selected

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#906]
Version 3.5.2
Dark selected in preferences
Mac OS Catalina
I got the update dialogue telling me there is a new version and saw it uses the light theme when dark is selected in prefrences

**Comment by openaudible** [comment]
Thank you. Fixed for next release.

**Comment by feldegast** [comment]
:)

**Comment by feldegast** [comment]
the browser also needs to be set to dark mode...I realize this may not be possible
it is visible when the new version prompt is shown and you click the button....

**Comment by openaudible** [comment]
Message dialogs fixed in latest beta.
Browser can't be made dark. But you can use an external browser.
