### ISSUE TITLE
Cannot attach artwork to book file

### ISSUE THREAD

**Issue by pslevy55** [openaudible/openaudible#910]
Trying to attach artwork to a book
Under Actions>get info>> Edit Book Popup,  Image tap: Drag and Drop does not work. tTis is OSX 12.1 M1. Perhaps an open file dialog box for an image?

**Comment by openaudible** [comment]
Unable to reproduce on 12.2.1 m1. 
Make sure you drag the art to the middle of the existing image. On Mac M1, you should see a little plus.
Only allowed image type is jpeg or png. 
Check the console for any errors. We do write a bunch of messages to the console when doing the drag and drop.

**Comment by pslevy55** [comment]
This is a mp3 file. There was no image attached. I tried to use a JPEG but it did not save then I noted it JPG so I converted to PNG and it saves. The console does complain about JPEG so I'm good.

Thanks!

**Comment by openaudible** [comment]
I think maybe the file was .jpeg and we were checking for .jpg ?
