### ISSUE TITLE
Audible Library not sinking completly

### ISSUE THREAD

**Issue by Craineum75** [openaudible/openaudible#911]
I purchased a few titles a week ago and neither a quick or full library sink brings up the new titles. Can someone with Openaudible look into this?

Thanks,

Tony

**Comment by openaudible** [comment]
If they are not actual purchases (instead, are free with subscription), they will not be able to be backed up. You can look at the log.

**Comment by Craineum75** [comment]
I have never added anything to my library that I did not purchase because I don't listen enough to use all of my credits. I am trying to do that at the moment and download all of my purchased audiobooks before closing my account. at the moment I probably have 20 or so titles that I haven't even started listen to and I'm tired of wasting money.  CI am trying to get the most recent books purchased by the end of the day because my account charges/renews on the 28th.

**Comment by openaudible** [comment]
Ok. Make sure you don't have any books "ignored". You can look through the log and see if any books were skipped.
Sometimes if a book becomes "free" it makes it hard to download.
If you want, quit and restart OA, do a "Full Library Sync", and send a bug report from the About menu with the name of a book you're not seeing.
