### ISSUE TITLE
Download format wrong

### ISSUE THREAD

**Issue by ziferius** [openaudible/openaudible#913]
The same problem as issue #825:
This audio format is not supported for the title. Please download in another audio format.
With the book '10 Masterpieces You have to Listen Before you Die 2'

From the library page on the website, I wasn't able to download the 'Full' audiobook, but was able to download it in parts.
Can I put the resultant aax files in the library axx folder and then modify the books.json?
From what I've seen, it doesn't support multiple files -- or doesn't appear to.

**Comment by openaudible** [comment]
I think you can import the aax files one at a time but not positive if they will be treated as duplicates. So at least one could be imported and converted. Then try part two and see if that works. 

Are you using the latest version?

**Comment by ziferius** [comment]
Yeah; 3.5.3

Here are the filenames it downloaded:
10MasterpiecesYouHavetoListenBeforeYouDie2Part1_ep9.aax
10MasterpiecesYouHavetoListenBeforeYouDie2Part2_ep9.aax
10MasterpiecesYouHavetoListenBeforeYouDie2Part3_ep9.aax
10MasterpiecesYouHavetoListenBeforeYouDie2Part4_ep9.aax
10MasterpiecesYouHavetoListenBeforeYouDie2Part5_ep9.aax
10MasterpiecesYouHavetoListenBeforeYouDie2Part6_ep9.aax
10MasterpiecesYouHavetoListenBeforeYouDie2Part7_ep9.aax

**Comment by openaudible** [comment]
So we don't have real support for converting them but you can try to drag and drop them onto your OpenAudible and see if they get imported as 7 "books" and at least have the parts. But they may get ignored as duplicates. 

If you attempt to download the book when "connected" to your audible and get that same error message about This audio format is not supported for the title, send a bug report and we can probably get a real fix.

**Comment by openaudible** [comment]
I'll keep an eye out for any bug reports with this #913 issue number.
