### ISSUE TITLE
feature request: make it possible to edit chapter titles

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#915]
when exporting to m4b files as a single file the file can contain chapter text, being able to edit this text before converting would be great
there is no GUI-based M4B chapter text editor that I am aware of....so this would be a great addition

**Comment by openaudible** [comment]
This gets tricky fast. Editing titles is pretty easy. Setting time stamps much harder as they are in seconds/milliseconds and no easy way to mark positions. Plus the chapters would be prone to be overwritten with the original audible data. Some audio editing software with a GUI is needed. 

Unlikely.

**Comment by feldegast** [comment]
changing timestamps would i agree be hard I was just referring to the chapter text

**Comment by openaudible** [comment]
Ok. Might be able to change just the text.

**Comment by feldegast** [comment]
if possible that would be great, I am searching around for an app to edit chapter text in m4b files, so far I have not found a good solution, so if it is solved during conversion a lot of my audiobooks will be good without an extra app

**Comment by feldegast** [comment]
as a 1st step, the start offset and length is currently displayed in seconds, if instead it was shown as HH:MM:SS.xxx it would at least be more readable, and this I think is easy
