### ISSUE TITLE
Error converting: ffprobe error

### ISSUE THREAD

**Issue by footflaps** [openaudible/openaudible#916]
Just downloaded, installed and licennsed OA for the first time and it crashes trying to download / import my one and only book.

Error log is:

It can't convert my one and only Audible book - errors with "Error converting: ffprobe error"

stdout:
stderr:
Apr 04, 2022 8:09:48 PM org.openaudible.convert.FFProbe probe
SEVERE: probe error on C:\Users\BenFreeman\OpenAudible\art\Harry Potter à l'École des Sorciers.jpg size=48168 cmd:"C:\Program Files\OpenAudible\bin\win\ffprobe.exe" -hide_banner "C:\Users\BenFreeman\OpenAudible\art\Harry Potter à l'École des Sorciers.jpg" -show_streams -show_chapters -show_error -show_format -print_format json 
error code:-1073741515(C0000135)+
**MFPlat.dll is required and should be added to your System32 directory if it is not there.**

stdout:
stderr:
Apr 04, 2022 8:09:48 PM org.openaudible.convert.FFProbe probeFiles
SEVERE: Error
java.io.IOException: ffprobe error
	at org.openaudible.convert.FFProbe.probe(FFProbe.java:54)
	at org.openaudible.convert.FFProbe.probe(FFProbe.java:23)
	at org.openaudible.convert.FFProbe.probeFiles(FFProbe.java:103)
	at org.openaudible.desktop.swt.manager.AudibleGUI.bookReport(AudibleGUI.java:1205)
	at org.openaudible.desktop.swt.manager.editor.DetailsView$PopulateTask.run(DetailsView.java:41)

**Comment by openaudible** [comment]
If you use Windows N, you need to install some extra software, namely Windows Media Future.

https://www.microsoft.com/en-us/software-download/mediafeaturepack

We've seen this in #430 which has more of a discussion.

**Comment by footflaps** [comment]
Hi Guys,

Yes it occurred to me last night that my Windows Pro build is probably the problem! I opted to not install Windows Media Player (as it's crap) but that has caused lots of things to not work properly!

Thanks,

Ben




[cid:CBNG_Logo_69501156-0daa-4628-a7a1-f23dc9f3e3b8.png]                Ben Freeman
Network Architect


        e: ***@***.***
        t: +44 7971 854 949
        w: www.cbng.co.uk<https://www.cbng.co.uk/>


[cid:SocialLink_Linkedin_32x32_86ed2d44-a8e3-4bc1-9fd6-a7dcf971b405.png]  Visit CBNG on LinkedIn<https://www.linkedin.com/company/cambridge-broadband/>
[cid:CBNG_Logo-Tiny_703862c1-f0d2-4fa1-843b-5009d051f32a.png]   CBNG Press Releases<https://www.cbng.co.uk/About/Press-Releases> & CBNG Newsletter<https://mailchi.mp/d34e19276de3/cbngmaynewsletter>
          Sign Up For Our Newsletter Mailing ***@***.***?subject=CBNG%20Newsletter%20Opt-In%20&body=Hello,%0D%0DPlease%20sign%20me%20up%20to%20receive%20the%20CBNG%20Newsletter.%20%0DThank%20You>


Cambridge Broadband Networks Group Ltd, registered company: 10427528 184 Cambridge Science Park, Milton Road, Cambridge, CB4 0GA, UK
.
The content of this email is confidential, intended for the recipient specified in the message only, and is deemed to be covered by a confidentiality agreement, if one exists between the parties. It is strictly forbidden to share any part of this message with any third party, without the written consent of the sender. If you received this message by mistake, please reply to this message and follow with its deletion, so that we can ensure such a mistake does not occur in the future. Cambridge Broadband Networks Group Limited puts email security at a high priority. Therefore, the company has taken reasonable precautions to ensure this message is error and virus-free before leaving our mail system. Unfortunately, full security of the email cannot be ensured, despite our best efforts, the data included could be intercepted, infected, or corrupted. Therefore, the recipient should check the email and any attachments for the presence of viruses and other threats with proper data security software. The sender does not accept liability for any damage inflicted by receiving, viewing the content of this email, or any attachments, including errors or omissions in the contents of this message which arise as a result of email transmission.





De : openaudible ***@***.***>
Envoyé : 04 April 2022 20:52
À : openaudible/openaudible ***@***.***>
Cc : Ben Freeman ***@***.***>; Author ***@***.***>
Objet : Re: [openaudible/openaudible] Error converting: ffprobe error (Issue #916)

CAUTION: This email originated from outside of CBNG.


If you use Windows N, you need to install some extra software, namely Windows Media Future.

https://www.microsoft.com/en-us/software-download/mediafeaturepack<https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.proofpoint.com%2Fv2%2Furl%3Fu%3Dhttps-3A__www.microsoft.com_en-2Dus_software-2Ddownload_mediafeaturepack%26d%3DDwQCaQ%26c%3DeuGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM%26r%3DPz9BjpDlww_zwhz80zPBMA%26m%3DVJbDkUchYN6bRQkRzFE9xdqmMfo4wGKYvWgCdKzaKeE%26s%3DrT9KiliQP3HLh46pUrjN8ctvGx3Hyi4dj4lpTiSRBWY%26e%3D&data=04%7C01%7C%7C9567c031d4014a330da708da16749928%7Cc86a68a8301d416f9cc68d2cc5cd0dfd%7C0%7C0%7C637846987284025447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=TQM6JxojmpGUD1P9Mece1%2FFJ58zKJTcXMsFmksEnVdc%3D&reserved=0>

We've seen this in #430<https://gbr01.safelinks.protection.outlook.com/?url=https%3A%2F%2Furldefense.proofpoint.com%2Fv2%2Furl%3Fu%3Dhttps-3A__github.com_openaudible_openaudible_issues_430%26d%3DDwMCaQ%26c%3DeuGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM%26r%3DPz9BjpDlww_zwhz80zPBMA%26m%3DVJbDkUchYN6bRQkRzFE9xdqmMfo4wGKYvWgCdKzaKeE%26s%3DWpnNoWgixsXanCkmMtgfL62F-7i4JsrWdR-_QQRJJtw%26e%3D&data=04%7C01%7C%7C9567c031d4014a330da708da16749928%7Cc86a68a8301d416f9cc68d2cc5cd0dfd%7C0%7C0%7C637846987284025447%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=mpg09Pc2Ys%2F8rcVyBM40ZaGFaKaK1XSYuETJTyikGdg%3D&reserved=0> which has more of a discussion.

-

**Comment by openaudible** [comment]
Ah. Ok. We will need to add a better alert. 
don’t need to install all of windows media player but just find a good copy of the dll.
