### ISSUE TITLE
Personal use notice repeatedly coming up!

### ISSUE THREAD

**Issue by alexr22ian** [openaudible/openaudible#918]
Every time a job is completed, (downloading a book, converting a book) the Personal use notice pops up requiring me to press Ok to have Open Audible continue!  I have 1 audible account, with nearly a thousand books on it.  Not 5 or 6.  Having to repeatedly press Ok to make the program continue makes a complete mockery of automation.  I'm not thick, I don't want to see it many times.  Once is more than enough please.

**Comment by DHBgithub2021** [comment]
Yes, getting this as well.

**Comment by openaudible** [comment]
A keys json file is created that caches the account info so it isn’t displayed if already present. But weird this is the first reports ever. 

Will investigate.

**Comment by openaudible** [comment]
Thank you for the report. Confirmed and fixed. 

We made a server side change that should reduce this behavior.. and have added a check on the application side to prevent this in the next version.
