### ISSUE TITLE
Settings Dialog Is Not Completely Screen Reader Friendly

### ISSUE THREAD

**Issue by RichWYamamoto** [openaudible/openaudible#919]
I am a completely blind user of OpenAudible, and I really like the application. The only problem I have is that the settings dialog isn't fully navigable with screen readers on Windows such as NVDA. The checkboxes, radio button groups, and combo boxes read just fine. The only elements that don't read, and the only things I can't click on with the keyboard are the directory points. I'm unable to change the directory locations for my library, web information, or preferences. If you change the graphics to labeled buttons and editable textfields, it would make this process completely accessible for blind users.

**Comment by feldegast** [comment]
the pencil buttons, if it was replaced with buttons with the text "edit" and the folder buttons replaced with buttons with the text "open" would solve this issue, if there is not an easier way to make it easier to use for those with vision issues

**Comment by openaudible** [comment]
Not a lot of room to add text.. but I did hack the Image button in a non-standard way. Will build a beta using a "toolbar" instead. 

Thanks for the suggestion.

**Comment by openaudible** [comment]
I posted a beta with new buttons for edit and reveal location in the preferences. 
The text isn't editable, but can be changed by clicking on the "edit" (pencil) button. 
https://openaudible.org/beta

**Comment by openaudible** [comment]
Reopen if not fixed in beta or next release. ThAnk you for the report.

**Comment by RichWYamamoto** [comment]
Looks good. I can see the button labels by moving the object navigator in NVDA to them, but when I press the tab key to navigate, the screen reader just says “button 1 of 2”. This means that it sees two buttons on each toolbar, but when I tab, it moves to the next toolbar instead of the next button. And the button label is only seen when I move the cursor to it with the mouse commands on the keyboard.This is a great start though. Keep up the good work! Sent from Mail for Windows From: openaudibleSent: Sunday, April 10, 2022 5:16 PMTo: openaudible/openaudibleCc: RichWYamamoto; AuthorSubject: Re: [openaudible/openaudible] Settings Dialog Is Not Completely Screen Reader Friendly (Issue #919) I posted a beta with new buttons for edit and reveal location in the preferences.The text isn't editable, but can be changed by clicking on the "edit" (pencil) button.https://openaudible.org/beta—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
