### ISSUE TITLE
Not downloading books added

### ISSUE THREAD

**Issue by firstWizball** [openaudible/openaudible#920]
I have added some books that are free to my library.
I can see the books in my library but open audible is not downloading them.
One such book is 
https://www.audible.co.uk/pd/Taliesin-Audiobook/B004FTKP2U?action_code=ASSGB149080119000H&share_location=pdp&shareTest=TestShare

I have no idea what to check in the console but cannot see any errors

**Comment by openaudible** [comment]
Did you select the book and select "Download" from the action menu? 
Also, "Connected" in the library status should say "Yes". 
Then check the log for any messages.

**Comment by firstWizball** [comment]
I think I did not describe this very well the books are not even showing in my library? 
   On Wednesday, 13 April 2022, 01:36:25 BST, openaudible ***@***.***> wrote:  
 
 


Did you select the book and select "Download" from the action menu?
Also, "Connected" in the library status should say "Yes".
Then check the log for any messages.

**Comment by davidsmith1986** [comment]
I have never been able to download the "free" books. I thought this wasn't possible.

**Comment by firstWizball** [comment]
Hi
I managed to find a program that can do this Libation.You might want to look to see how they do it.
RegardsPeter

    On Saturday, 16 April 2022, 10:01:35 BST, davidsmith1986 ***@***.***> wrote:  
 
 


I have never been able to download the "free" books. I thought this wasn't possible.

**Comment by openaudible** [comment]
Yeah, Libation is great. We just want to walk a fine line between offering a good product for backing up your purchases.

**Comment by oboe45** [comment]
Biggest problem is that it runs on WIndows, not Mac!

**Comment by firstWizball** [comment]
I am running this on windows?

Sent from Yahoo Mail on Android 
 
  On Sun, 17 Apr 2022 at 19:57, ***@***.***> wrote:   

Biggest problem is that it runs on WIndows, not Mac!
