### ISSUE TITLE
openaudible error message: error downloading:Tag mismatch

### ISSUE THREAD

**Issue by fwoeck1** [openaudible/openaudible#922]
New problem with openaudible. Had no problem recently downloading my audible library books until today. Book partially downloads then stops with the following message: error downloading:Tag mismatch.

**Comment by openaudible** [comment]
This is a strange one. Are you on a VPN? Seems like a security SSL connection issue. Only thing I can think of is to retry the download later..

**Comment by fwoeck1** [comment]
No VPN. What makes this odd is this was never a problem until today.
I've tried downloading it about 6 different times after closing and
opening OA. Running Win 10, 64 bit.

**Comment by fwoeck1** [comment]
This problem is solved (for now). After rebooting desktop I successfully
downloaded the title in question and transferred to itunesfor download
on my ipod nano 7.

**Comment by openaudible** [comment]
Very strange. But definitely a rare occurrence.

**Comment by xenduro** [comment]
i been getting them for several days now.55 at the moment. its been download for 4 days. i will try the restart when it fihishes the last 276 conversions
