### ISSUE TITLE
Unable to Purchase (web site 400 errors)

### ISSUE THREAD

**Issue by rnbwpnt** [openaudible/openaudible#923]
Time to renew, but Error 400 at https://openaudible.org/purchase

Confirmed in Brave, Firefox, and Chrome for Mac. Intermittent in Safari. Note that I'm on a T-Mobile Home Internet connection, which has a huge proxy. The payment processor may be blocking TMHI, which is a problem.

**Comment by openaudible** [comment]
That is a bummer. 

Here is the link we send you to: https://bookmanager.onfastspring.com/openaudible 
Can you try that one?

Also, if you're already a licensed user, go to the "License" field in OpenAudible and click on the upgrade link.. and it will take you to a new page that has a discounted price for the upgrade. 

Thank you for the heads up. Will try to diagnose on our end. Feel free to send me an email to openaudible at email dot tg if you need more help with an upgrade link or have other questions.

**Comment by openaudible** [comment]
I think we broke something. Just saw the same error on a linux computer. Also got a report from a user trying to download one of the binaries. We did recently change the redirect logic. Stand by as we try to debug.

**Comment by openaudible** [comment]
We rolled back some changes. 
we are unable to reliably reproduce this error. We have reports on downloads and the purchase links, both instances where we send a 302 location changed message in the browser to redirect the page to an external site. (For downloads, the releases section of this GitHub depository). 

Any updates of if this is still happening or resolved would be greatly appreciated. The one local Linux box that briefly had a 400 error is now working as expected. 

Thanks ya’ll.

**Comment by jacroe** [comment]
Tried it just now, and I've experienced no change, yet. Still receiving a 400 on my Ubuntu box with the purchase link as well as all the non-Docker downloads.

I'll keep trying though.

**Comment by rnbwpnt** [comment]
Unable to reliably confirm a fix at this time, but after a few attempts I started getting through. It may have been a combination of you rolling back the error and content caches expiring.

**Comment by jacroe** [comment]
Fully working for me now.

**Comment by openaudible** [comment]
Thank you for the reports. Very strange as I never saw 400’s on the server. But only on my old Linux browser n

**Comment by openaudible** [comment]
Finally solved. This was a missing cookie bug... Sorry for the troubles and THANK YOU for the reports!
