### ISSUE TITLE
Broken M1 download link, internal to app and on website.

### ISSUE THREAD

**Issue by the1gofer** [openaudible/openaudible#924]
Download link seems to be broken. https://openaudible.org/latest/OpenAudible_mac_aarch64.dmg

**Comment by openaudible** [comment]
I assume you're getting a 400 error? This sounds like a duplicate of #923 .... Which we are working on and _thought_ we had a fix for.

**Comment by openaudible** [comment]
Finally solved. This was a missing cookie bug... Sorry for the troubles and THANK YOU for the report.
