### ISSUE TITLE
Library not syncing new books

### ISSUE THREAD

**Issue by intile** [openaudible/openaudible#927]
For the life of me I cant get my library to find new books that I purchased. I am signed in & it will find 21 titles but there should be 26 titles.

**Comment by openaudible** [comment]
We don't allow "backing up" of "free" books. Only books you've purchased. That is the most common reason.

**Comment by intile** [comment]
For some reason audible was letting me listen to the full book and add it to my library without purchasing but once I purchased it fully it worked.

**Comment by openaudible** [comment]
Thank you for the update.
