### ISSUE TITLE
Ubuntu 21.10 and blank browser

### ISSUE THREAD

**Issue by JeeMo** [openaudible/openaudible#928]
Hi!
I am running Ubuntu 21.10 and when I try to 'Connect to Audible' I get a blank browser page.  When I try to edit Preferences, I get nothing.
Can you provide me any info about how to debug this issue?

I've purchased a license and activated it.  I've tried installing via the .deb and the AppImage methods.  I get the same responses for both.
Advice is greatly appreciated!

**Comment by openaudible** [comment]
What does the console log say? (CTRL-E)
The snap installer does have a different (Chromium based) browser that might give better results.
sudo snap install openaudible

**Comment by openaudible** [comment]
Oh good. 

For future reference:

There are some log window messages that can recommend other required packages that can be installed. 

Also, if the default internal browser isn't working, the chromium browser widget can be enabled by setting an enviornment variable:

```
oa_chromium=true
```
