### ISSUE TITLE
can' sign in to open audible

### ISSUE THREAD

**Issue by sones857** [openaudible/openaudible#930]
Debian 11     (.deb file installed. ) 

I can't open preferences, nothing happend when I click on preferences, also can't sign in, a blank window appears when I click on sign in to audible. 

tried sudo apt install gstreamer1.0-plugins-bad  

please advise. Thank you

**Comment by openaudible** [comment]
Anything in the console window? (Ctrl-e) 
You could try docker or snap version.

**Comment by sones857** [comment]
console output seems okay, yes, i will try that, thank you

**Comment by openaudible** [comment]
Ok. The other thing to do is define an environment variable of oa_chromium=true and try again. That should fix it. Although it’s a bug that it doesn’t automatically recognize that your browser is crashing.
