### ISSUE TITLE
Feature Request: File Naming

### ISSUE THREAD

**Issue by RandmTask** [openaudible/openaudible#932]
Saw this as a very old feature request, that could really be useful with the new ability to update tags in OpenAudible

Put in the file naming mask:
 \My Audiobooks\<Author>\<Series>\<Author> (Narrated by <Narrator>) - <Series>, Book <Series Number> - <Title> (<Year>)

Eg. \My Audiobooks\King, Stephen\Bill Hodges Trilogy\Stephen King (Narrated by Will Patton) - Bill Hodges Trilogy, Book 1 - Mr Mercedes (2014).m4b

Would be a fantastic addition if implemented

**Comment by openaudible** [comment]
This feature is in progress. Several duplicate issues and discussions are around. Marked as a feature request.
