### ISSUE TITLE
Issue with Plus catalogue

### ISSUE THREAD

**Issue by RandmTask** [openaudible/openaudible#933]
For some reason in 3.5.3 (and the latest beta) OpenAudible will not pull the Audible Plus free titles.

However, I can go back to my old version 3.1.2 and do a Full Library refresh and the Audible Plus titles appear and then I can download them in either 3.5.3 or 3.1.2

### **3.1.2 displays the Plus titles just fine**
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/7912017/165351484-ba45242d-f97d-4993-b2f2-e873b9e5786e.png">

### **3.5.3.1 after a Library refresh still doesnt show Plus titles:**
![AUDIBLE without PLUS titles](https://user-images.githubusercontent.com/7912017/165351614-357b347b-6705-4d5f-bb05-c571e139e1d4.png)

I have tried this on both my M1 Mac Mini and my M1 MacBook Air with the same results.

Let me know if you need any extra info to troubleshoot!

I tried to send a bug report from the app and got this:
_Error sending bug report.
Perhaps bug reporting is disabled or there is a bug in a bug reporter or a firewall or antivirus program is blocking it.
More details about this error are in the debug log.
You can resend, or cancel.
Error: java.lang Exception: Error accepting report. org.springframework.dao.DatalntegrityViolationException: could not execute statement; SQL [n/a]; nested exception is org.hibernate.exception. DataException: could not execute statement_

**Comment by oboe45** [comment]
Read the page on the Audible site.  You can listen to the books in the
"Included" category, and you may, in doing so, download the books to your
library, but you cannot, for example download and convert to any format.

It is not possible to download included books for subsequent conversion.
I have used the Mac versions of OpenAudible for years, you cannot
dowload and convert the Included books - in any version of OpenAudible.

Am I missing something?

**Comment by RandmTask** [comment]
If you have a look at the first picture, all the books are from the Plus catalogue except for the Stephen King book, which I purchased

You can see here that I have downloaded these books and converted them to m4b. 

<img width="541" alt="image" src="https://user-images.githubusercontent.com/7912017/165437910-e12518fb-434a-41c5-bf54-bc8eda5d8389.png">
 
To be clear, these Plus titles are **not** available to download from the Audible websites My Library page, only via OpenAudible (and libation on windows from which I can also download items from the Plus catalogue). Also, this is audible.com.au, so YMMV.

**Comment by RandmTask** [comment]
To summarise: 
First open OpenAudible v3.5.3.1 and do a Full Library refresh -> **No** Plus titles will appear
Then open OpenAudible v3.1.2 and do a Full Library refresh -> Plus items appear

Then can go back to OpenAudible v3.5.3.1 to download the Plus titles (or keep using v3.1.2)

**Comment by openaudible** [comment]
We are starting to add support for included titles, starting with the latest beta. You can take a look. (You'll need to enable "Included titles" in the preferences.) https://openaudible.org/beta
