### ISSUE TITLE
Error in startup application

### ISSUE THREAD

**Issue by djadul2** [openaudible/openaudible#934]
I've uninstalled and reinstalled and the app still won't open. It says there's an error in the start up code. Please advise.

If this requires some type of programming knowledge, because I've seen the responses for other issues, I don't think this is the app I need and I will request a refund. Just let me know. Thank you.

**Comment by openaudible** [comment]
What platform and installer did you use? 

All platforms require 64bit CPU.

Do you see an error message? Feel free to send a screenshot to openaudible at email dot tg.

**Comment by djadul2** [comment]
I have a 64 bit Windows 10 computer.
To install the program, I opened and ran the file.
What do you mean "installer"?
Attached is a screen shot of the message. I hope you can read it.

**Comment by openaudible** [comment]
For windows, you download the OpenAudibleInstaller.exe file, run that.. and then start the OpenAudible application.

I don't have a good sense of what steps you've followed and which one is not working. 

You may want to make sure your anti-virus program isn't blocking OpenAudible.

Didn't get the screenshot. Please email the screenshot to openaudible <@> email.tg and we can take a look.

**Comment by djadul2** [comment]
Ok. Iʻll try again.

Iʻll check the firewall. That is a good possibility.

Thank you.

Iʻll update in a few days.

**Comment by openaudible** [comment]
Looks like your anti-virus program is preventing some of the required installer functions to work.

**Comment by djadul2** [comment]
I appreciate your identification of the problem. ... Should I then turn *off
*my antivirus software, and *reinstall the program from the beginning*?
