### ISSUE TITLE
After upgrade / new license can no longer convert to MP3

### ISSUE THREAD

**Issue by adragor** [openaudible/openaudible#935]
Today I fired up OpenAudible to be told that there is a new version (3.5.3) so I upgraded. Then I was told that my one year license had expired, so I renewed.

Now I can no longer convert downloaded books to MP3. I have tried restarting OpenAudible and logging out / logging back in to Audible.

Please see license window and error (or at least message that I get) screenshot.

![OpenAudible Personal Use Notice](https://user-images.githubusercontent.com/8799132/166124917-a36362a5-3746-418f-a802-427240535291.png)

**Comment by openaudible** [comment]
I’ll invalidate that license and send you a new one.

**Comment by openaudible** [comment]
This should be resolved by now.. It looked like a server issue. If you have any questions, email us or send a bug report from the application.
