### ISSUE TITLE
Error converting: duplicate:ff:/oa/bin/tables

### ISSUE THREAD

**Issue by Fisheri** [openaudible/openaudible#936]
Consistent error with many files when attempting conversion!

**Comment by openaudible** [comment]
Strange. What version? We don’t use tables anymore. Copy and paste more of the error from the console.

**Comment by b1ueliner** [comment]
I am getting similar errors. When I got the error, I tried updating to your beta version: OpenAudible_3.5.3.1_beta_x86_64.exe, but that did not fix the problem. The State Error is: "Error converting: duplicate:fnf:/oa/bin/tables." I tried converting to .mp3 and m4b, with no luck.

**Comment by Fisheri** [comment]
here is my console:

{
 "date": "Sun May 01 06:19:35 EDT 2022",
 "books.json": "/Users/fisheri/Library/OpenAudible/books.json",
 "memory": "Memory: Using 318.99Mb of 4096Mb (8%) Min 217.17Mb Max 318.99Mb",
 "directories": [
  {
   "path": "/Users/fisheri/Library/OpenAudible",
   "kind": "BASE",
   "exists": true
  },
  {
   "path": "/Users/fisheri/Library/OpenAudible/books",
   "kind": "BOOKS",
   "exists": true
  },
  {
   "path": "/Users/fisheri/Library/OpenAudible/web",
   "kind": "WEB",
   "exists": true
  },
  {
   "path": "/Users/fisheri/Library/OpenAudible",
   "kind": "META",
   "exists": true
  },
  {
   "path": "/Users/fisheri/Library/OpenAudible/aax",
   "kind": "AAX",
   "exists": true
  },
  {
   "path": "/Users/fisheri/Library/OpenAudible/art",
   "kind": "ART",
   "exists": true
  },
  {
   "path": "/Users/fisheri/Library/OpenAudible/MP3",
   "kind": "MP3",
   "count": 1,
   "exists": true,
   "sample": "/Users/fisheri/Library/OpenAudible/MP3/sample.mp3"
  },
  {
   "path": "/Users/fisheri/Library/OpenAudible/tmp",
   "kind": "TMP",
   "exists": true
  },
  {
   "path": "/Applications/OpenAudible.app/Contents/Resources/app",
   "kind": "APP",
   "exists": true
  },
  {
   "path": "/Users/fisheri/Library/OpenAudible/M4A",
   "kind": "M4A",
   "count": 0,
   "exists": true,
   "sample": "/Users/fisheri/Library/OpenAudible/M4A/sample.m4a"
  },
  {
   "path": "/Users/fisheri/Library/OpenAudible/M4B",
   "kind": "M4B",
   "count": 15,
   "exists": true,
   "sample": "/Users/fisheri/Library/OpenAudible/M4B/sample.m4b"
  },
  {
   "path": "/Users/fisheri/Library/OpenAudible/PDF",
   "kind": "PDF",
   "exists": true
  }
 ],
 "gui": {
  "swt_platform": "cocoa",
  "main_window": "Rectangle {21, 23, 1404, 923}",
  "browser": {
   "prefer_chromium": false,
   "oa_chromium": "",
   "Desktop.isDesktopSupported": true,
   "externalBrowser": true,
   "Desktop.Action.BROWSE": true,
   "externalBrowserMode": "desktop",
   "oa_internal_browser": "",
   "browseWebCmd": ""
  },
  "display": {
   "highContrast": false,
   "bounds": "Rectangle {0, 0, 1920, 1080}",
   "dpi": "Point {72, 72}"
  },
  "aspect": 1.5211267,
  "theme": {
   "dark_debug": "set  org.eclipse.swt.display.useSystemTheme from  to true\n",
   "org.eclipse.swt.display.useSystemTheme": "true",
   "theme": "system",
   "is_dark": false
  },
  "swt_version": 4944
 },
 "compile_date": "2022-03-18 00:03",
 "region": "US",
 "version": "3.5.3",
 "demo": false,
 "platform": "mac",
 "properties": {
  "oa_external": "",
  "os": "ProductName:\tMac OS X\nProductVersion:\t10.14.6\nBuildVersion:\t18G9323\n",
  "java.version": "17.0.1",
  "oa_ayce": "",
  "sun.jnu.encoding": "UTF-8",
  "locale": "LANG=\"en_CA.UTF-8\"\nLC_COLLATE=\"en_CA.UTF-8\"\nLC_CTYPE=\"en_CA.UTF-8\"\nLC_MESSAGES=\"en_CA.UTF-8\"\nLC_MONETARY=\"en_CA.UTF-8\"\nLC_NUMERIC=\"en_CA.UTF-8\"\nLC_TIME=\"en_CA.UTF-8\"\nLC_ALL=\n",
  "oa_internal_browser": "",
  "oa_packaging": "",
  "org.eclipse.swt.display.useSystemTheme": "true",
  "file.encoding": "UTF-8",
  "oa_chromium": "",
  "SWT_GTK3": "null",
  "OPENAUDIBLE_HOME": ""
 },
 "prefs": {
  "disableVersionCheck": false,
  "lastVersion": "3.5.3",
  "playFileCmd": "",
  "webPageIncludeMP3": true,
  "format": "M4B",
  "autoConvert": false,
  "mp3Qscale": 4,
  "autoDownload": false,
  "language": "en",
  "autoWebPage": false,
  "autoRefreshMinutes": 0,
  "autoConnect": false,
  "uid": "1547666716621",
  "concurrentConversions": 3,
  "browseFileCmd": "",
  "autoLink": false,
  "concurrentDownloads": 3,
  "browser": "",
  "html": false,
  "theme": "",
  "autoPDF": true,
  "migrated": true,
  "region": "US",
  "browseWebCmd": ""
 }
![Screen Shot 2022-04-30 at 9 13 57 PM](https://user-images.githubusercontent.com/30553720/166141836-e0705aea-da83-4eee-b9f0-b0f14da3825a.png)
}

**Comment by anniekees** [comment]
@fisheri what did you do to solve this?  thank you

**Comment by Fisheri** [comment]
I did NOT solve it!

**Comment by openaudible** [comment]
That was a server problem on our end.. and the backup server was also failing. It should be fixed now. Sorry for the trouble.

**Comment by anniekees** [comment]
Yup super good! working like a charm now.

**Comment by Fisheri** [comment]
Works for me too! Thanks.

**Comment by b1ueliner** [comment]
It's working for me now, also. Thank you. 

However, I don't understand the connection to your server. Are conversions not performed on local machines? I didn't realize that that function involved a server dependency.
