### ISSUE TITLE
Can't convert books. Option is greyed out. 

### ISSUE THREAD

**Issue by bluedolphin0502** [openaudible/openaudible#937]
Hi all. 

No option to convert books, although I have successfully done so in the past. 
I've checked and have the latest version. 

TIA.

**Comment by openaudible** [comment]
Select the book. If the state says "ready to convert", the action menu should allow you to convert to mp3 or m4b, depending on your preferences. Maybe the book is already converted?

**Comment by bluedolphin0502** [comment]
Unfortunately it says 'In download queue', but nothing happens after that.
And yeah, definitely not already converted.
Everything still greyed out.

Any further suggestions, please?

Kind Regards
*Rach*

**Comment by openaudible** [comment]
If its in the download queue, that means the book hasn't been downloaded yet... and is waiting on other books to finish downloading. This can take a while for all your books to download. 

You can check which books are being downloaded by clicking on the "Downloading" number on the Library Info panel. 

You can click on "To Convert" to see which books have been downloaded and can be converted to mp3 or m4b.
