### ISSUE TITLE
Can't convert Books

### ISSUE THREAD

**Issue by Carescha** [openaudible/openaudible#938]
Hi. Yesterday I downloaded Openaudible. I downloaded an audiobook and converting was no problemo. Then i bought a license and now i can't convert books anymore.

It says  fehler beim Konvertieren: duplicate:fnf:/oa/bin/tables

Kind regards

**Comment by anniekees** [comment]
This is the same issue as #936.  Im in the exact same situation.

**Comment by Carescha** [comment]
I will participate in the other Post and close this one.
