### ISSUE TITLE
doesn't let me convert to mp3

### ISSUE THREAD

**Issue by jpca999** [openaudible/openaudible#94]
Pls see in the image below. 
1) I imported the aax file. 
2) i selected the file
3)  ??  it doesnt let me select "convert to mp3"  Whats wrong ?

![image](https://user-images.githubusercontent.com/1026325/52917685-a3c67700-32ab-11e9-8bc1-c1b8b15b35c7.png)

**Comment by openaudible** [comment]
It looks like the book is already being converted (status shows Converting: 1) ! Selecting the one book will update the "Task" that shows the status of downloading, converting, or whether it can be converted. 
Check the console window log. Re-open if this isn't the case.

**Comment by andrewcfitz** [comment]
It should be made more clear that it will auto convert.  I came here for the same problem.

**Comment by aaphid** [comment]
I've come here for the same issue except that in my case it does not show that it is converting anything at all.

I have downloaded and selected an .aax file but the convert option is greyed out.

Is there something else I need to do?
