### ISSUE TITLE
Unable to login to Audible from Windows OA

### ISSUE THREAD

**Issue by PacoBell** [openaudible/openaudible#941]
It doesn't seem to like my newly changed 128-character password. Is OA silently truncating my password before sending it to Amazon? I'll send a bug report capture.

**Comment by PacoBell** [comment]
Okay, it appears the issue is caused by my office firewall intercepting the TLS certificate and replacing it with its own. OA or Amazon doesn't like that, so it fails. If I connect to my phone's hotspot, it works fine. I'll use that workaround for now.

**Comment by openaudible** [comment]
Just saw you closed this. We don't intercept passwords.. we use the browser and once connected, we get a "cookie" that contains a login token we can use to access your books.
