### ISSUE TITLE
Duplicate Installations

### ISSUE THREAD

**Issue by shiningprince** [openaudible/openaudible#942]
I am using Ubuntu 20.04 LTS.  I installed OpenAudible today and purchased a license.  I got it working but it appears I have two copies of the application, one is filled with my Audible files and I cannot save that to my favorites and the other one opens empty (shows up next to the first one on dock) and it will allow me to save to favorites (or dock).

When I search for OpenAudible within Ubuntu both copies show up.  I went to uninstall from the app store and successfully uninstalled it (it now says "Install")  - but the empty version disappeared but the full version (with all my files) is still there.  How can I start fresh and install anew so that I have only 1 correctly working (meaning I can save to favorites) version?

Thanks.

**Comment by openaudible** [comment]
Not totally sure- Try uninstalling using the uninstaller, or snap uninstall, or just delete the application folder and any shortcuts. OA doesn’t install any drivers or things outside of the application dir, so pretty safe to just delete it. Then reinstall. The .sh installer is the preferred method for install/uninstall.

**Comment by shiningprince** [comment]
Thank you for the quick reply!

I did try those things and therefore will try just deleting the folder.

What is the .sh installer?

**Comment by openaudible** [comment]
It is the main OA installer for linux that has a .sh extension (rather than .deb, rpm, appImage)

Available here: https://openaudible.org/latest/OpenAudible_x86_64.sh
