### ISSUE TITLE
Request for sample m4b file with chapter data

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#944]
Hi, I am trying to get m4b chapter data implemented in other projects, kid3 to start with so I can edit chapter data within m4b files along with the basic metadata, to do that I need an m4b file with chapter data to give the kid3 developers, one that I can distribute...
would you be able to help?

Thanks in advance

**Comment by openaudible** [comment]
All the m4b files should include chapter data. You can review it with ffprobe which is also available in the OA book info page. 
Are you trying to edit chapter names? I think we started working on that.. 
We don't have any sample files that are copyright-free to distribute.

**Comment by feldegast** [comment]
I am trying to give someone working on KID3 a file so they can work on
adding chapter editing... so the file can have junk audio it just needs
chapter data if I knew how to edit the audio without changing other data I
could do it...

**Comment by openaudible** [comment]
I can send a license to them if you want. But I don't have any real samples. 

You could use ffmpeg to cut out a sample from a book, but I haven't tried it:

``` 
ffmpeg -ss 0 -i "original.mp3"  -t 10 "new.mp3"
```

**Comment by feldegast** [comment]
thnk you, they were able to find example files
