### ISSUE TITLE
Problems with multiple stages of OpenAudible with low speed connection

### ISSUE THREAD

**Issue by oboe45** [openaudible/openaudible#946]
I was sitting in our front yard, the net connection was stable and adequate for access via Google Browser, Google Mail and all of the apps I usually use, but definitely a bit slow.  I loaded Openaudible - Apple Mac with latest OS and updates - the load took a long time and the loaded app was unresponsive. I killed at and loaded agin - this time it was responsive, I did a scan using the app, it seemed to complete, showed me 1 file to download (as expected) - the download however did not start so, I killed the App, again, reloaded and it started to download immdiately - from the feedback, i could see that the download was a lillte slower than usual, but it seemed to complete but once again would not start the conversion to M4B.  I killed the app, restarted and the conversion began - very slow and seemed to complete but did not proceed to generate the web page.  Restarted and again the web page gen started and completed.  I have the preferences set to do everything in sequence without intervention, but each intermeidate step required a restart.   Just for the hell of it, I deleted the file downloded and converted and ran the app again, this time inside where net access is faster - it worked perfectly without  any manual intervention.   Is it normal for the app to just go to sleep on slow access?  it remained connected, just a bit slow.

**Comment by openaudible** [comment]
Not a known issue.. Never been reported. Can you run "top" or some kind of process monitor to see if its CPU, Disk or network that is slow? Also you can see if another app is using resources. Lastly, are you on M1 mac or Intel?

**Comment by oboe45** [comment]
Intel Mac.  Will close this since it was completely out of the blue, and I
cant reproduce the problem without sitting outside on a very hot evening!
The app rarely lets me down, and the inside rerun worked perfectly - I was
just interested to see if this was a known behaviour.

**Comment by openaudible** [comment]
Never heard of it before. It shouldn't do anything differently.. as downloads should run in the background and shouldn't require more "CPU" to handle than a fast network connection.. Appreciate the report and feel free to post more if you discover anything.
