### ISSUE TITLE
library sync just reads first page over and over

### ISSUE THREAD

**Issue by aljex** [openaudible/openaudible#95]
This issue already exists, and a requested test was performed and delivered weeks ago, but the original issue was closed almost immediately after I promised to do the requested test, and I just suspect that it's simply invisible or ignored now because it's "closed". I'm not demanding any sort of action, just trying to follow through with the original issue. If I could have re-opened that issue instead of making this clutter I would have. If I could pm the developer somehow instead of this I would have. Sorry.

https://github.com/openaudible/openaudible/issues/86

**Comment by openaudible** [comment]
Hi Alex, I will re-opened #86 and am closing this ticket. Will try to figure out your issue.
