### ISSUE TITLE
issues logging into audible

### ISSUE THREAD

**Issue by RyuushinHayashi** [openaudible/openaudible#952]
keeps failing and asking for password

**Comment by openaudible** [comment]
Is your username an email or and old one without an @ symbol?
If old, be sure to check the legacy login checkbox. Also make sure your region is correct.
Make sure you can log into your audible account with your expected credentials.
If that fails, send a bug report from the Help menu.

**Comment by RyuushinHayashi** [comment]
Probably problem with the internet earlier. I can login nowSent from my Huawei phone-------- Original message --------From: openaudible ***@***.***>Date: Thu, 26 May 2022, 00:36To: openaudible/openaudible ***@***.***>Cc: RyuushinHayashi ***@***.***>, Author ***@***.***>Subject: Re: [openaudible/openaudible] issues logging into audible (Issue #952)
Is your username an email or and old one without an @ symbol?
If old, be sure to check the legacy login checkbox. Also make sure your region is correct.
Make sure you can log into your audible account with your expected credentials.
If that fails, send a bug report from the Help menu.
