### ISSUE TITLE
Issues opening program

### ISSUE THREAD

**Issue by SpasticTransplant** [openaudible/openaudible#953]
When I try to open the program I get this.
![screenshot](https://user-images.githubusercontent.com/106718826/171542160-29aaa2f0-9307-492a-93a4-ad8443414c87.jpg)

**Comment by openaudible** [comment]
We've been trying to track down that error for a while, so appreciate the report. (We recently added the full long error message you found.) 

You have a faulty windows.json file.  If you can delete that file from your OpenAudible directory  you should be able to start the program. (But perhaps something strange is also happening during startup that causes the window preferences to be corrupt...)

In any case, the next version will handle that better. 

You can also run from the command line using the debug_linux.sh to get better error messages if you're having problems starting the application.

**Comment by SpasticTransplant** [comment]
Thank you for the prompt response, deleting that json file fixed my issue.
