### ISSUE TITLE
Found dialogue that does not use Dark Mode, Cancelled dialogue

### ISSUE THREAD

**Issue by feldegast** [openaudible/openaudible#954]
Ver 3.5.3
Dialogue title = Canceled
text = Operation was cancelled

this is the only dialogue i have seen in weeks that is not using dark mode, the rest of the app is in dark mode

**Comment by openaudible** [comment]
Thank you! Fixed for next release. Appreciate these reports.

**Comment by openaudible** [comment]
Fixed in latest beta. Cheers.
https://openaudible.org/beta

**Comment by feldegast** [comment]
small note, BiglyBT uses SWT but the app title bar is black unlike this app in dark mode..... I note in their GIT...maybe they have a solution?

[Bit more dark mode Win hackery for recent SWT (and therefore Java 11+)](https://github.com/BiglySoftware/BiglyBT/commit/67bf6224736cb6b075728de8242ca710d96f0cfb)
