### ISSUE TITLE
fatal error when starting the program

### ISSUE THREAD

**Issue by Mauro2107** [openaudible/openaudible#955]
I installed the latest version (3.5.5) and purchased the license last week.
Everything worked fine, download synchronization and conversion.
Today I start the program but it crashes right away and I can't see any error windows.
I attach log:

#
# A fatal error has been detected by the Java Runtime Environment:
#
#  EXCEPTION_ACCESS_VIOLATION (0xc0000005) at pc=0x00007ff8222abc7b, pid=13260, tid=16936
#
# JRE version: OpenJDK Runtime Environment Temurin-18.0.1+10 (18.0.1+10) (build 18.0.1+10)
# Java VM: OpenJDK 64-Bit Server VM Temurin-18.0.1+10 (18.0.1+10, mixed mode, tiered, compressed oops, compressed class ptrs, g1 gc, windows-amd64)
# Problematic frame:
# C  [ieframe.dll+0x25bc7b]
#
# No core dump will be written. Minidumps are not enabled by default on client versions of Windows
#

waiting for solution

Thank you
Mauro

**Comment by openaudible** [comment]
That is a new one. Is this windows N by any chance?

It looks like a problem loading the internal browser widget used to render the book info and do web pages. A few things to try:

1. Try disabling your anti-virus app or tell it that OpenAudible is "OK to run" (each anti-virus app has a way to do this.)
2. There is a beta with some browser changes: https://openaudible.org/beta
3. With the beta, you can edit OpenAudible/settings.json with a text editor and manually change the browser type to either "" (default), edge, ie, or chromium. Setting to "edge" is probably a good first thing to try.
4. Downgrade to an earlier version https://github.com/openaudible/openaudible/releases

Let us know..

**Comment by openaudible** [comment]
If you can try the latest 3.5.6 and let me know if this is fixed. Re-open if needed.
