### ISSUE TITLE
Moving OpenAudible to New PC

### ISSUE THREAD

**Issue by Nick4C** [openaudible/openaudible#957]
I have updated my desktop and have a very large collection that I backup with OpenAudible.  Is there a preferred method of moving my backups to my new installation with out having to download and convert all my books all over again?

**Comment by openaudible** [comment]
The preferred method is just to copy the settings and books directory over to the new PC and launch OpenAudible. If it doesn't find your books, look at the preferences on both machines and either change the location of the books directory... or move it to the "expected" location.
