### ISSUE TITLE
Unable to convert aax to mp3 (via OpenAudible Premium)?

### ISSUE THREAD

**Issue by brennanfife** [openaudible/openaudible#961]
Hello,

Recently purchased the premium version of OpenAudible so I could download Audible files to my mp3 for my race tomorrow. When I drag the file over however into OpenAudible, I don't see the option to convert to mp3 🧐. Any idea why I am not seeing the option to convert to mp3? The OS I am running is an M1 mac btw.

<img width="814" alt="Screen Shot 2022-06-16 at 12 41 10 PM" src="https://user-images.githubusercontent.com/31396350/174151441-c2a92d96-2bc8-439c-882b-baac8ce1bb47.png">

**Comment by openaudible** [comment]
Oh, it was converted to m4b, which should play on most players. To convert to mp3, change the preferences settings to output format mp3. Then it will be available.
