### ISSUE TITLE
Permission Denied for a custom library directory on Ubuntu

### ISSUE THREAD

**Issue by appmu** [openaudible/openaudible#963]
Hello,

I tried to specify a custom directory path for the library and now OpenAudible on Ubuntu doesn't start.

![image](https://user-images.githubusercontent.com/107863298/174612006-5b4ace32-cac6-4abd-827a-ffcaf95be008.png)

I'm doing this on a VirtualBox Ubuntu guest machine on a Windows host. When I tried to set a path of a network shared folder for the library, it first said "Permission Denied" but it let me select the folder so I selected it. 
![image](https://user-images.githubusercontent.com/107863298/174613030-70d31e55-8d1a-4ef3-bd01-58a7aaf8b39d.png)

![image](https://user-images.githubusercontent.com/107863298/174612970-631ab72c-1ba1-499e-9364-161440c8f15a.png)

The program said it needs to restart and immediately shut down. Then after that, the error shown in the first image keeps popping up and the program does not even start. 

I'm guessing it might be solved by adding a user responsible for running OpenAudible to the user group of the directory owner of the shared folder, in this case, `vboxsf`, like doing the following command.

```
sudo adduser $USER vboxsf
```

Any help would be greatly appreciated.

**Comment by openaudible** [comment]
Hmm. It does seem like a permission error. The app tries to write a test file to the dir named. It should be read/writable by the same user that runs the app. You could definitely try making the change… or even writable to all users. Not totally sure since it is a network share. Proceed with caution!

**Comment by appmu** [comment]
@openaudible Could you try to reproduce it? This is a legitimate use case. I don't want to save massive downloaded data to the virtual machine hard drive whose resource is limited. This avoids the situation to repeatedly manually copy some giga byte files. What I want to achieve is to run OpenAudible on a virtual machine and store converted audio files to a network shared folder and play them from different devices.

Firefox safely allows to set a download folder for the network shared folder which caused the problem with OpenAudible so I suppose this can be solved from the program side. 

The process owner of the running program of OpenAudible (which is named java) is the login user. I checked that from System Monitor by searching with the keyword `openaudible` and checking the property. And the login user is properly added to the user group (`vboxsf`) of the network shared folder.

OpenAudible: 3.5.3
Virtual Machine: Ubuntu 22.04 LTS 64bit
Host: Windows 10

**Comment by openaudible** [comment]
We test on network shares all the time. 

Make sure you can create and delete files at the path from the command line both in windows and Linux. 

Make sure the file path is correct and has the correct case sensitive name. Windows hosts can be tricky. 

I will add a check to future versions to check the new library path is read writable. So the error would prevent setting it to an unwritable share. 

You can run in debug mode by running the included debug_linux.sh script— perhaps you should see the full startup error. 

Finally, for Windows hosts, you can try using the windows version of OpenAudible. Well tested and better UI, better performance.

**Comment by openaudible** [comment]
I've added a check to make sure any newly selected file path is writable. If it isn't, an error message will be displayed. 
Should just be a configuration of permissions somewhere. Good luck.
