### ISSUE TITLE
Ignored books aren't saved when the prgram crashes

### ISSUE THREAD

**Issue by appmu** [openaudible/openaudible#966]
I mark converted books as ignored but when the program crashes, those ignored items become un-ingored after restating the program. 

As the program often crashes, it would be great if ignored items are saved properly when marked.

OpenAudible: 3.5.3
Ubuntu 22.04 LTS 64bit

**Comment by openaudible** [comment]
Why is the app crashing?!
I can save more frequently.. but don’t like the idea of bugs.

**Comment by appmu** [comment]
> Why is the app crashing?!

@openaudible Not sure. The program just keep crashing after running for a while. It could be [this](https://github.com/openaudible/openaudible/issues/873). You can try reproducing it on a virtual Ubuntu machine (Ubuntu 22.04 4GB memory 4CPU OpenAudible 3.5.3) by adding and queuing more than 500 books. 

Please keep in mind that this topic is not about bugs. This issue can be simply solved by saving the list when the user marks an item as ignored.

**Comment by openaudible** [comment]
Will fix in next release. 

If you can run using the command line devug_linux.sh you’ll be able to capture any crash errors. Copy and paste the error and submit a bug report if you can. 

Thanks for the report.
