### ISSUE TITLE
An option to delete AAX files after converting 

### ISSUE THREAD

**Issue by appmu** [openaudible/openaudible#967]
I run OpenAudible on a virtual machine which has a limited hard disk capacity and there is an issue with setting a network drive for the library path (https://github.com/openaudible/openaudible/issues/963) on Ubuntu. So I want to delete aax files which are taking too much disk space after successfully converting into an audio file (mp3 or m4b).

Currently, I have to manually delete them repeatedly and mark those books as ignored. But this is cumbersome especially when there are hundreds of books.

So it would be great if there is an option to delete only aax files after converting them to audio files. 

Thanks for your consideration.

**Comment by openaudible** [comment]
You should be able to delete the aax files after conversion. Ignoring unnecessary. They should show up green and won’t be downloaded if already converted.

**Comment by openaudible** [comment]
We are trying to keep the UI clean, so will avoid adding a new preference item. Hard drives are cheap, and OA does work with properly configured network shares.

**Comment by appmu** [comment]
> You should be able to delete the aax files after conversion. Ignoring unnecessary. They should show up green and won’t be downloaded if already converted.

As I said, the virtual machine hard drive resource is limited and I have to move the converted files as well. 

> Hard drives are cheap,

Don't assume all the users can attach a hard drive only for a virtual machine. And my use case is to access from different devices across the local network.

> OA does work with properly configured network shares.

No. It's not working on Ubuntu guest virtual machines. Please test your application thoroughly.

**Comment by ohare93** [comment]
This is a quick win, I don't see a reason not to add this feature. If you think it clutters up the preference page then add it under some Advanced expander that is minimised to begin with.

When doing a full download for all your audiobooks it can take A LOT of space. Not deleting the books by default makes it take twice as much. Interrupting the auto download for this and having to manually fix it (when it is not clear if we can indeed just delete the aax files) is annoying, without even going into how annoying it is for your harddrive to run out of memory. On some systems that means a crash.

**Comment by openaudible** [comment]
This has been added to the latest beta.
https://openaudible.org/beta

**Comment by rnbwpnt** [comment]
Thank you for changing your stance on this. I much appreciate it.

**Comment by ohare93** [comment]
Same here 👍

**Comment by openaudible** [comment]
It makes good sense. Will go in next version. Thank you for the feature suggestions.

**Comment by Robster100** [comment]
MANY thanks for this, beta is running great and asked to delete my 406 book tax library, very user friendly and suddenly a lot of space back!

**Comment by openaudible** [comment]
Finalized in version 3.6.2. Thanks for the testing and feedback everyone.

**Comment by appmu** [comment]
Superb!
