### ISSUE TITLE
[Ventura] [Crash] OpenAudible OSX (x86_64) crashes when attempting to login to audible 

### ISSUE THREAD

**Issue by wolfspyre** [openaudible/openaudible#968]
SSIA. Fresh install. Open app. Attempt to login to audible. App crashes immediately.
OpenAudible version: 3.5.6
Hardware: iMac Retina 5K, 27-inch, 2017
OS: 13.0 Beta (22A5286j)

Need anything else?

**Comment by openaudible** [comment]
Don't know much about the OS beta. 
Could you run from terminal and copy and paste the error (remove any personal details, URL's, or tokens)

Open terminal.

```
cd /Applications/OpenAudible.app/Contents/Resources/app
./debug_mac.sh
```

**Comment by wolfspyre** [comment]
Strangely enough, running the debug version allowed me to get over the hurdle I was hitting. Everything's working as expected now. 

¯\_(ツ)_/¯

I do have a few error files from the time it was crashing. is there a direct path to give them to you?

**Comment by openaudible** [comment]
Sure, send to openaudible at email dot tg. 
Will keep an eye out for more reports.. but maybe just a beta glitch that will be resolved. Thanks!

**Comment by openaudible** [comment]
New beta seems to have fixed it for the short term by using the JxBrowser library.

OpenAudible Beta Version 3.6.2.5
https://openaudible.org/beta
