### ISSUE TITLE
Refund needed as Openaudible does not work with Audible UK

### ISSUE THREAD

**Issue by almunday** [openaudible/openaudible#969]
I have lost my registration code email from Fastsping and so cannot access your website to retrieve my code.  Apart from that Openaudible UK does not login to my Audible account in spite of my checking that I am using my correct login details, so I need a refund please.

A copy of my payment details from Paypal is enclosed.

[openaudible payment details paypal.com-.pdf](https://github.com/openaudible/openaudible/files/8983718/openaudible.payment.details.paypal.com-.pdf)

**Comment by openaudible** [comment]
Drop an email to openaudible at email dot tg. 
havent had any reports of problems with audible Uk. Maybe try logging in from a fresh browser? But will refund since it isn’t working.
