### ISSUE TITLE
Website down (No update check possible)

### ISSUE THREAD

**Issue by BlockLabTV** [openaudible/openaudible#97]
I think you are already aware of this, but at the moment (at least) I can't reach your website http://openaudible.org/ . Should be fixed to re-enable updating.

![image](https://user-images.githubusercontent.com/29959150/53199367-34d87d80-361f-11e9-87c6-0c5c82e76909.png)
![image](https://user-images.githubusercontent.com/29959150/53199397-4457c680-361f-11e9-8bbf-a0435c919c8c.png)

**Comment by openaudible** [comment]
Thanks, putting money into my hosting account. Should be online soon.

**Comment by openaudible** [comment]
DNS records were wiped and are being restored.
