### ISSUE TITLE
"Low cost upgrade"

### ISSUE THREAD

**Issue by selsAT** [openaudible/openaudible#971]
I am bit surprised that the "Low cost upgrade" option for old license holders means that i do get 1€ 
rebate on the 15,95€ license price.
That is essentially a new license that you charge.

**Comment by openaudible** [comment]
It looks like we had the price on OpenAudible set wrong for people paying in Euros. It seems like the parity between dollars and euros has changed.

In any case, the current price is $18.95 for the full product and $11.95 for the (always optional) upgrade. 

Thanks for the heads up.
