### ISSUE TITLE
Local Metadata enhancement?

### ISSUE THREAD

**Issue by wolfspyre** [openaudible/openaudible#972]
Loving OpenAudible.

I'm noticing that openaudible doesn't seem to have some metadata constructs I'd like to see....
specifically:

- per book:
  - Audible-side:
    - audible-side-collections
    - audible-account-scoped-collections
    - audible-account-listencount
    - audible-account-scoped-listen-count
    - audible-account-scoped-rating
    - audible-account-scoped-rating-date
    - audible-account-scoped-review
    - audible-account-scoped-review-date
  - OpenAudible-scoped:
    - web-inclusion
    - listencount
    - conversion-scoped-metadata
    - datetime-converted
    - conversion-details
    - keep-aax?
    - bitrate/downsample
    - preferred-playback-speed
    - average-playback-speed
- OpenAudible-scoped:
   - default-playback-speed
   - conversion-behavior-preferences
   - collections/groups
   - adding-removing titles/series/authors/etc to the web export
   - scoping the web export to exclude/include cohorts defined with the above

this is just a quick off-the-cuff list.... 

Is there someplace this stuff has been discussed previously that I can educate myself before making silly suggestions? :)

**Comment by openaudible** [comment]
You're treading in uncharted territory.  We're trying to keep OA simple and not overwhelm the user with too many options or exported data. Back up your purchases is about all we promise to do well.  We do make a number of API calls that might get some of this information, but we ignore most of it. At some point we might work to get better web interfaces, for instance using audiobookshelf or allowing people to submit their own web designs.. and if that takes off we'll certainly consider more advanced details in the books.json file.

**Comment by openaudible** [comment]
I'm going to close and mark as a "feature request". Thank you for the suggestion.

**Comment by wolfspyre** [comment]
Would it be reasonable, at least, to have the option of a 'per collection' json file? I'm fairly confident that it'd be pretty simple to ask audible's API for 'what collections does the user have?' and then 'for collection in ...; do gettitlelist()' or something... 

that way, all existing functionality remains exactly the same, no changes to anything else necessary... you're just *ALSO* able to create additional datafiles which represent a subset of one's library. 

that might be an easier mechanism to use to facilitate subgroups/etc.... books.json becomes the 'kitchen sink' datafile, but addtional datafiles with slices of the kitchen sink content could be processed identically to the existing file simply by being given the alternate datafile.... y'know?
