### ISSUE TITLE
Login Credentials not accepted in Audible handshake

### ISSUE THREAD

**Issue by Kristina-la** [openaudible/openaudible#973]
My Audible login credentials are not being accepted for synchronizing/downloading between OpenAudible and Audible.  My credentials are accepted when I login directly to Audible. Can you help me?

**Comment by openaudible** [comment]
Which region are you in? Is your log in username an email address? Any errors in the console (do not copy and paste any tokens or personal details). No other reports, so try again?

**Comment by Kristina-la** [comment]
Mark it “resolved”!  I tried again, and for some reason it worked. 17th time is the charm?  Thank you for your response.

**Comment by openaudible** [comment]
Strange!
