### ISSUE TITLE
Problem viewing main screen

### ISSUE THREAD

**Issue by IamMaris** [openaudible/openaudible#974]
Today when I opened OpenAudible, the Library Status column was so narrow I could not see anything but the titles and 2 characters of the data .  I could not find any way to resize the Library Status/Audiobook Info columns to fix the display. 

Last time I used OA, three days ago, the view was OK.

**Comment by openaudible** [comment]
Strange. OA is supposed to set the width of a reasonable amount of text. 
Try expanding the window, then close and restart the app. There is also a "windows.json" file that can be deleted.

**Comment by IamMaris** [comment]
Thanks for the response. I also restarted my computer and that seemed to
fix it. I closed and opened it a couple more times and it worked, so must
have just been a temporary glitch.

Maris
