### ISSUE TITLE
Audible Japanese version cannot be downloaded.

### ISSUE THREAD

**Issue by hidetok0520** [openaudible/openaudible#979]
Audible Japanese version cannot be downloaded.
I used to be able to download it, but suddenly I can't download it.
Thank you for your support.

**Comment by openaudible** [comment]
Try the beta: https://openaudible.org/beta

please let us know if that works.

**Comment by hidetok0520** [comment]
Thank you.

**Comment by Cinnamoni** [comment]
I can confirm that OpenAudible Beta Version 3.5.6.1 still throws Service Unavailable error.

**Comment by openaudible** [comment]
Can you try to download, then send a bug report from the About menu? We'll see if we can figure out what happened.

**Comment by openaudible** [comment]
Thank you for the report. That helped. Try the beta 2. 

https://openaudible.org/beta

**Comment by openaudible** [comment]
Fixed in 3.5.7
