### ISSUE TITLE
On opening release 3.5.7, most fields in the Library Status column are blank

### ISSUE THREAD

**Issue by blurfl** [openaudible/openaudible#981]
On opening, all fields in the Library Status column other than Connected and Region are blank. Quitting before connecting to Audible creates a 2-byte books.json file, removing the previous library information. Not sure whether the diagnostics and console logs are sent with this report, but I have them available if needed.
This was previously reported in a discussion under Issue #978:   https://github.com/openaudible/openaudible/issues/978#issuecomment-1192135285

**Comment by openaudible** [comment]
Yes, a bug report would be helpful. I guess restore the books.json (and other config files) and restart the app...

Sounds like OA isn't finding your library. But it could be something else during the loading process. Are you using a network share that might be offline or have unusual permissions?

Thanks for your help!

**Comment by blurfl** [comment]
I've filed a bug report from within the app, does that bring the necessary info?

**Comment by openaudible** [comment]
This might be because of a problem where the previous session wasn't saving properly. I'll look at the bug report, thank you.
In the mean time, this beta is better about saving:
https://openaudible.org/beta

**Comment by blurfl** [comment]
The issue persists. I've tried on Mac M1 and Mac intel machines, both show java.lang.NullPointerException errors in the console.

**Comment by openaudible** [comment]
Hey thank you for the bug report which had the NullPointerException bug you mentioned. 
Uploaded a beta 2. Thank you and let me know if that helps.
https://openaudible.org/beta

**Comment by blurfl** [comment]
Glad to help, version 3.5.7.2beta corrects the issue.
