### ISSUE TITLE
 I can no longer save "ignored books"

### ISSUE THREAD

**Issue by hidetok0520** [openaudible/openaudible#982]
To Support
Thank you for the version upgrade. Thanks to you, the download was successful.
However, I can no longer save "ignored books".
I would appreciate it if you could improve it.

**Comment by Cinnamoni** [comment]
I have the same error. This is from the log:
[log.txt](https://github.com/openaudible/openaudible/files/9189351/log.txt)

**Comment by openaudible** [comment]
A new beta saves more frequently. Let me know.
https://openaudible.org/beta

**Comment by openaudible** [comment]
Should be fixed in 3.5.8.
