### ISSUE TITLE
Bug report does not work within OpenAudible

### ISSUE THREAD

**Issue by jhaug** [openaudible/openaudible#983]
Filled out form, excepting the github issue number.    Click on Submit, and a window pops up with the github issues list.   Clicking anything on the page makes the window close and return to the issue submission form.   Rinse, repeat, bang head on wall, rinse, repeat...

**Comment by jhaug** [comment]
Accepted bug report only if I included a github issue number.   Suggest removing the verbiage "Include the github issue number (if available)", or correct submission dialog such that it will work without the issue number.   Tried several times initially without an issue number.    Video available at https://haugtech.com/tmp/openaudible_bugreport.mp4

**Comment by openaudible** [comment]
Confirmed: Issue number is required error should show an error dialog, not open a web browser.

The issue number is required, although it can be made up. Just didn't want simple tech support questions or feature requests in the bug report database without some kind of discussion.

**Comment by openaudible** [comment]
Fixed in beta 2. Thank you!
