### ISSUE TITLE
Database no longer saved, requires full resync at every launch now?

### ISSUE THREAD

**Issue by jhaug** [openaudible/openaudible#984]
OpenAudible used to keep the database information each time I opened it.   I just finished going through after a full library resync, and renaming each file to include author's name, where the system showed the right icon for the MP3 being in-place, the filename stored as I renamed it, etc... Then it got stuck in downloading and I selected to Quit from the menu on top (not force quit).   Opened up completely empty, required a full resync to get files, and in looking through the folder, there are various duplicates and lots of MP3s in place that the system no longer detects properly presumably because I renamed it with the console but it didn't store.   So I'll go through AGAIN and rename all 230 books and hope it will save, on second thought I may just try one or two because I doubt it will save and persist.   Please fix this so the customized aspects are retained and not reset (like a new user) each time it opens.   macOS Monterey.  Regards, Josh

**Comment by jhaug** [comment]
Also, despite all of the metadata being within the MP3 files and AAX files present in the default locations, performing a "Refresh Files" doesn't remedy all of the disconnects.  See the metadata for the MP3 side-by-side with the book info window.     You'd think with the plethora of metadata including the product_id and ASIN numbers, OA would be able to build a link with ease between the AAX file, MP3 file, and the book record -- even if the files were named consecutively incrementing numbers ONLY.    Please remove these links once you view the videos because I didn't filter them at all, not that there's anything overly sensitive.. I guess I can remove the file on the webserver also.    Anyway, thanks for looking to see what's going on.   Hopefully my bug report will have submitted some technical data that may be of help. --Josh
https://haugtech.com/tmp/openaudible_chaosmode.mp4

**Comment by jhaug** [comment]
https://haugtech.com/tmp/openaudible_log.mp4
Bizarre, because log appears to be parsing all of the files, looking for the metadata, but obviously is incorrect in stating it's not there.   Using the MediaInfo app to pull the data.    Stranger still, is why the saved books database would have gotten lost/corrupted at all, because a good hundred+ files were showing with the green-dot, for the past year easy.   I'd just pop in and convert any new ones I got so I had them.   Anyway, still thankful for the utility but it's more tool and less utility in this mode...

**Comment by jhaug** [comment]
OK.   So here's the problem here, it would appear.   Running the shell command shown for ffmpeg metadata pull for the Wayne Dyer book results in
/Applications/OpenAudible.app/Contents/Resources/app/bin/mac/ffmpeg -i "/Users/User/Library/OpenAudible/aax/Excuses Begone! (by Dr. Wayne W. Dyer).AAX" -f ffmetadata - 
ffmpeg version N-104674-gf5e74e8d48-tessus  https://evermeet.cx/ffmpeg/  Copyright (c) 2000-2021 the FFmpeg developers
  built with Apple clang version 11.0.0 (clang-1100.0.33.17)
  configuration: --cc=/usr/bin/clang --prefix=/opt/ffmpeg --extra-version=tessus --enable-libmp3lame --pkg-config-flags=--static --disable-securetransport --disable-ffplay
  libavutil      57.  9.101 / 57.  9.101
  libavcodec     59. 13.101 / 59. 13.101
  libavformat    59.  9.102 / 59.  9.102
  libavdevice    59.  0.101 / 59.  0.101
  libavfilter     8. 17.100 /  8. 17.100
  libswscale      6.  1.100 /  6.  1.100
  libswresample   4.  0.100 /  4.  0.100
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7faa0a104d00] [aax] file checksum == 2c96d737ef96fb9952189c82050fe09811def67f
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7faa0a104d00] [aax] activation_bytes option is missing!
[mov,mp4,m4a,3gp,3g2,mj2 @ 0x7faa0a104d00] stream 0, timescale not set
[aac @ 0x7faa09704e00] channel element 3.7 is not allocated
Input #0, mov,mp4,m4a,3gp,3g2,mj2, from '/Users/User/Library/OpenAudible/aax/Excuses Begone! (by Dr. Wayne W. Dyer).AAX':
  Metadata:
    major_brand     : aax 
    minor_version   : 1
    compatible_brands: aax M4B mp42isom
    creation_time   : 2022-07-27T07:10:35.000000Z
    comment         : Chapter 21
    title           : Excuses Begone!: How to Change Lifelong, Self-Defeating Thinking Habits
    artist          : Dr. Wayne W. Dyer
    album_artist    : Dr. Wayne W. Dyer
    album           : Excuses Begone!: How to Change Lifelong, Self-Defeating Thinking Habits
    genre           : Audiobook
    copyright       : ©2009 Hay House, Inc. (P)2009 Hay House, Inc.
    date            : 2009
  Duration: 07:20:43.19, start: 0.000000, bitrate: 64 kb/s
  Chapters:
    Chapter #0:0: start 0.000000, end 265.450522
      Metadata:
        title           : Chapter 1
    Chapter #0:1: start 265.450522, end 2013.588027
      Metadata:
        title           : Chapter 2
    Chapter #0:2: start 2013.588027, end 3736.462222
      Metadata:
        title           : Chapter 3
    Chapter #0:3: start 3736.462222, end 5062.693152
      Metadata:
        title           : Chapter 4
    Chapter #0:4: start 5062.693152, end 6040.903401
      Metadata:
        title           : Chapter 5
    Chapter #0:5: start 6040.903401, end 7378.279909
      Metadata:
        title           : Chapter 6
    Chapter #0:6: start 7378.279909, end 8407.527619
      Metadata:
        title           : Chapter 7
    Chapter #0:7: start 8407.527619, end 9463.710476
      Metadata:
        title           : Chapter 8
    Chapter #0:8: start 9463.710476, end 10491.518549
      Metadata:
        title           : Chapter 9
    Chapter #0:9: start 10491.518549, end 11631.339683
      Metadata:
        title           : Chapter 10
    Chapter #0:10: start 11631.339683, end 12994.165261
      Metadata:
        title           : Chapter 11
    Chapter #0:11: start 12994.165261, end 14157.206349
      Metadata:
        title           : Chapter 12
    Chapter #0:12: start 14157.206349, end 15299.303039
      Metadata:
        title           : Chapter 13
    Chapter #0:13: start 15299.303039, end 16853.739683
      Metadata:
        title           : Chapter 14
    Chapter #0:14: start 16853.739683, end 18203.654966
      Metadata:
        title           : Chapter 15
    Chapter #0:15: start 18203.654966, end 19506.758821
      Metadata:
        title           : Chapter 16
    Chapter #0:16: start 19506.758821, end 21086.319456
      Metadata:
        title           : Chapter 17
    Chapter #0:17: start 21086.319456, end 22196.744127
      Metadata:
        title           : Chapter 18
    Chapter #0:18: start 22196.744127, end 23490.374240
      Metadata:
        title           : Chapter 19
    Chapter #0:19: start 23490.374240, end 24883.571519
      Metadata:
        title           : Chapter 20
    Chapter #0:20: start 24883.571519, end 26443.190023
      Metadata:
        title           : Chapter 21
  Stream #0:0[0x1](eng): Audio: aac (LC) (aavd / 0x64766161), 22050 Hz, stereo, fltp, 62 kb/s (default)
    Metadata:
      creation_time   : 2022-07-27T07:10:35.000000Z
      handler_name    : ?Apple Sound Media Handler
      vendor_id       : [0][0][0][0]
  Stream #0:1[0x2](eng): Data: bin_data (text / 0x74786574) (default)
    Metadata:
      creation_time   : 2022-07-27T07:10:35.000000Z
      handler_name    : ?Apple Text Media Handler
  Stream #0:2[0x0]: Video: mjpeg (Baseline), yuvj420p(pc, bt470bg/unknown/unknown), 500x500 [SAR 1:1 DAR 1:1], 90k tbr, 90k tbn (attached pic)
;FFMETADATA1
Output #0, ffmetadata, to 'pipe:':
  Metadata:
    major_brand     : aax 
    minor_version   : 1
    compatible_brands: aax M4B mp42isom
    date            : 2009
    comment         : Chapter 21
    title           : Excuses Begone!: How to Change Lifelong, Self-Defeating Thinking Habits
    artist          : Dr. Wayne W. Dyer
    album_artist    : Dr. Wayne W. Dyer
    album           : Excuses Begone!: How to Change Lifelong, Self-Defeating Thinking Habits
    genre           : Audiobook
    copyright       : ©2009 Hay House, Inc. (P)2009 Hay House, Inc.
    encoder         : Lavf59.9.102
  Chapters:
    Chapter #0:0: start 0.000000, end 265.450522
      Metadata:
        title           : Chapter 1
    Chapter #0:1: start 265.450522, end 2013.588027
      Metadata:
        title           : Chapter 2
    Chapter #0:2: start 2013.588027, end 3736.462222
      Metadata:
        title           : Chapter 3
    Chapter #0:3: start 3736.462222, end 5062.693152
      Metadata:
        title           : Chapter 4
    Chapter #0:4: start 5062.693152, end 6040.903401
      Metadata:
        title           : Chapter 5
    Chapter #0:5: start 6040.903401, end 7378.279909
      Metadata:
        title           : Chapter 6
    Chapter #0:6: start 7378.279909, end 8407.527619
      Metadata:
        title           : Chapter 7
    Chapter #0:7: start 8407.527619, end 9463.710476
      Metadata:
        title           : Chapter 8
    Chapter #0:8: start 9463.710476, end 10491.518549
      Metadata:
        title           : Chapter 9
    Chapter #0:9: start 10491.518549, end 11631.339683
      Metadata:
        title           : Chapter 10
    Chapter #0:10: start 11631.339683, end 12994.165261
      Metadata:
        title           : Chapter 11
    Chapter #0:11: start 12994.165261, end 14157.206349
      Metadata:
        title           : Chapter 12
    Chapter #0:12: start 14157.206349, end 15299.303039
      Metadata:
        title           : Chapter 13
    Chapter #0:13: start 15299.303039, end 16853.739683
      Metadata:
        title           : Chapter 14
    Chapter #0:14: start 16853.739683, end 18203.654966
      Metadata:
        title           : Chapter 15
    Chapter #0:15: start 18203.654966, end 19506.758821
      Metadata:
        title           : Chapter 16
    Chapter #0:16: start 19506.758821, end 21086.319456
      Metadata:
        title           : Chapter 17
    Chapter #0:17: start 21086.319456, end 22196.744127
      Metadata:
        title           : Chapter 18
    Chapter #0:18: start 22196.744127, end 23490.374240
      Metadata:
        title           : Chapter 19
    Chapter #0:19: start 23490.374240, end 24883.571519
      Metadata:
        title           : Chapter 20
    Chapter #0:20: start 24883.571519, end 26443.190023
      Metadata:
        title           : Chapter 21
Stream mapping:
Press [q] to stop, [?] for help
major_brand=aax 
minor_version=1
compatible_brands=aax M4B mp42isom
date=2009
comment=Chapter 21
title=Excuses Begone!: How to Change Lifelong, Self-Defeating Thinking Habits
artist=Dr. Wayne W. Dyer
album_artist=Dr. Wayne W. Dyer
album=Excuses Begone!: How to Change Lifelong, Self-Defeating Thinking Habits
genre=Audiobook
copyright=©2009 Hay House, Inc. (P)2009 Hay House, Inc.
encoder=Lavf59.9.102
[CHAPTER]
TIMEBASE=1/22050
START=0
END=5853184
title=Chapter 1
[CHAPTER]
TIMEBASE=1/22050
START=5853184
END=44399616
title=Chapter 2
[CHAPTER]
TIMEBASE=1/22050
START=44399616
END=82388992
title=Chapter 3
[CHAPTER]
TIMEBASE=1/22050
START=82388992
END=111632384
title=Chapter 4
[CHAPTER]
TIMEBASE=1/22050
START=111632384
END=133201920
title=Chapter 5
[CHAPTER]
TIMEBASE=1/22050
START=133201920
END=162691072
title=Chapter 6
[CHAPTER]
TIMEBASE=1/22050
START=162691072
END=185385984
title=Chapter 7
[CHAPTER]
TIMEBASE=1/22050
START=185385984
END=208674816
title=Chapter 8
[CHAPTER]
TIMEBASE=1/22050
START=208674816
END=231337984
title=Chapter 9
[CHAPTER]
TIMEBASE=1/22050
START=231337984
END=256471040
title=Chapter 10
[CHAPTER]
TIMEBASE=1/22050
START=256471040
END=286521344
title=Chapter 11
[CHAPTER]
TIMEBASE=1/22050
START=286521344
END=312166400
title=Chapter 12
[CHAPTER]
TIMEBASE=1/22050
START=312166400
END=337349632
title=Chapter 13
[CHAPTER]
TIMEBASE=1/22050
START=337349632
END=371624960
title=Chapter 14
[CHAPTER]
TIMEBASE=1/22050
START=371624960
END=401390592
title=Chapter 15
[CHAPTER]
TIMEBASE=1/22050
START=401390592
END=430124032
title=Chapter 16
[CHAPTER]
TIMEBASE=1/22050
START=430124032
END=464953344
title=Chapter 17
[CHAPTER]
TIMEBASE=1/22050
START=464953344
END=489438208
title=Chapter 18
[CHAPTER]
TIMEBASE=1/22050
START=489438208
END=517962752
title=Chapter 19
[CHAPTER]
TIMEBASE=1/22050
START=517962752
END=548682752
title=Chapter 20
[CHAPTER]
TIMEBASE=1/22050
START=548682752
END=583072340
title=Chapter 21
size=       2kB time=-577014:32:22.77 bitrate=N/A speed=N/A    
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded 

OK.   No ASIN or Product ID showing there.   Date showing 2009.    Take a look at the output when I pull the metadata using exiftool...

 (by Dr. Wayne W. Dyer).AAX'
ExifTool Version Number         : 12.42
File Name                       : Excuses Begone! (by Dr. Wayne W. Dyer).AAX
Directory                       : /Users/User/Library/OpenAudible/aax
File Size                       : 214 MB
File Modification Date/Time     : 2022:07:27 00:11:29-07:00
File Access Date/Time           : 2022:07:27 00:11:29-07:00
File Inode Change Date/Time     : 2022:07:27 01:08:53-07:00
File Permissions                : -rw-r--r--
File Type                       : AAX
File Type Extension             : aax
MIME Type                       : audio/vnd.audible.aax
Major Brand                     : Audible Enhanced Audiobook (.AAX)
Minor Version                   : 0.0.1
Compatible Brands               : aax , M4B , mp42, isom
Movie Header Version            : 0
Create Date                     : 2022:07:27 07:10:35
Modify Date                     : 2022:07:27 07:10:35
Time Scale                      : 600
Duration                        : 7:20:43
Preferred Rate                  : 1
Preferred Volume                : 0.00%
Preview Time                    : 0 s
Preview Duration                : 0 s
Poster Time                     : 0 s
Selection Time                  : 0 s
Selection Duration              : 0 s
Current Time                    : 0 s
Next Track ID                   : 3
Track Header Version            : 0
Track Create Date               : 2022:07:27 07:10:35
Track Modify Date               : 2022:07:27 07:10:35
Track ID                        : 1
Track Duration                  : 7:20:43
Track Layer                     : 0
Track Volume                    : 100.00%
Chapter List Track ID           : 2
Balance                         : 0
Audio Format                    : aavd
Audio Channels                  : 2
Audio Bits Per Sample           : 16
Audio Sample Rate               : 44100
Matrix Structure                : 1 0 0 0 1 0 0 0 1
Image Width                     : 160
Image Height                    : 160
Media Header Version            : 0
Media Create Date               : 2022:07:27 07:10:35
Media Modify Date               : 2022:07:27 07:10:35
Media Time Scale                : 22050
Media Duration                  : 7:20:43
Media Language Code             : eng
Handler Class                   : Media Handler
Handler Description             : Apple Text Media Handler
Gen Media Version               : 0
Gen Flags                       : 0 0 0
Gen Graphics Mode               : ditherCopy
Gen Op Color                    : 32768 32768 32768
Gen Balance                     : 0
Other Format                    : text
Warning                         : [minor] The ExtractEmbedded option may find more tags in the media data
Comment                         : Chapter 21
Handler Type                    : Metadata
Handler Vendor ID               : Apple
Title                           : Excuses Begone!: How to Change Lifelong, Self-Defeating Thinking Habits
Artist                          : Dr. Wayne W. Dyer
Album Artist                    : Dr. Wayne W. Dyer
Album                           : Excuses Begone!: How to Change Lifelong, Self-Defeating Thinking Habits
Genre                           : Audiobook
Product ID                      : BK_HAYH_000245
Description                     : In Excuses Begone! Dr. Wayne W. Dyer reveals how to change lifelong, self-defeating thinking patterns that prevent you from living at the highest levels of success, happiness, and health. You may know what to think but find it terribly difficult to change thinking habits that have been with you since childhood. This business of changing habituated thinking patterns is really the business of eliminating the same old tired excuses.
Copyright                       : ©2009 Hay House, Inc. (P)2009 Hay House, Inc.
Publisher                       : Hay House
Content Create Date             : 2009
Narrator                        : Dr. Wayne W. Dyer
Product Version                 : 4588521
GUID                            : ABT8W1CAXD7XX
Short Title                     : Excuses Begone!: How to Change Lifelong, Self-Defeating Thinking Habits
Release Date                    : 24-JUN-2009
Cover Art                       : (Binary data 49013 bytes, use -b option to extract)
Media Data Size                 : 211288278
Media Data Offset               : 2545414
Image Size                      : 160x160
Megapixels                      : 0.026
Avg Bitrate                     : 63.9 kbps

Also able to extract most of the same metadata using mediainfo:
iMac-Pro$ mediainfo /tmp/dyer.aax
General
Complete name                            : /tmp/dyer.aax
Format                                   : aax 
Codec ID                                 : aax  (aax /M4B /mp42/isom)
File size                                : 204 MiB
Duration                                 : 7 h 20 min
Overall bit rate mode                    : Constant
Overall bit rate                         : 64.7 kb/s
Album                                    : Excuses Begone!: How to Change Lifelong, Self-Defeating Thinking Habits
Album/Performer                          : Dr. Wayne W. Dyer
Track name                               : Excuses Begone!: How to Change Lifelong, Self-Defeating Thinking Habits
Track_More                               : In Excuses Begone! Dr. Wayne W. Dyer reveals how to change lifelong, self-defeating thinking patterns that prevent you from living at the highest levels of success, happiness, and health. You may know what to think but find it terribly difficult to change thinking habits that have been with you since childhood. This business of changing habituated thinking patterns is really the business of eliminating the same old tired excuses.
Performer                                : Dr. Wayne W. Dyer
Genre                                    : Audiobook
Recorded date                            : 2009
Encoded date                             : UTC 2022-07-27 07:10:35
Tagged date                              : UTC 2022-07-27 07:10:35
Writing library                          : Apple QuickTime
Copyright                                : ?2009 Hay House, Inc. (P)2009 Hay House, Inc.
Cover                                    : Yes
prID                                     : BK_HAYH_000245
pub                                      : Hay House
nrt                                      : Dr. Wayne W. Dyer
CDEK                                     : B002V8LEYK
CDET                                     : ADBL
VERS                                     : 4588521
GUID                                     : ABT8W1CAXD7XX
AACR                                     : CR!RAXYJM6FA92JX97J9ESDDY342XQ0
@sti                                     : Excuses Begone!: How to Change Lifelong, Self-Defeating Thinking Habits
rldt                                     : 24-JUN-2009
atnu                                     : 0

Audio
ID                                       : 1
Format                                   : AAC LC
Format/Info                              : Advanced Audio Codec Low Complexity
Codec ID                                 : aavd-40-2
Duration                                 : 7 h 20 min
Source duration                          : 7 h 20 min
Bit rate mode                            : Constant
Bit rate                                 : 64.0 kb/s
Channel(s)                               : 2 channels
Channel layout                           : L R
Sampling rate                            : 22.05 kHz
Frame rate                               : 21.533 FPS (1024 SPF)
Compression mode                         : Lossy
Stream size                              : 198 MiB (97%)
Source stream size                       : 198 MiB (97%)
Language                                 : English
Encoded date                             : UTC 2022-07-27 07:10:35
Tagged date                              : UTC 2022-07-27 07:10:35
Menus                                    : 2
Errors                                   : Missing ID_END

Menu
ID                                       : 2
Format                                   : Timed Text
Codec ID                                 : text
Duration                                 : 7 h 20 min
Language                                 : English
Encoded date                             : UTC 2022-07-27 07:10:35
Tagged date                              : UTC 2022-07-27 07:10:35
Menu For                                 : 1
Source duration                          : 26443208
Source frame count                       : 21
Source stream size                       : 495
Frame count                              : 21
Stream size                              : 495
00:00:00.000                             : Chapter 1
00:04:25.450                             : Chapter 2
00:33:33.588                             : Chapter 3
01:02:16.462                             : Chapter 4
01:24:22.693                             : Chapter 5
01:40:40.903                             : Chapter 6
02:02:58.279                             : Chapter 7
02:20:07.527                             : Chapter 8
02:37:43.710                             : Chapter 9
02:54:51.518                             : Chapter 10
03:13:51.339                             : Chapter 11
03:36:34.165                             : Chapter 12
03:55:57.206                             : Chapter 13
04:14:59.303                             : Chapter 14
04:40:53.739                             : Chapter 15
05:03:23.654                             : Chapter 16
05:25:06.758                             : Chapter 17
05:51:26.319                             : Chapter 18
06:09:56.744                             : Chapter 19
06:31:30.374                             : Chapter 20
06:54:43.571                             : Chapter 21

So, I'd be leaning toward perhaps an issue with a version of ffmpeg that you moved to?   It shouldn't be related to the file encoding because otherwise my files encoded back in 2020 should associate by means of properly decoded metadata with ffmpeg.     Anyway, that's my going over and above... I'll leave it to you...   (Note, I changed my username to User in several instances, lest it confuse you)

**Comment by openaudible** [comment]
I'm going to spend some time on this report.. Really appreciate it. We do kind of assume that the file names are consistent across all media types-- aax, mp3, m4b, images. 

I do have a beta that saves the book database more frequently... which might address some of the other issues that are open.
https://openaudible.org/beta

**Comment by jhaug** [comment]
Thanks;  also worth noting that I did not perform ANY manual file renames.    All renames took place via OA using the context menu that purportedly renames all assets associated with the title...      I think there are several issues at play here; first is the fact that the database is falling out-of-sync every time, and second that the "File rescan" fails because the ffmpeg tool isn't pulling the metadata.    The metadata is there, as evidenced by the other tools I used...

**Comment by openaudible** [comment]
OK. Posted a new beta. Found a bug affecting the library settings and loading/saving. Feel free to check beta 2.

FYI, for parsing AAX files, we do get the product ID and ASIN using an internal tool that isn't ffmpeg. 

Refresh files _should_ find files that have been renamed using the File Rename dialog. 

When you open OpenAudible, keep an eye on the console (CTRL-E) if you're seeing any bad behavior.. 

https://openaudible.org/beta

**Comment by openaudible** [comment]
Please try 3.5.8. Re-open or let me know if any issues remain.

**Comment by jhaug** [comment]
The database corruption issue seems to be resolved.   Will post a different problem ticket for the failure to refresh properly from existing files.

**Comment by jhaug** [comment]
Thanks.   Important to note here that I did NOT manually rename any of the files.   The only renaming that I did was via OA using the context menu which purportedly renames all assets consistently...
--Josh
