### ISSUE TITLE
'Refresh Files' function does not properly detect files due to ffmpeg

### ISSUE THREAD

**Issue by jhaug** [openaudible/openaudible#985]
As I mentioned within the last issue, viewing the console log during a Refresh Files is very revealing.    Then, from there, I tested the output from the shown console commands meant to dump the metadata within the AAX or MP3 files.    Indeed both ffmpeg and ffprobe output fails to include some critical identifying data.   Namely, ASIN, Product Number, probably others.   I included sample output from other commands which DO show the pertinent data.

Of course, I'm only in the position of needing this function to work because of the database corruption following my using the internal "rename" function.   But, all the same, it should work properly...  at least I'd want it to if it were my code.     I can't remember the reason for moving away from open source, I know I was donating before the switch... Anyway reference my examples from the last issue for more information.    I just ran a quick script against all of my AAX files,  and results are the same in terms of what's missing as in the prior comments on the other issue.
--Josh

**Comment by jhaug** [comment]
I went through and renamed all files back to remove the Author's name which I had added.  There were many variants of the book names in the folders also.   Once I renamed back, and relaunched OA, it detected the books as present.   Then I used the internal "Rename" function, after which the file is renamed back the way I wanted it.   Exited OA, relaunched, still shows as present with the new name.    So I know how to manually fix it, but it's a heck of a lot of time involved in doing so.   Feels like, with all the metadata present, it should be simple to programmatically associate any filename with the book, given that it has the right metadata (which they all do)...

**Comment by openaudible** [comment]
I haven’t been able to reproduce. But once I do I can fix. OA doesn’t just rely on ffprobe for aax meta data. If you import an aax into OA it will correctly get product id and asin. Same with refresh files. 

So I just don’t know the minimum steps to reproduce the problem you’re seeing. (I assume a book that has a blank asin/id). 

You mentioned folders— support for nested folders is not yet working. 

So I think it has to do with the renamed files. 

Assume:
connect, download, rename, quit, delete books.json, launch

variant 1: sync audible library, refresh files
Variant 2: refresh files, then sync with audible

both should correctly have the one downloaded/renamed book in the library with asin. 

And yes programmatically renaming the files is in the works in a development branch. Just much more difficult to migrate the code than expected. 

Anyway, simple steps to reproduce would be appreciated.

**Comment by openaudible** [comment]
Feel free to reopen with any additional details or reports.
