### ISSUE TITLE
Refresh Files does nothing.

### ISSUE THREAD

**Issue by heartburn22** [openaudible/openaudible#986]
I just installed OA on a new computer. I plugged in the external drive that holds the OA library that I created with my old computer. I configured OA to use the library folder on the external drive. I did a full Audible library sync and all of the books had grey icons indicating that they need to be downloaded. When I select "Refresh Files," i see a quick flash of a dialog that disappears too quickly to read, and nothing else happens. Selecting "Import Books" seems to mark them as downloaded and converted, but I think it's actually converting them. It will take a very long time to import nearly 400 books that are already on my machine and in the format that OA put them in. This can't be right.

**Comment by heartburn22** [comment]
I  just noticed that it made a subdirectory under my Audible folder named, "books" and it is copying all of my books from the parent directory into the books directory. I just want it to use the files that I already have. Isn't that what "refresh files" is supposed to do?

**Comment by heartburn22** [comment]
I moved all of the files to the subdirectory and "Refresh Files" seems to work now.

**Comment by heartburn22** [comment]
"Refresh Files" Appeared to work, but it only imported some of the books. I am left to re-download 202 books.

**Comment by openaudible** [comment]
Sorry. All converted audiobooks go in books, all aax files (unconverted) go in the aax directory.

**Comment by heartburn22** [comment]
Yes. I figured that out. But, "Refresh Files" still does nothing. I select it and it offers to import 202 "new" files. I click ok and it goes through each file, slowly, one at a time. After it's done, nothing was added and if I select "Refresh Files" again, it does the same thing. I finally gave up on that and let it download the files. Now  have duplicates of each of the 202 files. The new copies have just the main title in the filename. The old copies have the main title and the subtitle in the filename.

**Comment by heartburn22** [comment]
I was able to sort out the duplicates and get back to a good place. It's hard for me to say if the "Refresh Files" function is working or not. It seems to doing something, but not what I expected. I believe that it has something to do with the filenames. Is it possible that audible, an older version OA is naming the files differently? If that's the case, maybe the filename isn't the best thing to match on. Is it possible to put the AISN in the mp3 header or something? just thinking out loud...

**Comment by heartburn22** [comment]
Starting fresh, I deleted the OA folder in my home directory and deleted the .json file from my library folder. I opened OA and set the library folder to the one on my external drive and turned off automatic downloads. I restarted OA and there was nothing in my library, as expected. I selected  "Refresh Files," waited for it to finish, and all 363 of my books were listed, and they all had green icons. Perfect! 

But, then i did a full audible sync and all of the icons turned grey and the program offered to download 387 books. I did "Refresh Files" again, but nothing changed. I tried doing "Import Books" on one of the files, but it didn't help.

The strange thing is, if I select any book and choose "Show MP3" it opens the folder in Explorer and highlights the correct file.
![OAbug](https://user-images.githubusercontent.com/20681166/182037907-ba6bee22-2dcb-439a-b146-c76ae9427b14.png)

**Comment by heartburn22** [comment]
I tried it one more time from a fresh start, exactly as I described in my last post. Except, this time, I did a Quick Audible sync instead of a full audible sync and everything worked correctly.

**Comment by openaudible** [comment]
We match ASIN (first) then Product ID, and then filename, which are available in the mp3 meta data. 

The logic for whether a book can be downloaded says it should not let you download it if you already have a book in your chosen conversion format (MP3-- make sure your preferences are still set to MP3 output.) Its possible if you're set to M4B, it will need to re-download them before they can be converted, since going from mp3 (lossy) to m4b (audible quality) is not allowed.

If you can get the program to be in that state where it wants you to download 387 books.. send a bug report from the About menu and I'll be able to look at the logs and recreate.
