### ISSUE TITLE
Error downloading: error HTTP/1.1416 Requested Range Not Satisfiable

### ISSUE THREAD

**Issue by spelunkerofbasil** [openaudible/openaudible#989]
About 10% of my titles (for a current total of 55 books) fail to download with the following--
Error downloading: error HTTP/1.1416 Requested Range Not Satisfiable

"![git](https://user-images.githubusercontent.com/11848048/182291126-fe6eb537-19cf-45f1-b0ae-5008a3d49275.png)"

Is this a bug, or is it some dumb thing I'm doing wrong?

**Comment by openaudible** [comment]
Strange. Not a user error. Haven't seen others report it. So maybe something funky with your account.. Quit and restart OA after downloading is done (to remove any temporary download files) and retry.. if it continues, you can send a bug report from the about menu after you see the error again and we can take a look. Also make sure the book(s) are still in your audible library.. and if you want, you can open the internet web browser, go to your library, and click the "Download" button next to your book.

**Comment by spelunkerofbasil** [comment]
Hmmm. Tried to leave a bug report, but got this error: 
![OpenAudible](https://user-images.githubusercontent.com/11848048/182521003-fa772ff8-0072-4e88-9ccd-0c9ef7c33838.png)

Perhaps this is a clue to my original (and continuing) issue?

**Comment by openaudible** [comment]
Good news: your bug was submitted, but just not added to the database correctly.

The correct error should have been: "No space left on device". Check your hard drive for free space! :)  That should solve it.

The bug you found is unrelated.. but is getting fixed--only affects M1 users trying to send a bug report. Thank you for the report!!

In any case, re-open if needed.

**Comment by spelunkerofbasil** [comment]
Thanks so much!

I had  to repartition a drive to make room, but all is working as expected now.

**Comment by estrazio** [comment]
I have the same problem but only with a file! I have a lot of disc space.
