### ISSUE TITLE
Can'tlogin to Audible

### ISSUE THREAD

**Issue by jmays1959** [openaudible/openaudible#993]
Hi,  I have tried to login to Audible several times and it won't let me do so.  I even changed my password twice.   I can login from the app and from the web browser versions,  not from the pop up window your system sends up.   Help

**Comment by openaudible** [comment]
If your audible user name is old and isn't an email, make sure you check that box. Also check the region. 
You should see the password prompt, then a second one with a CAPTCHA, and after that, it should go through and say connected.
If still having problems, you can send a bug report from the About menu.. but it usually just one of the above issues.

**Comment by jmays1959** [comment]
I have done both of those thongs.  When I login to Audible on desktop it does a 2FA , and the pop-up that comes up in your system does not.  Is that the problem?Jeff Mays Get Outlook for Android

**Comment by openaudible** [comment]
Quit, launch OpenAudible, attempt to connect. Then send a bug report from the About menu and list issue 993.
I can take a look.

**Comment by openaudible** [comment]
Yeah, I am at a loss. No other reports suggest this is a bug--maybe just something unique to your set up or Audible account.

Only thing I can think of is to try it on a difference computer and if you can log in on another computer, copy the credentials.json file over from one computer to the other. Sorry.
