### ISSUE TITLE
Feature req (Sort of) I would gladly pay for a license for a 2nd app that can download and convert titles from the plus catalog

### ISSUE THREAD

**Issue by LouBJohnson** [openaudible/openaudible#994]
The description pretty much covers the request. Are there any plans to pursue this kind of thing?

**Comment by openaudible** [comment]
We are trying to focus on backing up user's purchases and keep Audible happy. 

There is an experimental feature you can enable by defining an environment variable oa_ayce=true 

But yes, it is something we are working on.

**Comment by LouBJohnson** [comment]
Thanks!
