### ISSUE TITLE
Directories Preference

### ISSUE THREAD

**Issue by ogapatapata** [openaudible/openaudible#996]
I've set the variable OPENAUDIBLE_HOME and restarted the application but it does not retain the changes and goes back to my Default which is my windows profile. Please advise.

**Comment by openaudible** [comment]
Check under About Menu: Diagnostics and see if is set under Properties.. and also under directories.
You might also check the startup log.
Lastly, you can run from the command line using the debug_linux.sh (or mac.sh or win.bat) in the application directory.. there should be a message during startup if the AUDIBLE_HOME env is set. 
Also, after setting the env variable, you often need to log out and back in of your computer before the setting will be fully set.

**Comment by openaudible** [comment]
Check the above diagnostics. If you have OPENAUDIBLE_HOME properly defined as an environment variable, OpenAudible will attempt to use that and log a message during startup.
