### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by ResonantEcho** [openaudible/openaudible#999]
Please add the ability to download and convert Audible Podcasts.

**Comment by openaudible** [comment]
Good suggestion. It isn't a trivial matter.. a lot of the podcasts are missing meta data.. and the audio format is often in a different format than what we expect. And several other issues come up including where to save them and whether we treat them as "audiobooks". But it is something that is possible, and is on the list of things to work on. No time frame, but perhaps in a beta soonish.

**Comment by openaudible** [comment]
We added a first pass in the beta to download podcasts. They just get lumped in with the books, so it isn't a great solution. You can take a look and let us know if you have any feedback.
https://openaudible.org/beta
Next step would be to create a new "podcasts" directory and save each podcast in its own directory.
Not sure if this feature will make it into the final versions-- it does get a little messy and most people only want to listen to a podcast once.

**Comment by ResonantEcho** [comment]
Thank you, I appreciate you adding the feature.  I did download the beta, but did not see any podcasts listed after completing a full Audible Library Sync.  Is there something else I should be doing?  The Podcast in question is added to my library.  

Just for clarification, Audible has many stories / audio productions in the form of podcasts in episode form.  These are the podcasts that I'm after.  For example, there is a podcast called "The Sea in the Sky" written by Jackson Musker.  It's 11 episodes long.

Thank you!

**Comment by openaudible** [comment]
Go to preferences and enable the "Podcasts" feature. If it wasn't checked, that should fix it when you rescan.

**Comment by JBlond** [comment]
@openaudible in 3.6.3 this feature isn't avaible over the GUI. Can you make it available?
